### ISSUE TITLE
Warning emitted for missing email

### ISSUE THREAD

**Issue by csuhta** [rubygems/rubygems#1291] opened 2015-06-17 01:35 UTC
I have a `Gem::Specification`/`.gemspec` file without an `email` attribute set. [According to the reference, `email` is optional](http://guides.rubygems.org/specification-reference/#email). But a warning is emitted anyway when I use `gem build`:

```
WARNING:  no email specified
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
```

I know I can just ignore the warning and continue, but it these two messages are contradictory. If I am not warned about other optional attributes that are missing, why am I warned about `email`?

```shell
$ gem --version
2.4.8
```

**Comment by djberg96** [comment] 2015-06-17 02:27
I think it's simply a case of "optional, but recommended" which is why you get a warning instead of an error, but not all optional attributes are necessarily recommended. So, not really a contradiction, just a best practices warning.

**Comment by drbrain** [comment] 2015-06-18 00:47
Yes, @djberg96 is correct.

We could look for bug tracker links in metadata and eliminate the email warning if one is found.

**Comment by krainboltgreene** [comment] 2015-12-31 08:59
Frankly I'm OK with this being mandatory.

**Comment by duckinator** [comment] 2016-01-17 05:20
This is behaving as intended, and nobody has responded to @drbrain's idea in the half-year since it was proposed, so I'm closing this issue. If you would like the email warning suppressed when a bug tracker link is specified, as @drbrain mentioned, please feel free to open an issue specifically for that.

**Closed by duckinator** 2016-01-17 05:20 UTC
Labels: category - gem spec, question, triage
