### ISSUE TITLE
`bundle exec <cmd>` gives "command not found" on JRuby+Windows

### ISSUE THREAD

**Issue by slonopotamus** [rubygems/rubygems#3256] opened 2020-01-25 11:32 UTC
1. Windows 10
2. `jruby 9.2.9.0 (2.5.7) 2019-10-30 458ad3e Java HotSpot(TM) 64-Bit Server VM 25.231-b11 on 1.8.0_231-b11 +jit [mswin32-x86_64]` installed via official installer [JRuby 9.2.9.0 Windows Executable (x64)](https://s3.amazonaws.com/jruby.org/downloads/9.2.9.0/jruby_windows_x64_9_2_9_0.exe)
3. Any Ruby project with `Gemfile`, for example [takahashim/epubcheck-ruby](https://github.com/takahashim/epubcheck-ruby)
4. `gem install bundler` (installs bundler-2.1.4 as of today)
5. `bundler install` (installs rake-12.3.3 as of today for given example project)
6. `bundler exec rake`

Expected: default rake target is executed
Actual:
```
bundler: command not found: rake
Install missing gem executables with `bundle install`
```

However, `bundle exec rake test` works!

This problem doesn't reproduce on Linux/MacOS. This problem doesn't reproduce with MRI. This problem happens on all of my Windows machines. Additionally, it [happens on GitHub Actions Windows nodes](https://github.com/slonopotamus/epubcheck-ruby/runs/407575475?check_suite_focus=true#step:5:4), so I believe bug is not caused by my misconfiguration. I do not have any evidence that it works on _any_ Windows machine.

Further testing shows that _any_ `bundle exec <cmd>` fails, however `bundle exec <cmd> <at least one more argument>` works.

I'm not sure whether this is Bundler or JRuby issue.

**Comment by deivid-rodriguez** [comment] 2020-09-11 11:20
We made some fixes to `bundle exec` on Windows. Is this still reproducible on bundler 2.2.0.rc.1?

**Comment by slonopotamus** [comment] 2020-09-14 09:53
Confirming that this problem does *not* reproduce with:

```
$ jruby --version
jruby 9.2.13.0 (2.5.7) 2020-08-03 9a89c94bcc OpenJDK 64-Bit Server VM 14.0.2+12-46 on 14.0.2+12-46 +jit [mswin32-x86_64]

$ bundle --version
Bundler version 2.2.0.rc.1
```

However, now each `bundle` invocation logs a warning:

```
2020-09-14T12:39:30.600+03:00 [main] WARN FilenoUtil : Native subprocess control requires open access to the JDK IO subsystem
Pass '--add-opens java.base/sun.nio.ch=org.jruby.dist --add-opens java.base/java.io=org.jruby.dist' to enable.
```

Should I report a separate issue for this? At the best, the warning should not be there and things would automatically work. At the worst, warning message needs to be improved because it isn't clear where and what exactly I need to add.

**Comment by deivid-rodriguez** [comment] 2020-09-14 11:45
Great! I'm going to close this ticket then, thanks for trying out!

Regarding the warning, yeah, I think that shouldn't be there, but it sounds like not an issue in bundler/rubygems but something that should be reported to jruby.

**Comment by eregon** [comment] 2021-06-20 17:08
This seems to be an issue again: https://github.com/jruby/jruby/issues/6053#issuecomment-864584117

**Comment by headius** [comment] 2021-06-29 15:59
This could not be reproduced using current JRuby 9.2.19.0 zip file and latest bundler.

https://github.com/jruby/jruby/issues/6053#issuecomment-870717926

**Comment by dentarg** [comment] 2021-07-05 08:53
https://github.com/jruby/jruby/issues/6053#issuecomment-871703681 seems to have some good information about this issue

**Comment by deivid-rodriguez** [comment] 2021-07-05 17:30
After closer investigation, there's chances that this is a jruby issue. Since the issue was reported as fixed on jruby 9.2.13.0, it might be worth double checking whether it's really fixed there, and if that's the case, which one is the first intermediate release between 9.2.13.0 and 9.2.19.0 that suffers from the issue again.

**Comment by deivid-rodriguez** [comment] 2021-07-06 09:12
Since my current investigation points to a problem in JRuby, for now I'm closing this in favour of https://github.com/jruby/jruby/issues/6745.

**Closed by deivid-rodriguez** 2021-07-06 09:12 UTC
Labels: Bundler, platform: windows, status: feedback required

**Comment by Aksandrsmirnov** [comment] 2022-08-20 21:00
> 1. Windows 10
> 2. `jruby 9.2.9.0 (2.5.7) 2019-10-30 458ad3e Java HotSpot(TM) 64-Bit Server VM 25.231-b11 on 1.8.0_231-b11 +jit [mswin32-x86_64]` устанавливается через официальный установщик [JRuby 9.2.9.0 Windows Executable (x64)](https://s3.amazonaws.com/jruby.org/downloads/9.2.9.0/jruby_windows_x64_9_2_9_0.exe)
> 3. Любой проект Ruby с`Gemfile`, например[, takahashim / epubcheck-ruby](https://github.com/takahashim/epubcheck-ruby)
> 4. `gem install bundler` (устанавливает bundler-2.1.4 по состоянию на сегодняшний день)
> 5. `bundler install` (устанавливает rake-12.3.3 на сегодняшний день для данного примера проекта)
> 6. `bundler exec rake`
> 
> Ожидаемый: цель рейка по умолчанию выполняется фактически:
> 
> ```
> bundler: command not found: rake
> Install missing gem executables with `bundle install`
> ```
> 
> Тем не менее, `bundle exec rake test`работает!
> 
> Эта проблема не воспроизводится в Linux / macOS. Эта проблема не воспроизводится при МРТ. Эта проблема возникает на всех моих компьютерах с Windows. Кроме того, это [происходит на узлах Windows GitHub Actions](https://github.com/slonopotamus/epubcheck-ruby/runs/407575475?check_suite_focus=true#step:5:4), поэтому я считаю, что ошибка не вызвана моей неправильной настройкой. У меня нет никаких доказательств того, что он работает на _любом_ компьютере с Windows.
> 
> Дальнейшее тестирование показывает, что _любое_ `bundle exec <cmd>` из них терпит неудачу, однако `bundle exec <cmd> <at least one more argument>`работает.
> 
> Я не уверен, является ли это проблемой Bundler или JRuby.

> 
![IMG-20220815-WA0008](https://user-images.githubusercontent.com/98289100/185765862-526b68d6-eca6-48b7-951a-e0fc028fb5c8.jpg)
