### ISSUE TITLE
"rake release" has invisible prompt for OTP code

### ISSUE THREAD

**Issue by svoop** [rubygems/rubygems#2774] opened 2019-05-22 19:56 UTC
When OTP (multi-factor authentication) is enabled, `rake publish` hangs after printing `Pushed git commits and tags`.

Pasting the current OTP code (in the following example "351080") get's things rolling again to an ultimately successful release:

```
$ rake release
aixm 0.3.6 built to pkg/aixm-0.3.6.gem.
Tagged v0.3.6.
Pushed git commits and tags.
351080
Pushed aixm 0.3.6 to rubygems.org
```

If the release fails at the hanging point, it will eventually raise an error:

```
rake aborted!
Pushing gem to https://rubygems.org...
You have enabled multi-factor authentication. Please enter OTP code.
Code:
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>502 Bad Gateway</title>
  </head>
  <body>
    <h1>Error 502 Bad Gateway</h1>
    <p>Bad Gateway</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-cdg20754-CDG 1558554084 3178316924</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
/Users/test/.gem/ruby/2.6.3/gems/bundler-2.0.1/lib/bundler/gem_helper.rb:177:in `sh'
/Users/test/.gem/ruby/2.6.3/gems/bundler-2.0.1/lib/bundler/gem_helper.rb:102:in `rubygem_push'
/Users/test/.gem/ruby/2.6.3/gems/bundler-2.0.1/lib/bundler/gem_helper.rb:69:in `block in install'
/Users/test/.gem/ruby/2.6.3/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `load'
/Users/test/.gem/ruby/2.6.3/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/test/.gem/ruby/2.6.3/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:28:in `run'
/Users/test/.gem/ruby/2.6.3/gems/bundler-2.0.1/lib/bundler/cli.rb:463:in `exec'
/Users/test/.gem/ruby/2.6.3/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/test/.gem/ruby/2.6.3/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/test/.gem/ruby/2.6.3/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/test/.gem/ruby/2.6.3/gems/bundler-2.0.1/lib/bundler/cli.rb:27:in `dispatch'
/Users/test/.gem/ruby/2.6.3/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/test/.gem/ruby/2.6.3/gems/bundler-2.0.1/lib/bundler/cli.rb:18:in `start'
/Users/test/.gem/ruby/2.6.3/gems/bundler-2.0.1/exe/bundle:30:in `block in <top (required)>'
/Users/test/.gem/ruby/2.6.3/gems/bundler-2.0.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Users/test/.gem/ruby/2.6.3/gems/bundler-2.0.1/exe/bundle:22:in `<top (required)>'
/Users/test/.gem/ruby/2.6.3/bin/bundle:23:in `load'
/Users/test/.gem/ruby/2.6.3/bin/bundle:23:in `<main>'
```

Looks like the OTP prompt is there after all but not visible – at least not on MacOS 10.14.5 with iTerm2 3.2.8.

```
$ gem env version
3.0.3
```

**Comment by bronzdoc** [comment] 2019-05-25 15:38
@svoop thanks for reporting this, i was able to reproduce it.

I will look into it.

**Comment by deivid-rodriguez** [comment] 2019-05-26 11:50
I think this is a duplicate of https://github.com/bundler/bundler/issues/6854.

**Closed** 2019-05-28 22:32 UTC
Labels: type: bug report
