### ISSUE TITLE
`gem install bundler` could render the default bundler executables unusable

### ISSUE THREAD

**Issue by rafaelfranca** [rubygems/rubygems#5098] opened 2021-11-25 22:44 UTC
### Describe the problem as clearly as you can

Bundler is failing to execute commands with Ruby 3.0.3 and Bundler 2.2.32

https://github.com/rails/spring/runs/4328629672?check_suite_focus=true

But it passes with Ruby 3.0.2 and same version of Bundler

https://github.com/rails/spring/runs/4328604987?check_suite_focus=true

### Did you try upgrading rubygems & bundler?

Yes, those are the newest versions

### Which command did you run?

`bundle check` is failing

**Comment by deivid-rodriguez** [comment] 2021-11-26 08:59
Thanks for reporting @rafaelfranca, this is a bit puzzling. I think it's related to the fact that ruby 3.0.3 comes with bundler 2.2.32 as a default gem, but at the same time the `ruby/setup-ruby` github action installs bundler 2.2.32 as a regular gem. I'll keep digging.

**Comment by deivid-rodriguez** [comment] 2021-11-26 09:05
Yay, I managed to reproduce locally following that idea.

**Comment by deivid-rodriguez** [comment] 2021-11-26 10:00
Ok, so now I understand the issue.

First, just noting that this is not a regression in bundler 2.2.32 nor in ruby 3.0.3. It's an issue that has existed for a long time, but that's only manifested when you install as a regular gem the same bundler version that comes with ruby by default. For example, in ruby 3.0.2 this can be reproduced by installing bundler 2.2.22 as a regular gem, since that's the version that comes by default there.

Second, why does this happen?

Say you have the following (like in ruby 3.0.3)

```
$ gem list bundler
bundler (default: 2.2.32)
```

This means bundler 2.2.32 is bundled with ruby's stdlib and when you use it, it gets activated as a gem. To achieve that, ruby installation layout comes with a default gem specification at `<ruby_prefix>/lib/ruby/gems/3.0.0/specifications/default/bundler-2.2.32.gemspec`, and bundler executables at `<ruby_prefix>/lib/ruby/gems/3.0.0/gems/rubygems-update-3.2.28/bundler/libexec/bundle`. The gemspec includes a `s.bindir = "libexec"` directive, so that the executables can be found.

Note that the above layout differs from what rubygems installs when you run `gem update --system`, since the path for executables for the upstream bundler gem is "exe", not "libexec". That means that when you run `gem install bundler`, the path for bundler's exectuable is overwriten and will now be `<ruby_prefix>/lib/ruby/gems/3.0.0/gems/rubygems-update-3.2.28/bundler/exe/bundle`.

That means that the "libexec" folder pointed to by the default bundler gemspec no longer exists, and that when spring tests run bundler commands in an isolated location (with custom GEM_PATH and GEM_HOME), the default bundler gem can no longer find bundler executables.

As per how to fix this, I can see several options.

* One is to move forward with https://github.com/rubygems/rubygems/pull/2909, which proposes to use a different (but standard) layout for default gems, so that there won't be any more interferences like this. This is my preferred approach, but the one that involves the most work.
* Sync executables folder between ruby-core and upstream. I think ruby-core uses `libexec` because it uses `exe` for placing actual binaries and it's not even source controlled, so I'm not sure whether it's viable that ruby-core switches to `exe`. Ruby-core could also change the gemspec folder on the fly someone to be "exe" during "make install", but it doesn't seem a great idea. We could also move upstream executables folder to be "libexec". I don't think this would pose issues but feels weird.
* Finally, we could make `gem install bundler` be a noop if the selected version is already installed as a default gem.

The latter seems the easiest thing to do to me, not sure what others think.

Also note that:

* Issue will automatically disappear once we release a new version of bundler. Because `gem install bundler` will no longer install the same version that comes with ruby by default., but a higher one and thus it will not mess with its executable folder. But the issue will still be there, hidden, waiting for another time to come up :imp:.

**Comment by rafaelfranca** [comment] 2021-11-26 18:39
Thank you for the investigation. I thought it had to with ruby setup-ruby installing the same version of bundler, but i think this issue is confusing enough to justify a fix in Ruby or Rubygems, maybe making the install no-op would be enough.

**Comment by deivid-rodriguez** [comment] 2021-11-26 18:45
Yeah, definitely. I will try to implement that.

**Comment by voxik** [comment] 2021-12-10 13:30
Unfortunately, I am not convinced that #2909 would help here. Although it would possibly allow to have the bundled gems in the RubyGems directory structure instead of being scattered all around the place.

Please note that there used to similar issues such as https://bugs.ruby-lang.org/issues/5060

**Comment by deivid-rodriguez** [comment] 2021-12-10 13:33
Since default gems would have their own home, they would never be overwritten by regular gems. I think it would fix this issue.

**Comment by voxik** [comment] 2021-12-10 13:57
Actually, you are right. The "executable" confused me, but the "executable" itself in `bin` dir would be still the same and the collision is on the .gemspec level.

**Comment by deivid-rodriguez** [comment] 2024-10-30 14:46
In the end, this was fixed by https://github.com/ruby/ruby/pull/9165.

My other approach at #5125 didn't work, so I'll close it since the current way is working fine other than this issue.

**Closed by deivid-rodriguez** 2024-10-30 14:46 UTC
Labels: Bundler
