### ISSUE TITLE
Bundler error with rubygems

### ISSUE THREAD

**Issue by release-fk** [rubygems/rubygems#5494] opened 2022-04-24 17:24 UTC
Bundler exiting with non zero code exception

Gem::RemoteFetcher::FetchError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate rejected) (https://oregon.production.s3.rubygems.org.s3-us-west-2.amazonaws.com/gems/rack-1.6.13.gem)

**Comment by sonalkr132** [comment] 2022-04-24 17:47
Hi. can you please share the command you ran, Gemfile and output of bundle env?

**Comment by release-fk** [comment] 2022-04-24 20:19
[eb-activity.log](https://github.com/rubygems/rubygems/files/8550438/eb-activity.log)

**Comment by aldent95** [comment] 2022-04-24 21:45
Same issue here.

Looks like some sort of SSL issue.
https://oregon.production.s3.rubygems.org.s3-us-west-2.amazonaws.com/gems/semantic_range-3.0.0.gem
![image](https://user-images.githubusercontent.com/8398954/164997942-4ddc95b4-693f-45d6-9cac-e6882295e083.png)

**Comment by WilliamDenniss** [comment] 2022-04-25 00:26
Same issue.

> Retrying download gem from http://rubygems.org/ due to error (2/4): Gem::RemoteFetcher::FetchError SSL_connect returned=1 errno=0 peeraddr=52.218.180.209:443 state=error: certificate verify failed (Hostname mismatch) (https://oregon.production.s3.rubygems.org.s3-us-west-2.amazonaws.com/gems/nio4r-2.5.8.gem)

My browser has the same issue when visiting https://oregon.production.s3.rubygems.org.s3-us-west-2.amazonaws.com/gems/nio4r-2.5.8.gem

`bundle install` will work on the same Gemfile when SSL verification is disabled via 
```
echo ":ssl_verify_mode: 0" > ~/.gemrc
```

**Comment by gtd** [comment] 2022-04-25 01:28
I can confirm this problem started in the last week or so.  I ran a `bundle install` that worked on Wednesday.  I uninstalled one gem from the bundle on the same server which hasn't been touched and now I get this error.  Looks like a problem with the bucket name since wildcard certs don't cover nested subdomains, if you use the bucket name as first segment of the path instead of as subdomain then there is no SSL error.  Eg. https://s3-us-west-2.amazonaws.com/oregon.production.s3.rubygems.org/gems/nio4r-2.5.8.gem

**Comment by aldent95** [comment] 2022-04-25 01:38
> I can confirm this problem started in the last week or so. I ran a `bundle install` that worked on Wednesday. I uninstalled one gem from the bundle on the same server which hasn't been touched and now I get this error. Looks like a problem with the bucket name since wildcard certs don't cover nested subdomains, if you use the bucket name as first segment of the path instead of as subdomain then there is no SSL error. Eg. https://s3-us-west-2.amazonaws.com/oregon.production.s3.rubygems.org/gems/nio4r-2.5.8.gem

It's been within the last 24 hours I think. I was running builds fine last night (GMT+12) but today it was broken.

**Comment by sonalkr132** [comment] 2022-04-25 02:15
Hi, we have deployed a fix for this. Can you please confirm that issue was resolved? Also, please confirm that you are using "http://rubygems.org" as source (not https).

**Comment by aldent95** [comment] 2022-04-25 03:11
@sonalkr132 Yep, working for me again now, cheers!

**Comment by appsan** [comment] 2022-04-25 03:22
Same for us, thank you @sonalkr132!

**Comment by release-fk** [comment] 2022-04-25 03:23
Same for us Thanks you @sonalkr132

**Closed** 2022-04-26 14:40 UTC

**Comment by sonalkr132** [comment] 2022-06-05 13:24
Hi, we have renabled the change which led to this issue. This time we have ensured that we handle oregon.production.s3.rubygems.org.s3-us-west-2.amazonaws.com correctly. Please let us know if you face any issues.

FYI, you would have hit this issue only if you had "http" source in your Gemfile. Updating that to https is good practice in general.
