### ISSUE TITLE
gem install fpm error

### ISSUE THREAD

**Issue by zxlzh2015** [rubygems/rubygems#1426] opened 2015-12-26 03:46 UTC
```
gem install fpm
Error fetching data: Errno::ETIMEDOUT: Operation timed out - connect(2)
```

Verbose install:

```
root@cloudify-VirtualBox:/home/cloudify# gem install fpm -V
GET https://ruby.taobao.org/latest_specs.4.8.gz
302 Moved Temporarily
GET https://rubygems-china.oss-cn-hangzhou.aliyuncs.com/latest_specs.4.8.gz
200 OK
GET https://ruby.taobao.org/specs.4.8.gz
302 Moved Temporarily
GET https://rubygems-china.oss-cn-hangzhou.aliyuncs.com/specs.4.8.gz
200 OK
Installing gem json-1.8.3
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/test_json.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/test_json_addition.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/test_json_encoding.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/test_json_fixtures.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/test_json_generate.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/test_json_generic_object.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/test_json_string_matching.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/test_json_unicode.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/.gitignore
/var/lib/gems/1.9.1/gems/json-1.8.3/.travis.yml
/var/lib/gems/1.9.1/gems/json-1.8.3/CHANGES
/var/lib/gems/1.9.1/gems/json-1.8.3/COPYING
/var/lib/gems/1.9.1/gems/json-1.8.3/COPYING-json-jruby
/var/lib/gems/1.9.1/gems/json-1.8.3/GPL
/var/lib/gems/1.9.1/gems/json-1.8.3/Gemfile
/var/lib/gems/1.9.1/gems/json-1.8.3/README-json-jruby.markdown
/var/lib/gems/1.9.1/gems/json-1.8.3/README.rdoc
/var/lib/gems/1.9.1/gems/json-1.8.3/Rakefile
/var/lib/gems/1.9.1/gems/json-1.8.3/TODO
/var/lib/gems/1.9.1/gems/json-1.8.3/VERSION
/var/lib/gems/1.9.1/gems/json-1.8.3/data/example.json
/var/lib/gems/1.9.1/gems/json-1.8.3/data/index.html
/var/lib/gems/1.9.1/gems/json-1.8.3/data/prototype.js
/var/lib/gems/1.9.1/gems/json-1.8.3/diagrams/.keep
/var/lib/gems/1.9.1/gems/json-1.8.3/ext/json/ext/fbuffer/fbuffer.h
/var/lib/gems/1.9.1/gems/json-1.8.3/ext/json/ext/generator/depend
/var/lib/gems/1.9.1/gems/json-1.8.3/ext/json/ext/generator/extconf.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/ext/json/ext/generator/generator.c
/var/lib/gems/1.9.1/gems/json-1.8.3/ext/json/ext/generator/generator.h
/var/lib/gems/1.9.1/gems/json-1.8.3/ext/json/ext/parser/depend
/var/lib/gems/1.9.1/gems/json-1.8.3/ext/json/ext/parser/extconf.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/ext/json/ext/parser/parser.c
/var/lib/gems/1.9.1/gems/json-1.8.3/ext/json/ext/parser/parser.h
/var/lib/gems/1.9.1/gems/json-1.8.3/ext/json/ext/parser/parser.rl
/var/lib/gems/1.9.1/gems/json-1.8.3/ext/json/extconf.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/install.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/java/src/json/ext/ByteListTranscoder.java
/var/lib/gems/1.9.1/gems/json-1.8.3/java/src/json/ext/Generator.java
/var/lib/gems/1.9.1/gems/json-1.8.3/java/src/json/ext/GeneratorMethods.java
/var/lib/gems/1.9.1/gems/json-1.8.3/java/src/json/ext/GeneratorService.java
/var/lib/gems/1.9.1/gems/json-1.8.3/java/src/json/ext/GeneratorState.java
/var/lib/gems/1.9.1/gems/json-1.8.3/java/src/json/ext/OptionsReader.java
/var/lib/gems/1.9.1/gems/json-1.8.3/java/src/json/ext/Parser.java
/var/lib/gems/1.9.1/gems/json-1.8.3/java/src/json/ext/Parser.rl
/var/lib/gems/1.9.1/gems/json-1.8.3/java/src/json/ext/ParserService.java
/var/lib/gems/1.9.1/gems/json-1.8.3/java/src/json/ext/RuntimeInfo.java
/var/lib/gems/1.9.1/gems/json-1.8.3/java/src/json/ext/StringDecoder.java
/var/lib/gems/1.9.1/gems/json-1.8.3/java/src/json/ext/StringEncoder.java
/var/lib/gems/1.9.1/gems/json-1.8.3/java/src/json/ext/Utils.java
/var/lib/gems/1.9.1/gems/json-1.8.3/json-java.gemspec
/var/lib/gems/1.9.1/gems/json-1.8.3/json.gemspec
/var/lib/gems/1.9.1/gems/json-1.8.3/json_pure.gemspec
/var/lib/gems/1.9.1/gems/json-1.8.3/lib/json.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/lib/json/add/bigdecimal.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/lib/json/add/complex.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/lib/json/add/core.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/lib/json/add/date.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/lib/json/add/date_time.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/lib/json/add/exception.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/lib/json/add/ostruct.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/lib/json/add/range.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/lib/json/add/rational.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/lib/json/add/regexp.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/lib/json/add/struct.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/lib/json/add/symbol.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/lib/json/add/time.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/lib/json/common.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/lib/json/ext.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/lib/json/ext/.keep
/var/lib/gems/1.9.1/gems/json-1.8.3/lib/json/generic_object.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/lib/json/pure.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/lib/json/pure/generator.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/lib/json/pure/parser.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/lib/json/version.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/fail1.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/fail10.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/fail11.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/fail12.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/fail13.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/fail14.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/fail18.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/fail19.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/fail2.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/fail20.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/fail21.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/fail22.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/fail23.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/fail24.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/fail25.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/fail27.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/fail28.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/fail3.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/fail4.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/fail5.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/fail6.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/fail7.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/fail8.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/fail9.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/pass1.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/pass15.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/pass16.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/pass17.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/pass2.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/pass26.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/fixtures/pass3.json
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/setup_variant.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/test_json.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/test_json_addition.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/test_json_encoding.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/test_json_fixtures.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/test_json_generate.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/test_json_generic_object.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/test_json_string_matching.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/tests/test_json_unicode.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/tools/fuzz.rb
/var/lib/gems/1.9.1/gems/json-1.8.3/tools/server.rb
Building native extensions. This could take a while...
ERROR: Error installing fpm:
ERROR: Failed to build gem native extension.

/usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in require': cannot load such file -- mkmf (LoadError) from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:inrequire'
from extconf.rb:1:in `

'
Gem files will remain installed in /var/lib/gems/1.9.1/gems/json-1.8.3 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/json-1.8.3/ext/json/ext/generator/gem_make.out
```

**Comment by krainboltgreene** [comment] 2015-12-30 03:12
Looks like it might be solved here: http://stackoverflow.com/questions/7645918/require-no-such-file-to-load-mkmf-loaderror

**Comment by bronzdoc** [comment] 2016-05-18 18:37
Can't reproduce closing

**Closed by bronzdoc** 2016-05-18 18:37 UTC
Labels: category - install, question
