### ISSUE TITLE
rubygems/core_ext/kernel_require.rb can exit without releasing RUBYGEMS_ACTIVATION_MONITOR

### ISSUE THREAD

**Issue by ko1** [rubygems/rubygems#1901] opened 2017-04-20 15:15 UTC
I'm using Ruby trunk <https://github.com/ruby/ruby/> and I got a problem on testing Ruby interpreter itself with  `make test-all TESTS=-j8` on my several machines. This test option `TESTS=-j8` running tests with multiple processes and sometimes it sleeps forever.

After exploration about this issue, I got that `RUBYGEMS_ACTIVATION_MONITOR` is not released correctly. 

https://github.com/rubygems/rubygems/blob/master/lib/rubygems/core_ext/kernel_require.rb#L46
`Kernel.send(:gem, spec.name)` cause Exception (`Gem::MissingSpecError` for my case) and it return without releasing `RUBYGEMS_ACTIVATION_MONITOR`. So that other threads try to require anything, this `require` method stops forever.

To avoid this issue, I introduced a patch <https://svn.ruby-lang.org/cgi-bin/viewvc.cgi?view=revision&revision=58419> to release when any exceptions are raised.

I'm not sure this fix is correct or not. But at least my environment the problem is fixed.

Memo:

* Generally speaking, using `Monitor#enter, #exit` is bad pattern. You need to use `Monitor#synchronize` with block. This replaced `require` method is very complex and easy to introduce such problems.
* I got `Gem::MissingSpecError` with requiring `webrick`, one of the default gem. I removed installdir/.../default/webrick...spec and I don't have same issue. So that it is possible to have a problem around default gems.

Thanks,
Koichi

**Comment by ko1** [comment] 2017-04-20 15:21
BTW this issue I find just after the commit <https://svn.ruby-lang.org/cgi-bin/viewvc.cgi?view=revision&revision=58403>. After this change, running Ruby's tests with parallel options stops forever (and kill forcefully).

**Comment by segiddins** [comment] 2017-04-20 17:40
Out of curiousity, what file is `require` failing on and what is the output of `gem env`?

**Comment by segiddins** [comment] 2017-04-20 17:44
Also, what is the value for `Gem::Specification.stubs_for("webrick").first.full_name`?

**Comment by ko1** [comment] 2017-04-20 22:40
```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.11
  - RUBY VERSION: 2.5.0 (2017-04-21 patchlevel -1) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/ko1/ruby/install/trunk/lib/ruby/gems/2.5.0
  - USER INSTALLATION DIRECTORY: /home/ko1/.gem/ruby/2.5.0
  - RUBY EXECUTABLE: /home/ko1/ruby/install/trunk/bin/ruby
  - EXECUTABLE DIRECTORY: /home/ko1/ruby/install/trunk/bin
  - SPEC CACHE DIRECTORY: /home/ko1/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/ko1/ruby/install/trunk/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/ko1/ruby/install/trunk/lib/ruby/gems/2.5.0
     - /home/ko1/.gem/ruby/2.5.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/ko1/ruby/install/trunk/bin
     - ~/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
```

```
$ ruby -ve 'p Gem::Specification.stubs_for("webrick").first.full_name'
ruby 2.5.0dev (2017-04-21 trunk 58420) [x86_64-linux]
"webrick-0.0.1"
```

**Comment by hsbt** [comment] 2017-04-21 00:29
It's related gemification issue, maybe.

**Comment by segiddins** [comment] 2017-04-21 02:51
I can't reproduce this on OS X

**Comment by ko1** [comment] 2017-04-24 10:58
> I can't reproduce this on OS X

Welcome to non-deterministic world!
This is one of difficulty of multi-thread programming.

**Comment by hsbt** [comment] 2017-05-02 01:19
It's already committed ruby core repository. 

https://github.com/ruby/ruby/commit/1721dfa0ea963a85d4ac1e3415eb18ef427d4d36

We have no reason to reject this request.

**Comment by indirect** [comment] 2017-05-02 01:31
@hsbt @ko1 could one of you submit a pull request to backport the change from core to this repo? I would like to try to keep them in sync. 🙇

**Comment by segiddins** [comment] 2017-05-03 15:54
I'm hesitant to accept fixes without accompanying test coverage, that's very likely to lead to regressions

**Comment by hsbt** [comment] 2017-11-30 08:17
I merged https://svn.ruby-lang.org/cgi-bin/viewvc.cgi?view=revision&revision=58419 to RG 2.7

**Closed by hsbt** 2017-11-30 08:17 UTC
