### ISSUE TITLE
sources are not prioritized (in contradiction to documentation)

### ISSUE THREAD

**Issue by ToadJamb** [rubygems/rubygems#3502] opened 2020-04-08 20:29 UTC
Thank you for contributing to the [rubygems](https://github.com/rubygems/rubygems) repository, and specifically to the [Bundler](https://bundler.io/) gem.

Before processing your issue please confirm that:

- [x] You checked all the following documents and couldn't find a solution for your issue:

- [Troubleshooting common issues](https://github.com/rubygems/bundler/blob/master/doc/TROUBLESHOOTING.md)
- [Bundler documentation site](https://bundler.io/)
- [Bundler man pages](https://bundler.io/man/bundle.1.html)
- [Bundler command line reference](https://bundler.io/v2.0/commands.html)

If you haven't done that, please do it before creating a new issue.

Please answer the following questions so we can process your issue as fast as possible:

1. Do you have a reproduction script? It would be really helpful for us if you provide one. Examples: [Sample repro script for Bundler issues](https://gist.github.com/xaviershay/6207550), [Another sample repro script for Bundler issues](https://gist.github.com/xaviershay/6295889).

    Script URL: 

2. What are you trying to accomplish?

    Your answer: Use multiple sources in my Gemfile

3. What command did you run?

    Your answer: bundle install

4. What were you expecting to happen?

    Your answer: I expected sources to be prioritized per the documentation.

5. What actually happened?

    Your answer: Bundler pulls from rubygems (instead of a private server) regardless of the order of the sources in the Gemfile. This is not an authentication issue, as any (and all) other gems that are exclusively on the private server are fetched with no problem.

6. Is there an exception backtrace? If so, please copy it below.

    Your answer: No.

7. Please run `bundle env` and paste the output below:

    Your answer:

For more information please check [Filing Issues: a guide](https://github.com/rubygems/rubygems/blob/master/bundler/doc/contributing/ISSUES.md).

Thank you!

**Comment by emptyflask** [comment] 2020-07-15 15:47
This should get more attention -- since I added a private source for sidekiq-pro (using `source: ...`), bundler tries to pull all my gems from it before falling back to rubygems.org.

Is there any reason why using a `source` argument on a single gem would add it to the global sources? This seems like a bug, despite it being mentioned in the docs.

**Comment by colby-swandale** [comment] 2020-07-17 13:07
@emptyflask Can you please share a minimal Gemfile that we can use to test/debug this issue

**Comment by deivid-rodriguez** [comment] 2020-09-03 20:00
We haven't received any further feedback or a way to reproduce this issue, so I'll close this for now.

**Closed by deivid-rodriguez** 2020-09-03 20:00 UTC
Labels: Bundler, status: user feedback required
