### ISSUE TITLE
Bundler failing to load a default gem

### ISSUE THREAD

**Issue by darix** [rubygems/rubygems#8008] opened 2024-09-06 10:06 UTC
### Describe the problem as clearly as you can

I have an rpm package for discourse. Our rpm package resolver sees "oh latest net-http is already part of the ruby3.3 core package i do not need to pull an extra package." During the package upgrade it runs rake tasks which started failing after my recent package update:

```
LoadError: cannot load such file -- /usr/lib64/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/https.rb (LoadError)
<internal:/usr/lib64/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/usr/lib64/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/srv/www/vhosts/discourse/config/application.rb:69:in `<top (required)>'
/srv/www/vhosts/discourse/Rakefile:7:in `<top (required)>'
/usr/bin/rake.ruby3.3:25:in `load'
/usr/bin/rake.ruby3.3:25:in `<top (required)>'
/usr/bin/bundler.ruby3.3-2.5.5:25:in `load'
/usr/bin/bundler.ruby3.3-2.5.5:25:in `<main>'
(See full trace by running task with --trace)
```

https://github.com/discourse/discourse/blob/main/config/application.rb#L69

The net-http files are in

```
rpm -ql ruby3.3 | rg '(net/http|net-http-0.4)' | grep -v vendor
/usr/lib64/ruby/3.3.0/net/http
/usr/lib64/ruby/3.3.0/net/http.rb
/usr/lib64/ruby/3.3.0/net/http/backward.rb
/usr/lib64/ruby/3.3.0/net/http/exceptions.rb
/usr/lib64/ruby/3.3.0/net/http/generic_request.rb
/usr/lib64/ruby/3.3.0/net/http/header.rb
/usr/lib64/ruby/3.3.0/net/http/proxy_delta.rb
/usr/lib64/ruby/3.3.0/net/http/request.rb
/usr/lib64/ruby/3.3.0/net/http/requests.rb
/usr/lib64/ruby/3.3.0/net/http/response.rb
/usr/lib64/ruby/3.3.0/net/http/responses.rb
/usr/lib64/ruby/3.3.0/net/http/status.rb
/usr/lib64/ruby/3.3.0/net/https.rb
/usr/lib64/ruby/gems/3.3.0/gems/net-http-0.4.1
/usr/lib64/ruby/gems/3.3.0/specifications/default/net-http-0.4.1.gemspec
```

Loading 'net/https' in general works fine:

```
pry
[1] pry(main)> require 'net/https'
=> true
[2] pry(main)> 
```

So why does bundler insist on loading files from `/usr/lib64/ruby/gems/3.3.0/gems/net-http-0.4.1`?

**Comment by deivid-rodriguez** [comment] 2024-09-06 10:57
If a gem is specified in your Gemfile, Bundler prefers installing it as a regular gem over using the default gem copy. But when Bundler loads gems, it should still fallback to default gems if the gem is not installed as a regular gem.

What does `gem list net-http` output? Which command are you running?

**Comment by deivid-rodriguez** [comment] 2024-09-06 11:12
Also it's unclear to me which version of Bundler you are using. Could you post `bundle env` details too?

**Comment by darix** [comment] 2024-09-06 11:25
on the discourse machine

```
gem list net-http

*** LOCAL GEMS ***

net-http (default: 0.4.1 ruby)
```

on the machine where i tested pry:

```
gem list net-http

*** LOCAL GEMS ***

net-http (default: 0.4.1)
```

bundler is the one that ships with the latest ruby 3.3


bundler env
## Environment

```
Bundler       2.5.5
  Platforms   ruby, x86_64-linux-gnu
Ruby          3.3.5p100 (2024-09-03 revision ef084cc8f4958c1b6e4ead99136631bef6d8ddba) [x86_64-linux-gnu]
  Full Path   /usr/bin/ruby.ruby3.3
  Config Dir  /etc
RubyGems      3.5.16
  Gem Home    /usr/lib64/ruby/gems/3.3.0
  Gem Path    /root/.local/share/gem/ruby/3.3.0:/usr/lib64/ruby/gems/3.3.0
  User Home   /root
  User Path   /root/.local/share/gem/ruby/3.3.0
  Bin Dir     /usr/bin
Tools         
  Git         2.46.0
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-01-18
Git SHA           2efa8cec93
Released Version  true
```

**Comment by deivid-rodriguez** [comment] 2024-09-06 11:30
Ok, so next thing I'd suggest to try would be to check whether this also reproduces with the latest version of Bundler and RubyGems.

**Comment by darix** [comment] 2024-09-06 11:33
the 2.5.16 that is part of ruby 3.3 is shadowed by an old gem

**Comment by darix** [comment] 2024-09-06 13:17
looks like 2.5.16 already fixed the issue. now updating my package to .18

**Comment by darix** [comment] 2024-09-10 05:27
ok i was too early with claiming it is solved. i can reproduce the error with 2.5.18:

## Environment

```
Bundler       2.5.18
  Platforms   ruby, x86_64-linux-gnu
Ruby          3.3.5p100 (2024-09-03 revision ef084cc8f4958c1b6e4ead99136631bef6d8ddba) [x86_64-linux-gnu]
  Full Path   /usr/bin/ruby.ruby3.3
  Config Dir  /etc
RubyGems      3.5.16
  Gem Home    /usr/lib64/ruby/gems/3.3.0
  Gem Path    /root/.local/share/gem/ruby/3.3.0:/usr/lib64/ruby/gems/3.3.0
  User Home   /root
  User Path   /root/.local/share/gem/ruby/3.3.0
  Bin Dir     /usr/bin
Tools
  Git         2.46.0
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-08-26
Git SHA           c218aab519
Released Version  true
```

gitlab-ce puma startup ( `/usr/bin/bundle.ruby3.3 exec /usr/bin/puma.ruby3.3 --env production --config /srv/www/vhosts/gitlab-ce/config/puma.rb` )

```
/usr/lib64/ruby/3.3.0/bundled_gems.rb:75:in `require': cannot load such file -- /usr/lib64/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/https.rb (LoadError)
        from /usr/lib64/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
        from /usr/lib64/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /usr/lib64/ruby/gems/3.3.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:4:in `<main>'
        from /usr/lib64/ruby/gems/3.3.0/gems/faraday-net_http-1.0.1/lib/faraday/net_http.rb:3:in `require_relative'
        from /usr/lib64/ruby/gems/3.3.0/gems/faraday-net_http-1.0.1/lib/faraday/net_http.rb:3:in `<main>'
        from /usr/lib64/ruby/3.3.0/bundled_gems.rb:75:in `require'
        from /usr/lib64/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
        from /usr/lib64/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /usr/lib64/ruby/gems/3.3.0/gems/faraday-1.10.3/lib/faraday.rb:42:in `<main>'
        from <internal:/usr/lib64/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/usr/lib64/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /usr/lib64/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
        from /usr/lib64/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /usr/lib64/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/runtime.rb:55:in `each'
        from /usr/lib64/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/runtime.rb:55:in `block in require'
        from /usr/lib64/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/runtime.rb:44:in `each'
        from /usr/lib64/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/runtime.rb:44:in `require'
        from /usr/lib64/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler.rb:212:in `require'
        from /srv/www/vhosts/gitlab-ce/config/application.rb:18:in `<top (required)>'
        from /srv/www/vhosts/gitlab-ce/config/environment.rb:4:in `require_relative'
        from /srv/www/vhosts/gitlab-ce/config/environment.rb:4:in `<top (required)>'
        from /usr/lib64/ruby/3.3.0/bundled_gems.rb:75:in `require'
        from /usr/lib64/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
        from config.ru:5:in `block in <main>'
        from /usr/lib64/ruby/gems/3.3.0/gems/rack-2.2.9/lib/rack/builder.rb:116:in `eval'
        from /usr/lib64/ruby/gems/3.3.0/gems/rack-2.2.9/lib/rack/builder.rb:116:in `new_from_string'
        from /usr/lib64/ruby/gems/3.3.0/gems/rack-2.2.9/lib/rack/builder.rb:105:in `load_file'
        from /usr/lib64/ruby/gems/3.3.0/gems/rack-2.2.9/lib/rack/builder.rb:66:in `parse_file'
        from /usr/lib64/ruby/gems/3.3.0/gems/puma-6.4.0/lib/puma/configuration.rb:368:in `load_rackup'
        from /usr/lib64/ruby/gems/3.3.0/gems/puma-6.4.0/lib/puma/configuration.rb:290:in `app'
        from /usr/lib64/ruby/gems/3.3.0/gems/puma-6.4.0/lib/puma/runner.rb:162:in `load_and_bind'
        from /usr/lib64/ruby/gems/3.3.0/gems/puma-6.4.0/lib/puma/cluster.rb:359:in `run'
        from /usr/lib64/ruby/gems/3.3.0/gems/puma-6.4.0/lib/puma/launcher.rb:194:in `run'
        from /usr/lib64/ruby/gems/3.3.0/gems/puma-6.4.0/lib/puma/cli.rb:75:in `run'
        from /usr/lib64/ruby/gems/3.3.0/gems/puma-6.4.0/bin/puma:10:in `<top (required)>'
        from /usr/bin/puma.ruby3.3:25:in `load'
        from /usr/bin/puma.ruby3.3:25:in `<top (required)>'
        from /usr/lib64/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/lib64/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/lib64/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/lib64/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/cli.rb:455:in `exec'
        from /usr/lib64/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /usr/lib64/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/lib64/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /usr/lib64/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/cli.rb:35:in `dispatch'
        from /usr/lib64/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /usr/lib64/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/cli.rb:29:in `start'
        from /usr/lib64/ruby/gems/3.3.0/gems/bundler-2.5.18/exe/bundle:28:in `block in <top (required)>'
        from /usr/lib64/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/lib64/ruby/gems/3.3.0/gems/bundler-2.5.18/exe/bundle:20:in `<top (required)>'
        from /usr/bin/bundle.ruby3.3:25:in `load'
        from /usr/bin/bundle.ruby3.3:25:in `<main>'
```

**Comment by deivid-rodriguez** [comment] 2024-09-10 17:01
Any chance you can share some steps to help reproducing it?

**Comment by darix** [comment] 2024-09-10 18:34
> Any chance you can share some steps to help reproducing it?

well i have built a container for you with the App installed inside ... but with the requirements of a DB and everything around it ... it is no fun to hook all of that up in a container.

the container is here `registry.opensuse.org/home/darix/apps/containers/opensuse-gitlab-ce-base:latest`

**Comment by deivid-rodriguez** [comment] 2024-09-10 18:39
Thank you. So, what do I need to run exactly to see the error?

**Comment by darix** [comment] 2024-09-10 18:41
that is a problem we would need to finish the whole setup. it wants a DB and stuff ... just like a normal rails app
not sure if there is an easy way within a rails app to trigger "just make bundler do its thing and try to load net-http via faraday"

**Comment by deivid-rodriguez** [comment] 2024-09-10 18:43
If you remove some dependencies temporarily to make this easier, can you still reproduce the error?

**Comment by darix** [comment] 2024-09-10 18:44
the dependencies are not the problem. it is patching out all the stuff to start the rails app. all the dependencies are there.

**Comment by deivid-rodriguez** [comment] 2024-09-10 18:49
I meant, can you temporarily change the app to not need a DB, so you don't need to setup all that?

**Comment by darix** [comment] 2024-09-10 18:51
i tried:

```
6cf526effb4f:/srv/www/vhosts/gitlab-ce # cat t.rb 
#!/usr/bin/ruby.ruby3.3

# frozen_string_literal: true
require_relative 'config/boot'

# Based on https://github.com/rails/rails/blob/v6.0.1/railties/lib/rails/all.rb
# Only load the railties we need instead of loading everything
require 'rails'

require 'active_record/railtie'
require 'action_controller/railtie'
require 'action_view/railtie'
require 'action_mailer/railtie'
require 'action_cable/engine'
require 'rails/test_unit/railtie'
require 'sprockets/railtie'

require 'gitlab/utils/all'

Bundler.require(*Rails.groups)

require 'faraday'

puts "hello world"
```

which is extracted from config/application.rb

but that wasnt enough to trigger it.

**Comment by deivid-rodriguez** [comment] 2024-09-10 19:11
I see. Maybe it's related to bootsnap? If you pass `DISABLE_BOOTSNAP_LOAD_PATH_CACHE=true`, does it work?

**Comment by darix** [comment] 2024-09-10 19:50
that also seems to fix it.

**Comment by deivid-rodriguez** [comment] 2024-09-10 19:54
Great, I guess you should reset bootsnap cache then. Not sure how you run into that state, maybe at some point you did run the app with net-http installed as a standard, non default, gem?

**Comment by darix** [comment] 2024-09-10 19:56
yeah but i wonder how to do that properly in the scope of the package. deleting the the cache everytime the package is updated seems also wrong.

**Comment by deivid-rodriguez** [comment] 2024-09-10 20:01
Well, since I can't reproduce this, I'm not sure how to help more. If it happens again next time you upgrade, we can try reproduce again?

**Comment by deivid-rodriguez** [comment] 2024-09-10 20:03
Which package are you upgrading, by the way? I honestly think this was a one time thing, but I'll gladly help more if it happens again.

**Comment by darix** [comment] 2024-09-10 20:13
yeah but if i already know this can be an issue ... so i wonder how to set up the package/service so that it is nothing user visible next time it happens.

**Comment by deivid-rodriguez** [comment] 2024-09-10 20:27
Well, I don't know how your policies work, but my recommendation would be to install the net-http` version in the `Gemfile.lock` in the standard gem location and forget it's a default gem. That makes the application independent from the specific default gems provided by each ruby version. For example, net-http-0.4.1 was not a default gem until Ruby 3.3.1.

**Comment by deivid-rodriguez** [comment] 2024-09-10 20:29
In any case, I'm going to close this since I don't see anything actionable for us right now, but happy to try help more though!

**Closed by deivid-rodriguez** 2024-09-10 20:29 UTC
Labels: Bundler

**Comment by darix** [comment] 2024-09-10 20:54
about the suggestion to ignore default gems. we have other users who prefer using them over having yet another copy of the same code if possible. and our package [dependency solver][1] learns "ruby3.3 is needed and it has the following provides" and the wont normally consider the gem based package. i can force it in the package but it also feels ugly. 

we triggered the bug  this time because the latest ruby 3.3.x upgraded net-http to the latest version and now it was available in both places.


[1]: https://github.com/opensuse/libsolv

**Comment by deivid-rodriguez** [comment] 2024-09-11 11:25
> we have other users who prefer using them over having yet another copy of the same code if possible. and our package [dependency solver](https://github.com/opensuse/libsolv) learns "ruby3.3 is needed and it has the following provides" and the wont normally consider the gem based package.

So your dependency solver makes sure that the default version is the exact same version that discourse uses, and only uses in that case. Otherwise it will install the appropriate version as a default gem. Is that accurate?

**Comment by darix** [comment] 2024-09-11 11:28
if the default version would fulfill the version constraint with the default version it will avoid adding another package to fulfill the dependency. if i want a newer version i can do

```
BuildRequires: %{rubygem net-http > 0.4.1}
```

in which case it would pull the extra package.

**Comment by deivid-rodriguez** [comment] 2024-09-11 11:32
Just to make sure, `discourse` is an application so I'd expect it uses a lockfile, and every dependency constraint should be an exact constraint. My understanding is that you ignore discourse's lockfile and only respect the `Gemfile` when installing its dependencies?
