### ISSUE TITLE
Symbol referencing for git branches not supported

### ISSUE THREAD

**Issue by hron84** [rubygems/rubygems#2902] opened 2019-09-02 19:18 UTC
I'm having a problem or would like to suggest a feature.

My current problem is if I have a Gemfile line like this:

```ruby
  gem 'guard-resque', github: 'jacquescrocker/guard-resque', branch: :master
```

Then the following exception happens:

https://gist.github.com/hron84/22641ec090af1d1f5d417ede1634f400

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Using Gemfile

Here are my current environment details:

```
$ gem env version
3.0.6
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by duckinator** [comment] 2019-09-13 13:03
If you change `:master` to `'master'` it should work.

**Comment by bronzdoc** [comment] 2019-09-17 03:53
@hron84 please provide steps to reproduce the error, thanks.

**Comment by hron84** [comment] 2019-09-17 14:28
@bronzdoc Errm... there is an example Gemfile definition in the OP. If you paste that into your Gemfile, and run `bundle install`, the exception will happen. (I could not try it out right now, I've no access for a machine runs ruby. I could check if it's already fixed by any means at weekend, sorry).

@duckinator Yeah, it could solve, but the problem is 

1) I want to keep using symbols since performance and other reasons 
2) the symbol itself comes from a way different code that is not included because it's irrelevant from the aspect of the question but it uses symbols internally for a reason. 
I previously tried with the mentioned line in my Gemfile and still fails so definitely the `:master` specification is the problem, not my code. 
Since it's so easy to convert symbol (and everything) to string by few finely placed `#to_s` calls I'd rather prefer if Bundler/RubyGems could support symbol notation rather than changing my codebase. For work it around I call `Symbol#to_s` myself but it's not so pretty solution.

**Comment by duckinator** [comment] 2019-09-23 18:26
@hron84 do you mean that you have something along the lines of this, or am I misunderstanding what you said?:

```
branch = :master # vast oversimplification of what you probably actually have

gem 'guard-resque', github: 'jacquescrocker/guard-resque', branch: branch
```

If that's what you meant, I don't understand how us changing RubyGems and making a new release and you making sure all your systems are using that version is easier than you calling `.to_s` on your end.

If that's not what you meant, I'm missing something.

**Comment by duckinator** [comment] 2019-09-23 18:34
Also, realistically, strings vs symbols in your Gemfile is not going to be a significant performance concern. Many other things will be more significant.

**Comment by duckinator** [comment] 2019-09-24 22:19
@hron84 I just realized I never explicitly said the most important part of what I was trying to explain. Sorry about that.

The main problem is that, realistically, even if a PR adding it got merged today, it'd likely be a bit before you can use it in practice &mdash; especially if you're coordinating with other developers. Given this, I feel that you're likely better off finding a workaround regardless of if/when support for symbols is added.

**Comment by hron84** [comment] 2019-09-26 13:01
@duckinator the project i actually working on is developed by only me so I don't care about collaboration. 

I think using symbols in these places would be good for other developers too as Bundler uses them at many different places (like group names, previously there was a shortcut for 'https://rubygems.org' as `:rubygems` in `source` definitions, etc. It seems like Bundler actually has a tradition for allow using symbols as well as strings.

It's so easy to miss the branch definition actually does not support symbols and Bundler will crash because of it - without any good error message. Take a look at Capistrano, it supports branch and other definitions in both strings and symbols. Really confusing using different libraries/tools in same project with different capabilities in treating symbols as valid replacement of strings. As far as I know, symbols only has benefits over strings but they can safely treated as equal to strings.

**Comment by zachrab** [comment] 2020-03-25 14:48
I cannot replicate this issue; @hron84 which bundler version were you using?

In attempt to reproduce this issue I used the most recent version of Bundler and added the same gem and options you have specified in this issue. `bundle install` produces no exceptions.

`bundler/lib/bundler/source/git.rb` lines 19-20 stringifies the git path options:
`# Stringify options that could be set as symbols
%w[ref branch tag revision].each {|k| options[k] = options[k].to_s if options[k] }`

If you are still encountering this issue can you state the exact steps you are taking to produce the problem?

**Comment by duckinator** [comment] 2020-03-26 20:38
The line @zachrab mentioned can be traced all the way back to Bundler v1.1.0:

https://github.com/rubygems/bundler/blob/v1.1.0/lib/bundler/source.rb#L488

@hron84 can you tell us if you're still having this problem? If you are, can you please provide the output of `bundle version`?

---

<details>
<summary>Notes from some quick poking around, in case it turns out relevant.</summary>

I looked at the stack trace again, and think this section at the start is noteworthy:

```
/srv/www/showtime.dragonhall.hu/.rvm/rubies/ruby-2.5.6/lib/ruby/site_ruby/2.5.0/rubygems/util.rb:58:in `exec': no implicit conversion of Symbol into String (TypeError)
	from /srv/www/showtime.dragonhall.hu/.rvm/rubies/ruby-2.5.6/lib/ruby/site_ruby/2.5.0/rubygems/util.rb:58:in `block in popen'
	from /srv/www/showtime.dragonhall.hu/.rvm/rubies/ruby-2.5.6/lib/ruby/site_ruby/2.5.0/rubygems/util.rb:54:in `fork'
	from /srv/www/showtime.dragonhall.hu/.rvm/rubies/ruby-2.5.6/lib/ruby/site_ruby/2.5.0/rubygems/util.rb:54:in `rescue in popen'
	from /srv/www/showtime.dragonhall.hu/.rvm/rubies/ruby-2.5.6/lib/ruby/site_ruby/2.5.0/rubygems/util.rb:49:in `popen'
	from /srv/www/showtime.dragonhall.hu/.rvm/rubies/ruby-2.5.6/lib/ruby/site_ruby/2.5.0/rubygems/source/git.rb:184:in `block in rev_parse'
```

It mentions `popen`, `rubygems/util.rb`, and being unable to implicitly convert a Symbol into a String, so I'm wondering if it's referring to the `Gem::Util.popen(*command)` function, and if `:master` is somehow getting dragged all the way through to it in certain situations.

</details>

**Comment by deivid-rodriguez** [comment] 2020-03-26 20:43
Also, @hron84 mention this error happening on `bundle install` but the backtrace seems to be the backtrace for a `gem` command (`gem install -g` I guess).

**Comment by hron84** [comment] 2020-04-11 18:50
Bundler 1.17.3 apparently have no issue with this definition. I stuck with this version of Bundler from another reason (RVM does not like Bundler 2.x)

**Comment by deivid-rodriguez** [comment] 2020-04-11 18:53
So I guess this issue can be closed, right?

Can you open a separate ticket explaining your problems with bundler 2 & RVM?

**Comment by hron84** [comment] 2020-04-11 18:56
@deivid-rodriguez I have to re-evaluate the RVM vs Bundler issue, but I will send an issue when I will have time for it.

Yes, apparently this issue could be solved. Sorry, I completely forget about this issue, and I just changed back my code to test if it's working and wow'd, as it does.

**Comment by deivid-rodriguez** [comment] 2020-04-11 18:58
Thanks for reporting back @hron84!

**Closed by deivid-rodriguez** 2020-04-11 18:58 UTC
Labels: help wanted, status: user feedback required, type: feature request
