### ISSUE TITLE
'bundle does not exist' logs when updating RubyGems

### ISSUE THREAD

**Issue by thisismydesign** [rubygems/rubygems#2060] opened 2017-11-04 01:54 UTC
My current problem is that I see 'bundle does not exist' logs when running `gem update --system`. The command exists successfully. This issue is **not** present when running `gem install rubygems-update && update_rubygems`. Might be related to #2055.

My exact output:

```
Step 6/12 : RUN gem install rubygems-update && update_rubygems
 ---> Running in 6cccd3544c27
Successfully installed rubygems-update-2.7.1
1 gem installed
[91mfatal: Not a git repository (or any of the parent directories): .git
[0m[91m`/opt/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.14.4/exe/bundle` does not exist, maybe `gem pristine bundler` will fix it?
`/opt/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.14.4/exe/bundler` does not exist, maybe `gem pristine bundler` will fix it?
[0mBundler 1.16.0 installed
RubyGems 2.7.1 installed
```

Unfortunately I could not reproduce on a minimal example. ([1](https://github.com/thisismydesign/rubygems-update-2.7.0-bug/tree/af708a682aad32a047caeda5a5332ff2e19ca844), [2](https://travis-ci.org/thisismydesign/rubygems-update-2.7.0-bug/builds/297064597))

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.7.1
```

Building via rbenv and docker.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment] 2017-11-06 10:04
It seems to duplicates with #2059

**Comment by thisismydesign** [comment] 2017-11-06 10:33
@hsbt No, this ticket specifically concerns `bundle does not exist` log messages while #2059 concerns `fatal: Not a git repository (or any of the parent directories): .git` message.

This issue is specific to the `gem update --system` command while #2059 is not. Also this ticket I could not reproduce via a minimal Travis setup. You cannot see this error in #2059's output.

Please re-open.

**Comment by hsbt** [comment] 2017-11-09 08:11
Can you try again with Rubygems 2.7.2?

**Comment by thisismydesign** [comment] 2017-11-22 10:21
@hsbt still present with 2.7.2:
```
11:11:03 Step 4/11 : RUN gem update --system && gem install bundler
11:11:03  ---> Running in 4589beede652
11:11:06 Updating rubygems-update
11:11:06 Successfully installed rubygems-update-2.7.2
11:11:06 Installing RubyGems 2.7.2
11:11:07 [91m`/opt/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.14.4/exe/bundle` does not exist, maybe `gem pristine bundler` will fix it?
11:11:07 `/opt/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.14.4/exe/bundler` does not exist, maybe `gem pristine bundler` will fix it?
11:11:07 [0mBundler 1.16.0 installed
11:11:07 RubyGems 2.7.2 installed
```

**Comment by hsbt** [comment] 2017-11-22 10:26
Its message is not error or defects.  Do you have an issue with your usecase? 

Again, This is duplicates with #2059, I think.

**Comment by thisismydesign** [comment] 2017-11-22 10:37
@hsbt 
As for https://github.com/rubygems/rubygems/issues/2059 I can only make the same explanation as before. Also since that has been closed but this issue is still present.

I can't tell if this has any side effects but it's an error message on screen. At best it's misleading. If there's no error there shouldn't be an error message. If there's an error it should be clear what that is and what effects it has. Neither is the case as far as I can tell.

**Comment by hsbt** [comment] 2017-11-30 07:45
This issue is same as https://github.com/rubygems/rubygems/issues/2071 . We need to update specification of `pristine` command.

**Comment by bronzdoc** [comment] 2018-02-26 01:53
I'm going to close this since is a duplicate of the issue https://github.com/rubygems/rubygems/issues/2071

**Closed by bronzdoc** 2018-02-26 01:53 UTC
Labels: status: user feedback required
