### ISSUE TITLE
Allow make options, to make extensions compilation considerably faster (2x/3x)

### ISSUE THREAD

**Issue by 64kramsystem** [rubygems/rubygems#5641] opened 2022-06-21 21:17 UTC
Currently, extensions are compiled (by make) in a single thread; due to "GIL and stuff", increasing the number of jobs doesn't help (extension compilation is largely CPU-bound).

As an effect of this, on projects with a large number of dependencies (assuming the the number of C extensions is correlated to the number of gems used), installing gems is very inefficient.

It's actually trivial to considerably improve the gem installations speed - just allow make options (that is, `-j JOBS` parameter, so that all the threads available to a machine can be used.

Tehcnically speaking, it's already possible to accomplish this - just set the env var `MAKE` to something like `make -j $(nproc)` (or the win/mac equivalent). This is however a hack, since MAKE is a (semi-)standard variable, which should point to the make binary - if permanently set in a system in this form (`make` + option), it surefire breaks some other programs' compilation.

Just to give an idea, on my 32-threads system, installing the gems for my company's project takes: 

- `bundle install --jobs=32`: 2'45"
- `MAKE='make -j 32' bundle install --jobs=32`: 1'04"

this is approximately 2.5x as fast; as a bonus, I get to sporadically see the CPU occupation bars all filled in htop, which is great.

Implementing this is trivial. The code is [here](https://github.com/rubygems/rubygems/blob/ecc8e895b69063562b9bf749b353948e051e4171/lib/rubygems/ext/builder.rb#L27):

```rb
    make_program_name = ENV['MAKE'] || ENV['make'] || $1
    unless make_program_name
      make_program_name = (/mswin/ =~ RUBY_PLATFORM) ? 'nmake' : 'make'
    end
    make_program = Shellwords.split(make_program_name)
```

there are different approaches to this.

A dead simple approach is just to add a `BUNDLER_MAKE_OPTS` env var; casual users are then able to set something like `BUNDLER_MAKE_OPTS="-j $(nproc)"`, and power users, can set whatever they want :smile:

Another approach is to automatically set the number of make jobs to the number of bundler jobs; this also makes sense, however, I'm afraid (but not 100% sure) that there could be an extreme (improbable, but potential) edge case where the number of total make threads would explode (n^2) - if my suspicion is correct, it'd be a memory problem, more than a cpu one.  Additionally, it'd need to be checked if all the make programs support the same option, and if not, the handling should be internally differentiated.
For these reasons, my personal preference is the first approach (it can be changed anyway, in the long term).

I can take care of this if somebody gives me the green lights (and their preference).

**Comment by deivid-rodriguez** [comment] 2022-06-22 07:49
Thanks for reporting this. I'll close  in favor of #5276 though since I think this is a duplicate of it. Feel free to post your comments there!

**Closed by deivid-rodriguez** 2022-06-22 07:49 UTC
Labels: Bundler
