### ISSUE TITLE
Bundler: bundle install never finishes "Resolving dependencies..." part after adding sorbet gem to Gemfile

### ISSUE THREAD

**Issue by Nowaker** [rubygems/rubygems#7455] opened 2024-02-03 21:39 UTC
### Describe the problem as clearly as you can

`bundle install` never finishes "Resolving dependencies..." part after adding sorbet gem to Gemfile

### Did you try upgrading rubygems & bundler?

Yes.

### Post steps to reproduce the problem

* How your ruby is setup (OS package, from source, using a version manager).

RVM

* How bundler & rubygems are configured.

Regular.

* The version of each involved piece of software that you are using.

rubygems 3.5.5 / bundler 2.5.5

### Which command did you run?

- Add `sorbet` to Gemfile
- Run `bundle`

### What were you expecting to happen?

Works.

### What actually happened?

Never ends.

```
% bundle 
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
^Cbundle  175.62s user 0.51s system 98% cpu 2:59.73 total
```

3 minutes here.

`strace -p [pid]` shows it's doing basically nothing:

```
...
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {tv_sec=32, tv_nsec=9240218}) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {tv_sec=32, tv_nsec=9286716}) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {tv_sec=32, tv_nsec=11187778}) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {tv_sec=32, tv_nsec=11232390}) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {tv_sec=32, tv_nsec=13113900}) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {tv_sec=32, tv_nsec=13157402}) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {tv_sec=32, tv_nsec=14898630}) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {tv_sec=32, tv_nsec=14940517}) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {tv_sec=32, tv_nsec=16326841}) = 0
...
```

## Environment

```
Bundler             2.5.5
  Platforms         ruby, x86_64-linux
Ruby                3.3.0p0 (2023-12-25 revision 5124f9ac7513eb590c37717337c430cb93caa151) [x86_64-linux]
  Full Path         /home/nowaker/.rvm/rubies/ruby-3.3.0/bin/ruby
  Config Dir        /home/nowaker/.rvm/rubies/ruby-3.3.0/etc
RubyGems            3.5.5
  Gem Home          /home/nowaker/.rvm/gems/ruby-3.3.0
  Gem Path          /home/nowaker/.rvm/gems/ruby-3.3.0:/home/nowaker/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0
  User Home         /home/nowaker
  User Path         /home/nowaker/.gem/ruby/3.3.0
  Bin Dir           /home/nowaker/.rvm/gems/ruby-3.3.0/bin
Tools               
  Git               2.43.0
  RVM               1.29.12-next (master)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2024-01-18
Git SHA           2efa8cec93
Released Version  true
```

## Bundler settings

```
build.nokogiri
  Set for the current user (/home/nowaker/.bundle/config): "--use-system-libraries"
jobs
  Set for the current user (/home/nowaker/.bundle/config): 20
retry
  Set for the current user (/home/nowaker/.bundle/config): 5
without
  Set for your local app (/home/nowaker/projekty/modern/worldmodern/.bundle/config): [:skip_arch]
```

### Gemfile

```ruby
source 'https://rubygems.org'

ruby File.read '.ruby-version' if File.exist? '.ruby-version'

gem 'active_scaffold'
gem 'active_hash'
gem 'activemerchant', '1.88.0'
gem 'appsignal'
gem 'aws-sdk-ses'
gem 'byebug'
gem 'color'
gem 'concurrent-ruby'
gem 'calendar_date_select'
gem 'dalli'
gem 'ezcrypto', '0.7.2'
gem 'fog-aws'
gem 'font-awesome-rails'
gem 'geocoder', '1.6.1'
gem 'geokit', '1.9.0'
gem 'geokit-rails'
gem 'gruff'
gem 'haml'
gem 'hpricot', '0.8.6'
gem 'http'
gem 'i18n'
gem 'jbuilder'
gem 'jquery-rails', '4.3.5'
gem 'jquery-ui-rails', '6.0.1'
gem 'justrun'
gem 'jwt'
gem 'flatpickr'
gem 'lograge', git: 'https://github.com/Nowaker/lograge.git', branch: 'head-brad-master-lograge' # https://github.com/roidrage/lograge/pull/303 rebased against master
gem 'make_resourceful', git: 'https://github.com/Nowaker/make_resourceful.git', branch: 'patch-1' # https://github.com/hcatlin/make_resourceful/issues/18
# gem 'make_resourceful', path: '/home/nowaker/projekty/modern/make_resourceful'
gem 'mail', '2.8.0.rc1' # https://github.com/mikel/mail/issues/1275
gem 'marginalia'
gem 'mime-types'
gem 'mini_magick'
# gem 'mobile-fu', '1.3.1'
gem 'money'
gem 'mysql2' #, '0.4.10'
gem 'nokogiri'
gem 'oauth2'
gem 'postmark-mitt', '0.0.11'
gem 'prototype-rails', git: 'https://github.com/Nowaker/prototype-rails.git', branch: '5.1'
# gem 'prototype-rails', path: '/home/nowaker/projekty/modern/prototype-rails'
# gem 'prototype_legacy_helper', '0.0.0', :git => 'https://github.com/rails/prototype_legacy_helper.git'
gem 'link_to_function_helper'
gem 'puma', '~> 5.0'
gem 'rack'
gem 'rack-attack'
gem 'rack_attack_admin', git: 'https://github.com/Nowaker/rack_attack_admin.git', branch: 'patch'
# gem 'rack_attack_admin', path: '../rack_attack_admin'
gem 'activesupport-duration-human_string', git: 'https://github.com/Nowaker/activesupport-duration-human_string.git', branch: 'patch'
# gem 'activesupport-duration-human_string', path: '../activesupport-duration-human_string'
gem 'rails', '~> 6.1.0'
gem 'redis'
# gem 'hiredis'
gem 'request_store'
gem 'responders'
gem 'rexml'
gem 'rmagick'
gem 'sassc-rails', git: 'https://github.com/Nowaker/sassc-rails.git', branch: 'patch' # https://github.com/sass/sassc-rails/pull/162/files
gem 'syslogger'
gem 'sidekiq', '~> 6'
gem 'sidekiq-batch'
gem 'sidekiq-failures'
gem 'sidekiq-status'
gem 'sinatra', '~> 2.2.0' # Used by sidekiq/web
gem 'sprockets'
gem 'streamio-ffmpeg', git: 'https://github.com/Nowaker/streamio-ffmpeg.git', branch: 'side_data_list-rotation'
gem 'terminal-table' # Used by rack_attack_admin
gem 'terser'
gem 'warning'
gem 'will_paginate'
gem 'xml-simple', '1.1.4'

# From plugins
gem 'liquid', '~> 3.0.0'
gem 'acts_as_taggable', path: 'vendor/plugins/acts_as_taggable'
gem 'acts_as_list'
gem 'spawnling'
gem 'zen_form_builder', path: 'vendor/plugins/zen_form_builder'
gem 'rbpdf'
gem 'sd_notify'

group :development do
  gem 'meta_request' # Chrome extension: https://chrome.google.com/webstore/detail/railspanel/gjpfobpafnhjhbajcjgccbbdofdckggg/related
  gem 'web-console'

  gem 'capistrano'
  gem 'capistrano-rails'
  gem 'capistrano-rbenv'
  gem 'capistrano-systemd-multiservice', git: 'https://github.com/BrandyMint/capistrano-systemd-multiservice.git'
end

group :development, :test do
  gem 'irb'
  gem 'rspec-rails'

  # For Ruby plugin for VS Code: https://marketplace.visualstudio.com/items?itemName=shopify.ruby-lsp
  gem 'debug'
  gem 'ruby-lsp-rails'
  gem 'ruby-lsp-rspec'

  # For other VS Code plugins:
  gem 'ripper-tags' # https://marketplace.visualstudio.com/items?itemName=gurgeous.bust-a-gem

  #gem 'sorbet'

  # Required by Capistrano
  gem 'ed25519'
  gem 'bcrypt_pbkdf'
end

group :production do
end

# These gems don't work on Arch Linux, and I haven't figured out a way to fix them yet.
# Use `bundle install --without skip_arch` to ignore them when installing gems.
group :skip_arch do
end

# M1 Macs must use mini_racer. therubyracer is broken: https://github.com/rubyjs/libv8/issues/312
# Intel Macs may use either - but therubyracer requires `brew install v8@3.15` and `bundle config build.therubyracer --with-v8-dir=$(brew --prefix)/opt/v8@3.15`, while mini_racer works out of the box.
# New Linuxes may use either.
# Ruby 3.1+ must use mini_racer, as therubyracer is broken: https://github.com/rubyjs/therubyracer/issues/467#issuecomment-1281963117
# Old Linuxes must use therubyracer, as mini_racer requires GCC 8+.
is_mac = RUBY_PLATFORM.include?('darwin')
is_ruby31_plus = Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('3.1')
use_mini_racer = is_mac || is_ruby31_plus
gem 'mini_racer', install_if: use_mini_racer
gem 'therubyracer', install_if: !use_mini_racer
gem 'libv8-node', '16.10.0.0'

gem 'momentjs-rails', '>= 2.9.0'
gem 'bootstrap3-datetimepicker-rails', '~> 4.14.30'
```

### Gemfile.lock

```
GIT
  remote: https://github.com/BrandyMint/capistrano-systemd-multiservice.git
  revision: 0f2c0fb2c72802f42e85667483ab6039d55ce018
  specs:
    capistrano-systemd-multiservice (0.1.0.beta12)
      capistrano (>= 3.7.0, < 3.17.0)

GIT
  remote: https://github.com/Nowaker/activesupport-duration-human_string.git
  revision: 94ac53515cf1172e09c367cf07610f6f1728891f
  branch: patch
  specs:
    activesupport-duration-human_string (0.1.1)
      activesupport (>= 4.2)

GIT
  remote: https://github.com/Nowaker/lograge.git
  revision: 8bdfb4ce5573d78f33a251a6df61fe58b6c6b6b6
  branch: head-brad-master-lograge
  specs:
    lograge (0.13.0)
      actionpack (>= 4)
      activesupport (>= 4)
      railties (>= 4)
      request_store (~> 1.0)

GIT
  remote: https://github.com/Nowaker/make_resourceful.git
  revision: eaa834ae8b83d1eb2cfe6b4b56b77d173ac72d77
  branch: patch-1
  specs:
    make_resourceful (2.0.0)

GIT
  remote: https://github.com/Nowaker/prototype-rails.git
  revision: 011eaf11815448c8c9e3d7717a0f521d338d3f47
  branch: 5.1
  specs:
    prototype-rails (4.0.0)
      rails

GIT
  remote: https://github.com/Nowaker/rack_attack_admin.git
  revision: 5f68296347a7e8e9facfd4c08e407fd6fe802373
  branch: patch
  specs:
    rack_attack_admin (0.1.2)
      activesupport (>= 4.2)
      activesupport-duration-human_string (>= 0.1.1)
      haml
      memoist
      rack-attack
      rails (>= 4.2)

GIT
  remote: https://github.com/Nowaker/sassc-rails.git
  revision: c2ec8c144fe7def9c6843be4afe0bb2356dfdc4d
  branch: patch
  specs:
    sassc-rails (2.1.2)
      railties (>= 4.0.0)
      sassc (>= 2.0)
      sprockets (> 3.0)
      sprockets-rails
      tilt

GIT
  remote: https://github.com/Nowaker/streamio-ffmpeg.git
  revision: 8f540c2e6539b20230ad5c35296b0512ca6ca31f
  branch: side_data_list-rotation
  specs:
    streamio-ffmpeg (3.0.2)
      multi_json (~> 1.8)

PATH
  remote: vendor/plugins/acts_as_taggable
  specs:
    acts_as_taggable (0)

PATH
  remote: vendor/plugins/zen_form_builder
  specs:
    zen_form_builder (0)

GEM
  remote: https://rubygems.org/
  specs:
    actioncable (6.1.7.6)
      actionpack (= 6.1.7.6)
      activesupport (= 6.1.7.6)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (6.1.7.6)
      actionpack (= 6.1.7.6)
      activejob (= 6.1.7.6)
      activerecord (= 6.1.7.6)
      activestorage (= 6.1.7.6)
      activesupport (= 6.1.7.6)
      mail (>= 2.7.1)
    actionmailer (6.1.7.6)
      actionpack (= 6.1.7.6)
      actionview (= 6.1.7.6)
      activejob (= 6.1.7.6)
      activesupport (= 6.1.7.6)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (6.1.7.6)
      actionview (= 6.1.7.6)
      activesupport (= 6.1.7.6)
      rack (~> 2.0, >= 2.0.9)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (6.1.7.6)
      actionpack (= 6.1.7.6)
      activerecord (= 6.1.7.6)
      activestorage (= 6.1.7.6)
      activesupport (= 6.1.7.6)
      nokogiri (>= 1.8.5)
    actionview (6.1.7.6)
      activesupport (= 6.1.7.6)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    active_hash (3.1.1)
      activesupport (>= 5.0.0)
    active_scaffold (3.7.0)
      cow_proxy (~> 0.3)
      ice_nine (~> 0.11)
      rails (>= 5.2.0)
      request_store (~> 1.3)
    activejob (6.1.7.6)
      activesupport (= 6.1.7.6)
      globalid (>= 0.3.6)
    activemerchant (1.88.0)
      activesupport (>= 4.2)
      builder (>= 2.1.2, < 4.0.0)
      i18n (>= 0.6.9)
      nokogiri (~> 1.4)
    activemodel (6.1.7.6)
      activesupport (= 6.1.7.6)
    activerecord (6.1.7.6)
      activemodel (= 6.1.7.6)
      activesupport (= 6.1.7.6)
    activestorage (6.1.7.6)
      actionpack (= 6.1.7.6)
      activejob (= 6.1.7.6)
      activerecord (= 6.1.7.6)
      activesupport (= 6.1.7.6)
      marcel (~> 1.0)
      mini_mime (>= 1.1.0)
    activesupport (6.1.7.6)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
      zeitwerk (~> 2.3)
    acts_as_list (1.1.0)
      activerecord (>= 4.2)
    addressable (2.8.5)
      public_suffix (>= 2.0.2, < 6.0)
    airbrussh (1.5.1)
      sshkit (>= 1.6.1, != 1.7.0)
    appsignal (3.4.12)
      rack
    aws-eventstream (1.1.1)
    aws-partitions (1.444.0)
    aws-sdk-core (3.114.0)
      aws-eventstream (~> 1, >= 1.0.2)
      aws-partitions (~> 1, >= 1.239.0)
      aws-sigv4 (~> 1.1)
      jmespath (~> 1.0)
    aws-sdk-ses (1.38.0)
      aws-sdk-core (~> 3, >= 3.112.0)
      aws-sigv4 (~> 1.1)
    aws-sigv4 (1.2.3)
      aws-eventstream (~> 1, >= 1.0.2)
    bcrypt_pbkdf (1.1.0)
    bindex (0.8.1)
    bootstrap3-datetimepicker-rails (4.14.30)
      momentjs-rails (>= 2.8.1)
    builder (3.2.4)
    byebug (10.0.2)
    calendar_date_select (2.1.2)
      rails (>= 3.1)
    capistrano (3.16.0)
      airbrussh (>= 1.0.0)
      i18n
      rake (>= 10.0.0)
      sshkit (>= 1.9.0)
    capistrano-bundler (2.1.0)
      capistrano (~> 3.1)
    capistrano-rails (1.6.3)
      capistrano (~> 3.1)
      capistrano-bundler (>= 1.1, < 3)
    capistrano-rbenv (2.2.0)
      capistrano (~> 3.1)
      sshkit (~> 1.3)
    chronic_duration (0.10.6)
      numerizer (~> 0.1.1)
    color (1.8)
    concurrent-ruby (1.2.3)
    connection_pool (2.4.1)
    cow_proxy (0.3.3)
    crass (1.0.6)
    dalli (3.2.4)
    date (3.3.4)
    debug (1.9.1)
      irb (~> 1.10)
      reline (>= 0.3.8)
    diff-lcs (1.5.1)
    domain_name (0.5.20180417)
      unf (>= 0.0.5, < 1.0.0)
    ed25519 (1.3.0)
    erubi (1.12.0)
    excon (0.80.0)
    execjs (2.9.1)
    ezcrypto (0.7.2)
    faraday (1.1.0)
      multipart-post (>= 1.2, < 3)
      ruby2_keywords
    ffi (1.15.0)
    ffi-compiler (1.0.1)
      ffi (>= 1.0.0)
      rake
    flatpickr (4.6.3.1)
    fog-aws (3.10.0)
      fog-core (~> 2.1)
      fog-json (~> 1.1)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-core (2.2.3)
      builder
      excon (~> 0.71)
      formatador (~> 0.2)
      mime-types
    fog-json (1.2.0)
      fog-core
      multi_json (~> 1.10)
    fog-xml (0.1.3)
      fog-core
      nokogiri (>= 1.5.11, < 2.0.0)
    font-awesome-rails (4.7.0.8)
      railties (>= 3.2, < 8.0)
    formatador (0.2.5)
    geocoder (1.6.1)
    geokit (1.9.0)
      multi_json (>= 1.3.2)
    geokit-rails (2.5.0)
      geokit (~> 1.5)
      rails (>= 3.0)
    globalid (1.2.1)
      activesupport (>= 6.1)
    gruff (0.19.0)
      histogram
      rmagick (>= 4.2)
    haml (5.2.2)
      temple (>= 0.8.0)
      tilt
    hashie (5.0.0)
    histogram (0.2.4.1)
    hpricot (0.8.6)
    htmlentities (4.3.4)
    http (5.0.4)
      addressable (~> 2.8)
      http-cookie (~> 1.0)
      http-form_data (~> 2.2)
      llhttp-ffi (~> 0.4.0)
    http-cookie (1.0.4)
      domain_name (~> 0.5)
    http-form_data (2.3.0)
    i18n (1.14.1)
      concurrent-ruby (~> 1.0)
    ice_nine (0.11.2)
    io-console (0.7.2)
    ipaddress (0.8.3)
    irb (1.11.1)
      rdoc
      reline (>= 0.4.2)
    jbuilder (2.10.1)
      activesupport (>= 5.0.0)
    jmespath (1.6.2)
    jquery-rails (4.3.5)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (6.0.1)
      railties (>= 3.2.16)
    json_pure (2.5.1)
    justrun (1.1.0)
    jwt (2.2.2)
    language_server-protocol (3.17.0.3)
    libv8 (3.16.14.19)
    libv8-node (16.10.0.0)
    link_to_function_helper (0.1.0)
    liquid (3.0.6)
    llhttp-ffi (0.4.0)
      ffi-compiler (~> 1.0)
      rake (~> 13.0)
    loofah (2.22.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.12.0)
    mail (2.8.0.rc1)
      mini_mime (>= 0.1.1)
      net-imap
      net-pop
      net-smtp
    marcel (1.0.2)
    marginalia (1.11.1)
      actionpack (>= 5.2)
      activerecord (>= 5.2)
    memoist (0.16.2)
    meta_request (0.7.4)
      rack-contrib (>= 1.1, < 3)
      railties (>= 3.0.0, < 7.1)
    method_source (1.0.0)
    mime-types (3.3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2021.0225)
    mini_magick (4.12.0)
    mini_mime (1.1.5)
    mini_portile2 (2.8.5)
    mini_racer (0.6.2)
      libv8-node (~> 16.10.0.0)
    minitest (5.21.2)
    momentjs-rails (2.29.4.1)
      railties (>= 3.1)
    money (6.14.1)
      i18n (>= 0.6.4, <= 2)
    multi_json (1.15.0)
    multi_xml (0.6.0)
    multipart-post (2.1.1)
    mustermann (2.0.2)
      ruby2_keywords (~> 0.0.1)
    mutex_m (0.2.0)
    mysql2 (0.5.4)
    net-imap (0.4.9.1)
      date
      net-protocol
    net-pop (0.1.2)
      net-protocol
    net-protocol (0.2.2)
      timeout
    net-scp (4.0.0)
      net-ssh (>= 2.6.5, < 8.0.0)
    net-sftp (4.0.0)
      net-ssh (>= 5.0.0, < 8.0.0)
    net-smtp (0.4.0.1)
      net-protocol
    net-ssh (7.2.1)
    nio4r (2.7.0)
    nokogiri (1.16.1)
      mini_portile2 (~> 2.8.2)
      racc (~> 1.4)
    numerizer (0.1.1)
    oauth2 (2.0.9)
      faraday (>= 0.17.3, < 3.0)
      jwt (>= 1.0, < 3.0)
      multi_xml (~> 0.5)
      rack (>= 1.2, < 4)
      snaky_hash (~> 2.0)
      version_gem (~> 1.1)
    pkg-config (1.5.6)
    postmark-mitt (0.0.11)
      json_pure
      multi_json
    prism (0.19.0)
    psych (5.1.2)
      stringio
    public_suffix (5.0.3)
    puma (5.6.7)
      nio4r (~> 2.0)
    racc (1.7.3)
    rack (2.2.8)
    rack-attack (6.6.1)
      rack (>= 1.0, < 3)
    rack-contrib (2.4.0)
      rack (< 4)
    rack-protection (2.2.4)
      rack
    rack-test (2.1.0)
      rack (>= 1.3)
    rails (6.1.7.6)
      actioncable (= 6.1.7.6)
      actionmailbox (= 6.1.7.6)
      actionmailer (= 6.1.7.6)
      actionpack (= 6.1.7.6)
      actiontext (= 6.1.7.6)
      actionview (= 6.1.7.6)
      activejob (= 6.1.7.6)
      activemodel (= 6.1.7.6)
      activerecord (= 6.1.7.6)
      activestorage (= 6.1.7.6)
      activesupport (= 6.1.7.6)
      bundler (>= 1.15.0)
      railties (= 6.1.7.6)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.2.0)
      activesupport (>= 5.0.0)
      minitest
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.6.0)
      loofah (~> 2.21)
      nokogiri (~> 1.14)
    railties (6.1.7.6)
      actionpack (= 6.1.7.6)
      activesupport (= 6.1.7.6)
      method_source
      rake (>= 12.2)
      thor (~> 1.0)
    rake (13.1.0)
    rbpdf (1.20.1)
      htmlentities
      rbpdf-font (~> 1.19.0)
    rbpdf-font (1.19.1)
    rdoc (6.6.2)
      psych (>= 4.0.0)
    redis (4.8.1)
    ref (2.0.0)
    reline (0.4.2)
      io-console (~> 0.5)
    request_store (1.5.1)
      rack (>= 1.4)
    responders (3.1.0)
      actionpack (>= 5.2)
      railties (>= 5.2)
    rexml (3.2.6)
    ripper-tags (1.0.1)
    rmagick (5.3.0)
      pkg-config (~> 1.4)
    rspec-core (3.12.2)
      rspec-support (~> 3.12.0)
    rspec-expectations (3.12.3)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.12.0)
    rspec-mocks (3.12.6)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.12.0)
    rspec-rails (6.1.1)
      actionpack (>= 6.1)
      activesupport (>= 6.1)
      railties (>= 6.1)
      rspec-core (~> 3.12)
      rspec-expectations (~> 3.12)
      rspec-mocks (~> 3.12)
      rspec-support (~> 3.12)
    rspec-support (3.12.1)
    ruby-lsp (0.13.4)
      language_server-protocol (~> 3.17.0)
      prism (>= 0.19.0, < 0.20)
      sorbet-runtime (>= 0.5.10782)
    ruby-lsp-rails (0.2.9)
      actionpack (>= 6.0)
      activerecord (>= 6.0)
      railties (>= 6.0)
      ruby-lsp (>= 0.13.0, < 0.14.0)
      sorbet-runtime (>= 0.5.9897)
    ruby-lsp-rspec (0.1.9)
      ruby-lsp (~> 0.13.0)
    ruby2_keywords (0.0.5)
    sassc (2.4.0)
      ffi (~> 1.9)
    sd_notify (0.1.1)
    sidekiq (6.5.12)
      connection_pool (>= 2.2.5, < 3)
      rack (~> 2.0)
      redis (>= 4.5.0, < 5)
    sidekiq-batch (0.1.9)
      sidekiq (>= 3)
    sidekiq-failures (1.0.0)
      sidekiq (>= 4.0.0)
    sidekiq-status (2.1.3)
      chronic_duration
      sidekiq (>= 5.0)
    sinatra (2.2.4)
      mustermann (~> 2.0)
      rack (~> 2.2)
      rack-protection (= 2.2.4)
      tilt (~> 2.0)
    snaky_hash (2.0.1)
      hashie
      version_gem (~> 1.1, >= 1.1.1)
    sorbet-runtime (0.5.11226)
    spawnling (2.1.6)
    sprockets (4.2.1)
      concurrent-ruby (~> 1.0)
      rack (>= 2.2.4, < 4)
    sprockets-rails (3.4.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)
    sshkit (1.22.0)
      mutex_m
      net-scp (>= 1.1.2)
      net-sftp (>= 2.1.2)
      net-ssh (>= 2.8.0)
    stringio (3.1.0)
    syslogger (1.6.4)
    temple (0.8.2)
    terminal-table (3.0.2)
      unicode-display_width (>= 1.1.1, < 3)
    terser (1.1.18)
      execjs (>= 0.3.0, < 3)
    therubyracer (0.12.3)
      libv8 (~> 3.16.14.15)
      ref
    thor (1.3.0)
    tilt (2.2.0)
    timeout (0.4.1)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.5)
    unicode-display_width (2.4.2)
    version_gem (1.1.1)
    warning (1.1.0)
    web-console (4.2.1)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    websocket-driver (0.7.6)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    will_paginate (3.3.1)
    xml-simple (1.1.4)
    zeitwerk (2.6.12)

PLATFORMS
  ruby

DEPENDENCIES
  active_hash
  active_scaffold
  activemerchant (= 1.88.0)
  activesupport-duration-human_string!
  acts_as_list
  acts_as_taggable!
  appsignal
  aws-sdk-ses
  bcrypt_pbkdf
  bootstrap3-datetimepicker-rails (~> 4.14.30)
  byebug
  calendar_date_select
  capistrano
  capistrano-rails
  capistrano-rbenv
  capistrano-systemd-multiservice!
  color
  concurrent-ruby
  dalli
  debug
  ed25519
  ezcrypto (= 0.7.2)
  flatpickr
  fog-aws
  font-awesome-rails
  geocoder (= 1.6.1)
  geokit (= 1.9.0)
  geokit-rails
  gruff
  haml
  hpricot (= 0.8.6)
  http
  i18n
  irb
  jbuilder
  jquery-rails (= 4.3.5)
  jquery-ui-rails (= 6.0.1)
  justrun
  jwt
  libv8-node (= 16.10.0.0)
  link_to_function_helper
  liquid (~> 3.0.0)
  lograge!
  mail (= 2.8.0.rc1)
  make_resourceful!
  marginalia
  meta_request
  mime-types
  mini_magick
  mini_racer
  momentjs-rails (>= 2.9.0)
  money
  mysql2
  nokogiri
  oauth2
  postmark-mitt (= 0.0.11)
  prototype-rails!
  puma (~> 5.0)
  rack
  rack-attack
  rack_attack_admin!
  rails (~> 6.1.0)
  rbpdf
  redis
  request_store
  responders
  rexml
  ripper-tags
  rmagick
  rspec-rails
  ruby-lsp-rails
  ruby-lsp-rspec
  sassc-rails!
  sd_notify
  sidekiq (~> 6)
  sidekiq-batch
  sidekiq-failures
  sidekiq-status
  sinatra (~> 2.2.0)
  spawnling
  sprockets
  streamio-ffmpeg!
  syslogger
  terminal-table
  terser
  therubyracer
  warning
  web-console
  will_paginate
  xml-simple (= 1.1.4)
  zen_form_builder!

RUBY VERSION
   ruby 3.3.0p0

BUNDLED WITH
   2.5.5
```

**Comment by deivid-rodriguez** [comment] 2024-02-05 19:06
Thanks for the report! Can you try minimize the Gemfile a bit and see if this still reproduces? In particular, the Gemfile includes gems pointing to a local `vendor/plugins` folder which has not been provided. But anything you can do to reducing it even further than that by removing gems helps!

**Comment by Nowaker** [comment] 2024-02-05 22:25
`vendor/plugins` gems have no dependencies. These are some archaic gems from the era when gems didn't even exist. These two dependencies are standalone dependencies. They don't pull in anything.

```ruby
Gem::Specification.new do |s|
  s.name = s.summary = 'zen_form_builder'
  s.authors = ['Modern Lifestyle']
  s.version = "0"
  s.files = Dir['lib/**/*']
  s.test_files = Dir['test/**/*']
end
```

**Comment by deivid-rodriguez** [comment] 2024-02-06 16:26
Yeah, I did try to reproduce it by removing those gems and uncommenting `sorbet` but it resolved fine. So probably something more deterministic would help too, maybe a reproduction under docker that we can run on our side or something. But in addition to that, the more you can reduce it, the better!

**Comment by deivid-rodriguez** [comment] 2024-04-05 14:27
I'm going to close this since I can't reproduce it, but feel free to reopen if you can share something self-contained. Thanks!

**Closed by deivid-rodriguez** 2024-04-05 14:27 UTC
Labels: Bundler

**Comment by MichalZaporski** [comment] 2024-05-10 09:40
This problem may occur when you have defined `BUNDLE_FORCE_RUBY_PLATFORM: "true"` in your Bundler config file. To find this file just run `bundle config` and change the line to `BUNDLE_FORCE_RUBY_PLATFORM: "false"`.

**Comment by deivid-rodriguez** [comment] 2024-05-10 10:15
If you are able to provide a way to reproduce this, please open a new issue :pray:.
