### ISSUE TITLE
require hangs on Windows in 2.5.0 but not 2.4.8

### ISSUE THREAD

**Issue by mr-salty** [rubygems/rubygems#1392] opened 2015-11-20 22:27 UTC
Hi, I installed Ruby 2.1.7 and the DevKit from http://rubyinstaller.org/ (32-bit), and updated rubygems to 2.5.0 with 'gem update system'.  My application is hanging during a 'require'.  This does not happen with RubyGems 2.4.8.

I've so far been unable to produce a simple case to reproduce this, but from instrumenting I can see what happens is it blocks forever on RUBYGEMS_ACTIVATION_MONITOR.enter.

The reason this happens is this call to [find_in_unresolved_tree](https://github.com/rubygems/rubygems/blob/65ab980dbc13d1b8e95b7d1f7266406720718c24/lib/rubygems/core_ext/kernel_require.rb#L87) throws a LoadError which gets caught on [line 122](https://github.com/rubygems/rubygems/blob/65ab980dbc13d1b8e95b7d1f7266406720718c24/lib/rubygems/core_ext/kernel_require.rb#L122).  That subsequently does another enter and exit, but we never exited from the enter at the top of the function, so the count is still 1.

This doesn't cause any immediate problems, because although we still hold the lock, we can enter the monitor recursively from the same thread.  The problem happens later due to a call to MultiJson.load (from [multi_json](https://github.com/intridea/multi_json)), which does a require at runtime, and in my case this is happening on a different thread.

Here is the backtrace from the exception (note the line number says 90 instead of 87 due to prints I inserted for debugging).  The part I can't reproduce in a simple test case is what is causing the exception in the first place, but I can keep working on it.

```
Could not find 'permutation' (>= 0) among 62 total gem(s)
Checked in 'GEM_PATH=C:/Users/salty/.gem/ruby/2.1.0;C:/Ruby21/lib/ruby/gems/2.1.0',
 execute `gem env` for more information
["C:/Ruby21/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:318:in `to_specs'",
 "C:/Ruby21/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2572:in `block in traverse'",
 "C:/Ruby21/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2571:in `each'",
 "C:/Ruby21/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2571:in `traverse'",
 "C:/Ruby21/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1044:in `block in find_in_unresolved_tree'",
 "C:/Ruby21/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1043:in `reverse_each'",
 "C:/Ruby21/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1043:in `find_in_unresolved_tree'",
 "C:/Ruby21/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:90:in `require'",
 "C:/Ruby21/lib/ruby/gems/2.1.0/gems/fluentd-0.14.0.pre.1/lib/fluent/command/fluentd.rb:17:in `<top (required)>'",
 "C:/Ruby21/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:72:in `require'",
 "C:/Ruby21/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:72:in `require'",
 "C:/Ruby21/lib/ruby/gems/2.1.0/gems/fluentd-0.14.0.pre.1/bin/fluentd:6:in `<top (required)>'",
 "C:/Ruby21/bin/fluentd:23:in `load'",
 "C:/Ruby21/bin/fluentd:23:in `<main>'"]
```

**Comment by duckinator** [comment] 2016-01-16 14:18
I can't reproduce this with Ruby 2.1.7 and rubygems 2.5.1. @mr-salty, can you try with rubygems 2.5.1 and see if this is resolved?

**Comment by duckinator** [comment] 2016-02-07 00:13
Okay, I haven't created a testcase yet, but I understand what's going on.

Given the code at [commit 45966be3](https://github.com/rubygems/rubygems/tree/45966be372d85520630143090b82b455d287cec6), in [lib/rubygems/core_ext/kernel_require.rb](https://github.com/rubygems/rubygems/blob/45966be372d85520630143090b82b455d287cec6/lib/rubygems/core_ext/kernel_require.rb):

1. It calls `RUBYGEMS_ACTIVATION_MONITOR.enter` on [line 40](https://github.com/rubygems/rubygems/blob/45966be372d85520630143090b82b455d287cec6/lib/rubygems/core_ext/kernel_require.rb#L40).
2. Assume the [call to find_in_unresolved_tree on line 86](https://github.com/rubygems/rubygems/blob/45966be372d85520630143090b82b455d287cec6/lib/rubygems/core_ext/kernel_require.rb#L86) raises a `LoadError`.
3. It calls `RUBYGEMS_ACTIVATION_MONITOR.enter` again on [lines 122](https://github.com/rubygems/rubygems/blob/45966be372d85520630143090b82b455d287cec6/lib/rubygems/core_ext/kernel_require.rb#L122).
4. It calls `RUBYGEMS_ACTIVATION_MONITOR.exit` on either [line 126](https://github.com/rubygems/rubygems/blob/45966be372d85520630143090b82b455d287cec6/lib/rubygems/core_ext/kernel_require.rb#L126) or [line 128](https://github.com/rubygems/rubygems/blob/45966be372d85520630143090b82b455d287cec6/lib/rubygems/core_ext/kernel_require.rb#L129).

At this point, `RUBYGEMS_ACTIVATION_MONITOR.enter` has been called one more time than `RUBYGEMS_ACTIVATION_MONITOR.exit` -- and there is nothing to call `.exit` a second time. *Thus, if you use `require` from a different thread, it will block.*

**Comment by segiddins** [comment] 2016-02-07 00:17
@duckinator maybe wrapping the stuff outside of the rescue with an `ensure` that exits the monitor would help?

**Comment by duckinator** [comment] 2016-02-07 00:33
@segiddins I was thinking something along the same lines, but it's really hard to tell for sure what would help without a testcase.

**Comment by duckinator** [comment] 2016-02-07 00:38
To trigger this, the first call to `require` must meet all of the following requirements:

1. [have an unresolved dependency by the time it gets to line 53](https://github.com/rubygems/rubygems/blob/45966be372d85520630143090b82b455d287cec6/lib/rubygems/core_ext/kernel_require.rb#L53-56)
2. [not already be loaded](https://github.com/rubygems/rubygems/blob/45966be372d85520630143090b82b455d287cec6/lib/rubygems/core_ext/kernel_require.rb#L64-L69)
3. [not be found by Gem::Specification.find_in_unresolved](https://github.com/rubygems/rubygems/blob/45966be372d85520630143090b82b455d287cec6/lib/rubygems/core_ext/kernel_require.rb#L73-L86)

**Comment by duckinator** [comment] 2016-02-07 00:43
I don't understand how `Gem::Specification.unresolved_deps` is used, so I'm not sure how to slip past that first conditional for a testcase.

**Comment by mr-salty** [comment] 2016-02-08 22:48
Thanks for the investigation.  When I reported this I did try to produce a simpler testcase but was unable to.  I can send detailed instructions on how to set up the case I was running into, run some experiments on my machine with extra "print"s, etc.

**Comment by fxn** [comment] 2016-03-01 10:35
I believe I am hitting the same problem, see https://groups.google.com/forum/#!topic/ruby-grape/XHzHUfPzD8g.

**Comment by duckinator** [comment] 2016-03-08 08:51
@fxn I'm having trouble getting your example code to work: https://gist.github.com/duckinator/93c540147f330362810e

**Comment by duckinator** [comment] 2016-03-10 22:05
It looks like it's an issue with both of the environments I tried running it in; other people can run that example code without issue. Not sure what's up.

**Comment by bronzdoc** [comment] 2018-03-31 21:53
We're going to close this because it is to old, but if this problem is still happening with the latest version of RubyGems please feel free to let us know with a new issue!

**Closed by bronzdoc** 2018-03-31 21:53 UTC
Labels: category: #gem or #require, platform: windows, type: bug report
