### ISSUE TITLE
bundle install error with JRuby 9.4.7.0

### ISSUE THREAD

**Issue by n-rodriguez** [rubygems/rubygems#7651] opened 2024-05-11 01:07 UTC
Hi there! I got this error when running `bundle install` with JRuby 9.4.7.0 : 

```
nicolas@MBP-de-Nicolas:~/PROJECTS/CONCERTO/concerto$ bundle install
Fetching https://github.com/discourse/prometheus_exporter.git
git version 2.45.0
git version 2.45.0
```

```
--- ERROR REPORT TEMPLATE -------------------------------------------------------
NoMethodError: undefined method `[]' for nil:NilClass
  /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/source/git/git_proxy.rb:95:in `version'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/source/git/git_proxy.rb:446:in `supports_fetching_unreachable_refs?'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/source/git/git_proxy.rb:207:in `depth'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/source/git/git_proxy.rb:434:in `full_clone?'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/source/git/git_proxy.rb:422:in `depth_args'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/source/git/git_proxy.rb:406:in `extra_clone_args'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/source/git/git_proxy.rb:175:in `clone_needs_extra_fetch?'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/source/git/git_proxy.rb:107:in `checkout'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/source/git.rb:352:in `fetch'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/source/git.rb:179:in `specs'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/source.rb:60:in `spec_names'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/source_map.rb:21:in `block in all_requirements'
          org/jruby/RubyArray.java:2803:in `map'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/source_map.rb:20:in `all_requirements'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/definition.rb:964:in `source_requirements'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/definition.rb:572:in `resolution_packages'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/definition.rb:554:in `resolver'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/definition.rb:631:in `start_resolution'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/definition.rb:314:in `resolve'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/definition.rb:584:in `materialize'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/definition.rb:207:in `specs'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/installer.rb:231:in `ensure_specs_are_compatible!'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/installer.rb:83:in `block in run'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/process_lock.rb:12:in `block in lock'
          org/jruby/RubyIO.java:1197:in `open'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/process_lock.rb:9:in `lock'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/installer.rb:71:in `run'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/installer.rb:23:in `install'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/cli/install.rb:63:in `run'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/cli.rb:247:in `block in install'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/settings.rb:157:in `temporary'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/cli.rb:246:in `install'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/cli.rb:35:in `dispatch'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/cli.rb:29:in `start'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/exe/bundle:28:in `block in <main>'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
          /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/gems/bundler-2.5.10/exe/bundle:20:in `<main>'
          org/jruby/RubyKernel.java:1220:in `load'
          /Users/nicolas/.asdf/installs/ruby/jruby-9.4.7.0/bin/bundle:25:in `<main>'

```

## Environment

```
Bundler       2.5.10
  Platforms   ruby, universal-java-21
Ruby          3.1.4p0 (2024-04-29 revision 597ff08ac1e0d7f05f8f6cc836648725756dd7db) [universal-java-21]
  Full Path   /Users/nicolas/.asdf/installs/ruby/jruby-9.4.7.0/bin/jruby
  Config Dir  /Users/nicolas/.asdf/installs/ruby/jruby-9.4.7.0/etc
RubyGems      3.3.26
  Gem Home    /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0
  Gem Path    /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0
  User Home   /Users/nicolas
  User Path   /Users/nicolas/.local/share/gem/jruby/3.1.0
  Bin Dir     /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.1.0/bin
OpenSSL
  Compiled    JRuby-OpenSSL 0.14.5
  Loaded      JRuby-OpenSSL 0.14.5
  Cert File   /opt/homebrew/Cellar/openjdk/21.0.3/libexec/openjdk.jdk/Contents/Home/lib/security/cacerts
  Cert Dir    /etc/ssl/certs
Tools
  Git
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

Thank you!

**Comment by deivid-rodriguez** [comment] 2024-05-13 14:26
Hei @n-rodriguez! It seems for some reason your git is printing `git --version` output to stderr, not stdout. It'd be nice to be able to reproduce this, did you install git with homebrew?

**Comment by n-rodriguez** [comment] 2024-05-13 15:29
> It seems for some reason your git is printing `git --version` output to stderr, not stdout.

That's what I thought.

> did you install git with homebrew?

Yes

**Comment by deivid-rodriguez** [comment] 2024-05-13 15:42
If you install `git` in some other way, does the error go away?

**Comment by deivid-rodriguez** [comment] 2024-05-13 16:27
Interesting, I'm not able to reproduce myself :disappointed:

**Comment by n-rodriguez** [comment] 2024-05-13 17:14
I can't reproduce it on Linux neither :/

**Comment by deivid-rodriguez** [comment] 2024-05-13 17:59
An approach that will probably work to fix this would be to change `GitProxy` to use stderr as the result if stdout is empty and the process status was "success". But I'd like to get to the bottom of this and reproduce this before we implement such a solution.

**Comment by n-rodriguez** [comment] 2024-05-14 16:36
I've opened an issue : https://github.com/jruby/jruby/issues/8237

**Comment by deivid-rodriguez** [comment] 2024-05-14 18:15
Thanks for investigating. Weirdly my JRuby works just fine... :thinking:

**Comment by deivid-rodriguez** [comment] 2024-05-16 14:23
I'm closing this issue in favor of the JRuby ticket that you opened. It doesn't seem like a JRuby bug, but a Java one, but at least it's closer to the culprit!

**Closed by deivid-rodriguez** 2024-05-16 14:23 UTC
Labels: status: feedback required, Bundler
