### ISSUE TITLE
How to specify using `--no-wrappers` for a gem

### ISSUE THREAD

**Issue by pt-stripe** [rubygems/rubygems#3330] opened 2019-03-21 21:52 UTC
I'm looking to distribute a gem with a platform dependent executable in it (`sorbet`, a Ruby typechecker). When I do:
```
gem install sorbet
```
it won't work because it is a C++ compiled binary. It gives:
```
SyntaxError: /Users/pt/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/sorbet-0.0.1-x86_64-darwin-17/bin/sorbet:1: invalid multibyte char (UTF-8)
  /Users/pt/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/bin/sorbet:23:in `load'
  /Users/pt/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/bin/sorbet:23:in `<top (required)>'
```
but if I do
```
gem install --no-wrappers sorbet
```
then it runs great with `sorbet`.

Now, I'm thinking that folks will want to put this gem in their `Gemfile` to lock the version of the typechecker they want to use and then execute it with `bundle exec sorbet`.

Is there a way to put the:
```
gem 'sorbet'
```
line so that it passes `--no-wrappers` during `gem install`? I tried:
```
$ bundle config build.sorbet --no-wrappers
```
but that seems to pass
```
gem install sorbet -- --no-wrappers
```
which doesn't give the option to `gem install` like I need.

**Comment by deivid-rodriguez** [comment] 2020-11-13 08:53
I think this is the same issue as #88 and would be fix by the solution proposed there?

**Comment by deivid-rodriguez** [comment] 2020-11-30 11:48
Closing as a dupe of #88.

**Closed by deivid-rodriguez** 2020-11-30 11:48 UTC
Labels: Bundler, status: feedback required, type: feature request
