### ISSUE TITLE
GEM_HOME & --no-user-install ineffective

### ISSUE THREAD

**Issue by jankyupeblik** [rubygems/rubygems#2943] opened 2019-10-05 05:38 UTC
Basically same as #687. `GEM_HOME` isn't working with ruby-2.6. `install: --no-user-install` works from `~/.gemrc`, but `--no-user-install` works nowhere as a `gem install` command argument, contrary to `gem install --help`.

**Comment by duckinator** [comment] 2019-10-26 21:04
@jankyupeblik are you still encountering this problem? If so, can you provide the output of running `gem env`? Thanks!

**Comment by jankyupeblik** [comment] 2019-11-02 08:19
@duckinator Yes.

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.6
  - RUBY VERSION: 2.6.5 (2019-10-01 patchlevel 114) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/lib64/ruby/gems/2.6.0
  - USER INSTALLATION DIRECTORY: /home/jan/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /usr/bin/ruby26
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /usr/bin
  - SPEC CACHE DIRECTORY: /home/jan/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/lib64/ruby/gems/2.6.0
     - /home/jan/.gem/ruby/2.6.0
     - /usr/local/lib64/ruby/gems/2.6.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "install" => "--install-dir /home/jan/.gem/ruby/2.6.0"
     - "uninstall" => "--install-dir /home/jan/.gem/ruby/2.6.0"
     - "update" => "--install-dir /home/jan/.gem/ruby/2.6.0"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/lib/llvm/6/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /opt/bin
```

```
$ diff <(gem env) <(GEM_HOME=FOO gem env)
4c4
<   - INSTALLATION DIRECTORY: /usr/lib64/ruby/gems/2.6.0
---
>   - INSTALLATION DIRECTORY: FOO
8c8
<   - EXECUTABLE DIRECTORY: /usr/bin
---
>   - EXECUTABLE DIRECTORY: FOO/bin
15c15
<      - /usr/lib64/ruby/gems/2.6.0
---
>      - FOO
16a17
>      - /usr/lib64/ruby/gems/2.6.0
```

**Comment by stealthHat** [comment] 2020-10-13 05:18
any update?

**Comment by postmodern** [comment] 2021-06-05 09:06
Also ran into this. I was hoping that `gem [install|update] --no-user-install` would install/update the gem in the ruby's rubygems directory (ex: `/usr/lib64/ruby/gems/...`), not `$GEM_HOME` (ex: `gem update --no-user-install rdoc`).

I feel like RubyGems needs to make a clear distinction between installing/updating/removing built-in gems (ex: bigdecimal, rake, rdoc, etc) and user-installed gems (ex: rails).

**Comment by deivid-rodriguez** [comment] 2024-05-09 17:28
I think this is working as expected. `gem install --no-user-install foo` is the same as `gem install foo`, since NOT installing to user home is the default. This is the behavior I'm seeing so I'm going to close this, but feel free to reopen if you disagree.

**Closed by deivid-rodriguez** 2024-05-09 17:28 UTC
Labels: status: triage

**Comment by deivid-rodriguez** [comment] 2024-05-16 16:13
I tried a few of the things reported here and in the other ticket and everything worked as I expected. That's why I closed this ticket.

I was hoping for some clear way to reproduce or confirmation that the problem is now fixed. Your reply comes off as unfriendly and aggressive to me, and it's definitely unhelpful. So I'll wait for someone else to chime in here or report a new ticket if this is not really fixed.

Cheers.

**Comment by jankyupeblik** [comment] 2024-05-18 08:23
> wait for someone else to  ... report a new ticket if this is not really fixed.

That's already why this ticket exists. Because the last item, #687, was ignored, in the same exact fashion as this one.

**Comment by deivid-rodriguez** [comment] 2024-05-20 18:31
As I have already explained, I have tried a few things reported in here and #687 and I could not understand what's wrong. Everything worked as I expected.

**Comment by duckinator** [comment] 2024-05-20 21:07
@jankyupeblik being frustrated that a problem is unresolved for so long is reasonable. However, please keep in mind that if we can't reproduce a problem, the only way we can resolve it is if we are given more information so we _can_ reproduce it.

If you're willing to provide more information about the problem, I'll take my own attempt at reproducing it. If I can reproduce it, I'll do my best to make sure it gets resolved.

Hopefully that's agreeable.

Now, let's try to get to the bottom of this.

---

The only concrete information I have to work with (from both this issue and #687) is:

- In some situations, `gem install` doesn't respect `GEM_HOME`.
- The `gem env` output from 5 years ago.

In order to try to resolve this, I need to reproduce it.

In order to reproduce it, we need a _current-day_ testcase.

When you have the time, can you please try to reproduce it on a still-maintained Ruby version (3.1.5+)?

If you can reproduce it with Ruby 3.1.5+, we need information on your environment.

This would be a good starting point:

- What is an exact command, or combination of commands, that reproduces the problem?
- `gem env` from the still-maintained Ruby version you reproduced this with
- What operating system are you using?
- What version of that operating system?
- How'd you install Ruby?
