### ISSUE TITLE
Git dependencies?

### ISSUE THREAD

**Issue by kholbekj** [rubygems/rubygems#1337] opened 2015-09-04 07:49 UTC
I don't know if this is just not supported at all (couldn't find any documentation?) but when i try to do `get i -g` with a Gemfile, as soon as it hits a `git:` dependency, it breaks with 

```
ERROR:  While executing gem ... (TypeError)
    no implicit conversion of nil into String
```

**Comment by djberg96** [comment] 2015-10-05 23:44
"get i -g" - what's that?

**Comment by drbrain** [comment] 2015-10-05 23:51
I think it's supposed to be `gem i -g` short for `gem install --file` which installs from a `Gemfile`.

Can you paste your Gemfile?

**Comment by kholbekj** [comment] 2015-10-06 07:22
```

**Comment by arthurnn** [comment] 2015-11-18 06:02
having the same problem, or a very similar one:
```
[arthurnn@snowball octohero]$ gem i -g
ERROR:  While executing gem ... (NoMethodError)
    undefined method `version' for nil:NilClass
[arthurnn@snowball octohero]$ gem -v
2.4.5.1
```

on my gemfile i have `gem 'rails', github: 'rails/rails'`

**Comment by bronzdoc** [comment] 2016-01-19 19:56
I think both errors are related, and this may be a duplicate of https://github.com/rubygems/rubygems/issues/1286
there's already a pull request waiting that solves unhandled gem options https://github.com/rubygems/rubygems/pull/1305

**Comment by indirect** [comment] 2016-01-20 03:20
I'd also like to make it clear that this isn't officially supported yet (which is related to the lack of docs). If you need to install Gemfiles, use Bundler while we work on combining them into a single codebase.

**Comment by bronzdoc** [comment] 2016-02-09 05:13
Closing, fixed by https://github.com/rubygems/rubygems/pull/1355

**Closed by bronzdoc** 2016-02-09 05:13 UTC
Labels: bug report, duplicate
