### ISSUE TITLE
bundler installation during rubygems installation does not respect destdir

### ISSUE THREAD

**Issue by Roguelazer** [rubygems/rubygems#4508] opened 2021-04-05 19:26 UTC
### Describe the problem as clearly as you can

Rubygems installs an updated bundler when it installs itself. This bundler installation does not respect the `--destdir` argument to `setup.rb`, making it exceedingly difficult to package rubygems (a situation where any write out side `--destdir` is a fatal error).

This is similar to #3604 but a new breakage in Rubygems 3.2

### Post steps to reproduce the problem

   1. Attempt to install rubygems into an empty destdir (e.g., one with no rubygems installed already) using `ruby setup.rb --destdir /path/to/destdir --no-regenerate-binstubs`

### What were you expecting to happen?

Rubygems and its dependencies should be installed in `/path/to/destdir`

### What actually happened?

The bundler installation attempts to write to the system-wide `GEM_HOME`, which fails. Traceback:

```
    You don't have write permissions for the /opt/ruby2.5/lib64/ruby/2.5.0 directory.
	/home/rpm/rpmbuild/BUILD/ruby25-2.5.9/rubygems-3.2.15/lib/rubygems/installer.rb:712:in `verify_gem_home'
	/home/rpm/rpmbuild/BUILD/ruby25-2.5.9/rubygems-3.2.15/lib/rubygems/installer.rb:880:in `pre_install_checks'
	/home/rpm/rpmbuild/BUILD/ruby25-2.5.9/rubygems-3.2.15/lib/rubygems/installer.rb:286:in `install'
	/home/rpm/rpmbuild/BUILD/ruby25-2.5.9/rubygems-3.2.15/lib/rubygems/commands/setup_command.rb:416:in `block in install_default_bundler_gem'
	/home/rpm/rpmbuild/BUILD/ruby25-2.5.9/rubygems-3.2.15/lib/rubygems/commands/setup_command.rb:412:in `chdir'
	/home/rpm/rpmbuild/BUILD/ruby25-2.5.9/rubygems-3.2.15/lib/rubygems/commands/setup_command.rb:412:in `install_default_bundler_gem'
	/home/rpm/rpmbuild/BUILD/ruby25-2.5.9/rubygems-3.2.15/lib/rubygems/commands/setup_command.rb:183:in `execute'
	/home/rpm/rpmbuild/BUILD/ruby25-2.5.9/rubygems-3.2.15/lib/rubygems/command.rb:323:in `invoke_with_build_args'
	/home/rpm/rpmbuild/BUILD/ruby25-2.5.9/rubygems-3.2.15/lib/rubygems/command_manager.rb:178:in `process_args'
	/home/rpm/rpmbuild/BUILD/ruby25-2.5.9/rubygems-3.2.15/lib/rubygems/command_manager.rb:147:in `run'
	/home/rpm/rpmbuild/BUILD/ruby25-2.5.9/rubygems-3.2.15/lib/rubygems/gem_runner.rb:53:in `run'
```

Looking at `rubygems/installer.rb`, it looks like it doesn't respect `--dest-dir` at all. I am wondering if changing `setup_command.rb` to pass install_dir might help? Something like the following patch?

```
--- lib/rubygems/commands/setup_command.rb.orig	2021-04-05 19:03:27.080859244 +0000
+++ lib/rubygems/commands/setup_command.rb	2021-04-05 19:03:28.840865748 +0000
@@ -405,16 +405,19 @@
     mkdir_p bundler_bin_dir, :mode => 0755
     bundler_spec.executables.each do |e|
       cp File.join("bundler", bundler_spec.bindir, e), File.join(bundler_bin_dir, e)
     end

+    install_dir = File.join(options[:destdir], Gem.dir)
+
     require 'rubygems/installer'

     Dir.chdir("bundler") do
       built_gem = Gem::Package.build(bundler_spec)
       begin
-        installer = Gem::Installer.at(built_gem, env_shebang: options[:env_shebang], format_executable: options[:format_executable], force: options[:force], install_as_default: true, bin_dir: bin_dir, wrappers: true)
+        installer = Gem::Installer.at(built_gem, env_shebang: options[:env_shebang], format_executable: options[:format_executable], force: options[:force], install_as_default: true, bin_dir: bin_dir, wrappers: true,
+                                      build_root: options[:destdir], install_dir: install_dir)
         installer.install
       ensure
         FileUtils.rm_f built_gem
       end
     end
```

Even after that patch, rubygems must be installed with `--no-regenerate-plugins`, since the `regenerate_plugins` command totally ignores the `--dest-dir` option.

As far as I can tell, all other upstreams have just given up on `setup.rb` and are building packages by manually and laboriously copying all of the gem files into place. I'd really like to be able to use your build system to build your software!

**Comment by deivid-rodriguez** [comment] 2021-06-27 12:56
@Roguelazer We're happy to get your suggested fix contributed :+1:.

**Comment by deivid-rodriguez** [comment] 2021-11-05 10:45
This is a duplicate of https://github.com/rubygems/rubygems/issues/3604, just shows the error with a more recent version of `bundler` if I understand correctly. So I'm closing in favor of https://github.com/rubygems/rubygems/issues/3604 and we'll track resolution there.

#5051 should fix this, by the way, in case you want to give it a try!

**Closed by deivid-rodriguez** 2021-11-05 10:45 UTC
Labels: Bundler

**Comment by deivid-rodriguez** [comment] 2021-11-05 12:23
Actually I just managed to reproduce this error even with all my patches. I'll add some more stuff to #5051.

**Comment by deivid-rodriguez** [comment] 2021-11-05 13:09
https://github.com/rubygems/rubygems/pull/5053 will fix this!
