### ISSUE TITLE
Can't activate gem, already activated gem with different version

### ISSUE THREAD

**Issue by milch** [rubygems/rubygems#1309] opened 2015-07-07 14:19 UTC
Over at [fastlane](https://github.com/krausefx/fastlane), we're having a problem with the following error message:

```
ruby/2.2.0/rubygems/specification.rb:2100:in `check_version_conflict': can't activate mime-types-2.6.1, already activated mime-types-1.25.1 (Gem::LoadError)
```

I tried tracking down the problem using the `DEBUG_RESOLVER` environment variable. The problem appears to be in the dependency resolver, as it seems to think that the `mime-types` gem isn't activated yet. It produces the following output for `mime-types`:

``` ruby
[Dependency request
   mime-types (>= 1.16)
    requested by [Activation request
     Gem::Specification.new do |s|
       s.name = "capybara"
       s.version = Gem::Version.new("2.4.4")
       s.installed_by_version = Gem::Version.new("2.4.5")
       s.dependencies =  ...
    for [Dependency request
       capybara (~> 2.4.3)
        requested by [Activation request
         Gem::Specification.new do |s|
           s.name = "fastlane_core"
           s.version = Gem::Version.new("0.9.2")
           s.installed_by_version = Gem::Version.new("2.4.5")
           s.dependencies = ....
          for [Dependency request
           fastlane_core (>= 0.7.2)
            requested by [Activation request
             Gem::Specification.new do |s|
               s.name = "frameit"
               s.version = Gem::Version.new("2.1.0")
               s.installed_by_version = Gem::Version.new("2.4.5")
               s.dependencies = ...
              for [Dependency request  frameit (>= 2.0.1)  requested by nil]
             others ["frameit-2.0.1"]]]]]]]]
```

Of course, `mime-types` version `1.25.1` already satisfies this request and is already activated, so the dependency resolver shouldn't try to activate it again. I verified that it is crashing when trying to activate this dependency using `pry` at line 213 of `rubygems.rb`. 

The issue is detailed in our repository at krausefx/fastlane#379

(Note: I am using version `2.4.8` of `rubygems`)

**Comment by tenderlove** [comment] 2015-07-23 22:55
Is there a way I can reproduce this?  I can tell you that the problem boils down to "you can't correctly resolve gem dependencies at runtime".  However, I *think* that if you add some `gem "mime-types"` statements to the top of **just your bin file**, it would resolve this issue.  I didn't want to offer a potential solution without verifying that it works though.

**Comment by KrauseFx** [comment] 2015-07-24 08:13
@tenderlove Thanks for your response. So in the case of `fastlane`, we'd add

```ruby
gem "mime-types"
```

into [bin/fastlane](https://github.com/KrauseFx/fastlane/blob/master/bin/fastlane) above the first `require` line?

**Comment by tenderlove** [comment] 2015-07-24 17:26
@KrauseFx yes, that is correct.  You can add the version string there too like `gem "mime-types", "1.2.3"` (like you would in the gemspec).  Without the version requirement, it will just use the newest that is on the system.

**NOTE** this is fairly dangerous.  It means that you will be using the newest version of the mime-types gem that is on the system *regardless* of what your gemspec says.  If you're OK with that, then it should be fine.

TBQH, it seems like for binstubs, RubyGems could eagerly resolve the requirements and eliminate this problem.  For bin stubs we know that the particular gem that provided the binfile (in this case `fastlane`) will want to activate all it's dependencies, so we could just do it in the binstub and eliminate this problem.  But as a work around, adding the `gem` declaration in your binfile *should* fix it.

**Comment by segiddins** [comment] 2015-07-24 17:27
@tenderlove that shouldn't be necessary, RubyGems should be doing that implicitly when it activates a strict/specific version of `fastlane`

**Comment by tenderlove** [comment] 2015-07-24 17:28
IOW, I don't think binstubs should lazily activate dependencies.

**Comment by tenderlove** [comment] 2015-07-24 17:30
@segiddins I don't think binstubs specify a strict version.  Also AFAIK, even if you specify a strict version, [it won't always walk the full dep tree eagerly](https://github.com/rubygems/rubygems/blob/503556fa67769f5c261f01116d5272e85f6a0e88/lib/rubygems/specification.rb#L1397-1402).

**Comment by copiousfreetime** [comment] 2016-04-30 21:57
@tenderlove @segiddins Is there still a bug here or is everything working as designed?

**Comment by segiddins** [comment] 2016-04-30 22:25
Still something we could improve.

**Comment by copiousfreetime** [comment] 2016-04-30 22:32
Alright, marking this for feedback/discussion then.

**Comment by bronzdoc** [comment] 2018-03-30 02:35
Closing since this isn't a bug and has been ide for a while

**Closed by bronzdoc** 2018-03-30 02:35 UTC

**Comment by segiddins** [comment] 2018-04-07 03:26
This has actually been fixed with `Gem.activate_bin_path`
