### ISSUE TITLE
feature request - to show native library dependencies

### ISSUE THREAD

**Issue by jnylund** [rubygems/rubygems#3567] opened 2020-04-28 15:56 UTC
Hi , I am looking for a utility that would list all the native libraries that my gems depend on.

**bundle viz** - this is super cool, but seems to only show ruby gems that are depended on, would be great if this could include native libraries.

I found this gem that lists all the gems that have native extensions -https://github.com/caius/bundler-native-gems. - problem is it only lists the gems, not the native libraries they depend on.

I think this would be cool so we could watch for security updates that change these libraries for potential regressions.

Let me know if this is already a capability somewhere and I missed it.

**Comment by MSP-Greg** [comment] 2020-04-28 16:21
Info about the native libraries is normally contained in the extconf.rb file(s), but that doesn't have any info about what version is used etc.

> list all the native libraries that my gems depend on.

You would probably need to review all of your gems and determine  version info about the native libraries (which hopefully is available), then use that to compare against a list of security updates.

Some examples in stdlib/default gems would be:
```
OpenSSL::OPENSSL_VERSION
OpenSSL::OPENSSL_LIBRARY_VERSION
Psych::LIBYAML_VERSION 
```

Depending on how the gems are compiled (static or shared), the issue may involve runtime vs build time...  Also, some gems vendor/embed the native libraries.

**Comment by jnylund** [comment] 2020-04-29 19:22
Agree, very big hassle to do manually, seems like it could be automated, especially if there was a convention for extconf.rb...doesn't seem to be right now, but I am guessing there are a finite number of ways dependent libraries could be referenced.

**Comment by MSP-Greg** [comment] 2020-04-29 20:56
Re parsing extconf.rb files -

If one parsed `dir_config`, that often has the 'package' name, but not always.  I've seen gems using OpenSSL use both `dir_config 'openssl'` and `dir_config 'ssl'`.

If one parsed `have_library`, that also has problems, since common package names don't always translate to library names.  With OpenSSL, the libraries are 'crypto' and 'ssl' (or 'libcrypto' and 'libssl', depending on the OS/build tools).

The best solution might be to have RG/Bundler recommend a metadata tag to be used in the gemspec that defined what external libraries were used, preferably with names matching apt-get, brew, or MSYS2 pacman...

**Comment by deivid-rodriguez** [comment] 2020-11-05 14:07
I think this feature request is basically a duplicate of https://github.com/rubygems/rubygems/issues/1296?

**Comment by deivid-rodriguez** [comment] 2020-11-19 13:36
Closing as a duplicate!

**Closed by deivid-rodriguez** 2020-11-19 13:36 UTC
Labels: Bundler, status: feedback required
