### ISSUE TITLE
a ~> requirement ending in a non-numeric segment is satisfied by unexpected versions

### ISSUE THREAD

**Issue by baroquebobcat** [rubygems/rubygems#198] opened 2011-09-27 18:13 UTC
should bump do this?

`"~> 3.1.0.rc1"` is satisfied by 3.1.1, when you'd expect it to be satisfied only by `"3.1.0.x"` where x > `rc1`.

*Possible outcomes*

We could change the behavior of bump, so it updates the last numeric segment instead of the second to last.

Or we could change ~>'s behavior to either
  a) use the last numeric segment as the max allowable when the last segment is a string
  b) warn users when the last segment is a string that it won't work as expected

changing ~>'s behavior would probably be safer as I don't know enough about how `bump` is used.

**Comment by duckinator** [comment] 2016-01-06 03:20
This issue's been idle been open for over four years, and idle for over two years, and the functionality in question behaves as intended. I think it's reasonable to close this.

**Closed** 2016-01-06 03:39 UTC
Labels: category - other
