### ISSUE TITLE
[Small bug or not enough information] system 'gem install rbt' fails

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems#4845] opened 2021-08-15 16:07 UTC
I'm having a problem or would like to suggest a feature.

My current problem is a small, strange bug.

This issue is related to:

  - [ ] Network problems
  - [X] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [ ] Other

Here are my current environment details:

I am using jruby right now; current version of ruby is 2.5.8.

I am starting "jruby irb" where irb is in the bin/ subdirectory.

I then do the following:

    system 'gem install rbt'

Next the output on the commandline as-is:

Ignoring atk-3.4.3 because its extensions are not built. Try: gem pristine atk --version 3.4.3
Ignoring cairo-gobject-3.4.3 because its extensions are not built. Try: gem pristine cairo-gobject --version 3.4.3
Ignoring gdk_pixbuf2-3.4.3 because its extensions are not built. Try: gem pristine gdk_pixbuf2 --version 3.4.3
Ignoring gio2-3.4.3 because its extensions are not built. Try: gem pristine gio2 --version 3.4.3
Ignoring glib2-3.4.3 because its extensions are not built. Try: gem pristine glib2 --version 3.4.3
Ignoring gobject-introspection-3.4.3 because its extensions are not built. Try: gem pristine gobject-introspection --version 3.4.3
Ignoring pango-3.4.7 because its extensions are not built. Try: gem pristine pango --version 3.4.7
ERROR:  While executing gem ... (NoMethodError)
    undefined method `request' for nil:NilClass
=> false

---
You can ignore the "gem pristine" output. I am having some ruby-gtk stuff that I am
re-building right now, for ruby 2.5.8. Normally I use ruby 3.x but jruby is lagging
behind so now I have to test on 2.5.8. Anyway.

The issue I am reporting it, in case it is not noticable, this here:

ERROR:  While executing gem ... (NoMethodError)
    undefined method `request' for nil:NilClass

I understand that there is some nil object, but I don't know how, where
and why. Note that other gems that I install via:

   system 'gem install XYZ'

work fine. I just installed opn, colours gem and some more.

For rbt this fails. No idea why, but this is why I report this here.

I believe that in the event that .request happens on a .nil
object more information should be shown to the user.

Right now this is a black box to me. I have no idea why it
failed. The output is not specific.

So my proposal is to make this information more verbose
and thus more useful. No idea why the output is only
like 6 words ... whoever wrote this must have hated 
verbose output. ;)

Gem version was:

system 'gem --version'

    3.2.25

I just updated this as well. But I don't think this matters - the error message
should be more verbose please so that I can fix the issue. Right now I
have a .request call on a nil object - how does this help me with anything?
Thanks.

**Comment by deivid-rodriguez** [comment] 2021-08-16 07:18
Closing as a duplicate of https://github.com/rubygems/rubygems/issues/4338. Please search for existing issues before opening new ones.

Thank you!

**Closed by deivid-rodriguez** 2021-08-16 07:18 UTC
Labels: RubyGems
