### ISSUE TITLE
SSL verification error - certificate not valid since update on 15th May 2020

### ISSUE THREAD

**Issue by fmonvoisin** [rubygems/rubygems#3640] opened 2020-05-19 15:59 UTC
I'm having a problem with rubygems certificate update since 15th may 2020

My current problem is to update gem on centos

This issue is related to:

  - [x] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:
OS : CentOS
```
$ gem env version
3.1.2
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

I have the following error : 
```
# gem update --system
ERROR:  SSL verification error at depth 0: certificate is not yet valid (9)
ERROR:  Certificate /C=US/ST=California/L=San Francisco/O=Fastly, Inc./CN=l.ssl.fastly.net not valid until 2020-05-15T14:31:03Z
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate is not yet valid) (https://rubygems.org/specs.4.8.gz)
```

Can someone please help me ?

Thank you

**Comment by MSP-Greg** [comment] 2020-05-19 17:48
I tried to repo, and using Ruby 2.7.1 and OpenSSL 1.1.1g, everything worked fine.  Please see:

https://bundler.io/v2.0/guides/rubygems_tls_ssl_troubleshooting_guide.html#automated-ssl-check

The command listed should probably be changed to:
```
ruby -ropen-uri -e "eval URI.open('https://git.io/vQhWq').read"
```

If you're still having problems, the top section of output ('Here's your Ruby and OpenSSL environment:') would be needed to see what your issue is...

**Comment by indirect** [comment] 2020-05-19 18:04
@MSP-Greg I just realized that using Ruby to download a script to diagnose SSL issues... from GitHub, over SSL... is maybe not the best idea. I think it should probably be changed to:

```
curl -s 'https://git.io/vQhWq' | ruby
```

**Comment by fmonvoisin** [comment] 2020-05-19 18:10
```
Here's your Ruby and OpenSSL environment:

Ruby:           2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
RubyGems:       3.1.2
Bundler:        2.1.2
Compiled with:  OpenSSL 1.0.2k  26 Jan 2017
Loaded version: OpenSSL 1.0.2k-fips  26 Jan 2017
SSL_CERT_FILE:  /etc/pki/tls/cert.pem
SSL_CERT_DIR:   /etc/pki/tls/certs

With that out of the way, let's see if you can connect to rubygems.org...

Bundler connection to rubygems.org:       failed  ❌  (bad argument (expected Bundler::URI object or Bundler::URI string))
ERROR:  SSL verification error at depth 0: certificate is not yet valid (9)
ERROR:  Certificate /C=US/ST=California/L=San Francisco/O=Fastly, Inc./CN=l.ssl.fastly.net not valid until 2020-05-15T14:31:03Z
RubyGems connection to rubygems.org:      failed  ❌  (certificate verification)
Ruby net/http connection to rubygems.org: failed  ❌

Unfortunately, this Ruby can't connect to rubygems.org. 😡
Your Ruby can't connect to rubygems.org because you are missing the certificate files OpenSSL needs to verify you are connecting to the genuine rubygems.org servers.
```

**Comment by MSP-Greg** [comment] 2020-05-19 18:12
@indirect

Agreed.  IF RG/Bundler is broke, likely that Ruby is also.  That command may not work for Windows users, I'll see if I can write a PowerShell command for it.

BTW, 'https://git.io/vQhWq' is from your fork of ruby-ssl-check?

**Comment by indirect** [comment] 2020-05-19 18:15
@MSP-Greg my fork is actually the original, transferred to rubygems. https://github.com/indirect/ruby-ssl-check redirects to https://github.com/rubygems/ruby-ssl-check now. ¯\_(ツ)_/¯

**Comment by MSP-Greg** [comment] 2020-05-19 18:16
@fmonvoisin

```
Compiled with:  OpenSSL 1.0.2k  26 Jan 2017
Loaded version: OpenSSL 1.0.2k-fips  26 Jan 2017
```

JFYI, OpenSSL 1.0.2 is EOL and stopped at 1.0.2u, so your system is a bit outdated.  Also, I've never worked with the OpenSSL 'fips' releases, especially given that your Ruby was compiled with a standard (non fips) release.  Can you update your system to OpenSSL 1.0.2u?

**Comment by lamont-granquist** [comment] 2020-05-20 19:13
"not valid until 2020-05-15T14:31:03Z"

is the time set wrong on the host?

**Comment by deivid-rodriguez** [comment] 2020-09-03 20:02
Is this still an issue?

**Comment by deivid-rodriguez** [comment] 2020-09-17 09:35
I'll assume it's not!

**Closed by deivid-rodriguez** 2020-09-17 09:35 UTC
Labels: RubyGems, status: user feedback required

**Comment by snex** [comment] 2021-05-16 19:44
I am having this issue. Slightly different output than @fmonvoisin :

```
Here's your Ruby and OpenSSL environment:

Ruby:           2.7.1p83 (2020-03-31 revision a0c7c23c9cec0d0ffcba012279cd652d28ad5bf3) [x86_64-linux]
RubyGems:       3.1.2
Bundler:        2.1.4
Compiled with:  OpenSSL 1.1.1d  10 Sep 2019
Loaded version: OpenSSL 1.1.1f  31 Mar 2020
SSL_CERT_FILE:  /usr/lib/ssl/cert.pem
SSL_CERT_DIR:   /usr/lib/ssl/certs

With that out of the way, let's see if you can connect to rubygems.org...

Bundler connection to rubygems.org:       failed  ❌  (certificate verification)
ERROR:  SSL verification error at depth 0: ok (0)
RubyGems connection to rubygems.org:      failed  ❌  (certificate verification)
Ruby net/http connection to rubygems.org: failed  ❌

Unfortunately, this Ruby can't connect to rubygems.org. 😡
Your Ruby can't connect to rubygems.org because you are missing the certificate files OpenSSL needs to verify you are connecting to the genuine rubygems.org servers.```

**Comment by deivid-rodriguez** [comment] 2021-05-17 16:33
Can you try upgrading rubygems (`gem update --system`)? If that works, could you propose a patch to https://github.com/rubygems/ruby-ssl-check to recommend upgrading rubygems as a potential fix?

**Comment by snex** [comment] 2021-05-17 16:34
```gem update --system``` yields a similar error:

```ERROR:  SSL verification error at depth 0: ok (0)
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate rejected) (https://rubygems.org/specs.4.8.gz)```

**Comment by deivid-rodriguez** [comment] 2021-05-17 16:45
Oh, I always forget, since your ruby installation can't connect to the internet, you can't simply upgrade rubygems in the standard way... :sweat:. Can you try these instructions instead: https://bundler.io/v2.2/guides/rubygems_tls_ssl_troubleshooting_guide.html#updating-ca-certificates?

**Comment by snex** [comment] 2021-05-17 16:49
I have not tried that since manually trusting certificates when the entire problem is an invalid certificate kind of defeats the point of SSL. The server is clearly giving me the wrong certificate for only my desktop, for some bizarre reason.

**Comment by deivid-rodriguez** [comment] 2021-05-17 17:04
The manual update has the same effect as the official update (download the certificates ruby needs to talk to rubygems.org, and that your current installation is missing, and put them in a location rubygems looks at when talking to rubugems.org. I linked to the solution directly, but above it there's a nice explanation of what's going on: https://bundler.io/v2.2/guides/rubygems_tls_ssl_troubleshooting_guide.html#the-problems.

**Comment by snex** [comment] 2021-05-17 17:06
The problem is, if I can't trust the certificate being served via the website, I can't trust any certificate links I might want to install manually.

**Comment by snex** [comment] 2021-05-17 17:08
By the way, this only stopped working recently, as in sometime within the last month or so.

**Comment by deivid-rodriguez** [comment] 2021-05-17 17:20
I don't know much about this but I did read the troubleshooting guide I told you to read, and given that you also can't connect to rubygems.org via curl or your browser, it sounds like also your browser and OS are missing the root certificates rubygems.org now needs. In particular, the one from GlobalSign. If you download the certificate manually and put it at the location rubygems needs, that should fix the issue for you although the won't fix your browser or OS, I guess you probably will need to update those too. Anyways, I can't really be of more help here :man_shrugging:.

**Comment by lamont-granquist** [comment] 2021-05-17 22:23
> By the way, this only stopped working recently, as in sometime within the last month or so.

It looks like Fastly updated their certs on May 15th.

The new certs are probably signed with a new CA cert chain.

If your desktop has an outdated set of CA certs this can cause sites to suddenly stop working.  As to why you'd get different results on your desktop and your laptop you'd have to take that up with Fastly.

And if you can upgrade your distribution CA certs, then use a web browser to download the GlobalSign CA cert over https and you install that where ruby can find it, then you haven't bypassed any SSL protections.

**Comment by snex** [comment] 2021-05-18 03:13
I am using Ubuntu 20.04 LTS, with certs up-to-date. It's possible that Ubuntu dropped the ball here, but I have had friends also running Ubuntu that aren't seeing the problem.
