### ISSUE TITLE
bundle/inline leaves gem executable unusable

### ISSUE THREAD

**Issue by svenfuchs** [rubygems/rubygems#3301] opened 2019-05-25 15:45 UTC
Not sure if I'm not using this right, but it looks like `bundler/inline` leaves the `gem` executable unusable. 

Also, I would have expected `Bundle.clean_env` to fix that, but it doesn't, while manually resetting `ENV` to `Bundler.original_env`, does.

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'json'
end

# doesn't fix it
# Bundler.clean_env

# fixes it
# ENV.replace(Bundler.original_env)

require 'fileutils'
include FileUtils

mkdir_p 'tmp'
chdir 'tmp'

File.write 'test.gemspec', <<~str
  Gem::Specification.new do |s|
    s.name        = 'test'
    s.version     = '0.0.1'
    s.licenses    = ['MIT']
    s.summary     = "This is test"
    s.description = "This is test."
    s.authors     = ["Travis CI"]
    s.email       = 'contact@travis-ci.com'
    s.homepage    = 'https://github.org/travis-ci/test'
  end
str

puts `gem build test.gemspec`
```

```
Traceback (most recent call last):
        5: from /Users/sven/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        4: from /Users/sven/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        3: from /Users/sven/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/setup.rb:20:in `<top (required)>'
        2: from /Users/sven/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler.rb:101:in `setup'
        1: from /Users/sven/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler.rb:135:in `definition'
/Users/sven/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/definition.rb:32:in `build': /Users/sven/Development/projects/travis/dpl/tmp/Gemfile not found (Bundler::GemfileNotFound)
```

**Comment by deivid-rodriguez** [comment] 2020-10-02 21:09
Hi, sorry I never got back here.

So, this is standard bundler behaviour (not specific to `bundler/inline`). Once `bundler` is setup, `-rbundler/setup` is added to `RUBYOPT` so that future subprocesses will use the same environment we just loaded. The way out of this `bundler` provides in `Bundler.with_(clean|original)_env`.

Not sure if this was a good choice, specifically I've seen places (like this one) where the specific addition of `RUBYOPT` surprises people and leads to unexpected behaviour. However, not sure how I would go about changing this, there's certainly places where this is desired, and since there's a way out of this, I'd rather leave things as they are, indeed.

**Comment by deivid-rodriguez** [comment] 2020-10-16 08:41
I'll close this for now but let us know if you have any further thoughts on this!

**Closed by deivid-rodriguez** 2020-10-16 08:41 UTC
Labels: Bundler, status: feedback required
