### ISSUE TITLE
Rubygems resolver appears to have an issue when large possibilities set

### ISSUE THREAD

**Issue by electrofelix** [rubygems/rubygems#5843] opened 2022-08-17 15:10 UTC
### Describe the problem as clearly as you can

On Arch linux vagrant is using rubygems to perform dependency resolving to install plugins. It calls into rubygems code /usr/lib/ruby/3.0.0/rubygems/resolver when performing plugin installs and ultimately fails with a conflict trying to resolve dependency versions.

There appears to be an issue when there is a large number of dependency possibilities due to a dependency having a wide range for a particular gem triggers an issue, however it is not triggered when specifying such dependency ranges directly by themselves and processing via bundler.

The issue was initially flagged as hashicorp/vagrant#12837 and after performing some initial debug by changing the resolution constraints and seeing it work, further setting `DEBUG_RESOLVER=1` as well as adding some extra statements to see what was happening failed to explain what was occurring within rubygems resolver that resulted in the it returning the message that net-ssh-6.2.0.rc2 could not satisfy the constraint `>= 2.6.5, < 7.0.0`.

### Did you try upgrading RubyGems?

As this is the distro managed version, it's a little less straight forward. However the latest release is rubygems 3.3.19-1, which is only one release behind 3.3.20.

I have run `sudo gem update --system`, and re-run the steps, but it had no effect and I'm not entirely sure whether it actually used the newer release.

### Post steps to reproduce the problem

Used vagrant + libvirt plugin installed on a host system to provide a pristine test guest environment
```
git clone https://github.com/vagrant-libvirt/vagrant-libvirt-qa
cd vagrant-libvirt-qa
vagrant up archlinux
vagrant ssh archlinux
```

in the guest
```
mkdir test
cat <<EOF > test/Gemfile
# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem 'net-scp', '3.0.0'
gem 'net-ssh', '6.2.0.rc2'
gem 'vagrant', :git => 'https://github.com/hashicorp/vagrant.git', :ref => 'v2.3.0'
EOF

bundle config --local path vendor/bundle
bundle install
bundle exec vagrant plugin install vagrant-libvirt
```

### What were you expecting to happen?

vagrant calling into bundler/rubygems resolver should see that net-ssh 6.2.0.rc2 is a valid version for the constraint '>= 2.6.5, < 7.0.0', and complete the installation of the plugins.

### What actually happened?

```
You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies net-ssh (>= 2.6.5, < 7.0.0) and net-ssh (= 6.2.0.rc2)
  Activated net-ssh-6.2.0.rc2
  which does not match conflicting dependency (>= 2.6.5, < 7.0.0)

  Conflicting dependency chains:
    net-ssh (= 6.2.0.rc2), 6.2.0.rc2 activated

  versus:
    net-scp (= 3.0.0), 3.0.0 activated, depends on
    net-ssh (>= 2.6.5, < 7.0.0)

  Gems matching net-ssh (>= 2.6.5, < 7.0.0):
    net-ssh-6.2.0.rc2
```

### Run `gem env` and paste the output below

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.20
  - RUBY VERSION: 3.0.4 (2022-04-12 patchlevel 208) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/lib/ruby/gems/3.0.0
  - USER INSTALLATION DIRECTORY: /home/vagrant/.local/share/gem/ruby/3.0.0
  - RUBY EXECUTABLE: /usr/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /usr/bin
  - SPEC CACHE DIRECTORY: /home/vagrant/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux
  - GEM PATHS:
     - /usr/lib/ruby/gems/3.0.0
     - /home/vagrant/.local/share/gem/ruby/3.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
     - "gem" => "--user-install"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/bin
     - /usr/bin/site_perl
     - /usr/bin/vendor_perl
     - /usr/bin/core_perl
```

**Comment by electrofelix** [comment] 2022-08-17 15:12
Copying debug efforts originally posted at https://github.com/hashicorp/vagrant/issues/12837#issuecomment-1216826334

---

It doesn't appear to be an issue with the rc2 suffix, I did some digging and it appears to be able to correctly resolve 6.2.0.rc2 as satisfying the dependency, but still rejects it.

I couldn't pin it down exactly what is going on, but the resolver appears to do something a little weird in that it tries to generate every version between the spec bounds and perform resolving, which means for net-ssh, it generates every version between 2.6.5 and 7.0.0 and checks whether it satisfies the constraints.

Following tweak to the gem specifications is sufficient to allow everything to work on arch:
```
diff -u /opt/vagrant/embedded/gems/2.3.0/specifications/net-scp-3.0.0.gemspec.orig /opt/vagrant/embedded/gems/2.3.0/specifications/net-scp-3.0.0.gemspec
--- /opt/vagrant/embedded/gems/2.3.0/specifications/net-scp-3.0.0.gemspec.orig	2022-08-16 15:47:12.928174587 +0000
+++ /opt/vagrant/embedded/gems/2.3.0/specifications/net-scp-3.0.0.gemspec	2022-08-16 15:46:37.998463158 +0000
@@ -27,11 +27,11 @@
   end
 
   if s.respond_to? :add_runtime_dependency then
-    s.add_runtime_dependency(%q<net-ssh>.freeze, [">= 2.6.5", "< 7.0.0"])
+    s.add_runtime_dependency(%q<net-ssh>.freeze, [">= 6.0.0", "< 7.0.0"])
     s.add_development_dependency(%q<test-unit>.freeze, [">= 0"])
     s.add_development_dependency(%q<mocha>.freeze, [">= 0"])
   else
-    s.add_dependency(%q<net-ssh>.freeze, [">= 2.6.5", "< 7.0.0"])
+    s.add_dependency(%q<net-ssh>.freeze, [">= 6.0.0", "< 7.0.0"])
     s.add_dependency(%q<test-unit>.freeze, [">= 0"])
     s.add_dependency(%q<mocha>.freeze, [">= 0"])
   end
```

Which suggests to me at least, that maybe some limit is being hit when trying to do the resolving the way that it's currently being approached rather than it not being satisfied by net-ssh-6.2.0rc2.

**Comment by electrofelix** [comment] 2022-08-17 15:13
Copying debug effort originally posted at https://github.com/hashicorp/vagrant/issues/12837#issuecomment-1216985386

---
The lowest number I could modify that dependency range to and have it work is `3.2.0`, going to `3.1.0` fails with a slightly different message:
```
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
/opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/bundler.rb:860:in `find_all': can't modify frozen Gem::Dependency: <Gem::Dependency type=:runtime name="net-ssh" requirements="< 7.0.0, >= 2.6.5"> (FrozenError)
	from /usr/lib/ruby/3.0.0/rubygems/resolver/composed_set.rb:54:in `block in find_all'
	from /usr/lib/ruby/3.0.0/rubygems/resolver/composed_set.rb:53:in `map'
	from /usr/lib/ruby/3.0.0/rubygems/resolver/composed_set.rb:53:in `find_all'
	from /usr/lib/ruby/3.0.0/rubygems/resolver.rb:203:in `find_possible'
	from /usr/lib/ruby/3.0.0/rubygems/resolver.rb:228:in `search_for'
	from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:11:in `block in search_for'
	from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
	from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:10:in `search_for'
	from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:779:in `possibilities_for_requirement'
	from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:761:in `push_state_for_requirements'
	from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
	from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:727:in `activate_new_spec'
	from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
	from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:254:in `process_topmost_state'
	from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:182:in `resolve'
	from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:43:in `resolve'
	from /usr/lib/ruby/3.0.0/rubygems/resolver.rb:190:in `resolve'
	from /usr/lib/ruby/3.0.0/rubygems/request_set.rb:411:in `resolve'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/bundler.rb:591:in `internal_install'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/bundler.rb:355:in `install'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/plugin/manager.rb:138:in `block in install_plugin'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/plugin/manager.rb:148:in `install_plugin'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/plugins/commands/plugin/action/install_gem.rb:30:in `call'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/action/warden.rb:48:in `call'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/action/builder.rb:180:in `call'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/action/runner.rb:101:in `block in run'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/action/runner.rb:101:in `run'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/plugins/commands/plugin/command/base.rb:14:in `action'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/plugins/commands/plugin/command/install.rb:70:in `block in execute'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/plugins/commands/plugin/command/install.rb:69:in `each'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/plugins/commands/plugin/command/install.rb:69:in `execute'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/plugins/commands/plugin/command/root.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/cli.rb:67:in `execute'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/bin/vagrant:248:in `<main>'
```

going to `2.6.0` as the lower range also works.

Enabling `DEBUG_RESOLVER=1` dumps the following for net-ssh when the constraint in net-scp is set to `>= 2.6.5, < 7.0.0`
```
:  75: Requiring nested dependencies (net-ssh (>= 2.6.5, < 7.0.0))
:  75: Creating possibility state for net-ssh (>= 2.6.5, < 7.0.0) (1 remaining)
:  76: Attempting to activate [net-ssh-6.2.0.rc2, net-ssh-2.6.5, net-ssh-2.6.6, net-ssh-2.6.7, net-ssh-2.6.8, net-ssh-2.7.0, net-ssh-2.8.0, net-ssh-2.9.0, net-ssh-2.9.1, net-ssh-2.9.2, net-ssh-2.9.4, net-ssh-3.0.1, net-ssh-3.0.2, net-ssh-3.1.0, net-ssh-3.1.1, net-ssh-3.2.0, net-ssh-4.0.0, net-ssh-4.0.1, net-ssh-4.1.0, net-ssh-4.2.0, net-ssh-5.0.0, net-ssh-5.0.1, net-ssh-5.0.2, net-ssh-5.1.0, net-ssh-5.2.0, net-ssh-6.0.0, net-ssh-6.0.1, net-ssh-6.0.2, net-ssh-6.1.0]
:  76: Found existing spec ([net-ssh-6.2.0.rc2])
:  76: Unsatisfied by existing spec ([net-ssh-6.2.0.rc2])
:  76: Unwinding for conflict: net-ssh (>= 2.6.5, < 7.0.0) to -1
```

Compared to when the lower bound is 3.2.0:
```
  75: Activated net-scp at [net-scp-3.0.0, net-scp-3.0.0]
:  75: Requiring nested dependencies (net-ssh (>= 3.2.5, < 7.0.0))
:  75: Creating possibility state for net-ssh (>= 3.2.5, < 7.0.0) (1 remaining)
:  76: Attempting to activate [net-ssh-6.2.0.rc2, net-ssh-4.0.0, net-ssh-4.0.1, net-ssh-4.1.0, net-ssh-4.2.0, net-ssh-5.0.0, net-ssh-5.0.1, net-ssh-5.0.2, net-ssh-5.1.0, net-ssh-5.2.0, net-ssh-6.0.0, net-ssh-6.0
.1, net-ssh-6.0.2, net-ssh-6.1.0]
:  76: Found existing spec ([net-ssh-6.2.0.rc2])
:  76: Creating possibility state for net-scp (~> 3.0.0) (2 remaining)
```

In general it looks like there are some issues in the underlying ruby bundler around how it tries to do some filtering of the valid possibilites in /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb

Adding some debug to that file to output the filtered_set:
```
      def attempt_to_filter_existing_spec(vertex)
        filtered_set = filtered_possibility_set(vertex)
        if name == "net-ssh"
          debug(depth) { "filtered_set => #{filtered_set}" }
        end
        if !filtered_set.possibilities.empty?
          activated.set_payload(name, filtered_set)
          new_requirements = requirements.dup
          push_state_for_requirements(new_requirements, false)
        else
          create_conflict
          debug(depth) { "Unsatisfied by existing spec (#{vertex.payload})" }
          unwind_for_conflict
        end
      end
```

gives the following for the failed resolving:
```
...
:  75: Creating possibility state for net-ssh (>= 2.6.5, < 7.0.0) (1 remaining)
:  76: Attempting to activate [net-ssh-6.2.0.rc2, net-ssh-2.6.5, net-ssh-2.6.6, net-ssh-2.6.7, net-ssh-2.6.8, net-ssh-2.7.0, net-ssh-2.8.0, net-ssh-2.9.0, net-ssh-2.9.1, net-ssh-2.9.2, net-ssh-2.9.4, net-ssh-3.0.1, net-ssh-3.0.2, net-ssh-3.1.0, net-ssh-3.1.1, net-ssh-3.2.0, net-ssh-4.0.0, net-ssh-4.0.1, net-ssh-4.1.0, net-ssh-4.2.0, net-ssh-5.0.0, net-ssh-5.0.1, net-ssh-5.0.2, net-ssh-5.1.0, net-ssh-5.2.0, net-ssh-6.0.0, net-ssh-6.0.1, net-ssh-6.0.2, net-ssh-6.1.0]
:  76: Found existing spec ([net-ssh-6.2.0.rc2])
:  76: filtered_set => []
:  76: Unsatisfied by existing spec ([net-ssh-6.2.0.rc2])
:  76: Unwinding for conflict: net-ssh (>= 2.6.5, < 7.0.0) to -1

:   0: Finished resolution (76 steps) (Took 5.012015612 seconds) (2022-08-16 17:57:02 +0000)
```

and for the successful
```
...
:  75: Attempting to activate [net-scp-3.0.0, net-scp-3.0.0]
:  75: Activated net-scp at [net-scp-3.0.0, net-scp-3.0.0]
:  75: Requiring nested dependencies (net-ssh (>= 3.2.0, < 7.0.0))
:  75: Creating possibility state for net-ssh (>= 3.2.0, < 7.0.0) (1 remaining)
:  76: Attempting to activate [net-ssh-6.2.0.rc2, net-ssh-3.2.0, net-ssh-4.0.0, net-ssh-4.0.1, net-ssh-4.1.0, net-ssh-4.2.0, net-ssh-5.0.0, net-ssh-5.0.1, net-ssh-5.0.2, net-ssh-5.1.0, net-ssh-5.2.0, net-ssh-6.0.0, net-ssh-6.0.1, net-ssh-6.0.2, net-ssh-6.1.0]
:  76: Found existing spec ([net-ssh-6.2.0.rc2])
:  76: filtered_set => [net-ssh-6.2.0.rc2]
:  76: Creating possibility state for net-scp (~> 3.0.0) (2 remaining)
...
```

I don't know exactly why this is happening, but it does look like the issue is rubygems resolver rather than vagrant.

**Comment by electrofelix** [comment] 2022-08-17 15:20
When making the same change with the vendored bundle:
```
diff -u vendor/bundle/ruby/3.0.0/specifications/net-scp-3.0.0.gemspec.orig vendor/bundle/ruby/3.0.0/specifications/net-scp-3.0.0.gemspec
--- vendor/bundle/ruby/3.0.0/specifications/net-scp-3.0.0.gemspec.orig	2022-08-17 15:11:15.673369019 +0000
+++ vendor/bundle/ruby/3.0.0/specifications/net-scp-3.0.0.gemspec	2022-08-17 15:11:18.133395625 +0000
@@ -27,11 +27,11 @@
   end
 
   if s.respond_to? :add_runtime_dependency then
-    s.add_runtime_dependency(%q<net-ssh>.freeze, [">= 2.6.5", "< 7.0.0"])
+    s.add_runtime_dependency(%q<net-ssh>.freeze, [">= 3.2.0", "< 7.0.0"])
     s.add_development_dependency(%q<test-unit>.freeze, [">= 0"])
     s.add_development_dependency(%q<mocha>.freeze, [">= 0"])
   else
-    s.add_dependency(%q<net-ssh>.freeze, [">= 2.6.5", "< 7.0.0"])
+    s.add_dependency(%q<net-ssh>.freeze, [">= 3.2.0", "< 7.0.0"])
     s.add_dependency(%q<test-unit>.freeze, [">= 0"])
     s.add_dependency(%q<mocha>.freeze, [">= 0"])
   end
```

And subsequently running:
```
bundle exec vagrant plugin install vagrant-share
```
it succeeds:
```
You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

Installing the 'vagrant-share' plugin. This can take a few minutes...
Fetching netrc-0.11.0.gem
Fetching unf_ext-0.0.8.2.gem
Building native extensions. This could take a while...
Fetching unf-0.1.4.gem
Fetching domain_name-0.5.20190701.gem
Fetching http-cookie-1.0.5.gem
Fetching http-accept-1.7.0.gem
Fetching rest-client-2.1.0.gem
Fetching vagrant-share-2.0.0.gem
Installed the plugin 'vagrant-share (2.0.0)'!
```

Which should allow reproducing how to workaround locally.


What exactly is going on in the resolver is not clear. Given that simply modifying the gem constraint is enough to allow a resolution subsequently, it does not appear to be how vagrant is calling bundler/rubygems that is the source, though maybe there is something incorrect there.

Trying to dump the contents of the possibility sets that the set arithmetic is being performed on and view the output resulted in my machine grinding almost to a halt, so I haven't been able to dig much further as I don't really have enough context as to what is happening at this level with bundler/rubygems.

**Comment by deivid-rodriguez** [comment] 2022-08-19 10:59
I don't have a linux machine available right now (it's being repaired), I'll look at this when I do. But for now I think I do understand the issue and I'm confident to label it as an issue in RubyGems. You only used Bundler to provide the environment necessary to reproduce the bug but vagrant's plugin manager uses RubyGems stuff under the hood (at least the error seems to be coming from RubyGems not Bundler).

**Comment by electrofelix** [comment] 2022-08-23 18:57
The issue with vagrant on arch has been resolved by having the distro package built without using a pre-release gem. A workaround has also been described, however it doesn't fully explain why modifying the allowed range could change the result of the resolutions.

I think either it should have failed for either the original range and the modified range, or succeeded for both.
Possibly less important now though.

**Comment by deivid-rodriguez** [comment] 2022-08-24 05:37
Thanks, so the repro instructions will no longer make the issue happen by default, correct? Is it still possible to reproduce is some other way?

**Comment by electrofelix** [comment] 2022-08-24 12:05
The repro instructions still work, the fix just impacted how the arch distribution package of vagrant was built, so it no longer includes the 6.2.0.rc2 release candidate of net-ssh and instead will use 6.1.0. This prevents the issue from occurring when using the distribution package. Since the Gemfile uses net-ssh 6.2.0.rc2 and vendoring it is still able to reproduce the behaviour.

Latest version of vagrant distributed by arch now is 2.3.0-5, and when I look at the gems bundled with it:
```
ls -w100 /opt/vagrant/embedded/gems/2.3.0/gems/
bcrypt_pbkdf-1.1.0                    gyoku-1.4.0                  nori-2.6.0
builder-3.2.4                         hashicorp-checkpoint-0.1.5   rb-fsevent-0.11.1
cgi-0.3.2                             httpclient-2.8.3             rb-inotify-0.10.1
childprocess-4.1.0                    i18n-1.12.0                  rb-kqueue-0.2.8
concurrent-ruby-1.1.10                lazy_priority_queue-0.1.1    rexml-3.2.5
delegate-0.2.0                        listen-3.7.1                 rgl-0.5.8
ed25519-1.3.0                         little-plugger-1.1.4         rubyntlm-0.6.3
erubi-1.11.0                          log4r-1.1.10                 rubyzip-2.3.2
excon-0.92.4                          logging-2.3.1                stream-0.5.4
ffi-1.15.5                            mime-types-3.4.1             vagrant-2.3.0
generator-0.0.1                       mime-types-data-3.2022.0105  vagrant_cloud-3.0.5
google-protobuf-3.21.5-x86_64-linux   multi_json-1.15.0            wdm-0.1.1
googleapis-common-protos-types-1.4.0  net-scp-3.0.0                winrm-2.3.6
grpc-1.48.0-x86_64-linux              net-sftp-3.0.0               winrm-elevated-1.2.3
gssapi-1.3.1                          net-ssh-6.1.0                winrm-fs-1.3.
```

Using the Gemfile I posted:
```
 bundle install
Using bcrypt_pbkdf 1.1.0
Using builder 3.2.4
Using bundler 2.3.20
Using childprocess 4.1.0
Using concurrent-ruby 1.1.10
Using ed25519 1.3.0
Using erubi 1.11.0
Using excon 0.92.4
Using ffi 1.15.5
Using generator 0.0.1
Using google-protobuf 3.21.5 (x86_64-linux)
Using googleapis-common-protos-types 1.4.0
Using grpc 1.48.0 (x86_64-linux)
Using gssapi 1.3.1
Using rexml 3.2.5
Using gyoku 1.4.0
Using hashicorp-checkpoint 0.1.5
Using httpclient 2.8.3
Using i18n 1.12.0
Using lazy_priority_queue 0.1.1
Using rb-fsevent 0.11.1
Using rb-inotify 0.10.1
Using listen 3.7.1
Using little-plugger 1.1.4
Using log4r 1.1.10
Using multi_json 1.15.0
Using logging 2.3.1
Using mime-types-data 3.2022.0105
Using mime-types 3.4.1
Using net-ssh 6.2.0.rc2
Using net-scp 3.0.0
Using net-sftp 3.0.0
Using nori 2.6.0
Using rb-kqueue 0.2.8
Using stream 0.5.4
Using rgl 0.5.8
Using rubyntlm 0.6.3
Using rubyzip 2.3.2
Using vagrant_cloud 3.0.5
Using wdm 0.1.1
Using winrm 2.3.6
Using winrm-fs 1.3.5
Using winrm-elevated 1.2.3
Using vagrant 2.3.1.dev from https://github.com/hashicorp/vagrant.git
Bundle complete! 3 Gemfile dependencies, 44 gems now installed.
Bundled gems are installed into `./vendor/bundle`
```

And then running a plugin install command:
```
bundle exec vagrant plugin install vagrant-share
You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

Installing the 'vagrant-share' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies net-ssh (>= 2.6.5, < 7.0.0) and net-ssh (= 6.2.0.rc2)
  Activated net-ssh-6.2.0.rc2
  which does not match conflicting dependency (>= 2.6.5, < 7.0.0)

  Conflicting dependency chains:
    net-ssh (= 6.2.0.rc2), 6.2.0.rc2 activated

  versus:
    net-scp (= 3.0.0), 3.0.0 activated, depends on
    net-ssh (>= 2.6.5, < 7.0.0)

  Gems matching net-ssh (>= 2.6.5, < 7.0.0):
    net-ssh-6.2.0.rc2
```

Testing it on my host system running Ubuntu 22.04 I can also reproduce with the Gemfile. Just used archlinux as a starting point since that's where it first appeared and it also had a recent versions of bundler and rubygems. Expect it should be reproducible with any host distro.

**Comment by huix11** [comment] 2023-09-22 03:07
q

**Comment by deivid-rodriguez** [comment] 2024-07-23 17:04
I suspect this may have been fixed by https://github.com/rubygems/rubygems/pull/7537. Please do reopen if you can still reproduce with the latest RubyGems. Thanks!

**Closed by deivid-rodriguez** 2024-07-23 17:04 UTC
Labels: RubyGems
