### ISSUE TITLE
Bundler check incorrectly fires while running on older versions of Ruby/Rubygems

### ISSUE THREAD

**Issue by schneems** [rubygems/rubygems#2666] opened 2019-02-28 20:11 UTC
Update: It turns out this problem is not limited to "pre" versions of Bundler, but rather all versions of Bundler. The problem goes something like this:

On june 19th of 2017 Sam Giddens added code into RubyGems that tightly couples it with Bundler and the Gemfile.lock https://github.com/rubygems/rubygems/commit/69847079c940a5c6935a7f83a43131097e08558b, the original behavior was original described by Andre in https://github.com/rubygems/rubygems/issues/1974. The behavior that was originally written makes RubyGems aware of the Gemfile.lock. When bundler is loaded, it tries to find the EXACT version that is specified on the system, but only when a major version of Bundler 2 is detected https://github.com/rubygems/rubygems/blob/69847079c940a5c6935a7f83a43131097e08558b/lib/rubygems/bundler_version_finder.rb#L59.

When the exact version of bundler cannot be found, it raises an error:

```
Could not find 'bundler' (2.0.0.pre.1) required by your Gemfile.lock
```

This is a problem for environments such as Travis and Heroku where a version of Bundler is provided. If the version in the Gemfile.lock is slightly different, for example 2.0.0 when the provided version is 2.0.1 then an error will be raised even though there is no technical need to do so.

The behavior was eventually changed in https://github.com/rubygems/rubygems/pull/2515 so that RubyGems would not perform a strict version check, but instead perform a major version check. I.e. if the Gemfile.lock says bundler "2.0.1" then any version of bundler 2.x is sufficient. This patch exists in RubyGems 3+. Ruby 2.6.1 ships with RubyGems 3.0.1 so it does not incorrectly fire this error, however this behavior still exists in older versions of RubyGems.

Unfortunately this code was shipped and still exists in older versions of RubyGems. According to GitHub this file exists on versions:

- v3.0.2 
- v3.0.1 
- v3.0.0 
- v3.0.0.beta3 
- v3.0.0.beta2 
- v3.0.0.beta1 
- v2.7.8 
- v2.7.7 
- v2.7.6 
- v2.7.5 
- v2.7.4 
- v2.7.3 
- v2.7.2 
- v2.7.1 
- v2.7.0 

This was not detected previously, because the check lies dormant on the system and only fires in the event that Bundler 2 is being used, and since it was not previously released, this issue went un-noticed.

For a reproduction see "original issue" below.

## Immediate Mitigation

If you're hitting this issue, upgrade to Ruby 2.6.1 and you're good to go. If you must use an older Ruby version then downgrade from Bundler 2 and update the `BUNDLED WITH` version to be a 1.x version.

## Original Issue

When using a project that has a BUNDLED WITH of 2.0.0.pre.1, I would expect that I can use this Gemfile.lock with bundler -v 2.0.1, however it raises an error using rubygems 2.7.8:

## Reproduction

```
 docker run -it --rm ruby:2.3.7 bash
```

```
unset BUNDLER_VERSION # otherwise it tries to use 1.16.6, ugh
gem install bundler -v 2.0.0.pre.1 --no-document
gem install rails -v 5.2.2 --no-document
rails new foo
cd foo
bundle _2.0.0.pre.1_ update --bundler # put pre-release version in the Gemfile.lock

gem install bundler -v 2.0.1
gem uninstall bundler -v 2.0.0.pre.1 -x

bundle _2.0.1_ exec ruby -v
```

Produces error:

```
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems.rb:289:in `find_spec_for_exe': Could not find 'bundler' (2.0.0.pre.1) required by your /foo/Gemfile.lock. (Gem::GemNotFoundException)
To update to the lastest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.0.0.pre.1`
  from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems.rb:308:in `activate_bin_path'
  from /usr/local/bundle/bin/bundle:23:in `<main>'
```

This bug exists in RubyGems 2.7.7 (which ships with the container) as well as 2.7.8. You can verify by updating the version and re-running the command above:

```
gem update --system 2.7.8
bundle _2.0.1_ exec ruby -v
```

If you update to the latest version of rubygems 3.x then the error goes away and the command executes correctly.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by colby-swandale** [comment] 2019-02-28 23:45
This is actually the reason why I had bundler v2.0.0 set the required version of RubyGems to `>= 3.0.0`.

This is not a bug, this behaviour is intentional in RG v2. When your Gemfile.lock is on a version that's `>= 2.0.0`, RubyGems will look only for the exact version of Bundler that's in the Gemfile.lock. So, if you run `gem install bundler -v '2.0.0.pre.1`, the error will disappear.

In RubyGems 3, I changed this behaviour so that any version of Bundler that matched the major version could be used (#2515).

**Comment by schneems** [comment] 2019-03-01 02:09
Ahh, that makes sense. I guess this issue is worse than it seems. It would error for any 2.x unless you happen to be using the EXACT same version we offer.

Can we backport that rubygems 3.x behavior to currently supported RubyGems versions?

**Comment by colby-swandale** [comment] 2019-03-01 02:53
@hsbt did indicate that this was going to be backported https://github.com/rubygems/rubygems/pull/2515#issuecomment-445445108.

Is that still the plan @hsbt?

**Comment by hsbt** [comment] 2019-03-01 10:15
I have a plan to backport #2515 to RG 3.0.x and RG 2.7.x, But I have no plan to release RG 2.5 and 2.6. I will consider to create a patch for heroku platform about them.

**Comment by schneems** [comment] 2019-03-01 18:42
Linking to an internal ticket number: 686675.

I've been thinking about this and I'm not sure how to support this behavior on Heroku moving forwards.

While we technically only support 3 versions of Ruby, older customers are expecting that their apps don't suddenly break if they upgrade their bundler version on Heroku-16 we offer 58 versions of Ruby https://gist.github.com/schneems/9aa4d002968d7da0617a29bf917f1cbb and each version uses the copy of RubyGems provided with it. Cedar-14 apps are currently available for at least another month and there's over 100 versions for that stack.

To be able to support existing applications that suddenly (or accidentally) update to Bundler 2.x I can think of a few options:

### Modify their `Gemfile.lock` to remove the `BUNDLED WITH` information from the buildpack.

- Pros: 
  - Would remove all RubyGems and Bundler version errors
- Cons: 
  - Mutating a customer's Gemfile.lock is pretty unexpected. 
  - Might have unexpected side-effects. 
  - Customers trying to reproduce with the exact same versions locally would get an error, but not on Heroku.


### Run all commands with the env var `BUNDLER_VERSION=2.0.1` when running with Bundler 2.x. While that looks like it works for rubygems 2.7 I don't know about older versions.

- Pros: 
  - Seems "cleaner" than mutating the Gemfile.lock
- Cons: 
  - Would also be surprising. 
  - Might also have unexpected side-effects. 
  - Could be accidentally over-written by a customer setting their own env vars
  - Customers trying to reproduce with the exact same versions locally would get an error, but not on Heroku.


### Update RubyGems to 3.x on deploy

- Pros:
  - Would fix the issue without modifying Gemfile.lock or using a seemingly "magic" env var
- Cons:
  - Could break existing behavior. 
  - It's really bad to give a customer a different major version of a library (due to breaking existing behavior).
  - Not sure this is easilly done since every version of Ruby comes with a RubyGems version and some of these errors that are being raised are while we are doing the download and setup of Ruby versions.
  - I don't think I would be willing to do this.

### Patch every version of Ruby

- Pros:
  - Would fix the issue without modifying Gemfile.lock or using a seemingly "magic" env var. 
  - Would not bump a major version of a library. 
  - It's very unlikely that this would break things - though it could.
- Cons:
  - Customers are now running custom patched Ruby code which we've been against in the past.
  - Could still break a thing if it introduces a bug, then we're on the hook for maintaining and re-patching the code
  - Would take an extraordinary amount of effort to patch and re-release hundreds of Ruby versions across 3 stacks
  - Customers trying to reproduce with the exact same versions locally would get an error, but not on Heroku

## Do nothing

- Pros:
  - It's easy 🤷‍♀️
- Cons: 
  - Customer's must navigate a minefield of Bundler/RubyGems/Ruby versions and get no help from us
  - Not really an option.

**Comment by schneems** [comment] 2019-03-04 16:28
I did some diving and it looks like maybe we don't have to patch anything older than RubyGems 2.7 if i'm understanding correctly.

The behavior was introduced in https://github.com/rubygems/rubygems/commit/69847079c940a5c6935a7f83a43131097e08558b and it looks like this file is in the following releases:

![](https://www.dropbox.com/s/anq5bmkbnnbeygh/Screenshot%202019-03-04%2010.26.09.png?raw=1)

- v3.0.2 
- v3.0.1 
- v3.0.0 
- v3.0.0.beta3 
- v3.0.0.beta2 
- v3.0.0.beta1 
- v2.7.8 
- v2.7.7 
- v2.7.6 
- v2.7.5 
- v2.7.4 
- v2.7.3 
- v2.7.2 
- v2.7.1 
- v2.7.0 

Is that a correct interpretation? If that's the case, then patching 2.7 should be sufficient. It also makes backporting a patch mean that we would only have to patch Ruby 2.5.x which is far less invasive than having to patch ALL rubies on Heroku.

**Comment by colby-swandale** [comment] 2019-03-04 22:16
Yea, the auto switch feature was first introduced in 2.7.0. And the new behaviour was released in v3.0.0, so the version list would be (i don't think you need to worry about the pre-releases):

v2.7.8
v2.7.7
v2.7.6
v2.7.5
v2.7.4
v2.7.3
v2.7.2
v2.7.1
v2.7.0

**Comment by schneems** [comment] 2019-03-04 22:40
Great, once there's a backport to 2.7.x then I can apply that patch to 2.5.0, 2.5.1, 2.5.2, and 2.5.3. 

@hsbt can you let me know when you make a patch for 2.7?

**Comment by hsbt** [comment] 2019-03-08 04:54
I did create the patch for Ruby 2.5: https://bugs.ruby-lang.org/issues/15643

**Comment by hsbt** [comment] 2019-04-30 23:44
I will release the next version with the above fix.

**Closed** 2019-04-30 23:43 UTC
Labels: status: triage
