### ISSUE TITLE
Cleaning build artifact broke some of gems

### ISSUE THREAD

**Issue by hsbt** [rubygems/rubygems#6205] opened 2022-12-27 03:04 UTC
### Describe the problem as clearly as you can

Related with https://github.com/rubygems/rubygems/issues/3958 and https://github.com/rubygems/rubygems/pull/6133

I found the some of issues related object cleanup.

* https://github.com/technion/ruby-argon2/issues/56
* https://mastodon.zunda.ninja/@zundan/109582899577282063

`ffi` may uses build artifact under the `ext` directory, not installation directory. Because they couldn't require gem library via `ffi`.

I didn't investigate `ffi` side yet.

### Post steps to reproduce the problem

```
bundle init; bundle add blurhash; bundle exec ruby -rblurhash -e 'puts Blurhash::VERSION'
```

`ffi` try load under the `ext` directory like

```
/Users/hsbt/.local/share/gem/gems/blurhash-0.1.6/lib/../ext/blurhash/encode.bundle
```

(`$HOME/.local/share/gem` is my GEM_HOME environment)

* Build files by RubyGems 3.4.1

```
$ fd .
CHANGELOG.md
CODE_OF_CONDUCT.md
Gemfile
Gemfile.lock
LICENSE.txt
README.md
Rakefile
bin/
bin/console
bin/setup
blurhash.gemspec
ext/
ext/blurhash/
ext/blurhash/Makefile
ext/blurhash/encode.c
ext/blurhash/encode.h
ext/blurhash/extconf.rb
lib/
lib/blurhash/
lib/blurhash/version.rb
lib/blurhash.rb
lib/encode.bundle
```

* Build files with RubyGems 3.3.26

```
$ fd .
CHANGELOG.md
CODE_OF_CONDUCT.md
Gemfile
Gemfile.lock
LICENSE.txt
README.md
Rakefile
bin/
bin/console
bin/setup
blurhash.gemspec
ext/
ext/blurhash/
ext/blurhash/Makefile
ext/blurhash/encode.bundle
ext/blurhash/encode.c
ext/blurhash/encode.h
ext/blurhash/encode.o
ext/blurhash/extconf.rb
lib/
lib/blurhash/
lib/blurhash/version.rb
lib/blurhash.rb
lib/encode.bundle
```

### What's the next step?

I'm not sure we should revert https://github.com/rubygems/rubygems/pull/6133 yet. Because why `ffi` uses extensions under the `ext` directory. But this change may broke <del>many of gems depends on `ffi`</del> some of gems.

**Comment by zunda** [comment] 2022-12-27 03:15
If this change is intentional, we'd want to change lines like https://github.com/Gargron/blurhash/blob/9cb4d6157b137aa855f1c1f72ae45fc009807c64/lib/blurhash.rb#L26

**Comment by hsbt** [comment] 2022-12-27 03:28
I found another issue https://github.com/ohler55/ox/issues/300 without `ffi` usage.

`ox` relied on `ext/ox/ox.{so,bundle}` from their ruby code.

**Comment by simi** [comment] 2022-12-27 03:33
I was aware of this potential problem, but I wasn't able to find out any regression in few popular gems I have tested. The question now is what's wrong. Should you rely on files in original build destination removed by `make clean` folder after successful `make install`?  Per my understanding doing this is a mistake in [autotools](https://en.wikipedia.org/wiki/GNU_Autotools) world.

**Comment by hsbt** [comment] 2022-12-27 03:40
Basically, I agreed to clean build directory with you.

* `blurhash`: They should use under the `lib` directory, not `ext` directory.
* `ruby-argon2`: Tha [find logic of `ffi-compiler`](https://github.com/ffi/ffi-compiler/blob/master/lib/ffi-compiler/loader.rb#L8) is may wrong. 
* `ox`: They use `require_relative "ox.so"`, not `ox/ox`.

I'm not sure how the impact about this. I can investigate and fix them for the current issues.

**Comment by hsbt** [comment] 2022-12-27 05:25
I submit a fix for `ox` https://github.com/ohler55/ox/pull/301

**Comment by simi** [comment] 2022-12-27 05:30
I'm looking into extensions right now to revisit how they works to make it finally clear. I'm not sure that fix is handling all the use-cases yet. Currently extensions are copied into two places per following code. https://github.com/rubygems/rubygems/blob/bd8d0835727e3eb2868675419bfeac2ecac40a0f/lib/rubygems/ext/ext_conf_builder.rb#L47-L57

**Comment by j-manu** [comment] 2022-12-27 05:36
This also broke this gem - https://github.com/akihikodaki/cld3-ruby and its predecessor

Ideally this change should be opt in. There are unmaintained gems that used to work but are now broken.

**Comment by simi** [comment] 2022-12-27 05:42
> The change also broke this gem - https://github.com/akihikodaki/cld3-ruby and its predecessor
> 
> Ideally this change should be opt in. There are unmaintained gems that used to work but are now broken.

That's seems like similar problem with ffi fixed path.

https://github.com/akihikodaki/cld3-ruby/blob/c183b6d9c3dbea72467a2aa4af1875fb0784fdce/lib/cld3/unstable.rb#L22

**Comment by hsbt** [comment] 2022-12-27 06:02
Submit the fix for `cld3-ruby` https://github.com/akihikodaki/cld3-ruby/pull/38

**Comment by deivid-rodriguez** [comment] 2022-12-27 06:36
Well, turns out @eloyesp and @simi were right and I completely missed the case of using the artifacts directly when I deemed #6133 as "mostly compatible"  at https://github.com/rubygems/rubygems/pull/6133#issuecomment-1354905530 🤦‍♂️ . And it does not seem that rare in retrospective since the compiled artifacts used to live relatively to the other gem files, not in some more strange location.

As per what to do, I'm not sure. For now I can move #6133 to the breaking changes section and add a note about what to do?

Also, regarding what to do, I want to note that installing to lib was supposed to be something only temporary and it was eventually planned to stop doing that. At least there's a TODO about making that change for RubyGems 4. I think the rationale being that extensions are arch-dependent, so they should be installed to an arch-dependent folder (and `lib` is not). I think the "arch-dependent" alternative would be `Gem.loaded_specs[<name>].extension_dir`.

**Comment by deivid-rodriguez** [comment] 2022-12-27 07:09
There's also this ramification that I didn't think about:

> ox relied on ext/ox/ox.{so,bundle} from their ruby code.

Artifacts generated at the `ext` folder (and now automatically cleaned up after installation) are the only ones with a valid `ox/ox` require path. Now that possible require path is gone. I wonder if this is also related to #6204 🤔.

Thinking about an ideal deprecation path here, it seems pretty messy to me 😭. We would need to warn when this kind of route is `require`'d. For that an idea would be to instead install a Ruby file that first warns and then delegates to the properly installed compiled artifact. But we'd want to display the warning only to gem authors, not to gem users, since gem users can't really do much about these warnings. I guess we'd need to detect whether the CWD is the root of the gem for that or something.

**Comment by deivid-rodriguez** [comment] 2022-12-27 07:24
Alternatively, since damage is done now and a fully clean deprecation path does not exist anymore, we could add a way for users to opt-out of the new behavior as suggested above, until gems are fixed and users can move on to the new version.

Ideally we could make this setting configurable per gem, so that users can still benefit from the savings of cleaning up other artifacts, but that's probably overkill.

**Comment by j-manu** [comment] 2022-12-27 07:51
I don't see why it should be opt out instead of opt in. Not cleaning up artefacts doesn't change any behaviour. It just uses extra diskspace, which is same as before.

Disk space is cheap. I spent some 5 hours yesterday trying to figure this out. Look at the number of people who commented on https://github.com/technion/ruby-argon2/issues/56 I'm pretty sure they would have happily spent that extra diskspace

> damage is done now 

This was caught in our CI since we use a Dockerfile which uses the latest rubygems. Imagine someone deploying a new machine image which does that. Apps which used to work will break in production. This latest update is a **ticking time bomb**. 

Please revert this change and push an update. It can be brought back as an opt in.

**Comment by simi** [comment] 2022-12-27 07:57
@j-manu I have explained the root of the problem at https://github.com/rubygems/rubygems/issues/6205#issuecomment-1365584250. I don't see any place (I was looking into already) where anyone recommends (even outside of RubyGems) to use those intermediate folder artifacts. I'm still wondering why that is used in those listed gems.

Originally this was reported by unhappy users with 1GB+ gem directories with intermediate build artifacts of grpc for example (https://github.com/grpc/grpc/issues/28627) or similar trouble mentioned by sassc gem if I remember well causing troubles with other usecases (tiny containers, ...).

**Comment by j-manu** [comment] 2022-12-27 08:21
@simi Ok. I didn't know there were gems with such high disk usage. It makes sense for those gems.

But my point is that any system where an affected gem is used and rubygems are updated to latest (like in a setup script) will break.

Doesn't it make more sense to revert the change and bring it back as opt in?

**Comment by hsbt** [comment] 2022-12-27 08:23
> I spent some 5 hours yesterday trying to figure this out.

I also spent over the 5 hours to fix them. Don't brag about the time spent. We are considering what's the best way and for the Ruby's ecosystem.

**Comment by deivid-rodriguez** [comment] 2022-12-27 08:32
We're considering what's best, the fact that a change breaks something for someone does not necessarily mean that it needs a revert. Even if we all believe this change is a right move that benefits the majority of the community, we need to evaluate how common it is to depend on the old behavior, and how common this is going to be in the wild and make a decision.

Of course, this only affects people not locking their dependencies, so a quick fix for people out there is to lock their dependency on RubyGems, which is a good practice for all your external dependencies anyways.

**Comment by simi** [comment] 2022-12-27 08:33
> But my point is that any system where an affected gem is used and rubygems are updated to latest (like in a setup script) will break.

It is hard to say, since personally I would not recommend to rely on `gem update --system` anywhere in automation for various (security, reliability, maintainability) reasons. For now feel free to replace that with `gem update --system 3.3.26` or any other version working well for you.

> Doesn't it make more sense to revert the change and bring it back as opt in?

As mentioned before, this is not easy to make opt-in/opt-out and after release it is even much harder. Also as mentioned before, I still do see using intermediate directory artifacts as a undocumented/not recommended way of handling gem extensions. If you have any insight, feel free to share to make it easier to decide.

**Comment by j-manu** [comment] 2022-12-27 08:50
> > I spent some 5 hours yesterday trying to figure this out.
> 
> I also spent over the 5 hours to fix them. Don't brag about the time spent. We are considering what's the best way and for the Ruby's ecosystem.

I'm not bragging about time spent. I'm comparing the time spent by various people including you to the advantage of this change - diskspace saved.

Please understand that I'm not trying to blame you or any of the maintainers. The change was made in good faith and I appreciate the effort all maintainers put in

We all have the same goals. As you said the health of Ruby's ecosystem. 

This is a breaking change. The gems affected may not have been following best practices but they worked before this change and now don't.

The best practices I know for deployment involves locking the Gemfile and locking the Ruby. I have never locked the rubygems. 

I have already solved the problem for myself. I am only asking for a revert and opt in because I think people might find out about this by their apps breaking.

**Comment by deivid-rodriguez** [comment] 2022-12-27 09:04
> This is a breaking change. The gems affected may not have been following best practices but they worked before this change and now don't.

I understand the pragmatic side of this, and we generally try to follow it. Just want to note that according to that definition, _any_ change is a breaking change. Because anybody could be depending on anything. A breaking change is a change that breaks public, documented usages of software, like APIs or any other contracts.

**Comment by eloyesp** [comment] 2022-12-27 18:23
I think that we are discussing many intermixed issues, and it is hard to solve them all with a single patch. So I would like to split the problem in parts:

- There is no documented folder structure for installed ruby gems so every user use a different strategy to access built extensions. To fix this we need to document a public API to access built extensions, like: `Gem.loaded_specs[<name>].extension_dir`, that works. By getting the API clear we make sure that most people interact with the gems with a simple entry point. We could also "promote" that API on the `ffi` docs and examples.

- We need a consistent "extensions" path, accessible by  that is correctly added to `LOAD_PATH`, as currently that folder is no consistent for git sourced gems installed with `bundler` (see [here](https://github.com/rubygems/rubygems/pull/4017#issuecomment-1352516109)).

- On the other hand, we need a patch for the current version to make it easy to workaround current issues with unmaintained gems. We can add the `--dirty` flag that disable the `clean` step altogether.

May be I'm missing some problem, but hope that the idea of _divide and conquer_ helps here.

**Comment by j-manu** [comment] 2022-12-28 05:46
> > This is a breaking change. The gems affected may not have been following best practices but they worked before this change and now don't.
> 
> I understand the pragmatic side of this, and we generally try to follow it. Just want to note that according to that definition, _any_ change is a breaking change. Because anybody could be depending on anything. A breaking change is a change that breaks public, documented usages of software, like APIs or any other contracts.

These gems were not depending upon a private API but a behaviour. Rubygems did not delete build artifacts before but now it does. I'm struggling to come up with an apt analogy but it is like automatically running `make clean` after `make install`.  

I found a couple of other gems which are probably affected by the same problem
* https://github.com/modelfoxdotdev/modelfox/issues/130
* https://github.com/metanorma/ruby-packer/issues/40

**Comment by hsbt** [comment] 2022-12-28 05:54
@j-manu Please report the same problems after confirming and investigating them.

`modelfox` case happened at Dec 21, 2022. That date is before the date of RubyGems release.

**Comment by deivid-rodriguez** [comment] 2022-12-28 06:06
> These gems were not depending upon a private API but a behaviour. Rubygems did not delete build artifacts before but now it does. I'm struggling to come up with an apt analogy but it is like automatically running make clean after make install.

This is a bit of a philosophical discussion, but again, every change changes some behavior from something to something else. So every change is a breaking change if you depend on the old behavior. To give a stupid example, even we released RubyGems 2.4.2 to be exactly the same as RubyGems 2.4.1, except for the version number, that would be a breaking change for a gem `foo` implemented as `raise if Gem.rubygems_version > Gem::Version.new("2.4.1")` 🤣.

The way I see it, not deleting build artifacts was an internal change unless we explicitly documented that the build artifacts are meant to be used (which we don't, as far as I know). Our understanding is installation artifacts installed by `make install` is what is meant to be used, not anything else.

That said, we understand some fairly popular gems were relying on this even if not officially supported in any way, and we're willing to minimize the disruption for people, so we'll make this work again somehow, at least temporarily, until we have a less disrupting way to do this.

**Comment by j-manu** [comment] 2022-12-28 06:29
Breaking Change - We will agree to disagree on this 🙂

Regarding using `gem update --system` without pinning a version, here are a few examples of it being used

* [Discourse](https://github.com/discourse/discourse_docker/blob/0595fc28210d1b563723b31baf55995afe856caf/image/base/slim.Dockerfile#L85)
* [Plots2](https://github.com/publiclab/plots2/blob/f845ccdd3bca3a78cc824c5954d0b41f23ffd4e1/Dockerfile#L43)
* [Rswag](https://github.com/rswag/rswag/blob/13e04716f91761a31dd424e21ee50c6cecc68d45/Dockerfile#L6)
* [Cloudserver](https://github.com/scality/cloudserver/blob/ba27ff79808f07c9324ccd344a6668f3bc8c212d/eve/workers/build/Dockerfile#L35)
* [Shuttle](https://github.com/square/shuttle/blob/bcb14e1925d75763b46911d3889a5ec984e2f79a/Dockerfile#L17)
* [Plaid Ruby](https://github.com/plaid/plaid-ruby/blob/121c593f15c38278ba2f039e219740c2b71e9385/Dockerfile#L10)

It's a very common pattern.

**Comment by Mange** [comment] 2022-12-30 10:49
So what should one do here, realistically? Just starting an unmodified Docker image of `ruby:2.3.0` will fail to install and load some gems because of this change.

Should I downgrade Rubygems inside the containers? Which version should I use? Will it work on Ruby 3.2.0 to backport to an earlier version than the shipped version?

Or is the solution to fork problematic gems and fix it there? What does the fix look like? Should the compiled files be moved into `lib` until we have a better option?

Sorry for being a bit dense here, but I find the discussion here to be pretty spread out over multiple things, and I just want to be pragmatic for the moment to get things working again.

> Is there anything to do, to be able to run the older Gem versions on a newer version of Ruby/Rubygems?
> If not, how to fix it so it work in both Ruby 3.2.0 and earlier at the same time, so that I can send in patches to affected gems?

Thank you.

**Comment by simi** [comment] 2022-12-30 10:59
@Mange ignoring your tone of voice, can you share details on what's your problem? Which gems? Have you tried to update to latest gem versions?

**Comment by akihikodaki** [comment] 2022-12-30 11:22
Hi, I'm a developer of an affected gem (cld3). First thanks for working on this issue and proposing a fix for cld3. For cld3, this issue is tracked at: https://github.com/akihikodaki/cld3-ruby/issues/37

I'm sorry but I decided not to apply the proposed fix, which uses the `lib` directory as an alternative. One of the problems of this approach is that the copy in the `lib` directory is expected to be removed in the future, which is already noted in this issue.

But I also found another issue: apparently some distributors patch RubyGems so that it won't create the copy at the `lib` directory. The below is the patches included in Fedora and Arch Linux:
- https://src.fedoraproject.org/rpms/rubygems/c/6aa4b2f223987a0ea3fe06da1633058174ccf871
- https://github.com/archlinux/svntogit-community/blob/packages/rubygems/trunk/rubygems_stop_so_duplication.patch

Eventually I decided not to support the latest RubyGems until a reliable way to get the binary is determined. It's been only a few days since Ruby 3.2.0 was released and I can wait a bit longer.

**Comment by deivid-rodriguez** [comment] 2022-12-30 11:30
@akihikodaki Did you try `Gem.loaded_specs[<name>].extension_dir`?

**Comment by simi** [comment] 2022-12-30 11:32
> @akihikodaki Did you try `Gem.loaded_specs[<name>].extension_dir`? That's where `make install` installs its artifacts.

I was just about to recommend the same.

https://github.com/rubygems/rubygems/blob/e1540e4bf64adcb9c98494e79f692762b3027f4d/lib/rubygems/basic_specification.rb#L104-L108

**Comment by akihikodaki** [comment] 2022-12-30 11:40
@deivid-rodriguez @simi I'm aware of the interface but I don't introduce it to my gem yet because it seems an API not documented and I haven't seen a consensus that it is the way forward though I do think it is a promising option. I'm not in hurry so I'll just wait until the interface to be used gets decided.

**Comment by simi** [comment] 2022-12-30 11:59
> @deivid-rodriguez @simi I'm aware of the interface but I don't introduce it to my gem yet because it seems an API not documented and I haven't seen a consensus that it is the way forward though I do think it is a promising option. I'm not in hurry so I'll just wait until the interface to be used gets decided.

That's the proper way of storing compiled extensions. Anyway feel free to wait if you're not in rush. I do plan to upgrade some guides to make it clear what's recommended way of handling extensions, since we have found out (thanks to this issue) there are various practices applied and not all of them are the good ones. 

Btw. IMHO in your case the best would be to not vendorize the gld3 at all, and ask client to install it into standard system paths on its own (using system package manager or by compiling and installing manually). But I understand that would add additional steps to the client side and it is not possible everytime.

**Comment by akihikodaki** [comment] 2022-12-30 12:20
@simi I think I will wait for the updated guide; it would help greatly.

cld3 is not designed in a way it can be installed as an independent library. Chromium and the Python binding just takes source files, compiles them, and link them directly. It also has a CMake build script, but it's just for compiling and doesn't have install rules (it doesn't say what header files to be copied and where the copies should be placed, for example) so it's not really useful. cld3-ruby also has its own code to convert cld3's C++ API to C so we need to build a shared object anyway.

**Comment by deivid-rodriguez** [comment] 2022-12-30 19:18
I proposed https://github.com/rubygems/rubygems/pull/6218 to get `Gem::Specification#extension_dir` documented.

**Comment by Mange** [comment] 2022-12-31 14:08
> @Mange ignoring your tone of voice, [...]

I apologize if it came off wrong. I tried to formulate myself as formal and technical as possible and just focusing on practicality, but I suppose that I didn't do it well. I'll reflect on how to make it even more cold in the future! :-)

> [...] can you share details on what's your problem? Which gems? Have you tried to update to latest gem versions?

Some old gems cannot be installed on a newer version of Ruby.
I want help them to fix it, but I'm not sure what API to use in any potential patches I want to send in.
I think I would want an "upgrade guide" or "here's how to install shared libraries in your gem" instruction. Is this documented anywhere?

---

I should add that I'm super happy for this change. I was one of the people that had real problems with `grpc` adding gigabytes of build artifacts when installing and actually migrated away from some Google services partly for that reason. I look forward to having this change implemented.

**Comment by hsbt** [comment] 2023-01-04 06:01
`appsignal-ruby` was fixed at https://github.com/appsignal/appsignal-ruby/pull/907.

**Comment by BrianHawley** [comment] 2023-01-04 18:02
@deivid-rodriguez this conversation has prompted a question...

It makes sense that `Gem.loaded_specs[<name>].extension_dir` should be the place to put these extension artifacts. However, is there a way for the gem to know what `<name>` is without hard-coding it or passing it in as a parameter? Like, to be detected from context?

I was looking at the ffi-compiler code to see if there was a way to get it to output to the appropriate directory, as a strategy to get support to be automatically added to old gems that use it, like scrypt. Right now, ffi-compiler outputs to the a subdirectory of the source directory, which might be ext. At least one of the gems mentioned above has run into this issue because of artifacts created by ffi-compiler. I'm trying to figure out how ffi-compiler could detect the right output directory if it's being used to compile an ext, and again when it's being used to load the stuff it compiled earlier. But to do that, it need to know that `<name>` to get the right directory.

Btw, afaik scrypt is not affected by this issue despite ffi-compiler putting the output files in ext, because it doesn't use "extconf.rb", so its generated code isn't deleted from ext. Still, it would be better to output to the right directories.

Another gotcha is that ffi-compiler isn't really maintained anymore, and the newer fork has a different name, which means that it's not usable by old gems which reference the original name. So I'm working on trying to fix the issue in a vendored ffi-compiler gem until it gets maintained again.

**Comment by deivid-rodriguez** [comment] 2023-01-04 18:25
@BrianHawley I'm not sure if that's possible, I think the full name of the gem would need to be passed as a parameter since there's one extensions dir per gem. For example, from my Ruby installation:

```
/Users/deivid/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/extensions/arm64-darwin-22/3.2.0/
├── byebug-11.1.3
│   ├── byebug
│   │   └── byebug.bundle
│   ├── gem.build_complete
│   └── gem_make.out
├── commonmarker-0.23.6
│   ├── commonmarker
│   │   └── commonmarker.bundle
│   ├── gem.build_complete
│   └── gem_make.out
...
```

At https://github.com/rubygems/rubygems/issues/6205#issuecomment-1365586074, @hsbt linked to `ffi-compiler` code and suggested we could do something about it there, but then the few fixes have gone directly to each affected gem so not sure if this is fixable inside `ffi-compiler`. Sorry I'm not able to help more, please share what you find.

**Comment by sly7-7** [comment] 2023-01-05 10:59
Hi, the fast_excel gem uses ffi to compile libxslxwriter and is also impacted by the change.

There is a PR https://github.com/Paxa/fast_excel/pull/90 which removes the `clean` task. As @Mange pointed there, I also think it's not the right move, but then I don't know how to fix, because from what I read in this issue, it seems to me the path for loading libxlsxwriter is the good one: https://github.com/Paxa/fast_excel/blob/master/lib/fast_excel/binding.rb#L16.

I'm clearly a noob about how a gem should build extensions, install, clean, etc.. so if anyone here could tell if the related pr in fast_excel is the solution, or if the shared lib should be built at an other place then correctly loaded by ffi.
Maybe @deivid-rodriguez, @simi, @BrianHawley ?

**Comment by jhawthorn** [comment] 2023-01-05 20:10
cross referencing some other extensions:
* [levenshtein-ffi](https://github.com/dbalatero/levenshtein-ffi) has two proposed fixes
  * https://github.com/dbalatero/levenshtein-ffi/pull/10
  * https://github.com/dbalatero/levenshtein-ffi/pull/11
* [murmurhash3](https://github.com/funny-falcon/murmurhash3-ruby)
  * discussion issue https://github.com/funny-falcon/murmurhash3-ruby/issues/10

**Comment by BrianHawley** [comment] 2023-01-06 03:07
Answering my own questions after reading the source...

> It makes sense that `Gem.loaded_specs[<name>].extension_dir` should be the place to put these extension artifacts. However, is there a way for the gem to know what `<name>` is without hard-coding it or passing it in as a parameter? Like, to be detected from context? Also, is that extension dir assigned to an environment variable or something during ext compilation so other Ruby code or non-Ruby code (like non-generated Makefile code) can refer to it in their install stages?

The different ext builders provide the `extension_dir` in different ways, depending on the builder type:

- The base `Gem::Ext::Builder` class has a `make` method that calls the platform's make command. It takes the `extension_dir` as its first `dest_dir` parameter, but then it completely ignores that value. However, it has an optional fourth `sitedir` parameter, which when provided, it defines the variables `sitearchdir` and `sitelibdir` with that value when it calls the external make command; no, I don't know why it defines the value in two variables (maybe it didn't used to be the same value). It also has an optional fifth parameter, which is the make targets, which it runs one after another in order, which by default is `["clean", "", "install"]`. The derived builders can call the `make` method.
- When the builders are passed the `lib_dir` value, it's not necessarily the "lib" dir. It's actually the first directory in the gem spec's `require_paths` collection. It just turns out that is often "lib".
- `Gem::Ext::ExtConfBuilder` (i.e. extconf.rb): It makes a temporary directory under the ext directory, runs the extconf.rb script which usually generates a Makefile, then passes that temporary directory as a relative path to the `make` method's `sitedir` parameter (see above). After it finishes running the make command with the default targets, it (temporarily) copies the contents of that temporary directory to `lib_dir`, then moves them to the `extension_dir`. Then, it calls `make` with the `clean` target, providing that `sitedir` value again. Then, lastly, it deletes that temporary directory with `rm -rf`.
- `Gem::Ext::ConfigureBuilder`: It passes the `extension_dir` as a `--prefix` parameter to `configure`. When it calls the generated Makefile with the default targets, it doesn't provide the `sitedir` parameter, so make sure `configure` uses that option properly. It doesn't call `make clean` afterwards.
- `Gem::Ext::RakeBuilder` (i.e. Rakefile, mkrf_conf.rb): This builder calls `rake` with the Rakefile (that was either defined or created), with the environment variables `RUBYARCHDIR` and `RUBYLIBDIR` assigned the `extension_dir` value. No, I don't know why it defines the value in two variables, again. It's notable that it passes the spec's `build_args` parameters to `rake`, so you can use those args to refer to a list of rake task names if you don't want to just do the default task.
- `Gem::Ext::CmakeBuilder`: The builder calls `cmake` with `CMAKE_INSTALL_PREFIX` defined with the value of the `extension_dir`. This presumably creates a Makefile, which is then called with the `make` method, with no `sitedir` parameter and the default targets. It doesn't call `make clean` afterwards.
- `Gem::Ext::CargoBuilder`: The builder calls `cargo` with the option `--target-dir` getting the `extension_dir` value. Later on, it makes a temporary directory similar to extconf, copies some files from ext, and does similar copying and moving behavior, and I don't know why this is needed given that `cargo` already knows the target dir.

There's no builder for a predefined Makefile, like in [ruby-argon2](https://github.com/technion/ruby-argon2) or [fast_excel](https://github.com/Paxa/fast_excel}, but there's a trick you can do:

1. Add a extconf.rb file with _no code_. Don't even call `require 'mkmf'`. The builder just assumes that extconf.rb is a Ruby script that creates a Makefile, but it doesn't check this, so as long as a Makefile exists afterwards (even if it was already there), it won't complain.
2. Make sure that your predefined Makefile has default, `clean`, and `install` targets.
3. Make sure that your predefined Makefile is aware of the `sitearchdir` or `sitelibdir` variables, and uses one of them to declare the path that you put the final compiled libraries in, during the `install` target. For instance, you could copy files to that target directory. Don't install anything in that directory that you don't want copied to the `lib_dir` and moved to the `extension_dir`. Make sure that you overwrite existing files on install.
4. In your Makefile's `clean` action, clean up the intermediate files. You probably don't need to clean up the installed files (I don't know standard practice here, but I thought that was a different target like "clobber"). Nonetheless, remember that after the final `clean` runs it will delete that `sitearchdir` or `sitelibdir` directory.

Now about ffi-compiler...

> I was looking at the ffi-compiler code to see if there was a way to get it to output to the appropriate directory, as a strategy to get support to be automatically added to gems that use it, like scrypt. Right now, ffi-compiler outputs to a subdirectory of the source directory, which might be ext. At least one of the gems mentioned above has run into this issue because of artifacts created by ffi-compiler. I'm trying to figure out how ffi-compiler could detect the right output directory if it's being used to compile an ext, and again when it's being used to load the stuff it compiled earlier. But to do that, it need to know that `<name>` to get the right directory.

The good news is that the ffi-compiler compile task adds the intermediate files it generates to rake's `CLEAN` collection, so you can use your gem's `build_args` to call `["default", "clean"]` or something. There is a downside, which I'll get into.

We can't get the `<name>` in non-Ruby code during ffi-compiler compilation, but we can get the `extension_dir`. However, the way that we get the `extension_dir` depends on the builder. For compilation there is an internal `out_dir` path calculated, but the target library file in that directory (`lib_name`) also gets added to `CLEAN`. So, it would probably be best to have an option to add install dir(s), and have an install task copy `lib_name` to the install dir(s). Then you can use whatever variable the `extension_dir` value is assigned to as that install dir, plus whatever other path you prefer. Maybe we can install to `ENV["RUBYARCHDIR"]` by default if that's set.

For the ffi-compiler loader `find` method, it takes a second parameter that's a start directory to look in, but then it goes up into higher level directories from there until it finds one named "lib" and searches for files in subdirectories, so that won't work for us. So it's best to do an option where you pass in a gem name that `Gem.loaded_specs[<name>]` can use. If that gem name is specified, we should just look into its `extension_dir` and not in the paths it does now. The only tricky part is managing parameters because the gem supports Ruby 1.9, so we can't just use a keyword parameter; old-school parameter handling with options hash tricks. This should work with scrypt, at least.

> Another gotcha is that ffi-compiler isn't really maintained anymore, and the newer fork has a different name, which means that it's not usable by old gems which reference the original name. So I'm working on trying to fix the issue in a vendored ffi-compiler gem until it gets maintained again.

Guess I just gotta make PRs to all the forks, plus a vendored version.

**Comment by BrianHawley** [comment] 2023-01-06 03:15
Given https://github.com/rubygems/rubygems/issues/6205#issuecomment-1373085201 I think I can help you, @sly7-7.

> Hi, the fast_excel gem uses ffi to compile libxslxwriter and is also impacted by the change.
> 
> There is a PR [Paxa/fast_excel#90](https://github.com/Paxa/fast_excel/pull/90) which removes the `clean` task. As @Mange pointed there, I also think it's not the right move, but then I don't know how to fix, because from what I read in this issue, it seems to me the path for loading libxlsxwriter is the good one: https://github.com/Paxa/fast_excel/blob/master/lib/fast_excel/binding.rb#L16.
> 
> I'm clearly a noob about how a gem should build extensions, install, clean, etc.. so if anyone here could tell if the related pr in fast_excel is the solution, or if the shared lib should be built at an other place, that would be nice.

You're already doing the no-code extconf.rb trick. I think that the `sitearchdir` var can be used to make the Makefile `install` target actually do something, then you can use `Gem.loaded_specs["fast_excel"].extension_dir` to get the directory for the file you pass to `ffi_lib`.

There's nothing in that PR that makes sense, except the title. I'll make a new one if you don't get to it first.

**Comment by sly7-7** [comment] 2023-01-06 14:58
@BrianHawley Thank you for the help, I think I've finally managed to find an acceptable fix. If you have the time, could you please review https://github.com/Paxa/fast_excel/pull/91/files and see if that makes sense ?

**Comment by BrianHawley** [comment] 2023-01-06 16:15
> Thank you for the help, I think I've finally managed to find an acceptable fix. If you have the time, could you please review https://github.com/Paxa/fast_excel/pull/91/files and see if that makes sense ?

@sly7-7 looks mostly good. I left a comment on the PR.

**Comment by akihikodaki** [comment] 2023-01-07 05:45
With a few days passed I decided to revisit this issue for my gem but the situation does not seem good. People are inventing different ways to fix this one problem, which may be creating potential compatibility hazards in the future. The below is candidates of fixes I have seen so far:
- Iterate `$LOAD_PATH`: https://github.com/dbalatero/levenshtein-ffi/pull/10
- Search `lib` and fall back to `ext`: https://github.com/dbalatero/levenshtein-ffi/pull/11
- Read `extension_dir` and fall back to `lib`: https://github.com/Paxa/fast_excel/pull/91

**Comment by sly7-7** [comment] 2023-01-09 09:43
@akihikodaki I've done it that way because reading this issue, it seemed to me this is the direction rubygems is taking (mostly seing https://github.com/rubygems/rubygems/issues/6205#issuecomment-1368060144)

**Comment by akihikodaki** [comment] 2023-01-09 10:14
I also think `extension_dir` is the most promising one, but it is not clarified yet if we can say it is the better one than other options.

Also, it is unclear what kind of fall backs we should have. Falling back to `lib` will allow running the gem during development without installing, but there are some caveats:
- You need to copy the binary to `lib` during development.
- It does not work in the case where binary is copied to global `sitearchdir`.
- If you write the code to read `extension_dir` in a wrong way, the code may still work because of the fall back and the bug may not be noticed before someone tries to install the released gem to Fedora, which does not copy binaries to `lib`.

So we may need to consolidate the method to fall back when RubyGems is not in use, or just decide to iterate `$LOAD_PATH`; it is more complex but solves all of these problems.

**Comment by hsbt** [comment] 2023-01-10 08:22
`extension_dir` is the best place for `ffi_lib` feature. We will document it at https://github.com/rubygems/rubygems/pull/6218.

I did investigate all affected gems in rubygems.org and fixed them that released in 2022. see https://gist.github.com/hsbt/e54b477c9c15a84175a6fed2d48cc969

I'll close this issue because there is no action about this in RubyGems 3.4.x.

**Comment by simi** [comment] 2023-01-10 08:28
My plan is to add recommendations to RubyGems guides as well. Feel free to close or leave open until that is done as well.

**Closed** 2023-01-10 10:06 UTC
Labels: RubyGems

**Comment by fidalgo** [comment] 2023-01-29 20:12
As a temporary **local fix**, I went to the gem dir and compile myself, using `make`.
```
/home/fidalgo/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/ffi-1.15.5/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library '/home/fidalgo/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/cld3-3.5.0/lib/cld3/../../ext/cld3/libcld3.so': /home/fidalgo/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/cld3-3.5.0/lib/cld3/../../ext/cld3/libcld3.so: cannot open shared object file: No such file or directory (LoadError)
```

So I went to `/home/fidalgo/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/cld3-3.5.0/lib/cld3/../../ext/cld3/` and just run `make` and voila, app loads again.

NOTE: This is a local workaround only.

**Comment by nevinera** [comment] 2023-02-07 20:51
You can also just copy the already-compiled file from the gem's lib/ directory. We ran into this on the `threatstack-agent-ruby` gem, which we can't fork and fix -.-
