### ISSUE TITLE
Non-deterministic behaviour with git sources using globs

### ISSUE THREAD

**Issue by riffraff** [rubygems/rubygems#4943] opened 2021-09-29 17:49 UTC
### Describe the problem as clearly as you can

We've recently started experiencing a problematic behaviour: the git sources list in `Gemfile.lock` keeps changing when running `bundle` in different operating systems. 
This appears to be caused by the fact that we have now multiple gems which refer to the same repository and are loaded using the glob option, something like this 

```
git_source(:organization) do |repo_name|
  "git@github.organization/#{repo_name}.git"
end

gem 'foo', organization: 'private_repo', glob: "gems/foo/*.gemspec", ref: '123'
gem 'bar', organization: 'private_repo', glob: "gems/bar/*.gemspec", ref: '123' 
gem 'baz', organization: 'private_repo', glob: "gems/baz/*.gemspec", ref: '123' # depends on bar and foo
```

It appears bundler attempts to order sources in a deterministic way [sorting by their string representation](https://github.com/rubygems/rubygems/blob/d01d6ca84011b05251b31d496f75f6aff8f677c4/bundler/lib/bundler/source_list.rb#L109) but the string representation is the same for all three, i.e. "repo name @ git reference", so the order in which the sources were initialized gets through, and we get a non-deterministic order of the source stanzas in `Gemfile.lock`

By changing `lock_other_sources` to account for the glob
```
# Bundler::SourceList 
  def lock_other_sources
    (path_sources + git_sources + plugin_sources).sort_by do |source|
      glob = source.respond_to?(:glob) ? source.glob : ''
      [source.to_s, glob]
    end
  end
```

we are able to get a behaviour which is consistent across different operating systems, and results in a `Gemfile.lock` where the three sources are sorted by glob (bar -> baz -> foo).

I guess we could change `SourceList#to_s` but that seems like it's used in multiple ways, so maybe a better way to do this is to introduce a `SourceList#sort_key` method which would only be used for this goal. 
I can try to provide a patch if you're interested. 

### Post steps to reproduce the problem

It's pretty hard to offer a way to reproduce this as it happens with our internal repo, and you need both a linux and macOS machine, but I will try to setup some test case later if the problem is not clear.

Anyway, the various software versions were ruby 2.6.5p114, rubygems 3.2.28, bundler 2.2.28.

### Which command did you run?

`bundle`

### What were you expecting to happen?

Get the same `Gemfile.lock` in Linux and macOS 

### What actually happened?

The Gemfile.lock is different on the two machines

### If not included with the output of your command, run `bundle env` and paste the output below

```
Bundler             2.2.28
  Platforms         ruby, x86_64-darwin-20
Ruby                2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin20]
  Full Path         /Users/riffraff/.rvm/rubies/ruby-2.6.5/bin/ruby
  Config Dir        /Users/riffraff/.rvm/rubies/ruby-2.6.5/etc
RubyGems            3.2.28
  Gem Home          /Users/riffraff/.rvm/gems/ruby-2.6.5
  Gem Path          /Users/riffraff/.rvm/gems/ruby-2.6.5:/Users/riffraff/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0
  User Home         /Users/riffraff
  User Path         /Users/riffraff/.gem/ruby/2.6.0
  Bin Dir           /Users/riffraff/.rvm/gems/ruby-2.6.5/bin
Tools               
  Git               2.33.0
  RVM               1.29.12 (latest)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2021-09-23
Git SHA           99b72cbd55
Released Version  true
```

## Bundler settings

```
build.libxml-ruby
  Set for the current user (/Users/riffraff/.bundle/config): "--use-system-libraries"
build.nokogiri
  Set for the current user (/Users/riffraff/.bundle/config): "--use-system-libraries"
build.puma
  Set for the current user (/Users/riffraff/.bundle/config): "--with-cflags=-Wno-error=implicit-function-declaration --with-opt-dir=/usr/local/opt/openssl"
gem.coc
  Set for the current user (/Users/riffraff/.bundle/config): true
gem.mit
  Set for the current user (/Users/riffraff/.bundle/config): false
gem.test
  Set for the current user (/Users/riffraff/.bundle/config): "minitest"
```

**Comment by deivid-rodriguez** [comment] 2021-09-29 18:03
Hi @riffraff, thanks for the issue. The problem is clear and a PR is appreciated. Intuitively my solution though would be to include the glob if present in `Bundler::Source::Git#to_s` representation, since otherwise user won't be able to differentiate the sources whe bundler displays them (not only causing this issue, but making it ambiguous in general, right?)

**Comment by riffraff** [comment] 2021-09-29 18:18
hey @deivid-rodriguez yeah, that was my first solution too, based on how it's done in [to_lock](https://github.com/rubygems/rubygems/blob/96e5cff3df491c4d943186804c6d03b57fcb459b/bundler/lib/bundler/source/git.rb#L45) but I was not sure what the implications might be. I'll try to create a PR in the morning.

**Comment by deivid-rodriguez** [comment] 2021-10-08 08:57
This was closed by https://github.com/rubygems/rubygems/pull/4947.

**Closed by deivid-rodriguez** 2021-10-08 08:57 UTC
Labels: Bundler
