### ISSUE TITLE
Bundler project specific options

### ISSUE THREAD

**Issue by abitrolly** [rubygems/rubygems#7181] opened 2023-11-21 10:58 UTC
### Describe the problem as clearly as you can

When installing `gems` for GitLab, it is easy to break other projects. To fix that by installing GitLab gems into project subdir, I've committed `.bundle/config` with the following contents into the repo.

```yaml
---
BUNDLE_PATH: ".gems"
```

That, however, was met with resistance, as people tell me that `.bundle/config` automatically saves user options, even implicit ones, such as `bundle install --jobs`.

So what are the project level settings file that could be committed to repository without conflicting with user preferences for the same project?

### What were you expecting to happen?

1. Config location for global user preferences for `bundler`
2. Config location for project specific preferences that override global user preferences
3. Config location for project specific user preferences that override project preferences

**Comment by indirect** [comment] 2023-11-21 19:05
We plan to change the `path` setting in the future to default to `.bundle`, to avoid this kind of problem with shared gems. In the meantime, you can set this at the user level with `bundle config set --global path .bundle`. At the individual project level, I normally handle this in the project's setup script, with commands like this:

```
bundle config set path .bundle
bundle install
```

**Comment by abitrolly** [comment] 2023-11-21 21:15
@indirect the problem is that people complain that `bundle config set path .bundle` is user level setting to override project settings. It creates `.bundle/config` that then starts to gather all other user options that should not be committed. Therefore there is no way for project specific settings.

**Comment by indirect** [comment] 2023-11-21 21:40
If you run `bundle config set path .bundle`, it will create a _project-level_ settings file in `$PROJECT/.bundle/config`. If you run `bundle config --global set path .bundle`, it will create a user-level settings file in `$HOME/.bundle/config`. The project-level setting will win if they conflict.

Bundler does not support checked-in per-project settings, by design. Each developer has final control over where and how gems are installed onto their machine, and allowing those settings to be committed would be a nightmare like committing per-project editor configuration. If you want to provide _suggested_ project settings, we recommend doing that in an automated project configuration and setup script. I usually call mine `bin/setup`.

**Comment by abitrolly** [comment] 2023-11-22 05:47
> Bundler does not support checked-in per-project settings, by design. 

The design needs another iteration to provide solution for projects, who don't want their gems to conflict with gems from other user projects. This is necessary to remove the pain form mainainers who have to deal with that.

> Each developer has final control over where and how gems are installed onto their machine, and allowing those settings to be committed would be a nightmare like committing per-project editor configuration

Do you think https://editorconfig.org/ is a nightmare? But we use it. https://gitlab.com/gitlab-org/gitlab-development-kit/-/blob/main/.editorconfig?ref_type=heads

> If you want to provide suggested project settings, we recommend doing that in an automated project configuration and setup script. I usually call mine bin/setup.

That could work for an inhouse project, but for the project like GitLab which aims to have a 1000 contributors monthly, relying on that everybody will do the setup the right way is unrealistic. People used to run `bundle install` with their other projects.

What I think could solve the problem for gem installation location with no side effects.

 *  **Global user** preference (project doesn't set its own, use that)
 *  **Project** preference (overrides global user preference if set) 
 *  **Project user** preferences that overrides project preference

**Comment by indirect** [comment] 2023-11-22 07:31
> That could work for an inhouse project, but for the project like GitLab which aims to have a 1000 contributors monthly, relying on that everybody will do the setup the right way is unrealistic. People used to run bundle install with their other projects.

I would love to hear about a large project with 1000 contributors monthly that does not have any kind of setup or update scripts, if you know of one. Here is a blog post about [how GitHub uses setup and update scripts](https://github.blog/2015-06-30-scripts-to-rule-them-all/) that provides the perfect place to set up per-project configuration that can be updated by users later.

> The design needs another iteration to provide solution for projects, who don't want their gems to conflict with gems from other user projects. This is necessary to remove the pain form mainainers who have to deal with that.

Insisting that you know better than us what we should do with our time is not a winning strategy for feature requests, my friend. If you have a use-case that is not met, please tell us about your needs. If you have ideas, feel free to tell us those ideas. If you have demands or insist things must be done a certain way, you should go make things work exactly the way you want, and not talk to us about it.

This is a warning that you're getting close to violating the code of conduct for this project. If you make further demands , you'll get a temporary ban from the issue tracker.

**Comment by abitrolly** [comment] 2023-11-23 17:45
Maybe that should be documented then. That you should not use `bundle install`, but provide a wrapper script to call it if you want a project specific configuration.

Is there a way to bail out with error if somebody tries to call `bundle install` directly?

> This is a warning that you're getting close to violating the code of conduct for this project. If you make further demands, you'll get a temporary ban from the issue tracker.

I bet you take the previous message from me personally, because you've misread who the "maintainers" in my phrase are. If you want me to apologize, I can, but let me assure that my intention is not to tell you what to do, but to ensure that you get my point of view right.

**Comment by indirect** [comment] 2023-11-23 18:56
Thank you for explaining further. @deivid-rodriguez pointed out to me that the jobs option you mention as a problem is already slated to be removed from the config file in the future, and we might be able to remove it sooner rather than later.

Would your current needs be met if we stopped saving the jobs option into the config file? Are there other options that are problematic for your team?

The workaround available today for “user preferences that override project preferences” is to set env vars, which will win out against settings in .bundle/config.

**Closed** 2023-11-24 12:33 UTC
Labels: Bundler
