### ISSUE TITLE
$ gem clean and $ gem remove should run in reverse topo sort

### ISSUE THREAD

**Issue by zenspider** [rubygems/rubygems#112] opened 2011-06-14 23:41 UTC
From: http://rubyforge.org/tracker/index.php?func=detail&aid=28713&group_id=126&atid=575

**Comment by duckinator** [comment] 2016-01-01 21:17
rubyforge.org appears to be entirely down, and as such everything related to this issue except the title is missing. Is this still valid? If so, can you provide another source and (preferably) also explain the issue here, so it doesn't disappear again?

**Comment by segiddins** [comment] 2016-01-01 21:24
It actually seems pretty self-explanatory to me -- the goal is to make sure that you remove the gems with the dependencies first, so you always have a correct setup at every point in the process.

**Comment by duckinator** [comment] 2016-01-06 03:16
The `gem uninstall` command [contains this code](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/commands/uninstall_command.rb#L142-L150), then loops through and uninstalls `deps`:

```ruby
    deplist = Gem::DependencyList.new
# <snip>
    deps = deplist.strongly_connected_components.flatten.reverse
```

`Gem::DependencyList` [includes the TSort library](https://github.com/rubygems/rubygems/blob/4a778c9c2489745e37bcc2d0a8f12c601a9c517f/lib/rubygems/dependency_list.rb#L22), and the `strongly_connected_components` method [appears to be defined by said library](http://ruby-doc.org/stdlib-2.0.0/libdoc/tsort/rdoc/TSort.html#method-i-strongly_connected_components).

Given that, I'd say this can be closed. (Although I don't have the permissions to close it, so somebody else will need to handle that.)

**Comment by segiddins** [comment] 2016-01-06 03:39
Thanks for digging into this, @duckinator !

**Closed by segiddins** 2016-01-06 03:39 UTC
Labels: bug report, ready for work

**Comment by zenspider** [comment] 2016-01-06 04:15
Given that I filed that ticket and some of that code is mine... I'm not so sure.

**Comment by segiddins** [comment] 2016-01-06 05:04
@zenspider the issue is 4.5 years old, and the body is inaccessible. If you happen to remember how to reproduce the issues that prompted the issue, then we can re-open and investigate a fix!

**Comment by duckinator** [comment] 2016-01-06 09:20
@zenspider the code that is yours showed up 3 months after this issue was opened, and according to your own commit message does what this issue asks for: https://github.com/rubygems/rubygems/commit/2439243b98892284b78b973ce924e781f7b08388
