### ISSUE TITLE
Reduce friction for newly created gems

### ISSUE THREAD

**Issue by thomasmarshall** [rubygems/rubygems#7699] opened 2024-05-30 08:20 UTC
### Describe the problem as clearly as you can

`bundle gem` creates a gem with an invalid gemspec. This is good and correct because it directs gem authors to add the necessary metadata for their project. However, it also means they cannot use any `bundle` commands (e.g. `bundle add` or `bundle`) in their project before addressing the following:

- invalid `homepage_uri`
- invalid `source_code_uri`
- invalid `changelog_uri`
- invalid `description`
- invalid `summary`
- invalid `homepage`

`homepage_uri`, `source_code_uri`, `changelog_uri`, `description`, and `homepage` can be commented out or removed, but `summary` is required so needs more consideration from the author. Authors may not know which of these fields are required, and I expect most don't have real values ready to assign to them. As such, this adds friction when starting a new project which potentially could have been delayed until the user is ready to publish the gem.

I propose that authors should be able to add dependencies and run `bundle` commands without having to first address the above validation issues. Possible solutions: 

1. Bundler creates a gem with an already valid gemspec. The downside is that authors might forget to add or update these details before publishing the gem.
2. Bundler delays validation of the gemspec (or these specific fields) until necessary (e.g. publishing the gem).

I would be happy to work on this and open a pull request to address it, but I wanted to raise this issue first to see if there is any other solution or if there is a good reason to keep the current behaviour?

### Did you try upgrading rubygems & bundler?

Yes, I am using the following versions:

- Gem version 3.5.11
- Bundler version 2.5.11

### Post steps to reproduce the problem

1. `bundle gem my_gem`
4. `cd my_gem`
5. `bundle add minitest`

### Which command did you run?

`bundle add minitest` (probably any `bundle` command)

### What were you expecting to happen?

Bundler should add `minitest` to my Gemfile. 

### What actually happened?

```
The gemspec at /Users/user/Projects/my_gem/my_gem.gemspec is not valid. Please fix this gemspec.
The validation error was 'metadata['homepage_uri'] has invalid link: "TODO: Put your gem's website or public repo URL here."'
```

### If not included with the output of your command, run `bundle env` and paste the output below

<details>
  <summary>bundle env</summary>

## Environment

```
Bundler       2.5.11
  Platforms   ruby, arm64-darwin-23
Ruby          3.3.1p55 (2024-04-23 revision c56cd86388092faec079981f779f140717020d58) [arm64-darwin-23]
  Full Path   /Users/user/.rubies/ruby-3.3.1/bin/ruby
  Config Dir  /Users/user/.rubies/ruby-3.3.1/etc
RubyGems      3.5.11
  Gem Home    /Users/user/.gem/ruby/3.3.1
  Gem Path    /Users/user/.gem/ruby/3.3.1:/Users/user/.rubies/ruby-3.3.1/lib/ruby/gems/3.3.0
  User Home   /Users/user
  User Path   /Users/user/.gem/ruby/3.3.0
  Bin Dir     /Users/user/.gem/ruby/3.3.1/bin
Tools         
  Git         2.39.3 (Apple Git-145)
  RVM         not installed
  rbenv       not installed
  chruby      0.3.9
```

## Bundler Build Metadata

```
Built At          2024-05-28
Git SHA           4afb2d450a
Released Version  true
```

## Bundler settings

```
gem.changelog
  Set for the current user (/Users/user/.bundle/config): false
gem.ci
  Set for the current user (/Users/user/.bundle/config): false
gem.coc
  Set for the current user (/Users/user/.bundle/config): false
gem.linter
  Set for the current user (/Users/user/.bundle/config): false
gem.mit
  Set for the current user (/Users/user/.bundle/config): false
gem.test
  Set for the current user (/Users/user/.bundle/config): false
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in my_gem.gemspec
gemspec

gem "rake", "~> 13.0"
```

### Gemfile.lock

```
<No /Users/user/Projects/my_gem/Gemfile.lock found>
```

### my_gem.gemspec

```ruby
# frozen_string_literal: true

require_relative "lib/my_gem/version"

Gem::Specification.new do |spec|
  spec.name = "my_gem"
  spec.version = MyGem::VERSION
  spec.authors = ["Example User"]
  spec.email = ["user@example.com"]

  spec.summary = "TODO: Write a short summary, because RubyGems requires one."
  spec.description = "TODO: Write a longer description or delete this line."
  spec.homepage = "TODO: Put your gem's website or public repo URL here."
  spec.required_ruby_version = ">= 3.0.0"

  spec.metadata["allowed_push_host"] = "TODO: Set to your gem server 'https://example.com'"

  spec.metadata["homepage_uri"] = spec.homepage
  spec.metadata["source_code_uri"] = "TODO: Put your gem's public repo URL here."
  spec.metadata["changelog_uri"] = "TODO: Put your gem's CHANGELOG.md URL here."

  # Specify which files should be added to the gem when it is released.
  # The `git ls-files -z` loads the files in the RubyGem that have been added into git.
  gemspec = File.basename(__FILE__)
  spec.files = IO.popen(%w[git ls-files -z], chdir: __dir__, err: IO::NULL) do |ls|
    ls.readlines("\x0", chomp: true).reject do |f|
      (f == gemspec) ||
        f.start_with?(*%w[bin/ test/ spec/ features/ .git appveyor Gemfile])
    end
  end
  spec.bindir = "exe"
  spec.executables = spec.files.grep(%r{\Aexe/}) { |f| File.basename(f) }
  spec.require_paths = ["lib"]

  # Uncomment to register a new dependency of your gem
  # spec.add_dependency "example-gem", "~> 1.0"

  # For more information and examples about making a new gem, check out our
  # guide at: https://bundler.io/guides/creating_gem.html
end
```

</details>

**Comment by deivid-rodriguez** [comment] 2024-05-30 08:34
I think this is essentially a duplicate of #6695?

I agree with the idea of delaying validation to `gem push` time. We could still print warnings, but allow the gem to build when validation errors are not "resolution related", like the gemspec missing name or version. How about that?

**Comment by simi** [comment] 2024-05-30 10:11
@deivid-rodriguez delaying validation to push time looks ok to me. If you would like to explore this @thomasmarshall, validation happens using `Gem::SpecificationPolicy`, good start would be to check where and why `bundle add` (and similar) calls this validation.

**Comment by deivid-rodriguez** [comment] 2024-05-30 11:55
The reason is, I believe, is to make sure `path` and `git` sources gems are valid for resolution, i.e., they have valid name, version, platform, and dependencies. I think that's fine to keep, but other specification warnings can be ignored and delayed to `gem push`.

**Comment by thomasmarshall** [comment] 2024-05-30 19:07
Are metadata fields relevant outside of packaging? I notice some validations are skipped when `packaging` is `false` and it would be a very small change to add the same guard clause to `SpecificationPolicy#validate_metadata` and `SpecificationPolicy#validate_lazy_metadata`.

**Comment by deivid-rodriguez** [comment] 2024-05-30 20:01
I think `packaging` here essentially separates "optional checks" vs "required checks". So you can push a gem not passing optional checks if you want. So I believe your suggestion would essentially make these TODO checks optional which is not what we want. I think we'd want to explicitly ignore this required errors when validating the specification from Bundler side.

**Comment by thomasmarshall** [comment] 2024-05-30 21:03
I saw `packaging` is set to `true` by default and explicitly by the `build` command too, so I figured the "optional checks" would always be performed whenever building the gem. Is that not always the case?

https://github.com/rubygems/rubygems/blob/d3193d24a8d4e5cc2ef13d5f9b7da43d1f510f16/lib/rubygems/specification.rb#L2564-L2570

https://github.com/rubygems/rubygems/blob/d3193d24a8d4e5cc2ef13d5f9b7da43d1f510f16/lib/rubygems/package.rb#L297

https://github.com/rubygems/rubygems/blob/d3193d24a8d4e5cc2ef13d5f9b7da43d1f510f16/lib/rubygems/specification_policy.rb#L49

The only place I can see that sets `packaging` as `false` when validating is in Bundler:

https://github.com/rubygems/rubygems/blob/d3193d24a8d4e5cc2ef13d5f9b7da43d1f510f16/bundler/lib/bundler/rubygems_integration.rb#L51

How does someone push a gem skipping these optional checks? Is there a code path that results in calling `validate(false)` as part of the publishing process? Testing locally I can see that `gem build` always seems to perform the optional checks because `packaging` is set to `true`.

Thanks for your help!

**Comment by simi** [comment] 2024-05-30 23:06
@thomasmarshall have you tried `gem build --force`?

**Comment by thomasmarshall** [comment] 2024-05-30 23:22
@simi the `--force` flag ends up as `skip_validation` here: https://github.com/rubygems/rubygems/blob/d3193d24a8d4e5cc2ef13d5f9b7da43d1f510f16/lib/rubygems/package.rb#L297

It looks like it bypasses validation entirely, not just the checks guarded by the `packaging` flag.

**Comment by simi** [comment] 2024-05-30 23:30
@thomasmarshall ahh, that one is used on rubygems.org side

https://github.com/rubygems/rubygems.org/blob/1420624b01bbd14b32059831c2b95a8713dbb754/app/models/pusher.rb#L292-L294

**Comment by deivid-rodriguez** [comment] 2024-05-31 09:48
I see, thanks for digging in more. I can see how "optional" is confusing here. All checks are normally run, "optional" would mean they only result into warnings, not errors, so you can push gems without fixing those warnings, as opposed to the other "required" checks.

Indeed the `packaging` parameter seems some flag added so that Bundler and RubyGems.org can run only "required validations" without potentially seeing all those "optional" extra warnings printed.

Because of this, I don't think moving these TODO validations from required to optional would be a good solution, because we still want to make these hard errors when pushing gems. I think my approach instead would be to add a new `validate_for_resolution` method that only runs validations strictly required for resolving, and start using that from the Bundler side, insteadl of the current `spec.validate(false)`.

**Comment by thomasmarshall** [comment] 2024-05-31 20:13
Thanks for the suggestion @deivid-rodriguez! I've tried to implement something like that in #7707.

**Comment by thomasmarshall** [comment] 2024-06-01 11:14
While working on this, I noticed the validation happens twice. I think that new behavior as of https://github.com/rubygems/rubygems/pull/7680/commits/639f0b72f40979b552b4bae44a122cfd176115a. Was that commit supposed to be a pure refactor or is the change of behavior intentional? If it's a regression I can open a bug report or attempt a fix.

**Comment by deivid-rodriguez** [comment] 2024-06-04 18:05
I did not intend to make validations run twice with that commit, no! Research on that definitely appreciated, yeah!

**Comment by thomasmarshall** [comment] 2024-06-06 19:10
I opened #7722 to capture what I think is the problem, but I probably don't have the context to attempt a fix for that at the moment.

**Closed as completed** 2024-06-25 14:32 UTC
Labels: Bundler
