### ISSUE TITLE
`bundle update --bundler` is broken in 2.2.32 for git source with `0.0.0.SNAPSHOT` version

### ISSUE THREAD

**Issue by ojab** [rubygems/rubygems#5095] opened 2021-11-25 15:28 UTC
### Describe the problem as clearly as you can

```shell
$ bundle install bundler -v 2.2.32
$ bundle update --bundler
…
The git source https://github.com/….git is not yet checked out. Please run `bundle install`
before trying to start your application
```

Cannot provide more details ATM since it's non-public project, hopefully it's clear what could cause it due to small amount of commits since 2.2.31. 

### Did you try upgrading rubygems & bundler?

Yep.

## Environment

```
Bundler       2.2.31
  Platforms   ruby, x86_64-linux
Ruby          2.7.4p191 (2021-07-07 revision a21a3b7d23704a01d34bd79d09dc37897e00922a) [x86_64-linux]
  Full Path   /home/ojab/.rbenv/versions/2.7.4/bin/ruby
  Config Dir  /home/ojab/.rbenv/versions/2.7.4/etc
RubyGems      3.2.32
  Gem Home    /home/ojab/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0
  Gem Path    /home/ojab/.gem/ruby/2.7.0:/home/ojab/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0
  User Home   /home/ojab
  User Path   /home/ojab/.gem/ruby/2.7.0
  Bin Dir     /home/ojab/.rbenv/versions/2.7.4/bin
Tools         
  Git         2.32.0
  RVM         not installed
  rbenv       rbenv 1.2.0-6-g304cb7b
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-11-08
Git SHA           2505ef8972
Released Version  true
```

**Comment by deivid-rodriguez** [comment] 2021-11-25 15:31
Hi, sorry, no, from the information you have given it's not clear to me what the culprit is. I need a reproducible example, thank you!

**Comment by ojab** [comment] 2021-11-25 15:55
Trying to craft the reproducer and (in the repo with the issue)
```
$ bundle info xxx
Could not find gem 'xxx', because it's in the group 'default', configured to be ignored.
```
:wat:

**Comment by deivid-rodriguez** [comment] 2021-11-25 15:59
What's the result of `bundle config`?

**Comment by ojab** [comment] 2021-11-25 16:00
Nothing related in my view
```
Settings are listed in order of priority. The top value will be used.
build.gpgme
Set for the current user (/home/ojab/.bundle/config): "--use-system-libraries"

build.nokogiri
Set for the current user (/home/ojab/.bundle/config): "--use-system-libraries"

enterprise.contribsys.com
Set for the current user (/home/ojab/.bundle/config): ":[REDACTED]"

gem.changelog
Set for the current user (/home/ojab/.bundle/config): true

gem.ci
Set for the current user (/home/ojab/.bundle/config): false

gem.coc
Set for the current user (/home/ojab/.bundle/config): false

gem.linter
Set for the current user (/home/ojab/.bundle/config): false

gem.mit
Set for the current user (/home/ojab/.bundle/config): false

gem.test
Set for the current user (/home/ojab/.bundle/config): "rspec"

gems.contribsys.com
Set for the current user (/home/ojab/.bundle/config): ":[REDACTED]"

github.com
Set for the current user (/home/ojab/.bundle/config): "ojab:[REDACTED]"

jobs
Set for the current user (/home/ojab/.bundle/config): 8
```

**Comment by deivid-rodriguez** [comment] 2021-11-25 16:02
Nope. I'm at loss.

**Comment by ojab** [comment] 2021-11-25 16:17
```
From: /home/ojab/.rbenv/versions/2.7.4/lib/ruby/site_ruby/2.7.0/bundler/lockfile_generator.rb:42 Bundler::LockfileGenerator#add_sources:

    30: def add_sources
    31:   definition.send(:sources).lock_sources.each_with_index do |source, idx|
    32:     out << "\n" unless idx.zero?
    33: 
    34:     # Add the source header
    35:     out << source.to_lock
    36: 
    37:     # Find all specs for this source
    38:     specs = definition.resolve.select {|s| source.can_lock?(s) }
    39:     add_specs(specs)
    40:   rescue GitError => e
    41:     binding.pry
 => 42:     raise
    43:   end
    44: end

[2] pry(#<Bundler::LockfileGenerator>)> source.to_lock
Bundler::GitError: The qgit source https://github.com/xx/xx.git is not yet checked out. Please run `bundle install` before trying to start your application
from /home/ojab/.rbenv/versions/2.7.4/lib/ruby/site_ruby/2.7.0/bundler/source/git/git_proxy.rb:226:in `allowed_with_path'
Caused by Bundler::GitError: The qgit source https://github.com/xx/xx.git is not yet checked out. Please run `bundle install` before trying to start your application
from /home/ojab/.rbenv/versions/2.7.4/lib/ruby/site_ruby/2.7.0/bundler/source/git/git_proxy.rb:226:in `allowed_with_path'
```
and we have
```
[4] pry(#<Bundler::Source::Git::GitProxy>)> @git.instance_variable_get(:@allow_remote)
=> false
[5] pry(#<Bundler::Source::Git::GitProxy>)> @git.instance_variable_get(:@allow_cached)
=> false
```
there

**Comment by deivid-rodriguez** [comment] 2021-11-25 16:39
Thanks for investigating. I still don't know what's going on 😞.

**Comment by ojab** [comment] 2021-11-25 16:47
I think I found it, the issue is gem version which is `0.0.0.SNAPSHOT`. New directory with `Gemfile`:
```ruby
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'tst_gem', github: 'ojab/tst_gem'
```
hangs locally during `bundle` (`tst_gem` has version `0.1.0.SNAPSHOT`). I guess it cannot resolve it for some reason?

**Comment by ojab** [comment] 2021-11-25 16:49
(and issue during installation because of `dep = @dependencies.find {|d| s.satisfies?(d) }` doesn't succeed and thinks that the gem is not installed)
```
[12] pry(#<Bundler::Definition>)> s
=> #<Bundler::LazySpecification:0x000000000226eec0
 @__identifier=["xxx", Gem::Version.new("0.0.0.SNAPSHOT"), "\u0000"],
 @__to_s="xxx (0.0.0.SNAPSHOT)",
 @dependencies=…,
 @name="xxx",
 @platform="ruby",
 @source=#<Bundler::Source::Git:0x3260 https://github.com/yyy/xxx.git (at main@61b8918)>,
 @specification=nil,
 @version=Gem::Version.new("0.0.0.SNAPSHOT")>
[13] pry(#<Bundler::Definition>)> d
=> Gem::Dependency.new("xxx", Gem::Requirement.new([">= 0"]), :runtime)
```

**Comment by deivid-rodriguez** [comment] 2021-11-25 16:50
The last issue might be fixed by #5092, can you try it?

**Comment by ojab** [comment] 2021-11-25 16:56
Yep, installation issue is fixed, but `bundle update --bundler` still fails :eyes:

**Comment by ojab** [comment] 2021-11-25 16:58
oh! With version `0.0.0.SNAPSHOT` this one could be reproduced, check the `Gemfiile`  above.

**Comment by deivid-rodriguez** [comment] 2021-11-25 17:02
I can't reproduce any of the issues with bundler 2.2.32 and the `Gemfile` above. Can you setup a Github Actions workflow where the issue can be seen?

**Comment by ojab** [comment] 2021-11-25 17:07
https://github.com/ojab/tst_gem/runs/4326626578

**Comment by deivid-rodriguez** [comment] 2021-11-25 17:09
Thanks @ojab, I'll try to figure this out.

**Comment by deivid-rodriguez** [comment] 2021-11-25 19:35
Wow, this is really tricky. So, previously this was working because of ... luck/reasons. There's two problems:

* Bundler assumes `Gemfile` dependencies without any version requirement have an implicit **>= 0** requirement. However, that means "any non prerelease version", not "any version at all". I believe this is a bug, because later on the resolver actually ignores this and includes prereleases if necessary. However, for the version checks we do to verify whether the `Gemfile.lock` is stale with respect to the `Gemfile`, these constraints are actually not ignored.

* My first thought is to change the default implicit requirement to be **>= 0.a** instead, which is RubyGems standard for allowing all versions including prereleases. However, for the specific version string you're using, that doesn't even work, because typographically the leading "S" from "SNAPSHOT" shorts before "a", so "0.0.0.SNAPSHOT" does not satisfy ">= 0.a". So I guess **>= 0.A** should be used instead.

But I'm not sure if implementing the above could break something. I hope not, but the alternatives would be to revert 7e593b05b261020179a622bba16ae19cfeca82d6 which was the offending commit that "broke" this. Basically the only effect that commit had was making our definition actually check versions to decide whether to expire a dependency (and thus got unintentionally broken because version checks are incorrect here).

**Comment by ojab** [comment] 2021-11-25 19:59
I guess this could be closed (could be fixed by bumping gem version), my only concern that it's a breaking change, so feel free to close as WONTFIX if you feel that's appropriate (I'm not the maintained here :P).

**Comment by ojab** [comment] 2021-11-25 20:04
(but yeah, it should fail everytime or never)

**Comment by deivid-rodriguez** [comment] 2021-11-25 20:36
I'll try to fix it! This bug should technically have other ramifications. For example, if I understand this correctly, `bundler` is always unlocking all prerelease dependencies in the `Gemfile`, no matter whether they are being explicitly requested to be unlocked through `bundle update <gem_locked_to_a_prerelease>` or not.

**Comment by deivid-rodriguez** [comment] 2021-11-30 18:52
https://github.com/rubygems/rubygems/pull/5116 should fix this!

**Comment by ojab** [comment] 2021-12-01 10:54
Thanks, works fine here.

**Comment by deivid-rodriguez** [comment] 2021-12-01 11:14
Great, I'll merge it and release it soon.

**Closed** 2021-12-02 09:10 UTC
Labels: type: bug report, Bundler
