### ISSUE TITLE
Failure in `test_traverse_parents_does_not_crash_on_permissions_error`

### ISSUE THREAD

**Issue by duckinator** [rubygems/rubygems#3452] opened 2020-03-27 22:54 UTC
My current problem is that running RubyGems' test suite in [rgdev](https://github.com/duckinator/rgdev#readme)'s CI setup results in a failure for `TestGemUtil#test_traverse_parents_does_not_crash_on_permissions_error`, but using rgdev locally _does not result in this failure_.

Given that rgdev's entire purpose is to make developing RubyGems easier, I'd like to figure out what the heck the problem is.

---

This is the test failure I get on CI:

```
  1) Failure:
TestGemUtil#test_traverse_parents_does_not_crash_on_permissions_error [/home/developer/rubygems/test/rubygems/test_gem_util.rb:48]:
--- expected
+++ actual
@@ -1 +1 @@
-"/home/developer/rubygems/test_rubygems_229"
+"/home/developer/rubygems"
```

Full output can be found here: https://cirrus-ci.com/task/5758333969760256?command=main#L11-L19

---

The thing that most surprises me is that running it locally, I can't reproduce it &mdash; even though it's doing everything in the same docker image! I think this means it's a difference between the CI environment and the local Docker environment. But I have no idea what differences could cause this test failure.

Here's what happens if I run it locally:

```
~$ git clone https://github.com/rubygems/rubygems.git
<...>
~$ cd rubygems
~/rubygems$ rgdev rake setup
<...>
~/rubygems$ rgdev rake test
Ignoring jaro_winkler-1.5.4 because its extensions are not built. Try: gem pristine jaro_winkler --version 1.5.4
Ignoring json-2.3.0 because its extensions are not built. Try: gem pristine json --version 2.3.0
Run options: --seed 5080                                                                                               
                             
# Running:
<...>
Finished in 71.021372s, 30.4979 runs/s, 95.3234 assertions/s.

2166 runs, 6770 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for Unit Tests to /home/puppy/rubygems/coverage. 8135 / 9033 LOC (90.06%) covered.
```

---

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:

(The setup is a bit more complicated than normal, so I included more version info than normal.)

```
$ cd $HOME/rubygems
$ ruby --version
ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-linux-musl]
$ gem env version
2.7.6.2
$ bundle version
Bundler version 2.1.4 (2020-01-05 commit 32a4159325)
$ ruby -Ilib bin/gem env version
Ignoring jaro_winkler-1.5.4 because its extensions are not built. Try: gem pristine jaro_winkler --version 1.5.4
Ignoring json-2.3.0 because its extensions are not built. Try: gem pristine json --version 2.3.0
3.2.0.pre1
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment] 2020-03-28 02:58
Maybe this issue should be open in `rgdev` since it only happens in the `rgdev` CI?

**Comment by duckinator** [comment] 2020-03-29 06:21
@bronzdoc I'm honestly not sure where it makes the most sense to open it, 'cause the whole reason I made rgdev is because I can't run the test suite at all without it. Would opening it on rgdev's repo and asking for help on the Bundler/RubyGems Slack make more sense? If so, I can do that.

**Comment by deivid-rodriguez** [comment] 2020-03-29 13:20
Hi @duckinator! :wave:

This is reproducible in your CI, I'm going to have a look at it today to help you getting unblocked! :+1:

**Comment by deivid-rodriguez** [comment] 2020-03-31 16:39
@duckinator I tried to repro this but first error I get is the one you're currently getting on master: https://github.com/duckinator/rgdev/runs/540770066

The problem there is that your docker image is using `--user-install` but your not adding the proper bin folder to `PATH`, so that installed executables are found. So, after `gem install bundler:2.1.4`, `bundle install` fails because the `bundle` executable is not found.

**Comment by duckinator** [comment] 2020-04-01 20:24
@deivid-rodriguez sorry about that! Serves me right for being like "oh, I can bump this version without making a new branch." :sweat_smile: 

It's back to the error that I reported originally: https://github.com/duckinator/rgdev/runs/553114260

**Comment by deivid-rodriguez** [comment] 2020-04-01 20:36
No problem, I'll have a look tomorrow! :)

**Comment by deivid-rodriguez** [comment] 2020-04-03 15:48
@duckinator It should be fixed by #3476. Have a look!

**Closed** 2020-04-06 14:04 UTC
Labels: RubyGems, status: triage

**Comment by duckinator** [comment] 2020-04-06 17:27
@deivid-rodriguez looks like that [fixed it](https://cirrus-ci.com/task/6659098317946880). Thanks!

**Comment by deivid-rodriguez** [comment] 2020-04-06 17:29
I'm happy to hear that! :+1:
