### ISSUE TITLE
incompatible marshal file format (format version 4.8 required; 60.33 given)

### ISSUE THREAD

**Issue by keykin** [rubygems/rubygems#1589] opened 2016-04-21 13:31 UTC
I'm having a problem.

My current problem is:
```
# gem install bundler
ERROR:  While executing gem ... (TypeError)
    incompatible marshal file format (can't be read)
	format version 4.8 required; 60.33 given
```

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current envrionment details:
# ruby --version
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
# uname -a
Linux localhost.localdomain 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
$ gem env version
2.6.3
```

any help?

thx.

**Comment by bronzdoc** [comment] 2016-08-27 15:57
@keykin Could not reproduce the error with the details you provide, I'm going to close this, please re-open if this is still an issue for you.

**Closed by bronzdoc** 2016-08-27 15:57 UTC

**Comment by hidehiro98** [comment] 2019-02-21 12:37
I have the same error,,,
Ruby version: 2.4.1
```
gem env version
2.6.11
```

**Comment by EliseS1** [comment] 2019-02-21 16:04
Same ! Ruby -v 2.5.3p105

**Comment by maxvia87** [comment] 2019-02-22 08:07
Same issue

**Comment by deivid-rodriguez** [comment] 2019-02-22 09:34
What's going on here? Can someone run the command with the `--backtrace`, `--debug` and `--verbose` flags to give us more information?

**Comment by WvanLelyveld** [comment] 2019-02-22 12:25
```
$ gem install bundler --backtrace --debug --verbose
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `LoadError' at /Users/WvL/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/resolv.rb:170 - LoadError
HEAD http://gems.rubyforge.org/api/v1/dependencies
301 Moved Permanently
HEAD https://rubygems.org
200 OK
HEAD http://gems.github.com/api/v1/dependencies
301 Moved Permanently
HEAD http://gems.github.io/api/v1/dependencies
404 Not Found
Exception `Gem::RemoteFetcher::FetchError' at /Users/WvL/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/rubygems/remote_fetcher.rb:244 - bad response Not Found 404 (http://gems.github.io/api/v1/dependencies)
Exception `Gem::RemoteFetcher::FetchError' at /Users/WvL/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/rubygems/remote_fetcher.rb:274 - bad response Not Found 404 (http://gems.github.io/api/v1/dependencies)
Exception `Errno::EEXIST' at /Users/WvL/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/fileutils.rb:239 - File exists @ dir_s_mkdir - /Users/WvL/.gem/specs/gems.github.com%80
GET http://gems.github.com/prerelease_specs.4.8.gz
301 Moved Permanently
GET http://gems.github.io/prerelease_specs.4.8.gz
404 Not Found
Exception `Gem::RemoteFetcher::FetchError' at /Users/WvL/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/rubygems/remote_fetcher.rb:244 - bad response Not Found 404 (http://gems.github.io/prerelease_specs.4.8.gz)
Exception `Gem::RemoteFetcher::FetchError' at /Users/WvL/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/rubygems/remote_fetcher.rb:274 - bad response Not Found 404 (http://gems.github.io/prerelease_specs.4.8.gz)
Exception `Errno::EEXIST' at /Users/WvL/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/fileutils.rb:239 - File exists @ dir_s_mkdir - /Users/WvL/.gem/specs/gems.github.com%80
GET http://gems.github.com/specs.4.8.gz
301 Moved Permanently
GET http://gems.github.io/specs.4.8.gz
404 Not Found
Exception `Gem::RemoteFetcher::FetchError' at /Users/WvL/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/rubygems/remote_fetcher.rb:244 - bad response Not Found 404 (http://gems.github.io/specs.4.8.gz)
Exception `Gem::RemoteFetcher::FetchError' at /Users/WvL/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/rubygems/remote_fetcher.rb:274 - bad response Not Found 404 (http://gems.github.io/specs.4.8.gz)
Exception `Gem::RemoteFetcher::FetchError' at /Users/WvL/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/rubygems/spec_fetcher.rb:269 - bad response Not Found 404 (http://gems.github.io/specs.4.8.gz)
GET https://rubygems.org?gems=bundler
200 OK
Exception `TypeError' at /Users/WvL/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/rubygems/resolver/api_set.rb:118 - incompatible marshal file format (can't be read)
	format version 4.8 required; 60.33 given
ERROR:  While executing gem ... (TypeError)
    incompatible marshal file format (can't be read)
	format version 4.8 required; 60.33 given
```

**Comment by halilim** [comment] 2019-02-22 12:33
Having a similar issue with rbenv
```
$ gem install bundler --backtrace --debug --verbose
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `LoadError' at /Users/halil/.rbenv/versions/2.6.1/lib/ruby/2.6.0/resolv.rb:170 - LoadError
HEAD http://gems.rubyforge.org/api/v1/dependencies
301 Moved Permanently
HEAD https://rubygems.org
200 OK
GET https://rubygems.org?gems=bundler
200 OK
Exception `TypeError' at /Users/halil/.rbenv/versions/2.6.1/lib/ruby/2.6.0/rubygems/resolver/api_set.rb:118 - incompatible marshal file format (can't be read)
	format version 4.8 required; 60.33 given
ERROR:  While executing gem ... (TypeError)
    incompatible marshal file format (can't be read)
	format version 4.8 required; 60.33 given
	/Users/halil/.rbenv/versions/2.6.1/lib/ruby/2.6.0/rubygems/resolver/api_set.rb:118:in `load'
	/Users/halil/.rbenv/versions/2.6.1/lib/ruby/2.6.0/rubygems/resolver/api_set.rb:118:in `versions'
	/Users/halil/.rbenv/versions/2.6.1/lib/ruby/2.6.0/rubygems/resolver/api_set.rb:55:in `find_all'
	/Users/halil/.rbenv/versions/2.6.1/lib/ruby/2.6.0/rubygems/resolver/composed_set.rb:55:in `block in find_all'
	/Users/halil/.rbenv/versions/2.6.1/lib/ruby/2.6.0/rubygems/resolver/composed_set.rb:54:in `map'
	/Users/halil/.rbenv/versions/2.6.1/lib/ruby/2.6.0/rubygems/resolver/composed_set.rb:54:in `find_all'
	/Users/halil/.rbenv/versions/2.6.1/lib/ruby/2.6.0/rubygems/resolver/best_set.rb:31:in `find_all'
	/Users/halil/.rbenv/versions/2.6.1/lib/ruby/2.6.0/rubygems/resolver/installer_set.rb:155:in `find_all'
	/Users/halil/.rbenv/versions/2.6.1/lib/ruby/2.6.0/rubygems/resolver/installer_set.rb:56:in `add_always_install'
	/Users/halil/.rbenv/versions/2.6.1/lib/ruby/2.6.0/rubygems/dependency_installer.rb:478:in `resolve_dependencies'
	/Users/halil/.rbenv/versions/2.6.1/lib/ruby/2.6.0/rubygems/commands/install_command.rb:201:in `install_gem'
	/Users/halil/.rbenv/versions/2.6.1/lib/ruby/2.6.0/rubygems/commands/install_command.rb:264:in `block in install_gems'
	/Users/halil/.rbenv/versions/2.6.1/lib/ruby/2.6.0/rubygems/commands/install_command.rb:258:in `each'
	/Users/halil/.rbenv/versions/2.6.1/lib/ruby/2.6.0/rubygems/commands/install_command.rb:258:in `install_gems'
	/Users/halil/.rbenv/versions/2.6.1/lib/ruby/2.6.0/rubygems/commands/install_command.rb:165:in `execute'
	/Users/halil/.rbenv/versions/2.6.1/lib/ruby/2.6.0/rubygems/command.rb:321:in `invoke_with_build_args'
	/Users/halil/.rbenv/versions/2.6.1/lib/ruby/2.6.0/rubygems/command_manager.rb:176:in `process_args'
	/Users/halil/.rbenv/versions/2.6.1/lib/ruby/2.6.0/rubygems/command_manager.rb:146:in `run'
	/Users/halil/.rbenv/versions/2.6.1/lib/ruby/2.6.0/rubygems/gem_runner.rb:59:in `run'
	/Users/halil/.rbenv/versions/2.6.1/bin/gem:21:in `<main>'
```

**Comment by WvanLelyveld** [comment] 2019-02-22 12:33
It seems bundler can't find sources for your gem.
It's probably because the remote sources are outdated. You can check your remote sources with `gem env`

```
  - REMOTE SOURCES:
     - http://gems.rubyforge.org/
     - http://gems.github.com
```
Are outdated, you should use https://rubygems.org now.
You can update the config with the following commands:

```
gem sources -r http://gems.rubyforge.org/
gem sources -r http://gems.github.com
gem sources -a https://rubygems.org/
```
When updated, `gem sources -l`should return:
```
*** CURRENT SOURCES ***

https://rubygems.org/
```
Credits go to https://qiita.com/hidehiro98/items/bb6ed9bc109021034af0

**Comment by halilim** [comment] 2019-02-22 12:41
Indeed, updating remote sources fixed it for me.

Is there any official announcement for this? And I have recently installed Ruby 2.6.1, could it be related 
to it? Sorry if I missed something.

**Comment by WvanLelyveld** [comment] 2019-02-22 12:42
Not that I know of.

**Comment by halilim** [comment] 2019-02-22 12:49
Apparently #2648 is the same issue. Not sure if these are one-off issues, or if there was an underlying change that broke something for a group of people.

**Comment by nachoal** [comment] 2019-02-25 18:18
Same issue I had after upgrading my hombrew version and messing around with Ruby files on Mac OS Mojave, @WvanLelyveld answer fixed my problem. Thanks

**Comment by foucist** [comment] 2019-04-03 04:32
Suddenly happened to me as well.  Probably because my source was still http://rubygems.org/  instead of https://rubygems.org/

**Comment by yasonrails** [comment] 2022-09-23 18:33
https://github.com/athityakumar/colorls/issues/398

**Comment by Skumar-Stock** [comment] 2023-06-30 12:04
It seems like version conflict of Rails.
[This](https://stackoverflow.com/questions/54786580/error-while-executing-gem-typeerror-incompatible-marshal-file-format-can/76588716#76588716) helped me a lot.
