### ISSUE TITLE
Version#approximate_recommendation suggests invalid specifier for prereleases

### ISSUE THREAD

**Issue by indirect** [rubygems/rubygems#1172] opened 2015-02-17 23:10 UTC
A `Gem::Version` object returns a specifier string from the `#approximate_recommendation` method, but when the version in question is a prerelease, the approximate_recommendation requirement cannot be satisfied by the gem itself:

```
> v = Gem::Version.new("1.9.0.dev")
=> Gem::Version.new("1.9.0.dev")
> v.approximate_recommendation
=> "~> 1.9"
> Gem::Requirement.new(v.approximate_recommendation).satisfied_by?(v)
=> false
```

**Comment by zzak** [comment] 2015-02-19 19:11
I'm not sure when/where this was discussed in the past, but it seems to be a feature.

What I mean is, historically I think this was expected behavior. One case could be user doesn't expect to install prerelease gem when updating, because it may not be considered stable.

**Comment by indirect** [comment] 2015-02-19 19:29
I'm not saying that ~> 1.9 should match the prerelease, I'm saying the method should return "~> 1.9.pre" or whatever, which both matches the same versions and allows prereleases.

**Comment by drbrain** [comment] 2015-03-17 06:45
@Elffers was asking me about this bug and it might be complicated to fix:

1. In order to be useable the recommendation needs to be compound like `>= 1.a, < 2`
1. Gem::Requirement.new doesn't accept compound requirements as a single string (but this might be changeable). We can't change the return type so if we can't update Gem::Requirement to accept a comma-separated string this method can't be fixed in RubyGems 2.x
1. Building a gem with development dependencies will issue a warning since you shouldn't be doing that. We need proper documentation to prevent bug reports.
1. We might also want to make sure gem building warns in all the appropriate cases for prerelease dependencies and none of the inappropriate ones (a prerelease gem should be able to have prerelease dependencies without the packager seeing warnings).

**Comment by copiousfreetime** [comment] 2016-03-14 18:28
I've confirmed that the behavior described by @indirect is still the case. And I believe @drbrain in (3) above means prerelease dependencies, not development dependencies.

**Closed** 2018-07-09 14:39 UTC
Labels: category: API, status: ready, type: bug report
