### ISSUE TITLE
bundler: failed to load command message when running a command.

### ISSUE THREAD

**Issue by martinos** [rubygems/rubygems#6620] opened 2023-04-17 16:24 UTC
### Describe the problem as clearly as you can

When I a command is run using `bundle exec` and raises an exception, I get an error message that doesn't come from the command that ran. I think that bundler should not change the behavior of the original command. 

### Did you try upgrading rubygems & bundler?

Yes

```
bundle -v
Bundler version 2.4.12
```

### Post steps to reproduce the problem

Create a thor file (misc.thor)

```ruby
class Misc < Thor
  desc "test_failure", "This task is for testing failure"

  def test_failure
    raise "EXCEPTION SENT MY test_failure task"
  end
end
```

### Which command did you run?

```
 bundle exec thor misc:test_failure
```

### What were you expecting to happen?

I am expecting the same behavior that running the command without `bundle exec`

Which only shows the stacktrace and the exception message. 

Example:

```
thor misc:test_failure
```

It returns

```
Traceback (most recent call last):
	13: from /Users/me/.gem/ruby/2.7.7/bin/thor:23:in `<main>'
...
...
	 1: from /Users/me/.gem/ruby/2.7.7/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/Users/me/tmp/bundler_issue/misc.thor:5:in `test_failure': EXCEPTION SENT MY test_failure task (RuntimeError)
```

Message

### What actually happened?

I got this message:

```
bundler: failed to load command: thor (/Users/gem/.gem/ruby/2.7.7/bin/thor)
	14: from /Users/me/.gem/ruby/2.7.7/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
...
...
	 1: from /Users/gem/.gem/ruby/2.7.7/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/Users/gem/tmp/bundler_issue/misc.thor:5:in `test_failure': EXCEPTION SENT MY test_failure task (RuntimeError)
```

**Comment by martinos** [comment] 2023-04-17 18:26
I would like to notice that the error message is not clear.

bundler: failed to load command: thor

It does not fail to load the command, it fails to run it successfully, which adds confusion.

**Comment by duckinator** [comment] 2023-07-27 21:39
The problem is that it _does_ fail to load the command, and it _has to_ change the command. The entire way `bundle exec` works is by doing `Kernel.load(...)` and catching an exception: https://github.com/rubygems/rubygems/blob/e2e2e7cff176ad0d25fa6e9c0d21a500217b47bd/bundler/lib/bundler/cli/exec.rb#L51-L65

And since thor throws an exception instead of exiting cleanly, `bundle exec` _fails to load the command._

However, the only change on my system between `thor misc:test_failure` and `bundle exec thor misc:test_failure` is it prepends the `bundler: failed to load ...` line and _adds_ lines to the end of stack trace. Nothing is modified or removed.


Here's what the full output looks like on my system:

```shellsession
puppy@orthrus:~/dev/rubygems/rg6620$ thor misc:test_failure
/usr/home/puppy/dev/rubygems/rg6620/misc.thor:5:in `test_failure': EXCEPTION SENT MY test_failure task (RuntimeError)
        from /usr/home/puppy/.gem/ruby/3.2.1/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /usr/home/puppy/.gem/ruby/3.2.1/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/home/puppy/.gem/ruby/3.2.1/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /usr/home/puppy/.gem/ruby/3.2.1/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        from /usr/home/puppy/.gem/ruby/3.2.1/gems/thor-1.2.2/lib/thor/runner.rb:41:in `method_missing'
        from /usr/home/puppy/.gem/ruby/3.2.1/gems/thor-1.2.2/lib/thor/command.rb:29:in `run'
        from /usr/home/puppy/.gem/ruby/3.2.1/gems/thor-1.2.2/lib/thor/command.rb:135:in `run'
        from /usr/home/puppy/.gem/ruby/3.2.1/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/home/puppy/.gem/ruby/3.2.1/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /usr/home/puppy/.gem/ruby/3.2.1/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        from /usr/home/puppy/.gem/ruby/3.2.1/gems/thor-1.2.2/bin/thor:6:in `<top (required)>'
        from /home/puppy/.gem/ruby/3.2.1/bin/thor:25:in `load'
        from /home/puppy/.gem/ruby/3.2.1/bin/thor:25:in `<main>'
puppy@orthrus:~/dev/rubygems/rg6620$ bundle _2.4.12_ exec thor misc:test_failure
bundler: failed to load command: thor (/usr/home/puppy/dev/rubygems/rg6620/.bundle/gems/ruby/3.2.0/bin/thor)
/usr/home/puppy/dev/rubygems/rg6620/misc.thor:5:in `test_failure': EXCEPTION SENT MY test_failure task (RuntimeError)
        from /usr/home/puppy/dev/rubygems/rg6620/.bundle/gems/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /usr/home/puppy/dev/rubygems/rg6620/.bundle/gems/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/home/puppy/dev/rubygems/rg6620/.bundle/gems/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /usr/home/puppy/dev/rubygems/rg6620/.bundle/gems/ruby/3.2.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        from /usr/home/puppy/dev/rubygems/rg6620/.bundle/gems/ruby/3.2.0/gems/thor-1.2.2/lib/thor/runner.rb:41:in `method_missing'
        from /usr/home/puppy/dev/rubygems/rg6620/.bundle/gems/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:29:in `run'
        from /usr/home/puppy/dev/rubygems/rg6620/.bundle/gems/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:135:in `run'
        from /usr/home/puppy/dev/rubygems/rg6620/.bundle/gems/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/home/puppy/dev/rubygems/rg6620/.bundle/gems/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /usr/home/puppy/dev/rubygems/rg6620/.bundle/gems/ruby/3.2.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        from /usr/home/puppy/dev/rubygems/rg6620/.bundle/gems/ruby/3.2.0/gems/thor-1.2.2/bin/thor:6:in `<top (required)>'
        from /usr/home/puppy/dev/rubygems/rg6620/.bundle/gems/ruby/3.2.0/bin/thor:25:in `load'
        from /usr/home/puppy/dev/rubygems/rg6620/.bundle/gems/ruby/3.2.0/bin/thor:25:in `<top (required)>'
        from /usr/home/puppy/.gem/ruby/3.2.1/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/home/puppy/.gem/ruby/3.2.1/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/home/puppy/.gem/ruby/3.2.1/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/home/puppy/.gem/ruby/3.2.1/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
        from /usr/home/puppy/.gem/ruby/3.2.1/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/home/puppy/.gem/ruby/3.2.1/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/home/puppy/.gem/ruby/3.2.1/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/home/puppy/.gem/ruby/3.2.1/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
        from /usr/home/puppy/.gem/ruby/3.2.1/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/home/puppy/.gem/ruby/3.2.1/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
        from /usr/home/puppy/.gem/ruby/3.2.1/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
        from /usr/home/puppy/.gem/ruby/3.2.1/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/home/puppy/.gem/ruby/3.2.1/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
        from /home/puppy/.gem/ruby/3.2.1/bin/bundle:25:in `load'
        from /home/puppy/.gem/ruby/3.2.1/bin/bundle:25:in `<main>'
puppy@orthrus:~/dev/rubygems/rg6620$
```

**Comment by deivid-rodriguez** [comment] 2024-09-17 14:31
As @duckinator explained, this is expected behavior, so I will close this, but let me know if the explanation still does not make sense to you @martinos.

**Closed by deivid-rodriguez** 2024-09-17 14:31 UTC
Labels: Bundler
