### ISSUE TITLE
Installing from a git multi-repo (Rails) fails (bundler v2.1.5)

### ISSUE THREAD

**Issue by palkan** [rubygems/rubygems#4540] opened 2021-04-16 16:58 UTC
### Describe the problem as clearly as you can

Installing from Git fails to resolve dependencies.

### Post steps to reproduce the problem

Gemfile:

```ruby
gem "rails", git: "https://github.com/rails/rails.git", branch: "main"
```

Fails with ([CI link](https://github.com/anycable/anycable-rails/runs/2363618859?check_suite_focus=true
)):

```
Fetching https://github.com/rails/rails.git
Bundler could not find compatible versions for gem "activerecord":
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
  In railsmaster.gemfile:
    activerecord

    rails was resolved to 7.0.0.alpha, which depends on
      activerecord (= 7.0.0.alpha)

Could not find gem 'activerecord (= 7.0.0.alpha)', which is required by gem
'rails', in any of the relevant sources:
  rubygems repository https://rubygems.org/ or installed locally
```

[Works](https://github.com/anycable/anycable-rails/pull/155/checks?check_run_id=2364206352) in 2.1.4.

**Comment by deivid-rodriguez** [comment] 2021-04-17 09:38
Thanks for the report @palkan, I'll look into it.

**Comment by deivid-rodriguez** [comment] 2021-04-17 10:24
The problem is that `add_development_dependency "activerecord"` in the gemspec forces the dependency to be pulled from rubygems.org, since gemspecs don't really have the notion of gem sources. So the workaround would be to move that dependency to each gemfile, like this (you don't need to add it to the railsmaster.gemfile since it's implicitly pulled from the git source):

```diff
diff --git a/anycable-rails.gemspec b/anycable-rails.gemspec
index 42cbaad..1e9a396 100644
--- a/anycable-rails.gemspec
+++ b/anycable-rails.gemspec
@@ -29,7 +29,6 @@ Gem::Specification.new do |spec|
   spec.add_dependency "actioncable", ">= 6"
   spec.add_dependency "globalid"
 
-  spec.add_development_dependency "activerecord"
   spec.add_development_dependency "ammeter", "~> 1.1"
   spec.add_development_dependency "bundler", ">= 1.10"
   spec.add_development_dependency "rake", "~> 13.0"
diff --git a/gemfiles/rails6.gemfile b/gemfiles/rails6.gemfile
index 14fe195..4024319 100644
--- a/gemfiles/rails6.gemfile
+++ b/gemfiles/rails6.gemfile
@@ -1,6 +1,7 @@
 source "https://rubygems.org"
 
 gem "actioncable", "~> 6.0"
+gem "activerecord"
 gem "rspec-rails", "~> 4.0.0"
 gem "sqlite3", "~> 1.4"
 
diff --git a/gemfiles/rails60.gemfile b/gemfiles/rails60.gemfile
index ba21c96..495d330 100644
--- a/gemfiles/rails60.gemfile
+++ b/gemfiles/rails60.gemfile
@@ -1,6 +1,7 @@
 source "https://rubygems.org"
 
 gem "actioncable", "~> 6.0.0"
+gem "activerecord"
 gem "rspec-rails", "~> 4.0.0"
 gem "sqlite3", "~> 1.4"
 
```

**Comment by palkan** [comment] 2021-04-18 06:37
Thanks!

So, should it be considered a bug then or it's an expected behavior (and the previous behavior was actually a bug I relied on)?

**Comment by deivid-rodriguez** [comment] 2021-04-19 10:58
Hi again, I think this is a consequence of https://github.com/rubygems/rubygems/pull/4418.

So, yeah, we chose to call that change a bug fix, and your case would be working by chance because of the bug. I admit that it's much less clear in this particular case of using `add_development_dependency`.

When you have

```ruby
# depends-on-foo.gemspec
Gem::Specification.new do |s|
  ...
  s.add_development_dependency "foo"
end
```

```ruby
# Gemfile
source "https://rubygems.org"

gemspec

gem "bar", git: "https://git_source_including_foo_and_bar" 
```

That's essentially equivalent to

```ruby
# Gemfile
source "https://rubygems.org"

gem "depends-on-foo", path: "."
gem "foo", group: :development

gem "bar", git: "https://git_source_for_foo_and_bar" 
```

Previously bundler would pick up "foo" from the git source in case it was necessary for resolution (for example, if "foo" is not present in the default source, or if the version of "foo" present in the default source does not match all requirements like in this case). Now bundler will only try to pull "foo" from the default source, instead of looking in all defined sources.

The idea is that this is more expected, and more secure, but it does break this particular situation.

**Comment by deivid-rodriguez** [comment] 2021-04-21 11:42
I'll close this given the above, sorry for the inconvenience :pray:.

**Closed by deivid-rodriguez** 2021-04-21 11:42 UTC
Labels: Bundler
