### ISSUE TITLE
Symlinks in a gemspec's files are not packaged

### ISSUE THREAD

**Issue by segiddins** [rubygems/rubygems#1208] opened 2015-03-26 00:55 UTC

**Comment by drbrain** [comment] 2015-03-26 01:07
Symlinks are not a portable filesystem feature.

Why do you need them?

**Comment by segiddins** [comment] 2015-03-26 01:10
Not all gems are meant to work on multiple platforms :)

I was working on a gem that vendored several OS X frameworks, which included symlinks (and required those symlinks in order to be openable). I wrote a small workaround to manually re-create those symlinks, but it would've been nice if the packaged gem included them.

**Comment by drbrain** [comment] 2015-03-26 01:38
Which gem?

Why not compute full paths using the APIs provided?

**Comment by segiddins** [comment] 2015-03-26 01:43
Versions 0.1.0-0.1.1 of https://github.com/Realm/jazzy (fixed in 0.1.2). It's not really possible to use full paths because frameworks are _expected_ to have symlinks in them.

**Comment by drbrain** [comment] 2015-03-30 23:44
Duplicate of #1209

**Closed** 2015-04-27 20:52 UTC
Labels: status - duplicate
