### ISSUE TITLE
Disallow gem downgrade when bundling by default

### ISSUE THREAD

**Issue by ngan** [rubygems/rubygems#7402] opened 2024-01-19 18:19 UTC
### Describe the problem as clearly as you can

I ran into a situation where doing a `bundle update some_gem` downgraded another gem so that the version requirements worked out. It wasn't until I `git reset --hard` and ran it again that I noticed the "other gem" getting downgraded in the printout.

I think it's very rare that someone would actually want dependencies to be downgraded for the sake of getting a bundle to be bundle-able.

I'd like to propose that, by default, Bundler errors when any gem is downgraded during a bundle update/install. We can provide a CLI flag to bypass this, like: `bundle update some_gem --allow-downgrades`

**Comment by deivid-rodriguez** [comment] 2024-01-22 15:22
Do you have an example where Bundler is downgrading dependencies? We have code to ensure Bundler never does this for direct dependencies. For direct dependencies, it does allow it as long as that permits bumping direct dependencies. I believe this is the behavior that everyone expect? I recall we got the same feature request in the past, but the downgrade was due to a bug in Bundler and after fixing the bug, the flag was no longer necessary.

**Comment by rubyFeedback** [comment] 2024-01-23 06:29
> I believe this is the behavior that everyone expect?

I can't say whether everyone expects it or not in this particular case here, but I
do remember people having been surprised about bundler's behaviour in
the past. For instance, an old IRC quote I have from banister (pry's author)
from June 2012 was "somehow bundler is getting in the way but i didnt ask
bundler to do a damn thing" specifically. Evidently this is a very long time
ago, and unrelated to the issue here, but I think assumptions about what
people expect from software may differ. So asking to toggle that behaviour,
such as via --allow-downgrades and --disallow-downgrades (or --enable 
and --disable correspondingly) may make sense (but, again, I don't know
if the behaviour here requires more controls; I just understand the basic
use case / requirement).

**Comment by deivid-rodriguez** [comment] 2024-03-26 19:28
I'm happy to add flags for behavior to trigger different behaviors when both modes are useful for different people / different situations. But I think it'd need to be properly motivated. As I explained, last time we were asked "can we add a flag so Bundler does not dowgrade dependencies", the root cause was actually a bug in Bundler, so we could do without adding any flags.

I suspect it's a similar situation here, so I'll tentatively close this. But happy to discuss further and eventually reopen if the flag is actually needed in this situation.

**Closed by deivid-rodriguez** 2024-03-26 19:28 UTC
Labels: Bundler

**Comment by ngan** [comment] 2024-03-27 04:33
I run into this once extremely rarely so totally fine with closing. We can use this issue as a reference for another point in time when this feature request was made. Thank you for your work, @deivid-rodriguez!
