### ISSUE TITLE
Bundler: Issue doing basic docker commands with bundler. Path variable not respected

### ISSUE THREAD

**Issue by luke-hill** [rubygems/rubygems#5286] opened 2022-01-13 17:28 UTC
### Describe the problem as clearly as you can

Cannot run basic docker-build commands

### Did you try upgrading rubygems & bundler?

Upgrading / version issues I **believe** is the issue. I'm trying to downgrade now to fix them

### Post steps to reproduce the problem

Try and build this image (I use compose)

```
FROM ruby:3.0.2-alpine

RUN mkdir -p /app

WORKDIR /app

ENV BUNDLE_PATH=/app/vendor/bundle \
    BUNDLER_VERSION='2.2.33'

RUN apk update && \
    apk upgrade && \
    apk add --no-cache jq build-base curl bash && \
    gem install bundler -v $BUNDLER_VERSION

RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    truncate -s 0 /var/log/*log

COPY Gemfile Gemfile.lock /app/

RUN bundle install --path vendor/bundle

USER root

COPY . /app

RUN $GEM_PATH
```

### Which command did you run?

docker-compose build. Bundler is not editing / installing gems correctly. It seems to be installing them to a local location. I then cannot access this local location for another reason

### What were you expecting to happen?

Bundler to install things to vendor/bundle

### What actually happened?

Bundler tries to install to usr/local/bundle - I then get some oddities.

**Comment by deivid-rodriguez** [comment] 2022-01-13 22:23
I did a quick test and everything worked as expected to me. Can you provide exact steps to reproduce the issue you're having?

**Comment by luke-hill** [comment] 2022-01-14 09:03
`docker-compose build`

**Comment by PhilippGoecke** [comment] 2022-01-14 10:02
We seem to have the same/similar issue. We use bundler inside a pipeline and set
`bundle config set path 'vendor'`
and later we use the result inside a Docker Context.

One thing i want to mention is, that it might be that we used bundler 2.2.33 to set this path and later used bundler 2.3.5 in Docker (Could this be the reason?).

In Docker we see the following Error:
```
/home/rails/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.5/lib/bundler/definition.rb:481:in `materialize': Could not find rails-6.0.4.4, ... long list of gems ... , crass-1.0.6 in any of the sources (Bundler::GemNotFound)
        from /home/rails/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.5/lib/bundler/definition.rb:190:in `specs'
        from /home/rails/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.5/lib/bundler/definition.rb:238:in `specs_for'
        from /home/rails/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:18:in `setup'
        from /home/rails/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.5/lib/bundler.rb:151:in `setup'
        from /home/rails/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.5/lib/bundler/setup.rb:20:in `block in <top (required)>'
       from /home/rails/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.5/lib/bundler/ui/shell.rb:136:in `with_level'
        from /home/rails/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.5/lib/bundler/ui/shell.rb:88:in `silence'
       from /home/rails/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.5/lib/bundler/setup.rb:20:in `<top (required)>'
        from /home/rails/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        from /home/rails/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        from /home/rails/project/config/boot.rb:8:in `<top (required)>'
        from bin/rails:3:in `require_relative'
        from bin/rails:3:in `<main>'
```

**Comment by deivid-rodriguez** [comment] 2022-01-14 10:17
Ok, thanks. I'll reopen then given that different people are seeing this. I'm not sure about the path divergence, maybe it's related to some change in bundler 2.3 but I'm not totally sure yet. Again, a way to reproduce the issue is quite necessary to fix this given that I don't yet know the actual culprit or how to see the error for myself.

**Comment by luke-hill** [comment] 2022-01-14 11:25
I think the issue here is as follows.

Bundler messing about with env vars. Docker then can't write to certain areas. I don't have a lot of free time sorry, I'll try get a github repo soon. But given it's just a single dockerfile I'm not sure how it's my env (Not saying it isn't).

I'm 99% sure it's actually some command or setting I've done wrong. But I'll try some different versions of bundler to see if I can isolate further. Some bundler settings **do seem wrong though** pointing to `/usr/local/bundle` when I've no idea why?

**Comment by luke-hill** [comment] 2022-01-14 12:09
@deivid-rodriguez question. Does the order of return values in `bundle config` matter? If so then I think I've half found the issue.

**Comment by PhilippGoecke** [comment] 2022-01-14 12:17
I would expect, that the order has no influence - at least should not have an influence. But maybe ...

**Comment by luke-hill** [comment] 2022-01-14 12:19
Between bundler -v 2.0.2 and bundler -v 2.2.33 the order of the variables returned by bundle config changed. I think this is partially the reason why I'm encountering issues. But it doesn't fix all of them.

**Comment by deivid-rodriguez** [comment] 2022-01-14 12:39
I don't think the order should matter, no.

**Comment by luke-hill** [comment] 2022-01-14 16:01
Further investigation yields bundler setting a key value of `/usr/local/bundle` which is then being picked up during docker build. So I'm not convinced the order isn't mattering. I "think" the order **is** the problem here, which a downgrade is partially easing.

**Comment by deivid-rodriguez** [comment] 2022-01-14 18:44
I'm not fully sure what you mean by "order" here. If you apply a configuration twice, the second one will be applied, and that hasn't changed, if that's what you mean. In any case, the best way to get this fixed is to provide a reproduction.

**Comment by deivid-rodriguez** [comment] 2022-01-17 09:47
I'm really willing to help here, but so far no useful information has been shared. @PhilippGoecke Can you help us with that reproducible example? Since this happens under Docker, which provides its own full isolated environment, it should be easy to share a reproducible `Dockerfile` (the one given in the original post in this ticket is incomplete, since it provides no `Gemfile`, `Gemfile.lock` files, for example).

**Comment by luke-hill** [comment] 2022-01-17 09:55
Any Gemfile and/or lock should be enough. The issue is bundler causes the configuration issues. So in theory you could omit all the lines after the bundler install invocation.

Try doing just the following

```
FROM ruby:3.0.2-alpine

RUN mkdir -p /app

WORKDIR /app

ENV BUNDLE_PATH=/app/vendor/bundle \
    BUNDLER_VERSION='2.2.33'

RUN apk update && \
    apk upgrade && \
    apk add --no-cache jq build-base curl bash && \
    gem install bundler -v $BUNDLER_VERSION
```

**Comment by luke-hill** [comment] 2022-01-17 10:49
I have mentioned a couple of times it's trying to install to `/usr/local/bundle` I'm not sure what more I can say to you?

1) Run `docker-compose build`
2) Observe it tries to install to `/usr/local/bundle` which then gives an error.

**Comment by deivid-rodriguez** [comment] 2022-01-17 11:14
Using the `Dockerfile` you provided above, and the following `Gemfile` and `Gemfile.lock`


```ruby
# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "rake", "~> 13.0"
```

``` 
GEM
  remote: https://rubygems.org/
  specs:
    rake (13.0.6)

PLATFORMS
  aarch64-linux-musl
  arm64-darwin-21

DEPENDENCIES
  rake (~> 13.0)

BUNDLED WITH
   2.3.4
```

I run the following

```
$ docker build -t foo --progress plain --no-cache .
#2 [internal] load .dockerignore
#2 sha256:24ad7cf5947b97a5191639cd66955704d7a885c566d03a449ab9fae15733fc32
#2 transferring context: 2B done
#2 ...

#1 [internal] load build definition from Dockerfile
#1 sha256:f4a5d8accdb91006f179c52bd162823c71a68cfa130efc4f97693683934fd704
#1 transferring dockerfile: 532B done
#1 DONE 0.3s

#2 [internal] load .dockerignore
#2 sha256:24ad7cf5947b97a5191639cd66955704d7a885c566d03a449ab9fae15733fc32
#2 DONE 0.5s

#3 [internal] load metadata for docker.io/library/ruby:3.0.2-alpine
#3 sha256:06846c9222efbcbfbcfdeb20e9621159bd9c6b44ee72918172b928432a4541bf
#3 DONE 1.3s

#4 [1/9] FROM docker.io/library/ruby:3.0.2-alpine@sha256:b5e479ebc175726b5b77168b78b0322fec55e730c96f38ce8ca5b565aceca3a6
#4 sha256:3ea9cb944880b8c30eb15e8aeb0223ae7b2ac9e3951f690b5d909475c2ea3e9a
#4 CACHED

#9 [internal] load build context
#9 sha256:0a06ed18f0e14d4c445925b6b41273e6ade27cd0db22deef7a835b9ff2b18102
#9 transferring context: 585B done
#9 DONE 0.3s

#5 [2/9] RUN mkdir -p /app
#5 sha256:50f35591372b7341505b2e29cafb1e6c9c13ba58341673730a430b4ef8a785d9
#5 DONE 1.1s

#6 [3/9] WORKDIR /app
#6 sha256:29720211a09810988bf52c439299c4e2d6994abb4f0e3b1fc6b03e818166a504
#6 DONE 0.7s

#7 [4/9] RUN apk update &&     apk upgrade &&     apk add --no-cache jq build-base curl bash &&     gem install bundler -v 2.2.33 &&     gem list bundler
#7 sha256:22ef6e9c74efb9ffaf242b0d94b79b62f10de1c25f03bc5f5813a71f8c573159
#7 0.881 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/aarch64/APKINDEX.tar.gz
#7 1.331 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/aarch64/APKINDEX.tar.gz
#7 1.796 v3.14.3-80-gaae985bf8c [https://dl-cdn.alpinelinux.org/alpine/v3.14/main]
#7 1.796 v3.14.3-79-gbc8053dfad [https://dl-cdn.alpinelinux.org/alpine/v3.14/community]
#7 1.796 OK: 14825 distinct packages available
#7 1.904 OK: 20 MiB in 36 packages
#7 1.917 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/aarch64/APKINDEX.tar.gz
#7 2.164 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/aarch64/APKINDEX.tar.gz
#7 2.298 (1/24) Installing bash (5.1.4-r0)
#7 2.340 Executing bash-5.1.4-r0.post-install
#7 2.341 (2/24) Installing binutils (2.35.2-r2)
#7 2.468 (3/24) Installing libmagic (5.40-r1)
#7 2.529 (4/24) Installing file (5.40-r1)
#7 2.558 (5/24) Installing libgomp (10.3.1_git20210424-r2)
#7 2.594 (6/24) Installing libatomic (10.3.1_git20210424-r2)
#7 2.623 (7/24) Installing libgphobos (10.3.1_git20210424-r2)
#7 2.705 (8/24) Installing isl22 (0.22-r0)
#7 2.757 (9/24) Installing mpfr4 (4.1.0-r0)
#7 2.813 (10/24) Installing mpc1 (1.2.1-r0)
#7 2.844 (11/24) Installing gcc (10.3.1_git20210424-r2)
#7 3.603 (12/24) Installing musl-dev (1.2.2-r3)
#7 3.705 (13/24) Installing libc-dev (0.7.2-r3)
#7 3.737 (14/24) Installing g++ (10.3.1_git20210424-r2)
#7 4.312 (15/24) Installing make (4.3-r0)
#7 4.345 (16/24) Installing fortify-headers (1.1-r1)
#7 4.374 (17/24) Installing patch (2.7.6-r7)
#7 4.406 (18/24) Installing build-base (0.5-r2)
#7 4.443 (19/24) Installing brotli-libs (1.0.9-r5)
#7 4.488 (20/24) Installing nghttp2-libs (1.43.0-r0)
#7 4.521 (21/24) Installing libcurl (7.79.1-r0)
#7 4.560 (22/24) Installing curl (7.79.1-r0)
#7 4.597 (23/24) Installing oniguruma (6.9.7.1-r0)
#7 4.639 (24/24) Installing jq (1.6-r1)
#7 4.682 Executing busybox-1.33.1-r6.trigger
#7 4.690 OK: 211 MiB in 60 packages
#7 5.492 Successfully installed bundler-2.2.33
#7 5.492 1 gem installed
#7 5.596 bundler (2.2.33, default: 2.2.22)
#7 DONE 6.0s

#8 [5/9] RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* &&     truncate -s 0 /var/log/*log
#8 sha256:378d3cbe0527f227bd2437b52838ee9e3d4342ee222f8a118fe691d6d255dd83
#8 DONE 1.1s

#10 [6/9] COPY Gemfile Gemfile.lock /app/
#10 sha256:4356d96bcf11e197e83c1b3a8a6ebc255b0e7f6d028fe11e02aabbac7922d2fd
#10 DONE 0.8s

#11 [7/9] RUN bundle install --path vendor/bundle
#11 sha256:f9c1e7b3b4d3c72e4eb4b4936c9e535c0b6a5c6d5ed2ddae58d206e5c5028875
#11 0.924 [DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local path 'vendor/bundle'`, and stop using this flag
#11 0.974 Warning: the running version of Bundler (2.2.33) is older than the version that created the lockfile (2.3.4). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.3.4`.
#11 1.503 Fetching gem metadata from https://rubygems.org/.
#11 1.518 Resolving dependencies...
#11 1.519 Fetching rake 13.0.6
#11 1.580 Installing rake 13.0.6
#11 1.644 Using bundler 2.2.33
#11 1.645 Bundle complete! 1 Gemfile dependency, 2 gems now installed.
#11 1.645 Bundled gems are installed into `./vendor/bundle`
#11 DONE 1.9s

#12 [8/9] COPY . /app
#12 sha256:881ae7133a8308114218b0c5e8987c3cd99c68d8d04ba3424bc7031f41e95708
#12 DONE 0.8s

#13 [9/9] RUN $GEM_PATH
#13 sha256:609155c77d5d5d6b53b58f9179e4c366dfdd9f74b23950032e4ae9db6400569b
#13 DONE 1.1s

#14 exporting to image
#14 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#14 exporting layers
#14 exporting layers 2.6s done
#14 writing image sha256:fe36ea72251635e2501f3ec1ae916551df2ca49b31a8a2524a3c9e3a97198690 0.0s done
#14 naming to docker.io/library/foo
#14 naming to docker.io/library/foo 0.0s done
#14 DONE 2.9s

$  docker run --rm -it foo sh                        
/app # ls /usr/local/bundle/gems/
bundler-2.2.33
/app # ls /app/vendor/bundle/ruby/3.0.0/gems/
rake-13.0.6
```

Rake has been installed to the proper place 🤷 . Also note "Bundled gems are installed into `./vendor/bundle`" in the output.

For the n-th time, please provide a way to reproduce this with concrete steps. I feel I'm trying to proof that some issue does not exist (which is impossible, since I'm not running into the issue), instead of letting you prove that it does exist.

I understand that what I'm asking for takes some effort. Providing an actual `Gemfile` takes more effort that saying "Any Gemfile will do", or providing an actual command that does not give the desired outcome takes more effort that saying "Observe it tries to install to /usr/local/bundle which then gives an error.". But it's the minimum requirement we ask for to be able to help you, and it sounds fair to me if you want your issue looked at.

I'l close this again, but I'm happy to reopen once proper information has been given. Thanks!

**Closed by deivid-rodriguez** 2022-01-17 11:14 UTC
Labels: status: feedback required, Bundler

**Comment by luke-hill** [comment] 2022-01-17 11:43
Using an interactive shell is bundle also installed into vendor/bundle? If it is then I guess it's my version of docker.

**Comment by deivid-rodriguez** [comment] 2022-01-17 12:00
> Using an interactive shell is bundler also installed into vendor/bundle? If it is then I guess it's my version of docker.

I think the version of docker and shell interactiveness are unrelated to this.

> Using your interactive shell it looks like bundler is installed in local? Which is wrong?

It is installed to `GEM_HOME`, which is set to `/usr/local/bundle` in the base image, and it's where RubyGems installs gems. So, totally expected since you are installing Bundler using `gem install`. `bundle config` is a Bundler command, so it doesn't affect `gem install`. It sounds like you might what to customize `GEM_HOME`, which both Bundler and RubyGems understand. Alternatively, you may also want to upgrade Bundler. Recent versions of Bundler automatically install a proper version of Bundler itself to the path configured with `bundle config`, and then restart using that Bundler version (by switching `GEM_HOME` to be the path configured via `bundle config`). So bundler 2.3.5 might do what you want by default.

**Comment by luke-hill** [comment] 2022-01-17 12:06
If this is only recently modified (The logic about the default install of where to put bundler), then something else is wrong with our docker/jenkins setup. As I've used this setup in previous companies (And just blindly assumed bundler was installed in vendor/).

I think this can be closed as "Something for my devops team to investigate"

**Comment by deivid-rodriguez** [comment] 2022-01-17 12:15
If there no write permissions to `/usr/local/bundle`, and the image has set `GEM_HOME` to `/usr/local/bundle`, and you try `gem install bundler`, that's expected to fail yeah.

@PhilippGoecke The original issue reported here is expected behavior, if you are still running into issues similar to this, please report a separate ticket!

**Comment by luke-hill** [comment] 2022-01-17 14:05
FYI I found out the issue for my problem is very specific.

Bundler has some issues when using Alpine 3.14 in terms of permissions **when** ran inside a Docker-in-Docker context on a CI platform.

For now downgrading to use alpine 3.13 works a charm

**Comment by PhilippGoecke** [comment] 2022-01-24 14:04
our solution was to specify `bundle config set --local path 'vendor'`. It worked fine with bundler <= 2.2.33 without and now bundler 2.3.5 it needs it to be set.

**Comment by luke-hill** [comment] 2022-01-24 14:07
that doesn't fix the issue. If you see the command I used then you'll see the issue was permissions not being respected when using a combination of ...

- alpine 3.14+
- docker in docker
- bundler

The solution I found (Given we couldn't mitigate item2/3), is to mitigate item1 by downgrading the alpine version

**Comment by deivid-rodriguez** [comment] 2022-01-24 15:21
@PhilippGoecke I think maybe you were running into something similar to https://github.com/rubygems/rubygems/issues/5297? Any change in behavior between bundler 2.2 and bundler 2.3 in this regard is not intentional and might be some regression.

**Comment by PhilippGoecke** [comment] 2022-01-24 15:23
Yes, thanks alot!
