### ISSUE TITLE
Errno::EACCES: Permission denied @ rb_sysopen

### ISSUE THREAD

**Issue by tanuchoudhary21** [rubygems/rubygems#4725] opened 2021-07-06 12:41 UTC
I am working on Ruby-on-Rails project. I updated my Gemfile with the following commands:
gem 'sqlite3', '~> 1.4', :group => [:development, :test]
gem 'pg', :group => [:production]

And when i run bundle install it gave me error. To resolve those errors i run 2 more commands:
1. sudo PATH=$PATH:/Library/PostgreSQL/x.y/bin gem install pg
2. sudo PATH=$PATH:/Library/PostgreSQL/x.y/bin bundle install

But now when i try to run bundle install it gives me these errors and i am unable to resolve them.

Errno::EACCES: Permission denied @ rb_sysopen - /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pg-1.2.3/.gemtest
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:424:in `initialize'
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:424:in `open'
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:424:in `block (2 levels) in extract_tar_gz'
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/package/tar_reader.rb:65:in `each'
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:405:in `block in extract_tar_gz'
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:534:in `block in open_tar_gz'
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:531:in `wrap'
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:531:in `open_tar_gz'
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:404:in `extract_tar_gz'
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:384:in `block (2 levels) in extract_files'
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/package/tar_reader.rb:65:in `each'
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:381:in `block in extract_files'
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/package/file_source.rb:29:in `open'
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/package/file_source.rb:29:in `with_read_io'
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/package.rb:378:in `extract_files'
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/installer.rb:837:in `extract_files'
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/rubygems_gem_installer.rb:24:in `install'
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/source/rubygems.rb:182:in `install'
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/installer/gem_installer.rb:67:in `install'
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/installer/gem_installer.rb:18:in `install_from_spec'
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/worker.rb:62:in `apply_func'
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/worker.rb:57:in `block in process_queue'
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/worker.rb:54:in `loop'
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/worker.rb:54:in `process_queue'
  /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/bundler/worker.rb:88:in `block (2 levels) in create_threads'
```

## Environment

```
Bundler       2.2.21
  Platforms   ruby, x86_64-darwin-20
Ruby          3.0.1p64 (2021-04-05 revision 0fb782ee38ea37fd5fe8b1f775f8ad866a82a3f0) [x86_64-darwin20]
  Full Path   /Users/tanuchoudhary/.rbenv/versions/3.0.1/bin/ruby
  Config Dir  /Users/tanuchoudhary/.rbenv/versions/3.0.1/etc
RubyGems      3.2.21
  Gem Home    /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0
  Gem Path    /Users/tanuchoudhary/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0:/Users/tanuchoudhary/.gem/ruby/3.0.0
  User Home   /Users/tanuchoudhary
  User Path   /Users/tanuchoudhary/.gem/ruby/3.0.0
  Bin Dir     /Users/tanuchoudhary/.rbenv/versions/3.0.1/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1k  25 Mar 2021
  Loaded      OpenSSL 1.1.1k  25 Mar 2021
  Cert File   /Users/tanuchoudhary/.rbenv/versions/3.0.1/openssl/ssl/cert.pem
  Cert Dir    /Users/tanuchoudhary/.rbenv/versions/3.0.1/openssl/ssl/certs
Tools         
  Git         2.30.1 (Apple Git-130)
  RVM         not installed
  rbenv       rbenv 1.1.2
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-06-23
Git SHA           0b5db72094
Released Version  true
```

## Gemfile

### Gemfile

```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.4'
# Use sqlite3 as the database for Active Record
# gem 'sqlite3', '~> 1.4'
gem 'sqlite3', '~> 1.4', :group => [:development, :test]
gem 'pg', :group => [:production]
# Use Puma as the app server
gem 'puma', '~> 5.0'
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 5.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'react-rails'
gem 'bcrypt', '~> 3.1.13'
gem "pundit"
# gem 'wdm', '>= 0.1.0'
gem 'rexml', '~> 3.2', '>= 3.2.5'
gem 'bundler-audit',require: false
gem 'ruby_audit', require: false
gem "sidekiq"
# For periodic sidekiq jobs
gem "sidekiq-cron"
# For opening mails in development env
gem "letter_opener", :group => :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 4.1.0'
  # Display performance information such as SQL time and flame graphs for each request in your browser.
  # Can be configured to work on production as well see: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/README.md
  gem 'rack-mini-profiler', '~> 2.0'
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (6.1.4)
      actionpack (= 6.1.4)
      activesupport (= 6.1.4)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (6.1.4)
      actionpack (= 6.1.4)
      activejob (= 6.1.4)
      activerecord (= 6.1.4)
      activestorage (= 6.1.4)
      activesupport (= 6.1.4)
      mail (>= 2.7.1)
    actionmailer (6.1.4)
      actionpack (= 6.1.4)
      actionview (= 6.1.4)
      activejob (= 6.1.4)
      activesupport (= 6.1.4)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (6.1.4)
      actionview (= 6.1.4)
      activesupport (= 6.1.4)
      rack (~> 2.0, >= 2.0.9)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (6.1.4)
      actionpack (= 6.1.4)
      activerecord (= 6.1.4)
      activestorage (= 6.1.4)
      activesupport (= 6.1.4)
      nokogiri (>= 1.8.5)
    actionview (6.1.4)
      activesupport (= 6.1.4)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (6.1.4)
      activesupport (= 6.1.4)
      globalid (>= 0.3.6)
    activemodel (6.1.4)
      activesupport (= 6.1.4)
    activerecord (6.1.4)
      activemodel (= 6.1.4)
      activesupport (= 6.1.4)
    activestorage (6.1.4)
      actionpack (= 6.1.4)
      activejob (= 6.1.4)
      activerecord (= 6.1.4)
      activesupport (= 6.1.4)
      marcel (~> 1.0.0)
      mini_mime (>= 1.1.0)
    activesupport (6.1.4)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
      zeitwerk (~> 2.3)
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    babel-source (5.8.35)
    babel-transpiler (0.7.0)
      babel-source (>= 4.0, < 6)
      execjs (~> 2.0)
    bcrypt (3.1.16)
    bindex (0.8.1)
    bootsnap (1.7.5)
      msgpack (~> 1.0)
    builder (3.2.4)
    bundler-audit (0.8.0)
      bundler (>= 1.2.0, < 3)
      thor (~> 1.0)
    byebug (11.1.3)
    capybara (3.35.3)
      addressable
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    childprocess (3.0.0)
    concurrent-ruby (1.1.9)
    connection_pool (2.2.5)
    crass (1.0.6)
    erubi (1.10.0)
    et-orbi (1.2.4)
      tzinfo
    execjs (2.8.1)
    ffi (1.15.3)
    ffi (1.15.3-x64-mingw32)
    fugit (1.5.0)
      et-orbi (~> 1.1, >= 1.1.8)
      raabro (~> 1.4)
    globalid (0.4.2)
      activesupport (>= 4.2.0)
    i18n (1.8.10)
      concurrent-ruby (~> 1.0)
    jbuilder (2.11.2)
      activesupport (>= 5.0.0)
    launchy (2.5.0)
      addressable (~> 2.7)
    letter_opener (1.7.0)
      launchy (~> 2.2)
    listen (3.5.1)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    loofah (2.10.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (1.0.1)
    method_source (1.0.0)
    mini_mime (1.1.0)
    minitest (5.14.4)
    msgpack (1.4.2)
    nio4r (2.5.7)
    nokogiri (1.11.7-x64-mingw32)
      racc (~> 1.4)
    nokogiri (1.11.7-x86_64-darwin)
      racc (~> 1.4)
    public_suffix (4.0.6)
    puma (5.3.2)
      nio4r (~> 2.0)
    pundit (2.1.0)
      activesupport (>= 3.0.0)
    raabro (1.4.0)
    racc (1.5.2)
    rack (2.2.3)
    rack-mini-profiler (2.3.2)
      rack (>= 1.2.0)
    rack-proxy (0.7.0)
      rack
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (6.1.4)
      actioncable (= 6.1.4)
      actionmailbox (= 6.1.4)
      actionmailer (= 6.1.4)
      actionpack (= 6.1.4)
      actiontext (= 6.1.4)
      actionview (= 6.1.4)
      activejob (= 6.1.4)
      activemodel (= 6.1.4)
      activerecord (= 6.1.4)
      activestorage (= 6.1.4)
      activesupport (= 6.1.4)
      bundler (>= 1.15.0)
      railties (= 6.1.4)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.3.0)
      loofah (~> 2.3)
    railties (6.1.4)
      actionpack (= 6.1.4)
      activesupport (= 6.1.4)
      method_source
      rake (>= 0.13)
      thor (~> 1.0)
    rake (13.0.3)
    rb-fsevent (0.11.0)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    react-rails (2.6.1)
      babel-transpiler (>= 0.7.0)
      connection_pool
      execjs
      railties (>= 3.2)
      tilt
    redis (4.3.1)
    regexp_parser (2.1.1)
    rexml (3.2.5)
    ruby_audit (2.0.0)
      bundler-audit (~> 0.8.0)
    rubyzip (2.3.0)
    sass-rails (6.0.0)
      sassc-rails (~> 2.1, >= 2.1.1)
    sassc (2.4.0)
      ffi (~> 1.9)
    sassc (2.4.0-x64-mingw32)
      ffi (~> 1.9)
    sassc-rails (2.1.2)
      railties (>= 4.0.0)
      sassc (>= 2.0)
      sprockets (> 3.0)
      sprockets-rails
      tilt
    selenium-webdriver (3.142.7)
      childprocess (>= 0.5, < 4.0)
      rubyzip (>= 1.2.2)
    semantic_range (3.0.0)
    sidekiq (6.2.1)
      connection_pool (>= 2.2.2)
      rack (~> 2.0)
      redis (>= 4.2.0)
    sidekiq-cron (1.2.0)
      fugit (~> 1.1)
      sidekiq (>= 4.2.1)
    spring (2.1.1)
    sprockets (4.0.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.2)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sqlite3 (1.4.2)
    thor (1.1.0)
    tilt (2.0.10)
    tzinfo (2.0.4)
      concurrent-ruby (~> 1.0)
    tzinfo-data (1.2021.1)
      tzinfo (>= 1.0.0)
    web-console (4.1.0)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    webdrivers (4.6.0)
      nokogiri (~> 1.6)
      rubyzip (>= 1.3.0)
      selenium-webdriver (>= 3.0, < 4.0)
    webpacker (5.4.0)
      activesupport (>= 5.2)
      rack-proxy (>= 0.6.1)
      railties (>= 5.2)
      semantic_range (>= 2.3.0)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    zeitwerk (2.4.2)

PLATFORMS
  x64-mingw32
  x86_64-darwin-20

DEPENDENCIES
  bcrypt (~> 3.1.13)
  bootsnap (>= 1.4.4)
  bundler-audit
  byebug
  capybara (>= 3.26)
  jbuilder (~> 2.7)
  letter_opener
  listen (~> 3.3)
  puma (~> 5.0)
  pundit
  rack-mini-profiler (~> 2.0)
  rails (~> 6.1.4)
  react-rails
  rexml (~> 3.2, >= 3.2.5)
  ruby_audit
  sass-rails (>= 6)
  selenium-webdriver
  sidekiq
  sidekiq-cron
  spring
  sqlite3 (~> 1.4)
  tzinfo-data
  web-console (>= 4.1.0)
  webdrivers
  webpacker (~> 5.0)

RUBY VERSION
   ruby 3.0.1p64

BUNDLED WITH
   2.2.21
```
Unfortunately, an unexpected error occurred, and Bundler cannot continue.
Please help me to resolve this particular error.

**Comment by deivid-rodriguez** [comment] 2021-07-06 13:08
Closing as a duplicate of https://github.com/rubygems/rubygems/issues/4725. Please subscribe to the other ticket for updates :+1:.

**Closed by deivid-rodriguez** 2021-07-06 13:08 UTC
Labels: Bundler
