### ISSUE TITLE
gem install -g: unexpected token: submodules

### ISSUE THREAD

**Issue by sevos** [rubygems/rubygems#1231] opened 2015-04-21 11:19 UTC
```
$ gem install -g
/home/vagrant/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/request_set/lockfile/parser.rb:64:in `get': unexpected token [:entry, "submodules"], expected [:entry, "specs"] (at line 70 column 2)
```

```
gem 'datetimepicker-rails', github: 'zpaulovics/datetimepicker-rails', branch: 'master', submodules: true
```

**Comment by bronzdoc** [comment] 2016-02-13 03:15
Couldn't reproduce this with the current version of rubygems, closing

**Closed by bronzdoc** 2016-02-13 03:15 UTC
Labels: triage

**Comment by evserykh** [comment] 2016-08-13 11:52
- Rbenv
- Ruby 2.3.1
- rubygems 2.5.1
- RUBYGEMS_GEMDEPS=-

I have the same issue when I try to execute in a Rails app: `rake -T`

With unseted RUBYGEMS_GEMDEPS and installed [rubygems-bundler](https://github.com/rvm/rubygems-bundler) all works fine
