### ISSUE TITLE
"gem install compass" issue on Windows 7

### ISSUE THREAD

**Issue by akhilesh25** [rubygems/rubygems#1370] opened 2015-11-04 21:50 UTC
Could anyone please help me to resolve the below issue?
---------
$ gem install compass
Building native extensions.  This could take a while...
ERROR:  Error installing compass:
        ERROR: Failed to build gem native extension.

    current directory: /home/akhilesh.verma/.gem/ruby/gems/ffi-1.9.10/ext/ffi_c
/usr/bin/ruby.exe -r ./siteconf20151104-9304-m0mphj.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)
        --with-ffi_c-dir
        --without-ffi_c-dir
        --with-ffi_c-include
        --without-ffi_c-include=${ffi_c-dir}/include
        --with-ffi_c-lib
        --without-ffi_c-lib=${ffi_c-dir}/lib
        --with-libffi-config
        --without-libffi-config
        --with-pkg-config
        --without-pkg-config
/usr/share/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate a    n executable file. (RuntimeError)
You have to install development tools first.
        from /usr/share/ruby/2.2.0/mkmf.rb:541:in `try_link0'
        from /usr/share/ruby/2.2.0/mkmf.rb:556:in `try_link'
        from /usr/share/ruby/2.2.0/mkmf.rb:637:in `try_ldflags'
        from /usr/share/ruby/2.2.0/mkmf.rb:1780:in `pkg_config'
        from extconf.rb:15:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can     be found here:

  /home/akhilesh.verma/.gem/ruby/extensions/x86_64-cygwin/ffi-1.9.10/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/akhilesh.verma/.gem/ruby/gems/ffi-1.9.1    0 for inspection.
Results logged to /home/akhilesh.verma/.gem/ruby/extensions/x86_64-cygwin/ffi-1.    9.10/gem_make.out
--------

**Comment by tenderlove** [comment] 2015-11-04 21:54
What version of RubyGems are you using?

**Comment by akhilesh25** [comment] 2015-11-04 21:56
[cid:image001.png@01D11753.E64BD970]

Thanks and Best Regards/
Mit freundlichen Grüßen

Akhilesh Verma

[cid:image003.png@01CFCC33.6ADA3F00]

**Comment by akhilesh25** [comment] 2015-11-04 21:57
akhilesh.verma@NotebookNL ~
$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-cygwin]

akhilesh.verma@NotebookNL ~
$ rails -v
Rails 4.2.4
akhilesh.verma@NotebookNL ~
$ gem -v
2.5.0
akhilesh.verma@NotebookNL ~
$ sass -v
Sass 3.4.14 (Selective Steve)

**Comment by tenderlove** [comment] 2015-11-04 22:01
Thanks @akhilesh25 I think this is a duplicate of #1369.  Can you try downgrading to 2.4.8?

**Comment by akhilesh25** [comment] 2015-11-04 22:10
Hi tenderlove

Could you please specify how to downgrade gem 2.5.0 to 2.4.8?

**Comment by akhilesh25** [comment] 2015-11-04 22:19
Hi Tenderlove

I tried to downgrade 2.4.8 but didn't work still same issue-

akhilesh.verma@NotebookNL ~
$ gem -v
2.4.8

akhilesh.verma@NotebookNL ~
$ gem install compass
Building native extensions.  This could take a while...
ERROR:  Error installing compass:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby.exe -r ./siteconf20151104-9912-1giz498.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)
        --with-ffi_c-dir
        --without-ffi_c-dir
        --with-ffi_c-include
        --without-ffi_c-include=${ffi_c-dir}/include
        --with-ffi_c-lib
        --without-ffi_c-lib=${ffi_c-dir}/lib
        --with-libffi-config
        --without-libffi-config
        --with-pkg-config
        --without-pkg-config
/usr/share/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an ex                                      ecutable file. (RuntimeError)
You have to install development tools first.
        from /usr/share/ruby/2.2.0/mkmf.rb:541:in `try_link0'
        from /usr/share/ruby/2.2.0/mkmf.rb:556:in `try_link'
        from /usr/share/ruby/2.2.0/mkmf.rb:637:in `try_ldflags'
        from /usr/share/ruby/2.2.0/mkmf.rb:1780:in `pkg_config'
        from extconf.rb:15:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /home/akhilesh.verma/.gem/ruby/gems/ffi-1.9.10 fo                                      r inspection.
Results logged to /home/akhilesh.verma/.gem/ruby/extensions/x86_64-cygwin/ffi-1.9.10                                      /gem_make.out

**Comment by djberg96** [comment] 2015-11-05 02:21
```
PS C:\Users\Daniel> gem -v
2.5.0
PS C:\Users\Daniel> ruby -v
ruby 2.1.6p336 (2015-04-13 revision 50298) [x64-mingw32]
PS C:\Users\Daniel> gem install compass --no-document
Fetching: compass-1.0.3.gem (100%)
    Compass is charityware. If you love it, please donate on our behalf at http://umdf.org/compass Thanks!
Successfully installed compass-1.0.3
1 gem installed
```

**Comment by akhilesh25** [comment] 2015-11-05 10:02
Hi djberg

I tried again - first I upgraded my gem from 2.4.8 to 2.5.0 then run the below command but still same issue--

akhilesh.verma@NotebookNL ~
$ gem -v
2.5.0

akhilesh.verma@NotebookNL ~
$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-cygwin]

akhilesh.verma@NotebookNL ~
$ gem install compass --no-document
Building native extensions.  This could take a while...
ERROR:  Error installing compass:
        ERROR: Failed to build gem native extension.

    current directory: /home/akhilesh.verma/.gem/ruby/gems/ffi-1.9.10/ext/ffi_c
/usr/bin/ruby.exe -r ./siteconf20151105-6084-1mxparr.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)
        --with-ffi_c-dir
        --without-ffi_c-dir
        --with-ffi_c-include
        --without-ffi_c-include=${ffi_c-dir}/include
        --with-ffi_c-lib
        --without-ffi_c-lib=${ffi_c-dir}/lib
        --with-libffi-config
        --without-libffi-config
        --with-pkg-config
        --without-pkg-config
/usr/share/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/share/ruby/2.2.0/mkmf.rb:541:in `try_link0'
        from /usr/share/ruby/2.2.0/mkmf.rb:556:in `try_link'
        from /usr/share/ruby/2.2.0/mkmf.rb:637:in `try_ldflags'
        from /usr/share/ruby/2.2.0/mkmf.rb:1780:in `pkg_config'
        from extconf.rb:15:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/akhilesh.verma/.gem/ruby/extensions/x86_64-cygwin/ffi-1.9.10/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/akhilesh.verma/.gem/ruby/gems/ffi-1.9.10 for inspection.
Results logged to /home/akhilesh.verma/.gem/ruby/extensions/x86_64-cygwin/ffi-1.9.10/gem_make.out

**Comment by akhilesh25** [comment] 2015-11-05 15:37
Anybody have any idea how to resolve the above issue?

Thanks in advance!!

**Comment by djberg96** [comment] 2015-11-05 15:41
@akhilesh25 Does this fix work?

https://github.com/rubygems/rubygems/issues/1369#issuecomment-153958921

**Comment by akhilesh25** [comment] 2015-11-05 15:45
Hi djberg

No I am still fighting to install compass using Cygwin

**Comment by ryanatball** [comment] 2015-11-05 16:58
mkmf is saying that it can't compile even a very simple c file:

```
/usr/share/ruby/2.2.0/mkmf.rb:456:in try_do': The compiler failed to generate a n executable file. (RuntimeError) You have to install development tools first. from 
```

Does your cygwin installation have gcc installed.  Can you compile something simple like:

```
int main (void) {
  return 0;
}
```

**Comment by akhilesh25** [comment] 2015-11-05 20:31
Hello ryanatball
Thanks for your reply - 

But still no success - see the below complete steps

akhilesh.verma@NotebookNL /cygdrive/c/Akhilesh
$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-cygwin]

akhilesh.verma@NotebookNL /cygdrive/c/Akhilesh
$ rails -v
Rails 4.2.4

akhilesh.verma@NotebookNL /cygdrive/c/Akhilesh
$ sass -v
Sass 3.4.14 (Selective Steve)

akhilesh.verma@NotebookNL /cygdrive/c/Akhilesh
$ gem -v
2.4.8

akhilesh.verma@NotebookNL /cygdrive/c/Akhilesh
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-cygwin/4.9.3/lto-wrapper.exe
Target: x86_64-pc-cygwin
Configured with: /cygdrive/i/szsz/tmpp/gcc/gcc-4.9.3-1.x86_64/src/gcc-4.9.3/configure --ssrc/gcc-4.9.3 --prefix=/usr --exec-prefix=/usr --localstatedir=/var --sysconfdir=/etc --dcc/html -C --build=x86_64-pc-cygwin --host=x86_64-pc-cygwin --target=x86_64-pc-cygwin --wibexecdir=/usr/lib --enable-shared --enable-shared-libgcc --enable-static --enable-versio-__cxa_atexit --with-dwarf2 --with-tune=generic --enable-languages=ada,c,c++,fortran,lto,ix --enable-libatomic --enable-libgomp --disable-libitm --enable-libquadmath --enable-libenable-libgcj-sublibs --disable-java-awt --disable-symvers --with-ecj-jar=/usr/share/javanclude=/usr/include/cloog-isl --without-libiconv-prefix --without-libintl-prefix --with-s
Thread model: posix
gcc version 4.9.3 (GCC)

akhilesh.verma@NotebookNL /cygdrive/c/Akhilesh
$ gcc hello2.c

akhilesh.verma@NotebookNL /cygdrive/c/Akhilesh
$ ./a.exe
Hello World

akhilesh.verma@NotebookNL /cygdrive/c/Akhilesh
$ gem install compass
Building native extensions.  This could take a while...
ERROR:  Error installing compass:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby.exe -r ./siteconf20151105-11672-1fz80uh.rb extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)
        --with-ffi_c-dir
        --without-ffi_c-dir
        --with-ffi_c-include
        --without-ffi_c-include=${ffi_c-dir}/include
        --with-ffi_c-lib
        --without-ffi_c-lib=${ffi_c-dir}/lib
        --with-libffi-config
        --without-libffi-config
        --with-pkg-config
        --without-pkg-config
/usr/share/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/share/ruby/2.2.0/mkmf.rb:587:in `try_cpp'
        from /usr/share/ruby/2.2.0/mkmf.rb:1060:in `block in have_header'
        from /usr/share/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
        from /usr/share/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from /usr/share/ruby/2.2.0/mkmf.rb:321:in `open'
        from /usr/share/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
        from /usr/share/ruby/2.2.0/mkmf.rb:321:in `open'
        from /usr/share/ruby/2.2.0/mkmf.rb:347:in `postpone'
        from /usr/share/ruby/2.2.0/mkmf.rb:910:in `checking_for'
        from /usr/share/ruby/2.2.0/mkmf.rb:1059:in `have_header'
        from extconf.rb:16:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /home/akhilesh.verma/.gem/ruby/gems/ffi-1.9.10 for inspection.
Results logged to /home/akhilesh.verma/.gem/ruby/extensions/x86_64-cygwin/ffi-1.9.10/gem_make.out

**Comment by akhilesh25** [comment] 2015-11-05 21:53
Hi All,

Now I got success after hunting many things -

The solution for this error was (and is for all such errors) to have a look at the mkmf.log file (for me, C:\cygwin64\home\akhilesh.verma\.gem\ruby\extensions\x86_64-cygwin\ffi-1.9.10\mkmf.log) and see which libraries are missing.

In my case, -lcrypt were failing, so I had to "cygwin-setup" and install libcrypt-devel package.

After install this I got different error - checked in again mkmf.log
"package configuration for libffi is not found"
Then I had to "cygwin-setup" and install libffi package.
After successfully install and tried to install compass and that's installed successfully with missing some file and directory not found issue..

Then I upgraded my gem 2.4.8 to 2.5.0 and tried again to install compass.
Now this time successfully installed without any error.

But when I run the below comand got command not found -
$ compass -v
"bash:compass command not found"

Then I set Environment variable PATH= where compass installed - In my case   
C:\cygwin64\home\akhilesh.verma\bin

Then I run again and got the version without any error

akhilesh.verma@NotebookNL ~
$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-cygwin]

akhilesh.verma@NotebookNL ~
$ rails -v
Rails 4.2.4

akhilesh.verma@NotebookNL ~
$ sass -v
Sass 3.4.14 (Selective Steve)

akhilesh.verma@NotebookNL ~
$ gem -v
2.5.0

akhilesh.verma@NotebookNL ~
$ compass -v
Compass 1.0.3 (Polaris)
Copyright (c) 2008-2015 Chris Eppstein
Released under the MIT License.
Compass is charityware.
Please make a tax deductable donation for a worthy cause: http://umdf.org/compass

Many thanks - tenderlove , djberg96 and ryanatball for your support :+1:

**Comment by duckinator** [comment] 2016-01-16 14:42
Closing because @akhilesh25 said this has been resolved.

**Closed** 2016-01-16 14:42 UTC
Labels: category - install, triage, windows
