### ISSUE TITLE
Unable to download data from https://rubygems.org

### ISSUE THREAD

**Issue by priyomukul** [rubygems/rubygems#2364] opened 2018-07-22 09:13 UTC
`sudo gem install compass`

ERROR:  Could not find a valid gem 'compass' (>= 0), here is why:

Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version (https://rubygems.org/latest_specs.4.8.gz)

here some info to help you!
`ruby -ropenssl -e 'p OpenSSL::OPENSSL_VERSION'`
"OpenSSL 0.9.8zc 19 Mar 2015"

**Comment by colby-swandale** [comment] 2018-07-22 10:03
Duplicate of #2340 #2342 and many others. Please see the SSL troubleshooting guide at https://bundler.io/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html

**Closed by colby-swandale** 2018-07-22 10:03 UTC
Labels: status: triage
