### ISSUE TITLE
Specifying both a version and Git-related attributes when a .gemspec exists

### ISSUE THREAD

**Issue by fxn** [rubygems/rubygems#7718] opened 2024-06-06 10:53 UTC
The documentation about [Bundler and Git](https://bundler.io/guides/git.html) says this:

> If there is no .gemspec at the root of a git repository, you must specify a version that bundler should use when resolving dependencies

Is setting an explicit version when a .gemspec exists supported? Example:

```ruby
gem 'rails', '7.1.3.4', github: 'rails', branch: '7-1-stable'
```

If you do not set the version, `Gemfile.lock` has the SHA1 **and also** explicit versions for the gems, eg:

```
GIT
  remote: https://github.com/rails/rails.git
  revision: eedbe69470962e2ac1fb91913b8104a0c873d17a
  branch: 7-1-stable
  specs:
    actioncable (7.1.3.4)
      actionpack (= 7.1.3.4)
      activesupport (= 7.1.3.4)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
      zeitwerk (~> 2.6)
    ...
```

If you remove the version, those disappear, and the gems like `actionpack` appear as dependencies of other gems with the expected version (extracted from their .gemspec). Also, if both things are set you get

```
rails (= 7.1.3.4)!
```

instead of just

```
rails!
```

If this is supported, should the description be something in line of: "If the repository has a .gemspec, Bundler ensures the versions match"? I could volunteer a documentation patch if you confirm.

**Comment by deivid-rodriguez** [comment] 2024-06-13 18:42
I honestly have no idea, but also I'm not fully clear on the lockfile differences. Can you post a diff between the two lockfiles, so it's more clear? Also, is there any functional difference between the two cases, like bundler failing to resolve or something?

**Comment by deivid-rodriguez** [comment] 2024-08-05 17:29
I'll close this since there was no further feedback, but please do reopen if still interested in improving this!

**Comment by technicalpickles** [comment] 2024-08-26 17:45
I was able to make a reproduction for the error we were seeing when using version + git branch.

1. Start with this Gemfile:

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

gem 'rails', '7.1.4', github: 'rails', branch: '7-1-stable'
```

2. Run `bundle install`
3.  Remove version `7.1.4` the Gemfile:

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

gem 'rails', github: 'rails', branch: '7-1-stable'
```

4. Run `bundle install` again
5. See error:

```
$ bundle install
Fetching https://github.com/rails/rails.git
Resolving dependencies...
Fetching gem metadata from https://rubygems.org/........
Your bundle is locked to actionpack (7.1.4) from rubygems repository https://rubygems.org/ or installed locally, but that version can no longer be found in that source. That means the author of actionpack (7.1.4) has removed it. You'll need to update
your bundle to a version other than actionpack (7.1.4) that hasn't been removed in order to install.
```

Separately, I tried removing the `Gemfile.lock` after changing to see the difference with vs without (`diff -u Gemfile.lock-with-version Gemfile.lock-without-version`)

```diff
--- Gemfile.lock-with-version	2024-08-26 13:31:58
+++ Gemfile.lock-without-version	2024-08-26 13:32:27
@@ -197,7 +197,7 @@
   x86_64-linux

 DEPENDENCIES
-  rails (= 7.1.4)!
+  rails!

 BUNDLED WITH
    2.5.17
```

I tracked down the code that raised this to: https://github.com/rubygems/rubygems/blob/3e94d6c6c54e3df7191ac1457b0689e6542e3659/bundler/lib/bundler/definition.rb#L585-L597

I poked around it with `binding.irb`, and confirmed that the `Bundler::Definition` is for `rails`, and that `missing_specs` is all its dependencies (ie actionpack and friends).

Interestingly, the locked spec for `actionpack`, based on the error message, is coming from rubygems.org rather than the git source 🤔 

Out of curiousity, I checked how `rails new --edge` sets up its git remote, and it does uses `gem 'rails', github: 'rails', branch: '7-1-stable'`

**Comment by fxn** [comment] 2024-08-27 12:20
Let me remind the origin of the PR.

The situation in which there is a `.gemspec` AND a version in `Gemfile`, as in:

```ruby
gem 'rails', '7.1.3.4', github: 'rails', branch: '7-1-stable'
```

it is NOT documented. So, the first thing we'd need to clarify is if it is supported. If it is not, maybe we are just experiencing the random side-effects of logic that was not written with this combination in mind. @deivid-rodriguez do you know?

**Comment by fxn** [comment] 2024-08-27 13:39
My point is the following:

1. If this combination is not supported, then what happens when you set both things does not really matter on does not need to be investigated. At most, bundler could raise saying two version specifications were been provided, and document this is not supported.
2. If the combination is supposed to be supported, then we'd need to understand what it should do first. For example, perhaps it should verify that both version specifiers are compatible or raise. If the are compatible, pick the one in the `.gemspec` and proceed as if that was the only one that existed. Once the expected behavior understood, then we can investigate if the current implementation agrees.

**Comment by fxn** [comment] 2024-08-27 13:55
The case is a bug _provided_ the feature is meant to be supported :).

**Comment by deivid-rodriguez** [comment] 2024-08-27 13:57
Well, I consider given such bad errors when people do "not that strange" things is also a bug.

By the way, I just noticed that 7-1-stable is no longer at 7.1.3.4, so the versions don't match anymore, actually.

**Comment by fxn** [comment] 2024-08-27 13:58
@deivid-rodriguez how does Bundler know that the `activerecord` dependency expressed in `rails.gemspec` is to be found in the repo that was checked out? Does it scan recursively for .gemspecs or something? I don't seem to find that documented either.

**Comment by deivid-rodriguez** [comment] 2024-08-27 14:02
Yes, I think that's what it does, but I'm not sure it's documented. I went to https://bundler.io/v2.5/man/gemfile.5.html to check and did not find it, but I actually found that we do document passing a version to `git` sources, regardless of gemspec existence. We're actually supposed to print a warning if versions don't match:

> If a git repository does have a .gemspec for the gem you attached it to, a version specifier, if provided, means that the git repository is only valid if the .gemspec specifies a version matching the version specifier. If not, bundler will print a warning.

Although I don't recall seeing any warnings like that, and I'm not seeing them in this case either.

**Comment by fxn** [comment] 2024-08-27 14:12
Isn't that documenting the `gemspec` method that you have available in `Gemfile`.

What I have in mind is different (I think, maybe it is related behind the scenes). Let me explain. This line

```ruby
gem 'rails', github: 'rails', branch: '7-1-stable'
```

we know makes Bundler clone the Rails repository and process its [.gemspec in the root directory](https://github.com/rails/rails/blob/7-1-stable/rails.gemspec). The .gemspec has this:

```ruby
s.add_dependency "activesupport", version
s.add_dependency "actionpack",    version
s.add_dependency "actionview",    version
...
s.add_dependency "bundler", ">= 1.15.0"
```

So, what is making Bundler understand those runtime dependencies are located in the same repo, except for `bundler`?

The `:glob` option or `gemspec` calls are not involved, yet those dependencies are located correctly:

```
% bundle show rails
/Users/xavier.noria/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/bundler/gems/rails-83c96069e50b
del_edge [main] % bundle show activerecord
/Users/xavier.noria/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/bundler/gems/rails-83c96069e50b/activerecord
```

**Comment by deivid-rodriguez** [comment] 2024-08-27 14:18
> Isn't that documenting the gemspec method that you have available in Gemfile?

Yes, I had edited my message to clarify that that's for `gemspec` but that I think `git` sources work in the same way.

**Comment by fxn** [comment] 2024-08-27 14:42
And that is consistent with

> For implicit gems (dependencies of explicit gems), any source, git, or path repository declared on the parent. This results in bundler prioritizing the ActiveSupport gem from the Rails git repository over ones from rubygems.org

Yeah, we need to say that other `.gemspecs` are processed (and you cannot pass `:name` for the other ones). I'll volunteer a doc patch if I can read the source code to verify what I am saying.

**Comment by deivid-rodriguez** [comment] 2024-08-30 10:34
Closed unintentionally by #7973, I'll keep this opened to tracked the documentation update.

**Comment by deivid-rodriguez** [comment] 2024-09-17 11:42
@fxn Are you still planning on sending us that documentation update?

**Comment by fxn** [comment] 2024-09-17 11:50
@deivid-rodriguez would love to, but EuRuKo and Rails World are eating my time.

If you will, you could close to reduce open tickets. If I get a patch I can open PR and link to this one for history.

**Comment by deivid-rodriguez** [comment] 2024-09-17 12:54
That sounds good, thank you @fxn!

**Closed by deivid-rodriguez** 2024-09-17 12:54 UTC
Labels: status: feedback required, Bundler
