### ISSUE TITLE
`pre` is inserted in the middle of my version string instead of appended

### ISSUE THREAD

**Issue by graywolf** [rubygems/rubygems#2163] opened 2018-01-31 13:50 UTC
I'm having a problem.

My current problem is that when doing `gem build` with version string being `0.0.1-reserve-name`, the resulting version is `0.0.1.reserve.pre.name`, which is not what I would expect. `0.0.1.reserve.name.pre` is probably the correct one here.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.7.3
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by graywolf** [comment] 2018-01-31 13:57
For that matter, why is the `pre` even added? I'm having trouble finding documentation specifying when it is added and how to supress it.

**Comment by shevegen** [comment] 2018-02-01 14:19
I agree to:

a) it should be documented

and

b) it should not make a modification that is at odds with what you (in this example) anticipate

I think the current problem may be that gem assumes that every user (at the least every gem author) wants to have/use this functionality and that no workaround should be applicable.

My first suggestion to resolve this is to not insert/tamper with any 'pre' names; I assume this is mostly "out of convention". If this is not possible then there should instead be a documented commandline flag that allows a user to specify the user string freely. IF the gem policy is to already allow non-numbers, then users should be free to format that in any way they see fit (assuming that at the least one number is part of the input).

At the end of the day it comes down to the policy that rubygems wants to enforce - but in all cases, I think it should be properly documented somewhere.

I would recommend this to be added to the section http://guides.rubygems.org/ by the way, in particular at http://guides.rubygems.org/name-your-gem/ -  since it currently does not state anything about the version string at the latter URL

PS: I myself only use numbers actually, never substrings such as "pre".

**Comment by segiddins** [comment] 2018-02-03 22:54
In the initializer for `Gem::Version`: `@version = version.to_s.strip.gsub("-",".pre.")`

**Comment by colby-swandale** [comment] 2018-02-28 07:52
This looks like it has been answered. Closing.

**Closed by colby-swandale** 2018-02-28 07:52 UTC
Labels: status: triage

**Comment by graywolf** [comment] 2018-03-01 23:23
So there is no way to supress the ".pre."?

**Comment by segiddins** [comment] 2018-03-02 07:58
> So there is no way to supress the ".pre."?

The only way is to not use `-` in your version

**Comment by graywolf** [comment] 2018-03-03 00:33
Would PR adding switch to disable this be accepted?

**Comment by segiddins** [comment] 2018-03-03 03:35
No, because it would be a completely backwards incompatible change that would break any gem that uses a `-`

**Comment by graywolf** [comment] 2018-03-03 13:46
That's why I wanted to add option like `--no-add-pre` or something, how's that backwards incompatible if you have to intentionally turn it on?

**Comment by segiddins** [comment] 2018-03-06 05:32
The issue is, since gems get published, _every gem you use_ would have to be in agreement on whether that flag is set or not
