### ISSUE TITLE
unable to require json with unresolved dependencies for it

### ISSUE THREAD

**Issue by ccutrer** [rubygems/rubygems#1451] opened 2016-01-12 22:17 UTC
The conditions to hit this are pretty complicated, but the tl;dr is that `Gem::Specification.find_in_unresolved_tree` doesn't return the built in `json` gem included with ruby.

So, full setup:
- Install ruby 2.3.0
- `gem install json -v 1.8.2`
- create the following files:

```
test_json/
  test_json.gemspec
  bin/
    test_json
```

Contents of the gemspec:

```
Gem::Specification.new do |s|
  s.name = 'test_json'
  s.version = '1.0'
  s.summary = ''
  s.authors = ['Cody Cutrer']
  s.add_dependency 'activesupport'
  s.add_dependency 'aws-sdk-v1'
  s.executables = 'test_json'
end
```

Contents of the binary:

```
#!/usr/bin/env ruby

require 'json'
```
- `gem build test_json.gemspec`
- `gem install test_json-1.0.gemspec`
- `test_json`
- observe the error:

```
/Users/cody/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2276:in `check_version_conflict': can't activate json-1.8.2, already activated json-1.8.3 (Gem::LoadError)
    from /Users/cody/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1405:in `activate'
    from /Users/cody/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:89:in `block in require'
    from /Users/cody/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:88:in `each'
    from /Users/cody/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:88:in `require'
    from /Users/cody/.gem/ruby/2.3.0/gems/test_json-1.0/bin/test_json:3:in `<top (required)>'
    from /Users/cody/.gem/ruby/2.3.0/bin/test_json:23:in `load'
    from /Users/cody/.gem/ruby/2.3.0/bin/test_json:23:in `<main>'
```

What's going on is that rubygem's require sees that `json` is a built in gem (it exists in `lib/ruby/gems/2.3.0/specifications/default`), so activates the gemspec. Due to the `test_json` gem's dependency on both `activesupport` and `aws-sdk-v1` (which transitively depend on `json`, but with different requirements), `unresolved_deps` is not empty. It also does not include `json` (cause `test_json` doesn't directly depend on it). So then we get to `Gem::Specification.find_in_unresolved_tree`, which finds two candidates - json 1.8.2 (which we manually installed. in my case it had been installed by an app that was locked to 1.8.2), and the builtin 1.8.3. But the 1.8.3 spec returns `false` for `have_file?('json')`, because its `gems_dir` is `lib/ruby/gems/2.3.0/gems`, and `lib/ruby/gems/2.3.0/gems/json-1.8.3/json.rb` does not exist - it's actually at `lib/ruby/2.3.0/json.rb`. I'm pretty sure the fix is to return immediately in `find_in_unresolved_tree` if `to_spec.activated?`. monkey patching that into my current ruby gems fixes it for me.

**Comment by duckinator** [comment] 2016-01-31 04:15
Hi! I attempted to reproduce this, but couldn't.

I made a testcase: https://gist.github.com/duckinator/664133265f1d6f1f6f17

Can you clone that, run `./test.sh`, and pastebin the results?

E.g.,

```
$ git clone https://gist.github.com/664133265f1d6f1f6f17.git rubygems-issue-1451-testcase
$ cd rubygems-issue-1451-testcase
$ ./test.sh
```


You should get results similar to the following:

```
$ ./test.sh
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
2.5.1
Building native extensions.  This could take a while...
Successfully installed json-1.8.2
Parsing documentation for json-1.8.2
Done installing documentation for json after 0 seconds
1 gem installed
  Successfully built RubyGem
  Name: rubygems-issue-1451-testcase
  Version: 1.0
  File: rubygems-issue-1451-testcase-1.0.gem
Successfully installed rubygems-issue-1451-testcase-1.0
Parsing documentation for rubygems-issue-1451-testcase-1.0
Done installing documentation for rubygems-issue-1451-testcase after 0 seconds
1 gem installed
$
```

**Comment by RUN-CMD** [comment] 2016-02-18 20:50
Howdy, I'm experiencing a similar problem. [Here's my output of the above testcase](http://pastebin.com/9Bm6iJFr). FWIW I had 1.8.3 installed prior to execution.

**Comment by duckinator** [comment] 2016-02-19 19:17
Hi! Good to know the testcase works. Could you pastebin the output of `gem env` for me, @RUN-CMD?

**Comment by RUN-CMD** [comment] 2016-02-19 20:50
Sure thing, [here's my output](http://pastebin.com/z96GQht6) from `$ gem env`

I'm only just now noticing that I'm not on the latest rubygems (2.5.1 vs 2.5.2)

**Comment by duckinator** [comment] 2016-02-19 23:25
The two differences that stand out between your system and my systems I can't reproduce it on are the operating system (OS X vs Windows 8 and Linux) and you using rbenv (as opposed to nothing and chruby). I'll poke around on a system with rbenv later and see if I can reproduce it there.

**Comment by ccutrer** [comment] 2016-02-19 23:30
I should note that when I was having the problem, I was on OS X with chruby.

**Comment by duckinator** [comment] 2016-02-19 23:31
Okay, then in that case it sounds like an OS X issue. I'll see if I can find someone who's got an OS X system who can look at this. Thanks!

**Comment by indirect** [comment] 2016-02-20 23:11
I'm on OS X with chruby, and I was able to run the test case without any problems:

```
$ git clone https://gist.github.com/664133265f1d6f1f6f17.git rubygems-issue-1451-testcase
Cloning into 'rubygems-issue-1451-testcase'...
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 17 (delta 5), reused 16 (delta 4), pack-reused 0
Unpacking objects: 100% (17/17), done.
Checking connectivity... done.

$ cd rubygems-issue-1451-testcase

$ chruby 2.3

$ ./test.sh
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
2.5.1
Fetching: json-1.8.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed json-1.8.2
1 gem installed
  Successfully built RubyGem
  Name: rubygems-issue-1451-testcase
  Version: 1.0
  File: rubygems-issue-1451-testcase-1.0.gem
Fetching: nokogiri-1.6.7.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed nokogiri-1.6.7.2
Fetching: aws-sdk-v1-1.66.0.gem (100%)
Successfully installed aws-sdk-v1-1.66.0
Fetching: activesupport-4.2.5.1.gem (100%)
Successfully installed activesupport-4.2.5.1
Successfully installed rubygems-issue-1451-testcase-1.0
4 gems installed
```

**Comment by Bodacious** [comment] 2016-03-28 07:23
I'm able to reproduce this quite regularly in Ruby 2.3.0 with `heroku-3.42.44`

Any time I run `heroku local` after a `bundle update` in my Rails 4.2.6 app I get the error.

    /Users/Gavin/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2274:in `check_version_conflict': can't activate json-1.8.2, already activated json-1.8.3 (Gem::LoadError)
    	from /Users/Gavin/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1403:in `activate'
    	from /Users/Gavin/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:89:in `block in require'
    	from /Users/Gavin/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:88:in `each'
    	from /Users/Gavin/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:88:in `require'
    	from /Users/Gavin/.rvm/gems/ruby-2.3.0/gems/heroku-3.42.44/lib/heroku/cli.rb:15:in `<top (required)>'
    	from /Users/Gavin/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    	from /Users/Gavin/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    	from /Users/Gavin/.rvm/gems/ruby-2.3.0/gems/heroku-3.42.44/bin/heroku:22:in `<top (required)>'
    	from /Users/Gavin/.rvm/gems/ruby-2.3.0/bin/heroku:23:in `load'
    	from /Users/Gavin/.rvm/gems/ruby-2.3.0/bin/heroku:23:in `<main>'
    	from /Users/Gavin/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
    	from /Users/Gavin/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by esetnik** [comment] 2016-04-06 00:11
I had the exact same issue on Mac OS X with `rbenv` and it went away after upgrading to `rubygems-2.6.3`. All I had to do is run `gem update --system` and `bundle update` and I am good now.

**Comment by whistlerbrk** [comment] 2016-06-27 14:38
for future readers : esetnik's fix did not work for me and I realized I may have my PATH ordering wrong; that is I had heroku installed both via gem (I use rbenv) and via brew, however my gem was being preferred. When I manually spelled out the brew path `/usr/local/bin/heroku` everything was 💯

**Comment by yoav-epstein** [comment] 2016-09-09 20:23
i had json 1.8.2 in gemfile.lock.

resolved with bundle update json and gem uninstall json

**Comment by bronzdoc** [comment] 2018-03-31 21:55
I'm going to close this because it is to old, but if this problem is still happening with the latest version of RubyGems please feel free to let us know with a new issue!

**Closed by bronzdoc** 2018-03-31 21:55 UTC
Labels: platform: osx, type: bug report
