### ISSUE TITLE
`bundle install` shows incorrect resolver error and hides the real culprit: a conflict with the `bundler` dependency

### ISSUE THREAD

**Issue by TheEvilSkeleton** [rubygems/rubygems#3930] opened 2020-09-05 02:29 UTC
### Describe the problem as clearly as you can

`bundle install` tells me that it uses an incompatible version of `middleman-sprockets`. I'm trying to test the website: [flatpak/flatpak.github.io](https://github.com/flatpak/flatpak.github.io)

### Post system independent steps to reproduce the problem

(I looked through the examples but I honestly have no idea what they mean)

### Which command did you run?

I hope you won't mind, but I opened an issue somewhere else containing all the commands I've ran: https://github.com/flatpak/flatpak.github.io/issues/420#issue-693914282

### What were you expecting to happen?

For `bundle install` to stop telling me that `Bundler could not find compatible versions for gem "middleman-sprockets"`

### What actually happened?

```bash
$ bundle install              
Following files may not be writable, so sudo is needed:
  /usr/bin
  /usr/share/gems
  /usr/share/gems/build_info
  /usr/share/gems/bundler
  /usr/share/gems/cache
  /usr/share/gems/doc
  /usr/share/gems/extensions
  /usr/share/gems/gems
  /usr/share/gems/specifications
Fetching https://github.com/barthalion/middleman-matomo.git
Fetching gem metadata from http://rubygems.org/............
Fetching gem metadata from http://rubygems.org/.
Resolving dependencies............................
Bundler could not find compatible versions for gem "middleman-sprockets":
  In Gemfile:
    middleman-sprockets (~> 3.1.2)

    middleman (~> 3) was resolved to 3.0.1.pre, which depends on
      middleman-sprockets (= 3.0.1.pre)
```

**Comment by deivid-rodriguez** [comment] 2020-09-05 09:47
Hi @TheEvilSkeleton! I'm sorry you run into this issue.

In this case, after closer inspection in debugging mode, I found out that the culprit is all possible resolutions for `middleman-core`  require `bundler ~> 1.1`, but you're using `bundler 2`. The error message is obviously really bad. :(

We have a workaround for this issue as a setting called `allow_bundler_dependency_conflicts` where if the running `bundler` finds a requirement for `bundler` itself that conflicts with the running version, it will ignore that requirement and print a warning message like

```
middleman-core (3.4.1) has dependency bundler (~> 1.1), which is unsatisfied by the current bundler version 2.2.0.rc.2, so the dependency is being ignored
```

So to workaround this issue, you can run `BUNDLE_ALLOW_BUNDLER_DEPENDENCY_CONFLICTS=true bundle install`. The error will also be resolved when the flatpack application upgrades to middleman 4, since middleman 4 has relaxed this requirement to allow bundler 2.

The following is for maintainers to debate:
 
Using the `allow_bundler_dependency_conflicts` setting might seem better that the current situation where you get a very cryptic error really hard to figure out. BUT, `bundler` will be resolving to a set of gems that might not actually work well with the running `bundler`. In the majority of the cases, this will be an error in the dependency specification that was overly strict (like `bundler ~> 1.1` here), but there could be a chance where an application is actually using some bundler functionality only available in certain version, and the requirement will be there for a good reason.

So, if we decided to enable to `allow_bundler_dependency_conflicts` setting by default as a "quick fix" for these issues, we should at least also display a noisy warning when `bundle exec` is run on a lockfile resolved in this way (BUNDLED_WITH conflicting with a `bundler` requirement).

In any case, the right fix for this would be to improve the resolver so that either:

* A proper error is displayed when the running `bundler` version conflicts with a requirement on `bundler`.
* A resolution is actually found by auto-switching to a compatible `bundler` version and re-resolving from there.

**Comment by TheEvilSkeleton** [comment] 2020-09-05 13:37
Alright, `BUNDLE_ALLOW_BUNDLER_DEPENDENCY_CONFLICTS=true bundle install` has fixed my problem, but now I have another problem:

```bash
$ BUNDLE_ALLOW_BUNDLER_DEPENDENCY_CONFLICTS=true bundle install
Following files may not be writable, so sudo is needed:
  /usr/bin
  /usr/share/gems
  /usr/share/gems/build_info
  /usr/share/gems/bundler
  /usr/share/gems/cache
  /usr/share/gems/doc
  /usr/share/gems/extensions
  /usr/share/gems/gems
  /usr/share/gems/specifications
Fetching https://github.com/barthalion/middleman-matomo.git
Fetching gem metadata from http://rubygems.org/............
Fetching gem metadata from http://rubygems.org/.
Resolving dependencies....
middleman-core (3.4.1) has dependency bundler (~> 1.1), which is unsatisfied by the current bundler version 2.1.4, so the dependency is being ignored
Using i18n 0.7.0
Using minitest 5.14.2
Using thread_safe 0.3.6
Using tzinfo 1.2.7
Using activesupport 4.2.11.3
Using execjs 2.7.0
Using autoprefixer-rails 9.8.6.3
Using ffi 1.13.1
Using sassc 2.4.0
Using bootstrap-sass 3.4.1
Using bundler 2.1.4
Using mime-types-data 3.2020.0512
Using mime-types 3.3.1
Using mini_portile2 2.4.0
Fetching nokogiri 1.10.10


Your user account isn't allowed to install to the system RubyGems.
  You can cancel this installation and run:

      bundle install --path vendor/bundle

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to RubyGems using sudo.

  Password: 
Installing nokogiri 1.10.10 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /tmp/bundler20200905-4268-11wsroinokogiri-1.10.10/gems/nokogiri-1.10.10/ext/nokogiri
/usr/bin/ruby -I /usr/share/rubygems -r ./siteconf20200905-4268-hrjjib.rb extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.4.0
checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib64
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)
	--help
	--clean
	--use-system-libraries
	--enable-static
	--disable-static
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib64
	--enable-cross-build
	--disable-cross-build

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /tmp/bundler20200905-4268-11wsroinokogiri-1.10.10/extensions/x86_64-linux/2.7.0/nokogiri-1.10.10/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /tmp/bundler20200905-4268-11wsroinokogiri-1.10.10/gems/nokogiri-1.10.10 for inspection.
Results logged to /tmp/bundler20200905-4268-11wsroinokogiri-1.10.10/extensions/x86_64-linux/2.7.0/nokogiri-1.10.10/gem_make.out

An error occurred while installing nokogiri (1.10.10), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.10.10' --source 'http://rubygems.org/'` succeeds before bundling.

In Gemfile:
  middleman was resolved to 3.4.1, which depends on
    middleman-sprockets was resolved to 3.1.4, which depends on
      middleman-core was resolved to 3.4.1, which depends on
        capybara was resolved to 2.4.4, which depends on
          xpath was resolved to 2.1.0, which depends on
            nokogiri
```

> ```Make sure that `gem install nokogiri -v '1.10.10' --source 'http://rubygems.org/'` succeeds before bundling.```

I ran this command, and then it gives me this:

```bash
$ gem install nokogiri -v '1.10.10' --source 'http://rubygems.org/'
Fetching nokogiri-1.10.10.gem
Building native extensions. This could take a while...
ERROR:  Error installing nokogiri:
	ERROR: Failed to build gem native extension.

    current directory: /home/themainone/.gem/ruby/gems/nokogiri-1.10.10/ext/nokogiri
/usr/bin/ruby -I /usr/share/rubygems -r ./siteconf20200905-4417-1d75k4e.rb extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.4.0
checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib64
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)
	--help
	--clean
	--use-system-libraries
	--enable-static
	--disable-static
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib64
	--enable-cross-build
	--disable-cross-build

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/themainone/.gem/ruby/extensions/x86_64-linux/2.7.0/nokogiri-1.10.10/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/themainone/.gem/ruby/gems/nokogiri-1.10.10 for inspection.
Results logged to /home/themainone/.gem/ruby/extensions/x86_64-linux/2.7.0/nokogiri-1.10.10/gem_make.out
```

> ```zlib is missing; necessary for building libxml2```

I tried to install zlib, but it's already installed:

```bash
# dnf install zlib                                     
Fedora Modular 32 - x86_64 - Updates                                                                                                                           38 kB/s |  15 kB     00:00    
Fedora 32 - x86_64 - Updates                                                                                                                                   36 kB/s | 8.2 kB     00:00    
Package zlib-1.2.11-21.fc32.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

**Comment by deivid-rodriguez** [comment] 2020-09-05 16:42
You probably need `zlib-dev` instead: https://nokogiri.org/tutorials/installing_nokogiri.html#fedora-red-hat-and-centos.

**Comment by TheEvilSkeleton** [comment] 2020-09-05 17:05
We're progressing!

I've installed `zlib-devel` and now the command worked!

```bash
$ BUNDLE_ALLOW_BUNDLER_DEPENDENCY_CONFLICTS=true bundle install
Following files may not be writable, so sudo is needed:
  /usr/bin
  /usr/share/gems
  /usr/share/gems/build_info
  /usr/share/gems/bundler
  /usr/share/gems/cache
  /usr/share/gems/doc
  /usr/share/gems/extensions
  /usr/share/gems/gems
  /usr/share/gems/specifications
Fetching https://github.com/barthalion/middleman-matomo.git
Fetching gem metadata from http://rubygems.org/............
Fetching gem metadata from http://rubygems.org/.
Resolving dependencies....
middleman-core (3.4.1) has dependency bundler (~> 1.1), which is unsatisfied by the current bundler version 2.1.4, so the dependency is being ignored
Using i18n 0.7.0
Using minitest 5.14.2
Using thread_safe 0.3.6
Using tzinfo 1.2.7
Using activesupport 4.2.11.3
Using execjs 2.7.0
Using autoprefixer-rails 9.8.6.3
Using ffi 1.13.1
Using sassc 2.4.0
Using bootstrap-sass 3.4.1
Using bundler 2.1.4
Using mime-types-data 3.2020.0512
Using mime-types 3.3.1
Using mini_portile2 2.4.0
Using nokogiri 1.10.10
Fetching rack 1.6.13


Your user account isn't allowed to install to the system RubyGems.
  You can cancel this installation and run:

      bundle install --path vendor/bundle

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to RubyGems using sudo.

  Password: 
Installing rack 1.6.13
Fetching rack-test 1.1.0
Installing rack-test 1.1.0
Fetching xpath 2.1.0
Installing xpath 2.1.0
Fetching capybara 2.4.4
Installing capybara 2.4.4
Fetching chunky_png 1.3.12
Installing chunky_png 1.3.12
Fetching coffee-script-source 1.12.2
Installing coffee-script-source 1.12.2
Fetching coffee-script 2.4.1
Installing coffee-script 2.4.1
Fetching multi_json 1.15.0
Installing multi_json 1.15.0
Fetching sass 3.4.25
Installing sass 3.4.25
Fetching compass-core 1.0.3
Installing compass-core 1.0.3
Fetching compass-import-once 1.0.5
Installing compass-import-once 1.0.5
Using rb-fsevent 0.10.4
Using rb-inotify 0.10.1
Fetching compass 1.0.3
Installing compass 1.0.3
Fetching eventmachine 1.2.7
Installing eventmachine 1.2.7 with native extensions
Fetching http_parser.rb 0.6.0
Installing http_parser.rb 0.6.0 with native extensions
Fetching em-websocket 0.5.1
Installing em-websocket 0.5.1
Using erubis 2.7.0
Fetching temple 0.8.2
Installing temple 0.8.2
Fetching tilt 1.4.1
Installing tilt 1.4.1
Fetching haml 5.1.2
Installing haml 5.1.2
Fetching hike 1.2.3
Installing hike 1.2.3
Fetching uber 0.0.15
Installing uber 0.0.15
Fetching hooks 0.4.1
Installing hooks 0.4.1
Using json 2.3.1
Fetching kramdown 1.17.0
Installing kramdown 1.17.0
Fetching libv8 3.16.14.19 (x86_64-linux)
Installing libv8 3.16.14.19 (x86_64-linux)
Using listen 3.0.8
Fetching padrino-support 0.12.9
Installing padrino-support 0.12.9
Fetching padrino-helpers 0.12.9
Installing padrino-helpers 0.12.9
Fetching thor 1.0.1
Installing thor 1.0.1
Fetching middleman-core 3.4.1
Installing middleman-core 3.4.1
Fetching middleman-more 3.1.6
Installing middleman-more 3.1.6
Fetching sprockets 2.12.5
Installing sprockets 2.12.5
Fetching sprockets-helpers 1.0.1
Installing sprockets-helpers 1.0.1
Fetching sprockets-sass 1.0.3
Installing sprockets-sass 1.0.3
Fetching middleman-sprockets 3.1.4
Installing middleman-sprockets 3.1.4
Fetching uglifier 2.7.2
Installing uglifier 2.7.2
Fetching middleman 3.4.1
Installing middleman 3.4.1
Fetching net-ssh 6.1.0
Installing net-ssh 6.1.0
Fetching net-sftp 3.0.0
Installing net-sftp 3.0.0
Fetching ptools 1.4.0
Installing ptools 1.4.0
Fetching middleman-deploy 1.0.0
Installing middleman-deploy 1.0.0
Fetching rack-livereload 0.3.17
Installing rack-livereload 0.3.17
Fetching middleman-livereload 3.4.6
Installing middleman-livereload 3.4.6
Using middleman-matomo 0.0.1 from https://github.com/barthalion/middleman-matomo.git (at master@62f213a)
Fetching redcarpet 3.5.0
Installing redcarpet 3.5.0 with native extensions
Fetching ref 2.0.0
Installing ref 2.0.0
Fetching therubyracer 0.12.3
Installing therubyracer 0.12.3 with native extensions
Bundle complete! 12 Gemfile dependencies, 64 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from compass:
    Compass is charityware. If you love it, please donate on our behalf at http://umdf.org/compass Thanks!
```

But now, when I run `bundle exec middleman server`, it still doesn't work:

```bash
$ bundle exec middleman server
Ignoring eventmachine-1.2.7 because its extensions are not built. Try: gem pristine eventmachine --version 1.2.7
Ignoring http_parser.rb-0.6.0 because its extensions are not built. Try: gem pristine http_parser.rb --version 0.6.0
Ignoring redcarpet-3.5.0 because its extensions are not built. Try: gem pristine redcarpet --version 3.5.0
Ignoring therubyracer-0.12.3 because its extensions are not built. Try: gem pristine therubyracer --version 0.12.3
Could not find eventmachine-1.2.7 in any of the sources
Run `bundle install` to install missing gems.
```

**Comment by deivid-rodriguez** [comment] 2020-09-06 10:22
Ok, the seems unexpected, I'll try to have a look at that.

**Comment by TheEvilSkeleton** [comment] 2020-09-26 14:28
Any update?

**Comment by deivid-rodriguez** [comment] 2020-09-26 15:50
I made some progress about the original issue, discovering that the conflict about the bundler requirement is actually there originally, but bundler does some cleanup of "redundant" conflicts before showing the error and in this case it's actually incorrect eliminating the actual culprit. I want to dig it more about this, so I'll go ahead a rename this issue to remind me what's about.

Regarding your actual problem, could you open a separate issue describing the situation and how it's unexpected, so that I don't forget about it?

**Comment by TheEvilSkeleton** [comment] 2020-09-28 00:13
Here you go: https://github.com/rubygems/rubygems/issues/3970.

**Comment by deivid-rodriguez** [comment] 2020-09-28 09:59
@TheEvilSkeleton I'm sorry I failed to explain what I meant. This issue originally was about a problem with the resolver. That problem has all the information for reproducing it and understand it here, and we also have a workaround (`BUNDLE_ALLOW_BUNDLER_DEPENDENCY_CONFLICTS`). So this ticket is good to track that issue.

However, after applying the workaround, you're now facing a separate issue. I'd like you to report the other issue separately, with steps to be able to reproduce it. It might be related to the sudo warning being printed earlier, not sure.

**Comment by deivid-rodriguez** [comment] 2020-09-28 10:00
Oh, sorry again, actually I now see that you posted correct steps there. Nevermind.

**Comment by TheEvilSkeleton** [comment] 2020-09-28 18:20
It's okay, we're all trying our best to help each other.

**Closed** 2021-01-25 10:28 UTC
Labels: Bundler
