### ISSUE TITLE
Respect Ruby Version when determining dependencies

### ISSUE THREAD

**Issue by enkessler** [rubygems/rubygems#4263] opened 2021-01-09 14:52 UTC
### Describe the problem as clearly as you can
Bundler does not take into account the version of Ruby that is running it when it resolves dependencies, often resulting in it selecting dependencies that are not compatible with the running version of Ruby.

My problem is essentially this very old issue: https://github.com/rubygems/bundler/issues/2721

Since it has been over half a decade, is this functionality possible yet?

### Post steps to reproduce the problem

1. Attempt to `bundle install` a gem on a version of Ruby that is outside of it's declared version range. 

### Which command did you run?

`bundle install` or `bundle update`

### What were you expecting to happen?

For Bundler to know better than to try and use a version of a gem that has explicitly declared (as per its gemspec and displayed listing on Rubygems) itself incompatible with the version of Ruby being used.

I would expect this phrase (taken from an unrelated page of the Bundler documentation) to apply:
> "Frankly, this is the sort of problem that computers are good at, and which you, a developer, should not need to spend time doing."

### What actually happened?

Bundler only considered the versions of gem dependencies and not the version of Ruby resulting in errors like this:

```
Installing cucumber 3.0.2

Gem::InstallError: cucumber requires Ruby version >= 2.2.

An error occurred while installing cucumber (3.0.2), and Bundler cannot
continue.
Make sure that `gem install cucumber -v '3.0.2'` succeeds before bundling.
```
(running on Ruby 2.1, for this example)

The result is that I often have to spend hours picking through transitive dependencies in order to figure out which versions of which gems work with which versions of Ruby and then filling my `Gemfile`s with code like this in order to compensate:

```
if RUBY_VERSION =~ /^2\.0/
  gem 'cucumber', '< 3.0.1' # Requires Ruby 2.1+ after this point
elsif RUBY_VERSION =~ /^2\.1/
  gem 'cucumber', '< 3.0.2' # Requires Ruby 2.2+ after this point
elsif RUBY_VERSION =~ /^3\./
  # You get the idea...
end
```

### If not included with the output of your command, run `bundle env` and paste the output below

Leaving this out for now, as this issue is more of a feature request/clarification than a bug.

**Comment by deivid-rodriguez** [comment] 2021-01-11 08:16
Hello @enkessler, thanks for the report.

I can confirm to you that this feature was added to bundler a long time ago and that the first statement in your issue is false in general. Since you explicitly stated that this isn't a bug report, I'll close this.

Please report a separate ticket with whatever problems you're having. Make sure you include a way to reproduce the issue, and if you can't, at least a failing CI link and some `bundle install --verbose` logs.

And please, make sure you use the latest bundler version in the new ticket. It feels a bit nonsensical to complain so vehemently about a functionality that was missing 5 years ago while admittedly using a bundler version that, from what I know so far about your issue, could be as old as that ticket.

**Closed by deivid-rodriguez** 2021-01-11 08:16 UTC
Labels: Bundler
