### ISSUE TITLE
With RubyGems 2.7.5 on JRuby, Bundler incorrectly activates the built-in minitest from stdlib

### ISSUE THREAD

**Issue by philr** [rubygems/rubygems#2188] opened 2018-02-13 20:51 UTC
I'm having a problem.

My current problem is that after upgrading to RubyGems 2.7.5 on JRuby 9.1.15.0, Bundler incorrectly activates the built-in copy of Minitest instead of the version requested in the `Gemfile`.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

Here are my current environment details:

```
$ gem env version
2.7.5
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

I initially raised this issue as jruby/jruby#5038. It was suggested that I raise it here instead.

With a clean install of JRuby 9.1.15.0 and a `Gemfile` containing `gem "minitest", "5.11.3"`, Bundler will activate the minitest 5.11.3 gem as expected. After upgrading to RubyGems 2.7.5, Bundler incorrectly activates the built-in version of minitest from stdlib instead.

Install a clean copy of JRuby 9.1.15.0 into `/tmp/jruby-9.1.15.0`:
```
$ curl https://repo1.maven.org/maven2/org/jruby/jruby-dist/9.1.15.0/jruby-dist-9.1.15.0-bin.tar.gz | tar xz -C /tmp
$ export PATH="/tmp/jruby-9.1.15.0/bin:$PATH"
$ hash -r
$ jruby -v
jruby 9.1.15.0 (2.3.3) 2017-12-07 929fde8 OpenJDK 64-Bit Server VM 25.151-b12 on 1.8.0_151-8u151-b12-0ubuntu0.17.04.2-b12 +jit [linux-x86_64]
$ gem --version
2.6.14
```

Install bundler 1.16.1 (the same version that is included in RubyGems 2.7.5):
```
$ gem install bundler -v1.16.1
Fetching: bundler-1.16.1.gem (100%)
Successfully installed bundler-1.16.1
1 gem installed
```

Create and switch to a directory for testing:
```
$ mkdir /tmp/issue2188 && cd /tmp/issue2188
```

Create a Gemfile, add minitest 5.11.3 and install:
```
$ bundle init && bundle add minitest -v 5.11.3
Writing new Gemfile to /tmp/gemissue/Gemfile
Fetching gem metadata from https://rubygems.org/.............
Resolving dependencies...
Fetching gem metadata from https://rubygems.org/.............
Using bundler 1.16.1
Fetching minitest 5.11.3
Installing minitest 5.11.3
```

Run a test to confirm that the correct version of minitest gets loaded (5.11.3) and that the load path is ordered appropriately:
```
$ bundle exec jruby -rminitest -e'puts Minitest::VERSION; p $:'
5.11.3
["/tmp/jruby-9.1.15.0/lib/ruby/gems/shared/gems/bundler-1.16.1/lib",
 "/tmp/jruby-9.1.15.0/lib/ruby/gems/shared/gems/minitest-5.11.3/lib",
 "/tmp/jruby-9.1.15.0/lib/ruby/2.3/site_ruby",
 "/tmp/jruby-9.1.15.0/lib/ruby/stdlib"]
```

Upgrade to RubyGems 2.7.5:
```
$ gem update --system 2.7.5
Updating rubygems-update
Fetching: rubygems-update-2.7.5.gem (100%)
Successfully installed rubygems-update-2.7.5
Installing RubyGems 2.7.5
Bundler 1.16.1 installed
RubyGems 2.7.5 installed
Regenerating binstubs
RubyGems system software updated
```

Re-run the test. This now (incorrectly) outputs the version of the built-in version of minitest (5.4.1). The stdlib directory is now ahead of the minitest gem in the load path.
```
$ bundle exec jruby -rminitest -e'puts Minitest::VERSION; p $:'
5.4.1
["/tmp/jruby-9.1.15.0/lib/ruby/stdlib",
 "/tmp/jruby-9.1.15.0/lib/ruby/gems/shared/gems/minitest-5.11.3/lib",
 "/tmp/jruby-9.1.15.0/lib/ruby/gems/shared/gems/bundler-1.16.1/lib",
 "/tmp/jruby-9.1.15.0/lib/ruby/2.3/site_ruby"]
```

**Comment by segiddins** [comment] 2018-02-13 21:48
Keep in mind that Bundler adds -rbundler/setup to RUBYOPT, which is used after -r flags passed via the command line

**Comment by philr** [comment] 2018-02-13 22:34
@segiddins The outcome is the same when requiring minitest in code instead of with a `-r` flag. With RubyGems upgraded to 2.7.5:

```
$ bundle exec jruby -e'require "minitest"; puts Minitest::VERSION; p $:'
5.4.1
["/tmp/jruby-9.1.15.0/lib/ruby/stdlib",
 "/tmp/jruby-9.1.15.0/lib/ruby/gems/shared/gems/minitest-5.11.3/lib",
 "/tmp/jruby-9.1.15.0/lib/ruby/gems/shared/gems/bundler-1.16.1/lib",
 "/tmp/jruby-9.1.15.0/lib/ruby/2.3/site_ruby"]
```

**Comment by indirect** [comment] 2018-02-14 22:37
Thank you for the reproduction instructions! That should make this much easier to figure out. :)

**Comment by headius** [comment] 2018-03-19 22:14
We have started to get secondary bug reports about this when people upgrade (intentionally or accidentally) to RG 2.7.5+. https://github.com/jruby/jruby/issues/5059

**Comment by deivid-rodriguez** [comment] 2018-07-06 16:37
The problem is that the default `bundler` gem in `jruby 9.1` lives in the stdlib folder on a flat directory structure, so when bundler [modifies RUBYLIB](https://github.com/bundler/bundler/blob/25b76e5e12f861c4f75e726d993d5ba55810deef/lib/bundler/shared_helpers.rb#L334) to put itself at the beginning of the the `LOAD_PATH`, it ends up putting the whole set of default gems in there, instead of only itself. In MRI the default `bundler` lives on a separate folder (`site_ruby`) and its whole directory structure is kept, so it's not affected

Jruby 9.2.0.0 no longer suffer from this issue because even if it ships with `rubygems 2.7.6`, it doesn't include `bundler` as a default gem. Maybe it's an internal modification to workaround this issue. I guess the solution would be that `jruby` does something similar to MRI here?

**Comment by deivid-rodriguez** [comment] 2019-04-25 11:08
This was fixed in https://github.com/bundler/bundler/pull/6941/, and jruby 9.1 is no longer supported anyways, so closing.

**Closed by deivid-rodriguez** 2019-04-25 11:08 UTC
Labels: category: #gem or #require, platform: java, type: bug report
