### ISSUE TITLE
Win32 Gem SSL errors in Japan

### ISSUE THREAD

**Issue by nmadura** [rubygems/rubygems#1855] opened 2017-02-28 06:44 UTC
My current problem is running/updating packages from gem. (on a Japanese Win7-32 computer)

This issue is related to:
  - [ x ] The command line `gem`
```
C:\Users\nm\>gem install roo -r -p http://nm:pass@addr:port
ERROR:  SSL verification error at depth 0: unable to get local issuer certificate (20)
ERROR:  You must add /C=JP/ST=Tokyo/O=Digital Arts Inc./OU=Digital Arts Inc./CN=Digital Arts Inc. CA to your local trusted store
<<Clipped, repeated two additional times>>
ERROR:  Could not find a valid gem 'roo' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://rubygems.org/specs.4.8.gz)
ERROR:  SSL verification error at depth 0: unable to get local issuer certificate (20)
ERROR:  You must add /C=JP/ST=Tokyo/O=Digital Arts Inc./OU=Digital Arts Inc./CN=Digital Arts Inc. CA to your local trusted store

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by nmadura** [comment] 2017-02-28 06:48
```
C:\Users\nm\>gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.10
  - RUBY VERSION: 2.2.6 (2016-11-15 patchlevel 396) [i386-mingw32]
  - INSTALLATION DIRECTORY: C:/Users/nm/Applications/Ruby22/lib/ruby/gems/2.2.0
  - USER INSTALLATION DIRECTORY: C:/Users/nm/.gem/ruby/2.2.0
  - RUBY EXECUTABLE: C:/Users/nm/Applications/Ruby22/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/Users/nm/Applications/Ruby22/bin
  - SPEC CACHE DIRECTORY: C:/Users/nm/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86-mingw32
  - GEM PATHS:
     - C:/Users/nm/Applications/Ruby22/lib/ruby/gems/2.2.0
     - C:/Users/nm/.gem/ruby/2.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\Windows\system32
     - C:\Windows
     - C:\Users\nm\Applications\Ruby22\bin
     - C:\Users\nm\Applications\bin
```

**Comment by nmadura** [comment] 2017-02-28 06:53
I have followed all directions I could find <http://guides.rubygems.org/ssl-certificate-update/>
I have also seen some users post the following
```
C:\Users\nm\> ruby -ropenssl -e 'p OpenSSL::X509::DEFAULT_CERT_FILE'
"C:/Users/Justin/Projects/knap-build/var/knapsack/software/x86-windows/openssl/1.0.2j/ssl/cert.pem"
```

```
 C:\Users\nm\Applications\Ruby22\lib\ruby\site_ruby\2.2.0\rubygems\ssl_certs のディレクトリ

2017/02/28  15:16    <DIR>          .
2017/02/28  15:16    <DIR>          ..
2017/02/28  15:10             1,521 AddTrustExternalCARoot.pem
2017/02/28  15:10             1,367 DigiCertHighAssuranceEVRootCA.pem
2017/02/28  15:14             1,261 GlobalSignRootCA.pem
2017/02/28  15:10    <DIR>          index.rubygems.org
2017/02/28  15:10    <DIR>          rubygems.global.ssl.fastly.net
2017/02/28  15:10    <DIR>          rubygems.org
               3 個のファイル               4,149 バイト
               5 個のディレクトリ   8,212,086,784 バイトの空き領域
```

**Comment by nmadura** [comment] 2017-02-28 06:54
I apologize for the multiple postings, the proxy I am driven through is rather draconian, and if I attempt to post something that is too long, it refuses to allow it through.

**Comment by bronzdoc** [comment] 2017-03-11 18:06
Duplicate of https://github.com/rubygems/rubygems/issues/1769 please check that issue for help, thanks!

**Closed by bronzdoc** 2017-03-11 18:06 UTC
Labels: platform: windows
