### ISSUE TITLE
Cannot install gems: 'undefined method `deprecated?' for nil:NilClass'

### ISSUE THREAD

**Issue by acouprie** [rubygems/rubygems#5619] opened 2022-06-10 17:18 UTC
Hello,

I'm having a problem.
I cannot install any gems, nor update `gem update --system`.

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.2.33
  - RUBY VERSION: 3.0.4 (2022-04-12 patchlevel 208) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/share/gems
  - USER INSTALLATION DIRECTORY: /home/ether/.gem/ruby
  - RUBY EXECUTABLE: /usr/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /usr/bin
  - SPEC CACHE DIRECTORY: /home/ether/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux
  - GEM PATHS:
     - /usr/share/gems
     - /home/ether/.gem/ruby
     - /usr/local/share/gems
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--user-install --bindir /home/ether/bin"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/ether/anaconda3/bin
     - /home/ether/bin
     - /home/ether/.pyenv/versions/3.7.2/bin
     - /home/ether/.rbenv/shims
     - /home/ether/.rbenv/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /home/ether/workspace/graph/gurobi901/linux64/bin
     - /opt/arm-tools/arm-none-eabi/bin
     - /home/ether/.fzf/bin
     - /home/ether/workspace/heroku/bin
     - /home/ether/.local/lib/python3.10/site-packages
     - /usr/local/bin
     - /usr/local/sbin
```
```
$ cat /etc/fedora-release
OS version Fedora release 35 (Thirty Five)
$ bundler --version
Bundler version 2.2.33
$ gem --version
3.2.33
$ ruby --version
ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux]
```

I tried `gem install bundler`, `gem update --system`, `gem pristine --all --no-extensions`, but whatever I try, I get this error trace:

```
Ignoring bindex-0.8.1 because its extensions are not built. Try: gem pristine bindex --version 0.8.1
Ignoring bootsnap-1.10.3 because its extensions are not built. Try: gem pristine bootsnap --version 1.10.3
Ignoring debug-1.4.0 because its extensions are not built. Try: gem pristine debug --version 1.4.0
Ignoring digest-3.1.0 because its extensions are not built. Try: gem pristine digest --version 3.1.0
Ignoring io-console-0.5.11 because its extensions are not built. Try: gem pristine io-console --version 0.5.11
Ignoring io-wait-0.2.1 because its extensions are not built. Try: gem pristine io-wait --version 0.2.1
Ignoring msgpack-1.4.4 because its extensions are not built. Try: gem pristine msgpack --version 1.4.4
Ignoring puma-5.6.1 because its extensions are not built. Try: gem pristine puma --version 5.6.1
Ignoring racc-1.6.0 because its extensions are not built. Try: gem pristine racc --version 1.6.0
Ignoring strscan-3.0.1 because its extensions are not built. Try: gem pristine strscan --version 3.0.1
Ignoring bindex-0.8.1 because its extensions are not built. Try: gem pristine bindex --version 0.8.1
Ignoring bootsnap-1.10.3 because its extensions are not built. Try: gem pristine bootsnap --version 1.10.3
Ignoring debug-1.4.0 because its extensions are not built. Try: gem pristine debug --version 1.4.0
Ignoring digest-3.1.0 because its extensions are not built. Try: gem pristine digest --version 3.1.0
Ignoring io-console-0.5.11 because its extensions are not built. Try: gem pristine io-console --version 0.5.11
Ignoring io-wait-0.2.1 because its extensions are not built. Try: gem pristine io-wait --version 0.2.1
Ignoring msgpack-1.4.4 because its extensions are not built. Try: gem pristine msgpack --version 1.4.4
Ignoring puma-5.6.1 because its extensions are not built. Try: gem pristine puma --version 5.6.1
Ignoring racc-1.6.0 because its extensions are not built. Try: gem pristine racc --version 1.6.0
Ignoring strscan-3.0.1 because its extensions are not built. Try: gem pristine strscan --version 3.0.1
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::OPENSSL_VERSION
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::OPENSSL_LIBRARY_VERSION
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::OPENSSL_VERSION_NUMBER
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::OPENSSL_FIPS
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::Config::DEFAULT_CONFIG_FILE
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::OPENSSL_VERSION
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::OPENSSL_LIBRARY_VERSION
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::OPENSSL_VERSION_NUMBER
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::OPENSSL_FIPS
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::Config::DEFAULT_CONFIG_FILE
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::OPENSSL_VERSION
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::OPENSSL_LIBRARY_VERSION
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::OPENSSL_VERSION_NUMBER
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::OPENSSL_FIPS
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::Config::DEFAULT_CONFIG_FILE
ERROR:  Loading command: install (LoadError)
	cannot load such file -- digest/loader
ERROR:  While executing gem ... (NoMethodError)
    undefined method `deprecated?' for nil:NilClass
```

I also tried to reinstall rubygems succesfully with: `sudo dnf reinstall rubygems`

I didn't found anything regarding this issue and the error trace is not very meaningful to find the cause.
Thank you

I acknowledged the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment] 2022-06-11 09:41
Can you show the output of `gem update --system --backtrace`?

**Comment by acouprie** [comment] 2022-06-22 14:14
Sure, here you go : 
```
$ gem update --system --backtrace
Ignoring bindex-0.8.1 because its extensions are not built. Try: gem pristine bindex --version 0.8.1
Ignoring bootsnap-1.10.3 because its extensions are not built. Try: gem pristine bootsnap --version 1.10.3
Ignoring debug-1.4.0 because its extensions are not built. Try: gem pristine debug --version 1.4.0
Ignoring digest-3.1.0 because its extensions are not built. Try: gem pristine digest --version 3.1.0
Ignoring io-console-0.5.11 because its extensions are not built. Try: gem pristine io-console --version 0.5.11
Ignoring io-wait-0.2.1 because its extensions are not built. Try: gem pristine io-wait --version 0.2.1
Ignoring msgpack-1.4.4 because its extensions are not built. Try: gem pristine msgpack --version 1.4.4
Ignoring puma-5.6.1 because its extensions are not built. Try: gem pristine puma --version 5.6.1
Ignoring racc-1.6.0 because its extensions are not built. Try: gem pristine racc --version 1.6.0
Ignoring strscan-3.0.1 because its extensions are not built. Try: gem pristine strscan --version 3.0.1
Ignoring bindex-0.8.1 because its extensions are not built. Try: gem pristine bindex --version 0.8.1
Ignoring bootsnap-1.10.3 because its extensions are not built. Try: gem pristine bootsnap --version 1.10.3
Ignoring debug-1.4.0 because its extensions are not built. Try: gem pristine debug --version 1.4.0
Ignoring digest-3.1.0 because its extensions are not built. Try: gem pristine digest --version 3.1.0
Ignoring io-console-0.5.11 because its extensions are not built. Try: gem pristine io-console --version 0.5.11
Ignoring io-wait-0.2.1 because its extensions are not built. Try: gem pristine io-wait --version 0.2.1
Ignoring msgpack-1.4.4 because its extensions are not built. Try: gem pristine msgpack --version 1.4.4
Ignoring puma-5.6.1 because its extensions are not built. Try: gem pristine puma --version 5.6.1
Ignoring racc-1.6.0 because its extensions are not built. Try: gem pristine racc --version 1.6.0
Ignoring strscan-3.0.1 because its extensions are not built. Try: gem pristine strscan --version 3.0.1
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::OPENSSL_VERSION
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::OPENSSL_LIBRARY_VERSION
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::OPENSSL_VERSION_NUMBER
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::OPENSSL_FIPS
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::Config::DEFAULT_CONFIG_FILE
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::OPENSSL_VERSION
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::OPENSSL_LIBRARY_VERSION
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::OPENSSL_VERSION_NUMBER
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::OPENSSL_FIPS
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::Config::DEFAULT_CONFIG_FILE
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::OPENSSL_VERSION
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::OPENSSL_LIBRARY_VERSION
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::OPENSSL_VERSION_NUMBER
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::OPENSSL_FIPS
/usr/lib64/ruby/openssl.so: warning: already initialized constant OpenSSL::Config::DEFAULT_CONFIG_FILE
ERROR:  Loading command: update (LoadError)
	cannot load such file -- digest/loader
	<internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	<internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	/usr/share/gems/gems/digest-3.1.0/lib/digest.rb:16:in `<top (required)>'
	<internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	<internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	/usr/share/rubygems/rubygems/security.rb:474:in `<module:Security>'
	/usr/share/rubygems/rubygems/security.rb:327:in `<top (required)>'
	/usr/share/rubygems/rubygems/package.rb:45:in `require_relative'
	/usr/share/rubygems/rubygems/package.rb:45:in `<top (required)>'
	/usr/share/rubygems/rubygems/dependency_installer.rb:4:in `require_relative'
	/usr/share/rubygems/rubygems/dependency_installer.rb:4:in `<top (required)>'
	/usr/share/rubygems/rubygems/commands/update_command.rb:4:in `require_relative'
	/usr/share/rubygems/rubygems/commands/update_command.rb:4:in `<top (required)>'
	<internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	<internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	/usr/share/rubygems/rubygems/command_manager.rb:223:in `load_and_instantiate'
	/usr/share/rubygems/rubygems/command_manager.rb:135:in `[]'
	/usr/share/rubygems/rubygems/command_manager.rb:196:in `find_command'
	/usr/share/rubygems/rubygems/command_manager.rb:178:in `process_args'
	/usr/share/rubygems/rubygems/command_manager.rb:149:in `run'
	/usr/share/rubygems/rubygems/gem_runner.rb:53:in `run'
	/usr/bin/gem:21:in `<main>'
ERROR:  While executing gem ... (NoMethodError)
    undefined method `deprecated?' for nil:NilClass
	/usr/share/rubygems/rubygems/command_manager.rb:179:in `process_args'
	/usr/share/rubygems/rubygems/command_manager.rb:149:in `run'
	/usr/share/rubygems/rubygems/gem_runner.rb:53:in `run'
	/usr/bin/gem:21:in `<main>'
```

**Comment by deivid-rodriguez** [comment] 2022-06-22 14:48
There's no `/usr/share/gems/gems/digest-3.1.0/lib/digest/loader.rb` file? Does `ruby --disable-gems -e"require 'digest'"` work?

**Comment by acouprie** [comment] 2022-06-22 15:11
Indeed, there is not this file : 
```
$ l /usr/share/gems/gems/digest-3.1.0/lib/digest/         
total 16K
drwxr-xr-x. 2 root root 4.0K Feb  2 23:09 .
drwxr-xr-x. 3 root root 4.0K Feb  2 23:09 ..
-rw-r--r--. 1 root root 3.8K Feb  2 23:09 sha2.rb
-rw-r--r--. 1 root root   69 Feb  2 23:09 version.rb
```

`ruby --disable-gems -e"require 'digest'"` execute succesfully and return nothing.

**Comment by acouprie** [comment] 2022-06-22 15:15
`loader.rb` does not exist either on the digest repo : https://github.com/ruby/digest/tree/master/lib/digest

**Comment by acouprie** [comment] 2022-06-22 15:24
I made it works by adding the file : `/usr/share/gems/gems/digest-3.1.0/lib/digest/loader.rb` with the content : 
```
# frozen_string_literal: true

require 'digest.so'
```

I found this answer in this commit history : https://github.com/ruby/digest/commit/8d7496c3be3b3476510d92a40443965102398da5

**Comment by deivid-rodriguez** [comment] 2022-06-23 09:16
Not sure what happened either, it sounds like your default gems are not properly installed, according to the warnings you were getting at the beginning of your command. I'll close this since the original issue is gone now, and it doesn't seem like a problem in RubyGems. On top of that, newer RubyGems versions don't use the `digest` gem anymore,  only `openssl`, so this should not reproduce in newer versions anyways.

**Closed by deivid-rodriguez** 2022-06-23 09:16 UTC
Labels: status: feedback required, RubyGems
