### ISSUE TITLE
(ArgumentError)     IPv6 address must be 16 bytes

### ISSUE THREAD

**Issue by kholbekj** [rubygems/rubygems#1626] opened 2016-05-25 13:53 UTC
I'm having a problem.

My current problem is that on my build server, trying to install a gem directly with `gem install ...` fails with

```
ERROR:  While executing gem ... (ArgumentError)
    IPv6 address must be 16 bytes
```

I've seen from some old issues that previously this has been either magically solved, or by monkey-patching rubygems like so:
`
sed -i 's/host = uri.host/host = "http:\/\/rubygems.org"/g' /usr/lib/ruby/2.3.1/rubygems/remote_fetcher.rb`

However, it seems pretty nasty and forward incompatible and crazy. Is it really the only fix?

This issue is related to:
- [ ] Network problems
- [ ] Installing a library
- [ ] Publishing a library
- [x] The command line `gem`
- [ ] Other

Here are my current environment details:

```
$ gem env version
2.6.4
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by djberg96** [comment] 2016-05-25 13:56
This was last discussed at https://github.com/rubygems/rubygems/issues/1274 if i recall.

**Comment by kholbekj** [comment] 2016-05-25 14:21
Yeah, that's the one. However, "I cannot reproduce this error anymore: the reason was our network bad configuration (someone else fixed it and I don't know the details)." doesn't exactly help me :)

**Comment by kholbekj** [comment] 2016-05-25 14:22
I can easily install gems with bundler, only dies when using rubygems directly (which complicates actually installing bundler).

**Comment by djberg96** [comment] 2016-05-25 15:26
@kholbekj can you give us the full backtrace please? And your `gem env` output?

**Comment by kholbekj** [comment] 2016-05-25 16:24
Will try when I'm back on the network tomorrow, that is all the normal output produces, so will have to somehow get it to spew out more. I can't replicate this locally, so it's a bit itchy.

**Comment by drbrain** [comment] 2016-05-25 22:26
You can get a backtrace by adding `--backtrace` to the command line.

**Comment by jrafanie** [comment] 2016-05-27 13:36
@kholbekj If you can provide a backtrace that would help isolate it... 

I believe it's being raised [here](https://github.com/ruby/ruby/blob/v2_3_1/lib/resolv.rb#L2497).

I'm taking a guess that [this enormous method with MANY regexps is involved](https://github.com/ruby/ruby/blob/v2_3_1/lib/resolv.rb#L2489).  If so, maybe you can print address and the incoming arg for that method.   Or, if you don't want to disclose a public IPv6 address, maybe you can figure out what's happing?  I'm guessing it's scanning the incoming host value and building what it "thinks" is an invalid IPv6 address.  I have no idea, I try not to validate IPv6 addresses ever.

If it's not that location, it might [be this](https://github.com/ruby/ruby/blob/v2_3_1/lib/resolv.rb#L2237).

I'm guessing there is something specific to the incoming IPv6 address.

**Comment by jrafanie** [comment] 2016-05-27 13:46
Note, there are "rules" for compressing/shrinking IPv6 addresses, such as "::1".  I can't even tell what that large method is doing but maybe it's trying to shrink the full address to a common format.

https://en.wikipedia.org/wiki/IPv6#Address_representation

**Comment by kholbekj** [comment] 2016-05-27 13:57
Gem env:
```
> RubyGems Environment: 
> - RUBYGEMS VERSION: 2.5.1 
> - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-linux] 
> - INSTALLATION DIRECTORY: /root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0 
> - USER INSTALLATION DIRECTORY: /root/.gem/ruby/2.3.0 
> - RUBY EXECUTABLE: /root/.rbenv/versions/2.3.1/bin/ruby 
> - EXECUTABLE DIRECTORY: /root/.rbenv/versions/2.3.1/bin 
> - SPEC CACHE DIRECTORY: /root/.gem/specs 
> - SYSTEM CONFIGURATION DIRECTORY: /root/.rbenv/versions/2.3.1/etc 
> - RUBYGEMS PLATFORMS: 
> - ruby 
> - x86_64-linux 
> - GEM PATHS: 
> - /root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0 
> - /root/.gem/ruby/2.3.0 
> - GEM CONFIGURATION: 
> - :update_sources => true 
> - :verbose => true 
> - :backtrace => false 
> - :bulk_threshold => 1000 
> - REMOTE SOURCES: 
> - https://rubygems.org/ 
> - SHELL PATH: 
> - /root/.rbenv/versions/2.3.1/bin 
> - /root/.rbenv/libexec 
> - /root/.rbenv/plugins/ruby-build/bin 
> - /root/.rbenv/plugins/ruby-build/bin 
> - /root/.rbenv/shims 
> - /root/.rbenv/bin 
> - /usr/local/sbin 
> - /usr/local/bin 
> - /usr/sbin 
> - /usr/bin 
> - /sbin 
> - /bin 
```
is the gem env. I'll see if I can get a stacktrace, but our system has been monkeypatched in the meantime because we really needed the buildserver.
(we replaced `host = uri.host` with `host = 'https://rubygems.org` in remote_fetcher.rb)

**Comment by kholbekj** [comment] 2016-05-27 13:57
Version was downgraded when we swapped rubies, but this happened in 2.6.4 also.

**Comment by jrafanie** [comment] 2016-05-27 14:15
> is the gem env. I'll see if I can get a stacktrace, but our system has been monkeypatched in the meantime because we really needed the buildserver.
> (we replaced host = uri.host with host = 'https://rubygems.org in remote_fetcher.rb)

@kholbekj Understood, but honestly, the address could be literally too many possible values for us to guess...  My eyes gloss over when I read the IPv6 rules and the regexps in resolv.rb.

**Comment by vimutter** [comment] 2017-01-12 16:30
Short version of fix: 
```bash
sed -i 's/res = self.get_length16 { typeclass.decode_rdata self }/begin; res = self.get_length16 { typeclass.decode_rdata self }; rescue => e; raise DecodeError.new("Error: #{e.message}"); end/' `ruby -e 'puts $LOAD_PATH.map { |path| path + "/resolv.rb" }.detect { |path| File.exist? path }'`
```

**Comment by bronzdoc** [comment] 2018-03-21 00:27
Gonna close this since is not clear how is happening, no backtrace was provided or steps to reproduce and nobody has complained about this in almost 2 years, but will reopen if it raises again.

**Closed by bronzdoc** 2018-03-21 00:27 UTC
Labels: status: triage
