### ISSUE TITLE
Failed to establish SSL connection.

### ISSUE THREAD

**Issue by SebastianStehle** [rubygems/rubygems#2294] opened 2018-05-18 10:53 UTC
I just installed ruby on Window 10 and I try to connect to rubygems.org, but it does not work. 

In fiddler I get:
`The connection to 'rubygems.org' failed.  <br />System.Security.SecurityException Failed to negotiate HTTPS connection with server.fiddler.network.https&gt; HTTPS handshake to rubygems.org (for #21) failed. System.IO.IOException Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. &lt; An existing connection was forcibly closed by the remote host`.

With `gem update --system` I get:
`ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    Errno::ECONNRESET: An existing connection was forcibly closed by the remote host. - SSL_connect (https://api.rubygems.org/specs.4.8.gz)`

In chrome it sometimes works, but most of the time it does not.

I also checked the cert store in Windows but there is nothing specific to ruby or rubygems.

This issue is related to:

  - [x] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.6.14.1
```

Do you have SSL problems at the moment?

**Comment by MSP-Greg** [comment] 2018-05-18 15:47
@SebastianStehle

Using 2.5.1 64, I just ran `gem update --system`, and had no issues (needed to update from 2.7.6 anyway).  Using Windows 10 also.

Are you still having issues?  If so, what version of Ruby did you install?

**Comment by SebastianStehle** [comment] 2018-05-18 15:53
I have 2.4.4-1 (x64) (I need this version). I also reinstalled and rebooted several times.

**Comment by MSP-Greg** [comment] 2018-05-18 16:11
Interesting.  I've got most Ruby releases, and `gem update --system` also worked with 2.4.4-1 (x64).

I hate to ask, might you be able to try with 2.5 or a trunk build?  Ruby 2.4.x uses OpenSSL 1.0.2, Ruby 2.5.x and trunk use OpenSSL 1.1.0.  Regardless, the fact that 2.4.4 works for me and not for you is confusing...

Lastly, I believe RubyGems is packaged with its own certs, so I'm not sure if it matters, but is `SSL_CERT_FILE` set in your environment?

**Comment by MSP-Greg** [comment] 2018-05-18 16:18
One last item, you mention that you need to use 2.4.4.  Ruby 2.5 is the first version of Ruby that was fully tested using both mswin & mingw builds.  If you can, you might consider using it...

**Comment by SebastianStehle** [comment] 2018-05-22 10:38
I have this problem only from my notebook at work. At home (other network) it works. I checked the router and there is nothing special. Other devices 

It seems that my device is blocked, but I don't know why. I have the problem with Chrome, Firefox, Edge, curl, fiddler and bundle.

**Comment by MSP-Greg** [comment] 2018-05-22 12:50
>  I have the problem with Chrome, Firefox, Edge, curl, fiddler and bundle.

I assume you mean the problem is connecting to any ssl/https site, but standard http works fine?

Regardless, this doesn't seem to be an issue specific to RubyGems, you might consider closing.

**Comment by bronzdoc** [comment] 2018-05-30 20:21
Closing this since is seems a problem with your device and not rubygems itself

**Closed by bronzdoc** 2018-05-30 20:21 UTC
Labels: status: triage
