### ISSUE TITLE
Permissions issue with strscan and rails 7.0.3 while running bundle install on windows

### ISSUE THREAD

**Issue by hurricup** [rubygems/rubygems#5542] opened 2022-05-16 05:09 UTC
most likely we have this problem again when running bundle install. (started 9 of May)

Environment:
```
- Bundler version 2.2.32
- RUBYGEMS VERSION: 3.2.32
- RUBY VERSION: 3.0.3 (2021-11-24 patchlevel 157) [x64-mingw32]
```

Gemfile is: 
```
source 'https://rubygems.org'

gem 'rails'
gem 'minitest'
gem 'activesupport'
gem 'shoulda'
gem 'minitest-spec-rails'
```

Gemfile.lock:
```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (7.0.3)
      actionpack (= 7.0.3)
      activesupport (= 7.0.3)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (7.0.3)
      actionpack (= 7.0.3)
      activejob (= 7.0.3)
      activerecord (= 7.0.3)
      activestorage (= 7.0.3)
      activesupport (= 7.0.3)
      mail (>= 2.7.1)
      net-imap
      net-pop
      net-smtp
    actionmailer (7.0.3)
      actionpack (= 7.0.3)
      actionview (= 7.0.3)
      activejob (= 7.0.3)
      activesupport (= 7.0.3)
      mail (~> 2.5, >= 2.5.4)
      net-imap
      net-pop
      net-smtp
      rails-dom-testing (~> 2.0)
    actionpack (7.0.3)
      actionview (= 7.0.3)
      activesupport (= 7.0.3)
      rack (~> 2.0, >= 2.2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (7.0.3)
      actionpack (= 7.0.3)
      activerecord (= 7.0.3)
      activestorage (= 7.0.3)
      activesupport (= 7.0.3)
      globalid (>= 0.6.0)
      nokogiri (>= 1.8.5)
    actionview (7.0.3)
      activesupport (= 7.0.3)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (7.0.3)
      activesupport (= 7.0.3)
      globalid (>= 0.3.6)
    activemodel (7.0.3)
      activesupport (= 7.0.3)
    activerecord (7.0.3)
      activemodel (= 7.0.3)
      activesupport (= 7.0.3)
    activestorage (7.0.3)
      actionpack (= 7.0.3)
      activejob (= 7.0.3)
      activerecord (= 7.0.3)
      activesupport (= 7.0.3)
      marcel (~> 1.0)
      mini_mime (>= 1.1.0)
    activesupport (7.0.3)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    builder (3.2.4)
    concurrent-ruby (1.1.10)
    crass (1.0.6)
    digest (3.1.0)
    erubi (1.10.0)
    globalid (1.0.0)
      activesupport (>= 5.0)
    i18n (1.10.0)
      concurrent-ruby (~> 1.0)
    loofah (2.18.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (1.0.2)
    method_source (1.0.0)
    mini_mime (1.1.2)
    minitest (5.15.0)
    minitest-spec-rails (6.1.0)
      minitest (>= 5.0)
      railties (>= 4.1)
    net-imap (0.2.3)
      digest
      net-protocol
      strscan
    net-pop (0.1.1)
      digest
      net-protocol
      timeout
    net-protocol (0.1.3)
      timeout
    net-smtp (0.3.1)
      digest
      net-protocol
      timeout
    nio4r (2.5.8)
    nokogiri (1.13.6-x64-mingw32)
      racc (~> 1.4)
    racc (1.6.0)
    rack (2.2.3)
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (7.0.3)
      actioncable (= 7.0.3)
      actionmailbox (= 7.0.3)
      actionmailer (= 7.0.3)
      actionpack (= 7.0.3)
      actiontext (= 7.0.3)
      actionview (= 7.0.3)
      activejob (= 7.0.3)
      activemodel (= 7.0.3)
      activerecord (= 7.0.3)
      activestorage (= 7.0.3)
      activesupport (= 7.0.3)
      bundler (>= 1.15.0)
      railties (= 7.0.3)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.4.2)
      loofah (~> 2.3)
    railties (7.0.3)
      actionpack (= 7.0.3)
      activesupport (= 7.0.3)
      method_source
      rake (>= 12.2)
      thor (~> 1.0)
      zeitwerk (~> 2.5)
    rake (13.0.6)
    shoulda (4.0.0)
      shoulda-context (~> 2.0)
      shoulda-matchers (~> 4.0)
    shoulda-context (2.0.0)
    shoulda-matchers (4.5.1)
      activesupport (>= 4.2.0)
    strscan (3.0.3)
    thor (1.2.1)
    timeout (0.2.0)
    tzinfo (2.0.4)
      concurrent-ruby (~> 1.0)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    zeitwerk (2.5.4)

PLATFORMS
  x64-mingw32

DEPENDENCIES
  activesupport
  minitest
  minitest-spec-rails
  rails
  shoulda

BUNDLED WITH
   2.2.32
```

Reproduced on CI but can't reproduce this locally:
```
Fetching gem metadata from https://rubygems.org/
Resolving dependencies...
Fetching rake 13.0.6
Installing rake 13.0.6
Using concurrent-ruby 1.1.10
Using i18n 1.10.0
Fetching minitest 5.15.0
Installing minitest 5.15.0
Using tzinfo 2.0.4
Using activesupport 7.0.3
Using builder 3.2.4
Using erubi 1.10.0
Fetching racc 1.6.0
Installing racc 1.6.0 with native extensions
Using nokogiri 1.13.6 (x64-mingw32)
Using rails-dom-testing 2.0.3
Using crass 1.0.6
Using loofah 2.18.0
Using rails-html-sanitizer 1.4.2
Using actionview 7.0.3
Using rack 2.2.3
Using rack-test 1.1.0
Using actionpack 7.0.3
Using nio4r 2.5.8
Using websocket-extensions 0.1.5
Using websocket-driver 0.7.5
Using actioncable 7.0.3
Using globalid 1.0.0
Using activejob 7.0.3
Using activemodel 7.0.3
Using activerecord 7.0.3
Using marcel 1.0.2
Using mini_mime 1.1.2
Using activestorage 7.0.3
Using mail 2.7.1
Fetching digest 3.1.0
Installing digest 3.1.0 with native extensions
Fetching timeout 0.2.0
Installing timeout 0.2.0
Fetching net-protocol 0.1.3
Installing net-protocol 0.1.3
Installing strscan 3.0.3 with native extensions
Bundler::PermissionError: There was an error while trying to delete
`C:/Users/builduser/.local/share/gem/ruby/3.0.0/extensions/x64-mingw32/3.0.0/strscan-3.0.3`. 
It is likely that you need to grant executable permissions for all parent directories and write permissions for
`C:/Users/builduser/.local/share/gem/ruby/3.0.0/extensions/x64-mingw32/3.0.0`, and the same thing for all subdirectories inside
C:/Users/builduser/.local/share/gem/ruby/3.0.0/extensions/x64-mingw32/3.0.0/strscan-3.0.3.
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/rubygems_gem_installer.rb:103:in `strict_rm_rf'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/rubygems_gem_installer.rb:20:in `install'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/source/rubygems.rb:200:in `install'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:54:in `install'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:186:in `do_install'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:171:in `install_serially'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:97:in `call'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:71:in `call'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer.rb:262:in `install_in_parallel'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer.rb:209:in `install'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer.rb:89:in `block in run'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/process_lock.rb:12:in `block in lock'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/process_lock.rb:9:in `open'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/process_lock.rb:9:in `lock'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer.rb:71:in `run'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/installer.rb:23:in `install'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/cli/install.rb:60:in `run'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/cli.rb:253:in `block in install'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/settings.rb:131:in `temporary'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/cli.rb:252:in `install'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/cli.rb:31:in `dispatch'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/cli.rb:25:in `start'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/libexec/bundle:49:in `block in <top (required)>'
C:/Ruby30-x64/lib/ruby/3.0.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/libexec/bundle:37:in `<top (required)>'
C:/Ruby30-x64/bin/bundle.cmd:31:in `load'
C:/Ruby30-x64/bin/bundle.cmd:31:in `<main>'

An error occurred while installing strscan (3.0.3), and Bundler cannot continue.

In Gemfile:
rails was resolved to 7.0.3, which depends on
actionmailbox was resolved to 7.0.3, which depends on
net-imap was resolved to 0.2.3, which depends on
strscan
```

When watching this from the CI agent we run on, i see the strscan directory with `so` file in it.
Presume it caused by rails 7.0.3 release

_Originally posted by @hurricup in https://github.com/rubygems/rubygems/issues/5274#issuecomment-1125940347_

**Comment by hurricup** [comment] 2022-05-16 05:11
Wasn't sure if you check closed issue, so posting as a new one. Also, looks like there is no additonal processes, besides extconf: https://github.com/rubygems/rubygems/issues/5274#issuecomment-1126021420

**Comment by deivid-rodriguez** [comment] 2022-05-16 08:18
Thanks, yeah, better a new issue. Too bad we can't yet reproduce it reliably.

**Comment by deivid-rodriguez** [comment] 2022-05-16 08:31
Something I want to improve here that might shed some light is that the error message might not really be accurate here. Any exception might've been raised while trying to remove the folder, the permissions issue is just a guess. The better fix here IMO would be that `fileutils` wouldn't swallow any exceptions while trying to remove the file, so that we can actually see the real culprit here. I proposed this change to fileutils at https://github.com/ruby/fileutils/pull/58, and I will bring it to ruby-core now.

**Comment by hurricup** [comment] 2022-05-16 08:32
I inspected the server when problem happened. All i see is a directory with `so` file in it.

**Comment by deivid-rodriguez** [comment] 2022-05-16 08:53
Oh, this is indeed probably the same as #5274, sorry I missed that. `bundle install` opens the `.so` file at some point, and a later time it tries to reinstall the library again (which completely removes any existing installation as a first step). Since the `.so` file is opened, Windows won't let you delete it. I guess we should detect if the library is currently loaded while installing it, and completely skip installation in that case.

Regarding why you can't reproduce, I think maybe you have multiple strscan versions installed locally and they are not conflicting like in CI (different version is being loaded from the one being installed?).

This should be fixed once https://github.com/ruby/psych/pull/534 is released and users pick that up, but it's an issue at the moment.

**Comment by hurricup** [comment] 2022-05-16 09:21
The thing is that i can't even reproduce it on CI server. 
Tried the same `Gemfile` but used different `--path` for bundle install. And worked like a charm. 
The thing is - I'm not quite understand why bundler or rubygems need to remove anything while installing gems. Feels strange. Shouldn't it just use the gem if it is already installed?

**Comment by deivid-rodriguez** [comment] 2022-05-16 09:27
Yes, if it's already installed, it uses it. But if it doesn't detect a "valid installation" and decides it needs to reinstall, it still makes sure the target folder is empty before installing anything. I guess this is to heal and bad previous installation, or something like that.

I think the fact that it can't be reproduced in CI might be because of a race condition, is it reproducible reliable with `--jobs=1`?

**Comment by hurricup** [comment] 2022-05-16 09:29
I'll try. But I was thinking that by default bundler do not parallelize installation (and jobs is 1).

**Comment by deivid-rodriguez** [comment] 2022-05-16 09:36
Oh, you're correct, on Windows we still default to 1 job. Than I'm not sure why it can't be reproduced every time 😭.

**Comment by hurricup** [comment] 2022-05-16 09:43
Ideally would be nice to see smart diagnostic here, like `unable to remove file.xxx held by proces pid: 123, command ....` but not sure if it's possible.

**Comment by deivid-rodriguez** [comment] 2022-05-16 10:53
Yeah, that would be ideal! By the way, psych 4.0.4 is out, so you should also be able to get rid of the error by upgrading that.

**Comment by hurricup** [comment] 2022-05-16 11:03
Yep, running tests already. Fingers crossed.

**Comment by deivid-rodriguez** [comment] 2022-05-16 12:59
Interesting, then I have no idea what's holding the `strscan.so` file. One idea to debug this would be to create a `strscan.rb` file that logs what's requiring it and then loads the `.so` file, so that we can figure out where this comes from.

**Comment by hurricup** [comment] 2022-05-16 13:01
Ok, seems I found the problem. 
There are multiple tests running. 
1. Looks like previous test unable to uninstall `strscan` and keeps this `so` file. 
2. When  `bundler` attempts to install for the next test it loads this `so` file (this is strange, because there is no gem, only `so` file). And then fails to remove the directory.

One thing for sure, in previous test I see: 
```
Failed to uninstall gem: GemInfo{myName='strscan', myVersion='3.0.3', myUrl='file://C:/Users/builduser/.local/share/gem/ruby/3.0.0/gems/strscan-3.0.3'}; Started with threads context:
```

**Comment by hurricup** [comment] 2022-05-16 13:01
I'll try to reproduce this. case.

**Comment by leoplct** [comment] 2022-07-02 13:35
I am having the same issue. Did you solve it?
It's caused by upgrading to Rails 7.0.3

` The application encountered the following error: You have already activated strscan 3.0.0, but your Gemfile requires strscan 3.0.3. Since strscan is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports strscan as a default gem. (Gem::LoadError)`

**Comment by jaykilleen** [comment] 2022-08-03 01:05
> 

I had this problem a while ago and had to manually change the `Gemfile.lock` to revert `strscan` from `strscan (3.0.3)`back to `strscan (3.0.1)`.

Today I updated my Gemfile and am now running `rails (7.0.3.1)`. `strscan` is now `3.0.4` but the server still blew up (Passenger 'We're sorry, but something went wrong screen').

Once again, manually changing my `Gemfile.lock` to `strscan (3.0.1)` and redeploying brought me back online.

**Comment by deivid-rodriguez** [comment] 2022-08-03 09:54
I finally had a look at this using the repro instructions posted by @hurricup at https://github.com/rubygems/rubygems/issues/5542#issuecomment-1203368066. The reason why installing latest psych does not fix the issue is that `bundle install --path <path>` changes the path to look for gems to `<path>`, so even if you installed `psych-4.0.4` globally before running `bundle install --path`, it won't be loaded because it won't be present at path, so the default `psych-3.3.2` will be loaded instead (which has the `strscan` problem).

So the proper fix for this case is to make sure `psych-4.0.4` is available at `%USERPROFILE%/.local/share/gem` by running `gem install psych --user-install` before running `bundle install --path`.

This will get sorted out by itself in newer Rubies where psych 4.0.4 or higher will be the default, so I will close this.

If someone is having similar issues, please make sure you upgrade to `psych-4.0.4` and that `psych-4.0.4` is actually loaded (you can put a debugging print at the proper `psych.rb` file to make sure it's being loaded). If you still think this is a problem in RubyGems or Bundler, please open a separate issue with repro steps.

Thanks!!

**Closed by deivid-rodriguez** 2022-08-03 09:54 UTC

**Comment by Shailajarapolu95** [comment] 2022-09-20 07:16
while checking version of ruby and rails in the cmd this error is showing(Ignoring strscan-3.0.4 because its extensions are not built. Try: gem pristine strscan --version 3.0.4) what can i do

**Comment by CodeChonk** [comment] 2024-05-01 02:04
if haven't tried 

export GEM_HOME=$(ruby -e 'puts Gem.user_dir')

give it a shot, it worked for me when i was trying to use bundler to install jekyll on arcos.

https://felipec.wordpress.com/2022/08/25/fixing-ruby-gems-installation/
