### ISSUE TITLE
Windows Ruby 2.1.4 can't install any gems, can't update, nor add sources

### ISSUE THREAD

**Issue by psionatix** [rubygems/rubygems#1838] opened 2017-02-10 13:19 UTC
I'm having a problem or would like to suggest a feature.

UPDATE: The manual update said it was  successful, when trying again:
Updating installed gems
Nothing to update

However gems --version still returns 2.2.2

My current problem is after following the steps at: http://guides.rubygems.org/ssl-certificate-update/#manual-solution-to-ssl-issue - I still can't download any gems. I cannot add http://rubygems.org to the sources list either, as it has a Fetching error no name, errors specied below.

Initially following the steps at: 
http://davehaeffner.com/selenium-guidebook/install/ruby/windows/2.1/

Once I run:
gem install bundler
I get:
ERROR: Could not find a valid gem 'bundler' <>= 0), here is why:
Unable to download data from https://rubygems.org/ - no such name (https://rubygems.org/latest_specs.4.8.gz)

If I run:
gem update --system
ERROR:  While executing gem ... (Gem::RemoteFetcher::UnknownHostError)
    no such name (https://rubygems.org/specs.4.8.gz)

if I run:
gem sources -a http://rubygems.org/
I get a prompt to add an insecure source, which I press 'y' and enter, then:
ERROR:  While executing gem ... (Gem::RemoteFetcher::UnknownHostError)
    no such name (https://rubygems.org/specs.4.8.gz)
Here are my current environment details:
Windows, Ruby 2.1.4,
gem env version
2.2.2

CMD is being run as administrator.

Do I need to update? Will that fix it? If so, will the rest of the selenium guide still be compatible?

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment] 2017-03-11 18:08
This may be a duplicate of https://github.com/rubygems/rubygems/issues/1769 please check that issue for help, thanks

**Closed by bronzdoc** 2017-03-11 18:08 UTC
Labels: platform: windows
