### ISSUE TITLE
ERROR:  While executing gem ... (Encoding::InvalidByteSequenceError)

### ISSUE THREAD

**Issue by jedrekdomanski** [rubygems/rubygems#2002] opened 2017-09-01 11:29 UTC
Operating system: Windows 10
ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
```
gem install rails
ERROR:  While executing gem ... (Encoding::InvalidByteSequenceError)
    incomplete "\x00" on UTF-16LE
```
```
$ gem env version
2.6.11
```

**Comment by hsbt** [comment] 2017-09-01 11:55
I couldn't reproduce it Windows 10 Japanese edition.

```
C:\Users\hsbt>gem i rails
Fetching: i18n-0.8.6.gem (100%)
Successfully installed i18n-0.8.6
Fetching: thread_safe-0.3.6.gem (100%)
Successfully installed thread_safe-0.3.6
(snip)
Parsing documentation for sprockets-rails-3.2.1
Installing ri documentation for sprockets-rails-3.2.1
Parsing documentation for rails-5.1.3
Installing ri documentation for rails-5.1.3
Done installing documentation for i18n, thread_safe, tzinfo, concurrent-ruby, activesupport, rack, rack-test, mini_portile2, nokogiri, loofah, rails-html-sanitizer, rails-dom-testing, builder, erubi, actionview, actionpack, activemodel, arel, activerecord, globalid, activejob, mime-types-data, mime-types, mail, actionmailer, nio4r, websocket-extensions, websocket-driver, actioncable, thor, method_source, railties, bundler, sprockets, sprockets-rails, rails after 171 seconds
36 gems installed

C:\Users\hsbt>
```

**Comment by jedrekdomanski** [comment] 2017-09-01 12:15
λ systeminfo                                                                                  
                                                                                              
Host Name:                 JDOMANSKINB                                                        
OS Name:                   Microsoft Windows 10 Pro                                           
OS Version:                10.0.14393 N/A Build 14393                                         
OS Manufacturer:           Microsoft Corporation                                              
OS Configuration:          Member Workstation                                                 
OS Build Type:             Multiprocessor Free                                                
Registered Owner:          Użytkownik systemu Windows                                         
Registered Organization:                                                                      
Product ID:                00330-80000-00000-AA750                                            
Original Install Date:     04.04.2017, 15:15:42                                               
System Boot Time:          01.09.2017, 09:18:08                                               
System Manufacturer:       LENOVO                                                             
System Model:              20FJS29G00                                                         
System Type:               x64-based PC                                                       
Processor(s):              1 Processor(s) Installed.                                          
                           [01]: Intel64 Family 6 Model 78 Stepping 3 GenuineIntel ~2396 Mhz  
BIOS Version:              LENOVO N1KET21W (1.08 ), 20.04.2016                                
Windows Directory:         C:\Windows                                                         
System Directory:          C:\Windows\system32                                                
Boot Device:               \Device\HarddiskVolume2                                            
System Locale:             pl;Polski                                                          
Input Locale:              pl;Polski                                                          
Time Zone:                 (UTC+01:00) Sarajewo, Skopie, Warszawa, Zagrzeb                    
Total Physical Memory:     16 251 MB                                                          
Available Physical Memory: 7 675 MB                                                           
Virtual Memory: Max Size:  18 683 MB                                                          
Virtual Memory: Available: 4 628 MB                                                           
Virtual Memory: In Use:    14 055 MB                                                          
Page File Location(s):     C:\pagefile.sys                                                    
Domain:                    lingaro.local                                                      
Logon Server:              \\QUEZON                                                           
Hotfix(s):                 6 Hotfix(s) Installed.                                             
                           [01]: KB3186568                                                    
                           [02]: KB3186594                                                    
                           [03]: KB4013418                                                    
                           [04]: KB4022730                                                    
                           [05]: KB4023834                                                    
                           [06]: KB4022715                                                    
Network Card(s):           4 NIC(s) Installed.                                                
                           [01]: Intel(R) Dual Band Wireless-AC 8260                          
                                 Connection Name: WiFi                                        
                                 DHCP Enabled:    Yes                                         
                                 DHCP Server:     10.0.0.15                                   
                                 IP address(es)                                               
                                 [01]: 192.168.20.189                                         
                                 [02]: fe80::4c7e:8de7:c4b9:6a78                              
                           [02]: Intel(R) Ethernet Connection I219-LM                         
                                 Connection Name: Ethernet                                    
                                 Status:          Media disconnected                          
                           [03]: Bluetooth Device (Personal Area Network)                     
                                 Connection Name: Bluetooth Network Connection                
                                 Status:          Media disconnected                          
                           [04]: Fortinet Virtual Ethernet Adapter (NDIS 6.30)                
                                 Connection Name: Ethernet 2                                  
                                 Status:          Media disconnected                          
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes                                    
                           Virtualization Enabled In Firmware: No                             
                           Second Level Address Translation: Yes                              
                           Data Execution Prevention Available: Yes

**Comment by jedrekdomanski** [comment] 2017-09-04 09:19
λ gem search rails

*** REMOTE GEMS ***

ERROR:  While executing gem ... (Encoding::InvalidByteSequenceError)
    incomplete "\x00" on UTF-16LE

**Comment by jedrekdomanski** [comment] 2017-09-04 09:21
λ gem search faker                                                   
                                                                     
*** REMOTE GEMS ***                                                  
                                                                     
ERROR:  While executing gem ... (Encoding::InvalidByteSequenceError) 
    incomplete "\x00" on UTF-16LE

**Comment by jedrekdomanski** [comment] 2017-09-04 09:21
λ gem search capybara

*** REMOTE GEMS ***

ERROR:  While executing gem ... (Encoding::InvalidByteSequenceError)
    incomplete "\x00" on UTF-16LE

**Comment by segiddins** [comment] 2017-09-04 20:21
What happens if you run with `--backtrace`?

**Comment by jedrekdomanski** [comment] 2017-09-04 20:26
λ gem i faker --backtrace
ERROR:  While executing gem ... (Encoding::InvalidByteSequenceError)
    incomplete "\x00" on UTF-16LE
        C:/Ruby24-x64/lib/ruby/2.4.0/win32/registry.rb:650:in `encode'
        C:/Ruby24-x64/lib/ruby/2.4.0/win32/registry.rb:650:in `read'
        C:/Ruby24-x64/lib/ruby/2.4.0/win32/registry.rb:694:in `read_s'
        C:/Ruby24-x64/lib/ruby/2.4.0/win32/resolv.rb:104:in `block (5 levels) in get_info'
        C:/Ruby24-x64/lib/ruby/2.4.0/win32/resolv.rb:102:in `each'
        C:/Ruby24-x64/lib/ruby/2.4.0/win32/resolv.rb:102:in `find'
        C:/Ruby24-x64/lib/ruby/2.4.0/win32/resolv.rb:102:in `block (4 levels) in get_info'
        C:/Ruby24-x64/lib/ruby/2.4.0/win32/registry.rb:435:in `open'
        C:/Ruby24-x64/lib/ruby/2.4.0/win32/registry.rb:542:in `open'
        C:/Ruby24-x64/lib/ruby/2.4.0/win32/resolv.rb:101:in `block (3 levels) in get_info'
        C:/Ruby24-x64/lib/ruby/2.4.0/win32/registry.rb:612:in `each_key'
        C:/Ruby24-x64/lib/ruby/2.4.0/win32/resolv.rb:100:in `block (2 levels) in get_info'
        C:/Ruby24-x64/lib/ruby/2.4.0/win32/registry.rb:435:in `open'
        C:/Ruby24-x64/lib/ruby/2.4.0/win32/registry.rb:542:in `open'
        C:/Ruby24-x64/lib/ruby/2.4.0/win32/resolv.rb:99:in `block in get_info'
        C:/Ruby24-x64/lib/ruby/2.4.0/win32/registry.rb:435:in `open'
        C:/Ruby24-x64/lib/ruby/2.4.0/win32/registry.rb:542:in `open'
        C:/Ruby24-x64/lib/ruby/2.4.0/win32/resolv.rb:76:in `get_info'
        C:/Ruby24-x64/lib/ruby/2.4.0/win32/resolv.rb:21:in `get_resolv_info'
        C:/Ruby24-x64/lib/ruby/2.4.0/resolv.rb:966:in `default_config_hash'
        C:/Ruby24-x64/lib/ruby/2.4.0/resolv.rb:983:in `block in lazy_initialize'
        C:/Ruby24-x64/lib/ruby/2.4.0/resolv.rb:976:in `synchronize'
        C:/Ruby24-x64/lib/ruby/2.4.0/resolv.rb:976:in `lazy_initialize'
        C:/Ruby24-x64/lib/ruby/2.4.0/resolv.rb:358:in `block in lazy_initialize'
        C:/Ruby24-x64/lib/ruby/2.4.0/resolv.rb:356:in `synchronize'
        C:/Ruby24-x64/lib/ruby/2.4.0/resolv.rb:356:in `lazy_initialize'
        C:/Ruby24-x64/lib/ruby/2.4.0/resolv.rb:516:in `fetch_resource'
        C:/Ruby24-x64/lib/ruby/2.4.0/resolv.rb:510:in `each_resource'
        C:/Ruby24-x64/lib/ruby/2.4.0/resolv.rb:491:in `getresource'
        C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/remote_fetcher.rb:105:in `api_endpoint'
        C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/source.rb:47:in `api_uri'
        C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/source.rb:86:in `dependency_resolver_set'
        C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/resolver/best_set.rb:24:in `block in pick_sets'
        C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/source_list.rb:98:in `each'
        C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/source_list.rb:98:in `each_source'
        C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/resolver/best_set.rb:23:in `pick_sets'
        C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/resolver/best_set.rb:29:in `find_all'
        C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/resolver/installer_set.rb:156:in `find_all'
        C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/resolver/installer_set.rb:55:in `add_always_install'
        C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/dependency_installer.rb:474:in `resolve_dependencies'
        C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/commands/install_command.rb:194:in `install_gem'
        C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/commands/install_command.rb:255:in `block in install_gems'
        C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/commands/install_command.rb:251:in `each'
        C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/commands/install_command.rb:251:in `install_gems'
        C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/commands/install_command.rb:158:in `execute'
        C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/command.rb:310:in `invoke_with_build_args'
        C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/command_manager.rb:169:in `process_args'
        C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/command_manager.rb:139:in `run'
        C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/gem_runner.rb:55:in `run'
        C:/Ruby24-x64/bin/gem.cmd:29:in `<main>'

**Comment by ElKonrad** [comment] 2017-11-28 17:05
@jedrekdomanski, did you resolve it? Because I have exactly the same error.

**Comment by jedrekdomanski** [comment] 2017-11-28 17:07
No, I decided to screw Windows forever :D

2017-11-28 18:05 GMT+01:00 Konrad Buczkowski <notifications@github.com>:

**Comment by ElKonrad** [comment] 2017-11-28 17:12
Oh no! I can't afford that...

**Comment by tjouan** [comment] 2017-11-29 13:49
It seems related to resolving `_rubygems._tcp.rubygems.org.`  `SRV`
record (based on how I understand the trace).

Maybe the output of  `dig _rubygems._tcp.rubygems.org. SRV` would
help? (or the equivalent in similar program).

**Comment by jroland2** [comment] 2018-01-25 00:35
Has anyone happened upon a resolution to this yet?  I'm having the same issue described above.  

Also on Windows 10.
OS Version:                10.0.16299 N/A Build 16299
$ gem --version
2.6.13
$ ruby --version
ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]

It appears to be some cross platform issue with gem assuming unix/macos byte order marking.

ERROR:  While executing gem ... (Encoding::InvalidByteSequenceError)
    "\xE8\xD8" followed by "\x8E]" on UTF-16LE

$ dig _rubygems._tcp.rubygems.org. SRV

; <<>> DiG 9.10.6 <<>> _rubygems._tcp.rubygems.org. SRV
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42581
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1280
;; QUESTION SECTION:
;_rubygems._tcp.rubygems.org.   IN      SRV

;; ANSWER SECTION:
_rubygems._tcp.rubygems.org. 111 IN     SRV     0 1 80 api.rubygems.org.


Works fine on my other Windows 10 system (same OS version).
$ gem --version
2.6.8
$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]

**Comment by djberg96** [comment] 2018-01-25 02:28
@jroland2 Can you paste the output of `gem env` as well as the backtrace? Also, what shell are you using?

**Comment by jroland2** [comment] 2018-01-25 12:22
Shell is: Git bash run in ConEmu (which worked before and currently working on my other system mentioned above)

I'll have to work with backtrace and get back to you.

$ gem_env                                                                            
RubyGems Environment:                                                                    
  - RUBYGEMS VERSION: 2.6.13                                                             
  - RUBY VERSION: 2.4.2 (2017-09-14 patchlevel 198) [x64-mingw32]                        
  - INSTALLATION DIRECTORY: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0               
  - USER INSTALLATION DIRECTORY: C:/Users/J/AppData/Local/chefdk/gem/ruby/2.4.0          
  - RUBY EXECUTABLE: C:/opscode/chefdk/embedded/bin/ruby.exe                             
  - EXECUTABLE DIRECTORY: C:/opscode/chefdk/embedded/bin                                 
  - SPEC CACHE DIRECTORY: C:/Users/J/.gem/specs                                          
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData                                       
  - RUBYGEMS PLATFORMS:                                                                  
    - ruby                                                                               
    - x64-mingw32                                                                        
  - GEM PATHS:                                                                           
     - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0                                    
     - C:/Users/J/AppData/Local/chefdk/gem/ruby/2.4.0                                    
  - GEM CONFIGURATION:                                                                   
     - :update_sources => true                                                           
     - :verbose => true                                                                  
     - :backtrace => false                                                               
     - :bulk_threshold => 1000                                                           
     - "install" => "--user"                                                             
     - "update" => "--user"                                                              
  - REMOTE SOURCES:                                                                      
     - https://rubygems.org/                                                             
  - SHELL PATH:                                                                          
     - C:\Users\J\bin                                                                    
     - C:\Program Files\Git\mingw64\bin                                                  
     - C:\Program Files\Git\usr\local\bin                                                
     - C:\Program Files\Git\usr\bin                                                      
     - C:\Program Files\Git\usr\bin                                                      
     - C:\Program Files\Git\cmd                                                          
     - C:\Program Files\ConEmu\ConEmu\Scripts                                            
     - C:\Program Files\ImageMagick-7.0.6-Q16                                            
     - C:\Python36\Scripts                                                               
     - C:\Python36                                                                       
     - C:\opscode\chefdk\bin                                                             
     - C:\Users\J\AppData\Local\chefdk\gem\ruby\2.1.0\bin                                
     - C:\opscode\chefdk\embedded\bin                                                    
     - C:\opscode\chefdk\bin                                                             
     - C:\Program Files\ConEmu\ConEmu\Scripts                                            
     - C:\Program Files\ConEmu                                                           
     - C:\Program Files\ConEmu\ConEmu                                                    
     - C:\Program Files (x86)\Intel\iCLS Client                                          
     - C:\Program Files\Intel\iCLS Client                                                
     - C:\Windows\System32                                                               
     - C:\Windows                                                                        
     - C:\Windows\System32\wbem                                                          
     - C:\Windows\System32\WindowsPowerShell\v1.0                                        
     - C:\Program Files\Intel\Intel(R) Management Engine Components\DAL                  
     - C:\Program Files\Intel\Intel(R) Management Engine Components\IPT                  
     - C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL            
     - C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT            
     - C:\Program Files (x86)\QuickTime\QTSystem                                         
     - C:\Program Files (x86)\Skype\Phone                                                
     - C:\Program Files (x86)\Windows Live\Shared                                        
     - C:\ProgramData\chocolatey\bin                                                     
     - C:\HashiCorp\Vagrant\bin                                                          
     - C:\Program File                                                                   
     - C:\Program Files (x86)\Oracle\VirtualBox                                          
     - C:\Program Files\KDiff3                                                           
     - C:\Program Files (x86)\Microsoft VS Code\binC                                     
     - C:\Program Files\Git\Program Files\Oracle\VirtualBox                              
     - C:\Program Files\Oracle\VirtualBox                                                
     - C:\Program Files\Git\cmd                                                          
     - C:\Program Files\Git\mingw64\bin                                                  
     - C:\Program Files\Git\usr\bin                                                      
     - C:\Windows\System32                                                               
     - C:\Windows                                                                        
     - C:\Windows\System32\wbem                                                          
     - C:\Windows\System32\WindowsPowerShell\v1.0                                        
     - C:\Program Files\Amazon\AWSCLI                                                    
     - C:\Program Files\nodejs                                                           
     - C:\Program Files\PuTTY                                                            
     - C:\Strawberry\c\bin                                                               
     - C:\Strawberry\perl\site\bin                                                       
     - C:\Strawberry\perl\bin                                                            
     - C:\Program Files\dig\bin                                                          
     - C:\opscode\chefdk\bin                                                             
     - C:\tools\Ruby24-x64\bin                                                           
     - C:\Program Files\kdiff3                                                           
     - C:\Program Files (x86)\Microsoft VS Code\bin                                      
     - C:\Users\J\AppData\Local\Microsoft\WindowsApps                                    
     - C:\opscode\chefdk                                                                 
     - C:\RubyDevKit                                                                     
     - C:\Users\J\AppData\Roaming\npm                                                    
     - C:\tools\vault                                                                    
     - C:\Program Files\Git\usr\bin\vendor_perl                                          
     - C:\Program Files\Git\usr\bin\core_perl

**Comment by djberg96** [comment] 2018-01-25 16:22
@jroland2 Do you have the same issue using the command shell or powershell? Can you compare your shell environments between systems, e.g. charset and LC_ALL?

**Comment by jroland2** [comment] 2018-01-26 14:54
Yes, exact same issue with Command shell and Powershell.  Shell environments are the same between both systems.  Neither had LC_ALL set and have LANG=en_US.UTF-8. I tried setting LC_ALL=C but that didn't help either.

**Comment by colby-swandale** [comment] 2018-03-06 22:43
@jroland2 is this still an issue?

**Comment by luckyvalentine** [comment] 2018-03-21 06:52
Hi.  I'm getting the exact same error with the vagrant embedded ruby.  (Vagrant 2.0.1)

```
PS C:\HashiCorp\Vagrant\embedded\mingw64\bin> .\ruby gem update
Updating installed gems
ERROR:  While executing gem ... (Encoding::InvalidByteSequenceError)
    incomplete "\x00" on UTF-16LE
```
I got the same with the latest version of vagrant (2.0.3).  

This is stopping me from install vagrant plugins (which is using ruby gems).  I've been all over the system, same system different user, tried it under cygwin, powershell, cmd.exe.  All the same error.

Please help!

**Comment by luckyvalentine** [comment] 2018-03-21 06:58
It errors out while checking the registry on line 652 in file registry.rb.  Here is the output of a --debug install of a non-existent plugin .. it errors out before it even checks.  Many lines omitted ...:

```
PS C:\HashiCorp\Vagrant\embedded\mingw64\bin> vagrant plugin install test_anything_still_errors --debug
 INFO global: Vagrant version: 2.0.1
 INFO global: Ruby version: 2.4.2
 INFO global: RubyGems version: 2.6.13
 INFO global: VAGRANT_DISABLE_PLUGIN_INIT="1"
 INFO global: VAGRANT_EXECUTABLE="C:\\HashiCorp\\Vagrant\\embedded\\gems\\gems\\vagrant-2.0.1\\bin\\vagrant"
 INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="C:\\HashiCorp\\Vagrant\\embedded"
 INFO global: VAGRANT_INSTALLER_ENV="1"
 INFO global: VAGRANT_INSTALLER_VERSION="2"
 INFO global: VAGRANT_LOG="debug"
...
DEBUG bundler: Enabling user defined remote RubyGems sources
DEBUG bundler: Enabling default remote RubyGems sources
DEBUG bundler: Adding source - https://rubygems.org/
DEBUG bundler: Adding source - https://gems.hashicorp.com/
ERROR warden: Error occurred: incomplete "\x00" on UTF-16LE
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<VagrantPlugins::CommandPlugin::Action::InstallGem:0x0000000003710cc0>
 INFO warden: Recovery complete.
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x0000000004658368>
C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:652:in `encode': incomplete "\x00" on UTF-16LE (ncoding::InvalidByteSequenceError)
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:652:in `read'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:67:in `read_s'
...

```
any idea on registry.rb ?

**Comment by jroland2** [comment] 2018-04-13 13:58
Yes, still an issue for me, btw.  Kind of gave up on it and have been using my other system.  Would like to get this resolved though.  Afraid to update these tools in my other system for fear that it will break it there too.

**Comment by hsbt** [comment] 2019-05-01 00:07
There is no feedback.

**Closed by hsbt** 2019-05-01 00:07 UTC
Labels: category: install, platform: windows

**Comment by chrisroberts** [comment] 2019-05-15 14:36
Hi, we had a report about this error and I came across this issue while searching for previous reports. The error is originating from the win32 resolv code in the stdlib. After some digging into the code it appears that a value is not able to be properly read from the Windows registry and results in the encountered error. 

For more information on the registry key/location please see the comment here: https://github.com/hashicorp/vagrant/issues/10845#issuecomment-492442408

Hopefully that will help anyone else that stumbles across this on the Windows platform.

Cheers!
