### ISSUE TITLE
bundler 2.1.0 and `bin/bundle` generated by Rails 5.2 raises error

### ISSUE THREAD

**Issue by fukayatsu** [rubygems/rubygems#3279] opened 2019-12-18 07:20 UTC
I noticed one of my Rails 5.2 app could not boot after upgrading bundler to 2.1.0 from 2.0.2.
The app start puma with `bin/bundle exec puma`, I don't know why it is not just `bundle exec puma`, but it works with bundler 2.0.2 and not works with bundler 2.1.0.

Here is a repo to reproduce the issue: 
https://github.com/fukayatsu/rails-generated-bin-bundle-with-bundler-2-1-0

---

Dockerfile:

```
FROM ruby:2.6.5-alpine3.10

RUN apk add --update --no-cache build-base tzdata

WORKDIR /app
COPY Gemfile Gemfile.lock /app/
RUN gem update --system
ARG BUNDLER_VERSION_TO_INSTALL
RUN gem install bundler -v $BUNDLER_VERSION_TO_INSTALL
RUN bundle config set path 'vendor/bundle'
RUN bundle install
COPY . /app
CMD bin/bundle exec puma
```

## with bundler 2.0.2

It works fine.

```
$ docker run -p 3000:3000 --rm "$(docker build -q -f Dockerfile . --build-arg BUNDLER_VERSION_TO_INSTALL=2.0.2)"

Puma starting in single mode...
* Version 3.12.2 (ruby 2.6.5-p114), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
```

## with bundler 2.1.0

Error occurred.

```
$ docker run -p 3000:3000 --rm "$(docker build -q -f Dockerfile . --build-arg BUNDLER_VERSION_TO_INSTALL=2.1.0)"

Puma starting in single mode...
* Version 3.12.2 (ruby 2.6.5-p114), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: development
/usr/local/lib/ruby/site_ruby/2.6.0/bundler/version.rb:4: warning: already initialized constant Bundler::VERSION
/usr/local/bundle/gems/bundler-2.1.0/lib/bundler/version.rb:4: warning: previous definition of VERSION was here
/usr/local/lib/ruby/site_ruby/2.6.0/bundler/constants.rb:4: warning: already initialized constant Bundler::WINDOWS
/usr/local/bundle/gems/bundler-2.1.0/lib/bundler/constants.rb:4: warning: previous definition of WINDOWS was here
/usr/local/lib/ruby/site_ruby/2.6.0/bundler/constants.rb:5: warning: already initialized constant Bundler::FREEBSD
/usr/local/bundle/gems/bundler-2.1.0/lib/bundler/constants.rb:5: warning: previous definition of FREEBSD was here
/usr/local/lib/ruby/site_ruby/2.6.0/bundler/constants.rb:6: warning: already initialized constant Bundler::NULL
/usr/local/bundle/gems/bundler-2.1.0/lib/bundler/constants.rb:6: warning: previous definition of NULL was here
/usr/local/lib/ruby/site_ruby/2.6.0/bundler/rubygems_integration.rb:6: warning: already initialized constant Bundler::RubygemsIntegration::EXT_LOCK
/usr/local/bundle/gems/bundler-2.1.0/lib/bundler/rubygems_integration.rb:10: warning: previous definition of EXT_LOCK was here
/usr/local/lib/ruby/site_ruby/2.6.0/bundler/current_ruby.rb:12: warning: already initialized constant Bundler::CurrentRuby::KNOWN_MINOR_VERSIONS
/usr/local/bundle/gems/bundler-2.1.0/lib/bundler/current_ruby.rb:12: warning: previous definition of KNOWN_MINOR_VERSIONS was here
/usr/local/lib/ruby/site_ruby/2.6.0/bundler/current_ruby.rb:25: warning: already initialized constant Bundler::CurrentRuby::KNOWN_MAJOR_VERSIONS
/usr/local/bundle/gems/bundler-2.1.0/lib/bundler/current_ruby.rb:25: warning: previous definition of KNOWN_MAJOR_VERSIONS was here
/usr/local/lib/ruby/site_ruby/2.6.0/bundler/current_ruby.rb:27: warning: already initialized constant Bundler::CurrentRuby::KNOWN_PLATFORMS
/usr/local/bundle/gems/bundler-2.1.0/lib/bundler/current_ruby.rb:27: warning: previous definition of KNOWN_PLATFORMS was here
/usr/local/lib/ruby/site_ruby/2.6.0/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: already initialized constant Bundler::FileUtils::VERSION
/usr/local/bundle/gems/bundler-2.1.0/lib/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: previous definition of VERSION was here
/usr/local/lib/ruby/site_ruby/2.6.0/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: already initialized constant Bundler::FileUtils::Entry_::S_IF_DOOR
/usr/local/bundle/gems/bundler-2.1.0/lib/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: previous definition of S_IF_DOOR was here
/usr/local/lib/ruby/site_ruby/2.6.0/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: already initialized constant Bundler::FileUtils::Entry_::DIRECTORY_TERM
/usr/local/bundle/gems/bundler-2.1.0/lib/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: previous definition of DIRECTORY_TERM was here
/usr/local/lib/ruby/site_ruby/2.6.0/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: already initialized constant Bundler::FileUtils::OPT_TABLE
/usr/local/bundle/gems/bundler-2.1.0/lib/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: previous definition of OPT_TABLE was here
/usr/local/lib/ruby/site_ruby/2.6.0/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: already initialized constant Bundler::FileUtils::LOW_METHODS
/usr/local/bundle/gems/bundler-2.1.0/lib/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: previous definition of LOW_METHODS was here
/usr/local/lib/ruby/site_ruby/2.6.0/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: already initialized constant Bundler::FileUtils::METHODS
/usr/local/bundle/gems/bundler-2.1.0/lib/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: previous definition of METHODS was here
bundler: failed to load command: puma (/app/vendor/bundle/ruby/2.6.0/bin/puma)
ArgumentError: Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered
  /usr/local/lib/ruby/site_ruby/2.6.0/bundler/errors.rb:9:in `status_code'
  /usr/local/lib/ruby/site_ruby/2.6.0/bundler/errors.rb:20:in `<class:GemfileError>'
  /usr/local/lib/ruby/site_ruby/2.6.0/bundler/errors.rb:20:in `<module:Bundler>'
  /usr/local/lib/ruby/site_ruby/2.6.0/bundler/errors.rb:3:in `<top (required)>'
  /usr/local/lib/ruby/site_ruby/2.6.0/bundler.rb:7:in `require_relative'
  /usr/local/lib/ruby/site_ruby/2.6.0/bundler.rb:7:in `<top (required)>'
  /usr/local/lib/ruby/site_ruby/2.6.0/bundler/setup.rb:6:in `require_relative'
  /usr/local/lib/ruby/site_ruby/2.6.0/bundler/setup.rb:6:in `<top (required)>'
  /app/config/boot.rb:3:in `require'
  /app/config/boot.rb:3:in `<top (required)>'
  /app/config/application.rb:1:in `require_relative'
  /app/config/application.rb:1:in `<top (required)>'
  /app/config/environment.rb:2:in `require_relative'
  /app/config/environment.rb:2:in `<top (required)>'
  config.ru:3:in `require_relative'
  config.ru:3:in `block in <main>'
  /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
  /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
  config.ru:in `new'
  config.ru:in `<main>'
  /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:49:in `eval'
  /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:49:in `new_from_string'
  /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:40:in `parse_file'
  /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.2/lib/puma/configuration.rb:320:in `load_rackup'
  /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.2/lib/puma/configuration.rb:245:in `app'
  /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.2/lib/puma/runner.rb:147:in `load_and_bind'
  /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.2/lib/puma/single.rb:98:in `run'
  /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.2/lib/puma/launcher.rb:186:in `run'
  /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.2/lib/puma/cli.rb:80:in `run'
  /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.2/bin/puma:10:in `<top (required)>'
  /app/vendor/bundle/ruby/2.6.0/bin/puma:23:in `load'
  /app/vendor/bundle/ruby/2.6.0/bin/puma:23:in `<top (required)>'
! Unable to load application: ArgumentError: Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered
```

# Workaround

```
$ bundle binstubs bundler --force
```

or change the last line of the Dockerfile to

```
CMD bundle exec puma
```

## Rails-generated binstubs issue

> [Rails-generated binstubs are incompatible with Bundler-generated binstubs · Issue #31193 · rails/rails](https://github.com/rails/rails/issues/31193)

This fixed on Rails 6.

**Comment by deivid-rodriguez** [comment] 2020-04-03 08:36
I think this might also be fixed by #3458.

Could you double check?

**Closed** 2020-04-03 09:19 UTC
Labels: Bundler, status: triage

**Comment by deivid-rodriguez** [comment] 2020-04-03 09:21
I merged the fix.

If this is still reproduced with the referenced fix and/or workaround, feel free to reopen.

**Comment by cmirnow** [comment] 2021-11-07 10:19
I have a weird problem. Two rails-app are installed locally (ruby on rails 6.1.4.1). The first app works and updates without problems, but the second app gives these warnings after execution 'bundle update'.

The second app was previously upgraded from rails 5 to rails 6, but warnings have appeared after the last update only. I don't know if there is a correlation. Any ideas?

Reproduce:

```
$ bundle update
$ rails s
Traceback (most recent call last):
        12: from bin/rails:3:in `<main>'
        11: from bin/rails:3:in `require_relative'
        10: from /home/alex/.disk_a/Rails/Heroku/masterpro_blog/config/boot.rb:3:in `<top (required)>'
         9: from /home/alex/.rbenv/versions/2.7.4/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         8: from /home/alex/.rbenv/versions/2.7.4/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         7: from /home/alex/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/setup.rb:10:in `<top (required)>'
         6: from /home/alex/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-1.17.2/lib/bundler.rb:107:in `setup'
         5: from /home/alex/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:26:in `setup'
         4: from /home/alex/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:26:in `map'
         3: from /home/alex/.rbenv/versions/2.7.4/lib/ruby/2.7.0/forwardable.rb:235:in `each'
         2: from /home/alex/.rbenv/versions/2.7.4/lib/ruby/2.7.0/forwardable.rb:235:in `each'
         1: from /home/alex/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:31:in `block in setup'
/home/alex/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:319:in `check_for_activated_spec!': You have already activated uri 0.10.0, but your Gemfile requires uri 0.11.0. Since uri is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports uri as a default gem. (Gem::LoadError)

$ bundle update --bundler

$ rails s
/home/alex/.rbenv/versions/2.7.4/lib/ruby/2.7.0/uri/version.rb:3: warning: already initialized constant URI::VERSION_CODE
/home/alex/.disk_a/Rails/blog/vendor/bundle/ruby/2.7.0/gems/uri-0.11.0/lib/uri/version.rb:3: warning: previous definition of VERSION_CODE was here
/home/alex/.rbenv/versions/2.7.4/lib/ruby/2.7.0/uri/version.rb:4: warning: already initialized constant URI::VERSION
/home/alex/.disk_a/Rails/blog/vendor/bundle/ruby/2.7.0/gems/uri-0.11.0/lib/uri/version.rb:4: warning: previous definition of VERSION was here
/home/alex/.rbenv/versions/2.7.4/lib/ruby/2.7.0/uri/rfc2396_parser.rb:29: warning: already initialized constant URI::RFC2396_REGEXP::PATTERN::ALPHA
/home/alex/.disk_a/Rails/blog/vendor/bundle/ruby/2.7.0/gems/uri-0.11.0/lib/uri/rfc2396_parser.rb:28: warning: previous definition of ALPHA was here
/home/alex/.rbenv/versions/2.7.4/lib/ruby/2.7.0/uri/rfc2396_parser.rb:31: warning: already initialized constant URI::RFC2396_REGEXP::PATTERN::ALNUM
...............
```

**Comment by deivid-rodriguez** [comment] 2021-11-07 11:35
You're running into something similar to #5016. I hope to fix it soon.

**Comment by cmirnow** [comment] 2021-11-09 19:35
> I hope to fix it soon.

OK. Thanks! How do I know the problem has been resolved?

**Comment by deivid-rodriguez** [comment] 2021-11-10 10:56
You can subscribe to the issue I linked to to track its resolution, or subscribe to releases of this repository so you can try them out and verify whether the problem is gone.
