### ISSUE TITLE
Issue with running Rails application using Bundler 2.2.0

### ISSUE THREAD

**Issue by kaspergrubbe** [rubygems/rubygems#4142] opened 2020-12-14 12:19 UTC
### Describe the problem as clearly as you can

When I bundle and run Rails application in the production environment (configured with: `bundle config set without 'development test'`) I get the following error:

```
Could not find public_suffix-4.0.3 in any of the sources
Run `bundle install` to install missing gems.
```

### Post steps to reproduce the problem

I've created a Docker setup over here that reproduces the problem: https://github.com/kaspergrubbe/bundler220 it consists of 3 scripts:

- `build.sh` - this builds 2 docker images, one with Bundler 2.1.4 and one with Bundler 2.2.0
- `run-bundler-2.1.4.sh` - this invokes Ruby using Bundler 2.1.4
- `run-bundler-2.2.0.sh` - this invokes Ruby using Bundler 2.2.0

2.1.4 just prints 42:

```
$ bash run-bundler-2.1.4.sh
42
```

2.2.0 just prints the error:

```
$ bash run-bundler-2.2.0.sh
Could not find public_suffix-4.0.3 in any of the sources
Run `bundle install` to install missing gems.
```

I've tried a combination of Rubygems and Bundler but it seems to be related to Bundler:

Does work:
- Rubygems 3.1.4 and Bundler 2.1.4
- Rubygems 3.2.0 and Bundler 2.1.4

Doesn't work:
- Rubygems 3.1.4 and Bundler 2.2.0
- Rubygems 3.2.0 and Bundler 2.2.0

### What were you expecting to happen?

To be able to run the command without any errors.

## Environment

```
Bundler       2.2.0
  Platforms   ruby, x86_64-linux
Ruby          2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.2.0
  Gem Home    /usr/local/bundle
  Gem Path    /home/railsapp/.local/share/gem/ruby/2.4.0:/usr/local/lib/ruby/gems/2.4.0:/usr/local/bundle
  User Home   /home/railsapp
  User Path   /home/railsapp/.local/share/gem/ruby/2.4.0
  Bin Dir     /usr/local/bundle/bin
Tools         
  Git         2.20.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2020-12-10
Git SHA           d3628e5019
Released Version  true
```

## Bundler settings

```
without
  Set for your local app (/usr/local/bundle/config): [:development, :test]
path
  Set via BUNDLE_PATH: "/usr/local/bundle"
bin
  Set via BUNDLE_BIN: "/usr/local/bundle/bin"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
gemfile
  Set via BUNDLE_GEMFILE: "/app/Gemfile"
```

### Gemfile

```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.4', '>= 5.2.4.1'
# Use Puma as the app server
gem 'puma', '~> 5.1.1'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer', platforms: :ruby

# Test jemalloc compilation https://github.com/kaspergrubbe/grubruby-jemalloc/pull/38
gem 'sq_mini_racer'

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'
end
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.2.4.1)
      actionpack (= 5.2.4.1)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailer (5.2.4.1)
      actionpack (= 5.2.4.1)
      actionview (= 5.2.4.1)
      activejob (= 5.2.4.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.2.4.1)
      actionview (= 5.2.4.1)
      activesupport (= 5.2.4.1)
      rack (~> 2.0, >= 2.0.8)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.2.4.1)
      activesupport (= 5.2.4.1)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    activejob (5.2.4.1)
      activesupport (= 5.2.4.1)
      globalid (>= 0.3.6)
    activemodel (5.2.4.1)
      activesupport (= 5.2.4.1)
    activerecord (5.2.4.1)
      activemodel (= 5.2.4.1)
      activesupport (= 5.2.4.1)
      arel (>= 9.0)
    activestorage (5.2.4.1)
      actionpack (= 5.2.4.1)
      activerecord (= 5.2.4.1)
      marcel (~> 0.3.1)
    activesupport (5.2.4.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    archive-zip (0.12.0)
      io-like (~> 0.3.0)
    arel (9.0.0)
    bindex (0.8.1)
    bootsnap (1.4.5)
      msgpack (~> 1.0)
    builder (3.2.4)
    byebug (11.0.1)
    capybara (3.30.0)
      addressable
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (~> 1.5)
      xpath (~> 3.2)
    childprocess (3.0.0)
    chromedriver-helper (2.1.1)
      archive-zip (~> 0.10)
      nokogiri (~> 1.8)
    coffee-rails (4.2.2)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    concurrent-ruby (1.1.5)
    crass (1.0.5)
    erubi (1.9.0)
    execjs (2.7.0)
    ffi (1.11.3)
    globalid (0.4.2)
      activesupport (>= 4.2.0)
    i18n (1.7.0)
      concurrent-ruby (~> 1.0)
    io-like (0.3.0)
    jbuilder (2.9.1)
      activesupport (>= 4.2.0)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.4.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (0.3.3)
      mimemagic (~> 0.3.2)
    method_source (0.9.2)
    mimemagic (0.3.3)
    mini_mime (1.0.2)
    mini_portile2 (2.4.0)
    minitest (5.13.0)
    msgpack (1.3.1)
    nio4r (2.5.2)
    nokogiri (1.10.8)
      mini_portile2 (~> 2.4.0)
    public_suffix (4.0.3)
    puma (5.1.1)
      nio4r (~> 2.0)
    rack (2.0.8)
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (5.2.4.1)
      actioncable (= 5.2.4.1)
      actionmailer (= 5.2.4.1)
      actionpack (= 5.2.4.1)
      actionview (= 5.2.4.1)
      activejob (= 5.2.4.1)
      activemodel (= 5.2.4.1)
      activerecord (= 5.2.4.1)
      activestorage (= 5.2.4.1)
      activesupport (= 5.2.4.1)
      bundler (>= 1.3.0)
      railties (= 5.2.4.1)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.3.0)
      loofah (~> 2.3)
    railties (5.2.4.1)
      actionpack (= 5.2.4.1)
      activesupport (= 5.2.4.1)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.19.0, < 2.0)
    rake (13.0.1)
    rb-fsevent (0.10.3)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    regexp_parser (1.6.0)
    ruby_dep (1.5.0)
    rubyzip (2.0.0)
    sass (3.7.4)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sass-rails (5.1.0)
      railties (>= 5.2.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    selenium-webdriver (3.142.7)
      childprocess (>= 0.5, < 4.0)
      rubyzip (>= 1.2.2)
    spring (2.1.0)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sq_mini_racer (0.3.1.0.1)
    thor (1.0.1)
    thread_safe (0.3.6)
    tilt (2.0.10)
    turbolinks (5.2.1)
      turbolinks-source (~> 5.2)
    turbolinks-source (5.2.0)
    tzinfo (1.2.6)
      thread_safe (~> 0.1)
    uglifier (4.2.0)
      execjs (>= 0.3.0, < 3)
    web-console (3.7.0)
      actionview (>= 5.0)
      activemodel (>= 5.0)
      bindex (>= 0.4.0)
      railties (>= 5.0)
    websocket-driver (0.7.1)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.4)
    xpath (3.2.0)
      nokogiri (~> 1.8)

PLATFORMS
  ruby

DEPENDENCIES
  bootsnap (>= 1.1.0)
  byebug
  capybara (>= 2.15)
  chromedriver-helper
  coffee-rails (~> 4.2)
  jbuilder (~> 2.5)
  listen (>= 3.0.5, < 3.2)
  puma (~> 5.1.1)
  rails (~> 5.2.4, >= 5.2.4.1)
  sass-rails (~> 5.0)
  selenium-webdriver
  spring
  spring-watcher-listen (~> 2.0.0)
  sq_mini_racer
  turbolinks (~> 5)
  uglifier (>= 1.3.0)
  web-console (>= 3.3.0)

BUNDLED WITH
   2.1.4
```

## Environment

```
Bundler       2.2.0
  Platforms   ruby, x86_64-linux
Ruby          2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.2.0
  Gem Home    /usr/local/bundle
  Gem Path    /home/railsapp/.local/share/gem/ruby/2.4.0:/usr/local/lib/ruby/gems/2.4.0:/usr/local/bundle
  User Home   /home/railsapp
  User Path   /home/railsapp/.local/share/gem/ruby/2.4.0
  Bin Dir     /usr/local/bundle/bin
Tools         
  Git         2.20.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2020-12-10
Git SHA           d3628e5019
Released Version  true
```

## Bundler settings

```
path
  Set via BUNDLE_PATH: "/usr/local/bundle"
bin
  Set via BUNDLE_BIN: "/usr/local/bundle/bin"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
gemfile
  Set via BUNDLE_GEMFILE: "/app/Gemfile"
```

### Gemfile

```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.4', '>= 5.2.4.1'
# Use Puma as the app server
gem 'puma', '~> 5.1.1'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer', platforms: :ruby

# Test jemalloc compilation https://github.com/kaspergrubbe/grubruby-jemalloc/pull/38
gem 'sq_mini_racer'

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'
end
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.2.4.1)
      actionpack (= 5.2.4.1)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailer (5.2.4.1)
      actionpack (= 5.2.4.1)
      actionview (= 5.2.4.1)
      activejob (= 5.2.4.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.2.4.1)
      actionview (= 5.2.4.1)
      activesupport (= 5.2.4.1)
      rack (~> 2.0, >= 2.0.8)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.2.4.1)
      activesupport (= 5.2.4.1)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    activejob (5.2.4.1)
      activesupport (= 5.2.4.1)
      globalid (>= 0.3.6)
    activemodel (5.2.4.1)
      activesupport (= 5.2.4.1)
    activerecord (5.2.4.1)
      activemodel (= 5.2.4.1)
      activesupport (= 5.2.4.1)
      arel (>= 9.0)
    activestorage (5.2.4.1)
      actionpack (= 5.2.4.1)
      activerecord (= 5.2.4.1)
      marcel (~> 0.3.1)
    activesupport (5.2.4.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    archive-zip (0.12.0)
      io-like (~> 0.3.0)
    arel (9.0.0)
    bindex (0.8.1)
    bootsnap (1.4.5)
      msgpack (~> 1.0)
    builder (3.2.4)
    byebug (11.0.1)
    capybara (3.30.0)
      addressable
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (~> 1.5)
      xpath (~> 3.2)
    childprocess (3.0.0)
    chromedriver-helper (2.1.1)
      archive-zip (~> 0.10)
      nokogiri (~> 1.8)
    coffee-rails (4.2.2)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    concurrent-ruby (1.1.5)
    crass (1.0.5)
    erubi (1.9.0)
    execjs (2.7.0)
    ffi (1.11.3)
    globalid (0.4.2)
      activesupport (>= 4.2.0)
    i18n (1.7.0)
      concurrent-ruby (~> 1.0)
    io-like (0.3.0)
    jbuilder (2.9.1)
      activesupport (>= 4.2.0)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.4.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (0.3.3)
      mimemagic (~> 0.3.2)
    method_source (0.9.2)
    mimemagic (0.3.3)
    mini_mime (1.0.2)
    mini_portile2 (2.4.0)
    minitest (5.13.0)
    msgpack (1.3.1)
    nio4r (2.5.2)
    nokogiri (1.10.8)
      mini_portile2 (~> 2.4.0)
    public_suffix (4.0.3)
    puma (5.1.1)
      nio4r (~> 2.0)
    rack (2.0.8)
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (5.2.4.1)
      actioncable (= 5.2.4.1)
      actionmailer (= 5.2.4.1)
      actionpack (= 5.2.4.1)
      actionview (= 5.2.4.1)
      activejob (= 5.2.4.1)
      activemodel (= 5.2.4.1)
      activerecord (= 5.2.4.1)
      activestorage (= 5.2.4.1)
      activesupport (= 5.2.4.1)
      bundler (>= 1.3.0)
      railties (= 5.2.4.1)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.3.0)
      loofah (~> 2.3)
    railties (5.2.4.1)
      actionpack (= 5.2.4.1)
      activesupport (= 5.2.4.1)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.19.0, < 2.0)
    rake (13.0.1)
    rb-fsevent (0.10.3)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    regexp_parser (1.6.0)
    ruby_dep (1.5.0)
    rubyzip (2.0.0)
    sass (3.7.4)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sass-rails (5.1.0)
      railties (>= 5.2.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    selenium-webdriver (3.142.7)
      childprocess (>= 0.5, < 4.0)
      rubyzip (>= 1.2.2)
    spring (2.1.0)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sq_mini_racer (0.3.1.0.1)
    thor (1.0.1)
    thread_safe (0.3.6)
    tilt (2.0.10)
    turbolinks (5.2.1)
      turbolinks-source (~> 5.2)
    turbolinks-source (5.2.0)
    tzinfo (1.2.6)
      thread_safe (~> 0.1)
    uglifier (4.2.0)
      execjs (>= 0.3.0, < 3)
    web-console (3.7.0)
      actionview (>= 5.0)
      activemodel (>= 5.0)
      bindex (>= 0.4.0)
      railties (>= 5.0)
    websocket-driver (0.7.1)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.4)
    xpath (3.2.0)
      nokogiri (~> 1.8)

PLATFORMS
  ruby
  x86_64-linux

DEPENDENCIES
  bootsnap (>= 1.1.0)
  byebug
  capybara (>= 2.15)
  chromedriver-helper
  coffee-rails (~> 4.2)
  jbuilder (~> 2.5)
  listen (>= 3.0.5, < 3.2)
  puma (~> 5.1.1)
  rails (~> 5.2.4, >= 5.2.4.1)
  sass-rails (~> 5.0)
  selenium-webdriver
  spring
  spring-watcher-listen (~> 2.0.0)
  sq_mini_racer
  turbolinks (~> 5)
  uglifier (>= 1.3.0)
  web-console (>= 3.3.0)

BUNDLED WITH
   2.2.0
```

**Comment by simi** [comment] 2020-12-14 12:38
Seems similar to https://github.com/rubygems/rubygems/issues/4131. Fix should be present in master https://github.com/rubygems/rubygems/pull/4140 and released soon (https://github.com/rubygems/rubygems/pull/4141).

Can you check with master bundler?

**Comment by kaspergrubbe** [comment] 2020-12-14 12:47
@simi I can most certainly give that a go, can you tell me how I install bundler from master?

**Comment by simi** [comment] 2020-12-14 12:49
@kaspergrubbe you can find some suggestion at https://github.com/rubygems/rubygems/issues/4128#issuecomment-744224478 and following comments.

**Comment by deivid-rodriguez** [comment] 2020-12-14 12:53
I did try to repro this by modifying the given Dockerfile to install the master branch and it _does not_ seem fixed for me :disappointed:.

**Comment by kaspergrubbe** [comment] 2020-12-14 12:55
@deivid-rodriguez Thanks for testing it out, it's above my bundler knowledge to get Bundler from master running.

**Comment by deivid-rodriguez** [comment] 2020-12-14 13:01
I changed the Dockerfile like this:

```diff
diff --git a/Dockerfile b/Dockerfile
index 9a8648e..ed97e70 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -30,7 +30,6 @@ RUN set -eux && \
   } >> /usr/local/etc/gemrc
 
 ARG BUNDLER_VERSION
-ENV BUNDLER_VERSION=${BUNDLER_VERSION}
 
 ENV RUBY_MAJOR=2.4
 ENV RUBY_VERSION=2.4.4
@@ -108,7 +107,6 @@ RUN set -eux && \
   ruby -e "puts Gem::Version.create(Gem::VERSION)" && \
   ruby -e 'exit(Gem::Version.create(ENV["RUBYGEMS_VERSION"]) >= Gem::Version.create(Gem::VERSION))' && \
   gem update --system "$RUBYGEMS_VERSION" && \
-  gem install bundler --version "$BUNDLER_VERSION" --force && \
   rm -r /root/.gem/ && \
 # verify we have no "ruby" packages installed
   ! dpkg -l | grep -i ruby && \
@@ -142,6 +140,8 @@ WORKDIR /app
 
 COPY . /app
 
+RUN git clone https://github.com/rubygems/rubygems -b release/bundler_2.2.1_rubygems_3.2.1 && cd rubygems && ruby setup.rb
+
 RUN bundle config set jobs 8
 RUN bundle config set without 'development test'
 RUN bundle install
```

**Comment by deivid-rodriguez** [comment] 2020-12-14 13:32
Oh, so without having actually verified it, I'm pretty sure this is a regression from https://github.com/rubygems/rubygems/pull/3666.

In your `Dockerfile`, you first run `bundle config without 'development test'`, and then create a user and make the application run under that user.

Before the bug fix I'm referencing, bundler would unintentionally copy the `global` configuration being set by your `bundle config set` command to the application configuration (which in this case is a fixed location, because it's controlled by the `BUNDLE_APP_CONFIG` environment variable).

After that bug fix, the command only sets the configuration to your root's user home location. `bundle install` works fine, but since after `bundle install` that you change the user to run the application, the `bundle exec` command no longer sees the configuration is thus tries to require a development only gem.

So:

### Workarounds:

* Move all bundle commands to be run by the user that will run the app.
* Change `bundle config set` commands to be `bundle config set --local`, so that the configuration is persisted to the `BUNDLE_APP_CONFIG` location.

Can you confirm that those workarounds work for you, @kaspergrubbe?

### Potential changes on our side:

I believe most users assume `bundle config` is local by default, so a potential change in bundler that would fix this problem in particular would be to make that change. I'm totally in favour of making that change (which @eregon suggested [here](https://github.com/rubygems/rubygems/issues/3926)), but I haven't yet done it for backwards compatibility reasons. However, it seems like the potential for breaking things is small (it would be much bigger if the change was the reverse), so we may as well call it a bug fix and just do it :man_shrugging:.

Thoughts?

**Comment by kaspergrubbe** [comment] 2020-12-14 13:43
@deivid-rodriguez Thank you so much for your detailed explanation, it makes total sense now. Using `--local` works for me, and I've just tested it. 

I agree with your assesment that users assume bundle config were local by default, but I don't know about the implications, and I am a mere user, and changing things around bundler must be a daunting task that I don't envy!

**Comment by deivid-rodriguez** [comment] 2020-12-14 13:43
Another possibility is that maybe my "bug fix" was just removing a feature, the feature being that you can have a global "without" configuration and `bundle install` will automatically apply that to each particular application if nothing else is set locally. It kind of makes sense, and it sounds that I didn't think through that "bug fix" properly, but if we make the change to make configuration local by default, it wouldn't be needed.

An issue with changing the default is that some configurations have the opposite meaning: they never make sense as local configurations. For example, all configurations gems related to gem creation.

Maybe each setting should have a different local/global default, and we should document that?

**Comment by deivid-rodriguez** [comment] 2020-12-14 13:44
> I agree with your assesment that users assume bundle config were local by default, but I don't know about the implications, and I am a mere user, and changing things around bundler must be a daunting task that I don't envy!

Absolutely :sweat_smile:

**Comment by deivid-rodriguez** [comment] 2020-12-14 13:58
Actually in https://github.com/rubygems/rubygems/issues/3926 @eregon suggestion works just fine for all settings I believe.

If run on an application context, local should be the default. If run outside of an application context, then global should be the default since there's no other alternative really :smiley:.

**Comment by jrochkind** [comment] 2020-12-15 13:56
I had assumed `bundle config` was local and project-specific (regardless of user) by default, and am surprised to hear it was not! So I could see it being a bugfix to make it so. 

With the deprecation (/removal?) of flags like `--deployment` and `--path` for using `bundle config`, a lot more people have been and are going to start using `bundle config`.  It seems wrong to me to suggest `bundle config` (global?) as a replacement for `--deployment` and `--path` (which were local).  Perhaps it should be more complicit that the suitable replacement is `bundle config --local` -- it makes sense to me that this should maybe be default. 

At the least, regardless of any code changes, I think it could benefit from more documentation and marketing, including example scenario "tutorial" or "guide" kind of documentation for how you are intended to use `bundle config` as a replacement for `--deployment` and `--path`, and what the implications of it are in various scenarios, including local/global and what that means/how that works. 

I'm actually shocked to find out I had such a misunderstanding about it!  I assumed that I had understood `bundle config set` was a good analogous replacement for `--deployment` and `--path` so was local, I had missed that I should really be doing `--local`.

**Comment by deivid-rodriguez** [comment] 2020-12-15 14:02
We already fixed the deprecation message, did it not make it to bundler 2.2?

**Comment by deivid-rodriguez** [comment] 2020-12-15 14:08
I think many of us have been surprised similarly, yeah :sob:. I did check git history and the current default is intentional although it's not explained why.

**Comment by iain** [comment] 2020-12-15 16:47
Just to chiming with what this unexpected change meant for me, so if other people see

```Dockerfile
FROM ruby:2.7.2-alpine3.12

# copying over the gems and installing them separately to build a Docker cache layer independent of other code changes
COPY Gemfile       /tmp/Gemfile
COPY Gemfile.lock  /tmp/Gemfile.lock
WORKDIR /tmp
RUN set -ex \
 && bundle config set without development test \
 && bundle install \
 && rm -rf /usr/local/bundle/cache

# copy over the rest of the source code
COPY --chown=app:app . /src
USER app
WORKDIR /src
RUN set -ex \
 && bundle config set without development test \ # <-- this is new
 && bootsnap precompile
```

I had to add the second line of `bundle config set without development test` with this new Bundler version that ran as the app user.

Honestly it is becoming increasingly confusing on what config options are available when, since `bundle install --without` is also deprecated. Maybe that's just a function of me not being fully up to date with all changes and plans.

**Comment by deivid-rodriguez** [comment] 2020-12-15 19:44
Hi @iain, it sounds like this thread slightly deviating from the original issue has created some confusion for you. I'll try to clarify it. This is a regression introduced in bundler 2.2.0. I'll fix this regression and release a new patch level version so that you can upgrade and your `Dockerfile` can still work without any changes.

**Comment by deivid-rodriguez** [comment] 2020-12-15 20:11
I created #4154 to restore the previous behaviour for the time being. I'll try to release it tomorrow.

**Comment by deivid-rodriguez** [comment] 2020-12-15 20:22
If someone can install https://github.com/rubygems/rubygems/issues/4142 and verify it fixes the problem on your `Dockerfile`, I'd appreciate it.

**Comment by deivid-rodriguez** [comment] 2020-12-16 09:51
I did try the initial Dockerfile given in this issue and the problem seems fixed :+1:. I'll get it ready for a release now.

I'm also wondering about your issue @iain, because I would have assumesd the workarounds given in this thread would've worked for you (like changing `bundle config set without development test` to `bundle config set --local without development test`). However, you applied a different workaround. I guess maybe you only read the last 2/3 posts in the thread? That could also explain your confusion.

**Comment by deivid-rodriguez** [comment] 2020-12-16 14:16
Pull request is merged and I will release it later today.

**Closed** 2020-12-16 14:15 UTC
Labels: Bundler

**Comment by iain** [comment] 2020-12-16 15:34
@deivid-rodriguez  Setting the `--local` option works too, I just found my workaround before I found this ticket. Sorry that I wasn't clearer on that.

**Comment by kaspergrubbe** [comment] 2020-12-16 16:34
Thank you for your time and explanations @deivid-rodriguez !

**Comment by deivid-rodriguez** [comment] 2020-12-16 21:26
Sorry I couldn't make it to release today in the end. Tomorrow it will be out for sure.
