### ISSUE TITLE
Errno::EACCES: Permission denied @ rb_file_s_symlink - (spec/support/../../.mod/drivers-evergreen-tools/.evergreen/ocsp, C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mongo-2.17.2/spec/support/ocsp)

### ISSUE THREAD

**Issue by arjunrdesai** [rubygems/rubygems#5768] opened 2022-07-25 12:11 UTC
```
Errno::EACCES: Permission denied @ rb_file_s_symlink - (spec/support/../../.mod/drivers-evergreen-tools/.evergreen/ocsp, C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mongo-2.17.2/spec/support/ocsp)
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:447:in `symlink'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:447:in `block (2 levels) in extract_tar_gz'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package/tar_reader.rb:65:in `each'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:413:in `block in extract_tar_gz'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:525:in `block in open_tar_gz'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:522:in `wrap'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:522:in `open_tar_gz'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:412:in `extract_tar_gz'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:392:in `block (2 levels) in extract_files'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package/tar_reader.rb:65:in `each'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:389:in `block in extract_files'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package/file_source.rb:29:in `open'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package/file_source.rb:29:in `with_read_io'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:386:in `extract_files'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/installer.rb:860:in `extract_files'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/rubygems_gem_installer.rb:26:in `install'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/source/rubygems.rb:207:in `install'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/installer/gem_installer.rb:54:in `install'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'

  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/worker.rb:62:in `apply_func'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/worker.rb:57:in `block in process_queue'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/worker.rb:54:in `loop'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/worker.rb:54:in `process_queue'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

Errno::EACCES: Permission denied @ rb_file_s_symlink - (spec/support/../../.mod/drivers-evergreen-tools/.evergreen/ocsp, C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mongo-2.17.2/spec/support/ocsp)
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:447:in `symlink'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:447:in `block (2 levels) in extract_tar_gz'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package/tar_reader.rb:65:in `each'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:413:in `block in extract_tar_gz'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:525:in `block in open_tar_gz'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:522:in `wrap'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:522:in `open_tar_gz'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:412:in `extract_tar_gz'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:392:in `block (2 levels) in extract_files'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package/tar_reader.rb:65:in `each'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:389:in `block in extract_files'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package/file_source.rb:29:in `open'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package/file_source.rb:29:in `with_read_io'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:386:in `extract_files'
  C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/installer.rb:860:in `extract_files'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/rubygems_gem_installer.rb:26:in `install'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/source/rubygems.rb:207:in `install'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/installer/gem_installer.rb:54:in `install'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'

  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/worker.rb:62:in `apply_func'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/worker.rb:57:in `block in process_queue'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/worker.rb:54:in `loop'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/worker.rb:54:in `process_queue'
  C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'


```

## Environment

```
Bundler       2.3.18
  Platforms   ruby, x64-mingw32
Ruby          2.7.2p137 (2020-10-01 revision 5445e0435260b449decf2ac16f9d09bae3cafe72) [x64-mingw32]
  Full Path   C:/Ruby27-x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      3.3.18
  Gem Home    C:/Ruby27-x64/lib/ruby/gems/2.7.0
  Gem Path    C:/Users/arjun/.gem/ruby/2.7.0;C:/Ruby27-x64/lib/ruby/gems/2.7.0
  User Home   C:/Users/arjun
  User Path   C:/Users/arjun/.gem/ruby/2.7.0
  Bin Dir     C:/Ruby27-x64/bin
OpenSSL
  Compiled    OpenSSL 1.1.1g  21 Apr 2020
  Loaded      OpenSSL 1.1.1h  22 Sep 2020
  Cert File   C:/Ruby27-x64/ssl/cert.pem
  Cert Dir    C:/Ruby27-x64/ssl/certs
Tools
  Git         2.36.1.windows.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-07-14
Git SHA           fc31b7f7d9
Released Version  true
```

### Gemfile

```ruby
source 'http://rubygems.org'

eval_gemfile File.expand_path(File.join(File.dirname(__FILE__), '../server/Gemfile'))
```

### ../server/Gemfile

```ruby
source 'http://rubygems.org'
ruby '~>2.7.0'

# unclear if this will actually force this version of rubygems to be used
# if not, run the following command to change system gem version:
# gem update --system 2.7.8
# gem 'rubygems-update', '2.7.8'

gem 'rails', '~> 6.1.3'
gem 'rake', '~> 13.0'

# added for support of the project rakefile
gem 'colored'

# data modules
gem 'jbuilder', '~> 2.11.2'
gem 'nokogiri', '~> 1.11.7'
gem 'rubyzip', '~> 2.3.0'
gem 'tzinfo-data', '~>1.2021.1'

# database modules

gem 'mongoid', '7.2.1'
#gem 'mongoid-paperclip'
# forked gem is neccessary as mongoid-paperclip relies on mimemagic which now requires freedesktop.org.xml at run time"
gem 'mongoid-paperclip', :github => 'tijcolem/mongoid-paperclip', :ref => 'master'
# Once this PR is merged (https://github.com/kreeti/kt-paperclip/pull/54) and released change to gem version
gem 'kt-paperclip', :github => 'tijcolem/kt-paperclip', :ref => 'use-marcel'
#gem 'paperclip'

# R
gem 'rserve-simpler', '~> 0.0.6'

# net-*
gem 'net-http-persistent', '~> 4.0.1'
gem 'net-scp', '~> 1.2.1'
gem 'net-sftp', '~> 3.0.0'
gem 'net-ssh', '~> 6.1.0'

# other useful gems
gem 'parallel', '~> 1.19.1'
gem 'sys-filesystem', '~> 1.4.1'

# web ui
# gem 'will_paginate'
gem 'jquery-rails', '~> 4.4.0'
gem 'kaminari', '~> 1.2.1'
gem 'kaminari-mongoid', '~> 1.0.1'

# job queuing
gem 'daemons', '~> 1.3.1'

# Gems used only for assets and not required
# in production environments by default.
gem 'bootstrap-sass', '~> 3.4.1'
gem 'coffee-rails', '~> 5.0.0'
gem 'sass', '~> 3.7.4'
gem 'sass-rails', '~> 6.0.0'
gem 'sprockets-rails', '~> 3.2.2'
gem 'uglifier', '~> 4.2.0'

# don't try to install sassc 2.
gem 'roo', '~> 2.8.3'
gem 'sassc', '~> 2.4.0'

# For workers - and other dependencies for measures
## Commonly update gems for testing and development

gem 'openstudio-workflow', '= 2.3.1'
#gem 'openstudio-analysis', :github => 'NREL/OpenStudio-analysis-gem', :ref => '270'
gem 'openstudio-analysis', '= 1.2.0'

# Remove urbanopt cli gems for minor for releases as they use different versions of ext gems
gem 'urbanopt-cli', '= 0.8.0'
#gem 'urbanopt-reopt', '= 0.8.0'

## End commonly updated gems

gem 'openstudio-aws'

# libxml 3.2.0 failing on windows
gem 'bson', '~> 4.12.0' # bson 4.6.0 requires ruby >= 2.3.0
#gem 'libxml-ruby'
gem 'msgpack', '~> 1.4.2'
gem 'multi_json', '~> 1.15.0'
gem 'nio4r', '~> 2.5.7'
gem 'rest-client', '~> 2.1.0'

# add to Gemfile to make available to Ruby scripts running via initialize/finalize scripts
gem 'rubyXL', '~> 3.4.17'

# linux based js runtime libraries
if RUBY_PLATFORM =~ /linux/
  gem 'execjs', '=2.7.0'
  gem 'libv8', '=3.16.14.19'
  gem 'therubyracer', '=0.12.3'
elsif RUBY_PLATFORM =~ /darwin/
  gem 'execjs', github: 'NREL/execjs'
end

# The only resque only is :docker, :docker-dev, :production
group :development, :docker, :'docker-dev', :'docker-test', :production, :test do
  gem 'redis', '~> 4.2.5'
  gem 'redis-namespace', '~> 1.8.1'
  gem 'resque', '~> 2.0.0'
  gem 'resque-web', '~> 0.0.12', require: 'resque_web'
end

group :development, :'docker-test', :test, :local, :'local-test' do
  gem 'delayed_job_mongoid', '~> 2.3.1'
end

group :development, :test do
  gem 'better_errors', '~> 2.9.1'
  gem 'meta_request', '~> 0.7.2'

  gem 'capybara', '~> 3.35.3'
  gem 'coveralls', '0.7.1', require: false
  gem 'public_suffix', '~> 4.0.6'
  gem 'puma', '~> 5.6.0' # used by capybara
  gem 'rspec', '~> 3.10.0'
  gem 'rspec-rails', '~> 5.0.1'
  gem 'rspec-retry', '~> 0.6.2'
  gem 'ruby-prof', '~> 1.4.3'
  gem 'selenium-webdriver', '~> 3.142.7'

  gem 'psych', '~> 3.3.1'
  gem 'rubocop', '~> 1.15.0'
  gem 'rubocop-checkstyle_formatter', '~> 0.4.0'
  gem 'rubocop-rspec', '~> 1.26.0'

  gem 'ci_reporter', '~> 2.0.0'
  gem 'factory_bot_rails', '~> 6.1.0'
  gem 'mongoid-rspec', '~> 4.1.0'
  gem 'rspec-html-matchers', '~> 0.9.4'

  gem 'json-schema', '~> 2.8.1'
end
```

### Gemfile.lock

```
<No E:/Github/OpenStudio-server/bin/Gemfile.lock found>
```

**Comment by deivid-rodriguez** [comment] 2022-07-25 12:17
Thanks for your report @arjunrdesai. Could you set up Github Actions on a Windows environment that reproduces this issue and share the logs?

**Comment by deivid-rodriguez** [comment] 2022-08-01 18:45
Milestone added because the keyboard on my WIndows machine is broken :rofl:. I managed to repro this, will try to fix it!

**Comment by deivid-rodriguez** [comment] 2022-08-01 19:26
OK, so I think this is not about the symlink being broken, which is something we could warn about in any case. But about symlinks not being enabled on some Windows. For example, I can reproduce locally on my WIndows VM, but this does not reproduce on GIthub Actions. 

@MSP-Greg Am I on the right track? Is there an easy command that can be run to enable symlink support? If there is, I think a good resolution for this issue would be to rescue this error and show a proper message explaining the problem and how to resolve it.

**Comment by MSP-Greg** [comment] 2022-08-01 21:28
> Am I on the right track?

Yes.  The GitHub Actions servers are setup like many servers, in that they run as a full admin.  Most desktops run as what might be considered a 'partial' admin.

Or, when working on my desktop, anytime I need a symlink, I have to open a terminal using 'Run as Administrator'.

When I was writing a lot of Windows desktop code (a long time ago), I configured my user account as a standard user, since a lot of desktop users are setup that way.

I've never had a need to figure out how to do it in code.  Or, whether one can elevate privileges in code...

**Comment by deivid-rodriguez** [comment] 2022-08-02 07:09
I see, thanks for the insights!

**Comment by deivid-rodriguez** [comment] 2022-08-02 11:38
Alright, so #5801 is not a general fix for this, we'd need to rescue the error a print a proper message. But will fix this particular problem when the symlink is broken but not attempting to install it at all.

**Comment by MSP-Greg** [comment] 2022-08-02 14:47
I can also repo locally (native Windows 11) with `gem install mongo`.

If I run it in a admin terminal/console, mongo installs, but the symlink's realpath doesn't exist.  Or:

```ruby
# fldr is mongo-2.18.1 gem folder

File.symlink? "#{fldr}/spec/support/ocsp"    #-> true
File.realpath "#{fldr}/spec/support/ocsp"    #-> <fldr>/spec/support/spec (Errno::ENOENT)
```

**Closed** 2022-08-04 04:36 UTC
Labels: Bundler

**Comment by voxik** [comment] 2022-08-10 17:23
I don't think this is good change. If the symlink is dangling after installation of gem A, it does not mean that gem B is not fixing the symlink. I am not Windows expert, but the original scenario was perfectly fine for Linux.

You can argue, that gems have to be installable on every platform, but I don't think this is to be decided by RubyGems. And if it should be, then the dangling symlinks could be probably checked during packaging of the gem. But it does not mean that the symlinks might not be dangling during packaging for a reason ....

**Comment by deivid-rodriguez** [comment] 2022-08-10 17:26
I see, so some packagers may be intentionally including dangling symlinks with their gems for some reason?

I actually thought you would fancy this change because you yourself contributed the same kind of change, but for gem executables, a while ago.

**Comment by voxik** [comment] 2022-08-10 17:35
Previously, AFAIR, RubyGems did some assumptions and I tried to remove as much assumptions as possible. [This](1393e7ccc5f3e5f3c3a02362c69de65e38a3e9f5) is the commit in question I believe. The comment says: "don't touch symlink references. If they are wrong, it is upstream failure."

**Comment by deivid-rodriguez** [comment] 2022-08-10 17:45
You're right, yours was a packaging change, not an installation change. We were already warning dangling symlink executables before https://github.com/rubygems/rubygems/pull/2836.

So, I'm re-reading your first comment and what you are saying is that some gem A might intentionally install a dangling symlink to a gem B, which will no longer be dangling once B is installed? Uggh.

**Comment by voxik** [comment] 2022-08-10 18:55
> So, I'm re-reading your first comment and what you are saying is that some gem A might intentionally install a dangling symlink to a future gem B install location, which will no longer be dangling once B is installed? Uggh.

Yes. However, I am not aware of any real life example. But why not? It might even not be gem B, but some other package/file/whatever. Symlinks are very handy way to tweak system in very interesting ways and I'd be unhappy see such cases go away. But if this is desired after all, then this should have been caught during packaging already (ignoring the backward compatibility for the moment).

**Comment by deivid-rodriguez** [comment] 2022-08-10 19:03
The good thing about catching this at install time is that we avoid it regardless of which version of RubyGems packaged the gem (with this change, or not). Also we can't change existing gems, so doing this here helps with the problem reported here of making this gem installable on Windows.

I guess we'll just wait for someone to want to do what you mentioned and then decide whether it's a valid use case or not.
