### ISSUE TITLE
SSL error, not encountered before now suddenly can't install gems

### ISSUE THREAD

**Issue by jjen6894** [rubygems/rubygems#1778] opened 2016-11-13 14:45 UTC
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)
 
I have been asking around but any help would be appreciated guys, thanks.

**Comment by bronzdoc** [comment] 2016-11-13 16:14
This is a duplicate of https://github.com/rubygems/rubygems/issues/1758 please check the provided solutions in that thread, thanks.

**Closed by bronzdoc** 2016-11-13 16:14 UTC
Labels: status: triage
