### ISSUE TITLE
Error: IPv6 address must be 16 bytes

### ISSUE THREAD

**Issue by egig** [rubygems/rubygems#1274] opened 2015-06-01 17:20 UTC
I need to Jekyll to be installed to my computer, by:

`gem install jekyll`

with or without `--verbose`, I get this:
````
ERROR:  While executing gem ... (ArgumentError)
    IPv6 address must be 16 bytes
````
Ubuntu 14.04
ruby 2.1.2p95 (2014-05-08) [x86_64-linux-gnu]
gem 2.2.2

**Comment by tenderlove** [comment] 2015-06-08 22:23
@egig thanks for reporting this.  Can you rerun gem install like this `RUBYOPT=-d gem install jekyll`, and post the output?  Also, can you try against edge RubyGems?  This may be fixed in master. /cc @jrafanie

**Comment by jrafanie** [comment] 2015-06-09 20:07
@tenderlove I don't know that my change in #1275 would fix this but it seems this is the [source of the output](https://github.com/ruby/ruby/blob/fe8cc13685a847f5b4b687d9edb88f5bee58fd70/lib/resolv.rb#L2479).  

@egig Please run again with the debug output as @tenderlove mentioned.  Is there a private/public rubygems.org that you're using?  What are your rubygems sources?  `gem sources --list`

**Comment by xmik** [comment] 2015-06-12 18:18
happened for me as well (Ubuntu 14.04.2), 
```
$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux-gnu]
$ gem -v
2.4.5
```
the output @tenderlove asked for (I install `m` gem because it is small and I treat it as a test gem):
```
$ RUBYOPT=-d gem install m
Exception `LoadError' at /usr/lib/ruby/2.2.0/rubygems.rb:1231 - cannot load such file -- rubygems/defaults/ruby
Exception `NoMethodError' at /usr/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x00000000a778d0>
Exception `NoMethodError' at /usr/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x00000000a57aa8>
Exception `NoMethodError' at /usr/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x00000000a43968>
Exception `NoMethodError' at /usr/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x00000000a5f640>
Exception `NoMethodError' at /usr/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x00000000a67b38>
Exception `NoMethodError' at /usr/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x00000000a80a48>
Exception `Gem::LoadError' at /usr/lib/ruby/2.2.0/rubygems/dependency.rb:315 - Could not find 'psych' (>= 1.2.1, ~> 1.2) - did find: [psych-2.0.8]
Checked in 'GEM_PATH=/usr/lib/ruby/gems/2.2.0/gems', execute `gem env` for more information
Exception `NameError' at /usr/lib/ruby/2.2.0/psych/class_loader.rb:67 - uninitialized constant BigDecimal
Exception `NameError' at /usr/lib/ruby/2.2.0/psych/class_loader.rb:67 - uninitialized constant Date
Exception `NameError' at /usr/lib/ruby/2.2.0/psych/class_loader.rb:67 - uninitialized constant DateTime
Exception `NameError' at /usr/lib/ruby/2.2.0/psych/core_ext.rb:16 - method `to_yaml' not defined in Object
Exception `NameError' at /usr/lib/ruby/2.2.0/psych/core_ext.rb:29 - method `yaml_as' not defined in Module
Exception `NameError' at /usr/lib/ruby/2.2.0/psych/deprecated.rb:81 - undefined method `to_yaml_properties' for class `Object'
Exception `NameError' at /usr/lib/ruby/2.2.0/rubygems/syck_hack.rb:42 - method `to_s' not defined in Psych::Syck::DefaultKey
Exception `LoadError' at /usr/lib/ruby/2.2.0/resolv.rb:168 - LoadError
Exception `ArgumentError' at /usr/lib/ruby/2.2.0/resolv.rb:2478 - IPv6 address must be 16 bytes
ERROR:  While executing gem ... (ArgumentError)
    IPv6 address must be 16 bytes
	/usr/lib/ruby/2.2.0/resolv.rb:2478:in `initialize'
	/usr/lib/ruby/2.2.0/resolv.rb:2218:in `new'
	/usr/lib/ruby/2.2.0/resolv.rb:2218:in `decode_rdata'
	/usr/lib/ruby/2.2.0/resolv.rb:1625:in `block in get_rr'
	/usr/lib/ruby/2.2.0/resolv.rb:1523:in `get_length16'
	/usr/lib/ruby/2.2.0/resolv.rb:1625:in `get_rr'
	/usr/lib/ruby/2.2.0/resolv.rb:1500:in `block (2 levels) in decode'
	/usr/lib/ruby/2.2.0/resolv.rb:1499:in `each'
	/usr/lib/ruby/2.2.0/resolv.rb:1499:in `block in decode'
	/usr/lib/ruby/2.2.0/resolv.rb:1512:in `initialize'
	/usr/lib/ruby/2.2.0/resolv.rb:1476:in `new'
	/usr/lib/ruby/2.2.0/resolv.rb:1476:in `decode'
	/usr/lib/ruby/2.2.0/resolv.rb:698:in `request'
	/usr/lib/ruby/2.2.0/resolv.rb:528:in `block in fetch_resource'
	/usr/lib/ruby/2.2.0/resolv.rb:1096:in `block (3 levels) in resolv'
	/usr/lib/ruby/2.2.0/resolv.rb:1094:in `each'
	/usr/lib/ruby/2.2.0/resolv.rb:1094:in `block (2 levels) in resolv'
	/usr/lib/ruby/2.2.0/resolv.rb:1093:in `each'
	/usr/lib/ruby/2.2.0/resolv.rb:1093:in `block in resolv'
	/usr/lib/ruby/2.2.0/resolv.rb:1091:in `each'
	/usr/lib/ruby/2.2.0/resolv.rb:1091:in `resolv'
	/usr/lib/ruby/2.2.0/resolv.rb:519:in `fetch_resource'
	/usr/lib/ruby/2.2.0/resolv.rb:509:in `each_resource'
	/usr/lib/ruby/2.2.0/resolv.rb:490:in `getresource'
	/usr/lib/ruby/2.2.0/rubygems/remote_fetcher.rb:92:in `api_endpoint'
	/usr/lib/ruby/2.2.0/rubygems/source.rb:46:in `api_uri'
	/usr/lib/ruby/2.2.0/rubygems/source.rb:85:in `dependency_resolver_set'
	/usr/lib/ruby/2.2.0/rubygems/resolver/best_set.rb:23:in `block in pick_sets'
	/usr/lib/ruby/2.2.0/rubygems/source_list.rb:97:in `each'
	/usr/lib/ruby/2.2.0/rubygems/source_list.rb:97:in `each_source'
	/usr/lib/ruby/2.2.0/rubygems/resolver/best_set.rb:22:in `pick_sets'
	/usr/lib/ruby/2.2.0/rubygems/resolver/best_set.rb:28:in `find_all'
	/usr/lib/ruby/2.2.0/rubygems/resolver/installer_set.rb:151:in `find_all'
	/usr/lib/ruby/2.2.0/rubygems/resolver/installer_set.rb:54:in `add_always_install'
	/usr/lib/ruby/2.2.0/rubygems/dependency_installer.rb:463:in `resolve_dependencies'
	/usr/lib/ruby/2.2.0/rubygems/commands/install_command.rb:238:in `install_gem'
	/usr/lib/ruby/2.2.0/rubygems/commands/install_command.rb:299:in `block in install_gems'
	/usr/lib/ruby/2.2.0/rubygems/commands/install_command.rb:295:in `each'
	/usr/lib/ruby/2.2.0/rubygems/commands/install_command.rb:295:in `install_gems'
	/usr/lib/ruby/2.2.0/rubygems/commands/install_command.rb:202:in `execute'
	/usr/lib/ruby/2.2.0/rubygems/command.rb:307:in `invoke_with_build_args'
	/usr/lib/ruby/2.2.0/rubygems/command_manager.rb:168:in `process_args'
	/usr/lib/ruby/2.2.0/rubygems/command_manager.rb:138:in `run'
	/usr/lib/ruby/2.2.0/rubygems/gem_runner.rb:54:in `run'
	/usr/bin/gem:21:in `<main>'
```

```
$ gem sources --list
*** CURRENT SOURCES ***

http://rubygems.org
```

I ran all as root, but when I run as any usual user, the outputs are the same. This happened in docker container, after router reboot. Before the router reboot I tested it multiple times (converged that docker container) and there was no such error.

**Comment by jrafanie** [comment] 2015-06-12 19:40
Thanks @xmik, I think it's here:  https://github.com/rubygems/rubygems/blob/master/lib/rubygems/remote_fetcher.rb#L89

Not sure how to test it.  You can try changing that to `uri.hostname` locally if you want.

**Comment by xmik** [comment] 2015-06-13 16:04
Thanks for suggestion @jrafanie, I tried `host = uri.hostname`, resulted in the same error. But then I tried: `host = "http://rubygems.org"` and it worked (gem `m` was installed).

**Comment by xmik** [comment] 2015-07-05 09:40
Happens also when I install gem from a local file, previously downloaded from rubygems.org:
```
$ gem install --local /home/ewa/Downloads/syck-1.0.5.gem
ERROR:  While executing gem ... (ArgumentError)
    IPv6 address must be 16 bytes
```

**Comment by djberg96** [comment] 2015-08-27 16:11
@egig @xmik Can you modify resolv.rb and see what "address" is exactly - both it's type and length.

I'm a bit confused by the resolv.rb code, as I thought an IPv6 address could be 46 characters.

**Comment by xmik** [comment] 2015-08-28 13:51
@djberg96, I cannot reproduce this error anymore: the reason was our network bad configuration (someone else fixed it and I don't know the details). But we spent some more time on this back then and the error happened only with https://rubygems.org/ (not http://rubygems.org/). Also it never happened with ruby 1.9.3 (Debian 7 default).

**Comment by djberg96** [comment] 2015-08-28 19:38
@xmik Ok, I think I'm going to close this out since it sounds like a networking configuration error, and possibly an issue with resolv.rb. If it crops up again please reopen.

**Closed by djberg96** 2015-08-28 19:38 UTC

**Comment by bigeagle** [comment] 2016-01-09 06:24
Hey, I'm also having this issue.
But i found that modifying `remote_fetcher.rb` from `host = uri.host` to `host = uri` solved it.
I guess my solution is actually wrong although it somehow worked, and I'm sure my network configuration is correct.
