### ISSUE TITLE
Bundler removes DYLD_ prefixed variables from the environment?

### ISSUE THREAD

**Issue by seven1m** [rubygems/rubygems#7893] opened 2024-07-26 01:44 UTC
### Describe the problem as clearly as you can

Why does Bundler remove the `DYLD_LIBRARY_PATH` environment variable on macOS? Or perhaps, why does Bundler remove any variable prefixed with `DYLD_`?

I tried this in a Linux container and `DYLD_LIBRARY_PATH` (and `LD_LIBRARY_PATH`) are left alone there.

### Did you try upgrading rubygems & bundler?

Yes, kinda. I upgraded Bundler to 2.5.16, but I'm running Nix, so the Rubygems version is pinned to 3.5.11.

### Post steps to reproduce the problem

```sh
# removed
→ DYLD_LIBRARY_PATH=foo bundle exec ruby -e "p ENV['DYLD_LIBRARY_PATH']"                                                                                             
nil

# works
→ DYLD_LIBRARY_PATH=foo ruby -e "p ENV['DYLD_LIBRARY_PATH']"
"foo"

# works
→ FOO_LIBRARY_PATH=foo bundle exec ruby -e "p ENV['FOO_LIBRARY_PATH']"
"foo"

# removed
→ DYLD_=foo bundle exec ruby -e "p ENV['DYLD_']"
nil

# works
→ DYLD=foo bundle exec ruby -e "p ENV['DYLD']"
"foo"
```

### Which command did you run?

I'm trying to use a library that uses FFI, and it cannot find the shared library whenever I use `bundle exec`.

### What were you expecting to happen?

I expected the environment variable I set to be available to the Ruby process.

### What actually happened?

The environment variable was cleared from the ENV. I grepped for `LIBRARY_PATH` and `DYLD` in the code and could not find it, so I'm puzzled where this might be happening and what the motivation for it is.

## Environment

```
Bundler       2.5.16
  Platforms   ruby, arm64-darwin-23
Ruby          3.3.2p78 (2024-05-30 revision e5a195edf62fe1bf7146a191da13fa1c4fecbd71) [arm64-darwin-23]
  Full Path   /nix/store/qfaw55crdlvajfkpmybjfq4cfmbmm86r-ruby-3.3.2/bin/ruby
  Config Dir  /nix/store/qfaw55crdlvajfkpmybjfq4cfmbmm86r-ruby-3.3.2/etc
RubyGems      3.5.11
  Gem Home    /Users/tim/pp/mya/.devbox/virtenv/ruby_3_3
  Gem Path    /nix/store/qfaw55crdlvajfkpmybjfq4cfmbmm86r-ruby-3.3.2/lib/ruby/gems/3.3.0:/Users/tim/pp/mya/.devbox/virtenv/ruby_3_3
  User Home   /Users/tim
  User Path   /Users/tim/.gem/ruby/3.3.0
  Bin Dir     /Users/tim/pp/mya/.devbox/virtenv/ruby_3_3/bin
Tools         
  Git         2.39.3 (Apple Git-146)
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-07-18
Git SHA           f49d3d48c9
Released Version  true
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:

PLATFORMS
  arm64-darwin-23
  ruby

DEPENDENCIES

BUNDLED WITH
   2.5.16
```

**Comment by jeromedalbert** [comment] 2024-07-26 02:49
Not a direct answer to your issue but on my macOS [environment](https://gist.github.com/jeromedalbert/07b29c8fd1f61d5c93b642aa0cb09ef0) when I run your second example I get nil:

```shell
→ DYLD_LIBRARY_PATH=foo ruby -e "p ENV['DYLD_LIBRARY_PATH']"
nil
```

On my environment it's almost like ruby itself removes `DYLD_` variables.

**Comment by indirect** [comment] 2024-07-26 03:22
As @jeromedalbert points out, this has nothing to do with Bundler. It could be Ruby, it could be your shell (bash? zsh?) it could be the OS, there are a lot of options. But it's definitely not Bundler, so I'm going to close this.

**Closed by indirect** 2024-07-26 03:22 UTC
Labels: Bundler

**Comment by indirect** [comment] 2024-07-26 03:25
After reading [this article about DYLD variables on MacOS](https://hynek.me/articles/macos-dyld-env/), my best guess is that you are using a Ruby version manager that replaces the `ruby` command with a shell script. Since the MacOS shells strip `DYLD_` env vars themselves any time you invoke them, you are removing your env vars every time your Ruby version manager loads a shell to then exec to a Ruby. You might have better results with something like `chruby`, which does not replace the `ruby` command with a shell script.

**Comment by hsbt** [comment] 2024-07-26 03:33
Thanks @indirect. I confirmed.

```
$ DYLD_LIBRARY_PATH=foo ruby -e "p ENV['DYLD_LIBRARY_PATH']"
nil
$ DYLD_LIBRARY_PATH=foo ~/.local/share/rbenv/versions/ruby-dev/bin/ruby -e "p ENV['DYLD_LIBRARY_PATH']"
"foo"
```

**Comment by seven1m** [comment] 2024-07-26 04:00
Thanks friends. The [linked article](https://hynek.me/articles/macos-dyld-env/) was indeed helpful.
