### ISSUE TITLE
Error `default_gem?' for Bundler LazySpecification

### ISSUE THREAD

**Issue by honeyankit** [rubygems/rubygems#7626] opened 2024-05-03 16:56 UTC
### Describe the problem as clearly as you can

We are getting below error 

```bash
undefined method `default_gem?' for #<Bundler::LazySpecification:0x00007f9b5a13cae8 @name="feature-flags-client", @version=#<Gem::Version "1.1.0">`
```

Full log
```ruby
2024/04/24 19:17:00 ERROR <job_819371770> undefined method `default_gem?' for #<Bundler::LazySpecification:0x00007f9b5a13cae8 @name="feature-flags-client", @version=#<Gem::Version "1.1.0">, @dependencies=[<Gem::Dependency type=:runtime name="faraday" requirements=">= 0">, <Gem::Dependency type=:runtime name="faraday-retry" requirements=">= 0">, <Gem::Dependency type=:runtime name="monolith-twirp-features-core" requirements="~> 1.1.1">, <Gem::Dependency type=:runtime name="twirp" requirements="~> 1.10">], @required_ruby_version=#<Gem::Requirement:0x00007f9b6fd8de90 @requirements=[[">=", #<Gem::Version "0">]], @_sorted_requirements=[[">=", #<Gem::Version "0">]], @_tilde_requirements=[]>, @required_rubygems_version=#<Gem::Requirement:0x00007f9b6fd8dd78 @requirements=[[">=", #<Gem::Version "0">]], @_sorted_requirements=[[">=", #<Gem::Version "0">]], @_tilde_requirements=[]>, @platform="ruby", @source=#<Bundler::Source::Rubygems:0x1520 rubygems repository https://rubygems.pkg.github.com/github/ or installed locally>, @force_ruby_platform=false, @full_name="feature-flags-client-1.1.0", @use_exact_resolved_specifications=true>
```

Context:

* [We use bundler 1.17.3](https://github.com/dependabot/dependabot-core/blob/29dcdfa8c7b91c011a2aefb9389a9ad025285000/bundler/helpers/v1/build#L25) to run v1 helpers.
* [`LazySpecification`](https://github.com/rubygems/bundler/blob/v1.17.3/lib/bundler/lazy_specification.rb) exists in bundler 1.17.3 but it does not define this `#loaded_from` method. However it is using [`#method_missing`](https://github.com/rubygems/bundler/blob/d7089abb6a3c922bfe74199c103e745bb11bd46f/lib/bundler/lazy_specification.rb#L115) to delegate to a wrapped specification, an `EndpointSpecification`, a `RemoteSpecification`, or a `StubSpecification`, by my read. `EndpointSpecification` inherits from `Gem::Specification`, the other two do not.
* The minimum version of rubygems [we require](https://github.com/dependabot/dependabot-core/blob/29dcdfa8c7b91c011a2aefb9389a9ad025285000/common/dependabot-common.gemspec#L24) is 3.3.7.
* In rubygems >= 3.3.7, `Gem::Specification` defines [`#loaded_from`](https://github.com/rubygems/rubygems/blob/bafe43c59332cd37d464e03b666233827e7704c3/lib/rubygems/basic_specification.rb#L25) (which appears to be [method chain-aliased](https://github.com/rubygems/rubygems/blob/d7089abb6a3c922bfe74199c103e745bb11bd46f/lib/bundler/rubygems_ext.rb#L41) in bundler 1.17.3 so it can define [its own `#loaded_from`](https://github.com/rubygems/rubygems/blob/d7089abb6a3c922bfe74199c103e745bb11bd46f/lib/bundler/rubygems_ext.rb#L57))

Versions:
- Ruby: 3.3.1
- Bundler: 1.17.3 

Recently, we added a [patch](https://github.com/dependabot/dependabot-core/blob/main/bundler/helpers/v1/patched_bundler) to run bundler 1.17.3 with Ruby 3.3+ for v1 helpers

### Did you try upgrading rubygems & bundler?

Ruby 3.3.1

### Post steps to reproduce the problem

1. Create a public repo in Github
2. Add bundler manifest file
3. Configure Dependabot version update for Bundler ecosystem

**Comment by deivid-rodriguez** [comment] 2024-05-03 17:17
Hei @honeyankit! Good to hear from you :heart:

It's hard to tell if this is an issue in Bundler or RubyGems without more information. Even if this is an issue, we'd need to be able to reproduce it with the latest Bundler, because if it's an issue in older Bundler, there's chances we have fixed it already. How can this error be reproduced? Can you post more information, like a full Bundler & RubyGems backtrace, and not just the error?

To try give some context in case it may help with your investigation, `LazySpecification` represents the specification for a gem, loaded from a `Gemfile.lock` file. So, it has no concept of "is this a default gem?", just "name", "vesion", "platform", and "dependencies". This is because the concept of "default gem" relies on the specification having been materialized into an actual `.gemspec` file (and whether it's a default gem or not depends on where that `.gemspec` file lives on disk).

If a `LazySpecification` is materialized into a "real" specification, then you may use methods specific to real specifications, like whether it's a default gem or not, and Bundler will delegate those methods to the underlying real specification.
 
I'm going to close this in favor of the [dependabot-core change that you are working on](https://github.com/dependabot/dependabot-core/pull/9660). If this ends up being a problem in RubyGems or Bundler once the root cause is figured out, I'll be happy to reopen!

**Closed by deivid-rodriguez** 2024-05-03 17:17 UTC
Labels: Bundler

**Comment by deivid-rodriguez** [comment] 2024-05-03 17:19
Oh, sorry, I see that you now added steps to reproduce to the issue. So is this happening on any repository using a Bundler 1 lockfile with Dependabot configured? Can you share a public repo that suffers from the problem?
