### ISSUE TITLE
error bundle install

### ISSUE THREAD

**Issue by Opti-kjh** [rubygems/rubygems#6075] opened 2022-11-25 09:44 UTC
[bundle install.txt](https://github.com/rubygems/rubygems/files/10090467/bundle.install.txt)

**Comment by hsbt** [comment] 2022-11-25 10:00
This is duplicate of https://github.com/rubygems/rubygems/issues/5981

@Opti-kjh Can you discuss about this on #5981? Thanks.

**Closed by hsbt** 2022-11-25 10:00 UTC
Labels: Bundler
