### ISSUE TITLE
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

### ISSUE THREAD

**Issue by Harrylever** [rubygems/rubygems#4636] opened 2021-05-31 01:58 UTC
gem 'rest-client', '>= 2.0.1'
    gem 'irb'
    gem 'pry-byebug'
    gem "websocket-client-simple", "~> 0.3.0"
    gem "browserstack-local", "~> 1.3"
end

source 'https://rubygems.org'
```

### Gemfile.lock

```
<No /home/kalide/beef/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

**Comment by deivid-rodriguez** [comment] 2021-05-31 10:16
Hi @Harrylever, unfortunately this issue doesn't include all the information needed for us to be able to help you, so I'm going to close it.

This _might_ be a duplicate of https://github.com/rubygems/rubygems/issues/4621. If it is, feel free to leave any comments that can help us troubleshooting this there. Otherwise, feel free to add more information to this ticket and reopen it. At least, we'd need to full output of the command that is crashing.

**Closed by deivid-rodriguez** 2021-05-31 10:16 UTC

**Comment by Harrylever** [comment] 2021-05-31 13:13
Thank you. But can I recompose the issues and update again? The main
problem I'm having us incomplete dependencies for installation of beEf.
