### ISSUE TITLE
"rubygems.rb" fails to "require" on paths using German umlauts.

### ISSUE THREAD

**Issue by ams-tschoening** [rubygems/rubygems#3853] opened 2020-07-24 17:04 UTC
I have a Ruby-based shell application which needs to require a library during startup. I'm using the following command line:

	"..\ruby\bin\ruby.exe" "-I../runtime/lib" "../visualizer/bin/ksv" "--require=de/[...]/par_opp_dispatcher.rb" "--opaque-types=true" "../files_to_show/recs_clt.bin" "de/[...]/par_recs_clt.rb"

This results in the following error, while the first line describes the current directory I'm in. It contains some German umlaut `ü`. using a ASCII-only path things work as expected.

	C:\[...]\Müller electronic\[...]\ks_ruby_visualizer>show.cmd
	Traceback (most recent call last):
	        1: from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
	<internal:gem_prelude>:2:in `require': No such file or directory -- C:/[...]/MÃ¼ller electronic/[...]/rubygems.rb (LoadError)

The problem seems to be that at some point Ruby or RubyGems really seems to forward UTF-8 encoded bytes into the file system and such a path simply doesn't exist. The interesting thing is that many times before the path is forwarded correctly according to the following ProcMon-log:

	18:57:48,7938985	ruby.exe	15296	CreateFile	C:\Users\tschoening\Documents\Svn\Src\Bibliothek\Konzepte\Müller electronic\muRead\OMS-Parser in UWP-App\IKVM\ks_ruby_visualizer\ruby\lib\ruby\2.6.0\rubygems.rb	SUCCESS	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened
	18:57:48,7940217	ruby.exe	15296	QueryBasicInformationFile	C:\Users\tschoening\Documents\Svn\Src\Bibliothek\Konzepte\Müller electronic\muRead\OMS-Parser in UWP-App\IKVM\ks_ruby_visualizer\ruby\lib\ruby\2.6.0\rubygems.rb	SUCCESS	CreationTime: 24.07.2020 14:48:44, LastAccessTime: 24.07.2020 14:48:44, LastWriteTime: 01.10.2019 23:01:05, ChangeTime: 04.02.2020 22:30:28, FileAttributes: A 0x80000
	18:57:48,7940500	ruby.exe	15296	CloseFile	C:\Users\tschoening\Documents\Svn\Src\Bibliothek\Konzepte\Müller electronic\muRead\OMS-Parser in UWP-App\IKVM\ks_ruby_visualizer\ruby\lib\ruby\2.6.0\rubygems.rb	SUCCESS	
	18:57:48,7942644	ruby.exe	15296	CreateFile	C:\Users\tschoening\Documents\Svn\Src\Bibliothek\Konzepte\Müller electronic\muRead\OMS-Parser in UWP-App\IKVM\ks_ruby_visualizer\ruby\lib\ruby\2.6.0\rubygems.rb	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a, OpenResult: Opened
	18:57:48,7943188	ruby.exe	15296	CloseFile	C:\Users\tschoening\Documents\Svn\Src\Bibliothek\Konzepte\Müller electronic\muRead\OMS-Parser in UWP-App\IKVM\ks_ruby_visualizer\ruby\lib\ruby\2.6.0\rubygems.rb	SUCCESS	
	18:57:48,7945545	ruby.exe	15296	CreateFile	C:\Users\tschoening\Documents\Svn\Src\Bibliothek\Konzepte\MÃ¼ller electronic\muRead\OMS-Parser in UWP-App\IKVM\ks_ruby_visualizer\ruby\lib\ruby\2.6.0\rubygems.rb	PATH NOT FOUND	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a

![Clipboard01](https://user-images.githubusercontent.com/6223655/88416199-13655d80-cde0-11ea-9b0d-2319b6c3af2b.png)

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

Here are my current environment details:

```
$ gem env version
3.0.3
```

* Windows 10 1909 x86-64
* default codepages Windows-1252 and CP-850
* Ruby 2.6.5

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment] 2020-09-29 11:31
Hi @ams-tschoening, just one quick question. Can you reproduce this using the `--disable-gems` ruby flag? If that's the case, the this is a ruby issue, and we should move it to ruby-core. Otherwise it is an issue in rubygems require.

**Comment by ams-tschoening** [comment] 2020-09-29 12:53
Yes, with those option the error is the same. I put it at various places in the executed command line and nothing changed.

**Comment by deivid-rodriguez** [comment] 2020-09-29 13:12
Now that I see the original error, it's certainly not a rubygems issue, since it's actually failing to require `rubygems` (so it can't be using `rubygems` require to do that).

Using `--disable-gems` you should get a different error while requiring something else, since `rubygems` should no longer be required (unless the scripts you're running explicitly require it).

To use the flag, I guess something like this?

```
"..\ruby\bin\ruby.exe" "--disable-gems" "-I../runtime/lib" "../visualizer/bin/ksv" "--require=de/[...]/par_opp_dispatcher.rb" "--opaque-types=true" "../files_to_show/recs_clt.bin" "de/[...]/par_recs_clt.rb"
```

In any case, could you open a separate ticket at https://bugs.ruby-lang.org/? (It seems down now for some reason, but when it's back up again :sweat_smile:).

**Comment by deivid-rodriguez** [comment] 2020-09-29 13:15
Actually, it's up now again, and I found some possibly related issues: https://bugs.ruby-lang.org/issues/15993, https://bugs.ruby-lang.org/issues/15655.

Have a look at those issues to see if they match your problem.

I'll close this for now since it doesn't seem like a problem in rubygems.

**Closed by deivid-rodriguez** 2020-09-29 13:15 UTC
Labels: RubyGems, status: user feedback required

**Comment by ams-tschoening** [comment] 2020-09-29 13:31
> To use the flag, I guess something like this?

Yes and at various other places, just to be sure. Your referenced bug looks promising in deed, I will put my findings there. Thanks!
