### ISSUE TITLE
Incorrect Code Figuring Out Missing Extensions and Deleting Gems

### ISSUE THREAD

**Issue by cfis** [rubygems/rubygems#4375] opened 2021-02-15 07:14 UTC
### Describe the problem as clearly as you can

Bundler is incorrectly deciding some gems have missing extensions when in fact they do not. This breaks the ability to manually install gems and then use bundler. This is a new breakage.

Let's go through an example. On mingw64, without ruby devkit installed, install the mysql2 gem:

```gem install --platform ruby mysql2```

It will fail because the mysql2 extconf.rb file has some incorrect logic.  Specifically line 184 should be changed from:

```if RUBY_PLATFORM =~ /mswin|mingw/ && !defined?(RubyInstaller)```

To:

```if RUBY_PLATFORM =~ /mswin/ && !defined?(RubyInstaller)```

So locally fix that line in extconf.rb, ruby, then rerun `ruby extconf.rb --with-mysql2-dir=/mingw64`, then run `make` to build mysql2.so successfully.

Next, follow the instructions from `gem help install` for this exact situation:

```
[build fails]
      Gem files will remain installed in \
      /path/to/gems/some_extension_gem-1.0 for inspection.
      Results logged to /path/to/gems/some_extension_gem-1.0/gem_make.out
      $ [cd /path/to/gems/some_extension_gem-1.0]
      $ [edit files or what-have-you and run make]
      $ gem spec ../../cache/some_extension_gem-1.0.gem --ruby > \
                 ../../specifications/some_extension_gem-1.0.gemspec
      $ gem list some_extension_gem
```
This works great, mysql2 gem is now installed. 

However, with the latest version of bundler this fails as soon as you run ```bundler update``` or ```bundler install``` because bundler does not think the extension exists and it deletes the gem from the list of gems!

Try it:

1. Have a Gemfile that requires mysql2 gem
2. ```bundle install```
3.  ```gem list mysql2``` now shows nothing!

I'm not sure where bundler is deleting the gem (it really should not be), but I do know where the faulty extension code is. See stub_specification.rb:

```
  def missing_extensions?
      return false if default_gem?
      return false if extensions.empty?
      return false if File.exist? gem_build_complete_path

      true
    end
```
This is new code - previously it was:

```
    def missing_extensions?
      stub.missing_extensions?
    end
```

The incorrect line is:

```return false if File.exist? gem_build_complete_path```

The file its looking for (gem_build_complete_path) is:

```
ruby-2.7.2\lib\ruby\gems\2.7.0\extensions\x64-mingw32\2.7.0\mysql2-0.5.3\gem_build.complete
```

Of course that file doesn't exist because we manually built the gem and its shared library.

Like I said, this is a new issue - this type of installation has worked fine in the past.

So a few thoughts:

* It seems strange bundler is even doing this check? Shouldn't RubyGems verify a gem was correctly installed at the time of installation? Not at some later time like bundler is doing here?
* Checking for gem_make.out seems like a poor choice. Shouldn't the .so file be checked instead?
* Can the "real" location of the so file be checked - ie, the gem path (gem/mysql2/lib/2.7/mysql2.so) or in its extension directory?
* If none of the above, then can ```gem help install`` be updated to note you have to create this dummy gem_build.complete file? And a command on how to do it?

Thanks

## Environment

```
Bundler       2.2.9
  Platforms   ruby, x64-mingw32
Ruby          2.7.2p137 (2020-10-01 revision 5445e0435260b449decf2ac16f9d09bae3cafe72) [x64-mingw32]
  Full Path   C:/msys64/usr/local/ruby-2.7.2/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      3.2.9
  Gem Home    C:/msys64/usr/local/ruby-2.7.2/lib/ruby/gems/2.7.0
  Gem Path    D:/cfis/.gem/ruby/2.7.0;C:/msys64/usr/local/ruby-2.7.2/lib/ruby/gems/2.7.0
  User Home   D:/cfis
  User Path   D:/cfis/.gem/ruby/2.7.0
  Bin Dir     C:/msys64/usr/local/ruby-2.7.2/bin
Tools
  Git         2.30.0.windows.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-02-08
Git SHA           30e740c073
Released Version  true
```

**Comment by deivid-rodriguez** [comment] 2021-02-15 10:39
Hi @cfis, thanks for reporting this!

For reference, this change was introduced by https://github.com/rubygems/rubygems/pull/3635 to fix https://github.com/rubygems/rubygems/issues/3365.

I was not expecting this to change the missing extension logic, since I was expecting the previous logic: `stub.missing_extensions?` to end up running the logic in the `Gem::Specification` class, which is exactly the same:

https://github.com/rubygems/rubygems/blob/22fb661dacc9cd905d43d77bf88399f746e09dda/lib/rubygems/specification.rb#L2124-L2135

But if this worked previously, then I'm somehow wrong of course.

> * It seems strange bundler is even doing this check? Shouldn't RubyGems verify a gem was correctly installed at the time of installation? Not at some later time like bundler is doing here?

I'm not fully sure, I think bundler does this to detect non-functional extension gems being installed and try to gracefully handle that case. But not really fully sure.

> * Checking for gem_make.out seems like a poor choice. Shouldn't the .so file be checked instead?
> * Can the "real" location of the so file be checked - ie, the gem path (gem/mysql2/lib/2.7/mysql2.so) or in its extension directory?

I don't think this is possible, because bundler can't curently know what's the expected artifact of compiling an extension. I believe that's why it uses a sentinel file at a specific location.

> * If none of the above, then can ```gem help install`` be updated to note you have to create this dummy gem_build.complete file? And a command on how to do it?

Yes, that seems like a nice improvement to me. But if you can dig in more about why the previous logic worked fine, and the current doesn't, and how to restore the previous logic without breaking anything fixed by the new logic, that would be best!

**Comment by cfis** [comment] 2021-02-15 10:49
Hi David,

Ah, well that is an interesting question. Thanks for the pointer to #3635. I'll try with an old version of bundler and see if I can tell what's changed.

**Comment by cfis** [comment] 2021-02-15 20:43
The default version of bundler packaged with Ruby 2.7.2 is 2.1.4. Using that version, what the old code did is:

```ruby
  def missing_extensions?
    return false if default_gem?
    return false if extensions.empty?
    return false if File.exist? gem_build_complete_path

    to_spec.missing_extensions?
  end
```

Notice the method ends with `to_spec.missing_extensions?`. The gem spec does exist because Ruby Gems says to create it:

```ruby
$ gem spec ../../cache/some_extension_gem-1.0.gem --ruby > \
                 ../../specifications/some_extension_gem-1.0.gemspec
```
In contrast, the updated code returns true which is the incorrect result.

Could that change be reverted? Also, maybe this code should be entirely removed? It still seems incorrect to me that Bundler is checking this - especially since it used to just default to checking the spec anyway.

Also, there is a second bug in the latest version of bundler that I mentioned that is deleting the mysql2 gem in the process of doing a bundle update or bundle create. That is very surprising. I haven't hunted down where that happens. Maybe that should be a separate ticket?

**Comment by deivid-rodriguez** [comment] 2021-02-15 22:04
> Could that change be reverted?

That change was introduced to fix a bug, so a revert is not an option because then the person was hitting the bug will now hit the bug again. And even more in this case where the problem caused by the bug (some troubleshoot instructions that would now require you to `touch` an extra file) is less critical than the original issue (a stackoverflow runtime crash).

> Also, maybe this code should be entirely removed? It still seems incorrect to me that Bundler is checking this - especially since it used to just default to checking the spec anyway.

If it was that easy, I'd be happy to do it, but it's not that easy. I'm pretty sure removing that code will break a bunch of use cases we're not aware of.

What I was trying to say before is that `to_spec.missing_extensions?` should end up running the same code again but inside the `Gem::Specification` class and end up returning `true` as well. So I don't get how this is happening.

> Also, there is a second bug in the latest version of bundler that I mentioned that is deleting the mysql2 gem in the process of doing a bundle update or bundle create. That is very surprising. I haven't hunted down where that happens. Maybe that should be a separate ticket?

Sure, please open a separate ticket with repro instructions.

**Comment by cfis** [comment] 2021-02-15 22:50
Its different because there are two different methods in RubyGems version 3.1.4, which shipped with Ruby 2.7.2 (there still might be in later versions, I haven't checked). Bundler took the code from specification.rb but ignored the code in stub_specification:

rubygems/stub_specification.rb

```ruby
 def missing_extensions?
    return false if default_gem?
    return false if extensions.empty?
    return false if File.exist? gem_build_complete_path

    to_spec.missing_extensions?
  end
```

rubygems/specification.rb

```ruby
  def missing_extensions?
    return false if default_gem?
    return false if extensions.empty?
    return false if installed_by_version < Gem::Version.new('2.2.0.preview.2')
    return false if File.exist? gem_build_complete_path

    true
  end
```

The mysql2 gem has a stub_specification, which was generated by the command RubyGems said to run:

```ruby
$ gem spec ../../cache/some_extension_gem-1.0.gem --ruby > \
                 ../../specifications/some_extension_gem-1.0.gemspec
```

In the fix in #3635 there are a lot of changes. If this one part of the change was reverted:

```ruby
def missing_extensions?
      stub.missing_extensions?
 end
```

Wouldn't it be better for Bundler to continue to acknowledge there are two different types of specifications? Would that break the fix? If yes, then hopefully there is an alternate solution that can fix #3635 but not cause this new breakage?

The problem with the current situation is this fix broke behavior that has worked since bundler has existed (so what, 10 years now) and invalidates the help that RubyGems provides.

**Comment by deivid-rodriguez** [comment] 2021-02-15 22:59
The commit specifically fixing the issue is this one: https://github.com/rubygems/rubygems/pull/3635/commits/226ec115fe503bcc93bffdf5cd3e8a668890b4d8. I understand the problem, and I'm not saying I don't want to fix it. I'm just saying it's not as easy as reverting the PR that introduced the problem.

Feel free to investigate, clone the repo, run tests, propose a solution and so on.

**Comment by cfis** [comment] 2021-02-15 23:27
David - I definitely appreciate the help!

You obviously know the code base and I surely don't. So do you have any thoughts on a solution that could keep manually installed gems working while at the same time not breaking #3635? I don't mind pitching in, but getting up to speed on bundler will take a while and my real goal in all this is trying to fix a couple of composite primary key bugs and this has sidetracked me for a day trying to get a working dev environment in place.

**Comment by deivid-rodriguez** [comment] 2021-02-15 23:30
No, sorry. Since I don't currently know why things broke, I don't know what a solution would look like. I would need to investigate but this issue is quite low priority for me compared to others.

**Comment by cfis** [comment] 2021-02-15 23:32
Digging more, my diagnosis wasn't quite right. This was the code in rubygems/specification.rb:

  def missing_extensions?
    return false if default_gem?
    return false if extensions.empty?
    return false if installed_by_version < Gem::Version.new('2.2.0.preview.2')
    return false if File.exist? gem_build_complete_path

    true
  end

It's this line:

```  return false if installed_by_version < Gem::Version.new('2.2.0.preview.2')```

Installed by version is for the manually installed mysql2 gem is 0. And thus bundler used to think its not missing extensions...

**Comment by deivid-rodriguez** [comment] 2021-02-15 23:37
Ha! That makes more sense.

Then this is a regression of 6f531673aea32d480329dd55f2feb75c4b2a7439 and it's easily fixable since that was just something I thought wasn't needed. I guess we can restore that line but checking for "0" explicit as a sign of "manually installed".

**Comment by cfis** [comment] 2021-02-15 23:42
I have to admit I don't see why its a regression of r6f53167.

But yes, I was thinking a check against installed version of 0 is the way to go versus Gem::Version.new('2.2.0.preview.2').

So I think the patch is add this line to `def missing_extensions?`

return false if installed_by_version == Gem::Version.new(0') # Allow manually installed gems

Do you want an pull request or is this enough info?

**Comment by cfis** [comment] 2021-02-15 23:52
Yes, that does the trick. So to be clear, in bundler/stub_specificationn.rb

```ruby
 # This is defined directly to avoid having to loading the full spec
    def missing_extensions?
      return false if default_gem?
      return false if extensions.empty?
      return false if File.exist? gem_build_complete_path
      return false if installed_by_version == Gem::Version.new(0) # Allow manually installed gems

      true
    end
```

**Comment by deivid-rodriguez** [comment] 2021-02-15 23:54
Sorry, bad reference, I edited the commit!

**Comment by cfis** [comment] 2021-02-16 00:05
Ah - yup I see now. So to state the obvious, the patch would be revert that commit but then update it for better clarity to use something like this:

```ruby
# This is for manually installed gems (see `gem help install` instructions for in-place fixing of gems that don't install)
installed_by_version == Gem::Version.new(0) 
```

**Comment by deivid-rodriguez** [comment] 2021-02-16 08:34
Yes, and it'd be also nice to also add a test to cover the fix.

**Comment by cfis** [comment] 2021-02-17 04:07
Ok, so I take it you would like a pull request then?

**Comment by cfis** [comment] 2021-02-24 03:50
David - Is there anything else you need from me to wrap this up? Would love to get this fixed.

Thanks  - Charlie

**Closed** 2021-03-01 10:11 UTC
Labels: Bundler
