### ISSUE TITLE
SSL issue with legacy Rubies and 2.7.11

### ISSUE THREAD

**Issue by JonRowe** [rubygems/rubygems#4228] opened 2021-01-02 17:25 UTC
Hello!

Thank you for your hard work maintaining Rubygems, it is especially appreciated you've taken the time to back port new SSL certs to older versions of Rubygems, e.g. 2.7.11

I'm trying to use this to build some CI for legacy (pre 2.0) Rubies as RSpec still supports these until we release 4.0.0 (and we'd like the sanity check for some of our extension gems and transition work toward that, where we will be changing to a minimum of 2.3 supported)

Using 2.7.11 to install the last Bundler 1.x release (`1.17.3`) results in this error:

```
 Unable to download data from https://rubygems.org/ - hostname was not match with the server certificate (https://api.rubygems.org/specs.4.8.gz)
```

Yet strangely some older versions of Rubygems work fine, e.g. the defaults for 1.9.3 and 2.0 can install bundler and carry on

Is there an intermediate certificate required to use the new certs?

**Comment by deivid-rodriguez** [comment] 2021-01-04 09:27
Hello! :wave: 

Unfortunately I have no idea about what the problem could be here, sorry. Can you stick to that older rubygems that installs bundler fine? :grimacing:

**Comment by JonRowe** [comment] 2021-01-07 22:49
Ok so I've been able to update the newer (but still EOL I know) Rubies to use the latest version, which makes me suspect this is an open ssl issue. (As manually downloading gems works fine, so the docker images their self must be able to validate Rubygems certs). 

However I cannot disable SSL verification via the `gemrc` trick, nor does bundler config seem to respect the flag, which may be related to #4192).

I've run the (slightly edited to ignore an non existent RUBY_REVISION) Ruby SSL checking script mentioned here:
https://bundler.io/guides/rubygems_tls_ssl_troubleshooting_guide.html#automated-ssl-check

And it doesn't mention anything other than its unable to match the hostname?

**Comment by JonRowe** [comment] 2021-01-07 22:50
Strangely JRuby 1.7 works fine, but if I run it in 1.8 mode that breaks, which makes me feel very much like its emulating something, if the TLS version was the issue would the script highlight that?

**Comment by isikyus** [comment] 2021-01-11 02:12
I believe I'm seeing the same issue as @JonRowe .
Output from https://github.com/rubygems/ruby-ssl-check/blob/master/check.rb :

```
$ ruby ~/Downloads/check.rb
Here's your Ruby and OpenSSL environment:

Ruby:           [old EOL ruby]
RubyGems:       2.0.17
Bundler:        1.17.3
Compiled with:  OpenSSL 1.0.2t  10 Sep 2019
SSL_CERT_FILE:  /home/linuxbrew/.linuxbrew/etc/openssl/cert.pem
SSL_CERT_DIR:   /home/linuxbrew/.linuxbrew/etc/openssl/certs

With that out of the way, let's see if you can connect to rubygems.org...

Bundler connection to rubygems.org:       failed  ❌  (hostname was not match with the server certificate)
RubyGems connection to rubygems.org:      failed  ❌  (hostname was not match with the server certificate (https://rubygems.org))
Ruby net/http connection to rubygems.org: failed  ❌

Unfortunately, this Ruby can't connect to rubygems.org. 😡
Your Ruby can't connect to rubygems.org because you are missing the certificate files OpenSSL needs to verify you are connecting to the genuine rubygems.org servers.
```

The source of that script in turn recommends https://github.com/mislav/ssl-tools/blob/8b3dec4/doctor.rb, which tells me this:

```
$ ruby ~/Downloads/doctor.rb rubygems.org
/home/edward/.rvm/rubies/[old EOL ruby]/bin/ruby ([old EOL ruby])
OpenSSL 1.0.2t  10 Sep 2019: /home/linuxbrew/.linuxbrew/etc/openssl
SSL_CERT_DIR=""
SSL_CERT_FILE=""

HEAD https://rubygems.org:443
OpenSSL::SSL::SSLError: hostname was not match with the server certificate

Possible causes:
  `/home/linuxbrew/.linuxbrew/etc/openssl/certs/' is empty
```

It looks like `/home/linuxbrew/.linuxbrew/etc/openssl/certs/` doesn't exist at all on my machine — I suspect I may have messed up installing Ruby (or it should be loading SSL certificates from somewhere else).

**Comment by isikyus** [comment] 2021-01-11 04:38
> And it doesn't mention anything other than its unable to match the hostname?

I've traced the request in Wireshark and it looks like the hostname actually is wrong.
RubyGems isn't sending the SNI extension, so Fastly isn't returning the correct rubygems.org certificate.

By contrast, CURL (which works) is sending a `server_name` extension in the client handshake.

**Comment by isikyus** [comment] 2021-01-11 04:43
It appears the issue is actually in `net/https`, not rubygems. The `doctor.rb` script doesn't use RubyGems, and it reproduces the failure in the old Ruby I'm using, but not in 2.6.3.

Both Rubies are built against the same OpenSSL:

```
$ ruby ~/Downloads/doctor.rb rubygems.org:443
/home/edward/.rvm/rubies/ruby-2.6.3/bin/ruby (2.6.3-p62)
OpenSSL 1.0.1f 6 Jan 2014: /usr/lib/ssl
SSL_CERT_DIR=""
SSL_CERT_FILE=""

HEAD https://rubygems.org:443
OK
```

```
$ ruby ~/Downloads/doctor.rb rubygems.org:443
/home/edward/.rvm/rubies/[old EOL Ruby]/bin/ruby ([old EOL Ruby])
OpenSSL 1.0.1f 6 Jan 2014: /usr/lib/ssl
SSL_CERT_DIR=""
SSL_CERT_FILE=""

HEAD https://rubygems.org:443
OpenSSL::SSL::SSLError: hostname was not match with the server certificate

Possible causes:
  `/usr/lib/ssl/cert.pem' does not exist
```

**Comment by MSP-Greg** [comment] 2021-01-11 04:52
Ruby's SSL uses either the cert file shown in:
```
SSL_CERT_FILE:  /home/linuxbrew/.linuxbrew/etc/openssl/cert.pem
```
or it will load individual files from:
```
SSL_CERT_DIR:   /home/linuxbrew/.linuxbrew/etc/openssl/certs
```

I don't know if there's any easy way to update either.  Windows Ruby builds have one bundled with them, but they're 7zip (`.7z`) files...

**Comment by deivid-rodriguez** [comment] 2021-01-11 08:27
Nice investigation @isikyus! I love how you redacted your EOL'd ruby version :rofl:.

Maybe you could try updating `net/http`. This library [is gemified](https://github.com/ruby/net-http) and it doesn't support your ruby version, but I'm not sure if it was bumped due to a real incompatibility or just for maintenance convinience :man_shrugging:.

**Comment by deivid-rodriguez** [comment] 2021-01-11 14:19
I found this link that might help you track this down: https://github.com/drbrain/net-http-persistent/issues/62. From there you can get to the ruby-core issue and the patch that got eventually merged to `net/http`.

**Comment by isikyus** [comment] 2021-01-12 11:06
> Maybe you could try updating `net/http`.

I may try that later on, thanks @deivid-rodriguez ; for the moment I've got it working through a proxy.
In the long run the plan is to use a current Ruby and avoid the issue entirely :smile:

**Comment by JonRowe** [comment] 2021-01-12 21:09
Is there a proxy or similar we can use that doesn't use SNI certificates?

**Comment by deivid-rodriguez** [comment] 2021-01-12 21:15
I have no idea, honestly, but if I had to guess I'd say no. Maybe @sonalkr132 has more insights.

**Comment by sonalkr132** [comment] 2021-01-15 10:13
Hi, sorry about the delay in reply here.
> Is there a proxy or similar we can use that doesn't use SNI certificates?

Fastly endpoints are the only ingress endpoints for us, so if it needs SNI I doubt there is going to be an option to work around it serverside.

>  Unable to download data from https://rubygems.org/ - hostname was not match with the server certificate (https://api.rubygems.org/specs.4.8.gz)

You have an option to avoid this error by disabling the certificate check. You can set `:ssl_verify_mode: 0` in your `.gemrc` file [[1](https://github.com/rubygems/rubygems/blob/a969c0f16aa56cdb69e2a051f2b093427010e1d9/lib/rubygems/config_file.rb#L126). Goes without saying this is very insecure, probably fine for travis builds but not recommended for your own hosts.

Another workaround for this could be adding `151.101.0.70 rubygem.org` to your `/etc/host` file. We have migrated away from these IPs and there is no guarantee of how long it will continue working.

**Comment by sonalkr132** [comment] 2021-01-18 06:10
I have reached out to fastly support to get a dedicated IP address for our service, which won't need SNI. I will update if that comes throught.

**Comment by JonRowe** [comment] 2021-01-22 09:33
>You have an option to avoid this error by disabling the certificate check. You can set :ssl_verify_mode: 0 in your .gemrc file [1. Goes without saying this is very insecure, probably fine for travis builds but not recommended for your own hosts.

I tried that, it didn't seem to work at an environment level, we're building docker containers so I thought it needed to be for the whole system not a user, although possibly we could try to set it for the root user.

> 151.101.0.70 rubygem.org

This works for now 👏  thank you! I just have to hope we manage to release RSpec 4 before it ceases to work 😂

**Comment by JonRowe** [comment] 2021-01-22 09:34
@sonalkr132 Can you share any progress with Fastly? It'd be nice to know if its worth reaching out myself to see if they'd "sponsor" RSpec with an endpoint 😂

**Comment by deivid-rodriguez** [comment] 2021-01-22 10:28
Since there won't be any actions taken in the client library, and a workaround has been provided, I'll close this. Feel free to use this issue though to post updates about the Fastly request :)

**Closed by deivid-rodriguez** 2021-01-22 10:28 UTC
Labels: RubyGems, status: feedback required

**Comment by sonalkr132** [comment] 2021-01-23 13:41
I followed up on my support ticket after your reply. Only received a reply today that they have pinged people to check why there were no updates. I hope this coming week we will some action. I doubt a separate ticket from your side would speed things up, you are welcome to try.

> I just have to hope we manage to release RSpec 4 before it ceases to work 

Fastly planned retirement of that interfaces was 31 Dec, however, it is clearly still working. I am not sure what is their timeline as of now https://docs.fastly.com/changes/significant/2020/03/09/special I guess we can ask them to not retire the old interface until we migrate to dedicated IP.

**Comment by sonalkr132** [comment] 2021-02-09 10:45
Fastly got back to us with an update that they won't be able to provide dedicated IP until 15 March due to their own internal dependencies (dedicated IP is a beta feature). They suggested that we can roll back to the old endpoint if we want. We are not rolling back since legacy doesn't support TLS 1.3 and traffic without SNI is very small (< 0.09 perc). This does mean that the legacy endpoint will continue to work in the near future, at the very least until we get a dedicated IP.
We also found out that we do receive traffic from ruby 1.8.7 occasionally https://ui.honeycomb.io/ruby-together/datasets/rubygems.org/result/kf13xTwDdvz I am not sure how 1.8.7 clients are sending traffic, if SNI wasn't supported until 1.9.2. I will update if I find out more.

**Comment by JonRowe** [comment] 2021-02-09 15:38
Thats great thanks :)

**Comment by d0minos** [comment] 2021-03-29 06:52
Has there been any updates regarding moving to a dedicated IP? From what I understand, Fastly could not provide it before 15 March but is such solution available now?
Thanks.

**Comment by sonalkr132** [comment] 2021-04-01 04:27
I had pinged them mid-march. They informed us that now the timeline is moved to mid-late April. The feature is not GA.

Are you having issues connecting to rubygems.org because of SNI? Have you tried the workarounds mentioned [here](https://github.com/rubygems/rubygems/issues/4228#issuecomment-760802106). You can also reach out to us at support@ruybgems.org

**Comment by d0minos** [comment] 2021-04-02 20:32
Ok, thanks for the update.
Yes, we are having issues with SNI due to using an old version of Ruby. We are using a workaround but just checking this topic once in a while to see when we can stop doing it. Based on latest news I guess I will check again some time in May.

**Comment by sonalkr132** [comment] 2021-04-22 21:04
> Another workaround for this could be adding 151.101.0.70 rubygem.org to your /etc/host file. 

FYI guys, this endpoint is no longer working since as expected fastly has removed our domain from cert served on this endpoint. Good news is we got dedicated IPs assigned to us this week. we have migrated our staging and testing things. We hope to migrate prod by Saturday.
You can use 151.101.129.227 instead of 151.101.0.70 if you were using this solution.

**Comment by sonalkr132** [comment] 2021-04-27 15:33
Hi, final update everyone. We have migrated rubygems.org (and its subdomains) to dedicated IP. You should be able to connect to rubygems.org without SNI requirements.

Please follow [this guide](https://bundler.io/v2.1/guides/rubygems_tls_ssl_troubleshooting_guide.html#updating-ca-certificates) if you get a certificate verification issue. Basically, you need to make sure [GlobalSignRootCA_R3](https://raw.githubusercontent.com/rubygems/rubygems/master/lib/rubygems/ssl_certs/rubygems.org/GlobalSignRootCA_R3.pem) is a trusted CA on your host/rubygems/bundler. This should already be the case for most hosts.
