### ISSUE TITLE
Paths with quotes not handled properly for "--install-dir" in ".gemrc"?

### ISSUE THREAD

**Issue by ams-tschoening** [rubygems/rubygems#3125] opened 2020-02-04 20:24 UTC
I'm having a problem or would like to suggest a feature.

My current problem is that when a `.gemrc` contains the following line only:

    gem: --install-dir "C:\Users\tschoening\.gem\ruby\2.6.0"

That results in the following error message when trying to install a gem:

    C:\Program Files\Ruby\2.6.5\bin>gem install solargraph
    ERROR:  While executing gem ... (Errno::EINVAL)
        Invalid argument - C:/Program Files/Ruby/2.6.5/bin/"C:/Users/tschoening/.gem/ruby/2.6.0"/specifications

I seems gem takes the configured path as a relative one because it starts with quotes, even though the exact same call on the shell works:

	C:\Program Files\Ruby\2.6.5\bin>gem install solargraph --install-dir "C:\Users\tschoening\.gem\ruby\2.6.0"
	Nokogiri is built with the packaged libraries: libxml2-2.9.10, libxslt-1.1.34, zlib-1.2.11, libiconv-1.15.
	Successfully installed nokogiri-1.10.7-x64-mingw32
	Successfully installed solargraph-0.38.5
	Parsing documentation for nokogiri-1.10.7-x64-mingw32
	Parsing documentation for solargraph-0.38.5
	Done installing documentation for nokogiri, solargraph after 2 seconds
	2 gems installed

Is that by design? Seems unexpected to me and things most likely fail for paths using spaces without quotes.

This issue is related to:

  - [ ] Network problems
  - [X] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.0.3
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment] 2020-02-13 14:05
It seems it's a windows problem, I couldn't reproduce it on a mac/linux machine

**Comment by deivid-rodriguez** [comment] 2021-07-09 11:45
Is this still reproducible?

**Comment by ams-tschoening** [comment] 2021-07-09 12:49
Not that I have the time right now, but what exactly should one test? Which parts of Ruby should be updated to which version?

**Comment by deivid-rodriguez** [comment] 2021-07-09 12:51
I would try to reproduce the issue you were having at the time using the latest ruby (3.0.2) & rubygems (3.2.22) versions.

**Comment by deivid-rodriguez** [comment] 2021-07-20 09:45
I'll close this for now, and if you can repro, we can reopen it!

**Closed by deivid-rodriguez** 2021-07-20 09:45 UTC
Labels: platform: windows, status: feedback required
