### ISSUE TITLE
Shim script launches incorrect version of Bundler unless RUBYLIB is set

### ISSUE THREAD

**Issue by raxod502** [rubygems/rubygems#4597] opened 2021-05-12 04:42 UTC
### Describe the problem as clearly as you can

When using the shim script for Bundler installed with RubyGems, it doesn't run the version of Bundler that was installed with RubyGems. Instead it runs the version of Bundler that was installed system-globally. The problem can be worked around by manually exporting the `RUBYLIB` environment variable.

### Post steps to reproduce the problem

Synopsis:

```
% gem --version                                
3.1.2
% gem install bundler -v 1.17.3 --install-dir /tmp/bundler-test               
Fetching bundler-1.17.3.gem
Successfully installed bundler-1.17.3
Parsing documentation for bundler-1.17.3
Installing ri documentation for bundler-1.17.3
Done installing documentation for bundler after 1 seconds
1 gem installed
% /tmp/bundler-test/bin/bundler version
Bundler version 2.1.2 (2021-05-12 commit unknown)
% RUBYLIB=/tmp/bundler-test/gems/bundler-1.17.3/lib /tmp/bundler-test/bin/bundler version
Bundler version 1.17.3 (2018-12-27 commit d7089abb6)
```

Dockerfile:

```
FROM ubuntu:focal
RUN apt-get update
RUN apt-get install -y ruby ruby-bundler
RUN gem install bundler -v 1.17.3 --install-dir /tmp/bundler-test
CMD /tmp/bundler-test/bin/bundler version
```

### Which command did you run?

```
% /tmp/bundler-test/bin/bundler version
```

### What were you expecting to happen?

```
Bundler version 1.17.3 (2018-12-27 commit d7089abb6)
```

### What actually happened?

```
Bundler version 2.1.2 (2021-05-12 commit unknown)
```

## Environment

```
Bundler       2.1.4
  Platforms   ruby, x86_64-linux
Ruby          2.7.0p0 (2019-12-25 revision 647ee6f091eafcce70ffb75ddf7e121e192ab217) [x86_64-linux-gnu]
  Full Path   /usr/bin/ruby2.7
  Config Dir  /etc
RubyGems      3.1.2
  Gem Home    /var/lib/gems/2.7.0
  Gem Path    /home/raxod502/.gem/ruby/2.7.0:/var/lib/gems/2.7.0:/usr/lib/ruby/gems/2.7.0:/usr/share/rubygems-integration/2.7.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0
  User Home   /home/raxod502
  User Path   /home/raxod502/.gem/ruby/2.7.0
  Bin Dir     /usr/local/bin
Tools         
  Git         2.25.1
  RVM         1.29.12 (manual)
  rbenv       not installed
  chruby      not installed
Gem.ruby      /usr/bin/ruby2.7
bundle #!     /usr/bin/ruby

```

## Bundler Build Metadata

```
Built At          2020-01-05
Git SHA           32a4159325
Released Version  true
```

**Comment by deivid-rodriguez** [comment] 2021-05-12 08:22
Hi @raxod502, thanks for your report.

This is expected behaviour. Shims generated by rubygems are unique per "GEM_HOME". If you install another bundler version to the same location, you can see how the shim generated by rubygems is unchanged, but that you have now two versions installed in that location (plus the default one). You can check this by running `gem install bundler -v 2.1.4 --install-dir /tmp/bundler-test` on top of your steps, and checking that `/tmp/bundler-test/bin/bundler` hasn't changed.

The behaviour of this shim is to automatically choose the latest version available, unless you pass a explicit version to it (like, this `/tmp/bundler-test/bin/bundler _1.17.3_ version`). In your case, the latest version available is the default one (the one that comes integrated with ruby itself, and that can't be uninstalled), and you're not passing an explicit version to the shim, that's why 2.1.2 is getting run.

Also, note that even if you had a higher version available than the default one, your example would still not work as you expected, because you're not telling rubygems to look for gems at your custom `--install-dir`. So after installing bundler-2.1.4 as above, in your example you'll still get 2.1.2 run, because rubygems doesn't now about your custom gem location, so it only knows about the default version. To get that working you'll need to either configure `RUBYLIB` as you did, or alternatively set `GEM_HOME` and `GEM_PATH` to your custom location:

```
$ # shows globally install versions
$ gem list bundler

*** LOCAL GEMS ***

bundler (default: 2.1.2)

$ # Shows versions installed at the custom location
$ GEM_HOME=/tmp/bundler-test GEM_PATH=/tmp/bundler-test gem list bundler

*** LOCAL GEMS ***

bundler (2.1.4, default: 2.1.2, 1.17.3)

$ # Chooses the latest version available at the custom location
$ GEM_HOME=/tmp/bundler-test GEM_PATH=/tmp/bundler-test /tmp/bundler-test/bin/bundler version
Bundler version 2.1.4 (2020-01-05 commit 32a4159325)

$ # Chooses the version you manually specified
$ GEM_HOME=/tmp/bundler-test GEM_PATH=/tmp/bundler-test /tmp/bundler-test/bin/bundler _1.17.3_ version
Bundler version 1.17.3 (2018-12-27 commit d7089abb6)
```

Hope this helps clarifying things!

**Comment by raxod502** [comment] 2021-05-16 19:12
Gotcha. So, basically, RubyGems doesn't have support for creating a shim script that hardcodes a specific version---and if we want one, we should create a wrapper ourselves, like this?

```
% GEM_HOME=/tmp/custom-test/gem gem install bundler -v 1.17.3                               
Fetching bundler-1.17.3.gem
Successfully installed bundler-1.17.3
Parsing documentation for bundler-1.17.3
Installing ri documentation for bundler-1.17.3
Done installing documentation for bundler after 1 seconds
1 gem installed
% mkdir /tmp/custom-test/bin
% cat <<"EOF" > /tmp/custom-test/bin/bundler
#!/usr/bin/env bash
GEM_PATH="$(dirname "$0")/../gem" exec "$(dirname "$0")/../gem/bin/bundler" _1.17.3_ "$@"
% /tmp/custom-test/bin/bundler version
Bundler version 1.17.3 (2018-12-27 commit d7089abb6)
```

Creating shim scripts like this is required for software like asdf (see e.g. https://github.com/jonathanmorley/asdf-bundler/issues/3). Do you think it would be a good idea to provide some way in Bundler to automate the creation of such scripts?

**Comment by deivid-rodriguez** [comment] 2021-05-20 09:23
Bundler already have a way to pin versions. If you run `bundle exec <executable>`,  the version of `<executable>` locked in your `Gemfile.lock` will be run. Alternative, you can generate binstubs with `bundle binstubs <executable>` if you prefer a shim instead of using `bundle exec`. Similarly for `bundler` itself, `bundle -v` will run the version of `bundler` locked in your `Gemfile.lock` file as long as it's installed.

**Comment by raxod502** [comment] 2021-05-21 01:38
Working with https://github.com/mustache/mustache, this is what I get:

```
% cat .bundle/config
---
BUNDLE_PATH: ".bundle/vendor"
% GEM_HOME=.bundle/vendor gem install bundler:1.17.3         
Fetching bundler-1.17.3.gem
Successfully installed bundler-1.17.3
Parsing documentation for bundler-1.17.3
Installing ri documentation for bundler-1.17.3
Done installing documentation for bundler after 1 seconds
1 gem installed
% bundle -v
Traceback (most recent call last):
	2: from /usr/bin/bundle:23:in `<main>'
	1: from /usr/lib/ruby/2.7.0/rubygems.rb:294:in `activate_bin_path'
/usr/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (1.17.3) required by your /home/raxod502/files/code/lib/mustache/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.17.3`
```

Are there additional steps I have to follow to get Bundler to know about where the correct version is installed, aside from setting `BUNDLE_PATH`?

**Comment by deivid-rodriguez** [comment] 2021-06-27 10:47
Sorry I dropped the ball here. Currently it's rubygems (not bundler, they are separate libraries as of now) doing the work of finding the proper bundler version. And rubygems doesn't know about `BUNDLE_PATH`. So you need to tell rubygems where to look for gems. So something like

```
GEM_HOME=.bundle/vendor GEM_PATH=.bundle/version bundle -v  
```

might do the trick.

**Comment by deivid-rodriguez** [comment] 2021-07-07 06:29
Closing for the moment since I'm not convinced there's something that should be changed on our side and I haven't yet got feedback on my last suggestion. Feel free to reopen when/if you get to this and you still believe we should change something :+1:.

**Closed by deivid-rodriguez** 2021-07-07 06:29 UTC
Labels: Bundler, status: feedback required

**Comment by raxod502** [comment] 2021-07-24 18:19
Okay, sounds good. I submitted a PR downstream accordingly: https://github.com/jonathanmorley/asdf-bundler/pull/4
