### ISSUE TITLE
Bundle command should be able to display messages from Nexus server

### ISSUE THREAD

**Issue by mifrazmify** [rubygems/rubygems#5797] opened 2022-08-01 13:36 UTC
### Describe the problem as clearly as you can
We are trying to integrate RubyGems support in our plugin which we developed for Nexus server. Our goal is to get the gems from Nexus when the `bundler install --redownload` command is initiated and send a custom message back to the terminal based on our back-end logic of the plugin.

However we have run into some issue when using the latest versions of Bundler. When we use the bundler v2.3.4 or a lower version, we were able to render the expected messages in the terminal once we execute our plugin. Following is a sample path we get trough Nexus.
`/gems/nokogiri-1.13.7.gem`

But when we use bundler v2.3.5 or above, we are not getting the expected error messages in the terminal once after the plugin is executed and getting a different error message. Also we observed that the file path also is different(please see the below path).
`/quick/Marshal.4.8/nokogiri-1.13.7.gemspec.rz`

#### Expected with bundler v2.3.5 or above
![image](https://user-images.githubusercontent.com/25836749/182146517-eb00bfa9-dc3f-465b-bc05-284ec3c7cbf5.png)

#### Actual with bundler v2.3.5 or above
![image](https://user-images.githubusercontent.com/25836749/182146840-1e084387-84a0-4dab-803c-932f0e03db59.png)

**Note:** We tried with different versions of Ruby(v3.0.4-1 and v3.1.2-1) as well as Nexus server(v3.39.0-01 and v3.40.1-01) and we found out that this issue happens because of bundler(from bundler v2.3.5 and above).

We suspect that issue is coming after introducing the `gemspec` support in bundler v2.3.5.

Will this be fixed in a upcoming release? Or else is there any workaround to display custom messages?

**Comment by deivid-rodriguez** [comment] 2022-08-01 13:48
Thanks for the report, and for isolating the Bundler version that does not work. Unfortunately, I'm going to need a way to reproduce this in order to help you. Never used a Nexus server myself, so not sure how to set that up.

**Comment by deivid-rodriguez** [comment] 2022-08-02 15:54
I see, this sounds like https://github.com/rubygems/rubygems/issues/5385. Since 2.3.5, Bundler fetches all gemspecs for custom servers not implementing the modern dependency APIs. Not sure what your RubyGems server uses under the hood, but if it's using geminabox, this will get fixed after https://github.com/geminabox/geminabox/pull/435 is merged and released.

**Comment by mifrazmify** [comment] 2022-08-02 16:04
@alzafacon: Is there a way that we can display custom http error message for `gemspec` ? or may be a compatible error code which will not override the custom http error message.

**Comment by deivid-rodriguez** [comment] 2022-08-03 11:56
Other than hoping (possibly helping too) geminabox and gemstash to move forward and implement new APIs, I don't think we can do much here. Since that's already tracked at #5385, I'll close this.

For the time being, t sounds like you should implement your plugin for gemspec endpoints too, and that would fix things for you..

**Closed by deivid-rodriguez** 2022-08-03 11:56 UTC
Labels: Bundler
