### ISSUE TITLE
Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered (3.1.2)

### ISSUE THREAD

**Issue by deepj** [rubygems/rubygems#3551] opened 2020-04-25 11:52 UTC
The original issue was reported here in https://github.com/socketry/falcon/issues/115

Some ruby gem commands such as `falcon` failing while running them with the above error. The work-around is to use `bundle exec`. Though there is no issue with downgraded `rubygems` to `3.0.x` version and I can call the command without any issue. Tested with `ruby 2.7.1` and `2.6.5`. In both cases `rubygems 3.1.2` and `bundler 2.1.4`.

```
|   ArgumentError: Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered
               |   → ~/.gem/ruby/2.7.1/gems/bundler-2.1.4/lib/bundler/errors.rb:9 in `status_code'
               |     ~/.gem/ruby/2.7.1/gems/bundler-2.1.4/lib/bundler/errors.rb:20 in `<class
               |     ~/.gem/ruby/2.7.1/gems/bundler-2.1.4/lib/bundler/errors.rb:20 in `<module
               |     ~/.gem/ruby/2.7.1/gems/bundler-2.1.4/lib/bundler/errors.rb:3 in `<top (required)>'
               |     ~/.gem/ruby/2.7.1/gems/bundler-2.1.4/lib/bundler.rb:7 in `require_relative'
               |     ~/.gem/ruby/2.7.1/gems/bundler-2.1.4/lib/bundler.rb:7 in `<top (required)>'
               |     ~/.gem/ruby/2.7.1/gems/bundler-2.1.4/lib/bundler/setup.rb:6 in `require_relative'
               |     ~/.gem/ruby/2.7.1/gems/bundler-2.1.4/lib/bundler/setup.rb:6 in `<top (required)>'
```

```
$ gem env version
3.1.2
```

**Comment by simi** [comment] 2020-04-25 12:25
I have tried to reproduce unsuccessfully.

```
[retro@retro  gemtest]❤ ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
[retro@retro  gemtest]❤ gem -v
3.1.2
[retro@retro  gemtest]❤ cat Gemfile
source 'https://rubygems.org'

gem 'falcon'
gem 'rack'
[retro@retro  gemtest]❤ cat config.ru 
# frozen_string_literal: true

run ->(env) { [200, {"Content-Type" => "text/html"}, ["Hello World!"]] }
[retro@retro  gemtest]❤ falcon serve --bind https://0.0.0.0:8000
 0.12s     info: Falcon::Command::Serve [oid=0x99c] [pid=2694020] [2020-04-25 14:25:02 +0200]
               | Falcon v0.36.4 taking flight! Using Async::Container::Forked {:count=>8}.
               | - Binding to: #<Falcon::Endpoint https://0.0.0.0:8000/ {}>
               | - To terminate: Ctrl-C or kill 2694020
               | - To reload configuration: kill -HUP 2694020
 0.27s     info: Async::Container::Process::Instance [oid=0xbcc] [pid=2694036] [2020-04-25 14:25:02 +0200]
               | - Per-process status: kill -USR1 2694036
 0.27s     info: Async::Container::Process::Instance [oid=0xbf4] [pid=2694037] [2020-04-25 14:25:02 +0200]
               | - Per-process status: kill -USR1 2694037
 0.27s     info: Async::Container::Process::Instance [oid=0xc1c] [pid=2694038] [2020-04-25 14:25:02 +0200]
               | - Per-process status: kill -USR1 2694038
 0.27s     info: Async::Container::Process::Instance [oid=0xc44] [pid=2694039] [2020-04-25 14:25:02 +0200]
               | - Per-process status: kill -USR1 2694039
 0.27s     info: Async::Container::Process::Instance [oid=0xc6c] [pid=2694040] [2020-04-25 14:25:02 +0200]
               | - Per-process status: kill -USR1 2694040
 0.27s     info: Async::Container::Process::Instance [oid=0xc94] [pid=2694041] [2020-04-25 14:25:02 +0200]
               | - Per-process status: kill -USR1 2694041
 0.27s     info: Async::Container::Process::Instance [oid=0xcbc] [pid=2694042] [2020-04-25 14:25:02 +0200]
               | - Per-process status: kill -USR1 2694042
 0.27s     info: Async::Container::Process::Instance [oid=0xce4] [pid=2694043] [2020-04-25 14:25:02 +0200]
               | - Per-process status: kill -USR1 2694043
```

Any idea how to reproduce?

**Comment by deivid-rodriguez** [comment] 2020-04-25 12:30
I think this might be another instance of the bundler gemspec issue in ruby 2.7.

Could you try downgrade and upgrade rubygems back and see if it fixes the issue?

`gem update --system 3.0.8 && gem update --system`.

**Comment by deepj** [comment] 2020-04-25 22:41
@deivid-rodriguez Yes, it helped before as I wrote about downgrading in my original post. But I guess the problem lies/led in something else.

When you look at the original post https://github.com/socketry/falcon/issues/115. The log is full of these warnings:

```
~/.gem/ruby/2.7.1/gems/bundler-2.1.4/lib/bundler/version.rb:4: warning: already initialized constant Bundler::VERSION
~/.rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/version.rb:4: warning: previous definition of VERSION was here
~/.gem/ruby/2.7.1/gems/bundler-2.1.4/lib/bundler/constants.rb:4: warning: already initialized constant Bundler::WINDOWS
~/.rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/constants.rb:4: warning: previous definition of WINDOWS was here
~/.gem/ruby/2.7.1/gems/bundler-2.1.4/lib/bundler/version.rb:4: warning: already initialized constant Bundler::VERSION
~/.rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/version.rb:4: warning: previous definition of VERSION was here
~/.gem/ruby/2.7.1/gems/bundler-2.1.4/lib/bundler/constants.rb:4: warning: already initialized constant Bundler::WINDOWS
~/.rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/constants.rb:4: warning: previous definition of WINDOWS was here
```

This went gone when I removed all gems by mistake and install them again. Now I can't reproduce the problem above + no these warnings are shown.

I use `ruby-build` + `chruby` combo. So nothing weird things come from `rvm`.

Though, I don't know. @ioquatix said he has some similar issues as well. I'm not sure. Maybe close this?

**Comment by ioquatix** [comment] 2020-04-26 07:32
I've had the same issue, easy to reproduce locally.

**Comment by simi** [comment] 2020-04-26 10:18
@ioquatix and how?

**Comment by deivid-rodriguez** [comment] 2020-04-26 10:45
@deepj I noticed in the initial report that you had downgraded but my workaround is to downgrade _and upgrade back_.

The underlying idea is that there's a problem specific to the bundler gemspec that comes with ruby 2.7, but since the rubygems installer installs its own copy of the default bundler gem, it "heals" things. However, if you're using the latest version already, `gem update --system` will do nothing, hence the recommendation to downgrade first.

You can also double check if this is the problem you're hitting by inspecting the default `bundler` gemspec being used and check whether it includes `s.bindir = libexec`, which is the specific bit of the gemspec provided by ruby causing trouble.

**Comment by ioquatix** [comment] 2020-04-26 23:06
Sorry, it was easy to reproduce a few days ago but looks like gem updates has fixed the issue some how. If I can get back to the state that every command without bundle exec causes the issue, I'll report back here! Sorry for the misfire.

**Comment by ioquatix** [comment] 2020-04-27 01:05
Oh, it's still happening:

```
koyoko% bake utopia:wiki:serve
/home/samuel/.gem/ruby/2.7.1/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: already initialized constant Bundler::FileUtils::VERSION
/home/samuel/.rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: previous definition of VERSION was here
/home/samuel/.gem/ruby/2.7.1/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: already initialized constant Bundler::FileUtils::Entry_::S_IF_DOOR
/home/samuel/.rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: previous definition of S_IF_DOOR was here
/home/samuel/.gem/ruby/2.7.1/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: already initialized constant Bundler::FileUtils::Entry_::DIRECTORY_TERM
/home/samuel/.rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: previous definition of DIRECTORY_TERM was here
/home/samuel/.gem/ruby/2.7.1/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: already initialized constant Bundler::FileUtils::OPT_TABLE
/home/samuel/.rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: previous definition of OPT_TABLE was here
/home/samuel/.gem/ruby/2.7.1/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: already initialized constant Bundler::FileUtils::LOW_METHODS
/home/samuel/.rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: previous definition of LOW_METHODS was here
/home/samuel/.gem/ruby/2.7.1/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: already initialized constant Bundler::FileUtils::METHODS
/home/samuel/.rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: previous definition of METHODS was here
Traceback (most recent call last):
	9: from /home/samuel/.gem/ruby/2.7.1/bin/bundle:23:in `<main>'
	8: from /home/samuel/.gem/ruby/2.7.1/bin/bundle:23:in `load'
	7: from /home/samuel/.gem/ruby/2.7.1/gems/bundler-2.1.4/exe/bundle:13:in `<top (required)>'
	6: from /home/samuel/.gem/ruby/2.7.1/gems/bundler-2.1.4/exe/bundle:13:in `require_relative'
	5: from /home/samuel/.gem/ruby/2.7.1/gems/bundler-2.1.4/lib/bundler.rb:7:in `<top (required)>'
	4: from /home/samuel/.gem/ruby/2.7.1/gems/bundler-2.1.4/lib/bundler.rb:7:in `require_relative'
	3: from /home/samuel/.gem/ruby/2.7.1/gems/bundler-2.1.4/lib/bundler/errors.rb:3:in `<top (required)>'
	2: from /home/samuel/.gem/ruby/2.7.1/gems/bundler-2.1.4/lib/bundler/errors.rb:20:in `<module:Bundler>'
	1: from /home/samuel/.gem/ruby/2.7.1/gems/bundler-2.1.4/lib/bundler/errors.rb:20:in `<class:GemfileError>'
/home/samuel/.gem/ruby/2.7.1/gems/bundler-2.1.4/lib/bundler/errors.rb:9:in `status_code': Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered (ArgumentError)
```

**Comment by deivid-rodriguez** [comment] 2020-04-27 12:13
So I should assume that the workaround has been applied in that situation, and it still doesn't work, right?

**Comment by ioquatix** [comment] 2020-04-28 04:50
To be honest, I'm not really sure why it's happening. I have tons of different environments and I can't say for sure that this environment has any workaround applied. Sorry, I wish it was simpler but it's not. When I have some time, I'll try to dig into this issue a bit more.

**Comment by deivid-rodriguez** [comment] 2020-04-28 10:23
Next time you run into it, you can run ` ruby -e 'puts eval(File.read(Dir.glob("#{Gem.default_specifications_dir}/bundler-*.gemspec").first)).bindir'`. If it prints `libexec` instead of `exe`, then it might be the issue I'm talking about and the workaround given should fix it. If it prints `exe`, then it's not the same issue and we treat this as a separate problem.

**Comment by ioquatix** [comment] 2020-04-28 13:05
It prints `libexec` - so the solution is to.. uninstall and reinstall bundler?

**Comment by ioquatix** [comment] 2020-04-28 13:10
Okay I confirm

```
gem update --system 3.0.8 && gem update --system
```

solved my problem! Thanks!

**Comment by deivid-rodriguez** [comment] 2020-04-28 13:40
Great, closing this ticket then!

@hsbt Could you release 3.1.3 including https://github.com/rubygems/rubygems/pull/3458? I'm also happy to do it myself if you're too busy at the moment.

**Closed by deivid-rodriguez** 2020-04-28 13:40 UTC
Labels: Rubygems

**Comment by hsbt** [comment] 2020-04-28 22:35
I'm going to release 3.1.3 after working https://github.com/rubygems/rubygems/pull/3545

**Comment by deivid-rodriguez** [comment] 2020-04-29 09:25
That's great @hsbt, thank you!

**Comment by schinery** [comment] 2020-06-17 14:11
> I think this might be another instance of the bundler gemspec issue in ruby 2.7.
> 
> Could you try downgrade and upgrade rubygems back and see if it fixes the issue?
> 
> `gem update --system 3.0.8 && gem update --system`.

Encountered this error after upgrading a Rails project to Ruby 2.7.1 and this fixed things for me... so many thanks for sharing 👍

**Comment by deivid-rodriguez** [comment] 2020-06-17 15:06
Note that downgrading first is no longer necessary now that we've released the fix. Just running `gem update --system` should do the trick.

**Comment by andie-chernysh** [comment] 2020-08-12 11:52
> Note that downgrading first is no longer necessary now that we've released the fix. Just running `gem update --system` should do the trick.

No, it doesn't for me.

**Comment by deivid-rodriguez** [comment] 2020-08-27 08:46
@andie-chernysh I have no idea why that is :man_shrugging:

**Comment by electronicbites** [comment] 2021-01-27 19:26
Why was this ticket closed? I am having still having big problems with this issue.

**Comment by lyleLH** [comment] 2021-09-23 04:14
> I think this might be another instance of the bundler gemspec issue in ruby 2.7.
> 
> Could you try downgrade and upgrade rubygems back and see if it fixes the issue?
> 
> `gem update --system 3.0.8 && gem update --system`.

It solved my problem,thanks

**Comment by Luiyit** [comment] 2021-12-07 21:57
Worked for me @hsbt.
Tthank you!

**Comment by ddoherty03** [comment] 2022-09-30 20:13
If it helps anyone, I was still getting this error after upgrading gem on ruby 2.7.2 on ubuntu 22.04, but was finally able to get it to work after removing the Gemfile.lock in my project.
