### ISSUE TITLE
Can't install gems 

### ISSUE THREAD

**Issue by IsaiahPatton** [rubygems/rubygems#1794] opened 2016-12-03 02:40 UTC
I'm having a problem or would like to suggest a feature.

My current problem is: I can't install gems.
**Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)**

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.5.1
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment] 2016-12-03 04:43
This is a duplicate of https://github.com/rubygems/rubygems/issues/1758

**Closed by bronzdoc** 2016-12-03 04:43 UTC
Labels: status: triage
