### ISSUE TITLE
Ruby 2.3 (rubygems 2.5) Gem.datadir returns wrong directory when referring to gem data directory

### ISSUE THREAD

**Issue by davidsiaw** [rubygems/rubygems#1673] opened 2016-07-21 10:19 UTC
I'm having a problem 

My current problem is: in Ruby 2.2.2 (rubygems 2.4) I used to be able to refer to a gem's source directory in Gemfile, for example "/Users/david/programs/weaver", and Gem.datadir would return the data directory in that dir "/Users/david/programs/weaver/data/weaver".

However that changed in Ruby 2.3  (rubygems 2.5), after changing to Ruby 2.3, all of a sudden it started returning a different directory: "/Users/david/programs/gems/weaver-0.3.4/data/weaver"

The "gems" directory does not (and should not) even exist, and I never created one, and the output of pwd when checking Gem.datadir is "/Users/david/programs/weaver-doc-source"

I have checked the changelogs and could not find any mention of changes to the Gem class that should affect this

This seems like a piece of debug code has made it into the Gem class.

This is not apparently a bundler issue since it does not happen with either the version of bundler I used or the latest version of bundler. The rubygems version is the only variable of consequence here.
This issue is related to:
- [ ] Network problems
- [ ] Installing a library
- [ ] Publishing a library
- [ ] The command line `gem`
- [x] Other

Here are my current environment details:

```
$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
$ gem -v
2.4.8

$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin14]
$ gem -v
2.5.1
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by davidsiaw** [comment] 2016-07-30 00:26
If this will help any, I have made a very simple test case to demonstrate this bug's failure

https://github.com/davidsiaw/gemdatadir_bug

To use it simply run:


```bash
git clone https://github.com/davidsiaw/gemdatadir_bug
cd gemdatadir_bug
bundle
bundle exec gemdatadir_bug
```

The resulting output of gemdatadir_bug is either PASS or FAIL, where PASS means the behaviour is expected and FAIL means it has changed to something unexpected.

**Comment by skopciewski** [comment] 2016-10-07 11:07
I notice the same problem (ruby ruby 2.3.1p112, gem 2.5.1). Does anyone know what can be done here?

**Comment by skopciewski** [comment] 2016-10-07 12:48
Quick fix:
in: https://github.com/rubygems/rubygems/blob/v2.5.1/lib/rubygems/basic_specification.rb#L153
```
  def datadir
# TODO: drop the extra ", gem_name" which is uselessly redundant
    #File.expand_path(File.join(gems_dir, full_name, "data", name)).untaint
    File.join full_gem_path, "data", name
  end
```

**Comment by duckinator** [comment] 2016-10-14 23:43
It looks like this is the commit that would have caused this change: https://github.com/rubygems/rubygems/commit/1a33f7d77b746f0429d08abc7a9ba80158156173

I can confirm it changed between 2.4 and 2.5, and hasn't been fixed in 2.6.

**Comment by luxflux** [comment] 2016-10-21 11:59
This (hacky) workaround helps a bit:
```patch
-gemrootdir = File.expand_path('../../', Gem.datadir('gemdatadir_bug'))
+gemrootdir = Gem.loaded_specs['gemdatadir_bug'].full_gem_path
```

**Comment by bronzdoc** [comment] 2018-06-22 15:54
@duckinator this can be closed?

**Closed** 2018-06-22 20:44 UTC
Labels: type: bug report
