### ISSUE TITLE
ERROR:  While executing gem ... (Errno::EINVAL) Invalid argument

### ISSUE THREAD

**Issue by yss14** [rubygems/rubygems#1726] opened 2016-09-30 08:04 UTC
I'm having a problem with gem on mac os x 10.11.6.

My current problem is I am not able to install any gems.

E.g.
```
gem install xcodeproj
ERROR:  While executing gem ... (Errno::EINVAL)
    Invalid argument
```

This issue is related to:

  - [x ] The command line `gem`

Here are my current environment details:
  - mac os x 10.11.6
  - ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```
$ gem env version
2.6.7
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment] 2016-09-30 11:28
What is the output installing with `--verbose --backtrace`? Thanks!

**Comment by yss14** [comment] 2016-09-30 11:51
gem install xcodeproj --verbose --backtrace
ERROR:  While executing gem ... (Errno::EINVAL)
    Invalid argument
	/usr/local/Cellar/ruby/2.3.1_1/lib/ruby/2.3.0/resolv.rb:672:in 'clock_gettime'
	/usr/local/Cellar/ruby/2.3.1_1/lib/ruby/2.3.0/resolv.rb:672:in 'request'
	/usr/local/Cellar/ruby/2.3.1_1/lib/ruby/2.3.0/resolv.rb:531:in 'block in fetch_resource'
	/usr/local/Cellar/ruby/2.3.1_1/lib/ruby/2.3.0/resolv.rb:1103:in 'block (3 levels) in resolv'
	/usr/local/Cellar/ruby/2.3.1_1/lib/ruby/2.3.0/resolv.rb:1101:in 'each'
	/usr/local/Cellar/ruby/2.3.1_1/lib/ruby/2.3.0/resolv.rb:1101:in 'block (2 levels) in resolv'
	/usr/local/Cellar/ruby/2.3.1_1/lib/ruby/2.3.0/resolv.rb:1100:in 'each'
	/usr/local/Cellar/ruby/2.3.1_1/lib/ruby/2.3.0/resolv.rb:1100:in 'block in resolv'
	/usr/local/Cellar/ruby/2.3.1_1/lib/ruby/2.3.0/resolv.rb:1098:in 'each'
	/usr/local/Cellar/ruby/2.3.1_1/lib/ruby/2.3.0/resolv.rb:1098:in 'resolv'
	/usr/local/Cellar/ruby/2.3.1_1/lib/ruby/2.3.0/resolv.rb:522:in 'fetch_resource'
	/usr/local/Cellar/ruby/2.3.1_1/lib/ruby/2.3.0/resolv.rb:512:in 'each_resource'
	/usr/local/Cellar/ruby/2.3.1_1/lib/ruby/2.3.0/resolv.rb:493:in 'getresource'
	/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/remote_fetcher.rb:105:in 'api_endpoint'
	/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/source.rb:47:in 'api_uri'
	/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/source.rb:86:in 'dependency_resolver_set'
	/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/resolver/best_set.rb:24:in 'block in pick_sets'
	/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/source_list.rb:98:in 'each'
	/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/source_list.rb:98:in 'each_source'
	/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/resolver/best_set.rb:23:in 'pick_sets'
	/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/resolver/best_set.rb:29:in 'find_all'
	/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/resolver/installer_set.rb:156:in 'find_all'
	/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/resolver/installer_set.rb:55:in 'add_always_install'
	/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/dependency_installer.rb:474:in 'resolve_dependencies'
	/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:194:in 'install_gem'
	/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:255:in 'block in install_gems'
	/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:251:in 'each'
	/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:251:in 'install_gems'
	/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:158:in 'execute'
	/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/command.rb:310:in 'invoke_with_build_args'
	/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/command_manager.rb:169:in 'process_args'
	/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/command_manager.rb:139:in 'run'
	/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/gem_runner.rb:55:in 'run'
	/usr/local/bin/gem:21:in '<main>'

**Comment by josephfrazier** [comment] 2016-09-30 13:47
I'm having the same problem. For what it's worth, I'm using [Homebrew](http://brew.sh/)'s ruby, and the problem still occurs even after uninstalling and reinstalling it. I even tried installing `gem` manually from cloning this repo.

**Comment by josephfrazier** [comment] 2016-09-30 14:03
Upon further investigation, this appears to be related to (or a duplicate of) https://github.com/Homebrew/homebrew-core/issues/5413

**Comment by holybit** [comment] 2016-09-30 15:28
Same issue here. Is there a PR in the works?

**Comment by yss14** [comment] 2016-10-02 07:39
As @josephfrazier has already mentioned [https://github.com/Homebrew/homebrew-core/issues/5413](url) works pretty well for me. Just re-installed ruby via homebrew from source.

**Closed** 2016-10-02 07:39 UTC
Labels: status: triage
