### ISSUE TITLE
`bundle package --all` only works once! (when not set in config)

### ISSUE THREAD

**Issue by hatkyinc2** [rubygems/rubygems#3896] opened 2020-08-24 01:34 UTC
### Describe the problem as clearly as you can
`bundle package --all` only works once! (when not set in config)
```
> bundle package --all
Using rake 13.0.1
Using concurrent-ruby 1.1.7
...
Updating files in vendor/cache
Bundle complete! 8 Gemfile dependencies, 22 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Updating files in vendor/cache
> bundle package --all
Unknown switches "--all"
> rm .bundle/config
> bundle package --all
Using rake 13.0.1
Using concurrent-ruby 1.1.7
...
Updating files in vendor/cache
Bundle complete! 8 Gemfile dependencies, 22 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Updating files in vendor/cache
```

### What were you expecting to happen?
Either let is work, or have a proper message of setting is already set in .bundle/config
(There is a lot of confusion with the docs saying to use switches and the command saying they are going to be deprecated and you should use `bundle config set`)

### What actually happened?
Error message
`Unknown switches "--all"`

### If not included with the output of your command, run `bundle env` and paste the output below
```
> bundle -v
Bundler version 2.1.4
> ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
>rbenv -v
rbenv 1.1.2-30-gc879cb0
```

**Comment by deivid-rodriguez** [comment] 2020-08-28 15:46
Thanks for the report. This is a duplicate of https://github.com/rubygems/rubygems/issues/3598, so I'll close this ticket in favor of that one, since it already has some discussion. I'll have a look at it now.

**Closed by deivid-rodriguez** 2020-08-28 15:46 UTC
Labels: Bundler

**Comment by deivid-rodriguez** [comment] 2020-09-02 12:51
@hatkyinc2 This should be fixed by https://github.com/rubygems/rubygems/pull/3914, in case you want to give that a try.
