### ISSUE TITLE
On-demand install of specific bundler version does not honor shebang settings

### ISSUE THREAD

**Issue by headius** [rubygems/rubygems#5523] opened 2022-05-09 09:45 UTC
JRuby on MacOS request the shebang for installed Ruby binscripts to use the "env shebang" due to the way that script executables get resolved. However, when Bundler installs the correct version for a given Gemfile.lock  on demand, it does not honor our default behavior of using env shebangs. This results in it breaking the `bundle` executable, due to the shebang line pointing directly at the bin/jruby shell script, and producing the following errors:

```
$ bundle
Bundler 2.3.3 is running, but your lockfile was generated with 2.2.29. Installing Bundler 2.2.29 and restarting using that version.
/Users/headius/projects/jruby/bin/bundle: line 9: require: command not found
/Users/headius/projects/jruby/bin/bundle: line 11: version: command not found
/Users/headius/projects/jruby/bin/bundle: line 13: str: command not found
/Users/headius/projects/jruby/bin/bundle: line 15: syntax error near unexpected token `('
/Users/headius/projects/jruby/bin/bundle: line 15: `  str = str.b[/\A_(.*)_\z/, 1]'
```

The errors here then immediately appear for all future invocations of `bundle`.

Bundler should honor the RubyGems default install flags for the current Ruby when installing bundler on demand.

**Comment by deivid-rodriguez** [comment] 2022-05-09 18:42
@headius I made some testing with JRuby on my Mac and I couldn't reproduce this. Can you share steps so that I can reproduce this and fix it?

**Comment by headius** [comment] 2022-05-09 18:44
@deivid-rodriguez I will try to come up with a simple scenario, but I believe it is when attempting to bundle install a Gemfile where the Gemfile.lock references an earlier (or just different?) bundler version.

**Comment by deivid-rodriguez** [comment] 2022-05-09 18:49
I did try that, also making sure that `--env-shebang` setting was in place, but everything worked fine.

**Comment by headius** [comment] 2022-05-09 18:51
Gemfile:

```ruby
source 'https://rubygems.org'

gem 'rake'
```

Bundle using an earlier version (2.2.29 in this case):

```
[] ~/projects/jruby-9.3 $ bundle -v
Bundler version 2.2.29

[] ~/projects/jruby-9.3 $ cd ../jruby/tmp

[] ~/projects/jruby/tmp $ bundle
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 13.0.6
Using bundler 2.2.29
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

Rebundle with an env that only has a newer Bundler installed:

```
[] ~/projects/jruby $ bundle -v
Bundler version 2.3.3

[] ~/projects/jruby $ cd tmp

[] ~/projects/jruby/tmp $ bundle
Bundler 2.3.3 is running, but your lockfile was generated with 2.2.29. Installing Bundler 2.2.29 and restarting using that version.
/Users/headius/projects/jruby/bin/bundle: line 9: require: command not found
/Users/headius/projects/jruby/bin/bundle: line 11: version: command not found
/Users/headius/projects/jruby/bin/bundle: line 13: str: command not found
/Users/headius/projects/jruby/bin/bundle: line 15: syntax error near unexpected token `('
/Users/headius/projects/jruby/bin/bundle: line 15: `  str = str.b[/\A_(.*)_\z/, 1]'

[] ~/projects/jruby/tmp $ bundle
/Users/headius/projects/jruby/bin/bundle: line 9: require: command not found
/Users/headius/projects/jruby/bin/bundle: line 11: version: command not found
/Users/headius/projects/jruby/bin/bundle: line 13: str: command not found
/Users/headius/projects/jruby/bin/bundle: line 15: syntax error near unexpected token `('
/Users/headius/projects/jruby/bin/bundle: line 15: `  str = str.b[/\A_(.*)_\z/, 1]'
```

The `bundle` command is now broken because it has been installed with a shebang pointing at the JRuby shell script:

```
[] ~/projects/jruby/tmp $ head -5 `which bundle`
#!/Users/headius/projects/jruby/bin/jruby
#
# This file was generated by RubyGems.
#
# The application 'bundler' is installed as part of a gem, and
```

**Comment by headius** [comment] 2022-05-09 18:52
Of course this is on JRuby, without the jruby-launcher native executable installed. rvm installs jruby-launcher by default, I believe, so you may not be able to reproduce that way. And of course, this is a MacOS problem.

**Comment by deivid-rodriguez** [comment] 2022-05-09 18:55
Yes, I explicitly removed `jruby-launcher` to try get this to reproduce. I use `rbenv` but I think it also installs `jruby-launcher` by default.

**Comment by headius** [comment] 2022-05-09 18:58
Reinstalling bundler fixes the shebang, so I know my local setup is using env-shebangs:

```
[] ~/projects/jruby/tmp $ gem install bundler
Fetching bundler-2.3.13.gem
Successfully installed bundler-2.3.13
Parsing documentation for bundler-2.3.13
Installing ri documentation for bundler-2.3.13
Done installing documentation for bundler after 1 seconds
1 gem installed

[] ~/projects/jruby/tmp $ head -5 `which bundle`
#!/usr/bin/env jruby
#
# This file was generated by RubyGems.
#
# The application 'bundler' is installed as part of a gem, and
```

**Comment by deivid-rodriguez** [comment] 2022-05-09 19:08
Yeah, I understand. If you can't share steps to reproduce, can you share the result of `gem env` and `gem list` to see if it sparks some ideas.

**Comment by headius** [comment] 2022-05-10 07:39
Didn't I share steps to reproduce above?

**Comment by deivid-rodriguez** [comment] 2022-05-10 07:51
Yes, you did, what I meant is that the steps you have shared so far seem very dependent on your environment, since I can't reproduce the issue on my machine by following them.

I'm guessing I need to install JRuby from source instead of using a version manager to mimic your environment so that the JRuby executable is a shell script? Is there any other way to run into this that does not involve installing JRuby from source?

**Comment by headius** [comment] 2022-05-10 08:15
Oh I understand. I will show a session from downloading JRuby to reproduction.

**Comment by deivid-rodriguez** [comment] 2022-05-10 09:00
No worries, I'm glad it's fixed! I'll close this then!

**Closed by deivid-rodriguez** 2022-05-10 09:00 UTC
Labels: Bundler

**Comment by headius** [comment] 2022-05-10 10:30
Looks like this was something fixed on the bundler side, FYI. After upgrading JRuby's rubygems to 3.3.13 but leaving Bundler at 3.3.3 I still have the problem, but upgrading both fixes it.

**Comment by deivid-rodriguez** [comment] 2022-05-10 10:34
Thanks! Makes sense.
