### ISSUE TITLE
Incorrect resolution related to required_ruby_version on macOS on Ruby 2.3

### ISSUE THREAD

**Issue by eregon** [rubygems/rubygems#3463] opened 2020-03-30 10:16 UTC
- [x] You checked all the following documents and couldn't find a solution for your issue:

- [Troubleshooting common issues](https://github.com/rubygems/bundler/blob/master/doc/TROUBLESHOOTING.md)
- [Bundler documentation site](https://bundler.io/)
- [Bundler man pages](https://bundler.io/man/bundle.1.html)
- [Bundler command line reference](https://bundler.io/v2.0/commands.html)

Please answer the following questions so we can process your issue as fast as possible:

1. Do you have a reproduction script? It would be really helpful for us if you provide one.

https://github.com/ffi/ffi/runs/545023910?check_suite_focus=true is essentially a reproduction script running in GitHub Actions.
Branch: https://github.com/eregon/ffi/tree/debug-bundler

3. What command did you run?

`bundle install`

5. What actually happened?

https://github.com/ffi/ffi/runs/545023910?check_suite_focus=true
```
$ bundle install
Fetching gem metadata from https://rubygems.org/..............
Resolving dependencies...
Fetching rake 13.0.1
Installing rake 13.0.1
Using bundler 2.1.4
Fetching diff-lcs 1.3
Installing diff-lcs 1.3
Fetching io-console 0.5.6
Installing io-console 0.5.6 with native extensions
Gem::InstallError: io-console requires Ruby version >= 2.4.0.
An error occurred while installing io-console (0.5.6), and Bundler cannot
continue.
Make sure that `gem install io-console -v '0.5.6' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  rubygems-tasks was resolved to 0.2.5, which depends on
    irb was resolved to 1.2.3, which depends on
      reline was resolved to 0.1.3, which depends on
        io-console
##[error]Process completed with exit code 5.
```

However that seems transient, sometimes it seems to work, such as in https://github.com/ffi/ffi/runs/544565919?check_suite_focus=true :
```
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Fetching rake 13.0.1
Installing rake 13.0.1
Using bundler 2.1.4
Fetching diff-lcs 1.3
Installing diff-lcs 1.3
Fetching irb 1.1.1
Installing irb 1.1.1
Fetching kramdown 2.1.0
Installing kramdown 2.1.0
Fetching rake-compiler 1.0.9
Installing rake-compiler 1.0.9
Fetching rake-compiler-dock 1.0.1
Installing rake-compiler-dock 1.0.1
Fetching rspec-support 3.9.2
Installing rspec-support 3.9.2
Fetching rspec-core 3.9.1
Installing rspec-core 3.9.1
Fetching rspec-expectations 3.9.1
Installing rspec-expectations 3.9.1
Fetching rspec-mocks 3.9.1
Installing rspec-mocks 3.9.1
Fetching rspec 3.9.0
Installing rspec 3.9.0
Fetching rubygems-tasks 0.2.5
Installing rubygems-tasks 0.2.5
Fetching yard 0.9.24
Installing yard 0.9.24
Bundle complete! 8 Gemfile dependencies, 14 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

where it picks irb 1.1.1 which doesn't have the reline dependency.

7. Please run `bundle env` and paste the output below:

This is on Ruby 2.3.8 on macOS, using Bundler 2.1.4.
There is no checked-in Gemfile.lock.
On Linux it seems to not happen.

Any idea what might happen and how to workaround this?

**Comment by eregon** [comment] 2020-03-30 10:20
@postmodern FYI, I guess this might affect other users of `rubygems-tasks`, since the new dependency on `irb`.

**Comment by eregon** [comment] 2020-03-30 20:58
This error seems to also happen on Ruby 2.4 when using Bundler 1 instead of Bundler 2: https://github.com/ffi/ffi/runs/546760495?check_suite_focus=true
(On 2.3 it happens even with Bundler 2)

**Comment by deivid-rodriguez** [comment] 2020-03-30 22:11
The last similar issue I recall to this is https://github.com/rubygems/bundler/pull/6728, which got shipped with bundler 2.1.

The problem there was that when the new rubygems API errors out, we fallback to the old API, and that older API doesn't include `required_rubygems_version` information. The specific errors that the API was throwing in that case was `TooManyRequest` errors, and we fixed that by retrying one spec at a time if that happens.

So, given the coincidence in time and that we haven't had this kind of reports for a long time, I wonder if https://github.com/rubygems/rubygems.org/pull/2270 is related.

**Comment by deivid-rodriguez** [comment] 2020-03-30 22:13
You can try `bundle install --verbose` to get more information.

**Comment by eregon** [comment] 2020-04-13 17:00
I got it to reproduce in https://github.com/eregon/ffi/runs/583198256?check_suite_focus=true
```
HTTP GET https://index.rubygems.org/info/rubysl-find
HTTP 429 Too Many Requests https://index.rubygems.org/info/rubysl-find
Bundler::Fetcher::TooManyRequestsError: <html>
<head><title>429 Too Many Requests</title></head>
<body>
<center><h1>429 Too Many Requests</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
Full output in https://gist.github.com/eregon/61c5d8c1136d38112e5156fe809d2e15 in case that log disappears.

Maybe related to `rubysl` having so many dependencies?
Is it expected Bundler tries to resolve it even though it's `gem "rubysl", "~> 2.0", :platforms => 'rbx'` and I'm running on MRI?

**Comment by eregon** [comment] 2020-04-13 17:05
I think even in non-`--verbose` mode Bundler should show this kind of errors which might have a side effect such as ignoring `required_rubygems_version` and the fact it fallbacks to a different API with different behavior. It's very confusing that sometimes it works and sometimes not.

**Comment by eregon** [comment] 2020-04-13 17:11
Quite a few gems (e.g., `spicycode-rcov`) seem considered and queried even though they don't end up in Gemfile.lock, so they must be unrelated. That's probably the same as bug #3345.

**Comment by deivid-rodriguez** [comment] 2020-04-13 17:14
@sonalkr132 Do you think this could be related to https://github.com/rubygems/rubygems.org/pull/2270?

We never had this kind of errors since we started falling back to fetching specs sequentially from the compact index API if requesting them in parallel leads to 429's. That has worked fine so far and we didn't get any reports about this at all until a few hours after the rubygems.org PR was merged.

Given the coincidence in time, and that the PR seems to change the request per second limits to start responding with 429's, I think it could be related.

**Comment by sonalkr132** [comment] 2020-04-13 19:25
The PR does change request per second limits but not for dependency endpoints (including compact index).
We have [rate limits on nginx](https://guides.rubygems.org/rubygems-org-api/#rate-limits) which would be applicable for all endpoints. Github builds could be hitting that, will check nginx logs and look for increase in 429.

cc: @dwradcliffe

**Comment by sonalkr132** [comment] 2020-04-13 19:33
> any report**s**

Please let me know if there are any other open issue related to this. I only see this, it would be nice to verify is this issue exists only for github build env or other place as well.

**Comment by deivid-rodriguez** [comment] 2020-04-13 20:32
Thanks @sonalkr132! :heart:

> Please let me know if there are any other open issue related to this. I only see this, it would be nice to verify is this issue exists only for github build env or other place as well.

We only have this one at the moment. We had more reports about it in the past (for example, https://github.com/rubygems/bundler/issues/6471 or https://github.com/rubygems/bundler/issues/6639), but none since https://github.com/rubygems/bundler/pull/6728 was shipped. Those older reports not related to github build env, because it didn't exist back then I believe.

**Comment by eregon** [comment] 2020-04-13 22:47
@deivid-rodriguez With https://github.com/rubygems/bundler/pull/6728 shouldn't we be safe from going to the fallback of the old API ignoring `required_ruby_version`? Or is there something like a 2-levels fallback and latest Bundler 2 might still fallback to the old API not supporting `required_ruby_version`?

**Comment by deivid-rodriguez** [comment] 2020-04-14 13:34
@eregon I believe there's still two levels fallback.

My PR would add one level of fallback where, if fetching specs in parallel from the new API leads to 429's from the server, bundler would retry still against the new API but fetching specs sequentially (which should be less requests per second, and thus less likely to be rate limited). But if that's rate limited too, the fallback to use the old API is still there.

**Comment by eregon** [comment] 2020-04-15 07:30
I see. Do you think we could show a warning when going to the fallback of the old API since that affects semantics?

**Comment by deivid-rodriguez** [comment] 2020-04-15 10:45
Yeah, I was having the same thought.

But I have hesitations since I really don't like non actionable warnings, specially when they hit all users, including the ones not being bothered by the current behaviour (those cases when the old API leads the same behaviour, or to a different but also correct resolution).

I guess it could be useful in the cases where end users report the warning to us, so we can find outa bit about how frequent it is, but it sounds like maybe being too annoying in order to find out some information that can better be gathered server side?

In my opinion, we should investigate this on the server side:

* How frequent is this fallback?
* Why does the old API not rate limit requests? Or does it have more relaxed limits? Or maybe rate limits are just not hit because it's less used since it's only a fallback?

I believe that we should make sure the new API is good enough to resolve realworld gemfiles and once we get to the point where we no longer get issues about this, and we observe no more fallbacks on the server side, then completely phase it out.

I'll open a ticket at rubygems.org about this.

**Comment by sonalkr132** [comment] 2020-04-15 22:20
Hey, we made some progress in debugging this. You are hitting the rate limit we have set on Nginx. To be specific, `info` endpoint is hitting [rate limit of 10 r/s (per IP)](https://guides.rubygems.org/rubygems-org-api/#rate-limits). Overall, ~0.3% of the total requests seem to be hitting this limit. We have increased the limit to 20 r/s, and it has reduced 429 count to half in the last few hours. We are monitoring the load on our servers and will probably relax this limit further.

These limits are in place for protection from abuse. It is not safe to expose our app endpoints with no limits (or too relaxed limits).

>  Why does the old API not rate limit requests? Or does it have more relaxed limits?

Yes, it has slightly more relaxed limits. v1 works without 429s because we can request dependencies for [multiple gems in single request](https://guides.rubygems.org/rubygems-org-api/#get---apiv1dependenciesgemscomma-delimited-gem-names), however with compact index we have to make `/info/gem_name` for each gem. This means compact index makes way more requests to the server than v1 by design [2]. I did a quick tcpdump analysis (for some reason --verbose wasn't showing all requests for me) and for rubygems.org Gemfile (and no local cache) I am seeing following numbers:
```
$ sed -i 's/https/http/' Gemfile && bundle install
$ sudo tcpdump -i wlp3s0 host 151.101.64.70 or 151.101.0.70 or 151.101.192.70 or 151.101.128.70 -w default.pcap

# compact index/default
$  tcpdump -A -r default.pcap | grep "HTTP: GET /info"  | wc -l
1030

# compact index disabled [1]
$ tcpdump -A -r v1.pcap | grep "HTTP: GET /api/v1/dependencies"  | wc -l
20
```
We are looking into a more elegant fix for this on the server-side. Andre suggested [net-http-persistent]( https://github.com/drbrain/net-http-persistent) could help with cutting down the number of requests made by the client. @deivid-rodriguez may be better person to evaluate this if he has time (and perhaps verify the numbers I quoted above).
For the time being, I would suggest making sure `bundler install` is cached across builds.

[1] added `return false` [here](https://github.com/rubygems/bundler/blob/master/lib/bundler/shared_helpers.rb#L193)
[2] check [this blog](https://andre.arko.net/2014/03/28/the-new-rubygems-index-format/) and talks Andre gave around the time if you like to know more about compact index.

**Comment by deivid-rodriguez** [comment] 2020-04-16 10:09
Wow, thanks a lot of that @sonalkr132, that's super helpful. Doubling the limit doesn't fix the issue once and for all, but it should make this kind of report even less rare.

I'm thinking that maybe for a definitive fix, we could add a second fetcher with more priority than the old API that rate limits requests to the API. It that works out well, and we get no more rate limited requests from bundler, we could finally phase out the old API.

**Comment by deivid-rodriguez** [comment] 2020-04-16 10:12
When I say "phase out", I mean stop using it in bundler. Obviously turning it off completely would require a slower process.

**Comment by eregon** [comment] 2020-04-16 19:28
Thanks for the investigation!

I wonder why this happens so little, maybe GitHub Actions machines tend to have a very fast connection, and/or maybe multiple runners share the same IP?

10 requests/second seems really small given for even simple Gemfiles there are easily 100+ gems. Maybe Bundler has some internal concurrency limit to avoid starting the 100+ connections at once?

Unfortunately, caching the result of `bundle install` is quite verbose in GitHub Actions, and so I think few people use it: https://github.com/ruby/setup-ruby/blob/master/README.md#caching-bundle-install
I'd like to integrate automatic caching in ruby/setup-ruby, but that needs https://github.com/actions/cache/issues/55

**Comment by dentarg** [comment] 2020-04-16 20:13
> Unfortunately, caching the result of `bundle install` is quite verbose in GitHub Actions

And not all events can make use of the cache: https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache (e.g. you have builds triggered by the [`schedule` event](https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule))

**Comment by deivid-rodriguez** [comment] 2020-09-01 13:06
Just updating this issue with the new findings. We have identified one case where the fallback is still incorrectly happening thanks to @pirj. See https://github.com/rspec/rspec-rails/pull/2366#issuecomment-667741176.

The logs there show some `Net::OpenTimeout: execution expired` errors that could maybe be related to the ipv6 problem we want to fix in https://github.com/rubygems/rubygems/pull/2662.

I'll tentatively close the resolution of this issue to that ticket.

**Comment by sonalkr132** [comment] 2020-09-01 14:27
> https://github.com/ffi/ffi/runs/545023910?check_suite_focus=true is essentially a reproduction script running in GitHub Actions.
Branch: https://github.com/eregon/ffi/tree/debug-bundler

Is this still the main issue? If so, I ran the same build here https://github.com/sonalkr132/ffi/runs/1056729819 and it seems to be passing.

**Comment by deivid-rodriguez** [comment] 2020-09-01 15:10
I guess it's intermittent right now?

**Comment by eregon** [comment] 2020-09-01 18:05
Yes I think it was transient although fairly frequent on 2.3, and less frequent on 2.4.

**Comment by sonalkr132** [comment] 2020-09-01 18:16
Would it be possible to share a link to the failed build which ran after 17 Aug? It would really helpful for us to confirm if this is still an issue. We have made two fixes related to this on the service side for this, first was of [removing unnecessary dependencies](https://github.com/rubygems/rubygems.org/issues/19060) and second was of [backfilling missing required_ruby_version](https://github.com/rubygems/rubygems.org/pull/2474).
Additionally, fallback to v1 dependency because of the rate limit on the info endpoint is not expected at the moment.

**Comment by pirj** [comment] 2020-09-01 21:07
Thanks for tackling those nasty issues!

Removed all workarounds https://github.com/rspec/rspec-rails/pull/2379. This pull removes all workarounds from the `3-9-maintenance` branch. That branch supports and builds on CI for as low as Ruby 1.8.7 and all the older gem versions, starting from Rails 3.0, up to Rails 6 with Ruby 2.6.
It may fail at first if I've removed something necessary. I'm going to run the build several times to check if it's stable.
For Ruby 2.2, we:
```
    gem update --system '2.7.10'
    gem install bundler -v '1.17.3'
```


A companion change for the `main` branch https://github.com/rspec/rspec-rails/pull/2380 that is for the latest `rspec-rails` (Ruby 2.2+, Rails 5.0+).

If those two passes, I'll also send pulls for `rspec-core`, `rspec-expectations`, `rspec-mocks`, `rspec-support`, `rspec-collection_matchers` that have similar workarounds.

**Comment by pirj** [comment] 2020-10-12 16:33
Yet another change to remove the previously needed workarounds https://github.com/rspec/rspec-rails/pull/2386 worked just fine.
I'm passing from removing it for other RSpec repos for now.

I guess the problem is resolved. Thanks a lot for fixing this!

**Comment by deivid-rodriguez** [comment] 2020-10-12 18:21
That's great, I'm happy you managed to remove all that code! :)

Closing this then!

**Closed by deivid-rodriguez** 2020-10-12 18:21 UTC
Labels: Bundler, status: triage
