### ISSUE TITLE
uninitialized constant Gem::Source::FileUtils

### ISSUE THREAD

**Issue by hurricup** [rubygems/rubygems#3976] opened 2020-09-29 14:54 UTC
I'm having a problem 

My current problem is: i'm unable to query for the rails gem on ruby 3.0.0-preview1

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.2.0.rc.1
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

When trying to query for the rails gem, getting an error:
```
/usr/share/rvm/bin/rvm ruby-3.0.0-preview1@untitled107 do /usr/share/rvm/rubies/ruby-3.0.0-preview1/bin/ruby -x /usr/share/rvm/rubies/ruby-3.0.0-preview1/bin/gem query --remote --details --all --prerelease --name-matches '^rails$' --verbose

*** REMOTE GEMS ***

ERROR:  While executing gem ... (NameError)
    uninitialized constant Gem::Source::FileUtils
Did you mean?  FileTest
```
Passing explicit `-r fileutils` to the ruby helps.

**Comment by deivid-rodriguez** [comment] 2020-09-29 15:16
Yes, this was fixed in https://github.com/rubygems/rubygems/commit/07e2d26a1bce2689629429be089aadbf2ae51324. You can install rubygems edge, clone this repo and run `ruby setup.rb`, and it should be ok.

**Comment by deivid-rodriguez** [comment] 2020-09-29 15:16
Closing since it's fixed on master, thanks for the report!

**Closed by deivid-rodriguez** 2020-09-29 15:16 UTC
Labels: RubyGems

**Comment by pboling** [comment] 2020-12-10 19:29
This error began happening for us immediately when the new versions dropped. 
<img width="485" alt="screen_shot_2020-12-11_at_2 25 13_am" src="https://user-images.githubusercontent.com/19505/101819843-5b4f0c00-3b58-11eb-97f5-fac4aa2b3f60.png">

Here's the error:
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/usr/local/rvm/gems/ruby-2.5.7/gems/ruby-*****-ide-0.7.2/ext
/usr/local/rvm/rubies/ruby-2.5.7/bin/ruby mkrf_conf.rb
Installing base gem
uninitialized constant Gem::Source::FileUtils
/usr/local/rvm/rubies/ruby-2.5.7/lib/ruby/site_ruby/2.5.0/rubygems/source.rb:151:in
`fetch_spec'
/usr/local/rvm/rubies/ruby-2.5.7/lib/ruby/site_ruby/2.5.0/rubygems/resolver/api_specification.rb:91:in
`spec'
/usr/local/rvm/rubies/ruby-2.5.7/lib/ruby/site_ruby/2.5.0/rubygems/resolver/installer_set.rb:77:in
`add_always_install'
/usr/local/rvm/rubies/ruby-2.5.7/lib/ruby/site_ruby/2.5.0/rubygems/dependency_installer.rb:321:in
`resolve_dependencies'
/usr/local/rvm/rubies/ruby-2.5.7/lib/ruby/site_ruby/2.5.0/rubygems/dependency_installer.rb:228:in
`install'
  mkrf_conf.rb:31:in `rescue in <main>'
  mkrf_conf.rb:24:in `<main>'

rake failed, exit code 1
```

More data that may help:
```
Step 8/80 : RUN gem update --system
 ---> Running in b708c7e11603
Updating rubygems-update
Successfully installed rubygems-update-3.2.0
Installing RubyGems 3.2.0
  Successfully built RubyGem
  Name: bundler
  Version: 2.2.0
  File: bundler-2.2.0.gem
Bundler 2.2.0 installed
RubyGems 3.2.0 installed
Regenerating binstubs
Regenerating plugins
```

and
```
Step 9/80 : RUN gem install bundler
 ---> Running in e9adeeef0725
Successfully installed bundler-2.2.0
1 gem installed
```

**Comment by pboling** [comment] 2020-12-10 21:26
@deivid-rodriguez is this a regression?  Should I open a new issue?

**Comment by hsbt** [comment] 2020-12-11 03:23
@pboling It's not regression, another issues. I created the patch for this.

https://github.com/rubygems/rubygems/pull/4124

**Comment by deivid-rodriguez** [comment] 2020-12-11 07:23
Thanks for reporting and fixing this, both!
