### ISSUE TITLE
Installation of Nokogiri fails with RubyGems 2.5.0

### ISSUE THREAD

**Issue by ervinb** [rubygems/rubygems#1389] opened 2015-11-18 09:24 UTC
Trying to install the `nokogiri` gem (version seems to be irrelevant) throws the following error while using the included libraries.
```bash
...
compiling xml_dtd.c
compiling xml_document_fragment.c
compiling xml_document.c
xml_document.c: In function ‘set_encoding’:
xml_document.c:182:12: warning: cast discards ‘__attribute__((const))’ qualifier from pointer target type [-Wcast-qual]
       free((char *) doc->encoding); /* this may produce a gcc cast warning */
            ^
xml_document.c: In function ‘canonicalize’:
xml_document.c:537:15: warning: cast discards ‘__attribute__((const))’ qualifier from pointer target type [-Wcast-qual]
       ns[i] = (xmlChar*) ptr;
               ^
compiling xml_comment.c
compiling xml_cdata.c
compiling xml_attribute_decl.c
compiling xml_attr.c
compiling nokogiri.c
compiling html_sax_push_parser.c
compiling html_sax_parser_context.c
compiling html_entity_lookup.c
compiling html_element_description.c
In file included from /home/runner/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby.h:33:0,
                 from ./nokogiri.h:33,
                 from ./html_element_description.h:4,
                 from html_element_description.c:1:
html_element_description.c: In function ‘get_description’:
html_element_description.c:252:40: warning: cast discards ‘__attribute__((const))’ qualifier from pointer target type [-Wcast-qual]
   return Data_Wrap_Struct(klass, 0, 0, (void *)description);
                                        ^
/home/runner/.rbenv/versions/2.2.2/include/ruby-2.2.0/ruby/ruby.h:1028:35: note: in definition of macro ‘Data_Wrap_Struct’
     rb_data_object_alloc((klass),(sval),(RUBY_DATA_FUNC)(mark),(RUBY_DATA_FUNC)(free))
                                   ^
compiling html_document.c
linking shared-object nokogiri/nokogiri.so
Cleaning files only used during build.
rm -rf /home/runner/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2/ext/nokogiri/tmp/x86_64-unknown-linux-gnu/ports
rmdir -p /home/runner/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2/ext/nokogiri/tmp/x86_64-unknown-linux-gnu
rm -rf /home/runner/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2/ports

No such file or directory - getcwd

Gem files will remain installed in /home/runner/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2 for inspection.
Results logged to /home/runner/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0-static/nokogiri-1.6.6.2/gem_make.out
```
By using the `--use-system-libraries` flag when initiating the installation, the issue isn't present.

Rolling back to RubyGems 2.4.8 also seems to do the trick.

```bash
$ gem update --system 2.4.8
$ gem --version
2.4.8
$ gem install nokogiri --no-ri --no-rdoc
Building native extensions.  This could take a while...
Successfully installed nokogiri-1.6.6.3
1 gem installed
```

The OS is Ubuntu 14.04 x64.

**Comment by catphish** [comment] 2016-01-11 12:18
I am also able to reproduce this. My environment uses overlayfs which I believe may be relevant to this issue.

**Comment by beanieboi** [comment] 2016-01-16 13:30
facing the same issue, is there anything we can help with? maybe revert the changes since this is a regression?

**Comment by tianon** [comment] 2016-01-16 16:14
It's a bug in overlayfs, and Nokogiri has a new RC out which removes the
code which triggers it (which I've personally successfully tested on
overlayfs).

**Comment by beanieboi** [comment] 2016-01-16 16:44
oh, ok, was just surprised that it got triggered by rubygems 2.5.0.
thanks for the clarification

**Comment by samstickland** [comment] 2016-01-21 15:31
I get this error on with Nokogiri 1.6.7.2, Rubygems 2.5.1, and Rails 2.3.0 only on Codeship. It works fine on my development box. Everything works fine with 1.6.8rc2 on Codeship.

**Comment by emaillenin** [comment] 2016-03-26 12:56
@samstickland I am getting this error in Codeship as well. How did you resolve it?

**Comment by catphish** [comment] 2016-03-26 13:43
The easiest way to resolve this error is to install the latest RC version
of Nokogiri rather than the current stable versiion.

**Comment by samstickland** [comment] 2016-03-26 14:44
@emaillenin , like catphish says, I installed 1.6.8rc2.

**Comment by emaillenin** [comment] 2016-03-27 14:51
thanks, I have just downgraded rubygems for now, since I need a stable version of nokogiri

**Comment by copiousfreetime** [comment] 2016-04-30 23:52
It appears from reading the nokogiri ticket and a few others down the path that this is an overlayfs issue that is triggered by something in a build process. Since this is not a rubygems issue I'm going to close this.

If someone can provide a reproducible test case then please reopen.

**Closed by copiousfreetime** 2016-04-30 23:52 UTC
Labels: category - install, declined

**Comment by williamkennedy** [comment] 2018-02-22 19:10
For anyone else who came across this issue on a Ubuntu 16.04.3x 64, the following worked for me.


```
sudo apt-get install build-essential patch ruby-dev zlib1g-dev liblzma-dev
```

It's the first line of the Nokogiri docs as well. I came across this issue while deploying to production. I was upgrading from Ruby 2.4.3 to Ruby 2.5.0
