### ISSUE TITLE
Bundler does not find platform specific gem

### ISSUE THREAD

**Issue by diasjorge** [rubygems/rubygems#4123] opened 2020-12-10 15:10 UTC
Today we started having some problems with our deployments, Bundler would refuse to find the google-protobuf gem.

We we're seeing this error: 

```
/var/lib/gems/2.5.0/gems/bundler-2.2.0/lib/bundler/spec_set.rb:86:in `block in materialize': Could not find google-protobuf-3.9.1 in any of the sources (Bundler::GemNotFound)"
```

Even though I could see it in the file system in this path: `vendor/bundle/ruby/2.5.0/gems/google-protobuf-3.9.1-x86_64-linux`

The Gemfile.lock was generated by bundler 2.1.4 but our system had upgraded to use bundler 2.2.0 automatically.

**Comment by diasjorge** [comment] 2020-12-10 15:13
Update: I downgraded our systems to use bundler 2.1.4 and we no longer have the issue

**Comment by deivid-rodriguez** [comment] 2020-12-10 15:27
Thanks for reporting this @diasjorge, I'll investigate what happened here because the main point of this release is better platform support :sweat_smile:.

I'll get back to this tomorrow but in the mean time if you (or someone else) can provide a repro or point me to a public CI that broke because of the release, I really appreciate it.

**Comment by diasjorge** [comment] 2020-12-10 16:28
@deivid-rodriguez I made this repository with instructions how to reproduce the bug https://github.com/diasjorge/rubygems-platform-bug

There's some missing information needed for bundle 2.2.0 in the gemfile.lock generated by a previous version. If that's the case I think it would be better for bundler to print an error about the breaking change and needing to update the Gemfile.lock file

**Comment by diasjorge** [comment] 2020-12-10 16:32
Here's a diff I see from the Gemfile.lock between versions:

```
diff --git a/Gemfile.lock b/Gemfile.lock
index 44fa2f6..cf51c94 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -2,12 +2,14 @@ GEM
   remote: https://rubygems.org/
   specs:
     google-protobuf (3.14.0)
+    google-protobuf (3.14.0-x86_64-linux)

 PLATFORMS
   ruby
+  x86_64-linux

 DEPENDENCIES
   google-protobuf

 BUNDLED WITH
-   2.1.4
+   2.2.0
```

**Comment by brettwgreen** [comment] 2020-12-10 21:13
> @deivid-rodriguez I made this repository with instructions how to reproduce the bug https://github.com/diasjorge/rubygems-platform-bug
> 
> There's some missing information needed for bundle 2.2.0 in the gemfile.lock generated by a previous version. If that's the case I think it would be better for bundler to print an error about the breaking change and needing to update the Gemfile.lock file

Having similar issue on a different gem... what's the correct way to 'update the Gemfile.lock'. I tried reinstalling all my gems but that did not fix the issue.

**Comment by diasjorge** [comment] 2020-12-10 22:41
@brettwgreen to update the Gemfile.lock you'd need to update the bundler version first and then perform a bundle install

**Comment by brettwgreen** [comment] 2020-12-10 22:47
> @brettwgreen to update the Gemfile.lock you'd need to update the bundler version first and then perform a bundle install

Yeah, I did that but had issues running a rails app. Same exact error as yours but with the bindex gem running inside a docker container. I thought maybe there was a way to rebuild the lock file to add whatever info it may have been missing. For now, I've locked to bundler 2.1.4.

**Comment by hsbt** [comment] 2020-12-10 23:04
FYI: https://github.com/rubyjs/libv8/issues/310

**Comment by Dantemss** [comment] 2020-12-10 23:53
What are the expected settings/workflow in bundler 2.2 for devs who develop/create a lockfile on one platform and need to install platform-specific gems on a server running on a different platform? I looked but couldn't find anything...

We have devs who prefer to develop on OS X and need to deploy to a linux server. The server is not able to build libv8 from source (nor do we want to spend time doing it).

Is Docker the only solution for now?

**Comment by deivid-rodriguez** [comment] 2020-12-11 08:24
Hi @diasjorge!

I'm really sorry about this issue. I failed to predict this kind of trouble. Let me explain what's going on.

In this case, bundler 2.1.4 behaviour is to lock the pure ruby alternative in the lock file, but then at installation time choose the platform specific alternative for installation. In this particular case, it works, but it's still error prone because, for example, a platform specific variant of a gem version could have different dependencies from the pure ruby variant. Without locking the specific variant that will be installed in the lock file, we can't really ensure that installation will have all dependencies met and thus will succeed.

In addition to this, if you have a lock file generated with bundler 2.1.4, and bundler is run against that lock file, we always prefer the exact version of bundler the lock file was generated with. So in theory, the final `bundle list` in your repro case should be run with `bundler 2.1.4` and should have no issues.

All the above is to try to justify why we decided to call this change a "bug fix" rather than a "breaking change".

So, why is your command failing

Behaviour regarding bundler version selection has two issues: it has gone back and forth in time, and it's currently coded inside rubygems, not in bundler, so it sometimes can have issues if you're running old rubygems. In this particular case, the exact version selection I talked about before (bundler 2.1.4 should be preferred if your lock file was generated with bundler 2.1.4) was fixed in https://github.com/rubygems/rubygems/pull/2583, which was shipped with rubygems 3.1. Unfortunately, you're running ruby 2.5, which ships with rubygems 3.0.3, hence you're getting the issue.

So... Instead of downgrading bundler to 2.1.4, you can upgrade either rubygems or ruby itself, and I think the issue should be gone. If you could confirm this for me, I appreciate that.

That doesn't change the fact that we broke your CI and I apologize for that again. I don't have a lot of ideas about how to "fix this" rather than maybe restricting the "bug fix", "breaking change" or however we want to call this to situations where a new enough rubygems is being run. I'll look into the other issues about this release mentioned in this ticket and others and make a decision later.

**Comment by deivid-rodriguez** [comment] 2020-12-11 08:36
@brettwgreen Could you point me to instructions or public repo where I can see your issue for myself? Maybe it's same issue, maybe it's not.

**Comment by deivid-rodriguez** [comment] 2020-12-11 09:30
Hi @Dantemss!

Bundler 2.2 is supposed to keep track of all platforms in the lock file and give you the best gem variant for your platform, so if you're running under a platform where a proper precompiled version is available, you should get that, otherwise you should fallback to the standard version (which might need to compile extensions on the fly).

Essentially the above scenario is what you need, right? There's some bug here that I'm missing because I would expect that to work, and it sounds like bundler 2.2 broke it.

Hopefully I'll get a way to repro on the libv8 issue and I can give more insights soon.

**Comment by diasjorge** [comment] 2020-12-11 13:00
@deivid-rodriguez I updated the repo with instructions to run with different ruby versions and being able to update rubygems. You could take a look at the readme.

The bug did not manifest with ruby 2.7 which ships with rubygems 3.1.4

With ruby 2.5 using the latest rubygems it does not manifest itself either, so your diagnosis is correct.

Another related question, is there a way to have the gem command install the bundler version specified in the Gemfile.lock?
I'm resorting to do this in bash `gem install bundler -v $(tail -1 Gemfile.lock)` but I wondered if there's any gem utility for that, I don't know if I can always assume the bundler version would be the last line of the file.

**Comment by deivid-rodriguez** [comment] 2020-12-11 13:46
Currenly we don't have such thing, although we should. My plan for the next version would be to make `bundle install` automatically manage the bundler version itselft, meaning:

* Read the `BUNDLED WITH` section.
* If installed, go on, to install the bundle.
* If not install, install that version, and `Kernel.exec` the original `bundle install` command to the version we just installed.

Regarding your workaround, I think it should work for the time being since as far as I know, `BUNDLED WITH` is always the latest section in the lockfile. Maybe very old Gemfile.lock files might not have it though.

**Comment by eregon** [comment] 2020-12-11 13:53
I'm not sure I understood https://github.com/rubygems/rubygems/issues/4123#issuecomment-743049519 very well, but so this bug is caused by locking with one version of Bundler and installing with another version of Bundler? So some old RubyGems actually picks the Bundler version non-deterministically, or is it because the lockfile needs to be generated on some other machine?

Maybe Bundler should have a `required_rubygems_version` or so, but I guess that's not really feasible.
Without that, I guess the best is to check `BUNDLED WITH` and behave accordingly.

**Comment by deivid-rodriguez** [comment] 2020-12-11 13:56
> Maybe Bundler should have a required_rubygems_version or so, but I guess that's not really feasible. Without that, I guess the best is to check BUNDLED WITH and behave accordingly.

Yes, I think I'm going to check the "BUNDLED WITH" version, revert to the previous behaviour if pre-2.2.0, and release a patch-level version of bundler.

**Comment by deivid-rodriguez** [comment] 2020-12-11 14:03
I'm not sure I understood #4123 (comment) very well, but so this bug is caused by locking with one version of Bundler and installing with another version of Bundler? So some old RubyGems actually picks the Bundler version non-deterministically, or is it because the lockfile needs to be generated on some other machine?

This particular bug is caused by locking and installing with a particular version of bundler, and then running `bundle list` with a higher version. The old version recorded `google-protobuf (3.14.0)` in the lockfile even it ended up installing `google-protobuf (3.14.0-x86_64-linux)`. The new version installs and locks the same version, so when running `bundle list` it would look for `google-protobuf (3.14.0)` because that's what's recorded, but couldn't find it.

**Comment by deivid-rodriguez** [comment] 2020-12-11 14:14
I have to leave my laptop now but I'll come in ~6h and try to get this thing fixed.

**Comment by diasjorge** [comment] 2020-12-11 14:36
Just to clarify the example case uses `bundle list` because it's easy to demonstrate the problem but trying to run an app that uses bundler fails the same way.

**Comment by deivid-rodriguez** [comment] 2020-12-11 14:45
Yep, yep, `bundle exec` would have the same issue.

**Comment by deivid-rodriguez** [comment] 2020-12-11 23:00
Hei, I created a fix https://github.com/rubygems/rubygems/pull/4127. I'm fighting with the spec that covers the regression locally for me but fails in CI. If you have time to try it, I appreciate.

**Comment by FireFart** [comment] 2020-12-11 23:06
We have the same issue with our docker image too.

We do the following in the Dockerfile during build time:

```
gem install bundler && \
bundle config force_ruby_platform true && \
bundle config disable_version_check 'true' && \
bundle config without "$BUNDLER_WITHOUT" && \
bundle config path.system 'true' && \
bundle install --gemfile=$APP_HOME/Gemfile && \
```

This config forces the platform to always be ruby. In our update script to update the gems we had the following commands implemented:

```
gem install bundler; bundle lock --update
```

This always worked, but with bundler 2.2.0 it added a new plattform (alongside the ruby platform) to the `Gemfile.lock`.

We fixed this on our side by adding `bundle config force_ruby_platform true` to the update script too. This seems to prevent the addition of the new platform, but the container will still not start up.

Here is the entrypoint and cmd of the Dockerfile
```
ENTRYPOINT ["/sbin/tini", "--", "bundle", "exec"]
CMD ["rails", "server", "-b", "0.0.0.0"]
```

Here is the error from a `bundle exec rake db:migrate`

```text
bundler: failed to load command: rake (/usr/local/bundle/bin/rake)
/usr/local/bundle/gems/bundler-2.2.0/lib/bundler/spec_set.rb:86:in `block in materialize': Could not find ast-2.4.1 in any of the sources (Bundler::GemNotFound)
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/spec_set.rb:80:in `map!'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/spec_set.rb:80:in `materialize'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/definition.rb:175:in `specs'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/definition.rb:245:in `specs_for'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/definition.rb:227:in `requested_specs'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/runtime.rb:91:in `block in definition_method'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/runtime.rb:20:in `setup'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler.rb:149:in `setup'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/setup.rb:20:in `block in <top (required)>'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/ui/shell.rb:136:in `with_level'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/ui/shell.rb:88:in `silence'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/setup.rb:20:in `<top (required)>'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/cli/exec.rb:61:in `require_relative'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/cli/exec.rb:61:in `kernel_load'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/cli/exec.rb:28:in `run'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/cli.rb:497:in `exec'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/cli.rb:30:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/cli.rb:24:in `start'
        from /usr/local/bundle/gems/bundler-2.2.0/exe/bundle:49:in `block in <top (required)>'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
        from /usr/local/bundle/gems/bundler-2.2.0/exe/bundle:37:in `<top (required)>'
        from /usr/local/bundle/bin/bundle:23:in `load'
        from /usr/local/bundle/bin/bundle:23:in `<main>'
```

And the stacktrace when running puma (the default entrypoint and cmd from above):

```text
[1] ! Unable to load application: Bundler::GemNotFound: Could not find ast-2.4.1 in any of the sources
/usr/local/bundle/gems/bundler-2.2.0/lib/bundler/spec_set.rb:86:in `block in materialize': Could not find ast-2.4.1 in any of the sources (Bundler::GemNotFound)
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/spec_set.rb:80:in `map!'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/spec_set.rb:80:in `materialize'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/definition.rb:175:in `specs'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/definition.rb:245:in `specs_for'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/definition.rb:227:in `requested_specs'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/runtime.rb:91:in `block in definition_method'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/runtime.rb:20:in `setup'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler.rb:149:in `setup'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/setup.rb:20:in `block in <top (required)>'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/ui/shell.rb:136:in `with_level'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/ui/shell.rb:88:in `silence'
        from /usr/local/bundle/gems/bundler-2.2.0/lib/bundler/setup.rb:20:in `<top (required)>'
        from /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from /app/config/boot.rb:5:in `<top (required)>'
        from /app/config/application.rb:3:in `require_relative'
        from /app/config/application.rb:3:in `<top (required)>'
        from /app/config/environment.rb:4:in `require_relative'
        from /app/config/environment.rb:4:in `<top (required)>'
        from /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from config.ru:5:in `block in <main>'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
        from /usr/local/bundle/gems/puma-5.1.1/lib/puma/configuration.rb:342:in `load_rackup'
        from /usr/local/bundle/gems/puma-5.1.1/lib/puma/configuration.rb:264:in `app'
        from /usr/local/bundle/gems/puma-5.1.1/lib/puma/runner.rb:138:in `load_and_bind'
        from /usr/local/bundle/gems/puma-5.1.1/lib/puma/cluster.rb:342:in `run'
        from /usr/local/bundle/gems/puma-5.1.1/lib/puma/launcher.rb:182:in `run'
        from /usr/local/bundle/gems/puma-5.1.1/lib/puma/cli.rb:80:in `run'
        from /usr/local/bundle/gems/puma-5.1.1/bin/puma:10:in `<top (required)>'
        from /usr/local/bundle/bin/puma:23:in `load'
        from /usr/local/bundle/bin/puma:23:in `<main>'
```

**Comment by brettwgreen** [comment] 2020-12-11 23:10
Yep, same as us. The gem it hits first probably depends on your particular init process. Workaround, for now, is to lock bundler using `gem install bundler - v 2.1.4`.

**Comment by deivid-rodriguez** [comment] 2020-12-11 23:26
Could you try the fix?

**Comment by brettwgreen** [comment] 2020-12-12 00:36
> Could you try the fix?

I'm kind of fried after this week, but I'll see if i can try it tomorrow. Thanks for your work.

**Comment by brettwgreen** [comment] 2020-12-13 15:52
Could not reproduce on my local development environment for some reason. Deploying in a broken state on my QA environment is not something I can do right now. I did dig in to find something interesting.

I am running rails under a docker image using phusion passenger as the base docker image and application server. The gem I hit an issue on was `bindex` which is used by `web-console` which is under the `:development` group in my Gemfile. In QA, of course, it runs under the `:qa` environment group.

So it seems that, on startup, it's still trying to pull in development gems that aren't there because they weren't bundled in when the docker image was built... I build the image under `RAILS_ENV=qa`. That's the origin of the GemNotFound problem I believe. Note that nothing changed in my setup, only the switch to bundler 2.2.0. 

The passenger docker image uses ubuntu as its base and uses jruby as the interpreter.

Locally, I tried running in the passenger docker image with all the environment setup the same... only difference is that I run under puma whereas in qa/prod it runs under the passenger app with nginx. 

I'd be curious if, in @diasjorge's setup, if the `ast` gem is something in the `development` gem group that it shouldn't be looking for in prod/qa.

**Comment by brettwgreen** [comment] 2020-12-13 16:41
In any case, we have a PR to upgrade shortly to Ruby 2.7 that will probably get merged this week. I'll change it to use bundler 2.2.0 and let you know. If you are correct, it should fix the problem.

**Closed** 2020-12-14 11:52 UTC

**Comment by FireFart** [comment] 2020-12-14 23:09
@deivid-rodriguez thanks for you fix but unfortunately the error persists with bundler 2.2.1:

Sidekiq:
```text
2020-12-14T23:06:41.709Z pid=1 tid=1ih WARN: Bundler::GemNotFound: Could not find ast-2.4.1 in any of the sources
2020-12-14T23:06:41.709Z pid=1 tid=1ih WARN: /usr/local/bundle/gems/bundler-2.2.1/lib/bundler/spec_set.rb:86:in `block in materialize'
/usr/local/bundle/gems/bundler-2.2.1/lib/bundler/spec_set.rb:80:in `map!'
/usr/local/bundle/gems/bundler-2.2.1/lib/bundler/spec_set.rb:80:in `materialize'
/usr/local/bundle/gems/bundler-2.2.1/lib/bundler/definition.rb:175:in `specs'
/usr/local/bundle/gems/bundler-2.2.1/lib/bundler/definition.rb:245:in `specs_for'
/usr/local/bundle/gems/bundler-2.2.1/lib/bundler/definition.rb:227:in `requested_specs'
/usr/local/bundle/gems/bundler-2.2.1/lib/bundler/runtime.rb:91:in `block in definition_method'
/usr/local/bundle/gems/bundler-2.2.1/lib/bundler/runtime.rb:20:in `setup'
/usr/local/bundle/gems/bundler-2.2.1/lib/bundler.rb:149:in `setup'
/usr/local/bundle/gems/bundler-2.2.1/lib/bundler/setup.rb:20:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.2.1/lib/bundler/ui/shell.rb:136:in `with_level'
/usr/local/bundle/gems/bundler-2.2.1/lib/bundler/ui/shell.rb:88:in `silence'
/usr/local/bundle/gems/bundler-2.2.1/lib/bundler/setup.rb:20:in `<top (required)>'
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:103:in `require'
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:103:in `require'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `block in require'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `require'
/app/config/boot.rb:5:in `<top (required)>'
/app/config/application.rb:3:in `require_relative'
/app/config/application.rb:3:in `<top (required)>'
/app/config/environment.rb:4:in `require_relative'
/app/config/environment.rb:4:in `<top (required)>'
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:155:in `require'
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:155:in `require'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `block in require'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `require'
/usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/cli.rb:252:in `boot_application'
/usr/local/bundle/gems/sidekiq-6.1.2/lib/sidekiq/cli.rb:37:in `run'
/usr/local/bundle/gems/sidekiq-6.1.2/bin/sidekiq:31:in `<top (required)>'
/usr/local/bundle/bin/sidekiq:23:in `load'
/usr/local/bundle/bin/sidekiq:23:in `<main>'
```

Rake:
```text
rake aborted!
Bundler::GemNotFound: Could not find ast-2.4.1 in any of the sources
/usr/local/bundle/gems/bundler-2.2.1/lib/bundler/spec_set.rb:86:in `block in materialize'
/usr/local/bundle/gems/bundler-2.2.1/lib/bundler/spec_set.rb:80:in `map!'
/usr/local/bundle/gems/bundler-2.2.1/lib/bundler/spec_set.rb:80:in `materialize'
/usr/local/bundle/gems/bundler-2.2.1/lib/bundler/definition.rb:175:in `specs'
/usr/local/bundle/gems/bundler-2.2.1/lib/bundler/definition.rb:245:in `specs_for'
/usr/local/bundle/gems/bundler-2.2.1/lib/bundler/definition.rb:227:in `requested_specs'
/usr/local/bundle/gems/bundler-2.2.1/lib/bundler/runtime.rb:91:in `block in definition_method'
/usr/local/bundle/gems/bundler-2.2.1/lib/bundler/runtime.rb:20:in `setup'
/usr/local/bundle/gems/bundler-2.2.1/lib/bundler.rb:149:in `setup'
/usr/local/bundle/gems/bundler-2.2.1/lib/bundler/setup.rb:20:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.2.1/lib/bundler/ui/shell.rb:136:in `with_level'
/usr/local/bundle/gems/bundler-2.2.1/lib/bundler/ui/shell.rb:88:in `silence'
/usr/local/bundle/gems/bundler-2.2.1/lib/bundler/setup.rb:20:in `<top (required)>'
/app/config/boot.rb:5:in `<top (required)>'
/app/config/application.rb:3:in `require_relative'
/app/config/application.rb:3:in `<top (required)>'
/app/Rakefile:6:in `<top (required)>'
/usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
```

The `Gemfile.lock` now also contains `bundler-2.2.1` and under platforms there is only `ruby`

**Comment by diasjorge** [comment] 2020-12-15 00:57
@deivid-rodriguez thanks for the fix, I can confirm the bug doesn't happen anymore with the new version of bundler in my test repository.

**Comment by deivid-rodriguez** [comment] 2020-12-15 08:46
No @diasjorge, I'm happy things are fixed for you :)

@FireFart The error is the same but I think the root cause of your issue might be #4142 which I'm planning to fix now.

**Comment by brettwgreen** [comment] 2020-12-15 11:59
This is almost certainly the problem I am having... My deployment was seeking dev gems unnecessarily also. Deceiving that the error looks the same!

**Comment by JorgeGarciaxyz** [comment] 2021-07-27 15:54
For anyone wondering I just encountered this bug, even though the gem is installed.

bundler version: 2.2.24
OS: arch linux

```
$ gem install grpc --version 1.32.0
$ bundle check

The following gems are missing
 * grpc (1.32.0)
```

Downgrading to version 2.1.4 did the trick and is now working.

**Comment by deivid-rodriguez** [comment] 2021-07-27 17:50
My guess is that `gem` installed a platform specific version (`gem list grpc` should confirm that), but your lockfile only includes the pure ruby version. If that's  the case, I think `bundle update --bundler` should fix things for you.
