### ISSUE TITLE
Bug: Bundler evaluates local git gem gemspec within current directory instead of gem's directory

### ISSUE THREAD

**Issue by chriscz** [rubygems/rubygems#4528] opened 2021-04-12 23:12 UTC
### Describe the problem as clearly as you can
When a git-sourced gem has a local override then bundler evaluates its gemspec in the context of the current directory instead of the repository directory. 

Local gems which use a local filesystem path work correctly as can be seen in the MWE.

### Post steps to reproduce the problem
A minimal working example with steps can be found here: https://github.com/chriscz/bundler-bug

### Which command did you run?
I could not generate binstubs for my gem, bundler claimed it couldn't find the executables

```
bundle binstubs gemname
```

### What were you expecting to happen?

The binstubs to be generated i.e. executables to be set in `spec.executables` like when using the `path: "../"`

### What actually happened?

binstubs wasn't generated

## Environment

```
Bundler       2.2.16
  Platforms   ruby, x86_64-linux
Ruby          2.7.2p137 (2020-10-01 revision 5445e0435260b449decf2ac16f9d09bae3cafe72) [x86_64-linux]
  Full Path   /home/chris/.rbenv/versions/2.7.2/bin/ruby
  Config Dir  /home/chris/.rbenv/versions/2.7.2/etc
RubyGems      3.2.16
  Gem Home    /home/chris/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0
  Gem Path    /home/chris/.gem/ruby/2.7.0:/home/chris/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0
  User Home   /home/chris
  User Path   /home/chris/.gem/ruby/2.7.0
  Bin Dir     /home/chris/.rbenv/versions/2.7.2/bin
Tools         
  Git         2.30.2
  RVM         not installed
  rbenv       rbenv 1.1.1
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-04-09
Git SHA           3d7bfaff25
Released Version  true
```

**Comment by jeromedalbert** [comment] 2024-08-28 20:37
Can you confirm this is still an issue?

**Comment by chriscz** [comment] 2024-08-29 04:44
Hi @jeromedalbert, yes this is still an issue.

I've simplified the reproduction repository a bit, so hopefully it's clearer now.

Tested on:
1. `ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]` 
   `Bundler version 2.5.15`
2. `ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]` 
    `Bundler version 2.5.18`

**Comment by jeromedalbert** [comment] 2024-08-29 08:12
Thanks for updating the attached repro app, I am able to run the Makefile and see the custom fail messages after following the instructions.

Can you also provide a the most minimal repro app you can, basically with only one minimal app using one gem (the bar-git failing gem I guess) and no Makefile? Thank you

**Comment by chriscz** [comment] 2024-08-29 11:04
Here you go: https://github.com/chriscz/bundler-bug/tree/minimal

Just do  `./main`.

**Comment by jeromedalbert** [comment] 2024-08-29 21:45
Thank you. Here are the steps I used to reproduce the problem:

1. Run these commands:

    ```shell
    $ git clone https://github.com/chriscz/bundler-bug/
    $ cd bundler-bug
    $ git checkout minimal
    $ ./main

    Resolving dependencies...
    Resolving dependencies...
    Gemfile.path => executables: ["phonebook"]
    Resolving dependencies...
    Resolving dependencies...
    Gemfile.git  => executables: []
    ```

2. Observe that the last line shows an empty executable array `[]`. The expected behavior is that it should show `["phonebook"]`. The last line output comes from this command:

    `bundle exec --gemfile Gemfile.git ruby -e  'require "bundler/setup"; puts "Gemfile.git  => executables: #{Bundler.definition.specs.find { |s| s.name == "phonebook" }.executables}"'`

    which comes from the `main` file. See that file for more details about how the app (and `phonebook` local gem) is set up.

**Comment by jeromedalbert** [comment] 2024-08-29 22:39
As mentioned in the attached repro app [README](https://github.com/chriscz/bundler-bug), the root cause of the issue seems to be that `phonebook.gemspec` is using the following:

```ruby
spec.files = Dir["{app,config,db,lib,exe}/**/*", "MIT-LICENSE", "Rakefile", "README.md"]
```

instead of something the following:

```ruby
Dir.chdir(__dir__) do
  spec.files = Dir["{app,config,db,lib,exe}/**/*", "MIT-LICENSE", "Rakefile", "README.md"]
end
```

This problem happens on repro app and gem that was created 3 years ago. But [nowadays](https://github.com/rubygems/rubygems/blob/2fc63d4ebf81f44ca3694952a4dd2b69d4423fb2/bundler/lib/bundler/templates/newgem/newgem.gemspec.tt#L31-L36) gems generated by `bundle gem` include a specfile with the following:

```ruby
gemspec = File.basename(__FILE__)
spec.files = IO.popen(%w[git ls-files -z], chdir: __dir__, err: IO::NULL) do |ls|
  ls.readlines("\x0", chomp: true).reject do |f|
    (f == gemspec) ||
      f.start_with?(*%w[bin/ test/ spec/ features/ .git .github appveyor Gemfile])
  end
end
```

And this code calculates `spec.files` correctly. When using this code in `phonebook/phonebook.gemspec`, everything works as expected: the Bundler spec has the right `phonebook` executable, and the `phonebook` binstub is created correctly. If that looks good on your end @chriscz, can you close this issue?

**Comment by chriscz** [comment] 2024-08-29 22:44
Hi @jeromedalbert your explanation looks correct, but as I've explained the README and elsewhere, there are existing gems which do not use Dir.chdir. Furthermore, bundler is not the only way that people generate gems, there's `rails`,`hoe` and other templating tools.

The fundamental problem is that Bundler's behaviour deviates from the normal gem system when you do local overrides, and it shouldn't, it should behave as-if I installed the gem directly.

**Comment by jeromedalbert** [comment] 2024-08-30 00:00
> there are existing gems which do not use Dir.chdir. Furthermore, bundler is not the only way that people generate gems, there's rails,hoe and other templating tools.

If the issue were about templating, I understand that it would indeed only work correctly if the template defines `spec.files` in a way that works. Templating tools that would currently work are [`bundle gem`](https://github.com/rubygems/rubygems/blob/2fc63d4ebf81f44ca3694952a4dd2b69d4423fb2/bundler/lib/bundler/templates/newgem/newgem.gemspec.tt#L31-L36), maybe [`rails plugin new`](https://github.com/rails/rails/blob/c692e75d96f572f3fe518f06bec0dfd12b548429/railties/lib/rails/generators/rails/plugin/templates/%25name%25.gemspec.tt#L23-L25) too (although they don't use use `exe`). For `hoe` it seems to be whatever the user manually or automatically puts in `Manifest.txt`. In any case there is indeed no control over the myriad of templating tools, or even over how someone defines a gem by hand. If someone creates a gem by hand and only provides `s.files = ["lib/mygem.rb"]` in their gemspec, then no executable will be detected. An incorrectly defined gemspec will naturally result in an executable not being found.

> The fundamental problem is that Bundler's behaviour deviates from the normal gem system when you do local overrides, and it shouldn't, it should behave as-if I installed the gem directly.

Are suggesting that this is not a templating issue? I am not clear on this, what should the fix be in your view?

**Comment by chriscz** [comment] 2024-08-30 00:30
In the original reproduction repository I give several examples of how a gem can be added to a Gemfile. 

All of these would work the same if it weren't for the `local` overrides. There must be a bug somewhere when doing a local override of a `git`-sourced gem.

`bundler` is being inconsistent in how it loads gemspecs in this case. 

The correct behaviour, if we suppose that all the other cases are correct, is that a gemspec should be evaluated in the directory where it presides, i.e. the root of the gem, not anywhere else.

**Comment by chriscz** [comment] 2024-08-30 00:34
I'm not 100% certain where this occurs, but I would suspect it's in, near or related to:

https://github.com/rubygems/rubygems/blob/2fc63d4ebf81f44ca3694952a4dd2b69d4423fb2/bundler/lib/bundler/source/git.rb#L149

**Comment by jeromedalbert** [comment] 2024-08-30 01:32
> In the original reproduction repository I give several examples of how a gem can be added to a Gemfile.

Just for reference for anyone else reading the issue, here is the `Gemfile` in question:

```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# This one is broken 🪲
gem "bar-git", git: "git@github.com:chriscz/bar", branch: 'main'

gem "bar-git-fixed", git: "git@github.com:chriscz/bar-git-fixed", branch: 'main'

gem "bar-path", path: '../bar-path'
```

The app with this Gemfile has been set up with a Makefile with `bundle config --local local.bar-git ...`, `bundle config --local local.bar-git-fixed ...`, and `bundle config --local local.bar-path ...`.

A few asides:

- It seems like the officially [documented](https://bundler.io/guides/git.html#local) way to use Bundler local git repos is to do `bundle config set local.mygem path/to/mygem`, not `bundle config --local local.bar-git path/to/mygem`. Either way seems to work anyways.
- According to the [docs](https://bundler.io/guides/git.html#local-git-repos) Bundler local git repos must be setup setup with a git source and branch. So the third use case in that Gemfile may note make sense (i.e. when `path: '../bar-path'` is defined in the Gemfile, and the app has also been configured with `bundle config --local local.bar-path`).

**Comment by jeromedalbert** [comment] 2024-08-30 02:03
> All of these would work the same if it weren't for the `local` overrides I added. [...]
> 
> `bundler` is being inconsistent in how it loads gemspecs [...].
> 
> The correct behaviour, if we suppose that all the other cases are correct (including for non-overridden gems), is that a gemspec should be evaluated in the directory where it presides [...]

Thanks for clarifying, I see what you mean. In other words:

- a gemspec should be evaluated consistently, no matter whether we started evaluating the gemspec from that gem's directory, or from an app in a different directory that is pointing to that gem via local overrides
- If the gem is working fine by itself in isolation with a simple `spec.files = ['some-file-1', 'some-file-2']`, it should continue to work fine if the gem is being pointed to from another Gemfile, whether via `path: ...` (which is already working consistently) or via a local override (which is currently not working consistently and is the subject of this bug report).

**Comment by deivid-rodriguez** [comment] 2024-09-02 14:04
Yes, this is a bug, and I agree with the proposed solution, let me create a fix.

**Closed** 2024-09-04 12:00 UTC
Labels: Bundler
