### ISSUE TITLE
 Unfortunately, an unexpected error occurred, and Bundler cannot continue.

### ISSUE THREAD

**Issue by Naved143** [rubygems/rubygems#4476] opened 2021-03-20 07:42 UTC
I am getting this issue while doing gem bundle clash and all it is saying me this along with some others things like 
Errno::ENOENT: No such file or directory @ rb_sysopen - C:/Users/HP TECHNOLOGY/Documents/Desktop/Coc_Gem.Rb/clash/.git/HEAD
  C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/cli/gem.rb:188:in `read'
  C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/cli/gem.rb:188:in `run'
  C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/cli.rb:612:in `run'
  C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'

  C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/cli.rb:30:in `dispatch'
  C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/cli.rb:24:in `start'
  C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/exe/bundle:49:in `block in <top (required)>'
  C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
  C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/exe/bundle:37:in `<top (required)>'
  C:/Ruby30-x64/bin/bundle:23:in `load'
  C:/Ruby30-x64/bin/bundle:23:in `<main>'

**Comment by deivid-rodriguez** [comment] 2021-03-20 09:55
Duplicate of #4468.

**Closed by deivid-rodriguez** 2021-03-20 09:55 UTC
