### ISSUE TITLE
Faulty OpenSSL / HAVE_SSL detection

### ISSUE THREAD

**Issue by anthonyryan1** [rubygems/rubygems#6408] opened 2023-02-26 22:29 UTC
### Describe the problem as clearly as you can

Within [openssl.rb](https://github.com/rubygems/rubygems/blob/v3.4.7/lib/rubygems/openssl.rb) `defined?` does not trigger `autoload`, causing `HAVE_OPENSSL` to be a false negative.

I'm not sure why problems with this aren't more common, but the code looks wrong based on my understanding.

### Did you try upgrading RubyGems?

Yes

### Post steps to reproduce the problem

I think the flaw is most easily demonstrated via irb.

```ruby
irb(main):001:0> RUBY_VERSION
=> "3.0.5"
irb(main):002:0> autoload :OpenSSL, "openssl"
=> nil
irb(main):003:0> defined? OpenSSL::SSL
=> nil
irb(main):004:0> OpenSSL
=> OpenSSL
irb(main):005:0> defined? OpenSSL::SSL
=> "constant"
```

I think we need to replace the combination of `autoload` and `defined?` with  something simple, like require. Lazy imports are causing false negatives here.

### Which command did you run?

```
gem install whatever
```

### What were you expecting to happen?

A gem to install.

### What actually happened?

OpenSSL exception with backtrace
```
ERROR:  While executing gem ... (Gem::Exception)
    OpenSSL is not available. Install OpenSSL and rebuild Ruby (preferred) or use non-HTTPS sources
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/request.rb:47:in `configure_connection_for_https'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/request/https_pool.rb:6:in `setup_connection'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/request/http_pool.rb:39:in `make_connection'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/request/http_pool.rb:20:in `checkout'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/request.rb:129:in `connection_for'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/request.rb:188:in `perform_request'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/request.rb:154:in `fetch'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/remote_fetcher.rb:309:in `request'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/remote_fetcher.rb:209:in `fetch_http'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/remote_fetcher.rb:248:in `fetch_path'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/source.rb:88:in `dependency_resolver_set'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/resolver/best_set.rb:23:in `block in pick_sets'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/source_list.rb:94:in `each'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/source_list.rb:94:in `each_source'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/resolver/best_set.rb:22:in `pick_sets'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/resolver/best_set.rb:28:in `find_all'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/resolver/installer_set.rb:170:in `find_all'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/resolver/installer_set.rb:61:in `add_always_install'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/dependency_installer.rb:322:in `resolve_dependencies'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/commands/install_command.rb:205:in `install_gem'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/commands/install_command.rb:230:in `block in install_gems'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/commands/install_command.rb:223:in `each'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/commands/install_command.rb:223:in `install_gems'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/commands/install_command.rb:169:in `execute'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/command.rb:323:in `invoke_with_build_args'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/command_manager.rb:251:in `invoke_command'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/command_manager.rb:191:in `process_args'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/command_manager.rb:149:in `run'
	/usr/lib64/ruby/site_ruby/3.0.0/rubygems/gem_runner.rb:51:in `run'
	/usr/bin/gem:10:in `<main>'
```

### Run `gem env` and paste the output below

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.4.3
  - RUBY VERSION: 3.0.5 (2022-11-24 patchlevel 211) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/lib64/ruby/gems/3.0.0
  - USER INSTALLATION DIRECTORY: /home/user/.local/share/gem/ruby/3.0.0
  - RUBY EXECUTABLE: /usr/bin/ruby30
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /usr/bin
  - SPEC CACHE DIRECTORY: /home/user/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux
  - GEM PATHS:
     - /usr/lib64/ruby/gems/3.0.0
     - /mnt/mpatha/user/.local/share/gem/ruby/3.0.0
     - /usr/local/lib64/ruby/gems/3.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
     - "install" => "--install-dir /home/user/.local/share/gem/ruby/3.0.0 --bindir /home/user/bin"
     - "uninstall" => "--install-dir /home/user/.local/share/gem/ruby/3.0.0 --bindir /home/user/bin"
     - "update" => "--install-dir /home/user/.local/share/gem/ruby/3.0.0 --bindir /home/user/bin"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /opt/bin
     - /usr/lib/llvm/15/bin
```

**Comment by duckinator** [comment] 2023-02-27 00:34
It's very strange that you're getting that result. On Ruby 3.2.1, I get this:

```
irb(main):001:0> RUBY_VERSION
=> "3.2.1"
irb(main):002:0> autoload :OpenSSL, "openssl"
=> nil
irb(main):003:0> defined? OpenSSL
=> "constant"
```

I thought maybe it was being automatically-loaded, so I tried `defined? OpenSSL` before the autoload:

```
irb(main):001:0> RUBY_VERSION
=> "3.2.1"
irb(main):002:0> defined? OpenSSL
=> nil
irb(main):003:0> autoload :OpenSSL, "openssl"
=> nil
irb(main):004:0> defined? OpenSSL
=> "constant"
```

I'll dig into this a bit more and see if I find anything. :)

**Comment by duckinator** [comment] 2023-02-27 00:47
@anthonyryan1 can you provide more details about your environment. E.g., what Linux distro are you using, and how did you install Ruby? I can't reproduce the problem with Ruby 3.0.5 on FreeBSD, with my Ruby versions managed using `ruby-install` and `chruby`.

```
irb(main):001:0> RUBY_VERSION
=> "3.0.5"
irb(main):002:0> autoload :OpenSSL, "openssl"
=> nil
irb(main):003:0> defined? OpenSSL::SSL
=> "constant"
```

And, just to confirm again that it wasn't `require`d before I got a prompt from `irb`:

```
irb(main):001:0> RUBY_VERSION
=> "3.0.5"
irb(main):002:0> defined? OpenSSL::SSL
=> nil
irb(main):003:0> autoload :OpenSSL, "openssl"
=> nil
irb(main):004:0> defined? OpenSSL::SSL
=> "constant"
```

**Comment by rubyFeedback** [comment] 2023-02-27 13:50
I also get the result from duckinator. My ruby is compiled from source, RUBY_VERSION yields "3.2.1" and my openssl is also compiled from source.

Of course I do not know what system anthonyryan1 is using, but I assume it may be some stock ruby on a linux distribution? Not that I disagree that it may be best to avoid autoload, but it could be there is at the least one other problem (or autoload not at fault at all) within the context of this issue reported.

**Comment by anthonyryan1** [comment] 2023-02-27 16:45
I'm using `dev-lang/ruby:3.0` on Gentoo Linux.

I've tested another Gentoo machine with the same version and seen the same behaviour as you for autoload and defined. I'll investigate a bit further.

**Comment by deivid-rodriguez** [comment] 2023-02-28 22:05
This may be https://bugs.ruby-lang.org/issues/19115? It seems a core issue fixed in Ruby 3.2, and probably backported to 3.1.

**Comment by deivid-rodriguez** [comment] 2023-03-10 16:24
Assuming this is the ruby-core referenced bug, so closing. If this is still reproducible on Ruby 3.2, feel free to reopen.

**Closed by deivid-rodriguez** 2023-03-10 16:24 UTC
Labels: status: feedback required, RubyGems

**Comment by anthonyryan1** [comment] 2023-04-09 13:53
Just chiming in, for anyone seeing this in the future that the fix for https://bugs.ruby-lang.org/issues/19115 has now been backported into Gentoo's stable ruby 3.0 packages.
