### ISSUE TITLE
Time to require gems increases significantly with many installed gems

### ISSUE THREAD

**Issue by aasmith** [rubygems/rubygems#1076] opened 2014-11-26 00:53 UTC
It seems `require` becomes significantly slower once I have a certain number of gems installed.
## Steps to Reproduce

Create a simple gem 'foo' (I used `bundle gem foo`), with a `bin/foo` containing:

``` ruby
s = Time.now
require 'yaml'
puts Time.now-s
```

Ensure it has some dependencies. I added these to `foo.gemspec`:

``` ruby
  spec.add_dependency "commander"
  spec.add_dependency "git"
  spec.add_dependency "colored"
  spec.add_dependency "capybara"
  spec.add_dependency "selenium-webdriver"
  spec.add_dependency "pry"
  spec.add_dependency "ruby2ruby"
```

Install the gem, and notice that it executes very quickly:

```
aasmith$ time foo
0.016539

real  0m0.544s
user  0m0.458s
sys   0m0.082s
```

Install lots of gems. My system has ~380 gemspecs in the system gem specifications dir.

Note that time to run `foo` has ballooned:

```
aasmith$ time foo
0.792959

real  0m1.048s
user  0m0.939s
sys   0m0.107s
```
## Sniffing so far

I moved all but the 27 required gemspecs from the specifications dir to a temp dir `x`, and ran a script to add all of them back, in random order, one a time, running `time foo` each time.

The results of these runs are at:

https://gist.github.com/aasmith/57109b3b912dff16586f

I also graphed these runs, respectively:

![image](https://cloud.githubusercontent.com/assets/12484/5194494/ccbee666-74c2-11e4-8e35-adc8684e5576.png)

![image](https://cloud.githubusercontent.com/assets/12484/5194496/d1c08bec-74c2-11e4-8aea-bc9084f61302.png)

(Time to execute in seconds vs number of gems installed)
## Versions

```
aasmith$ gem -v
2.4.4
aasmith$ ruby -v
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
```

**Comment by mfazekas** [comment] 2015-02-14 16:39
This might be related to #1167 Can you try the patch at #1168?

**Comment by tonobo** [comment] 2018-01-09 14:32
This possibly also related to #2037

**Comment by tonobo** [comment] 2018-01-09 15:00
I've done futher analyze with rubys trace point. The following statistic will show to amount of calls per class during a gem requirement, sorted in descending order.

```
Gem::Dependency - 13292
  runtime? - 11104
  requirement - 1006
  matching_specs - 426
  to_specs - 426
  initialize - 294
  matches_spec? - 35
  merge - 1
Gem::StubSpecification - 11580
  data - 4496
  name - 2072
  activated? - 1162
  extensions - 937
  full_name - 539
  raw_require_paths - 483
  default_gem? - 483
  missing_extensions? - 483
  version - 465
  to_spec - 433
  this - 27
Gem::Specification - 9459
  dependencies - 1854
  default_value - 1260
  hash - 588
  extensions - 536
  satisfies_requirement? - 524
  platform - 499
  sort_obj - 432
  full_name - 320
  gems_dir - 316
  raw_require_paths - 300
  has_conflicts? - 296
  add_dependency_with_type - 292
  missing_extensions? - 238
  traverse - 236
  conficts_when_loaded_with? - 232
  add_development_dependency - 182
  add_runtime_dependency - 110
  base_dir - 71
  invalidate_memoized_attributes - 65
  summary= - 63
  date= - 63
  authors= - 63
  require_paths= - 63
  required_rubygems_version= - 63
  version= - 63
  internal_init - 63
  initialize - 63
  add_self_to_load_path - 62
  runtime_dependencies - 62
  activate_dependencies - 62
  raise_if_conflicts - 62
  activate - 62
  installed_by_version= - 62
  licenses= - 58
  description= - 51
  files= - 27
  extra_rdoc_files= - 22
  required_ruby_version= - 20
  installed_by_version - 16
  rdoc_options= - 15
  respond_to_missing? - 10
  executables= - 7
  extensions= - 4
  platform= - 2
Gem::Version - 7696
  segments - 3086
  _version - 1533
  <=> - 1533
  hash - 588
  bump - 361
  release - 361
  prerelease? - 86
  initialize - 83
  version - 65
Gem::BasicSpecification - 3087
  have_extensions? - 753
  have_file? - 721
  contains_requirable_file? - 721
  default_gem? - 363
  extension_dir - 99
  full_gem_path - 66
  full_name - 63
  internal_init - 63
  initialize - 63
  find_full_gem_path - 62
  full_require_paths - 62
  gem_build_complete_path - 47
  extensions_dir - 4
#<Class:Gem> - 1667
  suffixes - 759
  platforms - 432
  default_dir - 363
  load_path_insert_index - 62
  find_unresolved_default_spec - 38
  ruby_api_version - 4
  extension_api_version - 4
  default_ext_dir_for - 4
  try_activate - 1
Gem::Requirement - 1386
  satisfied_by? - 969
  initialize - 377
  none? - 35
  as_list - 2
  to_s - 2
  == - 1
#<Class:Gem::Requirement> - 771
  parse - 393
  create - 377
  default - 1
```
Oneliner to reproduce:

```ruby
# tracing the requirement
x = []; t = TracePoint.new(:call){ |tp| x << [tp.lineno, tp.defined_class, tp.method_id, tp.event]}.enable{ require 'hctl' }
# formatting output
x.group_by{|y| y[1] }.map{|y| [y[0], y[1].size]}.sort_by{|y| y[1]}.reverse.map{|m| puts m.join(' - '); puts x.select{|y| y[1] == m[0] }.group_by{|y| y[2] }.map{|y| [y[0], y[1].size]}.sort_by{|y| y[1]}.reverse.map{|n| '  '+ n.join(' - ')}}
```

**Comment by bronzdoc** [comment] 2018-03-31 21:26
We're going to close this because it is to old, but if this problem is still happening with the latest version of RubyGems please feel free to let us know with a new issue!

**Closed by bronzdoc** 2018-03-31 21:26 UTC
Labels: performance, status: ready, type: bug report
