### ISSUE TITLE
Error while installing rails on windows 10

### ISSUE THREAD

**Issue by trustsantosh** [rubygems/rubygems#2168] opened 2018-02-01 13:23 UTC
I'm having a problem while installing rails on Windows 10 via ruby gem.
Find below logs:
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing rails:
        ERROR: Failed to build gem native extension.

    current directory: D:/rubyinstaller-2.5.0-1-x64/rubyinstaller-2.5.0-1-x64/lib/ruby/gems/2.5.0/gems/nio4r-2.2.0/ext/nio4r
D:/rubyinstaller-2.5.0-1-x64/rubyinstaller-2.5.0-1-x64/bin/ruby.exe -r ./siteconf20180201-3388-slvjal.rb extconf.rb

current directory: D:/rubyinstaller-2.5.0-1-x64/rubyinstaller-2.5.0-1-x64/lib/ruby/gems/2.5.0/gems/nio4r-2.2.0/ext/nio4r
make "DESTDIR=" clean
'make' is not recognized as an internal or external command,
operable program or batch file.

current directory: D:/rubyinstaller-2.5.0-1-x64/rubyinstaller-2.5.0-1-x64/lib/ruby/gems/2.5.0/gems/nio4r-2.2.0/ext/nio4r
make "DESTDIR="
'make' is not recognized as an internal or external command,
operable program or batch file.

make failed, exit code 1

Gem files will remain installed in D:/rubyinstaller-2.5.0-1-x64/rubyinstaller-2.5.0-1-x64/lib/ruby/gems/2.5.0/gems/nio4r-2.2.0 for inspection.
Results logged to D:/rubyinstaller-2.5.0-1-x64/rubyinstaller-2.5.0-1-x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/nio4r-2.2.0/gem_make.out

Current Ruby version : 2.5.0
Current Msys2 : Latest version 20161025
Current OS : Windows 10

Updated log with same configuration after installing **make** gem
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing rails:
        ERROR: Failed to build gem native extension.

    current directory: D:/rubyinstaller-2.5.0-1-x64/rubyinstaller-2.5.0-1-x64/lib/ruby/gems/2.5.0/gems/nio4r-2.2.0/ext/nio4r
D:/rubyinstaller-2.5.0-1-x64/rubyinstaller-2.5.0-1-x64/bin/ruby.exe -r ./siteconf20180201-2944-ca4bo8.rb extconf.rb

current directory: D:/rubyinstaller-2.5.0-1-x64/rubyinstaller-2.5.0-1-x64/lib/ruby/gems/2.5.0/gems/nio4r-2.2.0/ext/nio4r
make "DESTDIR=" clean
D:/rubyinstaller-2.5.0-1-x64/rubyinstaller-2.5.0-1-x64/lib/ruby/gems/2.5.0/gems/make-0.3.1/bin/make:4:in `<top (required)>': undefined local variable or method `make' for main:Object (NameError)
        from D:/rubyinstaller-2.5.0-1-x64/rubyinstaller-2.5.0-1-x64/bin/make:23:in `load'
        from D:/rubyinstaller-2.5.0-1-x64/rubyinstaller-2.5.0-1-x64/bin/make:23:in `<main>'

current directory: D:/rubyinstaller-2.5.0-1-x64/rubyinstaller-2.5.0-1-x64/lib/ruby/gems/2.5.0/gems/nio4r-2.2.0/ext/nio4r
make "DESTDIR="
D:/rubyinstaller-2.5.0-1-x64/rubyinstaller-2.5.0-1-x64/lib/ruby/gems/2.5.0/gems/make-0.3.1/bin/make:4:in `<top (required)>': undefined local variable or method `make' for main:Object (NameError)
        from D:/rubyinstaller-2.5.0-1-x64/rubyinstaller-2.5.0-1-x64/bin/make:23:in `load'
        from D:/rubyinstaller-2.5.0-1-x64/rubyinstaller-2.5.0-1-x64/bin/make:23:in `<main>'

make failed, exit code 1

Gem files will remain installed in D:/rubyinstaller-2.5.0-1-x64/rubyinstaller-2.5.0-1-x64/lib/ruby/gems/2.5.0/gems/nio4r-2.2.0 for inspection.
Results logged to D:/rubyinstaller-2.5.0-1-x64/rubyinstaller-2.5.0-1-x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/nio4r-2.2.0/gem_make.out

Appreciate your help.

Thanks @trustsantosh

**Comment by shevegen** [comment] 2018-02-01 14:23
Just so that others can understand the above:

- The installation of rails fails because of the gem nio4r, which attempts to compile something, leading to the failure? If this is correct, is the gem nio4r really part of rails?

I may not be up to date since I use Linux mostly but I just wanted to ask so that it can be confirmed; I do not remember rails requiring lots of compilation normally on linux.

**Comment by trustsantosh** [comment] 2018-02-01 15:19
I am quite new to rails.
I would like to try this along with other integrated system(running different web container), currently Azure.
Reported this issue on https://github.com/rails/rails/issues/31861.

It seems that the latest version of rails is not stable yet for Windows Machine.
There seems to be something in installation of rails where it looks for some more dependencies.

**Comment by matthewd** [comment] 2018-02-01 15:30
nio4r is a Rails dependency. I didn't actually realise it'd cause a compile on Windows, but that's my fault for not looking close enough: https://github.com/socketry/nio4r/blob/fcd25cbff47439fadc672d0bef2a049b5da6d21e/ext/nio4r/extconf.rb#L5-L10 (i.e., it's a no-op, but still needs a working `make`)

If it's our only not-precompiled-for-Windows dep, I should definitely look into alternative arrangements... but it sounds like Ruby Installer intends to support native extensions anyway, so [I suspect the problem lies over there](https://github.com/rails/rails/issues/31861#issuecomment-362300165).

**Comment by colby-swandale** [comment] 2018-02-02 01:02
I'm closing this issue as this is not a problem with rubygems itself.

**Closed by colby-swandale** 2018-02-02 01:02 UTC
Labels: status: triage

**Comment by shuxinjin** [comment] 2019-01-25 02:57
hide so deep,waste my time ...
