### ISSUE TITLE
Bundler installs all the files when installing from git repositories instead of what the gemspec specifies

### ISSUE THREAD

**Issue by revolter** [rubygems/rubygems#7652] opened 2024-05-11 23:45 UTC
### Describe the problem as clearly as you can

Using

```ruby
gem 'minima'
```

installs only `LICENSE.txt` and `README.md` files (inside `~/.gems/gems/minima-2.5.1`) from the top-level directory of the repository, while using

```ruby
gem 'minima', github: 'jekyll/minima'
```

installs all the 14 existing files (inside `~/.gems/bundler/gems/minima-a35b5ab0f276`) from the top-level directory of the repository.

This means that the `files` attribute of the `Specification` class is completely ignored.

### Did you try upgrading rubygems & bundler?

Yes.

### Post steps to reproduce the problem

Explained in the first section.

### Which command did you run?

Explained in the first section.

### What were you expecting to happen?

Only 2 files from the top-level directory of the repository to be installed.

### What actually happened?

Explained in the first section.

## Environment

```
Bundler       2.5.10
  Platforms   ruby, arm64-darwin-21
Ruby          3.0.3p157 (2021-11-24 revision 3fb7d2cadc18472ec107b14234933b017a33c14d) [arm64-darwin-21]
  Full Path   /Users/revolt/.rbenv/versions/3.0.3/bin/ruby
  Config Dir  /Users/revolt/.rbenv/versions/3.0.3/etc
RubyGems      3.2.32
  Gem Home    /Users/revolt/.gems
  Gem Path    /Users/revolt/.gem/ruby/3.0.0:/Users/revolt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0:/Users/revolt/.gems
  User Home   /Users/revolt
  User Path   /Users/revolt/.gem/ruby/3.0.0
  Bin Dir     /Users/revolt/.gems/bin
Tools         
  Git         2.45.0
  RVM         not installed
  rbenv       rbenv 1.2.0
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-05-03
Git SHA           24cac00613
Released Version  true
```

### Gemfile

```ruby
# frozen_string_literal: true

source 'https://rubygems.org'

gem 'jekyll-octicons'
gem 'minima', github: 'jekyll/minima'
```

### Gemfile.lock

```
GIT
  remote: https://github.com/jekyll/minima
  revision: a35b5ab0f276318b11ea23bfb82a333ea113f6e5
  specs:
    minima (3.0.0.dev)
      jekyll (>= 3.5, < 5.0)
      jekyll-feed (~> 0.9)
      jekyll-seo-tag (~> 2.1)

GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.8.6)
      public_suffix (>= 2.0.2, < 6.0)
    colorator (1.1.0)
    concurrent-ruby (1.2.3)
    em-websocket (0.5.3)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0)
    eventmachine (1.2.7)
    ffi (1.16.3)
    forwardable-extended (2.6.0)
    google-protobuf (3.25.3)
    google-protobuf (3.25.3-aarch64-linux)
    google-protobuf (3.25.3-arm64-darwin)
    google-protobuf (3.25.3-x86-linux)
    google-protobuf (3.25.3-x86_64-darwin)
    google-protobuf (3.25.3-x86_64-linux)
    http_parser.rb (0.8.0)
    i18n (1.14.5)
      concurrent-ruby (~> 1.0)
    jekyll (4.3.3)
      addressable (~> 2.4)
      colorator (~> 1.0)
      em-websocket (~> 0.5)
      i18n (~> 1.0)
      jekyll-sass-converter (>= 2.0, < 4.0)
      jekyll-watch (~> 2.0)
      kramdown (~> 2.3, >= 2.3.1)
      kramdown-parser-gfm (~> 1.0)
      liquid (~> 4.0)
      mercenary (>= 0.3.6, < 0.5)
      pathutil (~> 0.9)
      rouge (>= 3.0, < 5.0)
      safe_yaml (~> 1.0)
      terminal-table (>= 1.8, < 4.0)
      webrick (~> 1.7)
    jekyll-feed (0.17.0)
      jekyll (>= 3.7, < 5.0)
    jekyll-octicons (19.8.0)
      jekyll (>= 3.6, < 5.0)
      octicons (= 19.8.0)
    jekyll-sass-converter (3.0.0)
      sass-embedded (~> 1.54)
    jekyll-seo-tag (2.8.0)
      jekyll (>= 3.8, < 5.0)
    jekyll-watch (2.2.1)
      listen (~> 3.0)
    kramdown (2.4.0)
      rexml
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    liquid (4.0.4)
    listen (3.9.0)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    mercenary (0.4.0)
    octicons (19.8.0)
    pathutil (0.16.2)
      forwardable-extended (~> 2.6)
    public_suffix (5.0.5)
    rake (13.2.1)
    rb-fsevent (0.11.2)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rexml (3.2.6)
    rouge (4.2.1)
    safe_yaml (1.0.5)
    sass-embedded (1.69.5)
      google-protobuf (~> 3.23)
      rake (>= 13.0.0)
    sass-embedded (1.69.5-arm64-darwin)
      google-protobuf (~> 3.23)
    sass-embedded (1.69.5-x86_64-darwin)
      google-protobuf (~> 3.23)
    terminal-table (3.0.2)
      unicode-display_width (>= 1.1.1, < 3)
    unicode-display_width (2.5.0)
    webrick (1.8.1)

PLATFORMS
  aarch64-linux
  arm-linux
  arm64-darwin
  x86-linux
  x86_64-darwin
  x86_64-linux

DEPENDENCIES
  jekyll-octicons
  minima!

BUNDLED WITH
   2.5.10
```

**Comment by indirect** [comment] 2024-05-11 23:48
You are accurately describing how git gems work. Can you elaborate on why you would expect files from the repo to be deleted based on the gemspec? Also, can you please explain why this is a problem or something that should be changed?

**Comment by revolter** [comment] 2024-05-12 00:25
> Can you elaborate on why you would expect files from the repo to be deleted based on the gemspec?

Because I find it to be an unexpected (and undocumented!) behaviour.

I would expect a gem dependency to be installed identically regardless of the source used for downloading it.

In other words, the installation method should be transparent to the project using the gem.

> Also, can you please explain why this is a problem or something that should be changed?

In my specific case, the issue is that `jekyll/minima` repository contains both the source code for a Jekyll theme, and a Jekyll presentation website for the theme itself.

This means that it contains a `_config.yml` file that's used to build and deploy the https://jekyll.github.io/minima/ website, which doesn't make sense to reach any project using this gem (hence configuring the `files` attribute: https://github.com/jekyll/minima/blob/a35b5ab0f276318b11ea23bfb82a333ea113f6e5/minima.gemspec#L15-L17).

But more than not making sense, it actually causes some issues. For example, if your project does not specify an `author` configuration, `jekyll/minima`'s `author` configuration (https://github.com/jekyll/minima/blob/a35b5ab0f276318b11ea23bfb82a333ea113f6e5/_config.yml#L2-L4) is automatically used, which renders the explicit behaviour of hiding the `author` section (https://github.com/jekyll/minima/blob/a35b5ab0f276318b11ea23bfb82a333ea113f6e5/_includes/footer.html#L15) useless.

---


Is there a temporary workaround for this issue?

**Comment by deivid-rodriguez** [comment] 2024-05-13 09:35
This is a duplicate of https://github.com/rubygems/rubygems/issues/3194.

We could potentially first try build the gem (via `gem build` or `rake build`) and if it doesn't build successfully, do what we do now.

There's no standard way to build a gem though, so not sure what the success rate would be of such a naive approach. I guess we could also expose some gemspec directive that gem authors can use to declare how the gem is built, but maybe we could try the naive approach first. I wonder if it would work in this particular case.

On top of that, `path` gems would have the additional complexity of continuously rebuilding the gem as files in the local path change.

**Comment by deivid-rodriguez** [comment] 2024-05-13 13:10
Even if it's very old, I think the other issue has more discussion and helpful context, so let's continue the discussion over there.

**Closed by deivid-rodriguez** 2024-05-13 13:10 UTC
Labels: Bundler
