### ISSUE TITLE
$ bundle install The unmet dependencies are: * bundler (~> 1.0), dependency of rails-3.0.20, unsatisfied by bundler-2.4.20

### ISSUE THREAD

**Issue by BAYRAM0661** [rubygems/rubygems#7069] opened 2023-10-16 13:26 UTC
`$ bundle install
`

> Installing bcrypt-ruby 3.0.1 with native extensions
Installing json 1.7.7 with native extensions
Installing eventmachine 1.0.0 with native extensions

>Your lockfile doesn't include a valid resolution.
You can fix this by regenerating your lockfile or manually editing the bad locked gems to a version that satisfies all pendencies.
The unmet dependencies are:

>bundler (~> 1.0), dependency of rails-3.0.20, unsatisfied by bundler-2.4.20 Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

![image](https://github.com/rubygems/rubygems/assets/90972092/15a25d38-99ad-4740-92d8-e9826a3d659e)
![image](https://github.com/rubygems/rubygems/assets/90972092/f8142ead-f313-43a1-8b1b-9adf211dd1c9)

**Comment by hsbt** [comment] 2023-10-16 23:43
Duplicate of #7068

**Closed by hsbt** 2023-10-16 23:43 UTC
Labels: Bundler
