### ISSUE TITLE
Your bundle is locked to X but that version can no longer be found in that source. (2.4.14 to 2.4.15)

### ISSUE THREAD

**Issue by professor** [rubygems/rubygems#6799] opened 2023-07-06 16:31 UTC
### Describe the problem as clearly as you can

We have a lot of developers working out of a rails mono-repo. On 6/29/2023, we upgraded bundler from 2.4.14 to 2.4.15 and a few of our developers started seeing messages like:

```
Your bundle is locked to packwerk (3.0.1) from https://github.com/Shopify/packwerk.git (at main@b51ac53), but that version can no longer be found in that source. That means the author of packwerk (3.0.1) has removed it. You'll need to
update your bundle to a version other than packwerk (3.0.1) that hasn't been removed in order to install.
```

Most have the issue with `packwerk` and one has the issue with `rails` gem. 

### Did you try upgrading rubygems & bundler?

We are on the latest bundler. We have not tried upgrading rubygems.

On a working machine we are on `rubygems-update (3.4.13, 3.4.12)`

### Post steps to reproduce the problem

We still don't know what is causing the issue and exactly how to fix it.

Here's what we can rule out
- It's probably not the gem since its happening for multiple gems (packwerk, rails)
- It's probably not the ruby environment manager since its happening for chruby and rbenv

So far, the issue only happens withe gems that are linked to a branch. 

We've tried several work arounds. Sometimes they work for 1 developer but then not someone else. Our current candidate work arounds are:
- commented out the gem in the gemfile, run `gem pristine --all` then uncomment the gem and then `run bundle install.`
- delete the gems folder managed by bundler and do a bundle install. (e.g `.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/ ` or `.gem/ruby/3.2.2/bundler/gems`

Other work arounds that don't always work:
- Upgrading to a newer commit for the gem's version number. E.g. stay on packwerk 3.0.1 but choose a newer sha
- `gem uninstall bundler`, `gem install bundler` , `bundle install`

In one early case, we learned that in the bundler's managed version of the gem, there's a git repo and that git repo had everything deleted. We did a `git pull` and `git reset --hard origin/main` to completely reset the state of that directory to the most recent commit of the remote repo. In subsequent cases, these git repos appeared to be fine.

### Which command did you run?

bundle install

### What were you expecting to happen?

Normal `bundle install` behavior

### What actually happened?

```
Your bundle is locked to packwerk (3.0.1) from https://github.com/Shopify/packwerk.git (at main@b51ac53), but that version can no longer be found in that source. That means the author of packwerk (3.0.1) has removed it. You'll need to
update your bundle to a version other than packwerk (3.0.1) that hasn't been removed in order to install.
```

### If not included with the output of your command, run `bundle env` and paste the output below

I have this information for working machines.

## Environment

```
Bundler       2.4.15
  Platforms   ruby, arm64-darwin-22
Ruby          3.2.2p53 (2023-03-30 revision e51014f9c05aa65cbf203442d37fef7c12390015) [arm64-darwin-22]
  Full Path   /Users/todd.sedano/.rubies/ruby-3.2.2/bin/ruby
  Config Dir  /Users/todd.sedano/.rubies/ruby-3.2.2/etc
RubyGems      3.4.13
  Gem Home    /Users/todd.sedano/.gem/ruby/3.2.2
  Gem Path    /Users/todd.sedano/.gem/ruby/3.2.2:/Users/todd.sedano/.rubies/ruby-3.2.2/lib/ruby/gems/3.2.0
  User Home   /Users/todd.sedano
  User Path   /Users/todd.sedano/.gem/ruby/3.2.0
  Bin Dir     /Users/todd.sedano/.gem/ruby/3.2.2/bin
Tools
  Git         2.41.0
  RVM         not installed
  rbenv       not installed
  chruby      0.3.9
```

## Bundler Build Metadata

```
Built At          2023-06-29
Git SHA           702f922bf2
Released Version  true
```

## Bundler settings

```
build.nokogiri
  Set for your local app (/Users/todd.sedano/workspace/zenpayroll/.bundle/config): "--use-system-libraries"
force_ruby_platform
  Set for your local app (/Users/todd.sedano/workspace/zenpayroll/.bundle/config): false
```

RUBY VERSION
   ruby 3.2.2p53

BUNDLED WITH
   2.4.15
```

**Comment by deivid-rodriguez** [comment] 2023-07-06 17:40
Sorry you're having those issues :(

Ideally we'd need a reproducible case to be able to help. Maybe try reducing a small case that you can make public. For example, does it still happen if you remove all gems from the Gemfile, except for the one showing the issue? If you make a backup of those folders you mentioned above on a machine that has the issue, and then restore them after having fixed them with any of the workarounds, does the problem show up again?

**Comment by nertzy** [comment] 2023-07-07 14:41
I just started running into a similar issue today.

I had a project that was working properly, bundled with 2.4.10. I was having unrelated issues that I suspected might be fixed by recompiling native extensions for my gems, so I ran `bundle pristine --all`. Once that finished, the bundle would no longer activate.

```
❯ bin/rails --help

Could not find rails-boost-0.1.0 in https://github.com/srpatx/rails-boost.git nor scrapbook-rails-0.1.0 in https://github.com/srpatx/scrapbook-rails.git
Run `bundle install --gemfile /Users/grant/projects/title_chaining/Gemfile` to install missing gems.
```

I've tried running `bundle install`, `bundle update rails-boost`, etc., but nothing seems to get my local installation to properly find the gem version on that commit in that (public) repository. Here is the [commit](https://github.com/srpatx/rails-boost/commit/f2256c24fa602968f89ebfdb745e4e35065c93f4), it does exist.

```
❯ bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://enterprise.contribsys.com/..
Fetching source index from https://gems.karafka.io/
Your bundle is locked to rails-boost (0.1.0) from https://github.com/srpatx/rails-boost.git (at master@f2256c2),
but that version can no longer be found in that source. That means the author of rails-boost (0.1.0) has removed
it. You'll need to update your bundle to a version other than rails-boost (0.1.0) that hasn't been removed in
order to install.
```

Hi @professor! 👋🏻

**Comment by nertzy** [comment] 2023-07-07 14:52
I was able to dig further and navigate to the directory with the git checkout of the gem in question.

All of the files in its directory are deleted:

```
~/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-boost-f2256c24fa60 master*
❯ ls -al
total 0
drwxr-xr-x@  3 grant  staff   96 Jul  7 08:57 ./
drwxr-xr-x@ 11 grant  staff  352 Jul  7 08:57 ../
drwxr-xr-x@ 12 grant  staff  384 Jul  7 09:51 .git/
```

I ran `git reset --hard` in there and now things are back to normal.

So the bug is that `bundle pristine` appears to be deleting all of the files in the Git working copy.

**Comment by deivid-rodriguez** [comment] 2023-07-07 15:12
Thanks. So, what do I need to do to reproduce, this is happening for you in a public repo, right? So what do I need to run after cloning that repo?

**Comment by professor** [comment] 2023-07-12 22:13
We're still trying to find a minimal reproducible project. I've noticed that our issue only comes from gems that are defined like this...

```
gem 'rails', '7.0.6', github: 'rails', branch: '7-0-stable'
gem 'packwerk', github: 'Shopify/packwerk', branch: 'main'
gem 'buildkite-cli', github: 'gusto/buildkite-cli', branch: 'main'
gem 'socketry', github: 'socketry/socketry', ref: '8cb1516', require: false
gem 'webpacker', '6.0.0.beta.7', github: 'gusto/webpacker', branch: '6.0.0-beta.7'
```

On a machine that is having issues. We'll nuke all the bundle installed gems. (e.g. `mv .gem/ruby/3.2.2/bundler/gems /tmp`, then we'll do a `bundle install` and we still have the issue. My current guess is that there's a local cache of the github repo someplace on disk.

When we create a brand new project with a new Gemfile and only include the following, it work when it gets a different sha for that branch:
```
source 'https://rubygems.org'
ruby File.read(File.join(__dir__, '.ruby-version')).strip
gem 'rails', '7.0.6', github: 'rails', branch: '7-0-stable'

<and nothing else>
```

**Comment by deivid-rodriguez** [comment] 2023-07-13 09:11
Yes @professor, you're correct.

Bundler should be keeping a bare clone at `.gem/ruby/3.2.2/cache/bundler/git`, and then checking out the specific revision it resolves to into `.gem/ruby/3.2.2/bundler/gems`.

**Comment by nanaya** [comment] 2023-08-03 15:38
I have this problem (bundle not finding git-versioned gem after pristine) and removing the aforementioned `cache/bundler/git` fixed it.

**Comment by deivid-rodriguez** [comment] 2023-08-03 15:41
If you can provide a way to reproduce, I can try to help fixing this properly.

**Comment by nanaya** [comment] 2023-08-03 16:50
I can't reproduce it anymore. It was [this](https://github.com/feedbin/feedbin/tree/f1dbb6acc37ea8039cfa2a359611339bb468e023) and the error was

```
$ bundle pristine
...
Installing multipart-post 2.3.0                                                                                                                                 Installing faraday-multipart 1.0.4
Installing faraday-net_http 1.0.1
Installing faraday-net_http_persistent 1.2.0
Installing faraday-patron 1.0.0
Installing faraday-rack 1.0.0                                                                                                                                   Installing faraday-retry 1.0.3
Failed to pristine ruby2_keywords (0.0.5). Cached gem /opt/ruby32/lib/ruby/gems/3.2.0/cache/ruby2_keywords-0.0.5.gem does not exist.
Installing faraday 1.10.3
Using sax-machine 1.3.2 from https://github.com/feedbin/sax-machine.git (at feedbin@80c6e3b)
Using feedjira 2.1.2 from https://github.com/feedbin/feedjira.git (at f2@67807b0)
Installing http-cookie 1.0.5
Installing http-form_data 2.3.0
Installing ffi-compiler 1.0.1
Installing llhttp-ffi 0.4.0 with native extensions
Using http 5.1.0 from https://github.com/feedbin/http.git (at feedbin@abff8b0)
Installing rchardet 1.8.0
Installing http_parser.rb 0.6.0 with native extensions
Installing thread_safe 0.3.6
...
Installing standard-custom 1.0.2
Installing standard-performance 1.1.2
Installing standard 1.30.1
Installing stimulus-rails 1.2.1
Installing stripe 5.55.0
Using stripe-ruby-mock 2.5.0 from https://github.com/feedbin/stripe-ruby-mock.git (at feedbin@c391131)
Installing stripe_event 2.7.0
Installing strong_migrations 1.6.0
Installing tailwindcss-rails 2.0.30
Installing uglifier 4.2.0
Installing unicorn 6.1.0 with native extensions
Installing web-push 3.0.0
Installing webmock 3.8.0
Installing will_paginate 4.0.0
$ be rails assets:precompile
Could not find feedjira-2.1.2 in https://github.com/feedbin/feedjira.git (at f2@67807b0) nor feedkit-0.1.0 in https://github.com/feedbin/feedkit.git (at master@
f6688ea)
Run `bundle install` to install missing gems.
$ bundle
Fetching gem metadata from https://rubygems.org/.......
Your bundle is locked to feedjira (2.1.2) from https://github.com/feedbin/feedjira.git (at f2@67807b0), but that version can no longer be found in that source.
That means the author of feedjira (2.1.2) has removed it. You'll need to update
your bundle to a version other than feedjira (2.1.2) that hasn't been removed in order to install.
$ bundle --version
Bundler version 2.4.10
$ ruby --version
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-freebsd13.2]
$ cat .bundle/config
---
BUNDLE_PATH: "/home/feedbin/apps/ruby-bundle"
BUNDLE_DISABLE_SHARED_GEMS: "true"
```

**Comment by deivid-rodriguez** [comment] 2023-08-03 16:53
Ok. I'm going to close this. If someone can provide a repro, I'll reopen!

**Closed by deivid-rodriguez** 2023-08-03 16:53 UTC
Labels: type: bug report, Bundler
