### ISSUE TITLE
Surprising interaction between force_ruby_platform and bundle lock --add-platform

### ISSUE THREAD

**Issue by haines** [rubygems/rubygems#4125] opened 2020-12-11 11:02 UTC
### Describe the problem as clearly as you can

We're running macOS locally and Alpine Linux in production, so when we upgraded to Bundler 2.2.0 I wanted to include both `x86_64-darwin-19` and `x86_64-linux` in the `PLATFORMS` section of the lockfile, and platform-specific gems for both platforms in the `GEM.specs` section.

When I ran `bundle lock --add-platform x86_64-linux`, it correctly added `x86_64-linux` to `PLATFORMS` and `google-protobuf (3.13.0-x86_64-linux)` to `GEM.specs`.

I then ran `bundle lock --add-platform x86_64-darwin-19`, and it removed `x86_64-linux` and `google-protobuf (3.13.0-x86_64-linux)`, and replaced them with `x86_64-darwin-19` and `google-protobuf (3.13.0-universal-darwin)`.

This was surprising - I was expecting to have both darwin and linux in the lockfile after running these commands.

I tried reproducing in a clean repo with no success, and then discovered that I still had a `.bundle/config` file containing `BUNDLE_FORCE_RUBY_PLATFORM: "true"` in my application repo - a hangover from before google-protobuf released a platform-specific gem for Ruby 2.7  🤦 

After removing the `BUNDLE_FORCE_RUBY_PLATFORM` setting I was able to add both platforms to the lockfile successfully.

#### Gemfile

```ruby
source "https://rubygems.org"
gem "google-protobuf"
```

#### Commands
```console
$ bundle config set --local force_ruby_platform true

$ bundle install

$ cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    google-protobuf (3.14.0)

PLATFORMS
  ruby

DEPENDENCIES
  google-protobuf

BUNDLED WITH
   2.2.0

$ bundle lock --add-platform x86_64-darwin-19

$ cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    google-protobuf (3.14.0)
    google-protobuf (3.14.0-universal-darwin)

PLATFORMS
  ruby
  x86_64-darwin-19

DEPENDENCIES
  google-protobuf

BUNDLED WITH
   2.2.0

$ bundle lock --add-platform x86_64-linux

$ cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    google-protobuf (3.14.0)
    google-protobuf (3.14.0-x86_64-linux)

PLATFORMS
  ruby
  x86_64-linux

DEPENDENCIES
  google-protobuf

BUNDLED WITH
   2.2.0
```

### Which command did you run?

```console
$ bundle config set --local force_ruby_platform true
$ bundle install
$ bundle lock --add-platform x86_64-darwin-19
$ bundle lock --add-platform x86_64-linux
```

### What were you expecting to happen?

`bundle lock --add-platform` fails with a helpful error message when `force_ruby_platform` is `true`.

### What actually happened?

Bundler adds the first platform and then replaces it with the second.

### Environment

```
Bundler       2.2.0
  Platforms   ruby, x86_64-darwin-19
Ruby          2.7.2p137 (2020-10-01 revision 5445e0435260b449decf2ac16f9d09bae3cafe72) [x86_64-darwin19]
  Full Path   /Users/andrew/.rubies/ruby-2.7.2/bin/ruby
  Config Dir  /Users/andrew/.rubies/ruby-2.7.2/etc
RubyGems      3.1.4
  Gem Home    /Users/andrew/.gem/ruby/2.7.2
  Gem Path    /Users/andrew/.gem/ruby/2.7.2:/Users/andrew/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0
  User Home   /Users/andrew
  User Path   /Users/andrew/.gem/ruby/2.7.0
  Bin Dir     /Users/andrew/.gem/ruby/2.7.2/bin
Tools         
  Git         2.29.2
  RVM         not installed
  rbenv       not installed
  chruby      0.3.9
```

#### Bundler Build Metadata

```
Built At          2020-12-10
Git SHA           d3628e5019
Released Version  true
```

#### Bundler settings

```
force_ruby_platform
  Set for your local app (/Users/andrew/bundler-2.2-add-platform-repro/.bundle/config): true
```

**Comment by deivid-rodriguez** [comment] 2020-12-11 11:06
Hi @haines, thanks for reporting this. That's definitely an interesting interaction... What should we do there, though? Maybe warn when `bundle lock --add-platform` is run and the `force_ruby_platform` is set?

**Comment by deivid-rodriguez** [comment] 2020-12-11 11:07
Oh, I just saw that you updated the expected behaviour with throwing an error. That makes sense to me I think.

**Comment by haines** [comment] 2020-12-11 11:24
Yep, I think successfully adding the platform to the lockfile (even with a warning) in this case would be wrong, because next time `bundle install` updates the lockfile it'll remove the extra platforms anyway.

By setting `force_ruby_platform` I've told Bundler "don't install platform-specific gems" but by then running `bundle lock --add-platform` I'm telling Bundler "install platform-specific gems for this platform". I'm contradicting myself, so it seems reasonable for Bundler to refuse to comply 😄

**Comment by deivid-rodriguez** [comment] 2020-12-11 11:29
Absolutely, I fully agree with you :+1:.

**Comment by deivid-rodriguez** [comment] 2020-12-11 11:36
What about the reverse?

Having specific platforms locked in your lockfile, and trying to set `force_ruby_platform`? I guess we should also fail and tell users to run `bundle lock --remove-platform <non_ruby_platforms>` first if that's what they really want to do?

**Comment by haines** [comment] 2020-12-11 11:54
I think it'd have to be a check during `bundle install`, right? In case someone sets `force_ruby_platform` via an environment variable, for example.

I think in this case Bundler could either fail and tell the user how to fix the situation (as you suggest), or proceed with the install and remove the other platforms, but print a warning like

```
WARN Removed platforms from your lockfile because force_ruby_platform is set to true
<in .bundle/config|via BUNDLE_FORCE_RUBY_PLATFORM|...>.

To undo this change, unset force_ruby_platform and run
  bundle lock --add-platform a
  bundle lock --add-platform b
```

**Comment by deivid-rodriguez** [comment] 2020-12-11 12:04
Well, you're totally right again!

**Comment by deivid-rodriguez** [comment] 2020-12-11 12:06
I think plain error might be easier. We try to move to better supported platform specific gems, so I expect `force_ruby_platform` to be less used over time, so this should be a rare case.

**Comment by haines** [comment] 2020-12-11 17:23
I started on a PR (#4126) and might have come across an alternative option to throwing an error when installing from a multiplatform lockfile with `force_ruby_platform` set.

I think we can just remove the behaviour that strips the non-ruby-platform dependencies from the lockfile when running with `force_ruby_platform`? That's a small change to remove this conditional, so that we always start with the same list of platforms as in the lockfile: 

https://github.com/rubygems/rubygems/blob/a6db700eab4d750aed63f897e4bed52e53c4b676/bundler/lib/bundler/definition.rb#L91-L95

That way, the config option just means "I don't want to install platform-specific gems on this machine" rather than "I don't want anyone to install platform-specific gems on any machine".

What do you think?

**Comment by deivid-rodriguez** [comment] 2020-12-11 20:53
Hei @haines, thanks for the help!

While a change that removes code and fixes an issue seems very appealing, I think we should carefully think about that since it changes the specification for the option after all. Your other proposal seems a no-brainer, so I'd go with that now and then give the other idea some more calmed thought.

**Comment by haines** [comment] 2020-12-11 21:29
Fair enough! I've marked the PR as ready for review with only the first change included.

What's potentially worth considering, though, is that removing the behaviour that strips the extra platforms might actually eliminate the need to throw the error when attempting to add a platform!

Based on the suggested semantics that the config option should only affect which platforms are selected for installation, not which platforms are included in the lockfile, it would be valid to want to add a platform to the lockfile even when `force_ruby_platform` is true.

And, without that conditional, it would actually work... The surprising behaviour I encountered only happens because we reset the platforms to a single-element array on line 92 before adding the new one.

Happy to proceed as you see fit - I don't think this urgently needs to be fixed (it was 90% user error!) so if you'd prefer to consider it more before making any changes, that's fine by me 🙂

**Comment by deivid-rodriguez** [comment] 2020-12-11 22:01
> Based on the suggested semantics that the config option should only affect which platforms are selected for installation, not which platforms are included in the lockfile, it would be valid to want to add a platform to the lockfile even when force_ruby_platform is true.

Actually, the config option affects resolution. Basically it tells the resolver to disregard any platform specific gems. Then installation installs what was resolved. So basically with `force_ruby_platform` you'll never get any platform specific gems in the lockfile at all, so no platform specific gems get ever installed.

So, I don't see how you'd want platforms in your lockfile and ignore platform specific gems at the same time. If it's for another machine without the `force_ruby_platform` setting, then the lockfile will be incorrect anyways and will need to be reresolved I believe.

**Comment by haines** [comment] 2020-12-12 00:53
>So basically with `force_ruby_platform` you'll never get any platform specific gems in the lockfile at all, so no platform specific gems get ever installed.

I think this would no longer be the case if we removed the check for `force_ruby_platform` in the definition.

Please feel free to correct me here because I'm not super familiar with the codebase, but here's my understanding!

`force_ruby_platform` is currently used in three places:

1. It sets `Bundler.local_platform` to `ruby` [here](https://github.com/rubygems/rubygems/blob/a6db700eab4d750aed63f897e4bed52e53c4b676/bundler/lib/bundler.rb#L437-L440)
2. It sets `Bunder.rubygems.platforms` to `[ruby]` [here](https://github.com/rubygems/rubygems/blob/a6db700eab4d750aed63f897e4bed52e53c4b676/bundler/lib/bundler/rubygems_integration.rb#L113-L116)
3. It sets `Bundler.definition.platforms` to `[ruby]`, ignoring what's in the lockfile, [here](https://github.com/rubygems/rubygems/blob/a6db700eab4d750aed63f897e4bed52e53c4b676/bundler/lib/bundler/definition.rb#L91-L95)

Removing 3. but keeping 1. and 2. will mean:
- installation on a machine with `force_ruby_platform = true` does not install platform-specific gems (the existing behaviour)
- resolution on a machine with `force_ruby_platform = true` will resolve for all the platforms listed in the lockfile (adding `ruby` if it's not already there), and not remove any platforms from the lockfile (not the existing behaviour, but imho it makes more sense)

It doesn't change the existing behaviour for installation, because that relies on 2., which is used to filter the set of specs to install [here](https://github.com/rubygems/rubygems/blob/a6db700eab4d750aed63f897e4bed52e53c4b676/bundler/lib/bundler/spec_set.rb#L187).

It does result in resolving platform-specific gems for all platforms listed in the lockfile, because the list of platforms that is passed to the resolver [here](https://github.com/rubygems/rubygems/blob/a6db700eab4d750aed63f897e4bed52e53c4b676/bundler/lib/bundler/definition.rb#L277) is now the list of platforms included in the lockfile (plus `ruby` is added if it wasn't there already [here](https://github.com/rubygems/rubygems/blob/a6db700eab4d750aed63f897e4bed52e53c4b676/bundler/lib/bundler/definition.rb#L557-L563))

This means that you wouldn't get platform-specific gems installed on the machine with `force_ruby_platform` set, but you would continue to have a valid lockfile for other machines which do want platform-specific gems.

**Comment by deivid-rodriguez** [comment] 2020-12-12 10:27
I think you're probably right. Just not 100% sure if the new behaviour will be more useful for people than plain incompatibility between the setting and multiple platforms. I mean, in your use case, wasn't the `force_ruby_setting` just a left over but you _do_ want platform specific gems installed in your machine?

**Comment by haines** [comment] 2020-12-12 12:52
Yeah, absolutely, I did want platform-specific gems, so I'd have been totally happy if Bundler just threw an error and told me not to do that 🙂

I guess the question we need to answer is "for two different users/machines using the same Gemfile.lock, is there ever a valid reason for one to want platform-specific gems and the other not to?"

If there's no reason to allow that, then making the setting incompatible with multiplatform lockfiles totally makes sense.

I'm wondering if there is a situation where a platform-specific gem might not be compatible with a particular machine on that platform - maybe a linux gem is fine on Ubuntu but doesn't work on Alpine - so that some users might want to opt out of installing them without forcing other users to?

**Comment by deivid-rodriguez** [comment] 2020-12-13 17:40
Hei!

Although generally one of the main goals of bundler is to provide a consistent and deterministic environment for all users and environments of an application and we try to deviate from these machine/user/environment discrepancies, what you present sounds like a plausible reason to allow that, indeed?

I've actually have reworked how this works due to several issues we've created with this release. The most important change is https://github.com/rubygems/rubygems/pull/4134, where "RUBY" is no longer kept in the lockfile by default (it's replaced by the specific platform), unless:

* It's already there and you're in frozen mode.
* You have `force_ruby_platform` enabled.

I think it would make sense to go with your suggestion and could be easily applied on top of that PR. I'm going to aim to release bundler 2.2.1 tomorrow, and after that we can revisit this, since this sounds like a less pressing problem, ok?

**Comment by haines** [comment] 2020-12-13 17:42
Sounds like a plan 👍

**Comment by deivid-rodriguez** [comment] 2020-12-15 10:09
Hi @haines! Bundler 2.2.1 is out now, we can proceed with this.

I think your idea makes of allowing `--add-platform` to be used with `force_ruby_platform` makese sense, can you get it ready?

**Comment by haines** [comment] 2020-12-15 11:59
Will do!

**Comment by deivid-rodriguez** [comment] 2020-12-15 12:27
By the way, I noticed what I think it's a bug with `force_ruby_platform` at the moment, and I think it could be related to this.

Right now the `RUBY` platform is no longer recorded in the lockfile. You can force it to be recorded though by using either `force_ruby_platform` and running `bundle install` or by using `bundle lock --add-platform ruby`.

However, if you already have a lockfile generated with bundler 2.2 (no RUBY platform), and run `bundle install` with `force_ruby_platform` enabled, then RUBY will replace the locked platform. I expect your PR to, instead, result in the RUBY platform being added to the list of locked platforms. Correct?

However, I also observe that the resolution with `force_ruby_platform` is the same if there's a lockfile with platform specific gems. `bundle install` with `force_ruby_platform` in that situation should resolve in the lockfile being resolved again, and no platform specific gems being installed at all.

I _think_ a patch like this:

```diff
diff --git a/bundler/lib/bundler/match_platform.rb b/bundler/lib/bundler/match_platform.rb
index 69074925a6..50a6cb3167 100644
--- a/bundler/lib/bundler/match_platform.rb
+++ b/bundler/lib/bundler/match_platform.rb
@@ -13,6 +13,7 @@ def match_platform(p)
     def self.platforms_match?(gemspec_platform, local_platform)
       return true if gemspec_platform.nil?
       return true if Gem::Platform::RUBY == gemspec_platform
+      return false if Bundler.settings[:force_ruby_platform]
       return true if local_platform == gemspec_platform
       gemspec_platform = Gem::Platform.new(gemspec_platform)
       return true if GemHelpers.generic(gemspec_platform) === local_platform
```

might solve that issue but no idea if it could break other stuff since I didn't run tests with that.

Anyways, I thought it could maybe help here :+1:.

**Comment by deivid-rodriguez** [comment] 2021-02-01 11:43
@haines Are you still planning to work on this?

**Comment by haines** [comment] 2021-02-01 12:34
Yep, I'll take a look!

**Comment by haines** [comment] 2021-02-01 13:57
@deivid-rodriguez I've opened #4336 - from the subset of specs that I've run locally, it looks like removing the special treatment of `force_ruby_platform` in the definition is sufficient. Hopefully CI agrees 😅

**Closed** 2021-02-03 09:58 UTC
Labels: Bundler
