### ISSUE TITLE
Cannot lock bundler version to <2

### ISSUE THREAD

**Issue by thedanbob** [rubygems/rubygems#3323] opened 2019-04-04 15:52 UTC
I have rails projects that cannot be updated to bundler 2 yet because the servers still have bundler 1. According to the [docs](https://bundler.io/v2.0/guides/bundler_2_upgrade.html), the Gemfile.lock is only updated to use bundler 2 if you run `bundle update --bundler`. However, my Gemfile.lock is getting updated to bundler 2.0.1 when I run just `bundle update`. If I try to set the version of bundler in the Gemfile with `gem 'bundler', '< 2'` I get the error

```
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    bundler (< 2)

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (< 2)' in any of the relevant sources:
  the local ruby installation
```
I have both bundler 2.0.1 and 1.17.3 installed.

**Comment by deivid-rodriguez** [comment] 2020-09-03 20:26
I think this is a duplicate of https://github.com/rubygems/rubygems/issues/3318.

The referenced issue is newer, and has a very nice explanation, so I'll close this ticket in favor of that one.

**Comment by thedanbob** [comment] 2020-09-03 21:04
I don't think these are actually duplicates. The other issue happens when you don't have a `Gemfile.lock` while this one occurs because bundler is ignoring the `BUNDLED WITH` line in `Gemfile.lock`. Unless specifying a bundler version in the `Gemfile` has the same effect as the `BUNDLED WITH` line, I suppose.

But since ruby 2.3 and 2.4 are both EOL now and this bug doesn't affect newer rubies, I guess the point is moot.

**Comment by deivid-rodriguez** [comment] 2020-09-03 21:18
Oh, I see, you're right. I thought it was the same case because https://github.com/rubygems/rubygems/issues/3323#issuecomment-505893412 repro instructions included "delete Gemfile.lock". Reopening!

**Comment by deivid-rodriguez** [comment] 2021-12-19 21:50
Since we will no implement auto installing and auto switching to the `BUNDLED WITH` version in #4076, I think this should no longer be an issue because your servers should be ready for bundler 2, just like for every other gem (the `BUNDLED WITH` version willl be installed alongside with the rest of your gems).

So I'll close this because of that but let me know if this doesn't sound good.

In fact, now that we have auto locking, I think we should [change the behavior of `bundle update`](https://github.com/rubygems/rubygems/issues/5171) to behave like explained in this ticket.

**Closed by deivid-rodriguez** 2021-12-19 21:50 UTC
Labels: Bundler, category: bundler version locking
