### ISSUE TITLE
Ignore `Bundler::GemNotFound` for gems in `without` groups

### ISSUE THREAD

**Issue by stdedos** [rubygems/rubygems#3248] opened 2020-02-12 14:45 UTC
I am not sure if it makes sense, but I'll try to make a case.

tl;dr: Should `bundle exec` be `.bundle/config`-aware?
_May be related to #6312_

----

I have:

```ruby
gem 'a'

group :ignore do
	gem 'rake'
end

group :dev do
	gem 'c'
	gem 'rubocop'
end
```

and:

```console
$  bat .bundle/config 
───────┬───────────────────────────────────────
       │ File: .bundle/config
───────┼───────────────────────────────────────
   1   │ ---
   2   │ BUNDLE_WITHOUT: "ignore"
───────┴───────────────────────────────────────
```

And I have normally done `bundle install`.

----

Now, if I try to run:

```console
$ ~/.rvm/bin/rvm ruby-2.6.5@dev do ~/.rvm/gems/ruby-2.6.5@dev/bin/bundle exec ~/.rvm/rubies/ruby-2.6.5/bin/ruby ~/.rvm/gems/ruby-2.6.5@dev/bin/rubocop --format json --force-exclusion Gemfile
```

I will get this:
```
Could not find rake-13.0.1 in any of the sources
Run `bundle install` to install missing gems.
```

or that:
```console
~/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler/spec_set.rb:91:in `block in materialize': Could not find rake-13.0.1 in any of the sources (Bundler::GemNotFound)
	from ~/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler/spec_set.rb:85:in `map!'
	from ~/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler/spec_set.rb:85:in `materialize'
	from ~/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:170:in `specs'
	from ~/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:237:in `specs_for'
	from ~/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:226:in `requested_specs'
	from ~/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:108:in `block in definition_method'
	from ~/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:20:in `setup'
	from ~/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2. ...
 
```

**Comment by deivid-rodriguez** [comment] 2020-09-17 11:45
Hi @stdedos!

This is, as far as I know, the exact use case for the `BUNDLE_WITHOUT` configuration. What is your expectation here?

**Comment by stdedos** [comment] 2020-09-17 12:55
> Hi @stdedos!

Hellou! 😃 

> This is, as far as I know, the exact use case for the `BUNDLE_WITHOUT` configuration. What is your expectation here?

What would "this is [...] the exact use case" stand for?
The issue is a little bit old, I didn't do a perfect job in describing it and/or I need to regain context. 😅 

I am assuming: I have setup my dev environment very well, and fetched everything. Now, I am trying to run `rubocop` (via this very elaborate command that is no contraption of mine), and I fail to do so.

I am assuming that the command is correct (if I am not wrong it's Jetbrains' magic), so - why would it annoy me about `rake` missing? I have a successful `bundle install` run and, if I "run something via it", IMU it should not fail.

**Comment by deivid-rodriguez** [comment] 2020-09-17 13:03
You use `BUNDLE_WITHOUT` when you want a specific set of gems ignored on a specific environment. So this is what `bundler` is doing: not installing gems in the `ignore` group, and not considering them on a `bundle exec` context.

I think you might want to remove your `.bundle/config` file, since I don't think you actually want this configuration in your current environment. That should fix the error you're getting.

**Comment by stdedos** [comment] 2020-09-17 13:06
It appears to me that it's ignoring them for `install`, but it's not for `exec`.

Actually, I don't want the `:ignored` set nowhere. They are just there for "reference purposes". But I don't want them "gray" either (i.e. commented-out)

**Comment by deivid-rodriguez** [comment] 2020-09-17 13:09
> It appears to me that it's ignoring them for install, but it's not for exec.

It's ignoring them for install, and then failing to find them for `bundle exec` since it's ignoring them for install, so they are not installed.

> Actually, I don't want the :ignored set nowhere. They are just there for "reference purposes". But I don't want them "gray" either (i.e. commented-out)

I'm not sure what you mean, sorry. Can you elaborate?

**Comment by stdedos** [comment] 2020-09-17 13:37
> > It appears to me that it's ignoring them for install, but it's not for exec.
> 
> It's ignoring them for install, and then failing to find them for `bundle exec` since it's ignoring them for install, so they are not installed.

Oh. I thought it would *just* ignore them. Forever, from everything

> > Actually, I don't want the :ignored set nowhere. They are just there for "reference purposes". But I don't want them "gray" either (i.e. commented-out)
> 
> I'm not sure what you mean, sorry. Can you elaborate?

There is this "notepad" of gems that are stored in the Gemfile. I want them to still be there, preferably uncommented, and not taken into any account for any operation.

**Comment by deivid-rodriguez** [comment] 2020-09-17 14:01
> Oh. I thought it would just ignore them. Forever, from everything

So, what would you expect `bundle exec rake` to do, then? You want a different error message?

> There is this "notepad" of gems that are stored in the Gemfile. I want them to still be there, preferably uncommented, and not taken into any account for any operation.

Interesting. Well, we definitely don't expect people to keep gems that they don't want to use in their Gemfile. Also, if you don't want to use `rake`, why are you running `bundle exec rake`.

Actually, I just looked closely at your report, and I see that you're not running `bundle exec rake`, but `~/.rvm/bin/rvm ruby-2.6.5@dev do ~/.rvm/gems/ruby-2.6.5@dev/bin/bundle exec ~/.rvm/rubies/ruby-2.6.5/bin/ruby ~/.rvm/gems/ruby-2.6.5@dev/bin/rubocop --format json --force-exclusion Gemfile`, without specifying `rubocop` in your `Gemfile`? This sounds like something we definitely we don't support.

**Comment by stdedos** [comment] 2020-09-17 14:33
> > Oh. I thought it would just ignore them. Forever, from everything
> 
> So, what would you expect `bundle exec rake` to do, then? You want a different error message?

_Nothing, since I am not talking about that command I guess_

> > There is this "notepad" of gems that are stored in the Gemfile. I want them to still be there, preferably uncommented, and not taken into any account for any operation.
> 
> Interesting. Well, we definitely don't expect people to keep gems that they don't want to use in their Gemfile.

Yeah, it kinda feels that way to me too. However, all gems related to this repo (think of them as "optional dependencies") will be under one place, instead once in the Gemfile, and once _somewhere else_

> Actually, I just looked closely at your report, and I see that you're not running `bundle exec rake`, but `~/.rvm/bin/rvm ruby-2.6.5@dev do ~/.rvm/gems/ruby-2.6.5@dev/bin/bundle exec ~/.rvm/rubies/ruby-2.6.5/bin/ruby ~/.rvm/gems/ruby-2.6.5@dev/bin/rubocop --format json --force-exclusion Gemfile`, without specifying `rubocop` in your `Gemfile`? This sounds like something we definitely we don't support.

Apologies, too much scrubbing on the `Gemfile`. Rubocop is under `:dev`

**Comment by deivid-rodriguez** [comment] 2020-09-17 16:06
No problem, thanks for editing the description.

Ok, then this makes somewhat more sense now. It's pretty weird the way commands are run (prepending the full path to `ruby` to the full path to `bundler`). But I guess things should still work and if `rake` is a runtime dependency of `rubocop`, it should still be found, since even if it's part of an ignored group, it's also a dependency of `rubocop`.

Now I would need you to create a sample application that reproduces this error, so that I can investigate it, since I've never seen something like this.

**Comment by deivid-rodriguez** [comment] 2020-10-01 10:53
No further feedback, so I'll go ahead and close this. Feel free to reopen if you can help us reproduce this issue!

**Closed by deivid-rodriguez** 2020-10-01 10:53 UTC
Labels: Bundler, status: user feedback required

**Comment by stdedos** [comment] 2020-10-01 11:11
I haven't had time to actually do anything, and as you can see, this is a pretty old issue.
If you don't lock the conversation, I do have this in my backlog somewhere.

**Comment by deivid-rodriguez** [comment] 2020-10-01 11:43
No problem, yeah, I'm triaging old issues (better late than never... :sweat_smile:). I'll leave this as it is now, whenever you get to it, you can reopen it with repro steps :+1:.
