### ISSUE TITLE
`bundler-2.3.26` removes `debug` gem dependecies on ruby-3.1.3

### ISSUE THREAD

**Issue by ojab** [rubygems/rubygems#6082] opened 2022-11-28 15:22 UTC
### Describe the problem as clearly as you can

Given `Gemfile`
```ruby
# frozen_string_literal: true

source "https://rubygems.org"

ruby '3.1.2'

gem 'debug'
```
and generated `Gemfile.lock`
```
GEM
  remote: https://rubygems.org/
  specs:
    debug (1.6.3)
      irb (>= 1.3.6)
      reline (>= 0.3.1)
    io-console (0.5.11)
    irb (1.5.0)
      reline (>= 0.3.0)
    reline (0.3.1)
      io-console (~> 0.5)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  debug

RUBY VERSION
   ruby 3.1.2p20

BUNDLED WITH
   2.3.26
```
after updating ruby to 3.1.3 with corresponding `Gemfile` change, we're getting 
```patch
diff --git a/Gemfile.lock b/Gemfile.lock
index 5c27724..18bfece 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -2,13 +2,6 @@ GEM
   remote: https://rubygems.org/
   specs:
     debug (1.6.3)
-      irb (>= 1.3.6)
-      reline (>= 0.3.1)
-    io-console (0.5.11)
-    irb (1.5.0)
-      reline (>= 0.3.0)
-    reline (0.3.1)
-      io-console (~> 0.5)
 
 PLATFORMS
   x86_64-linux
@@ -17,7 +10,7 @@ DEPENDENCIES
   debug
 
 RUBY VERSION
-   ruby 3.1.2p20
+   ruby 3.1.3p185
 
 BUNDLED WITH
    2.3.26
```
after running `bundle`.
This shouldn't happen because `debug` has `irb` & `reline` in runtime deps and removal breaks `deployment true`:
```
$ bundle config --local set deployment true
$ BUNDLE_PATH=/tmp/b bundle
Fetching gem metadata from https://rubygems.org/...
Using bundler 2.3.26
Downloading debug-1.6.3 revealed dependencies not in the API or the lockfile (irb (>= 1.3.6), reline (>= 0.3.1)).
Either installing with `--full-index` or running `bundle update debug` should fix the problem.
```

$ bundle env
## Environment

```
Bundler       2.3.26
  Platforms   ruby, x86_64-linux
Ruby          3.1.3p185 (2022-11-24 revision 1a6b16756e0ba6b95ab71a441357ed5484e33498) [x86_64-linux]
  Full Path   /home/ojab/.rbenv/versions/3.1.3/bin/ruby
  Config Dir  /home/ojab/.rbenv/versions/3.1.3/etc
RubyGems      3.3.26
  Gem Home    /home/ojab/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0
  Gem Path    /home/ojab/.gem/ruby/3.1.0:/home/ojab/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0
  User Home   /home/ojab
  User Path   /home/ojab/.gem/ruby/3.1.0
  Bin Dir     /home/ojab/.rbenv/versions/3.1.3/bin
Tools         
  Git         2.38.0
  RVM         not installed
  rbenv       rbenv 1.2.0-48-g6717c62
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-11-28
Git SHA           unknown
Released Version  false
```

## Bundler settings

```
build.gpgme
  Set for the current user (/home/ojab/.bundle/config): "--use-system-libraries"
build.nokogiri
  Set for the current user (/home/ojab/.bundle/config): "--use-system-libraries"
gem.changelog
  Set for the current user (/home/ojab/.bundle/config): true
gem.ci
  Set for the current user (/home/ojab/.bundle/config): false
gem.coc
  Set for the current user (/home/ojab/.bundle/config): false
gem.linter
  Set for the current user (/home/ojab/.bundle/config): false
gem.mit
  Set for the current user (/home/ojab/.bundle/config): false
gem.test
  Set for the current user (/home/ojab/.bundle/config): "rspec"
jobs
  Set for the current user (/home/ojab/.bundle/config): 8
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

ruby '3.1.3'

gem 'debug'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    debug (1.6.3)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  debug

RUBY VERSION
   ruby 3.1.3p185

BUNDLED WITH
   2.3.26
```

**Comment by rbclark** [comment] 2022-11-28 15:44
I'm running into this same issue as well. So far it seems no matter what I do it is currently impossible to get a functional lockfile on `3.1.3`. Since this is on a project that already is working fine on ruby `3.1.2`, I've tried:

- Deleting the `Gemfile.lock` and regenerating.
- Upgrading from our current bundler version `2.3.12` to `2.3.26`
- Reverting the `Gemfile.lock` to the one we currently have in `main`, upgrading ruby and running `bundle` again.

No matter what I do I can't get a version that actually works in deployment mode.

**Comment by nickstanish** [comment] 2022-11-28 17:01
I found a way to manually repair Gemfile.lock to get it to work with deployment mode in 3.1.3:

- disable deployment mode temporarily: `$ bundle config unset --local deployment &&  bundle config unset --local path`
- upgrade to bundler `2.3.26`: `$ bundle update --bundler`
- include `irb` and `reline` in Gemfile and run `$ bundle install`, which should succeed
- add the missing lines under debug in Gemfile.lock 

```
    debug (1.6.3)
      irb (>= 1.3.6)
      reline (>= 0.3.1)
```

After that, `bundle install` succeeded for me in deployment mode and subsequent installs do not seem to remove the lines

**Comment by miharekar** [comment] 2022-11-28 17:14
This gems are now included in the system Ruby, so I don’t think this is incorrect behavior.

**Comment by deivid-rodriguez** [comment] 2022-11-28 20:26
Hei! This issue is actually fixed in master, currently tracking down which specific change fixed it, and figuring out whether it should be backported or not.

**Comment by deivid-rodriguez** [comment] 2022-11-28 21:02
This is actually a ruby-core issue.

The default `debug-1.6.3.gemspec` file that comes installed with Ruby 3.1.3 does not specify any dependencies. A workaround is to reinstall the debug gem manually (`gem install debug`) so that the gemspec is regenerated with the proper dependencies and Bundler can use that information.

The reason this works on master is just luck. In [this commit](https://github.com/rubygems/rubygems/commit/7b64c64262a7a980c0eb23b96ea56cf72ea06e89), which was not meant to change behavior, I unintentionally reversed the order of locked specs vs remote/installed specs when considering them for resolution.

<img width="922" alt="Captura de pantalla 2022-11-28 a las 21 54 04" src="https://user-images.githubusercontent.com/2887858/204378835-9e63e4eb-9455-464b-a04f-d0894be9c010.png">

Previously locked specs were placed at the end of the results array, and installed specs at the beginning. That resulted in the dependencies of installed specs taking priority (and these are none due to the ruby-core bug). After that change, locked specs are considered first, which means dependencies recorded in the lockfile are always respected.

I'll try to write a spec to make sure we're not affected by this kind of ruby-core bug in the future again, and will also report this to ruby-core.

**Comment by deivid-rodriguez** [comment] 2022-11-29 12:41
I created #6085 to backport the fix to Bundler 2.3, together with a regression test.

I will now report the issue to ruby-core. From a quick first search for potential culprits, https://github.com/ruby/ruby/commit/a2c66f52f402cb58372e271226f3341065561e53 sounds like a likely candidate.

**Comment by deivid-rodriguez** [comment] 2022-11-29 12:57
Reported to ruby-core as https://bugs.ruby-lang.org/issues/19158.

**Comment by hsbt** [comment] 2022-11-30 07:24
@deivid-rodriguez Thanks for your investigation.

**Closed** 2022-12-01 09:10 UTC
Labels: Bundler

**Comment by loust333** [comment] 2022-12-01 11:35
Hello people, 

_Just adding my use case here for reference:_ 

I had the same issue with bundler 2.3.14.

The issue appeared when executing the rails test with github action after upgrading to **ruby-3.1.3.**

Error:
```
Run ruby/setup-ruby@v1
Modifying PATH
Downloading Ruby
Extracting  Ruby
Print Ruby version
Installing Bundler
bundle install
Error: Error: The process '/opt/hostedtoolcache/Ruby/3.1.3/x64/bin/bundle' failed with exit code 34
    at ExecState._setResult (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5340:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5323:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5217:27)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

This confirms that the issue is not from bundler but ruby-3.1.3 as indicated from @deivid-rodriguez 

To solve the issue: 

Commented in the gemfile the debug gem

```
  # TODO: Reinstall debug after bundler 2.4
  # gem "debug", platforms: [:mri, :mingw, :x64_mingw]
```

and installed debug temporarily:

`gem install debug`

Thanks for the feedback everyone.

**Comment by melvinotieno** [comment] 2023-02-18 19:41
> Just as a note to everyone following along, since `debug 1.7.0` shipped it is now possible to upgrade to that version in order to get past this issue.

And the issue comes back on debug 1.7.1

**Comment by palladius** [comment] 2024-07-07 11:48
What's the status? I'm still hit by this issue when trying to compile my Dockerfile

**Comment by deivid-rodriguez** [comment] 2024-07-08 13:04
This particular issue was fixed a long time ago. I think something similar to this reappeared recently with another default gem, but I'd need more information to be able to help. Feel free to open a [new discussion](https://github.com/orgs/rubygems/discussions/new?category=q-a) with more details.
