### ISSUE TITLE
Unable to install any ruby gem on my Mac - libsystem_network.dylib not found

### ISSUE THREAD

**Issue by Schnodderbalken** [rubygems/rubygems#3628] opened 2020-05-14 13:28 UTC
This issue is related to:
  - [X] Installing a library

My current problem is that I can not install any ruby gem on my MacBook Pro 2013. 
No matter which gem I want to install (in this case I tried `cocoapoads`), it always gives me this output:

```
Building native extensions. This could take a while...
ERROR:  Error installing cocoapods:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.7.0/gems/ffi-1.12.2/ext/ffi_c
/usr/local/opt/ruby/bin/ruby -I /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0 -r ./siteconf20200514-18511-14cul4f.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/Cellar/ruby/2.7.1_2/bin/$(RUBY_BASE_NAME)
	--with-ffi_c-dir
	--without-ffi_c-dir
	--with-ffi_c-include
	--without-ffi_c-include=${ffi_c-dir}/include
	--with-ffi_c-lib
	--without-ffi_c-lib=${ffi_c-dir}/lib
	--enable-system-libffi
	--disable-system-libffi
	--with-libffi-config
	--without-libffi-config
	--with-pkg-config
	--without-pkg-config
/usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/mkmf.rb:471:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/mkmf.rb:564:in `try_link0'
	from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/mkmf.rb:582:in `try_link'
	from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/mkmf.rb:684:in `try_ldflags'
	from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/mkmf.rb:1851:in `pkg_config'
	from extconf.rb:9:in `system_libffi_usable?'
	from extconf.rb:34:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/lib/ruby/gems/2.7.0/extensions/x86_64-darwin-19/2.7.0/ffi-1.12.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/2.7.0/gems/ffi-1.12.2 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.7.0/extensions/x86_64-darwin-19/2.7.0/ffi-1.12.2/gem_make.out
```

If I look into the content of the mkmf.log, I see the following:

```
"pkg-config --exists libffi"
| pkg-config --libs libffi
=> "-lffi\n"
"clang -o conftest -I/usr/local/Cellar/ruby/2.7.1_2/include/ruby-2.7.0/x86_64-darwin19 -I/usr/local/Cellar/ruby/2.7.1_2/include/ruby-2.7.0/ruby/backward -I/usr/local/Cellar/ruby/2.7.1_2/include/ruby-2.7.0 -I.  -I/usr/local/opt/libyaml/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/readline/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wdivision-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wmissing-noreturn -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wextra-tokens  -fno-common -pipe conftest.c  -L. -L/usr/local/Cellar/ruby/2.7.1_2/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib     -lruby.2.7   "
ld: file not found: /usr/lib/system/libsystem_network.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */
```

Here are my current environment details:

```
$ gem env version
3.1.2
$ ruby --version
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
$ clang --version                                                                          
Apple clang version 11.0.3 (clang-1103.0.32.59)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ xcode-select --version
xcode-select version 2373.
```
MacOS Catalina Version 10.15.4 (19E287)

I have installed ruby via homebrew. It used to work a couple of weeks ago.

I wonder which part looks or libsystem_network.dylib and why

**Comment by bronzdoc** [comment] 2020-05-19 03:55
Couldn't reproduce this. Seems like `libsystem_network.dylib` is no longer present in newer Mac OS. Try re installing ruby?

**Comment by Schnodderbalken** [comment] 2020-05-19 06:33
@bronzdoc thank you.  Unfortunately I already tried reinstalling ruby (the currently installed version is the newest available version in homebrew) - no success. In fact, I have already spent countless hours on that issue.
I think the most interesting question would be, which part (ruby? gems? libffi? clang) wants to access the `libsystem_network.dylib`. As you correctly stated, this lib hasn't been part of MacOS for several years now. But why is some part of the installation routine even requesting it? And can I update this part?
I also already updated XCode and used a different C++ compiler (gcc instead of the native one) but all that changed literally nothing :(.

**Comment by deivid-rodriguez** [comment] 2020-05-19 09:33
Hi @Schnodderbalken, this is most likely not a problem in `rubygems`, but in either the `ffi` gem or your `ruby` installation.

I found [this thread in the `ffi` repo](https://github.com/ffi/ffi/issues/653), which has a couple of posts with a lot of :heart:, :+1: and :rocket: reactions, so I recommend that you go carefully through it and you'll hopefully be able to fix your issues.

I'm going to close this ticket, but if you still think there's a problem in this repo, please continue the discussion.

Good luck!

**Closed by deivid-rodriguez** 2020-05-19 09:33 UTC
Labels: RubyGems

**Comment by deivid-rodriguez** [comment] 2020-05-19 09:51
Actually, the thread I linked to does not mention `libsystem_network.dylib` so it might not be helpful to you :(, sorry.

**Comment by simi** [comment] 2020-05-19 09:54
I would suggest to remove all gems or reinstall (`gem pristine --all`).

**Comment by deivid-rodriguez** [comment] 2020-05-19 10:07
I've heard this kind of problem on MacOS before and it was due to `brew` being configured to use a specific version of a system library, but your ruby being linked against another. For example, this stackoverflow thread explains how to fix a similar issue for `readline` using `brew switch` or directly adding the proper symlinks: https://stackoverflow.com/questions/21488778/library-not-loaded-usr-local-opt-readline-lib-libreadline-6-2-dylib/41476592#41476592.

**Comment by Schnodderbalken** [comment] 2020-05-19 10:27
@simi I tried your suggestion but the problem persists.

@deivid-rodriguez but wouldn't this also be resolved by completely reinstalling homebrew's `ruby`and `ruby-build`? Just tried that. Does not make a difference. Or is there any other way to completely reset linking in that regard?

I also made a search on my hard drive for `libsystem_network.dylib`. Found an occurrence somewhere iOS Simulator folder. Gave it a shot and copied it to where my other dylibs are. Now I get this:

```ld: warning: building for macOS, but linking in dylib file (/usr/local/lib/libsystem_network.dylib) built for iOS Simulator
ld: file not found: /usr/lib/system/libsystem_stats.dylib for architecture x86_64```

So it's telling me that the `libsystem_network.dylib` I copied there is incompatible (no surprise). However, now the next lib is missing. Why does it look for dylibs which are not on my system in the first place?

**Comment by deivid-rodriguez** [comment] 2020-05-19 10:29
I'm not sure @Schnodderbalken, sorry. I don't have a MacOS machine, so I'm not of much help. The stuff I know is only from user reports like yours. I wish I could be of more help.

**Comment by Schnodderbalken** [comment] 2020-05-19 10:43
Do you know if it's safe to uninstall the whole RubyGems package? Or does the system in any way depend on it being installed? I would like to reset the whole Gems package without having to completely reset my OS.

**Comment by deivid-rodriguez** [comment] 2020-05-19 11:03
I'm not sure what you mean. Tell me which command you intend to run and I can tell you my opinion on how safe it is.

**Comment by Schnodderbalken** [comment] 2020-05-19 13:13
I just thought it might help to somehow remove the RubyGem application along with all of its configuration (like linked libs) from the system and reinstalling it.
I am just trying to erase that part on my system that has a dependency on that outdated dylib.

However, I can't figure out how to do that. If i put in `which gem` it tells me this: 
```
gem () {
	\typeset result
	(
		\typeset rvmrc
		rvm_rvmrc_files=("/etc/rvmrc" "$HOME/.rvmrc") 
		if [[ -n "${rvm_prefix:-}" ]] && ! [[ "$HOME/.rvmrc" -ef "${rvm_prefix}/.rvmrc" ]]
		then
			rvm_rvmrc_files+=("${rvm_prefix}/.rvmrc") 
		fi
		for rvmrc in "${rvm_rvmrc_files[@]}"
		do
			[[ -s "${rvmrc}" ]] && source "${rvmrc}" || true
		done
		unset rvm_rvmrc_files
		command gem "$@"
	) || result=$? 
	hash -r
	return ${result:-0}
}
```

**Comment by deivid-rodriguez** [comment] 2020-05-19 13:19
That's interesting because you said you installed ruby via `homebrew` but that sounds like an `rvm`-installed `ruby`. So you can try removing `rvm` completety. I don't recall how you go about uninstalling `rvm` completely but you can probably find steps online.

**Comment by Schnodderbalken** [comment] 2020-05-19 13:22
Yes, I am also confused.
I managed to uninstall rvm. I also uninstalled ruby via homebrew. However, if I use
```
gem install xy
```
I still get the same feedback.

**Comment by deivid-rodriguez** [comment] 2020-05-19 13:24
So where does `gem which` shows now? Is it an actual file and not a bash function?

**Comment by deivid-rodriguez** [comment] 2020-05-19 13:25
If it still shows the function even when restarting your shell, that means there's still traces of `rvm` somewhere.

**Comment by Schnodderbalken** [comment] 2020-05-19 13:43
Now I am told
```
/usr/bin/gem
```
when I ask `which gem`

**Comment by deivid-rodriguez** [comment] 2020-05-19 14:04
Great. So perhaps you can try reinstalling `brew` ruby now?

**Comment by Schnodderbalken** [comment] 2020-05-19 15:04
After having installed ruby via homebrew `which gem` returns:
```
/usr/local/opt/ruby/bin/gem
```

however, this does not affect the above mentioned issue.
You're probably right and it may not be an issue of RubyGems. Anyways, I would really like to know where the dependency on this particular dynamic library comes from (if not from RubyGems). Also, why does `system_libffi_usable` throw a RuntimeError because `brew list` indeed shows me that libffi is installed.

**Comment by deivid-rodriguez** [comment] 2020-05-19 15:17
I made a google search for this and it pointed me here: https://github.com/NixOS/nix/issues/2244. It sounds like an OS issue? :/
