### ISSUE TITLE
Possible inconsistent pessimist versioning behaviour

### ISSUE THREAD

**Issue by mmontossi** [rubygems/rubygems#1304] opened 2015-07-04 00:48 UTC
This works fine:

```ruby
'>= 4.0.0', '< 4.3.0'
```

But this not:

```ruby
'>= 4.0.0', '~> 4.2.0'
```

After reading the documentation on http://guides.rubygems.org/patterns/#declaring_dependencies, makes me thing it should work, I'm wrong?

Thanks

**Comment by segiddins** [comment] 2015-07-04 02:35
What do you mean 'it doesn't work'? What behavior were you expecting to see, and what actually happened?

Those two sets of requirements are not equivalent -- the latter would just evaluate to `~> 4.2.0`

**Comment by mmontossi** [comment] 2015-07-04 13:58
Since you can do things like:

```ruby
'~> 4.2.0', '> 4.2.1'
```

(Versions 4.2.X starting at 4.2.1)

I thought was possible to define:

```ruby
'>= 4.0.0', '~> 4.2.0'
```

(Versions from 4.0.0 until 4.2.X)

Why in the last case everything gets overwritten to just ~> 4.2.0?

**Comment by indirect** [comment] 2015-07-04 15:36
The ~> 4.2.0 requirement requires _at least_ 4.2. Always. You can't turn that off by adding >= 4.0.0.

**Comment by duckinator** [comment] 2016-01-17 05:10
Versions which satisfy`~> 4.2.0` are a subset of versions which satisfy `>= 4.0.0`, so it by definition will not be different than `~> 4.2.0` on its own. Closing since this is behaving as intended.

**Closed by duckinator** 2016-01-17 05:10 UTC
Labels: question, triage
