### ISSUE TITLE
Can't add Rubygems as a rouces

### ISSUE THREAD

**Issue by grantkemp** [rubygems/rubygems#2346] opened 2018-07-06 12:24 UTC
I'm having a problem or would like to suggest a feature.

My current problem is I cannot add Rubgems as a source

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x ] The command line `gem`
  - [ ] Other

When I try add rubygems to sources I get this error: 
```gem sources -a https://rubygems.org/
Error fetching https://rubygems.org/:
	SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version (https://rubygems.org/specs.4.8.gz)```
I am able to connect to all other websites and add other sources - eg taobao


Here are my current environment details:

```
$ gem env version
2.0.14.1
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by colby-swandale** [comment] 2018-07-06 14:49
Marking as a duplicate of #2342 and many others about this issue.

**Closed by colby-swandale** 2018-07-06 14:49 UTC
Labels: status: triage

**Comment by grantkemp** [comment] 2018-07-06 15:37
@colby-swandale  / @bronzdoc  I don't think its the same issue -as the other ticket didn't resolve the issue. 
Surely this needs to be fixed if other people have the issue instead of just closing it?

**Comment by MSP-Greg** [comment] 2018-07-06 15:45
@grantkemp

As stated in #2342, TLSv1_2 needs to appear in:
```
ruby -ropenssl -e "puts OpenSSL::SSL::SSLContext::METHODS.grep(/.+\d$/).sort"
```

If not, the combination of your Ruby version & your OpenSSL version are too old to connect to RubyGems.org.
