### ISSUE TITLE
bundle config set path 'vendor/bundle' without global / local flag defaults to global

### ISSUE THREAD

**Issue by Juksefantomet** [rubygems/rubygems#4813] opened 2021-08-03 11:17 UTC
### Start blank project (example with bundle version 2.2.25)
`gem install bundler`
`bundle init`
`bundle install --path 'vendor/bundle'`

output:
````
output generated
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local path 'vendor/bundle'`, and stop using this flag
````

### Set bundle path without local or global flag
`bundle config set path 'vendor/bundle'`

### What were you expecting to happen?
I was expecting the command to default to local path

### What actually happened?
Global path was set

### Thoughts
Running that command often is a use case for local projects.

One does not often define a global path for gems.

`bundle config set path 'path/path'` without a flag has a potential for screwing up gem pathing for multiple projects if done without the flag by accident.

Defaulting to local flag and/or requiring the flag as a part of the command would better secure the outcome.

**Comment by deivid-rodriguez** [comment] 2021-08-03 11:39
Yes, I totally agree, we just need to make a decision for the transition, but I tend to believe it should be compatible enough to just do it. Closing as a duplicate of #3926.

**Closed by deivid-rodriguez** 2021-08-03 11:39 UTC
Labels: Bundler
