### ISSUE TITLE
URI::InvalidURIError: bad URI(is not URI?): homepage: http://dev.azure.com/saigkill/hoe-manns

### ISSUE THREAD

**Issue by saigkill** [rubygems/rubygems#2485] opened 2018-11-21 19:14 UTC
I'm having a problem or would like to suggest a feature.

My current problem is i can't build and deploy a gem to rubygems with the error above.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [X ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
C:\Users\Sasch\Development\Source\RubymineProjects\hoe-manns>gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.14.1
  - RUBY VERSION: 2.4.4 (2018-03-28 patchlevel 296) [x64-mingw32]
  - INSTALLATION DIRECTORY: C:/Ruby24-x64/lib/ruby/gems/2.4.0
  - USER INSTALLATION DIRECTORY: C:/Users/Sasch/.gem/ruby/2.4.0
  - RUBY EXECUTABLE: C:/Ruby24-x64/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/Ruby24-x64/bin
  - SPEC CACHE DIRECTORY: C:/Users/Sasch/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x64-mingw32
  - GEM PATHS:
     - C:/Ruby24-x64/lib/ruby/gems/2.4.0
     - C:/Users/Sasch/.gem/ruby/2.4.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\Program Files (x86)\Common Files\Oracle\Java\javapath
     - C:\Windows\System32
     - C:\Windows
     - C:\Windows\System32\wbem
     - C:\Windows\System32\WindowsPowerShell\v1.0\
     - C:\Windows\System32\OpenSSH\
     - C:\Program Files\dotnet\
     - C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
     - C:\Program Files\MiKTeX 2.9\miktex\bin\x64\
     - C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\
     - C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\
     - C:\Program Files\Microsoft SQL Server\140\Tools\Binn\
     - C:\Program Files\Microsoft SQL Server\140\DTS\Binn\
     - C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\
     - C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\
     - C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\
     - C:\Program Files (x86)\GnuPG\bin
     - C:\Program Files\Git\cmd
     - C:\Program Files (x86)\GtkSharp\2.12\bin
     - C:\Program Files\IDM Computer Solutions\UltraEdit
     - C:\WINDOWS\system32
     - C:\WINDOWS
     - C:\WINDOWS\System32\Wbem
     - C:\WINDOWS\System32\WindowsPowerShell\v1.0\
     - C:\WINDOWS\System32\OpenSSH\
     - C:\Program Files\nodejs\
     - C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\
     - C:\Program Files\Calibre2\
     - C:\Users\Sasch\AppData\Local\Programs\Python\Python37\Scripts\
     - C:\Users\Sasch\AppData\Local\Programs\Python\Python37\
     - C:\Ruby24-x64\bin
     - C:\Users\Sasch\AppData\Local\Microsoft\WindowsApps
     -
     - C:\Users\Sasch\AppData\Local\Programs\Microsoft VS Code\bin
     - C:\Users\Sasch\AppData\Roaming\npm
     - C:\Users\Sasch\.dotnet\tools
     - %USERPROFILE%\AppData\Local\Microsoft\WindowsApps

```

The Project files itself can accessed by: https://dev.azure.com/saigkill/_git/hoe-manns

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment] 2018-11-21 23:57
Please show how we can reproduce the error

**Comment by saigkill** [comment] 2018-11-22 07:05
In General it should come, if you check out https://saigkill@dev.azure.com/saigkill/hoe-manns/_git/hoe-manns and run `rake release VERSION=2.1.4`

**Comment by bronzdoc** [comment] 2018-11-22 14:03
can you paste the error when you execute that command please, thanks

**Comment by MSP-Greg** [comment] 2018-11-22 18:36
Is there a space at the end of "hoe-manns "?

**Comment by bronzdoc** [comment] 2018-11-22 18:41
in your `README.md`  remove the text `homepage:` from the line `homepage: http://dev.azure.com/saigkill/hoe-manns`

**Comment by saigkill** [comment] 2018-11-22 18:59
>           Is there a space at the end of "hoe-manns "?

There are two spaces, because of a line break. MD doesn't support `<br />`

**Comment by bronzdoc** [comment] 2018-11-22 19:00
Closing since this is not a Rubygems issue, Rubygems is behaving as expected `homepage: http://dev.azure.com/saigkill/hoe-manns` is not a valid URI

**Closed by bronzdoc** 2018-11-22 19:00 UTC
Labels: status: user feedback required

**Comment by saigkill** [comment] 2018-11-22 19:03
Why this isn't a valid URI? https://dev.azure.com/saigkill/hoe-manns works perfectly and the http one will redirected to the https.
Caused by:
URI::InvalidURIError: bad URI(is not URI?): codebase: https://dev.azure.com/saigkill/hoe-manns

**Comment by bronzdoc** [comment] 2018-11-22 19:21
Sorry it wasn't my intention to come as rude :)
> Why this isn't a valid URI? https://dev.azure.com/saigkill/hoe-manns 

that it is a valid uri, the problem is that you are passing `homepage: http://dev.azure.com/saigkill/hoe-manns` which it isn't

If i remove the `homepage:` part in `homepage: http://dev.azure.com/saigkill/hoe-manns`
in your `README.md` the issue is solved

If i run the following:
```
$ rake release

mkdir -p pkg
mkdir -p pkg/hoe-manns-2.1.4
rm -f pkg/hoe-manns-2.1.4/CODE_OF_CONDUCT.md
ln CODE_OF_CONDUCT.md pkg/hoe-manns-2.1.4/CODE_OF_CONDUCT.md
rm -f pkg/hoe-manns-2.1.4/CONTRIBUTING.md
ln CONTRIBUTING.md pkg/hoe-manns-2.1.4/CONTRIBUTING.md
rm -f pkg/hoe-manns-2.1.4/Gemfile
ln Gemfile pkg/hoe-manns-2.1.4/Gemfile
rm -f pkg/hoe-manns-2.1.4/Gemfile.lock
ln Gemfile.lock pkg/hoe-manns-2.1.4/Gemfile.lock
rm -f pkg/hoe-manns-2.1.4/History.rdoc
ln History.rdoc pkg/hoe-manns-2.1.4/History.rdoc
rm -f pkg/hoe-manns-2.1.4/LICENSE.md
ln LICENSE.md pkg/hoe-manns-2.1.4/LICENSE.md
rm -f pkg/hoe-manns-2.1.4/MAINTENANCE.md
ln MAINTENANCE.md pkg/hoe-manns-2.1.4/MAINTENANCE.md
rm -f pkg/hoe-manns-2.1.4/Manifest.txt
ln Manifest.txt pkg/hoe-manns-2.1.4/Manifest.txt
rm -f pkg/hoe-manns-2.1.4/README.md
ln README.md pkg/hoe-manns-2.1.4/README.md
rm -f pkg/hoe-manns-2.1.4/Rakefile
ln Rakefile pkg/hoe-manns-2.1.4/Rakefile
mkdir -p pkg/hoe-manns-2.1.4/lib/hoe
rm -f pkg/hoe-manns-2.1.4/lib/hoe/manns-methods.rb
ln lib/hoe/manns-methods.rb pkg/hoe-manns-2.1.4/lib/hoe/manns-methods.rb
rm -f pkg/hoe-manns-2.1.4/lib/hoe/manns.rb
ln lib/hoe/manns.rb pkg/hoe-manns-2.1.4/lib/hoe/manns.rb
mkdir -p pkg/hoe-manns-2.1.4/spec
rm -f pkg/hoe-manns-2.1.4/spec/manns_spec.rb
ln spec/manns_spec.rb pkg/hoe-manns-2.1.4/spec/manns_spec.rb
rm -f pkg/hoe-manns-2.1.4/spec/spec_helper.rb
ln spec/spec_helper.rb pkg/hoe-manns-2.1.4/spec/spec_helper.rb
cd pkg/hoe-manns-2.1.4
  Successfully built RubyGem
  Name: hoe-manns
  Version: 2.1.4
  File: hoe-manns-2.1.4.gem
cd -
Must supply VERSION=x.y.z
```

It seems that in your release process the `README.md` file is being read to form a gem specification, but that is out of the scope of Rubygems

**Comment by saigkill** [comment] 2018-11-22 19:51
Thanks for answering :-)
I tried it also without any comment before the url. But i'm getting again:

> Caused by:
URI::InvalidURIError: bad URI(is not URI?): https://dev.azure.com/saigkill/hoe-manns

What can i do to localize the error?

**Comment by bronzdoc** [comment] 2018-11-22 19:55
I get that error if i there is a whitespace before the url, do you have a whispace before the url?

**Comment by saigkill** [comment] 2018-11-22 20:10
No. That is the last Version, what i used: https://paste.ubuntu.com/p/tftG27CMmY/

**Comment by bronzdoc** [comment] 2018-11-22 20:18
Sorry but i can't reproduce your issue, for me if i remove the `homepage:` part "it works". Try reporting this to https://github.com/seattlerb/hoe
