### ISSUE TITLE
Network problems with gems fetching

### ISSUE THREAD

**Issue by AlexWayfer** [rubygems/rubygems#2253] opened 2018-03-28 10:22 UTC
I'm having a problem.

My current problem is:

```
$ gem i browser --verbose
ERROR:  Could not find a valid gem 'browser' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - timed out (https://api.rubygems.org/specs.4.8.gz)

$ gem update --system --verbose
ERROR:  While executing gem ... (Gem::RemoteFetcher::UnknownHostError)
    timed out (https://api.rubygems.org/specs.4.8.gz)

$ curl -O https://rubygems.org/gems/browser-2.5.3.gem
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 46592  100 46592    0     0  74428      0 --:--:-- --:--:-- --:--:-- 74428
```

This issue is related to:

  - [X] Network problems
  - [X] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.7.3
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by duckinator** [comment] 2018-04-12 22:00
hi,

If you're still having this issue, can you provide the output of running this command?:

    curl -vO https://api.rubygems.org/specs.4.8.gz

As well as this command?:

    ruby -r rubygems/remote_fetcher -e 'puts(Gem::RemoteFetcher.new.fetch_path("https://api.rubygems.org/specs.4.8.gz") ? "success" : "failure")'

**Comment by WedgeSparda** [comment] 2018-04-13 08:31
I'm having the same problem. Here's my output for those commands

```
curl -vO https://api.rubygems.org/specs.4.8.gz

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 2a04:4e42:600::514...
* TCP_NODELAY set
*   Trying 151.101.194.2...
* TCP_NODELAY set
* Connected to api.rubygems.org (151.101.194.2) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [102 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [5039 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Fastly, Inc.; CN=f2.shared.global.fastly.net
*  start date: Mar 26 22:40:12 2018 GMT
*  expire date: Oct  6 14:45:12 2018 GMT
*  subjectAltName: host "api.rubygems.org" matched cert's "*.rubygems.org"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign CloudSSL CA - SHA256 - G3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7faf32806000)
> GET /specs.4.8.gz HTTP/2
> Host: api.rubygems.org
> User-Agent: curl/7.54.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< x-amz-id-2: dmdpMm1Zh7GoRcd4M+yenfHgEb2+GBEt3YWPqx9lWcuTxWu8bl+jVYefWSmPRGezKBGjyeExqcA=
< x-amz-request-id: 3CEED0923A9CC5FE
< x-amz-replication-status: COMPLETED
< last-modified: Fri, 13 Apr 2018 08:25:30 GMT
< etag: "1aa92c124ad6e4d87316ec18772ca172"
< cache-control: max-age=31536000
< x-amz-meta-surrogate-key: full-index
< x-amz-version-id: 2Oe30418VBqqyOzIjSENhDzSF_CXwQpr
< via: 1.1 varnish
< content-type: application/octet-stream
< x-backend: F_S3 52.218.212.73:443, fastlyshield--shield_ssl_cache_sea1037_SEA 157.52.67.37:443
< accept-ranges: bytes
< date: Fri, 13 Apr 2018 08:28:47 GMT
< via: 1.1 varnish
< age: 194
< x-served-by: cache-sea1037-SEA, cache-cdg8726-CDG
< x-cache: HIT, HIT
< x-cache-hits: 1, 2
< x-timer: S1523608128.514265,VS0,VE0
< vary: Fastly-SSL
< server: RubyGems.org
< content-length: 3541980
< 
{ [2213 bytes data]
100 3458k  100 3458k    0     0  2569k      0  0:00:01  0:00:01 --:--:-- 2569k
* Connection #0 to host api.rubygems.org left intact
```

And

```
ruby -r rubygems/remote_fetcher -e 'puts(Gem::RemoteFetcher.new.fetch_path("https://api.rubygems.org/specs.4.8.gz") ? "success" : "failure")'

/Users/Wedge/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/remote_fetcher.rb:306:in `rescue in fetch_path': timed out (https://api.rubygems.org/specs.4.8.gz) (Gem::RemoteFetcher::UnknownHostError)
	from /Users/Wedge/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/remote_fetcher.rb:284:in `fetch_path'
	from -e:1:in `<main>'
```

**Comment by AlexWayfer** [comment] 2018-04-13 08:35
> If you're still having this issue

No, I no longer have this problem:

```
$ gem i browser --verbose
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=browser
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.api.rubygems.org
GET https://api.rubygems.org/quick/Marshal.4.8/browser-2.5.3.gemspec.rz
200 OK
...
```

**Comment by WedgeSparda** [comment] 2018-04-13 08:38
@AlexTalker Did you do something to fix your problem?

**Comment by AlexWayfer** [comment] 2018-04-13 08:53
> @AlexTalker Did you do something to fix your problem?

Sorry, I don't remember. I think no…

Probably, rebooted my Internet-connection (router, computer, etc.).

**Comment by WedgeSparda** [comment] 2018-04-13 09:18
This is really weird. I can't install anything using RubyGems, always getting a timeout. But If I connect remotely to another computer in another network it works. How can I get more info about this weird problem?

**Comment by WedgeSparda** [comment] 2018-04-13 10:01
Making more tests. Pings to rubygems.org and api.rubygems.org work perfectly. 
Accesing to https://api.rubygems.org/specs.4.8.gz via web browser works too.
It seems that only happens from my terminal. I'm using macOS High Sierra 10.13.4.

Running `gem i fastlane --verbose` returns a timeout.

```
ERROR:  Could not find a valid gem 'fastlane' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - timed out (https://api.rubygems.org/specs.4.8.gz)
```

Anyone can help me? I'm unable of installing fastlane because of this and need to run a deploy.

Thanks.

**Comment by AlexWayfer** [comment] 2018-04-13 10:04
> Anyone can help me?

Did you try to reboot your computer and router?

**Comment by WedgeSparda** [comment] 2018-04-13 10:05
@AlexWayfer Yes. No luck.

**Comment by AlexWayfer** [comment] 2018-04-13 10:09
> But If I connect remotely to another computer in another network it works.

Maybe you can use some proxy or VPN temporarily, while problems are here?

**Comment by WedgeSparda** [comment] 2018-04-13 11:40
So I was able to run the installation using tethering with my phone. Any idea why a specific connection is giving error? Any port that I should open on my router?

**Comment by AlexWayfer** [comment] 2018-04-13 11:42
@WedgeSparda You can try `traceroute`, I guess, and paste its output here.

**Comment by WedgeSparda** [comment] 2018-04-13 11:45
@AlexWayfer Sorry, I'm not familiar with traceroute, which options should I run it with? 

```
Version 1.4a12+Darwin
Usage: traceroute [-adDeFInrSvx] [-A as_server] [-f first_ttl] [-g gateway] [-i iface]
	[-M first_ttl] [-m max_ttl] [-p port] [-P proto] [-q nqueries] [-s src_addr]
	[-t tos] [-w waittime] [-z pausemsecs] host [packetlen]
```

**Comment by AlexWayfer** [comment] 2018-04-13 11:51
@WedgeSparda Without any option, I think.

**Comment by WedgeSparda** [comment] 2018-04-13 11:53
@AlexWayfer If I run just traceroute, that's what I'm getting

```
Version 1.4a12+Darwin
Usage: traceroute [-adDeFInrSvx] [-A as_server] [-f first_ttl] [-g gateway] [-i iface]
	[-M first_ttl] [-m max_ttl] [-p port] [-P proto] [-q nqueries] [-s src_addr]
	[-t tos] [-w waittime] [-z pausemsecs] host [packetlen]
```

**Comment by AlexWayfer** [comment] 2018-04-13 11:54
@WedgeSparda Look at `host` — this is argument for command. I wrote RubyGems hosts above.

**Comment by WedgeSparda** [comment] 2018-04-13 11:58
@AlexWayfer Sorry, I missed that. This is what I'm getting:

```
traceroute: Warning: rubygems.org has multiple addresses; using 151.101.66.2
traceroute to rubygems.org (151.101.66.2), 64 hops max, 52 byte packets
 1  192.168.1.1 (192.168.1.1)  1.390 ms  0.565 ms  0.421 ms
 2  109.230.217.254 (109.230.217.254)  2.840 ms  3.160 ms  2.568 ms
 3  10.3.1.1 (10.3.1.1)  1.871 ms  2.036 ms  1.960 ms
 4  10.255.2.4 (10.255.2.4)  8.921 ms  9.028 ms  9.024 ms
 5  213.27.208.165 (213.27.208.165)  9.157 ms  8.881 ms  8.734 ms
 6  212.74.70.51 (212.74.70.51)  31.261 ms  30.440 ms  31.703 ms
 7  212.74.73.241 (212.74.73.241)  29.560 ms
    te0-0-0-0-pr2.par.router.colt.net (212.74.88.161)  30.952 ms
    212.74.70.51 (212.74.70.51)  30.595 ms
 8  * * *
 9  * * *
10  * * *
11  * *
```
It just keeps adding lines like the last ones and nothing else happens.

**Comment by AlexWayfer** [comment] 2018-04-13 12:00
@duckinator, is it helpful?

**Comment by WedgeSparda** [comment] 2018-04-13 15:12
@AlexWayfer I'm using the Google DNS (8.8.8.8 and 8.8.4.8). Maybe the problem is with them?

**Comment by AlexWayfer** [comment] 2018-04-13 15:16
@WedgeSparda maybe, I don't know. You can change this and write here the results.

**Comment by bronzdoc** [comment] 2018-04-13 17:10
I'm going to close this since the original problem was fixed and it seems the problem is out of the scope of rubygems itself

**Closed by bronzdoc** 2018-04-13 17:10 UTC
Labels: status: triage

**Comment by rrcobb** [comment] 2018-10-23 06:31
In case anyone else ends up running into this one - I was pretty stumped for a while. Could install fine from a hotspot, but wifi ended up with 

```
$ gem install bundler
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - timed out (https://api.rubygems.org/specs.4.8.gz)
``` 

Eventual fix and explanation came from 
- https://stackoverflow.com/questions/49800432/gem-cannot-access-rubygems-org 
- http://help.rubygems.org/discussions/problems/31074-timeout-error

Rubygems.org seems like it filters some IPv6 requests from certain domains - not quite sure why. 

You can see for yourself with
```
$ # ipv4 works fine
$ curl -v --head https://api.rubygems.org

$ # ipv6 broken
$ curl -6 -v --head https://api.rubygems.org
```

or more carefully, 
```
$ dig AAAA api.rubygems.org +short
rubygems.org.
2a04:4e42:400::70
2a04:4e42:600::70
2a04:4e42:200::70
2a04:4e42::70
$ nmap -p 443 -6 -Pn -v -oG - 2a04:4e42:400::70 2a04:4e42:600::70 2a04:4e42:200::70 2a04:4e42::70
# Nmap 7.70 scan initiated Tue Oct 23 02:22:41 2018 as: nmap -p 443 -6 -Pn -v -oG - 2a04:4e42:400::70 2a04:4e42:600::70 2a04:4e42:200::70 2a04:4e42::70
# Ports scanned: TCP(1;443) UDP(0;) SCTP(0;) PROTOCOLS(0;)
Host: 2a04:4e42:400::70 ()	Status: Up
Host: 2a04:4e42:400::70 ()	Ports: 443/filtered/tcp//https///
Host: 2a04:4e42:600::70 ()	Status: Up
Host: 2a04:4e42:600::70 ()	Ports: 443/filtered/tcp//https///
Host: 2a04:4e42:200::70 ()	Status: Up
Host: 2a04:4e42:200::70 ()	Ports: 443/filtered/tcp//https///
Host: 2a04:4e42::70 ()	Status: Up
Host: 2a04:4e42::70 ()	Ports: 443/filtered/tcp//https///
# Nmap done at Tue Oct 23 02:22:54 2018 -- 4 IP addresses (4 hosts up) scanned in 13.25 seconds
```

compared to ipv4
```
$ dig api.rubygems.org +short
rubygems.org.
151.101.64.70
151.101.0.70
151.101.192.70
151.101.128.70
$ nmap -p 443 -Pn -v -oG - 151.101.64.70 151.101.0.70 151.101.192.70 151.101.128.70
# Nmap 7.70 scan initiated Tue Oct 23 02:25:45 2018 as: nmap -p 443 -Pn -v -oG - 151.101.64.70 151.101.0.70 151.101.192.70 151.101.128.70
# Ports scanned: TCP(1;443) UDP(0;) SCTP(0;) PROTOCOLS(0;)
Host: 151.101.64.70 ()	Status: Up
Host: 151.101.64.70 ()	Ports: 443/open/tcp//https///
Host: 151.101.0.70 ()	Status: Up
Host: 151.101.0.70 ()	Ports: 443/open/tcp//https///
Host: 151.101.192.70 ()	Status: Up
Host: 151.101.192.70 ()	Ports: 443/open/tcp//https///
Host: 151.101.128.70 ()	Status: Up
Host: 151.101.128.70 ()	Ports: 443/open/tcp//https///
# Nmap done at Tue Oct 23 02:25:56 2018 -- 4 IP addresses (4 hosts up) scanned in 11.10 seconds
```

(notice that these results for IPv4 addresses say 'open' instead of 'filtered' for IPv6)

The fix as a user is to change your network settings so that you make your requests over IPv4. The stackoverflow post above has more details, but for me, it's 

> System Preferences > Network > Advanced > TCP/IP > Configure IPv6: Link-local only

For rubygems, I'm not sure what the long-term fix is, except to dig into why some IPv6 requests are getting filtered.

**Comment by georgeu2000** [comment] 2019-01-23 21:14
I ran into this exact issue today. After using rubygems for 6 years it was a new issue for me and a bit of a surprise. Thanks @rrcobb.

**Comment by jlcarruda** [comment] 2019-02-27 20:07
I was stuck on this error for a week now. The workaround for me was to change my connection from a Wireless connection into a wired one. The strangest thing is that I've always used Wireless connection and this error never showed up. 
Thanks @rrcobb to lightened those tech infos.

**Comment by sankalpanand** [comment] 2019-04-05 07:23
As of April 5th, even the IPv4 is also getting filtered-

```
$ dig api.rubygems.org +short
rubygems.org.
151.101.0.70
151.101.192.70
151.101.64.70
151.101.128.70

$ nmap -p 443 -Pn -v -oG - 151.101.0.70 151.101.192.70 151.101.64.70 151.101.128.70
# Nmap 7.70 scan initiated Fri Apr  5 00:21:42 2019 as: nmap -p 443 -Pn -v -oG - 151.101.0.70 151.101.192.70 151.101.64.70 151.101.128.70
# Ports scanned: TCP(1;443) UDP(0;) SCTP(0;) PROTOCOLS(0;)
Host: 151.101.0.70 ()	Status: Up
Host: 151.101.0.70 ()	Ports: 443/filtered/tcp//https///
Host: 151.101.192.70 ()	Status: Up
Host: 151.101.192.70 ()	Ports: 443/filtered/tcp//https///
Host: 151.101.64.70 ()	Status: Up
Host: 151.101.64.70 ()	Ports: 443/filtered/tcp//https///
Host: 151.101.128.70 ()	Status: Up
Host: 151.101.128.70 ()	Ports: 443/filtered/tcp//https///
```

**Comment by jalleyne** [comment] 2019-07-19 13:33
+1 that @rrcobb's solution switching to ip4 for wan traffic still works.

**Comment by tueksta** [comment] 2019-09-28 21:26
why is nobody at rubygems.org looking into their filters? This exists for years now, and still no fix. It looks like Germany is mostly affected by this?

**Comment by indirect** [comment] 2019-09-28 21:52
@tueksta because the problem is with your ISP or their upstream providers. RubyGems.org is perfectly happy to accept IPv6 traffic, and I re-test on consumer and business IPv6 connections every time someone reports it isn’t working. It’s always working.

**Comment by undecided** [comment] 2019-10-03 11:36
HI @indirect - I also have this problem (United Kingdom, ISP = Sky), and it seems to be getting more consistent. It doesn't affect the website RubyGems.org - only bundler. 

If I do the dance:
```
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
```

it fixes itself, straight away, 100% of the time. Have just switched back and bundler still works - possibly because it's cached the ipv4 address. `curl -6 --head https://api.rubygems.org` throws the error, regardless of the above sysctl changes.

As one affected, if there's anything I can do to help debug this, please let me know. I don't personally mind the workaround now that I know about it, but it'll be enough of a stumper for a newbie to walk away.

**Comment by duckinator** [comment] 2019-10-03 12:32
For future reference, for folks who stumble across this issue:

1. If you're on an operating system with the `curl` program available, compare `curl -4 --head https://api.rubygems.org` and `curl -6 --head https://api.rubygems.org` &mdash; if only the latter fails, it's specific to IPv6.
2. If disabling IPv6 fixes it, it's specific to IPv6
3. If the problem is specific to IPv6, it's _probably_ your ISP.

ISPs providing IPv6 addresses is a requirement for people access the entirety of the internet (as opposed to only part of it), at this point. Unfortunately some ISPs are bad at this.

**Comment by alexventuraio** [comment] 2020-06-25 04:21
If the problem is due to IPv6 on MacOS X, then you can also **_enable/disable_** it from the terminal using the following commands depending on the network interface you are using **WiFi** or **Ethernet(Cable)**:
```sh
sudo networksetup -setv6off Wi-Fi
sudo networksetup -setv6automatic Wi-Fi

sudo networksetup -setv6off Ethernet
sudo networksetup -setv6automatic Ethernet
```

**Comment by sonalkr132** [comment] 2020-09-06 10:15
Hi, we are trying to verify the rubygems.org IPv6 connection issue at Fastly's (our CDN provider) end.
It would be very helpful if anyone here who has this issue can confirm that `wget -6 www.google.com` works but **`wget -6 rubygems.org` timesout**. Please [open a support ticket at our help site](https://help.rubygems.org/discussion/new) if you have this specific issue.

**Comment by AlexWayfer** [comment] 2020-09-06 11:20
> Please [open a support ticket at our help site](https://help.rubygems.org/discussion/new) if you have this specific issue.

<details><summary>A little off-topic, sorry.</summary>

I've created a discussion there about another problem, question: https://help.rubygems.org/discussions/questions/31631-i-want-to-get-multitool-name?unresolve=true

As you can see, it was created at Oct 28, 2019. And there is still no any attention, no responses. It even looks not-published at all: I don't see it in search neither in my profile:

![image](https://user-images.githubusercontent.com/6510020/92324569-a504f380-f04b-11ea-98b7-89e5b806a91b.png)

![image](https://user-images.githubusercontent.com/6510020/92324572-ab936b00-f04b-11ea-8d4e-7cfd84d93f26.png)

So… this approach, suggested by you, looks non-working (for me).
</details>

**Comment by sonalkr132** [comment] 2020-09-06 11:46
sorry, your ticket was marked spam. tender sometimes messes this up, unfortunately, it what we are using at the moment. we will migrate to zendesk soon.

**Comment by samhrncir** [comment] 2020-12-02 19:56
Was having this same issue today.

**Solution for me**:



> In case anyone else ends up running into this one - I was pretty stumped for a while. Could install fine from a hotspot, but wifi ended up with
> 
> ```
> $ gem install bundler
> ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
>           Unable to download data from https://rubygems.org/ - timed out (https://api.rubygems.org/specs.4.8.gz)
> ```
> 
> Eventual fix and explanation came from
> 
> * https://stackoverflow.com/questions/49800432/gem-cannot-access-rubygems-org
> * http://help.rubygems.org/discussions/problems/31074-timeout-error
> 
> Rubygems.org seems like it filters some IPv6 requests from certain domains - not quite sure why.
> 
> You can see for yourself with
> 
> ```
> $ # ipv4 works fine
> $ curl -v --head https://api.rubygems.org
> 
> $ # ipv6 broken
> $ curl -6 -v --head https://api.rubygems.org
> ```
> 
> or more carefully,
> 
> ```
> $ dig AAAA api.rubygems.org +short
> rubygems.org.
> 2a04:4e42:400::70
> 2a04:4e42:600::70
> 2a04:4e42:200::70
> 2a04:4e42::70
> $ nmap -p 443 -6 -Pn -v -oG - 2a04:4e42:400::70 2a04:4e42:600::70 2a04:4e42:200::70 2a04:4e42::70
> # Nmap 7.70 scan initiated Tue Oct 23 02:22:41 2018 as: nmap -p 443 -6 -Pn -v -oG - 2a04:4e42:400::70 2a04:4e42:600::70 2a04:4e42:200::70 2a04:4e42::70
> # Ports scanned: TCP(1;443) UDP(0;) SCTP(0;) PROTOCOLS(0;)
> Host: 2a04:4e42:400::70 ()	Status: Up
> Host: 2a04:4e42:400::70 ()	Ports: 443/filtered/tcp//https///
> Host: 2a04:4e42:600::70 ()	Status: Up
> Host: 2a04:4e42:600::70 ()	Ports: 443/filtered/tcp//https///
> Host: 2a04:4e42:200::70 ()	Status: Up
> Host: 2a04:4e42:200::70 ()	Ports: 443/filtered/tcp//https///
> Host: 2a04:4e42::70 ()	Status: Up
> Host: 2a04:4e42::70 ()	Ports: 443/filtered/tcp//https///
> # Nmap done at Tue Oct 23 02:22:54 2018 -- 4 IP addresses (4 hosts up) scanned in 13.25 seconds
> ```
> 
> compared to ipv4
> 
> ```
> $ dig api.rubygems.org +short
> rubygems.org.
> 151.101.64.70
> 151.101.0.70
> 151.101.192.70
> 151.101.128.70
> $ nmap -p 443 -Pn -v -oG - 151.101.64.70 151.101.0.70 151.101.192.70 151.101.128.70
> # Nmap 7.70 scan initiated Tue Oct 23 02:25:45 2018 as: nmap -p 443 -Pn -v -oG - 151.101.64.70 151.101.0.70 151.101.192.70 151.101.128.70
> # Ports scanned: TCP(1;443) UDP(0;) SCTP(0;) PROTOCOLS(0;)
> Host: 151.101.64.70 ()	Status: Up
> Host: 151.101.64.70 ()	Ports: 443/open/tcp//https///
> Host: 151.101.0.70 ()	Status: Up
> Host: 151.101.0.70 ()	Ports: 443/open/tcp//https///
> Host: 151.101.192.70 ()	Status: Up
> Host: 151.101.192.70 ()	Ports: 443/open/tcp//https///
> Host: 151.101.128.70 ()	Status: Up
> Host: 151.101.128.70 ()	Ports: 443/open/tcp//https///
> # Nmap done at Tue Oct 23 02:25:56 2018 -- 4 IP addresses (4 hosts up) scanned in 11.10 seconds
> ```
> 
> (notice that these results for IPv4 addresses say 'open' instead of 'filtered' for IPv6)
> 
> The fix as a user is to change your network settings so that you make your requests over IPv4. The stackoverflow post above has more details, but for me, it's
> 
> > System Preferences > Network > Advanced > TCP/IP > Configure IPv6: Link-local only
> 
> For rubygems, I'm not sure what the long-term fix is, except to dig into why some IPv6 requests are getting filtered.

**Comment by Roald87** [comment] 2021-01-17 11:21
On Windows 10 I disabled Ipv6 via (translated from Dutch, so menus might be called differently):

1. Go to **Control Panel > Network and Internet > Network connections**
2. Select the network connection you're currently using
3. Right click on it and choose **Properties**
4. Remove check mark for Internet Protocol version 6 (TCP/IPv6)
5. Click OK
6. Run your gem command again

**Comment by deivid-rodriguez** [comment] 2021-01-18 10:04
Hi @Roald87, thanks for reporting your findings! So, if I understand correctly, you're able to reliably reproduce this problem by going to your network configuration and checking the box for IPv6 again, correct? If this is the case, would you be willing to help us testing out some potential fixes?

**Comment by Roald87** [comment] 2021-01-27 21:16
I just enabled IPv6 again and `gem install bundler` worked without issues. Maybe it cached the IPv4 address somewhere?

**Comment by deivid-rodriguez** [comment] 2021-01-27 21:24
I don't know, maybe. Have You tried turning it off and on again? :sweat_smile:

This issue is hard to repro :( Thanks for trying anyways!

**Comment by WEBTECHCOMPANY** [comment] 2024-06-25 01:13
> Se o problema for devido ao IPv6 no MacOS X, você também pode **_ativá-lo/desativá-_** lo no terminal usando os seguintes comandos, dependendo da interface de rede que você está usando **WiFi** ou **Ethernet (cabo)** :
> 
> ```shell
> sudo networksetup -setv6off Wi-Fi
> sudo networksetup -setv6automatic Wi-Fi
> 
> sudo networksetup -setv6off Ethernet
> sudo networksetup -setv6automatic Ethernet
> ```

Nem todo heroi usa capa

**Comment by candiepih** [comment] 2024-08-20 11:00
I had this issue. Looks like IP6 was been preferred compared to IP4. Instead, I had to make IP4 the preferred option and it worked. Details on how to set preferred option  [here](https://weblog.lkiesow.de/20220311-make-linux-prefer-ipv4.html#:~:text=IPv4%20is%20actually%20an%20embedded,and%20the%20IPv4%20address%20192.168.)

**Comment by deivid-rodriguez** [comment] 2024-08-20 17:20
For what it's worth, a Happy Eyeballs implementation landed in Ruby [recently](https://github.com/ruby/ruby/pull/9374), so this should no longer be an issue in Ruby 3.4.

**Comment by weignerg** [comment] 2024-12-05 15:51
I tried in a docker image with this.

https://github.com/docker-library/ruby/blob/f268d3972ab3d0f8c8f6b546be8f0bb613a9dfd9/3.4-rc/alpine3.19/Dockerfile

The command `bundle install` fails when using my own self signed cert over my own networks vpn.

ca-certificate and root certs are installed in the container

Many of the fetches for gems succeed, but eventually one of them attempts to use ipv6 in stead of ipv4 and it fails.

curl to index.rubygems.org returns 301
