### ISSUE TITLE
`system bundle` works incorrect after `Dir.chdir`

### ISSUE THREAD

**Issue by AlexWayfer** [rubygems/rubygems#6181] opened 2022-12-23 00:02 UTC
### Describe the problem as clearly as you can

I have the tests. They worked, as I remember. Now they're passing, although they should not.

Example of PR: https://github.com/AlexWayfer/gem_template/pull/31

Root Bundler has been updated to the 1.41 version.

The template's one still has `~> 1.39.0`.

And `spec/generated_gem_spec.rb` has `describe 'outdated Ruby gems'` with `system 'bundle outdated'`.

But it returns `true`.

### Post steps to reproduce the problem

1. `Dir.chdir` into a sub-directory (`before` RSpec's hook?)
2. `system 'bundle outdated'` or `list` (`subject` RSpecs's?)
3. Get the result including parent directory.

### What were you expecting to happen?

`system 'pwd'`, `Dir.pwd`, `cat '*.gemspec'` return correct results. I'm inside the sub-directory. I want `bundle outdated` returns `false` (and the list of outdated).

### What actually happened?

`bundle`'s sub-commands return results including parent directory. 

`Bundler.with_unbundled_env` can be work-around, but I don't understand why it doesn't work correctly out-of-the-box.

### If not included with the output of your command, run `bundle env` and paste the output below

(you have `h2` tags for the content under `h3`, did you know?)

## Environment

```
Bundler       2.3.26
  Platforms   ruby, x86_64-linux
Ruby          3.1.3p185 (2022-11-24 revision 1a6b16756e0ba6b95ab71a441357ed5484e33498) [x86_64-linux]
  Full Path   /home/alex/.rbenv/versions/3.1.3/bin/ruby
  Config Dir  /home/alex/.rbenv/versions/3.1.3/etc
RubyGems      3.3.26
  Gem Home    /home/alex/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0
  Gem Path    /home/alex/.gem/ruby/3.1.0:/home/alex/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0
  User Home   /home/alex
  User Path   /home/alex/.gem/ruby/3.1.0
  Bin Dir     /home/alex/.rbenv/versions/3.1.3/bin
Tools         
  Git         2.39.0
  RVM         not installed
  rbenv       rbenv 1.2.0
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-11-17
Git SHA           23ec5b8501
Released Version  true
```

## Bundler settings

```
bin_path
  Set via BUNDLE_BIN_PATH: "/home/alex/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/exe/bundle"
gemfile
  Set via BUNDLE_GEMFILE: "/home/alex/Projects/ruby/gem_template/Gemfile"
```

### ../Gemfile

```ruby
# frozen_string_literal: true

source 'https://rubygems.org'

gem 'gem_generator', '~> 0.4.0'

gem 'pry-byebug', '~> 3.9'

group :test do
	gem 'ffaker', '~> 2.20'
	gem 'rspec', '~> 3.9'
end

group :lint do
	gem 'bundler-audit', '~> 0.9.0'

	gem 'rubocop', '~> 1.41.0'
	gem 'rubocop-performance', '~> 1.0'
	gem 'rubocop-rspec', '~> 2.0'
end
```

### ../Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
=> true
```
    alt_memery (2.1.0)
      module_methods (~> 0.1.0)
      ruby2_keywords (~> 0.0.2)
    ast (2.4.2)
    bundler-audit (0.9.1)
      bundler (>= 1.2.0, < 3)
      thor (~> 1.0)
    byebug (11.1.3)
    clamp (1.3.2)
    coderay (1.1.3)
    diff-lcs (1.5.0)
    ffaker (2.21.0)
    gem_generator (0.4.0)
      bundler (~> 2.0)
      gorilla_patch (~> 5.0)
      project_generator (~> 0.3.0)
    gorilla_patch (5.0.1)
    json (2.6.3)
    method_source (1.0.0)
    module_methods (0.1.0)
    parallel (1.22.1)
    parser (3.1.3.0)
      ast (~> 2.4.1)
    project_generator (0.3.0)
      alt_memery (~> 2.0)
      bundler (~> 2.0)
      clamp (~> 1.3)
      gorilla_patch (~> 5.0)
    pry (0.14.1)
      coderay (~> 1.1)
      method_source (~> 1.0)
    pry-byebug (3.10.1)
      byebug (~> 11.0)
      pry (>= 0.13, < 0.15)
    rainbow (3.1.1)
    regexp_parser (2.6.1)
    rexml (3.2.5)
    rspec (3.12.0)
      rspec-core (~> 3.12.0)
      rspec-expectations (~> 3.12.0)
      rspec-mocks (~> 3.12.0)
    rspec-core (3.12.0)
      rspec-support (~> 3.12.0)
    rspec-expectations (3.12.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.12.0)
    rspec-mocks (3.12.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.12.0)
    rspec-support (3.12.0)
    rubocop (1.41.1)
      json (~> 2.3)
      parallel (~> 1.10)
      parser (>= 3.1.2.1)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml (>= 3.2.5, < 4.0)
      rubocop-ast (>= 1.23.0, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 1.4.0, < 3.0)
    rubocop-ast (1.24.0)
      parser (>= 3.1.1.0)
    rubocop-performance (1.15.1)
      rubocop (>= 1.7.0, < 2.0)
      rubocop-ast (>= 0.4.0)
    rubocop-rspec (2.16.0)
      rubocop (~> 1.33)
    ruby-progressbar (1.11.0)
    ruby2_keywords (0.0.5)
    thor (1.2.1)
    unicode-display_width (2.3.0)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  bundler-audit (~> 0.9.0)
  ffaker (~> 2.20)
  gem_generator (~> 0.4.0)
  pry-byebug (~> 3.9)
  rspec (~> 3.9)
  rubocop (~> 1.41.0)
  rubocop-performance (~> 1.0)
  rubocop-rspec (~> 2.0)

BUNDLED WITH
   2.3.26
```

**Comment by deivid-rodriguez** [comment] 2022-12-23 00:29
I'm guessing your specs run in the Bundler environment of root directory. In that context, any subprocess created inherits that Bundler environment, no matter where the process starts. If you want to reset the Bundler environment so that the process works as if you started it from the command line in an unbundled environment, you need `Bundler.with_unbundled_env`.

I agree that not sticking the original environment into subprocesses is probably how it should work by default, but that ship sailed a long time ago. I believe it's too breaking to change the behavior now.

**Comment by AlexWayfer** [comment] 2023-01-09 22:44
The behavior already has changed as I monitor. I've setup the tests/CI and it worked correctly, but now… as you describe. Probably mine benefit was `bundler`'s error. :sweat_smile:

You can close this issue if you're sure the Bunlder works as intended. I can live with the `Bundler.with_unbundled_env`, although it's weird and not intuitive.

**Comment by deivid-rodriguez** [comment] 2023-01-10 11:40
I don't recall any recent changes around this? Can you provide detail about which version changed the behavior?

**Comment by AlexWayfer** [comment] 2023-01-10 12:40
> I don't recall any recent changes around this? Can you provide detail about which version changed the behavior?

Sorry, there was a pending test because of outdated `pry-byebug`, some mess with Depfu bot after.

So I can't now surely say it worked as I expected whenever.

**Comment by deivid-rodriguez** [comment] 2023-03-03 17:54
Closing since it's impossible to verify any regression here and a change in behavior sounds too breaking.

**Closed by deivid-rodriguez** 2023-03-03 17:54 UTC
Labels: status: feedback required, Bundler
