### ISSUE TITLE
ruby is invalid license type

### ISSUE THREAD

**Issue by zzak** [rubygems/rubygems#1423] opened 2015-12-25 14:10 UTC
We ran into an issue when trying to use the ruby license in our gemspec.

You can see we had to workaround the issue here: ruby/ruby@52c3b2eb2afc9b2587dc1530331b9667dfab442b

I'm not sure who's fault it is, maybe related to #1249 though.

**Comment by segiddins** [comment] 2015-12-25 14:17
According to SPDX, it's `Ruby`, not `ruby`

**Comment by Solnse** [comment] 2015-12-28 17:37
not sure the issue you ran into, but it looks like licenses wasn't an array.

**Comment by krainboltgreene** [comment] 2015-12-30 03:15
Hey @zzak, do you have steps to reproduce? I'm going to setup time to see if it was either of the suggested problems.

**Comment by duckinator** [comment] 2016-01-31 05:09
Hi! So, I just confirmed what @Solnse said: It is "Ruby", not "ruby."

Looking at the documentation for `spec.license` and `spec.licenses` (http://guides.rubygems.org/specification-reference/#license=), it says to use the SPDX ID and links to https://spdx.org/licenses/. That link says the SPDX ID is "Ruby", not "ruby". Given that, and the fact that `spec.license` and `spec.licenses` are case sensitive, an error is expected. You would've gotten a similar error if you didn't capitalise "BSD-2-Clause" exactly as you did.

You should be able to change it to "Ruby" and have it work, so I'm closing this issue. If that for some reason doesn't work, leave a comment here letting me know, and I'll reopen it.

**Closed by duckinator** 2016-01-31 05:09 UTC
Labels: category - gem spec
