### ISSUE TITLE
Wrong version of bundler is used if there are 2 versions

### ISSUE THREAD

**Issue by Pr0p1k** [rubygems/rubygems#3523] opened 2020-04-16 14:22 UTC
For example: 
Project: [diaspora](https://github.com/diaspora/diaspora)
I have system Ruby 2.5.1 (reproducible with rvm either). I have bundlers 2.1.2 and 1.17.3 installed and run bundle install -> lockfile is bundled with 2.1.2
Reproduce:
1. Ensure you have bundler versions pre 2.0 and 2+
2. Run `bundle install` -> 2+ version is used (see BUNDLED WITH in lockfile)
3. Run Rails application without `bundle exec`

Expected: Bundler version from bundled with is used. (2+ here)
Actual: Older one is used and hence we have an error: `You must use Bundler 2 or greater with this lockfile.`

**Comment by deivid-rodriguez** [comment] 2020-04-16 14:33
Could you post repro steps, please? Thanks.

**Comment by Pr0p1k** [comment] 2020-04-17 10:00
@deivid-rodriguez updated.

**Comment by deivid-rodriguez** [comment] 2020-04-17 10:05
Can you post the result of `bundle env`,or if that doesn't work due to the same issue, the result of `gem env`?

**Comment by Pr0p1k** [comment] 2020-04-17 13:25
## Environment

```
Bundler       2.1.2
  Platforms   ruby, x86_64-linux
Ruby          2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
  Full Path   /usr/bin/ruby2.5
  Config Dir  /etc
RubyGems      2.7.6
  Gem Home    /var/lib/gems/2.5.0
  Gem Path    /home/alex/.gem/ruby/2.5.0:/var/lib/gems/2.5.0:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.5.0:/usr/share/rubygems-integration/2.5.0:/usr/share/rubygems-integration/all
  User Home   /home/alex
  User Path   /home/alex/.gem/ruby/2.5.0
  Bin Dir     /usr/local/bin
Tools         
  Git         not installed
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2019-12-20
Git SHA           4da3289ebd
Released Version  true
```

**Comment by Pr0p1k** [comment] 2020-04-17 13:27
And also my gem list

*** LOCAL GEMS ***
```
actioncable (5.2.4.2)
actionmailer (5.2.4.2)
actionpack (5.2.4.2)
actionview (5.2.4.2)
active_model_serializers (0.9.7)
activejob (5.2.4.2)
activemodel (5.2.4.2)
activerecord (5.2.4.2)
activerecord-import (1.0.4)
activestorage (5.2.4.2)
activesupport (5.2.4.2)
acts-as-taggable-on (6.5.0)
acts_as_api (1.0.1)
addressable (2.7.0)
aes_key_wrap (1.0.1)
arel (9.0.0)
asset_sync (2.11.0)
ast (2.4.0)
attr_encrypted (3.1.0)
attr_required (1.0.1)
autoprefixer-rails (8.6.5)
babel-source (5.8.35)
babel-transpiler (0.7.0)
backports (3.17.1)
bcrypt (3.1.13)
bigdecimal (default: 1.3.4)
bindata (2.4.7)
bootstrap-sass (3.4.1)
bootstrap-switch-rails (3.3.3)
buftok (0.2.0)
builder (3.2.4)
bundler (2.1.2, 1.17.3, 1.16.1)
byebug (11.1.1)
capybara (3.15.0)
carrierwave (1.3.1)
celluloid (0.17.4)
celluloid-essentials (0.20.5)
celluloid-extras (0.20.5)
celluloid-fsm (0.20.5)
celluloid-io (0.17.3)
celluloid-pool (0.20.5)
celluloid-supervision (0.20.6)
chunky_png (1.3.11)
cliver (0.3.2)
cmath (default: 1.0.0)
coderay (1.1.2)
compass (1.0.3)
compass-core (1.0.3)
compass-import-once (1.0.5)
compass-rails (3.1.0)
concurrent-ruby (1.1.6)
configurate (0.3.1)
connection_pool (2.2.2)
coveralls (0.8.23)
crack (0.4.3)
crass (1.0.6)
csv (default: 1.0.0)
cucumber (3.1.2)
cucumber-api-steps (0.14.0)
cucumber-core (3.2.1)
cucumber-expressions (6.0.1)
cucumber-rails (2.0.0)
cucumber-tag_expressions (1.1.1)
cucumber-wire (0.0.1)
database_cleaner (1.8.3)
date (default: 1.0.0)
dbm (default: 1.0.0)
devise (4.7.1)
devise-two-factor (3.0.3)
devise_lastseenable (0.0.6)
diaspora_federation (0.2.6)
diaspora_federation-json_schema (0.2.6)
diaspora_federation-rails (0.2.6)
diaspora_federation-test (0.2.6)
did_you_mean (1.2.0)
diff-lcs (1.3)
docile (1.3.2, 1.1.5)
domain_name (0.5.20190701)
encryptor (3.0.0)
entypo-rails (3.0.0)
equalizer (0.0.11)
erubi (1.9.0)
eslintrb (2.1.0)
et-orbi (1.2.4)
etc (default: 1.0.0)
ethon (0.12.0)
excon (0.73.0)
execjs (2.7.0)
eye (0.10.0)
fabrication (2.21.1)
factory_girl (4.9.0)
factory_girl_rails (4.9.0)
faraday (0.15.4)
faraday-cookie_jar (0.0.6)
faraday_middleware (0.13.1)
fcntl (default: 1.0.0)
ffi (1.12.2)
ffi-compiler (1.0.1)
fiddle (default: 1.0.0)
fileutils (default: 1.0.2)
fixture_builder (0.5.2)
fog-aws (3.5.2)
fog-core (2.2.0)
fog-json (1.2.0)
fog-xml (0.1.3)
formatador (0.2.5)
fugit (1.3.4)
fuubar (2.5.0)
gdbm (default: 2.0.0)
get_process_mem (0.2.5)
gherkin (5.1.0)
gitlab (4.14.1)
globalid (0.4.2)
gon (6.3.2)
guard (2.16.1)
guard-compat (1.2.1)
guard-rspec (4.7.3)
guard-rubocop (1.3.0)
haml (5.1.2)
haml_lint (0.35.0)
hamlit (2.11.0)
handlebars_assets (0.23.8)
hashdiff (1.0.1)
hashie (4.1.0)
http (4.4.1)
http-cookie (1.0.3)
http-form_data (2.3.0)
http-parser (1.2.1)
http_accept_language (2.1.1)
http_parser.rb (0.6.0)
httparty (0.18.0)
httpclient (2.8.3)
i18n (1.8.2)
i18n-inflector (2.6.7)
i18n-inflector-rails (1.0.7)
idn-ruby (0.1.0)
io-console (default: 0.4.6)
ipaddr (default: 1.2.0)
ipaddress (0.8.3)
jaro_winkler (1.5.4)
jasmine (3.5.1)
jasmine-core (3.5.0)
jasmine-jquery-rails (2.0.3)
jquery-rails (4.3.5)
js-routes (1.4.9)
js_image_paths (0.1.1)
json (2.3.0, default: 2.1.0)
json-jwt (1.11.0)
json-schema (2.8.1)
json-schema-rspec (0.0.4)
jsonpath (1.0.5)
jwt (2.2.1)
kgio (2.11.3)
kostya-sigar (2.0.6)
leaflet-rails (1.6.0)
listen (3.2.1)
little-plugger (1.1.4)
logging (2.2.2)
logging-rails (0.6.0)
loofah (2.5.0)
lumberjack (1.2.4)
macaddr (1.7.2)
mail (2.7.1)
marcel (0.3.3)
markdown-it-html5-embed (1.0.0)
markerb (1.1.0)
memoizable (0.4.2)
method_source (1.0.0)
mime-types (3.3.1)
mime-types-data (3.2019.1009)
mimemagic (0.3.4)
mini_magick (4.10.1)
mini_mime (1.0.2)
mini_portile (0.6.2)
mini_portile2 (2.4.0)
minitest (5.14.0, 5.10.3)
mobile-fu (1.4.0)
molinillo (0.6.4)
multi_json (1.14.1)
multi_test (0.1.2)
multi_xml (0.6.0)
multipart-post (2.1.1)
mysql2 (0.5.3)
naught (1.1.0)
nenv (0.3.0)
net-http-persistent (2.9.4)
net-telnet (0.1.1)
nio4r (2.5.2)
nokogiri (1.10.9)
notiffany (0.1.3)
oauth (0.5.4)
oauth2 (1.4.4)
octokit (4.18.0)
omniauth (1.9.1)
omniauth-oauth (1.1.0)
omniauth-oauth2 (1.6.0)
omniauth-tumblr (1.2)
omniauth-twitter (1.4.0)
omniauth-wordpress (0.2.2)
open_graph_reader (0.7.0)
openid_connect (1.1.8)
openssl (default: 2.1.1)
orm_adapter (0.5.0)
parallel (1.19.1)
parser (2.7.1.0)
phantomjs (2.1.1.0)
poltergeist (1.18.1)
power_assert (0.2.7)
pronto (0.10.0)
pronto-eslint (0.10.0)
pronto-haml (0.10.0)
pronto-rubocop (0.10.0)
pronto-scss (0.10.0)
pry (0.13.1)
pry-byebug (3.9.0)
psych (default: 3.0.2)
public_suffix (4.0.4)
raabro (1.1.6)
rack (2.0.9)
rack-cors (1.1.1)
rack-google-analytics (1.2.0)
rack-mobile-detect (0.4.0)
rack-oauth2 (1.12.0)
rack-piwik (0.3.0)
rack-protection (2.0.8.1)
rack-rewrite (1.5.1)
rack-ssl (1.4.1)
rack-test (1.1.0)
rails (5.2.4.2)
rails-assets-autosize (4.0.2)
rails-assets-backbone (1.3.3)
rails-assets-blueimp-gallery (2.33.0)
rails-assets-bootstrap (3.4.1)
rails-assets-bootstrap-markdown (2.10.0)
rails-assets-corejs-typeahead (1.2.1)
rails-assets-cropperjs (1.4.3)
rails-assets-fine-uploader (5.13.0)
rails-assets-highlightjs (9.12.0)
rails-assets-jasmine (3.4.0)
rails-assets-jasmine-ajax (4.0.0)
rails-assets-jquery (3.4.1)
rails-assets-jquery-placeholder (2.3.1)
rails-assets-jquery-textchange (0.2.3)
rails-assets-jquery.are-you-sure (1.9.0)
rails-assets-jquery.ui (1.11.4)
rails-assets-markdown-it (8.4.2)
rails-assets-markdown-it--markdown-it-for-inline (0.1.1)
rails-assets-markdown-it-diaspora-mention (1.2.0)
rails-assets-markdown-it-hashtag (0.4.0)
rails-assets-markdown-it-sanitizer (0.4.3)
rails-assets-markdown-it-sub (1.0.0)
rails-assets-markdown-it-sup (1.0.0)
rails-assets-pica (5.0.0)
rails-assets-underscore (1.9.1)
rails-assets-utatti-perfect-scrollbar (1.4.0)
rails-controller-testing (1.0.4)
rails-dom-testing (2.0.3)
rails-html-sanitizer (1.3.0)
rails-i18n (5.1.3)
rails-timeago (2.18.0)
railties (5.2.4.2)
rainbow (3.0.0)
raindrops (0.19.1)
rake (12.3.3, 12.3.1)
rb-fsevent (0.10.3)
rb-inotify (0.10.1)
rdoc (default: 6.0.1)
redcarpet (3.5.0)
redis (3.3.5)
regexp_parser (1.7.0)
request_store (1.5.0)
responders (2.4.1)
rexml (3.2.4)
rotp (2.1.2)
rqrcode (1.1.2)
rqrcode_core (0.1.2)
rspec (3.9.0)
rspec-core (3.9.1)
rspec-expectations (3.9.1)
rspec-json_expectations (2.2.0)
rspec-mocks (3.9.1)
rspec-rails (4.0.0, 3.9.1)
rspec-support (3.9.2)
rubocop (0.80.1)
rubocop-rails (2.4.1)
ruby-oembed (0.12.0)
ruby-progressbar (1.10.1)
rubyzip (1.3.0)
rugged (0.99.0)
safe_yaml (1.0.5)
sass (3.4.25)
sass-rails (5.0.7)
sassc (2.2.1)
sawyer (0.8.2)
scanf (default: 1.0.0)
scss_lint (0.55.0)
sdbm (default: 1.0.0)
secure_headers (6.3.0)
shellany (0.0.1)
shoulda-matchers (4.0.1)
sidekiq (5.2.8)
sidekiq-cron (1.1.0)
simple_captcha2 (0.5.0)
simple_oauth (0.3.1)
simplecov (0.16.1, 0.15.0)
simplecov-html (0.10.2)
sinon-rails (1.15.0)
spring (2.1.0)
spring-commands-cucumber (1.0.1)
spring-commands-rspec (1.0.4)
sprockets (3.7.2)
sprockets-es6 (0.9.2)
sprockets-rails (3.2.1)
state_machines (0.5.0)
string-direction (1.2.2)
stringio (default: 0.0.1)
strscan (default: 1.0.0)
swd (1.1.2)
sync (0.5.0)
sysexits (1.2.0)
systemu (2.6.5)
temple (0.8.2)
term-ansicolor (1.7.1)
terminal-table (1.8.0)
test-unit (3.2.5)
thor (0.20.3, 0.19.4)
thread_safe (0.3.6)
tilt (2.0.10)
timecop (0.9.1)
timers (4.3.0)
tins (1.24.1)
to_regexp (0.2.1)
turbo_dev_assets (0.0.2)
twitter (7.0.0)
twitter-text (3.0.0)
typhoeus (1.3.1)
tzinfo (1.2.7)
uglifier (4.2.0)
unf (0.1.4)
unf_ext (0.0.7.7)
unicode-display_width (1.6.1)
unicorn (5.5.3)
unicorn-worker-killer (0.4.4)
uuid (2.3.9)
valid (1.2.0)
validate_email (0.1.6)
validate_url (1.0.8)
versionist (2.0.1)
warden (1.2.8)
webfinger (1.1.0)
webmock (3.8.3)
webrick (default: 1.4.2)
websocket-driver (0.7.1)
websocket-extensions (0.1.4)
will_paginate (3.3.0)
xpath (3.2.0)
yajl-ruby (1.4.1)
yard (0.9.24)
zlib (default: 1.0.0)
```

**Comment by Pr0p1k** [comment] 2020-04-20 10:18
Yep, looks like it solves the problem in this particular case.

**Comment by deivid-rodriguez** [comment] 2020-05-12 20:53
Closing since the issue is solved in the latest rubygems.

**Closed by deivid-rodriguez** 2020-05-12 20:53 UTC
Labels: Bundler
