### ISSUE TITLE
rubygems signing does not support CA certificate located in HSM

### ISSUE THREAD

**Issue by gkerner** [rubygems/rubygems#5243] opened 2021-12-30 08:33 UTC
Hi,

I cannot sign ruby packages as our CA certificate is signed by a private key located in HSM and is non- extractable.

According to this code, certificate must be provided with its corresponding private key - in pem/bytes format, but none can be provided when using HSM:
[https://github.com/rubygems/rubygems/blob/e7e1487459eb8b96d6adfeb2dcc434121f10bed9/lib/rubygems/security/signer.rb#L87]

The only way to access the private key object is during a token session but it cannot being converted to any of the ruby expectation formats.

Will it be supported? Any other solution you can think about?

Thanks!

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x ] Other

Here are my current environment details:

$ gem env
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\Program Files\Python310\Scripts\
     - C:\Program Files\Python310\
     - C:\Program Files\Java\jdk1.8.0_211\bin
     - C:\Windows\system32
     - C:\Windows
     - C:\Windows\System32\Wbem
     - C:\Windows\System32\WindowsPowerShell\v1.0\
     - C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps
     - C:\Dell\DELL EMC System Update
     - C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps
     - C:\Dell\DELL EMC System Update
     - C:\Program Files\SafeNet\Authentication\SAC\x64
     - C:\Program Files\SafeNet\Authentication\SAC\x32
     - C:\Program Files\Git\cmd
     - C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64
     - C:\Hlkx
     - C:\Ruby26-x64\bin
     - C:\Ruby26-x64\bin

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment] 2021-12-30 08:53
Duplicate of https://github.com/rubygems/rubygems/discussions/5107

**Closed by hsbt** 2021-12-30 08:53 UTC
Labels: RubyGems

**Comment by gkerner** [comment] 2021-12-30 08:57
#5107 moved to discussion
