### ISSUE TITLE
gem pristine doesn't seem to account for --user-install

### ISSUE THREAD

**Issue by mpalmer** [rubygems/rubygems#1968] opened 2017-07-05 02:15 UTC
Having somehow managed to get a pile of extensions miscompiled, I'm now being prompted to run `gem pristine <gem> --version <something>` for rather a lot of things.  However, it isn't working so well:

    $ gem pristine unicorn --version 5.3.0
    ERROR:  While executing gem ... (Gem::FilePermissionError)
        You don't have write permissions for the /var/lib/gems/2.3.0 directory.
    $ sudo gem pristine unicorn --version 5.3.0
    ERROR:  While executing gem ... (Gem::Exception)
        Failed to find gems ["unicorn"] = 5.3.0

I install all my gems with `--user-install` by default (my `~/.gemrc` has `install: --user-install`), so it's not surprising that running `gem pristine` as `root` gets confused, however I'm somewhat perturbed that running `gem pristine` as me is erroring out.

If I explicitly set `GEM_HOME=~/.gem` and then run `gem pristine`, everything seems to work, but my understanding was that doing that in general was considered poor form, and that `--user-install` was the recommended solution.

Here are my current environment details:

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.2
  - RUBY VERSION: 2.3.3 (2016-11-21 patchlevel 222) [x86_64-linux-gnu]
  - INSTALLATION DIRECTORY: /var/lib/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /home/mpalmer/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/bin/ruby2.3
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /home/mpalmer/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /var/lib/gems/2.3.0
     - /home/mpalmer/.gem/ruby/2.3.0
     - /usr/lib/x86_64-linux-gnu/rubygems-integration/2.3.0
     - /usr/share/rubygems-integration/2.3.0
     - /usr/share/rubygems-integration/all
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :benchmark => false
     - :sources => ["https://rubygems.org/"]
     - "install" => "--user-install --no-ri --no-rdoc --env-shebang"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/mpalmer/.gem/ruby/2.3.0/bin
[etc]
$ sudo gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.2
  - RUBY VERSION: 2.3.3 (2016-11-21 patchlevel 222) [x86_64-linux-gnu]
  - INSTALLATION DIRECTORY: /var/lib/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /root/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/bin/ruby2.3
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /var/lib/gems/2.3.0
     - /root/.gem/ruby/2.3.0
     - /usr/lib/x86_64-linux-gnu/rubygems-integration/2.3.0
     - /usr/share/rubygems-integration/2.3.0
     - /usr/share/rubygems-integration/all
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :benchmark => false
     - :sources => ["http://rubygems.org/"]
  - REMOTE SOURCES:
     - http://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by colby-swandale** [comment] 2017-08-20 13:27
Sorry that no one has replied, are you still experiencing your issue?

**Comment by mpalmer** [comment] 2017-08-21 05:33
Yep, just tried again, same behaviour as previously reported:

```
$ gem pristine onebox --version 1.8.16
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.3.0 directory.
$ sudo gem pristine onebox --version 1.8.16
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["onebox"] = 1.8.16
$ gem pristine --user-install onebox --version 1.8.16
ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: --user-install
$ GEM_HOME=~/.gem gem pristine onebox --version 1.8.16
Restoring gems to pristine condition...
Restored onebox-1.8.16
$ gem --version
2.5.2
```

(I picked `onebox-1.8.16` pretty much at random from the list of gems I had installed)

**Comment by myfreeweb** [comment] 2017-10-04 16:27
ruby 2.3.5p376 / gem 2.6.13 — it doesn't even respect `GEM_HOME`, running `GEM_HOME=~/.gem gem pristine --all` returns the same permission error.

**Comment by colby-swandale** [comment] 2017-12-12 11:24
I'm working on a fix for this.

**Comment by bronzdoc** [comment] 2018-06-22 18:32
I'm not able to reproduce this with the current version of rubygems(2.7.7) @mpalmer is this still and issue for you?

**Comment by mpalmer** [comment] 2018-06-25 05:13
Yep, still misbehaving in exactly the same way, with the added amusement that a couple of previously legit gemspecs now seem to be causing all sorts of spurious rubbish in the output:

```
$ gem pristine onebox --version 1.8.16
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from /home/mpalmer/.gem/ruby/2.3.0/specifications/openid-redis-store-0.0.2.gemspec:17.
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from /home/mpalmer/.gem/ruby/2.3.0/specifications/rack-openid-1.3.1.gemspec:17.
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.3.0 directory.
$ sudo gem pristine onebox --version 1.8.16
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["onebox"] = 1.8.16
$ gem pristine --user-install onebox --version 1.8.16
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from /home/mpalmer/.gem/ruby/2.3.0/specifications/openid-redis-store-0.0.2.gemspec:17.
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from /home/mpalmer/.gem/ruby/2.3.0/specifications/rack-openid-1.3.1.gemspec:17.
ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: --user-install
$ GEM_HOME=~/.gem gem pristine onebox --version 1.8.16
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from /home/mpalmer/.gem/ruby/2.3.0/specifications/openid-redis-store-0.0.2.gemspec:17.
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from /home/mpalmer/.gem/ruby/2.3.0/specifications/rack-openid-1.3.1.gemspec:17.
Restoring gems to pristine condition...
Restored onebox-1.8.16
$ gem --version
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from /home/mpalmer/.gem/ruby/2.3.0/specifications/openid-redis-store-0.0.2.gemspec:17.
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from /home/mpalmer/.gem/ruby/2.3.0/specifications/rack-openid-1.3.1.gemspec:17.
2.7.7
```

**Comment by bronzdoc** [comment] 2018-07-26 20:05
Closing since this seems like a problem with your environment and not a Rubygems issue

**Comment by alick** [comment] 2019-01-06 19:07
I met the same issue when I use `/usr/bin/gem`, even when my `~/.gemrc` has `--user-install`. The issue disappears when I switch to rvm and use gem from rvm (and no `~/.gemrc`).

**Comment by junaruga** [comment] 2019-09-06 13:35
Hi I created a reproducing script for this issue using Fedora container image and Travis CI.

Here it is.
https://github.com/junaruga/rubygems-to-restore-to-pristine
https://travis-ci.org/junaruga/rubygems-to-restore-to-pristine/jobs/581673419

This is executed by user permission.

```
+ gem -v
Ignoring byebug-11.0.1 because its extensions are not built. Try: gem pristine byebug --version 11.0.1
Ignoring nio4r-2.5.1 because its extensions are not built. Try: gem pristine nio4r --version 2.5.1
3.0.3

+ gem pristine byebug --version 11.0.1
Ignoring byebug-11.0.1 because its extensions are not built. Try: gem pristine byebug --version 11.0.1
Ignoring nio4r-2.5.1 because its extensions are not built. Try: gem pristine nio4r --version 2.5.1
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/share/gems directory.
The command "docker run --rm -t test/fedora "${TEST_CMD}"
" exited with 1.
```

I wish this helps to fix this issue.
Thanks!

**Comment by bronzdoc** [comment] 2019-09-06 13:39
Thanks for the reproducing script @junaruga! will give it a look

**Comment by mpalmer** [comment] 2019-09-08 05:00
@junaruga, you are awe-inspiring.

**Closed** 2019-10-26 20:48 UTC
Labels: type: bug report
