### ISSUE TITLE
"Could not find pkg-version in any of the sources" after upgrading to >= 2.2.14

### ISSUE THREAD

**Issue by theflow** [rubygems/rubygems#4553] opened 2021-04-21 14:53 UTC
### Describe the problem as clearly as you can

We're seeing increased "Could not find pkg-version in any of the sources" errors after upgrading to 2.2.16 (from 2.2.13) in Depfu, likely caused by #4381.

I've tried to debug this a bit but I have no real idea what's going on, I think the common thing is a Gemfile similar to this:

```
source 'https://rubygems.org'

gem 'dotenv'

source 'http://devfu-geminabox.flowbyte.net/' do
  gem 'pkg-gem-flowbyte-with-dep'
end

gem 'vcr', source: 'https://rubygems.org'
```

where an existing source is "reused" later. My best guess is that triggers `Definition#converge_sources` in a way that confuses something, but I can't really get to the bottom of it.

### Post steps to reproduce the problem

I've tried to reproduce it here, but not 100% sure if it reliably does. If it doesn't for you, please let me know

https://gist.github.com/theflow/27cb3e90df882d769c9bd3b882791f5f

### Which command did you run?

I want to `bundle update oj`, but it fails on 2.2.16 with an earlier lockfile. In the repro above I used `bundle outdated` since that was quicker to test and seems to show the same behavior.

### What were you expecting to happen?

That Bundler 2.2.16 updates `oj` to the new version without me having to regenerate the lockfile in the new format.

👉 I can also remove `source: 'https://rubygems.org'` from the `vcr` line and it works!

### What actually happened?

```
+ mkdir -p /tmp/repro-could-not-find
+ cd /tmp/repro-could-not-find
+ cat
+ cat
+ bundle _2.2.13_ install
Using bundler 2.2.13
Using dotenv 2.7.6
Using oj 3.11.3
Using pkg-gem-flowbyte-with-dep 1.0.0
Using vcr 6.0.0
Bundle complete! 3 Gemfile dependencies, 5 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
+ bundle _2.2.13_ outdated
Fetching gem metadata from https://rubygems.org/...
Fetching gem metadata from http://devfu-geminabox.flowbyte.net/...
Fetching gem metadata from https://rubygems.org/...
Fetching gem metadata from https://rubygems.org/.
Fetching gem metadata from http://devfu-geminabox.flowbyte.net/..
Resolving dependencies...

Gem  Current  Latest  Requested  Groups
oj   3.11.3   3.11.5
+ bundle _2.2.16_ outdated
[DEPRECATED] Your lockfile contains a single rubygems source section with multiple remotes, which is insecure. You should run `bundle update` or generate your lockfile from scratch.
Fetching gem metadata from https://rubygems.org/...
Fetching gem metadata from http://devfu-geminabox.flowbyte.net/...
Fetching gem metadata from https://rubygems.org/...
Fetching gem metadata from https://rubygems.org/.
Fetching gem metadata from http://devfu-geminabox.flowbyte.net/..
Fetching gem metadata from https://rubygems.org/.
Fetching gem metadata from http://devfu-geminabox.flowbyte.net/..
Resolving dependencies...
Could not find oj-3.11.5 in any of the sources
```

**Comment by javierjulio** [comment] 2021-04-21 21:14
I've run into the same issue after also updating bundler to 2.2.16. We have a similar setup but the second remote is for Sidekiq to install Pro and Enterprise so we get that same deprecation warning but also the "could not find (gem) in any of the sources" message on `bundle install`.

**Comment by thewalkingtoast** [comment] 2021-04-21 23:36
Seems like a duplicate of https://github.com/rubygems/rubygems/issues/4543

**Comment by deivid-rodriguez** [comment] 2021-04-22 07:11
It's a fix for a different issue, but https://github.com/rubygems/rubygems/pull/4554 seems to also fix this!

**Comment by deivid-rodriguez** [comment] 2021-04-22 11:05
I also proposed #4556 separately, that should speed up several parts of `bundler` and as a side effect, also fix this issue.

**Comment by theflow** [comment] 2021-04-22 11:20
Ok, #4556 fixes this for the `bundle outdated` call:

```
~/tmp/repro git:(main) ▶ bundle _2.2.16_ outdated
[DEPRECATED] Your lockfile contains a single rubygems source section with multiple remotes, which is insecure. You should run `bundle update` or generate your lockfile from scratch.
Fetching gem metadata from https://rubygems.org/...
Fetching gem metadata from http://devfu-geminabox.flowbyte.net/...
Fetching gem metadata from https://rubygems.org/...
Fetching gem metadata from https://rubygems.org/.
Fetching gem metadata from http://devfu-geminabox.flowbyte.net/..
Fetching gem metadata from https://rubygems.org/.
Fetching gem metadata from http://devfu-geminabox.flowbyte.net/..
Resolving dependencies...

Gem  Current  Latest  Requested  Groups
oj   3.11.3   3.11.5
```

but the actual problem I'm having isn't fixed with that or #4554:

```
~/tmp/repro git:(main) ▶ bundle _2.2.16_ update oj
[DEPRECATED] Your lockfile contains a single rubygems source section with multiple remotes, which is insecure. You should run `bundle update` or generate your lockfile from scratch.
Fetching gem metadata from https://rubygems.org/...
Fetching gem metadata from http://devfu-geminabox.flowbyte.net/...
Fetching gem metadata from https://rubygems.org/..
Fetching gem metadata from http://devfu-geminabox.flowbyte.net/..
Fetching gem metadata from https://rubygems.org/..
Fetching gem metadata from http://devfu-geminabox.flowbyte.net/..
Fetching gem metadata from https://rubygems.org/..
Fetching gem metadata from http://devfu-geminabox.flowbyte.net/..
Fetching gem metadata from https://rubygems.org/..
Fetching gem metadata from http://devfu-geminabox.flowbyte.net/..
Fetching gem metadata from https://rubygems.org/..
Fetching gem metadata from http://devfu-geminabox.flowbyte.net/..
Resolving dependencies...
Could not find oj-3.11.5 in any of the sources
```

(sorry, looks like the outdated wasn't quite the same to reproduce this)

**Comment by deivid-rodriguez** [comment] 2021-04-22 11:30
Indeed, I can still repro with `bundle update oj`. I'll have one more look tomorrow.

**Comment by deivid-rodriguez** [comment] 2021-04-22 17:18
This patch on top of #4554 seems to do the trick:

```diff
diff --git a/bundler/lib/bundler/source/rubygems.rb b/bundler/lib/bundler/source/rubygems.rb
index 323c54c26a..cede580b0a 100644
--- a/bundler/lib/bundler/source/rubygems.rb
+++ b/bundler/lib/bundler/source/rubygems.rb
@@ -29,7 +29,7 @@ def initialize(options = {})
       def local!
         return if @allow_local
 
-        specs.use(installed_specs, :override_dupes)
+        @specs = nil
         @allow_local = true
       end
 
diff --git a/bundler/lib/bundler/spec_set.rb b/bundler/lib/bundler/spec_set.rb
index 423466da58..67669cdd0e 100644
--- a/bundler/lib/bundler/spec_set.rb
+++ b/bundler/lib/bundler/spec_set.rb
@@ -82,9 +82,9 @@ def materialize(deps, missing_specs = nil)
       materialized.group_by(&:source).each do |source, specs|
         next unless specs.any?{|s| s.is_a?(LazySpecification) }
 
+        source.local!
         names = -> { specs.map(&:name).uniq }
         source.double_check_for(names)
-        source.local!
       end
 
       materialized.map! do |s|
@@ -108,10 +108,10 @@ def materialized_for_all_platforms
       @specs.group_by(&:source).each do |source, specs|
         next unless specs.any?{|s| s.is_a?(LazySpecification) }
 
-        names = -> { specs.map(&:name).uniq }
-        source.double_check_for(names)
         source.local!
         source.remote!
+        names = -> { specs.map(&:name).uniq }
+        source.double_check_for(names)
       end
 
       @specs.map do |s|
```

I'll try to wrap this up tomorrow.

**Closed** 2021-04-28 06:36 UTC
Labels: Bundler

**Comment by theflow** [comment] 2021-04-28 10:25
Thanks @deivid-rodriguez 🙏 I can confirm this fixes the issues we were seeing.
