### ISSUE TITLE
Unable to run bundle with a preview ruby version

### ISSUE THREAD

**Issue by wildmaples** [rubygems/rubygems#7179] opened 2023-11-20 21:33 UTC
### Describe the problem as clearly as you can

Given a simple Gemfile with a required ruby version: 

```ruby
source 'https://rubygems.org'

ruby "3.3.0-preview2"
```

Running bundle on it gives me this error:

```
Your Ruby version is 3.3.0.preview2, but your Gemfile specified 3.3.0.pre.preview2
```

### Did you try upgrading rubygems & bundler?

I am on bundler v2.5.0.dev 

### Post steps to reproduce the problem

Stated above! 

### Which command did you run?

`bundle` 

### What were you expecting to happen?

For the ruby version to be resolved correctly to the ruby version in my Gemfile

### What actually happened?

Bundler doesn't do anything because of the validation check 

## Environment

```
Bundler       2.5.0.dev
  Platforms   ruby, arm64-darwin-23
Ruby          3.3.0p-1 (2023-09-14 revision e50fcca9a79d8e25b33ad3611df6bf4627faafbf) [arm64-darwin-23]
  Full Path   /Users/maple.ong/.rbenv/versions/3.3.0-preview2/bin/ruby
  Config Dir  /Users/maple.ong/.rbenv/versions/3.3.0-preview2/etc
RubyGems      3.5.0.dev
  Gem Home    /Users/maple.ong/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0
  Gem Path    /Users/maple.ong/.gem/ruby/3.3.0+0:/Users/maple.ong/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0
  User Home   /Users/maple.ong
  User Path   /Users/maple.ong/.gem/ruby/3.3.0+0
  Bin Dir     /Users/maple.ong/.rbenv/versions/3.3.0-preview2/bin
Tools         
  Git         2.39.3 (Apple Git-145)
  RVM         not installed
  rbenv       rbenv 1.2.0
  chruby      
```

## Bundler Build Metadata

```
Built At          2023-11-20
Git SHA           unknown
Released Version  false
```

### Gemfile

```ruby
source 'https://rubygems.org'

ruby "3.3.0-preview2"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:

PLATFORMS
  arm64-darwin-23

DEPENDENCIES

BUNDLED WITH
   2.5.0.dev
```

**Comment by simi** [comment] 2023-11-20 22:26
seems like dupe of https://github.com/rubygems/rubygems/issues/7013

**Comment by wildmaples** [comment] 2023-11-20 22:50
Hmm am I tripping or was [that fix supposed to go out in v2.4.21 ](https://github.com/rubygems/rubygems/releases/tag/bundler-v2.4.21) but I am still seeing it on the latest dev version.

**Comment by simi** [comment] 2023-11-20 22:59
@wildmaples you have reported with `Bundler 2.5.0.dev`, which could be anything (even older than 2.4.21). Can you test with 2.4.21 or newer released version?

**Comment by hsbt** [comment] 2023-11-20 23:49
Bundler 2.5.0.dev with 3.3.0-preview2 is old version. It's not contained https://github.com/rubygems/rubygems/issues/7013

**Comment by martinemde** [comment] 2023-12-05 21:57
@wildmaples I'm closing this for now since it seems like the fix might have been merged after the version you tested. If you still see this failure with an up-to-date copy of rubygems dev, please re-open.

**Closed by martinemde** 2023-12-05 21:57 UTC
Labels: Bundler
