### ISSUE TITLE
gem cleanup is busted due to skipping potential specs

### ISSUE THREAD

**Issue by zenspider** [rubygems/rubygems#334] opened 2012-05-18 20:59 UTC
As discovered in jbarnette/isolate#47, 7d43f14 makes Specification._all respond with a list of specifications minus redundant specs. As such, Specification.each skips potential specs to remove.

**Comment by copiousfreetime** [comment] 2016-01-19 01:15
I think this falls into the same category and/or is a duplicate of #335 so marking closed.

**Closed by copiousfreetime** 2016-01-19 01:15 UTC
Labels: bug report, duplicate
