### ISSUE TITLE
gem install fails with TypeError

### ISSUE THREAD

**Issue by stephengroat** [rubygems/rubygems#1700] opened 2016-08-27 19:07 UTC
I'm having a problem.

My current problem is `gem install` seems to fail in the Windows registry

This issue is related to:
- [ ] Network problems
- [ ] Installing a library
- [ ] Publishing a library
- [x] The command line `gem`
- [ ] Other

Here are my current environment details:

Windows 10, fully updated.
Running "Start Command Prompt with Ruby" as either user or Administrator

```
C:\Users\user>gem install --backtrace "rubygems-update"
ERROR:  While executing gem ... (TypeError)
    Type mismatch (expect [1] but 3 present)
        C:/Ruby23-x64/lib/ruby/2.3.0/win32/registry.rb:646:in `read'
        C:/Ruby23-x64/lib/ruby/2.3.0/win32/registry.rb:694:in `read_s'
        C:/Ruby23-x64/lib/ruby/2.3.0/win32/resolv.rb:64:in `block in get_info'
        C:/Ruby23-x64/lib/ruby/2.3.0/win32/registry.rb:435:in `open'
        C:/Ruby23-x64/lib/ruby/2.3.0/win32/registry.rb:542:in `open'
        C:/Ruby23-x64/lib/ruby/2.3.0/win32/resolv.rb:62:in `get_info'
        C:/Ruby23-x64/lib/ruby/2.3.0/win32/resolv.rb:20:in `get_resolv_info'
        C:/Ruby23-x64/lib/ruby/2.3.0/resolv.rb:972:in `default_config_hash'
        C:/Ruby23-x64/lib/ruby/2.3.0/resolv.rb:989:in `block in lazy_initialize'
        C:/Ruby23-x64/lib/ruby/2.3.0/resolv.rb:982:in `synchronize'
        C:/Ruby23-x64/lib/ruby/2.3.0/resolv.rb:982:in `lazy_initialize'
        C:/Ruby23-x64/lib/ruby/2.3.0/resolv.rb:360:in `block in lazy_initialize'
        C:/Ruby23-x64/lib/ruby/2.3.0/resolv.rb:358:in `synchronize'
        C:/Ruby23-x64/lib/ruby/2.3.0/resolv.rb:358:in `lazy_initialize'
        C:/Ruby23-x64/lib/ruby/2.3.0/resolv.rb:518:in `fetch_resource'
        C:/Ruby23-x64/lib/ruby/2.3.0/resolv.rb:512:in `each_resource'
        C:/Ruby23-x64/lib/ruby/2.3.0/resolv.rb:493:in `getresource'
        C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/remote_fetcher.rb:99:in `api_endpoint'
        C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/source.rb:47:in `api_uri'
        C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/source.rb:86:in `dependency_resolver_set'
        C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/resolver/best_set.rb:24:in `block in pick_sets'
        C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/source_list.rb:98:in `each'
        C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/source_list.rb:98:in `each_source'
        C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/resolver/best_set.rb:23:in `pick_sets'
        C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/resolver/best_set.rb:29:in `find_all'
        C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/resolver/installer_set.rb:152:in `find_all'
        C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/resolver/installer_set.rb:55:in `add_always_install'
        C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/dependency_installer.rb:474:in `resolve_dependencies'
        C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/commands/install_command.rb:239:in `install_gem'
        C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/commands/install_command.rb:300:in `block in install_gems'
        C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/commands/install_command.rb:296:in `each'
        C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/commands/install_command.rb:296:in `install_gems'
        C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/commands/install_command.rb:203:in `execute'
        C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/command.rb:308:in `invoke_with_build_args'
        C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/command_manager.rb:169:in `process_args'
        C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/command_manager.rb:139:in `run'
        C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/gem_runner.rb:55:in `run'
        C:/Ruby23-x64/bin/gem.cmd:29:in `<main>'
```

```
C:\Users\user>gem env version
2.5.1
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by kozo2** [comment] 2016-12-24 10:44
FYI, this is not limited to remote gems.
```
PS C:\Ruby23-x64\bin> .\gem install .\iruby-0.2.9.gem
ERROR:  While executing gem ... (TypeError)
    Type mismatch (expect [1] but 3 present)
PS C:\Ruby23-x64\bin> .\gem env version
2.5.2
PS C:\Ruby23-x64\bin>
```

**Comment by j-koch** [comment] 2016-12-26 15:31
I am having the same issue - I have both a desktop and a Surface Pro 4. Gem installs fail on the Surface with this error, using Ruby 2.2.6. Install of the _seemingly_ same configuration of Ruby on the desktop is successful on first try.

**Comment by segiddins** [comment] 2016-12-26 15:43
Since this is crashing deep in `resolv`, I'm not sure this is actually a bug in rubygems?

**Comment by j-koch** [comment] 2016-12-26 16:10
You're probably correct since I have successfully installed gems on two other machines... I'm just stumped why it has been throwing fits on this particular machine with this error. Do you have any suggestions on where to look for potential issues?

**Comment by kozo2** [comment] 2016-12-28 00:39
Apparently Ruby's resolv.rb is the cause of this problem.
I created a ticket on Ruby redmine. https://bugs.ruby-lang.org/issues/13081

**Comment by nobu** [comment] 2016-12-28 02:23
It reads the registry `\\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\SearchList`, which should be `REG_SZ` usually.
Why is it `REG_BINARY` on your machines?

**Comment by kozo2** [comment] 2016-12-30 02:36
I don't know why `SearchList` has `REG_BINARY` but certainly `SearchList` is not `REG_SZ`.

**Comment by stephengroat** [comment] 2016-12-30 03:51
for me, it's `REG_BINARY`. are you on windows 10?

**Comment by kozo2** [comment] 2016-12-30 04:13
I fixed this by replacing
`reg.read("SearchList", Registory::REG_SZ, Registory::REG_BINARY)`
to
`reg.read("SearchList", Registry::REG_SZ, Registry::REG_BINARY)[1]`
in `C:\Ruby23-x64\lib\ruby\2.3.0\resolv.rb`

**Comment by kozo2** [comment] 2016-12-30 04:14
@stephengroat Yes, I'm on Windows 10.

**Comment by nobu** [comment] 2017-01-04 07:59
Is the value in that `REG_BINARY` `SearchList` effective?
e.g., `ipconfig /all` shows it?

**Comment by kozo2** [comment] 2017-01-09 02:45
@nobu I do not know how to check the effectiveness.
My Windows is Japanese edition. I could not find the word "REG_BINARY" or "SearchList" in the "ipconfig /all" output.

**Comment by nobu** [comment] 2017-01-09 04:49
When `REG_BINARY`

```
C:>reg query HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters /v SearchList
reg query HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters /v SearchList

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
    SearchList    REG_BINARY    6578616D706C652E6E6574


C:>ipconfig /all | findstr DNS
ipconfig /all | findstr DNS
   プライマリ DNS サフィックス . . . . .: 
   接続固有の DNS サフィックス . . . . .: 
   DNS サーバー. . . . . . . . . . . . .: 192.168.0.1
   接続固有の DNS サフィックス . . . . .: 
   DNS サーバー. . . . . . . . . . . . .: 192.168.56.1
   接続固有の DNS サフィックス . . . . .: 
   接続固有の DNS サフィックス . . . . .: 
```

When `REG_SZ`

```
C:>reg query HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters /v SearchList
reg query HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters /v SearchList

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
    SearchList    REG_SZ    example.net


C:>ipconfig /all | findstr DNS
ipconfig /all | findstr DNS
   プライマリ DNS サフィックス . . . . .: 
   DNS サフィックス検索一覧. . . . . . .: example.net
   接続固有の DNS サフィックス . . . . .: 
   DNS サーバー. . . . . . . . . . . . .: 192.168.0.1
   接続固有の DNS サフィックス . . . . .: 
   DNS サーバー. . . . . . . . . . . . .: 192.168.56.1
   接続固有の DNS サフィックス . . . . .: 
   接続固有の DNS サフィックス . . . . .: 
```

Note that "DNS サフィックス検索一覧".

**Comment by kozo2** [comment] 2017-01-11 11:03
@nobu 
```
Microsoft Windows [Version 10.0.14986]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\knishida>ipconfig /all | findstr DNS
   プライマリ DNS サフィックス . . . . .:
   接続固有の DNS サフィックス . . . . .:
   接続固有の DNS サフィックス . . . . .:
   接続固有の DNS サフィックス . . . . .:
   DNS サーバー. . . . . . . . . . . . .: 10.2.240.16
   接続固有の DNS サフィックス . . . . .:
   接続固有の DNS サフィックス . . . . .:

C:\Users\knishida>
```

**Comment by nobu** [comment] 2017-01-11 14:30
If the registry entry is set but `ipconfig` doesn't show the search list, your system also considers the entry broken.

**Comment by kozo2** [comment] 2017-02-13 06:53
seems this update will fix this issue
https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/57265/diff/ext/win32/lib/win32/resolv.rb

**Comment by ignatiusbill** [comment] 2017-02-28 07:37
Looking at https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/57265/diff/ext/win32/lib/win32/resolv.rb, I can't seem to find the path `ext/win32/lib/win32/resolv.rb` on my Windows 10 machine. The closest thing I get is `C:\Windows\System32` but there's no resolv.rb in there. Regardless, gem install isn't working for me.

Typing in `gem install json --platform=ruby` or any other install using the gem command gives
```ERROR:  While executing gem ... (TypeError)
    Type mismatch (expect [1] but 3 present)```

**Comment by drbrain** [comment] 2017-02-28 19:06
I think that file will be installed at `gem which win32/resolv.rb` on your machine.

**Comment by ignatiusbill** [comment] 2017-02-28 20:21
Thanks! But since I'm using a newer version of Ruby (I'm guessing), my resolv.rb ([pastebin link](http://pastebin.com/CRbZYHyq)) isn't like the one provided by nobu. Which lines should I replace/add/delete?

**Comment by hsbt** [comment] 2017-11-30 08:22
This issue was fixed at ruby core.

**Closed by hsbt** 2017-11-30 08:22 UTC
Labels: platform: windows, status: triage
