### ISSUE TITLE
gem 3.0.0 `require': cannot load such file

### ISSUE THREAD

**Issue by k-yamada-4105156** [rubygems/rubygems#2535] opened 2018-12-20 08:04 UTC
I'm having a problem

My current problem is
I cannot build nokogiri libraries in gem 3.0.0 with non privileged user
I cloud build in gem 2.7.8 and gem 2.5.1
How cloud I solve this problem?

my environment
```
Amazon linux
ruby 2.3.1
```

I ran command below
`root@ip-10-7-4-13:~$ runuser -l deploy -c 'bundle config build.nokogiri --use-system-libraries'` 

Error messages below
```
/usr/local/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rubygems/core_ext/kernel_warn (LoadError)
	from /usr/local/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:1395:in `<top (required)>'
	from <internal:gem_prelude>:4:in `require'
	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
```

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [x] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
root@ip-10-7-4-13:~$ gem -v
3.0.0
```

**Comment by hsbt** [comment] 2018-12-20 08:18
I couldn't reproduce with Ruby 2.3.8 and RubyGems 3.0.0.

```
~ > ruby -v
ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-darwin18]
~ > gem -v
3.0.0
~ > gem i nokogiri -- --use-system-libraries=true
Fetching nokogiri-1.9.1.gem
Fetching mini_portile2-2.4.0.gem
Successfully installed mini_portile2-2.4.0
Building native extensions with: '--use-system-libraries=true'
This could take a while...
Successfully installed nokogiri-1.9.1
1 gem installed
```

Maybe, It's related with https://github.com/rubygems/rubygems/pull/2442

**Comment by ryanjwilke** [comment] 2018-12-20 17:56
I'm having a similar issue on my CI platform. I'm getting lots of this:

```
/usr/gem/bin/bundle:23:in `load': cannot load such file -- /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/exe/bundle
```

So far, the fix has been to add `RUN gem update --system 2.7.8` to my Dockerfile.

**Comment by MSP-Greg** [comment] 2018-12-20 18:09
@ryanjwilke

Not being sure what other gem commands are being run, but the following should be safe for anything newer than Ruby 2.2.x.  It will use RG 3.0.0 rather than forcing 2.7.8...

```
gem update --system --conservative
gem i bundler --conservative
```

**Comment by ryanjwilke** [comment] 2018-12-20 20:53
@MSP-Greg I just tried that, but is still breaks with the following error message:
```
/usr/gem/bin/bundle:23:in `load': cannot load such file -- /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/exe/bundle (LoadError)
	from /usr/gem/bin/bundle:23:in `<main>'
```

**Comment by MSP-Greg** [comment] 2018-12-20 21:18
@ryanjwilke

What CI platform?  Do you know if bundler is already installed?  Your error shows the standard 'internal' gem path, but I think RG 3.0.0 installs bundler in 'site_ruby'.

I think I've repo'd it locally.  Adding the following before the above two lines fixed it.
```
gem uninstall bundler -x --force
```

**Comment by ryanjwilke** [comment] 2018-12-21 00:55
@MSP-Greg CodeShip is the CI platform. I'm using Jekyll's docker image which already has some stuff packaged with it. Here's what the `Dockerfile` looks like:
```
FROM jekyll/jekyll:3.8.5
ENV JEKYLL_VERSION=3.8.5

RUN apk --no-cache add curl jq
RUN gem update --system 2.7.8
RUN npm install --global surge

WORKDIR /srv/jekyll

COPY Gemfile* /srv/jekyll/

RUN bundle install

ADD . /srv/jekyll
```

**Comment by hsbt** [comment] 2018-12-21 13:21
@ryanjwilke @zx1986 Maybe your problems caused by the linux distribution problem like Debian. I can not support them.

**Comment by envygeeks** [comment] 2018-12-21 14:36
@hsbt this happens on Alpine Linux too. https://github.com/rubygems/rubygems/issues/2541#issuecomment-449403367 the only thing special about Alpine Linux docker image is GEM_HOME, and BUNDLE_HOME

**Comment by envygeeks** [comment] 2018-12-21 16:35
@ryanjwilke I've fixed this bug in `jekyll/jekyll` Docker image, and it's deploying right now, this should no longer be an issue on my images.

**Comment by jeremywadsack** [comment] 2018-12-21 21:31
We are having the same problem on Circle CI. See [this StackOverflow post] for additional instances.

I ended up changing out `Dockerfile` to not update rubygems:

```
- RUN gem update --system --no-document
+ RUN gem update bundler --no-document
```

Per #2541 we are running these commands a `root` because we are building a container. But then we create a user to run `bundle` so that gems are installed with the user that will be accessing them.

**Comment by headius** [comment] 2018-12-22 00:19
JRuby master (pre-9.2.6 with fixes for recently discovered issues) appears to be unaffected, but previous versions will likely not get this far due to #2542.

**Comment by zx1986** [comment] 2018-12-22 02:12
my solution is lock rubygems version by:
`gem update --system 2.7.8`

**Closed** 2018-12-22 11:49 UTC
Labels: status: triage
