### ISSUE TITLE
gemspec needs a way to declare source: private Gems can depend on private Gems

### ISSUE THREAD

**Issue by tilo** [rubygems/rubygems#4441] opened 2021-03-08 23:00 UTC
### Describe the problem as clearly as you can

We have private gems, which contain private gems. The dependency is declared in the gemspec file.

Currently there is no way to declare that the private dependencies are coming from a specific source, other than RubyGems

Please add support for the `source` syntax in the gemspec files

**Comment by dpep** [comment] 2021-03-10 22:15
yeah, while Gemfile allows us to specify ruby sources (eg. RubyGems and Gemfury), gemspec does not.  adding a `source` option to gemspec would help guard against attacks like our industry's recent dependency confusion: https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610

thanks!

**Comment by evanphx** [comment] 2021-03-10 23:54
Hi @tilo, thinking about this particular solution, I'm unsure how putting source in the gemspec would solve this. What would read this new field? What values of the field would trigger what behavior?

**Comment by tilo** [comment] 2021-03-15 16:38
Private gems are to be published only to a private repository, and any dependencies to other private gems need to be isolated, so that bundler is not pulling them from rubygems.org, but only from the specified source.

```
  # private dependencies
  source 'https://gem.fury.io/private' do
    spec.add_dependency 'private_gem_1'
    spec.add_dependency 'private_gem_2', '2.2.6'
  end
```

or

```
  spec.add_dependency 'private_gem_1', source:  'https://gem.fury.io/private'
  spec.add_dependency 'private_gem_2', '2.2.6',  source:  'https://gem.fury.io/private'
```

**Comment by tmtrademarked** [comment] 2021-06-02 23:35
I could be misunderstanding the situation - but it seems like as it is today, a private gem that *only* depends on public gems still has trouble in Bundler. We have a gem published to a private gem fury, which depends on public gems via a gemspec. But when we bundle with the latest bundler, it seems to treat the dependencies for that gem as being "local" (ie, sourceless), which is clearly wrong.

So, again, if I'm understanding it all correctly, it seems like there might be a problem both in terms of specifying private sources, and in terms of correctly parsing sources for private gems even as is.

**Comment by deivid-rodriguez** [comment] 2021-06-27 18:27
This is a duplicate of https://github.com/rubygems/rubygems/issues/2731, so I'll close it in favour of that issue.

**Closed by deivid-rodriguez** 2021-06-27 18:27 UTC
Labels: Bundler
