### ISSUE TITLE
Extra space before `BUNDLED WITH` and `RUBY VERSION` entries

### ISSUE THREAD

**Issue by kiendang** [rubygems/rubygems#6780] opened 2023-06-29 18:21 UTC
### Describe the problem as clearly as you can

This is not a bug report, just a question. Why is there an extra space before the entries under `RUBY VERSION` and `BUNDLED WITH` in a bundler generated Gemfile.lock?

```
PLATFORMS
  arm64-darwin-22

DEPENDENCIES
  github-pages

BUNDLED WITH
   2.3.9
```

There are 3 spaces before `2.3.9` compared to 2 before `arm64-darwin-22` and `github-pages`.

**Comment by deivid-rodriguez** [comment] 2023-06-29 18:25
Duplicate of https://github.com/rubygems/rubygems/issues/3326. I think it was just an oversight.

**Closed by deivid-rodriguez** 2023-06-29 18:25 UTC
Labels: Bundler
