### ISSUE TITLE
تعذر التثبيت

### ISSUE THREAD

**Issue by khalid-Hake** [rubygems/rubygems#5933] opened 2022-09-18 00:30 UTC
Could not find loofah-2.18.0 in any of the sources

**Comment by simi** [comment] 2022-09-18 00:45
Can you provide steps to reproduce? I can't reproduce using `https://rubygems.org` source.

```
$ gem install loofah:2.18.0 --verbose

HEAD https://index.rubygems.org/
200 OK
GET https://index.rubygems.org/info/loofah
200 OK
GET https://index.rubygems.org/info/crass
200 OK
GET https://index.rubygems.org/info/nokogiri
200 OK
GET https://index.rubygems.org/info/mini_portile
200 OK
GET https://index.rubygems.org/info/mini_portile2
200 OK
GET https://index.rubygems.org/info/pkg-config
200 OK
GET https://index.rubygems.org/info/racc
200 OK
C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/loofah-2.18.0/CHANGELOG.md
C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/loofah-2.18.0/MIT-LICENSE.txt
C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/loofah-2.18.0/README.md
C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/loofah-2.18.0/SECURITY.md
C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/loofah-2.18.0/lib/loofah.rb
C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/loofah-2.18.0/lib/loofah/elements.rb
C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/loofah-2.18.0/lib/loofah/helpers.rb
C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/loofah-2.18.0/lib/loofah/html/document.rb
C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/loofah-2.18.0/lib/loofah/html/document_fragment.rb
C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/loofah-2.18.0/lib/loofah/html5/libxml2_workarounds.rb
C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/loofah-2.18.0/lib/loofah/html5/safelist.rb
C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/loofah-2.18.0/lib/loofah/html5/scrub.rb
C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/loofah-2.18.0/lib/loofah/instance_methods.rb
C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/loofah-2.18.0/lib/loofah/metahelpers.rb
C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/loofah-2.18.0/lib/loofah/scrubber.rb
C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/loofah-2.18.0/lib/loofah/scrubbers.rb
C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/loofah-2.18.0/lib/loofah/version.rb
C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/loofah-2.18.0/lib/loofah/xml/document.rb
C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/loofah-2.18.0/lib/loofah/xml/document_fragment.rb
Successfully installed loofah-2.18.0
Parsing documentation for loofah-2.18.0
Parsing sources...
100% [15/15]  lib/loofah/xml/document_fragment.rb
Installing ri documentation for loofah-2.18.0
Done installing documentation for loofah after 1 seconds
1 gem installed
```

**Comment by khalid-Hake** [comment] 2022-09-18 01:28
> 

.../opt/metasploit-framework $ msfconsole
Could not find factory_bot_rails-6.2.0, rspec-rails-5.1.2, actionpack-6.1.7, metasploit-concern-4.0.5, metasploit-credential-5.0.9, metasploit_data_models-5.0.5, metasploit-model-4.0.6, metasploit-payloads-2.0.94, railties-6.1.7, recog-2.3.23, actionview-6.1.7 in locally installed gems
Run `bundle install` to install missing gems.
![Uploading Screenshot_٢٠٢٢٠٩١٨-٠٤٢٧٤٠_Termux.jpg…]()

**Comment by flavorjones** [comment] 2022-09-19 13:09
Without more information, I can't be sure, but I suspect you may be running into issues installing nokogiri on termux (nokogiri is a dependency of loofah).

If that's the case, please check out
- https://nokogiri.org/tutorials/installing_nokogiri.html#termux_2

**Comment by flavorjones** [comment] 2022-09-19 20:55
Recommend closing this, I've asked for more information upstream at https://github.com/sparklemotion/nokogiri/issues/2651

**Closed** 2022-09-19 22:43 UTC
