### ISSUE TITLE
`find_spec_for_exe': can't find gem rms_web_service (>= 0.a) with executable rails

### ISSUE THREAD

**Issue by YanKyawMinSonicmoov** [rubygems/rubygems#5308] opened 2022-01-25 10:40 UTC
My current problem is 
After completion of  ** bundle install **,

```
$  rails -v
/Users/xxx/.rubies/ruby-3.1.0/lib/ruby/site_ruby/3.1.0/rubygems.rb:265:in `find_spec_for_exe': can't find gem rms_web_service (>= 0.a) with executable rails (Gem::GemNotFoundException)
        from /Users/xxx/.rubies/ruby-3.1.0/lib/ruby/site_ruby/3.1.0/rubygems.rb:284:in `activate_bin_path'
        from /Users/xxx/.gem/ruby/3.1.0/bin/rails:25:in `<main>'
```
So, I can't call rails cmd, and then I run **bundler -v**, this error occur.
I try this [link](https://bundler.io/blog/2019/05/14/solutions-for-cant-find-gem-bundler-with-executable-bundle.html), but it is not fixed for me.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env

RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.5
  - RUBY VERSION: 3.1.0 (2021-12-25 patchlevel 0) [x86_64-darwin19]
  - INSTALLATION DIRECTORY: /Users/xxx/.gem/ruby/3.1.0
  - USER INSTALLATION DIRECTORY: /Users/xxx/.gem/ruby/3.1.0
  - RUBY EXECUTABLE: /Users/xxx/.rubies/ruby-3.1.0/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /Users/xxx/.gem/ruby/3.1.0/bin
  - SPEC CACHE DIRECTORY: /Users/xxx/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/xxx/.rubies/ruby-3.1.0/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-darwin-19
  - GEM PATHS:
     - /Users/xxx/.gem/ruby/3.1.0
     - /Users/xxx/.rubies/ruby-3.1.0/lib/ruby/gems/3.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/xxx/.gem/ruby/3.1.0/bin
     - /Users/xxx/.rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/bin
     - /Users/xxx/.rubies/ruby-3.1.0/bin
     - /usr/local/sbin
     - /usr/local/opt/php@7.3/sbin
     - /usr/local/opt/php@7.3/bin
     - /Users/xxx/.pyenv/shims
     - /Users/xxx/.pyenv/bin
     - /Users/xxx/.nodebrew/current/bin
     - /opt/local/bin
     - /opt/local/sbin
     - /Users/xxx/.nodebrew/current/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Library/Apple/usr/bin
     - /usr/local/sbin
     - /usr/local/opt/php@7.3/sbin
     - /usr/local/opt/php@7.3/bin
     - /Users/xxx/.pyenv/shims
     - /Users/xxx/.pyenv/bin
     - /Users/xxx/.nodebrew/current/bin
     - /opt/local/bin
     - /opt/local/sbin
     - /Applications/Visual Studio Code.app/Contents/Resources/app/bin
     - /Users/xxx/go/bin
     - /usr/local/opt/go/libexec/bin
     - /Applications/Visual Studio Code.app/Contents/Resources/app/bin
     - /Users/xxx/go/bin
     - /usr/local/opt/go/libexec/bin
```

```
$ gem list

*** LOCAL GEMS ***

abbrev (default: 0.1.0)
actioncable (7.0.1, 6.1.4.4)
actionmailbox (7.0.1, 6.1.4.4)
actionmailer (7.0.1, 6.1.4.4, 4.0.8)
actionpack (7.0.1, 6.1.4.4, 4.0.8)
actiontext (7.0.1, 6.1.4.4)
actionview (7.0.1, 6.1.4.4)
active_scaffold (3.6.3, 3.6.0, 3.5.5, 3.4.27)
activejob (7.0.1, 6.1.4.4)
activemodel (7.0.1, 6.1.4.4, 4.0.8)
activerecord (7.0.1, 6.1.4.4, 4.0.8)
activerecord-deprecated_finders (1.0.4)
activerecord-session_store (2.0.0, 1.1.3, 0.1.1)
activestorage (7.0.1, 6.1.4.4)
activesupport (7.0.1, 6.1.4.4, 4.0.8)
addressable (2.8.0)
airbrussh (1.4.0)
akami (1.3.1)
arel (4.0.2)
autoprefixer-rails (10.4.2.0, 6.3.7)
base64 (default: 0.1.1)
bcrypt (3.1.16, 3.1.10)
benchmark (default: 0.2.0)
bigdecimal (default: 3.1.1)
bindex (0.8.1)
bootsnap (1.10.2)
bootstrap-sass (3.4.1, 3.3.5)
builder (3.2.4, 3.1.4)
bundler (2.3.5, 1.17.3, 1.15.0)
capistrano (3.16.0, 3.4.0)
capistrano-bundler (2.0.1, 1.6.0, 1.1.4)
capistrano-passenger (0.2.1, 0.1.1)
capistrano-rails (1.6.1, 1.1.8, 1.1.3)
capistrano-rbenv (2.2.0, 2.0.3)
capybara (3.36.0)
cgi (default: 0.3.1)
childprocess (4.1.0)
coderay (1.1.3, 1.1.0)
coffee-rails (5.0.0, 4.0.1)
coffee-script (2.4.1)
coffee-script-source (1.12.2, 1.9.1.1)
colorize (0.7.7)
concurrent-ruby (1.1.9)
coveralls (0.8.23)
cow_proxy (0.3.3)
crass (1.0.6)
csv (default: 3.2.2)
date (default: 3.2.2)
debase (0.2.5.beta2)
debase-ruby_core_source (0.10.14)
debug (1.4.0)
delegate (default: 0.2.0)
devise (4.8.1, 3.5.10)
did_you_mean (default: 1.6.1)
diff-lcs (1.5.0, 1.2.5)
digest (default: 3.1.0)
docile (1.4.0, 1.1.5)
double-bag-ftps (0.1.4, 0.1.2)
drb (default: 2.1.0)
english (default: 0.7.1)
erb (default: 2.2.3)
error_highlight (default: 0.3.0)
erubi (1.10.0)
erubis (2.7.0)
etc (default: 1.3.0)
excon (0.90.0, 0.45.4)
execjs (2.8.1, 2.6.0)
faraday (1.9.3, 0.9.1)
faraday-em_http (1.0.0)
faraday-em_synchrony (1.0.0)
faraday-excon (1.1.0)
faraday-httpclient (1.0.1)
faraday-multipart (1.0.3)
faraday-net_http (1.0.1)
faraday-net_http_persistent (1.2.0)
faraday-patron (1.0.0)
faraday-rack (1.0.0)
faraday-retry (1.0.3)
fcntl (default: 1.0.1)
ffi (1.15.5)
fiddle (default: 1.1.0)
fileutils (default: 1.6.0)
find (default: 0.1.1)
formatador (1.1.0, 0.2.5)
forwardable (default: 1.3.2)
getoptlong (default: 0.1.1)
globalid (1.0.0)
guard (2.18.0)
guard-compat (1.2.1)
guard-rspec (4.7.3)
gyoku (1.3.1)
hashie (5.0.0, 3.6.0, 3.4.2)
hike (1.2.3)
httpclient (2.8.3, 2.6.0.1)
httpi (2.5.0)
i18n (1.8.11, 0.9.5, 0.7.0)
ice_nine (0.11.2)
image_size (3.0.1, 1.4.1)
importmap-rails (1.0.2)
io-console (0.5.11, default: 0.5.10)
io-nonblock (default: 0.1.0)
io-wait (default: 0.2.1)
ipaddr (default: 1.2.3)
irb (default: 1.4.1)
jbuilder (2.11.5, 1.5.3)
jeff (2.0.2, 1.5.2, 1.5.1)
jquery-rails (4.4.0, 3.1.5)
json (default: 2.6.1)
jwt (2.3.0, 1.5.1)
libv8 (3.16.14.19, 3.16.14.13, 3.16.14.3)
listen (3.7.1)
logger (default: 1.5.0)
loofah (2.13.0)
lumberjack (1.2.8, 1.0.9)
mail (2.7.1, 2.5.5, 2.5.4)
marcel (1.0.2)
matrix (0.4.2)
method_source (1.0.0, 0.8.2)
migration_comments (0.4.1, 0.3.2)
mime-types (1.25.1)
mini_mime (1.1.2)
mini_portile (0.6.2)
mini_portile2 (2.7.1)
minitest (5.15.0, 4.7.5)
msgpack (1.4.4)
multi_json (1.15.0, 1.11.2)
multi_xml (0.6.0, 0.5.5)
multipart-post (2.1.1, 2.0.0)
mutex_m (default: 0.1.1)
nenv (0.3.0, 0.2.0)
net-ftp (0.1.3)
net-http (default: 0.2.0)
net-imap (0.2.3, 0.2.2)
net-pop (0.1.1)
net-protocol (default: 0.1.2)
net-scp (3.0.0, 1.2.1)
net-smtp (0.3.1)
net-ssh (6.1.0, 3.0.1)
netrc (0.10.3)
nio4r (2.5.8)
nkf (default: 0.1.1)
nokogiri (1.13.1 x86_64-darwin, 1.6.6.2)
nori (2.6.0)
notiffany (0.1.3)
oauth2 (1.4.7)
observer (default: 0.1.1)
omniauth (2.0.4, 1.4.2)
omniauth-oauth2 (1.7.2, 1.5.0)
omniauth-yconnect (0.0.4.1)
open-uri (default: 0.2.0)
open3 (default: 0.1.1)
openssl (default: 3.0.0)
optparse (default: 0.2.0)
orm_adapter (0.5.0)
ostruct (default: 0.5.2)
pathname (default: 0.2.0)
pg (1.3.0)
polyglot (0.3.5)
power_assert (2.0.1)
pp (default: 0.3.0)
prettyprint (default: 0.1.1)
prime (0.1.2)
pry (0.14.1)
pstore (default: 0.1.1)
psych (default: 4.0.3)
public_suffix (4.0.6)
puma (5.5.2)
racc (default: 1.6.0)
rack (2.2.3, 1.5.5)
rack-protection (2.1.0)
rack-test (1.1.0, 0.6.3)
rails (7.0.1, 6.1.4.4, 4.0.8)
rails-dom-testing (2.0.3)
rails-html-sanitizer (1.4.2)
railties (7.0.1, 6.1.4.4, 4.0.8)
rake (13.0.6, 10.5.0, 10.4.2)
rb-fsevent (0.11.0, 0.9.6)
rb-inotify (0.10.1)
rbs (2.0.0)
rdoc (default: 6.4.0, 6.3.3)
readline (default: 0.0.3)
readline-ext (default: 0.1.4)
ref (2.0.0)
regexp_parser (2.2.0)
reline (0.3.1, default: 0.3.0)
request_store (1.5.1)
resolv (default: 0.2.1)
resolv-replace (default: 0.1.0)
responders (3.0.1, 1.1.2)
rexml (3.2.5)
rinda (default: 0.1.1)
rspec (3.10.0)
rspec-core (3.10.1, 3.3.2)
rspec-expectations (3.10.2, 3.3.1)
rspec-mocks (3.10.2, 3.3.2)
rspec-support (3.10.3, 3.3.0)
rss (0.2.9)
ruby-debug-ide (0.7.3, 0.6.0)
ruby2_keywords (default: 0.0.5)
rubygems-update (3.3.5)
rubyzip (2.3.2, 1.1.7)
sass (3.2.19)
sass-rails (6.0.0, 4.0.5)
sassc (2.4.0)
sassc-rails (2.1.2)
savon (2.12.1)
sdoc (2.3.0)
securerandom (default: 0.1.1)
selenium-webdriver (4.1.0)
set (default: 1.0.2)
shellany (0.0.1)
shellwords (default: 0.1.0)
simplecov (0.16.1)
simplecov-html (0.10.2, 0.10.0)
singleton (default: 0.1.1)
slop (3.6.0)
socksify (1.7.1)
sprockets (4.0.2, 2.12.5, 2.12.4)
sprockets-rails (3.4.2, 2.3.3)
sqlite3 (1.4.2)
sshkit (1.21.2, 1.7.1)
stimulus-rails (1.0.2)
stringio (default: 3.0.1)
strscan (default: 3.0.1)
sync (0.5.0)
syslog (default: 0.1.0)
tempfile (default: 0.1.2)
term-ansicolor (1.7.1)
test-unit (3.5.3)
thor (1.2.1, 0.19.1)
thread_safe (0.3.6, 0.3.5)
tilt (2.0.10, 1.4.1)
time (default: 0.2.0)
timeout (default: 0.2.0)
tins (1.31.0, 1.6.0)
tmpdir (default: 0.1.2)
treetop (1.4.15)
tsort (default: 0.1.0)
turbo-rails (1.0.1)
typeprof (0.21.1)
tzinfo (2.0.4, 0.3.60, 0.3.44)
uglifier (4.2.0)
un (default: 0.2.0)
unf_ext (0.0.7.1)
uri (default: 0.11.0)
warden (1.2.9, 1.2.7)
wasabi (3.6.1)
weakref (default: 0.1.1)
web-console (4.2.0)
webdrivers (5.0.0)
websocket-driver (0.7.5)
websocket-extensions (0.1.5)
xpath (3.2.0)
yaml (default: 0.2.0)
zeitwerk (2.5.3)
zlib (default: 2.1.1)
```

**Comment by deivid-rodriguez** [comment] 2022-01-25 10:49
It seems like you rails binstub is corrupt? 😬

Can you show the contents of `/Users/xxx/.gem/ruby/3.1.0/bin/rails`?

**Comment by YanKyawMinGIT** [comment] 2022-01-26 01:42
```
xxx@xxx-MACPC bin % pwd 
/Users/xxx/.gem/ruby/3.1.0/bin

xxx@xxx-MACPC bin % cat rails
#!/usr/bin/env ruby
#
# This file was generated by RubyGems.
#
# The application 'rms_web_service' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

Gem.use_gemdeps

version = ">= 0.a"

str = ARGV.first
if str
  str = str.b[/\A_(.*)_\z/, 1]
  if str and Gem::Version.correct?(str)
    version = str
    ARGV.shift
  end
end

if Gem.respond_to?(:activate_bin_path)
load Gem.activate_bin_path('rms_web_service', 'rails', version)
else
gem "rms_web_service", version
load Gem.bin_path("rms_web_service", "rails", version)
end

```

**Comment by deivid-rodriguez** [comment] 2022-01-26 04:06
Yeah, that's what I expected. I have no idea how that binstub got there, you don't even have a "rms_web_service" gem installed, and it does not provide a "rails" executable anyways. Does `bundle install --force` fix things?

**Comment by YanKyawMinSonicmoov** [comment] 2022-01-26 04:39
After run `bundle install --force`, i get rails version cmd,
```
xxxx@xxxx-MACPC projectrepo % bundler -v
Bundler version 2.3.5
xxxx@xxxx-MACPC projectrepo % rails -v
Rails 7.0.1
```
After server run `bin/rails server` or `rails server`, this error occur ;
```
xxxx@xxxx-MACPC projectrepo % bin/rails server           
/Volumes/Macintosh HD - Data/xxxx/repos/project/projectrepo/lib/mws/recommendations.rb:1:in `require': /Volumes/Macintosh HD - Data/xxxx/repos/project/projectrepo/lib/mws/recommendations/client.rb:19: circular argument reference - marketplace_id (SyntaxError)
        from /Volumes/Macintosh HD - Data/xxxx/repos/project/projectrepo/lib/mws/recommendations.rb:1:in `<top (required)>'
        from /Volumes/Macintosh HD - Data/xxxx/repos/project/projectrepo/lib/mws.rb:11:in `require'
        from /Volumes/Macintosh HD - Data/xxxx/repos/project/projectrepo/lib/mws.rb:11:in `<top (required)>'
        from /Volumes/Macintosh HD - Data/xxxx/repos/project/projectrepo/lib/peddler.rb:1:in `require'
        from /Volumes/Macintosh HD - Data/xxxx/repos/project/projectrepo/lib/peddler.rb:1:in `<top (required)>'
        from /Users/xxxx/.gem/ruby/3.1.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:60:in `require'
        from /Users/xxxx/.gem/ruby/3.1.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /Users/xxxx/.gem/ruby/3.1.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:55:in `each'
        from /Users/xxxx/.gem/ruby/3.1.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:55:in `block in require'
        from /Users/xxxx/.gem/ruby/3.1.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:44:in `each'
        from /Users/xxxx/.gem/ruby/3.1.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:44:in `require'
        from /Users/xxxx/.gem/ruby/3.1.0/gems/bundler-2.3.5/lib/bundler.rb:176:in `require'
        from /Volumes/Macintosh HD - Data/xxxx/repos/project/projectrepo/config/application.rb:7:in `<top (required)>'
        from /Users/xxxx/.gem/ruby/3.1.0/gems/railties-7.0.1/lib/rails/commands/server/server_command.rb:137:in `require'
        from /Users/xxxx/.gem/ruby/3.1.0/gems/railties-7.0.1/lib/rails/commands/server/server_command.rb:137:in `block in perform'
        from <internal:kernel>:90:in `tap'
        from /Users/xxxx/.gem/ruby/3.1.0/gems/railties-7.0.1/lib/rails/commands/server/server_command.rb:134:in `perform'
        from /Users/xxxx/.gem/ruby/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /Users/xxxx/.gem/ruby/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/xxxx/.gem/ruby/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /Users/xxxx/.gem/ruby/3.1.0/gems/railties-7.0.1/lib/rails/command/base.rb:87:in `perform'
        from /Users/xxxx/.gem/ruby/3.1.0/gems/railties-7.0.1/lib/rails/command.rb:48:in `invoke'
        from /Users/xxxx/.gem/ruby/3.1.0/gems/railties-7.0.1/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by deivid-rodriguez** [comment] 2022-01-26 04:43
Hei, that sounds like some issue in your user code, we can't help there.

Regarding the binstubs, do you have any idea about how "rms_web_service" got there? Do you install this gem manually, or did you use to depend on it?

(I'm closing this, since the issue is solved and it's unclear whether it was originally caused by an issue in our software, but I'm happy to keep digging to find the culprit).

**Closed by deivid-rodriguez** 2022-01-26 04:43 UTC
Labels: RubyGems
