### ISSUE TITLE
Bundler 2.6.1 cannot install Bundler 2.5.14

### ISSUE THREAD

**Issue by alexreid** [rubygems/rubygems#8339] opened 2024-12-18 15:03 UTC
### Describe the problem as clearly as you can

Bundler 2.6.1 cannot install Bundler 2.5.14

### Post steps to reproduce the problem

(Tested on ruby 3.3.3 (2024-06-12 revision f1c7b6f435) [x86_64-linux] running on Linux kernel 6.10.14)

1. Install Bundler 2.6.1
2. Attempt to `bundle install` with a Gemfile.lock created using Bundler 2.5.14 

### Which command did you run?

`bundle install`

### What were you expecting to happen?

Bundler 2.6.1 to successfully install Bundler 2.5.14, then use Bundler 2.5.14 to install the gems in  the lockfile.

### What actually happened?

```
#29 2.493 Bundler 2.6.1 is running, but your lockfile was generated with 2.5.14. Installing Bundler 2.5.14 and restarting using that version.
#29 7.831 Fetching gem metadata from https://rubygems.org/.
#29 7.917 Fetching bundler 2.5.14
#29 8.201 Installing bundler 2.5.14
#29 8.488 /usr/local/rvm/gems/ruby-3.3.3/bin/ruby_executable_hooks:15:in `read': No such file or directory @ rb_sysopen - install (Errno::ENOENT)
#29 8.488       from /usr/local/rvm/gems/ruby-3.3.3/bin/ruby_executable_hooks:15:in `<main>'
#29 ERROR: process "/bin/sh -c gem install bundler && bundle install" did not complete successfully: exit code: 1
```

## Environment

```
Bundler             2.5.14
  Platforms         ruby, x86_64-linux
Ruby                3.3.3p89 (2024-06-12 revision f1c7b6f435f1167a0514b39a5f72f55cec4d1426) [x86_64-linux]
  Full Path         /usr/local/rvm/rubies/ruby-3.3.3/bin/ruby
  Config Dir        /usr/local/rvm/rubies/ruby-3.3.3/etc
RubyGems            3.5.11
  Gem Home          /usr/local/rvm/gems/ruby-3.3.3
  Gem Path          /usr/local/rvm/gems/ruby-3.3.3:/usr/local/rvm/rubies/ruby-3.3.3/lib/ruby/gems/3.3.0
  User Home         /root
  User Path         /root/.local/share/gem/ruby/3.3.0
  Bin Dir           /usr/local/rvm/gems/ruby-3.3.3/bin
Tools               
  Git               2.34.1
  RVM               not installed
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2024-06-21
Git SHA           72920bc230
Released Version  true
```

## Bundler settings

```
build.mysql2
  Set for your local app (/[redacted]/.bundle/config): "--with-openssl-dir=/usr/local/opt/openssl@1.1 --with-mysql-dir=/usr/local/opt/mysql@5.7"
```

### Gemfile

[Redacted]

### Gemfile.lock

[Redacted]

RUBY VERSION
   ruby 3.3.3p89

BUNDLED WITH
   2.5.14
```

**Comment by deivid-rodriguez** [comment] 2024-12-18 15:24
Yeah, `gem uninstall rubygems-bundler executable-hooks` should fix the problem.

**Comment by DBugger32** [comment] 2024-12-18 16:37
This started occurring yesterday in our builds -- don't think this is an rvm issue -- think it is an issue with bundler trying to reinstall another version.

**Comment by deivid-rodriguez** [comment] 2024-12-18 16:42
RVM specific gems like `rubygems-bundler` and similar are not really supported. The heavily hack into Bundler & RubyGems internals and have been abandoned for years. This issue comes up once in a while (not only when Bundler tries to install a different version of itself, but in other situations too), and it's always resolved by removing those gems.

**Comment by DBugger32** [comment] 2024-12-18 16:49
those gems are not installed

**Comment by DBugger32** [comment] 2024-12-18 17:04
It works when bundler is installed and version is unchanged, but only fails if bundler attempts to install another version -- a functionality that worked perfectly well before 2.6.0. Trying to understand how this relates to how ruby is installed.

**Comment by deivid-rodriguez** [comment] 2024-12-18 17:20
Well I have no idea how Bundler 2.6 could have changed anything here, but maybe it makes `rubygems-bundler` and friends patches behave even worse 🤷‍♂️. In any case, the solution is to remove those gems.

**Comment by deivid-rodriguez** [comment] 2024-12-18 17:34
No problem! Yeah, they need to be uninstalled in whatever environment it's running into the error.

Just to confirm, which version of Bundler do you have in your `Gemfile.lock` file? If you downgrade Bundler to a version different from that version in your `Gemfile.lock` file, but lower than Bundler 2.6.0, then installation of the locked version during `bundle install` works just fine?

**Comment by DBugger32** [comment] 2024-12-18 19:02
I support 20 ruby apps that are dockerized. I noticed the issue yesterday when trivial dependabot bumps (appsignal 4.2.2 to 4.2.3) started having image build failures in our CI.  The logs showed the reported error.

We have bundler versions between 2.3.x and 2.5.x in our gemfile.lock files.  Our docker builds do a 

```
gem update --system \
  && gem install bundler
```

before running `bundle install`.

Prior to yesterday morning we'd get...

```
Bundler 2.4.10 is running, but your lockfile was generated with 2.3.26. Installing Bundler 2.3.26 and restarting using that version.
08:14:35   #34 2.461 Fetching gem metadata from https://rubygems.org/.
08:14:35   #34 2.522 Fetching bundler 2.3.26
08:14:35   #34 2.652 Installing bundler 2.3.26
```
the new version of bundler would then happily run `bundle install`.

So yesterday morning, I went through our active apps and bundled all the gems with 2.6.0, and kicked off the builds. Since bundler didn't have to reinstall a version, everything worked...

...until today, when version 2.6.1 was installed in the container and the error returned because bundler had to install version 2.6.0.

I've reproduced it locally by uninstalling whatever older version of the bundler was used to make the gemfile.lock and get the error as now expected....

```
bundle install                  
Bundler 2.6.1 is running, but your lockfile was generated with 2.3.23. Installing Bundler 2.3.23 and restarting using that version.
Fetching gem metadata from https://rubygems.org/.
Fetching bundler 2.3.23
Installing bundler 2.3.23
/Users/blah/.rvm/gems/ruby-3.2.2/bin/ruby_executable_hooks:15:in `read': No such file or directory @ rb_sysopen - install (Errno::ENOENT)
	from /Users/blah/.rvm/gems/ruby-3.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

The interesting thing is, if I then rerun `bundle install` afterward -- it works without complaint.

So the install of the matching version is *mostly* working, however it does not work in the context of the original call as it once did.

I spent a little time trying to reproduce the reverse case starting with an older version of bundler -- but goodness bundler just wants to run with the latest version and using the _2.X.X_ command obviously defeats the purpose.

**Comment by deivid-rodriguez** [comment] 2024-12-18 19:13
Something I don't understand, if you're doing `gem update --system && gem install bundler` in your Dockerfile, it's strange that you were running `Bundler 2.4.10`, no? The previous latest version was 2.5.23.

According to your explanation, it could've been any change in between 2.4.10 and 2.6.0 that triggered this, right?

Did you try adding `gem uninstall rubygems-bundler gem-wrappers executable-hooks` to your Dockerfile? That should fix things.

I don't plan to add any changes to support these gems. Instead, I plan to move forward with https://github.com/rubygems/rubygems/pull/7752, since I think it's the same functionality these gems want to provide, and then ask RVM to stop installing these gems by default.

**Comment by DBugger32** [comment] 2024-12-18 19:20
I just pulled an old log file i had lying around for an example. 

This started breaking with 2.6.0.

Since it has been clear I have to live with the new normal -- I've updated our CI process to grab the bundler version from the gemfile.lock and pass it in as an argument to the docker build and just install the version I need.

gem update --system \
  && gem install bundler -v $BUNDLER_VERSION

**Comment by deivid-rodriguez** [comment] 2024-12-18 19:32
> I just pulled an old log file i had lying around for an example.

Ah, I see. Ok.

> I spent a little time trying to reproduce the reverse case starting with an older version of bundler -- but goodness bundler just wants to run with the latest version and using the 2.X.X command obviously defeats the purpose.

You could downgrade the latest version with `gem update --system 3.5.23 && gem uninstall bundler:2.6.0 bundler:2.6.1`.

> This started breaking with 2.6.0.

I totally believe you about Bundler 2.6.0 making this stop working, I just don't know how since I'm unfamiliar to how all these gems modify Bundler & RubyGems. It's surprising though, I wasn't expecting the kind of changes that went into this version to break things like this.

> I've updated our CI process to grab the bundler version from the gemfile.lock and pass it in as an argument to the docker build and just install the version I need.

Cool, that seems like it would work too. I still recommend to completely get rid of these gems, they have caused other issues in the past and are likely to break again.

**Comment by DBugger32** [comment] 2024-12-18 19:36
I am sure this not the last you are going to hear of this.

**Comment by deivid-rodriguez** [comment] 2024-12-18 19:39
@DBugger32 Thanks for willing to help reproduce this and providing feedback, I will try to reproduce this myself so I can at least better document this problem since I'm too curious now 😅!

> I am sure this not the last you are going to hear of this.

Most likely, we'll see!

**Comment by MikeMcQuaid** [comment] 2024-12-19 08:29
> This started breaking with 2.6.0.

Confirmed that we've been seeing this as well. As of Bundler 2.6.0 a manual `gem install bundler $VERSION` is required where previously it was automatically installed by Bundler itself.

We have the Bundler version in the Gemfile.lock and are not using RVM or another version manager and are able to reproduce this.

If it helps, binstubs are also failing like so:

```
To install the version of bundler this project requires, run `gem install bundler -v '~> 2.6'`
Activating bundler (~> 2.6) failed:
Could not find 'bundler' (~> 2.6) - did find: [bundler-2.5.23]
Checked in 'GEM_PATH=/home/runner/.local/share/gem/ruby/3.3.0:/home/linuxbrew/.linuxbrew/lib/ruby/gems/3.3.0:/home/linuxbrew/.linuxbrew/Cellar/ruby/3.3.6/lib/ruby/gems/3.3.0' , execute `gem env` for more information
```

Again, this was not required before Bundler 2.6.0.

**Comment by deivid-rodriguez** [comment] 2024-12-19 11:50
The backtrace shared by the OP specifically includes RVM specific binstubs, why do you think it's the same issue @MikeMcQuaid? Can you share the error that you are getting?

**Comment by deivid-rodriguez** [comment] 2024-12-19 13:15
Ok, so I managed to reproduce the issue, at least the one related to RVM executable hooks. The problem is indeed introduced by https://github.com/rubygems/rubygems/pull/8320.

The problem is executable hooks consume the original ARGV and replace `$0` with the first program argument. After #8320, when we re-exec we run this "executable hook script" again (because of using `Process.argv` instead of `$0`), but `ARGV` has already been process, so the first original argument (that included the bundler binstub itself) is lost.

Previously, the new value of `$0` after executable hooks reassigned it would be the bundler binstub, and re-exec'ing would just work.

In order to fix this we could try checking which one of `Process.argv` or `$0` is the bundler binstub and re-exec using that. However, this makes me think whether https://github.com/rubygems/rubygems/pull/8320 makes sense at all. If you re-assign `$0`, I think it's fair to assume that re-executions will use the re-assigned script.

According to https://github.com/phusion/passenger/issues/2577#issuecomment-2525105583, Passenger actually re-assigns `$0` to "Passenger AppPreloader: /path-to-app" just for display purposes, so that `ps` shows something more meaningful.

I think this confirms https://github.com/rubygems/rubygems/pull/8320 is not a good change. Instead, Passenger should use [Process.setproctitle](https://rubyapi.org/3.3/o/process#method-c-setproctitle) for this.

So I think the best course of action is to revert #8320, also because there may be other issues with it according to @MikeMcQuaid's report. I'll summon @CamJN and @FooBarWidget though for awareness and to confirm this makes sense to them.

**Comment by deivid-rodriguez** [comment] 2024-12-19 16:19
@MikeMcQuaid I believe your issue should not be the same because in your case Bundler is not even getting loaded, so I don't think any fix in Bundler will make a difference.

I suspect your issue has always existed, but was just triggered by releasing a new minor version of Bundler. When your were on 2.5.x, even if your lockfile had a higher version that the one you had installed (say Gemfile locked to 2.5.23 and 2.5.22 being installed), then the bundler binstub that's throwing an error now would activate Bundler just fine because both version match `~> 2.5` which is what the binstub would try to activate.

Nowadays I don't think there's any reason for `bundle binstubs` generate a binstub for Bundler itself because all supported RubyGems versions have builtin support for activating the proper version of Bundler. If you remove the `bin/bundler` script, does that fix the error?

**Comment by CamJN** [comment] 2024-12-19 20:18
I would caution against relying on a process' arguments after there's been any chance to manipulate them, in my experience it's not that uncommon for people to do so, especially people with any systems administration background. It seems that `Process.argv0` giving an absolute path to the script is problematic in some cases, perhaps Bundler would prefer to strip the path off? Then it would more closely resemble what `$0` would provide if it weren't reassigned, but retain the benefit of being safe from user's manipulations.

**Comment by deivid-rodriguez** [comment] 2024-12-19 20:34
> I would caution against relying on a process' arguments after there's been any chance to manipulate them, in my experience it's not that uncommon for people to do so, especially people with any systems administration background.

In the case of `executable-hooks`, I feel it intends for everything to rely on the replaced `$0`. Basically it replaces the shebang in all binstubs to `#!/usr/bin/env ruby_executable_hooks`, then in that script it "does its thing" (I think requiring `bundler/setup` under the hood), replaces `$0` with the binstub is supposed to be running, and then loads the binstub. From then on, its intention is that things are equivalent to having run the binstub with a ruby shebang directly. That's why re-execing with `$0` just works, but `Process.argv` breaks.

>  It seems that Process.argv0 giving an absolute path to the script is problematic in some cases, perhaps Bundler would prefer to strip the path off? Then it would more closely resemble what $0 would provide if it weren't reassigned, but retain the benefit of being safe from user's manipulations.

I don't think the problem is whether `Process.argv0` gives an absolute or a relative path. The problem is that in the case of this issue it contains the `ruby_executable_hooks` script, and the original `ARGV` which contains the actual script has been lost when we re-exec, because it has been modified [here](https://github.com/rvm/executable-hooks/blob/db8ab2655f16a734c65ab2927aa2a52ae257929b/bin/ruby_executable_hooks#L4).

Unfortunately I can't think of a good way to fix this rather than reverting... and I honestly believe it'd be better if passenger uses `Process.setproctitle` to improve `ps` output since that seems to be its exact use case.

**Comment by CamJN** [comment] 2024-12-19 21:32
`Process.setproctitle` does seem safer for Passenger, and I imagine I can get us switched over to it, and we can stop caring about all of this.

However, I think you kinda make my point about relying on the arguments of a process that's had any chance to modify them, which is to say that they are extremely flakey and prone to being manipulated in surprising ways, that break things. Posix allows this, unix-like OSs allow this, and Ruby allows this, I think  Bundler is asking a lot to expect everyone to not touch the process' arguments, or to always have the arguments in a state that bundler can exec, and I think that expectation will be subverted on a periodic basis going forward, causing a lot of headaches.

**Comment by MikeMcQuaid** [comment] 2024-12-20 08:31
> Nowadays I don't think there's any reason for `bundle binstubs` generate a binstub for Bundler itself because all supported RubyGems versions have builtin support for activating the proper version of Bundler. If you remove the `bin/bundler` script, does that fix the error?

@deivid-rodriguez It does, thanks for the help and sorry for the off-topic distraction! I'd like to gently suggest a feature request for a better error message here and/or for `bundle` to refuse to create/use its own binstubs if this is known to no longer work. Thanks again, unsubscribing for now!

**Comment by deivid-rodriguez** [comment] 2024-12-20 12:09
> However, I think you kinda make my point about relying on the arguments of a process that's had any chance to modify them, which is to say that they are extremely flakey and prone to being manipulated in surprising ways, that break things. Posix allows this, unix-like OSs allow this, and Ruby allows this, I think Bundler is asking a lot to expect everyone to not touch the process' arguments, or to always have the arguments in a state that bundler can exec, and I think that expectation will be subverted on a periodic basis going forward, causing a lot of headaches.

Any specific suggestions about what we should do? I was thinking maybe we can use `$0` unless it's not an actual file, otherwise fallback to `Process.argv0`.

This feature is definitely not perfect, but it's been in place for two years, and while there have been issues, I'd say it works reasonably well. Maybe if Ruby introduced something like `Process.argv` similar to `Process.argv0` we could do better but it is what it is now...

**Comment by deivid-rodriguez** [comment] 2024-12-20 13:33
@MikeMcQuaid I proposed to stop generating Bundler binstubs at https://github.com/rubygems/rubygems/pull/8345.

@CamJN I proposed a small modification of your `Process.argv0` patch to play nice with more common cases at https://github.com/rubygems/rubygems/pull/8343. I still suggest that passsenger switches to `Process.setproctitle` though!

**Closed** 2024-12-20 19:42 UTC
Labels: Bundler
